### ISSUE TITLE
Make registration of JacksonMessageBodyProvider optional

### ISSUE THREAD

**Issue by karel1980** [dropwizard/dropwizard#1005]
see AbstractServerFactory.createAppServlet:
jersey.register(new JacksonMessageBodyProvider(objectMapper, validator))

Problem description: (I noticed this during migration from 0.7.1 to 0.8.1)
Given:
- an entity class without a default constructor
- a method @POST + @Consumes("application/json) which takes an instance of the entity class.
- A custom MessageBodyReader for deserializing the class.
  When you post json to the given resource method you can get errors because JacksonMessageBodyProvider is consulted before my own messagebodyreader.

Notes:
- In my environment this manifests itself as a heisenbug: when I debug an integration test exposing this problem I often end up in my own MessageBodyReader (depending on where  I installed breakpoints). Presumably it's related to timing, but I have yet to pin it down.
- One could create a custom ServerFactory which extends DefaultServerFactory and overrides AbstractServerFactory.createAppServlet, but that method calls private methods and I would have to end up copying almost everything.
- IIUC I may be able to work around this using @JsonIgnoreType
- There are other providers being registered at AbstractServerFactory.createAppServlet, one might want to make these optional as well.

**Comment by karel1980** [comment]
Update:
- The order in which the MessageBodyReaders are attempted depends (in my case) on the result of Providers.getCustomProviders(locator, MessageBodyReader.class) in MessageBodyFormat, which takes down the hk2 rabbit hole. A place I'm not willing to visit right now, because
- Using the JsonIgnoreType annotation does indeed help (but it may not for others who don't want to, or are unable to add the jackson-annotations dependency)

**Comment by ptomli** [comment]
This also gets into the way of using Jersey [Entity Data Filtering](https://jersey.java.net/documentation/latest/entity-filtering.html). 

Basically, `JacksonMessageBodyProvider` extends `JacksonJaxbJsonProvider`, but the Jackson entity data filtering support is provided through `org.glassfish.jersey.media:jersey-media-json-jackson`, specifically `FilteringJacksonJaxbJsonProvider`. As a result, the entity filtering cannot occur.

I have a [StackOverflow question](http://stackoverflow.com/questions/31338758/how-to-implement-request-scoped-jackson-filterprovider-in-dropwizard) relating to this.

**Comment by jplock** [comment]
Is this still an issue after https://github.com/dropwizard/dropwizard/pull/1251 was merged?
