### ISSUE TITLE
formatting dates in serialized json

### ISSUE THREAD

**Issue by qmnonic** [dropwizard/dropwizard#1008]
Maybe I'm missing something, but I can't figure out how to change how dates (java.util.Date) are serialized into json.  Currently, it's output as YYYY-MM-DD in all json output.

I tried updating the object mapper, but no luck?

```
    public void run(AppConfiguration config, Environment environment) throws ClassNotFoundException {
    	// doesn't work
    	//environment.getObjectMapper().setDateFormat(new SimpleDateFormat("yyyy-MM-dd'T'HH:mm:ss.SSSZ"));
    	// doesn't work
    	// environment.getObjectMapper().setDateFormat(ISO8601DateFormat.getInstance());
    	// doesn't work
        // doesn't work
      //environment.getObjectMapper().configure(SerializationFeature.WRITE_DATES_AS_TIMESTAMPS, true);
```

I'm using dropwizard 0.8.1.

**Comment by carlo-rtr** [comment]
This code below ran against master and produced:
```
{
myDate: "2015-04-23T13:37:31.994+0000"
}
```


diff --git a/dropwizard-example/src/main/java/com/example/helloworld/HelloWorldApplication.java b/dropwizard-example/src/main/java/com/example/helloworld/HelloWorldApplication.java
index 3d9cea3..0cb52be 100644
--- a/dropwizard-example/src/main/java/com/example/helloworld/HelloWorldApplication.java
+++ b/dropwizard-example/src/main/java/com/example/helloworld/HelloWorldApplication.java
@@ -8,12 +8,8 @@ import com.example.helloworld.core.User;
 import com.example.helloworld.db.PersonDAO;
 import com.example.helloworld.filter.DateRequiredFeature;
 import com.example.helloworld.health.TemplateHealthCheck;
-import com.example.helloworld.resources.FilteredResource;
-import com.example.helloworld.resources.HelloWorldResource;
-import com.example.helloworld.resources.PeopleResource;
-import com.example.helloworld.resources.PersonResource;
-import com.example.helloworld.resources.ProtectedResource;
-import com.example.helloworld.resources.ViewResource;
+import com.example.helloworld.resources.*;
+import com.fasterxml.jackson.databind.SerializationFeature;
 import com.google.common.base.Function;
 import io.dropwizard.Application;
 import io.dropwizard.assets.AssetsBundle;
@@ -81,6 +77,7 @@ public class HelloWorldApplication extends Application<HelloWorldConfiguration>
 
     @Override
     public void run(HelloWorldConfiguration configuration, Environment environment) {
+        environment.getObjectMapper().disable(SerializationFeature.WRITE_DATES_AS_TIMESTAMPS);
         final PersonDAO dao = new PersonDAO(hibernateBundle.getSessionFactory());
         final Template template = configuration.buildTemplate();
 
@@ -97,6 +94,7 @@ public class HelloWorldApplication extends Application<HelloWorldConfiguration>
         environment.jersey().register(new HelloWorldResource(template));
         environment.jersey().register(new ViewResource());
         environment.jersey().register(new ProtectedResource());
+        environment.jersey().register(new DateResource());
         environment.jersey().register(new PeopleResource(dao));
         environment.jersey().register(new PersonResource(dao));
         environment.jersey().register(new FilteredResource());
@@ -132,3 +130,4 @@ public class HelloWorldApplication extends Application<HelloWorldConfiguration>
         };
     }
 }
+
diff --git a/dropwizard-example/src/main/java/com/example/helloworld/core/ModelWithDate.java b/dropwizard-example/src/main/java/com/example/helloworld/core/ModelWithDate.java
new file mode 100644
index 0000000..c8bcfa2
--- /dev/null
+++ b/dropwizard-example/src/main/java/com/example/helloworld/core/ModelWithDate.java
@@ -0,0 +1,26 @@
+package com.example.helloworld.core;
+
+import com.fasterxml.jackson.annotation.JsonProperty;
+
+import java.util.Date;
+
+public class ModelWithDate {
+    @JsonProperty
+    private Date myDate;
+
+    public Date getMyDate() {
+        return myDate;
+    }
+
+    public void setMyDate(Date myDate) {
+        this.myDate = myDate;
+    }
+
+    public ModelWithDate() {
+
+    }
+
+    public ModelWithDate(Date myDate) {
+        this.myDate = myDate;
+    }
+}
diff --git a/dropwizard-example/src/main/java/com/example/helloworld/resources/DateResource.java b/dropwizard-example/src/main/java/com/example/helloworld/resources/DateResource.java
new file mode 100644
index 0000000..471f81f
--- /dev/null
+++ b/dropwizard-example/src/main/java/com/example/helloworld/resources/DateResource.java
@@ -0,0 +1,18 @@
+package com.example.helloworld.resources;
+
+import com.example.helloworld.core.ModelWithDate;
+
+import javax.ws.rs.GET;
+import javax.ws.rs.Path;
+import javax.ws.rs.Produces;
+import java.util.Date;
+
+@Path("dates")
+@Produces("application/json")
+public class DateResource {
+    @GET
+    public ModelWithDate getModel() {
+        ModelWithDate modelWithDate = new ModelWithDate(new Date());
+        return modelWithDate;
+    }
+}
