### ISSUE TITLE
JerseyClientBuilder with MultiPartFeature causes HTTP 400 Bad Request with org.jvnet.mimepull.MIMEParsingException: Missing start boundary.

### ISSUE THREAD

**Issue by young-druid** [dropwizard/dropwizard#1013]
Defect is briefly described in a subject.
Please, find a project by this [link](https://drive.google.com/file/d/0B55JU7RHUffndGVGX29pZkpQUjA/view?usp=sharing) where after running an integration test you can see that JerseyClientBuilder (with Apache client inside I think) causes HTTP 400 when uploading a multipart form but default Jersey client works fine.
It can be related to a problem described [here](https://jersey.java.net/documentation/latest/client.html#connectors.warning).

**Comment by arteam** [comment]
Please, disable a chunked encoding for the Jersey Client
````java
JerseyClientConfiguration configuration = new JerseyClientConfiguration();
configuration.setChunkedEncodingEnabled(false);
Client client = new JerseyClientBuilder(RULE.getEnvironment())
           .using(configuration)
           .build("test-client");
````
or change the YML [configuration file](http://www.dropwizard.io/manual/configuration.html#jerseyclient)

If the transfer encoding is chunked, then the server doesn't know a boundary, so it can't correctly split the attached data from the base message.

**Comment by young-druid** [comment]
Thanks a lot for explanation. It is not a dropwizard's issue at all.

**Comment by cccmpuser** [comment]
Did you find solution for this issue? It happens only in IE for me.
