### ISSUE TITLE
ErrorMessage serialization

### ISSUE THREAD

**Issue by scho** [dropwizard/dropwizard#1019]
Hi,

in our project we configured the `ObjectMapper` in that manner, that we have to annotate getters/setters or fields with `@JsonProperty` explicitly. Usually dropwizard does the same, except for the `ErrorMessage` class. In our project serialized error messages result in `{}`.

I'd like to annotate the getters with `@JsonProperty`. If you guys agree with this approach I'll send a PR.

Cheers
Georg

**Comment by joschi** [comment]
Thanks for the pointer. I just added the missing `@JsonProperty` annotations to the getters in `ErrorMessage`.

**Comment by scho** [comment]
That was FAST. Thanks!
