### ISSUE TITLE
DropwizardAppRule handling lifecycle of Jersey Client's ExecutorService when injected from another HK2 ServiceLocator

### ISSUE THREAD

**Issue by natnan** [dropwizard/dropwizard#1026]
Gosh, that's impossible to set a proper title to explain this..

As I was trying to fix #862, I came across a couple of solutions in [this Stackoverflow Question](http://stackoverflow.com/questions/23224234/how-can-i-cleanly-override-the-default-servicelocator-used-by-jersey). Unfortunately, my `DropwizardAppRule` tests that involve jersey client making async calls started to fail with the following stacktrace:

```
java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.FutureTask@3f3bdbb9 rejected from java.util.concurrent.ThreadPoolExecutor@7a39523a[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 1]
! at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2047) ~[na:1.8.0_25]
! at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:823) ~[na:1.8.0_25]
! at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1369) ~[na:1.8.0_25]
! at java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:112) ~[na:1.8.0_25]
! at org.glassfish.jersey.client.ClientRuntime.submit(ClientRuntime.java:197) ~[jersey-client-2.17.jar:na]
! at org.glassfish.jersey.client.ClientRuntime.submit(ClientRuntime.java:141) ~[jersey-client-2.17.jar:na]
! at org.glassfish.jersey.client.JerseyInvocation.submit(JerseyInvocation.java:723) ~[jersey-client-2.17.jar:na]
! at org.glassfish.jersey.client.JerseyInvocation$AsyncInvoker.method(JerseyInvocation.java:602) ~[jersey-client-2.17.jar:na]
! at org.glassfish.jersey.client.JerseyInvocation$AsyncInvoker.get(JerseyInvocation.java:471) ~[jersey-client-2.17.jar:na]
.....
```

The first test in the class doesn't produce this, but the following ones do. This doesn't occur when I use `environment.jersey().register(new AbstractBinder(){...})` but only occurs when I overwrite `ServletContext`s `SERVICE_LOCATOR` attribute or bridge my own `ServiceLocator` to jersey's. 

It's very difficult for me to explain the whole thing because it involves too many actors. So I've created a simple test project at https://github.com/natnan/dropwizard-executor-test which should explain it better.

I've tried going into TestSupport code, and debug it to find the difference between two approaches but couldn't find anything.

**Comment by natnan** [comment]
It was my misunderstanding of `HK2 ServiceLocator`.

So, in my application class I create a `ServiceLocator` as following:
```java
    final Client jersey = new JerseyClientBuilder(environment).using(configuration.getJersey()).build("jersey");

    ServiceLocator locator = ServiceLocatorUtilities.bind(new AbstractBinder() {
      @Override
      protected void configure() {
        bind(jersey).to(Client.class);
      }
    });
```

Turns out, if you don't give a name to `bind` method, it uses a default name and if that name already exists, it simply returns the old locator. So when I run multiple tests using `DropwizardAppRule` in one JVM, the same locator is used again and again and that returns a closed `Jersey Client` after the first run. Simply changing it to 

```java
   ServiceLocator locator = ServiceLocatorUtilities.bind(UUID.randomUUID().toString(), new AbstractBinder() {
      @Override
      protected void configure() {
        bind(jersey).to(Client.class);
      }
    });
```

fixed it.

**Comment by carlo-rtr** [comment]
Thanks for sharing
