### ISSUE TITLE
Supporting JSR 356, Java API for WebSocket

### ISSUE THREAD

**Issue by TomCools** [dropwizard/dropwizard#1029]
When improving my Java-skills, I decided I wanted to give the JavaEE7 Websocket API a test-drive. It's very easy to work with and it's just as simple as writing a Servlet or REST-API. Unfortunatly, I could not find the support for this JSR 356 anywhere in Dropwizard.

We are using a Jetty version that supports the new JSR introduced in JavaEE7. Yet, for now, it is not possible to add a WebSocket-class to the Jetty server through the current Dropwizard API.

I have already started to work on this and am almost finished... mostly because I wanted to dive into the Dropwizard sourcecode. However, I read that it was better to open an issue before I make a pull-request... so here i am :-).

Do you think this functionality is something you would want in Dropwizard?

**Comment by joschi** [comment]
If possible at all without modifying the core of Dropwizard, it would be great if you could publish your project as a 3rd party extension (and add it to http://modules.dropwizard.io/).

**Comment by TomCools** [comment]
Great Idea. I'll rework what I have and push it as a Module once i got everything working. :-).

**Comment by yunspace** [comment]
@TomCools Not sure why you mentioned it's not possible to add WebSocket to embedded Jetty. 

In their official repo there exists examples for both Native and JSR356 implementations: https://github.com/jetty-project/embedded-jetty-websocket-examples which may be good reference material

**Comment by TomCools** [comment]
@yunspace I read that page and I know it is possible in Jetty. What I meant with the lines " Yet, for now, it is not possible to add a WebSocket-class to the embedded Jetty." is that it is not possible to add a websocket on Jetty through te current Dropwizard API. environment.servlets() (which is basically the Jetty Environment) does not contain any method to enable this.

I am currently making a Bundle myself to integrate a way to add Websockets easily using the current core configuration.

**Comment by TomCools** [comment]
I have finished my Bundle project and it is available as a 3th party module:
http://modules.dropwizard.io/thirdparty/    -> dropwizard-websocket-jee7

**Comment by joschi** [comment]
@TomCools Awesome! Thanks for the update!

**Comment by yunspace** [comment]
nice @TomCools, seen alot of DW with native jetty websocket implementations but this is first I've seen using JSR 356. Very useful. Starred and forked.
