### ISSUE TITLE
On demand initialization of database connection pools

### ISSUE THREAD

**Issue by tblasche** [dropwizard/dropwizard#1037]
I'm currently facing the problem that DW fails to start when there are unreachable databases configured as data sources.

On startup process, DW tries to init the connection pools for all configured data sources. If there is e.g. an unreachable database configured, DW will fail to start with an exception.

**Desirable behaviour:**
DW starts even if there are connection pools which could not be set up. Everytime the application tries to borrow a connection from the connection pool, DW retries to init this connection pool.
Even better: Connection pools are just tried to be initialized when they are used for the first time (i.e. kind of lazy initialization; also can help saving resources).

**Background:**
If e.g. a non-critical database is down in production environment which is only required by let's say 1 of 10 resources, I want DW to start properly so I can use 9 of 10 resources correctly and only requests to the one resource which requires the down database will fail.

**Comment by arienkock** [comment]
I suspect an easy way to support this is to allow the initialSize property of the DatasourceFactory to be 0. During startup the connection pool initializes (in my version this happens at `org.apache.tomcat.jdbc.pool.ConnectionPool.init(ConnectionPool.java:464) [tomcat-jdbc-8.0.28.jar:na]`) and that wouldn't happen if the initial size was 0.
