### ISSUE TITLE
0.8+ with Jersey 1.x

### ISSUE THREAD

**Issue by ghenkes** [dropwizard/dropwizard#1038]
I have an existing 3rd party servlet that is using Jersey 1.x that I would like to add in to my Dropwizard app. I’d like to stay current with Dropwizard (0.8+); however it currently uses Jersey 2.x. We have Jersey 1 transitive dependencies of existing projects that we utilize, making it difficult for us to use the latest versions of Dropwiazard (since we can’t uplift all of these dependencies yet).

In order to get this to work I managed the version of dropwizard-jersey to 0.7.1, as it still uses Jersey 1 and made a couple tweaks to dropwizard-core and dropwizard-jersey. Reading https://github.com/dropwizard/dropwizard/issues/934 and [here](https://groups.google.com/forum/#!topic/dropwizard-dev/VInOW_ebiAc) it sounds like the Jersey upgrade has caused other users problems when upgrading as well. Is there interest in having a dropwizard-jersey1 module included so consumers of dropwizard-core can choose which jersey version to use? If so, I'll contribute that and the changes needed in dropwizard-core and dropwizard-jersey.

**Comment by cchesser** [comment]
+1 for offering a compatibility module for consumers to stay current with dropwizard, but allow migration from Jersey 1 to 2 (as this can be quite painful for service assembly owners). It would be nice to achieve this vs. pinning to dropwizard to 0.7.1 for the interim.

Perhaps naming could be dropwizard-jersey-glassfish (2) or dropwizard-jersey-sun (1. Or just keeping dropwizard-jersey and a dropwizard-jersey-compat /  dropwizard-jersey-legacy module.

[Migrating from Jersey 1.x to 2.0](https://jersey.java.net/documentation/latest/migration.html#mig-1.x)

**Comment by joschi** [comment]
To be honest, I don't think this will happen anytime soon if at all.

There are basically a gazillion dependencies on Jersey 2 in Dropwizard, e. g. dropwizard-auth, dropwizard-client, dropwizard-core, dropwizard-jersey (obviously), dropwizard-forms, dropwizard-hibernate, dropwizard-jdbi, and dropwizard-testing all depend on classes provided by Jersey 2. So in the end it would either lead to a complete fork of Dropwizard or a impenetrable pile of dependencies like dropwizard-auth-jersey1/dropwizard-auth-jersey2 etc.

**Comment by ghenkes** [comment]
@joschi Thanks for the reply. Yeah, I saw Jersey all over in the code. For my purposes I really only needed dropwizard-core and it's almost free of direct Jersey dependencies. There's just [one direct dependency dropwizard-core has on Jersey](https://www.google.com/url?q=https%3A%2F%2Fgithub.com%2Fdropwizard%2Fdropwizard%2Fblob%2Fmaster%2Fdropwizard-core%2Fsrc%2Fmain%2Fjava%2Fio%2Fdropwizard%2Fsetup%2FEnvironment.java%23L79&sa=D&sntz=1&usg=AFQjCNHshJoSqo9f52CxQJws3Ct8igJHXg). (And [one unused import](https://github.com/dropwizard/dropwizard/blob/master/dropwizard-core/src/main/java/io/dropwizard/server/AbstractServerFactory.java#L21).)

What are your thoughts on adding a way to get a ServletContainer from dropwizard-jersey, so there's an abstraction between dropwizard-core and Jersey. Then consumers would be able to add their own drop-in implementation of dropwizard-jersey via dependency management. It doesn't solve the Jersey problem for all dropwizard modules, but it would at least allow consumers to run a barebones dropwizard service.

**Comment by joschi** [comment]
> What are your thoughts on adding a way to get a ServletContainer from dropwizard-jersey, so there's an abstraction between dropwizard-core and Jersey.

If you manage to do it in a backward-compatible* way, you've got my vote.

*: Backward-compatible to Dropwizard 0.8.x.

**Comment by ghenkes** [comment]
@joschi Here's the code for what I'm proposing. I can open a pull request if it's easier to review there.

Add the following to dropwizard-jersey
```java
/**
 * Extends {@link ServletContainer} to provide consumers of dropwizard-jersey a means of obtaining a ServletContainer
 * without directly depending on Jersey.
 */
public class JerseyServletContainer extends ServletContainer {

    private static final long serialVersionUID = 8217023192775181696L;

    /**
     * Create Jersey Servlet container.
     */
    public JerseyServletContainer() {
    }

    /**
     * Create Jersey Servlet container.
     * @param resourceConfig container configuration.
     */
    public JerseyServletContainer(final ResourceConfig resourceConfig) {
        super(resourceConfig);
    }
}
```

Then in dropwizard-core's Environment change line [79](https://github.com/dropwizard/dropwizard/blob/master/dropwizard-core/src/main/java/io/dropwizard/setup/Environment.java#L79) to:
```java
this.jerseyServletContainer = new JerseyContainerHolder(new JerseyServletContainer(jerseyConfig));
```
