### ISSUE TITLE
Would it be possible to relax the final constraint on ConfiguredCommand?

### ISSUE THREAD

**Issue by mikeycmccarthy** [dropwizard/dropwizard#1045]
We're doing some work that means it would be really helpful to be able to extend ConfiguredCommand, specifically to override the run method without having to create an entire copy of the class. Would there be any objections to removing the final modifier on this run method?

https://github.com/dropwizard/dropwizard/blob/2655ac703a0f6ddb4eae933a74dae3d12fde287f/dropwizard-core/src/main/java/io/dropwizard/cli/ConfiguredCommand.java#L60-L82

Thanks

**Comment by arteam** [comment]
I think it's justified. Pushed a fix to master.

**Comment by mikeycmccarthy** [comment]
Many thanks, much appreciated!
