### ISSUE TITLE
Allow "either-or" authentication methods for resources

### ISSUE THREAD

**Issue by alph486** [dropwizard/dropwizard#1050]
This is more of a question about functionality:

Right now one can implement a ChainedAuthenticationFactory and have *all* of the auth methods apply. In order to get different authentication behavior for different resources, I guess I would need to break out the resources requiring separate authentication methods into a separate service.

My situation, where I believe it would be necessary, is in my OAuth 2.0 based services, my authorization service is in the same deployable artifact as the other resources that will use the tokens vended by it. A user would call /auth/token with Basic Auth and then call /users with Bearer Token auth.

Any issue with this idea? Is there a way to do this already I'm not aware of?

**Comment by vvondra** [comment]
@alph486 we're exactly hitting the OAuth token case. What was the path you chose to go?

Not being able to configure the AuthenticationFactory per resource seems like a big limitation to us.

**Comment by alph486** [comment]
Hi @vvondra , I ended up reorganizing my services to enable different authentication for my token resources. In other words, the auth service is now a different service/deployable artifact altogether.

**Comment by shtratos** [comment]
@alph486 I wonder if polymorphic principal would solve your case: https://github.com/dropwizard/dropwizard/issues/1318

**Comment by alph486** [comment]
@shtratos Thanks. In truth, I've since moved on from this project, but good suggestion.

**Comment by jplock** [comment]
Going to close this out as the creator has moved on and #1318 has been merged.
