### ISSUE TITLE
Allow for RolesAllowed annotation on classes

### ISSUE THREAD

**Issue by tocr** [dropwizard/dropwizard#1054]
Currently, the `AuthDynamicFeature` checks `@RolesAllowed` annotation only on method level.
This prevents creating class level annotations on resources.

Expected behavior:
Check also for the annotation on resource class and register the authentication filter in case the annotation is found

Proposed code:
````java
public class AuthDynamicFeature implements DynamicFeature {
    private ContainerRequestFilter authFilter;
    public AuthDynamicFeature(ContainerRequestFilter authFilter) {
        this.authFilter = authFilter;
    }
  
    @Override
    public void configure(ResourceInfo resourceInfo, FeatureContext context) {
        //get the RolesAllowed on the class level
        RolesAllowed ra = resourceInfo.getResourceClass().getAnnotation(RolesAllowed.class);

        AnnotatedMethod am = new AnnotatedMethod(resourceInfo.getResourceMethod());
        if(ra != null || am.isAnnotationPresent(RolesAllowed.class) || am.isAnnotationPresent(DenyAll.class)) {
            context.register(authFilter);
        }
    }
}
````

**Comment by PixelBumper** [comment]
+1 definitely a show stopper for us

**Comment by jplock** [comment]
Would you mind submitting a pull request to implement this improvement?

**Comment by tocr** [comment]
Surely I can submit a PR. Give me a few days please.

**Comment by tocr** [comment]
I have submitted a PR #1437 regarding this

**Comment by patrox** [comment]
@jplock I believe that this has been addressed in: https://github.com/dropwizard/dropwizard/pull/1437 and it can be closed.
