### ISSUE TITLE
Serving static content with AssetsBundle doesn't work in 0.8.1

### ISSUE THREAD

**Issue by rskokan** [dropwizard/dropwizard#1059]
I have a REST API app and now I am trying to add also some static content.

I follow https://dropwizard.github.io/dropwizard/manual/core.html, "Bundles" section.
- I created "assets" folder under /src/main/resources with an index.html file
- edited config file, added

    server:
        type: simple
        rootPath: /app/*

- added "bootstrap.addBundle(new AssetsBundle("/assets", "/", "index.html"));" to initialize()
==> result:
- the app starts
- endpoints registered, e.g. "GET     /app/hello-world"
- attempt to access /app/hello-world: 404
- attempt to access /app: 404
- attempt to access /: 404

Simply nothing can be used

I also tried not to change anything in the config, only register jersey at e.g. /app/* as described in http://spin.atomicobject.com/2014/10/11/serving-static-assets-with-dropwizard/: the the app didn't start, URL conflict.

**Comment by patricioe** [comment]
+1 on this issue.

**Comment by joschi** [comment]
@rskokan You're using the "simple" server connector which automatically sets the application context path to `/application` (see http://www.dropwizard.io/0.8.1/docs/manual/configuration.html#simple). Together with a `rootPath` of `/app/*` the complete path to your JAX-RS resources is `/application/app`, e. g. `/application/app/hello-world`. The assets should be available at `/application`, e. g. `/application/index.html`.
