### ISSUE TITLE
Require JDK 8

### ISSUE THREAD

**Issue by cemo** [dropwizard/dropwizard#1060]
I have seen https://github.com/dropwizard/dropwizard-java8 this project recently and thought why there is such a project. One of the core values Dropwizard brings is security. Given that the end of public updates of Java 7 has been announced, supporting a publicly not updated version of Java is not necessary.

I am in favor of supporting JDK8 as a minimum version and bring all nice features implemented by @joschi and JDK8 features into directly Dropwizard.

**Comment by rondagostino** [comment]
To some degree that makes sense in theory, but the reality is that many people will be using JRE 1.7 for a while.  Corporate customers often purchase extended support to receive security updates long after the public end-of-life date.  I'm not arguing the wisdom -- just the reality.  I would prefer to see JRE 1.7 supported for a while longer -- perhaps until Java 9 becomes available in 2016.

Ron

**Comment by carlo-rtr** [comment]
This was discussed on the dev mailing list a while back. We are leaning towards what @rondagostino said.

https://groups.google.com/forum/#!topic/dropwizard-dev/k1Gf38ekDZM

**Comment by carlo-rtr** [comment]
btw, duplicate of #962
