### ISSUE TITLE
"No session currently bound to execution context" error when configuring multiple data sources

### ISSUE THREAD

**Issue by cbehrends** [dropwizard/dropwizard#1076]
I"m upgrading one of our internal apps to 0.8.1which connects to several data bases.  After the upgrade, we started getting "No session currently bound to execution context" when we attempt to connect to additional databases.  The first one will work, all others fail.  

I'm still wrapping my head around DW's internals, but i think the issue may lie with the UnitOfWorkApplicationListener.  Per the code notes, UnitOfWorkApplicationListener is registered as a singleton with Jersey.  I think DW is creating a UnitOfWorkApplicationListener per DataSourceFactory and thus attempting to add a second singleton of UnitOfWorkApplicationListener into Jersey.  Here is a gist showing this behavior.  

https://gist.github.com/cbehrends/08caebdb747e1f7e8a31
and another showing the same test passing in 0.7.1
https://gist.github.com/cbehrends/e3717140a52b4f7d78ff

I've noticed that when my app loads I get the the following warning.   

WARN  [2015-05-25 15:50:20,443] org.glassfish.jersey.internal.Errors: The following warnings have been detected: WARNING: Cannot create new registration for component type class io.dropwizard.hibernate.UnitOfWorkApplicationListener: Existing previous registration found for the type.

If you think I'm on the right track here, I'd be more than happy to submit a patch.  Any guidance would be appreciated.

**Comment by cbehrends** [comment]
I've actually refactored my services so that I no longer require multiple datasources.  If you think this is something worth fixing I'd still be willing to pitch in and take a look shot at it.

**Comment by FMPAR** [comment]
I've just encountered this issue as well, I've dropped down to 0.7.1 for now. Any chance on a fix for this in a future version?

**Comment by arteam** [comment]
Support for several data sources/Hibenate bundles was contributed in #1276.
