### ISSUE TITLE
Add option to disable collecting counter metrics for paths ending in forward slash

### ISSUE THREAD

**Issue by peterdmello** [dropwizard/dropwizard#1078]
In most (possibly all) REST applications, the following two URL's hit the same endpoint: `http://localhost:8080/myapp/v1/persons` and `http://localhost:8080/myapp/v1/persons/`. However, the counter metrics generated for the two are distinct `counter.status.200.v1.persons.count` and `counter.status.200.v1.persons.root.count`. There should be a way to prevent the `.root.count` metric from being created. I'm using the GraphiteReporter in my app.

**Comment by cbehrends** [comment]
I think the reason it get's registered twice has less to do with DW and more to do with how the HTTP spec works.  When you leave off the trailing slash, most web servers will do a redirect to the same URL with the trailing slash.  

The reason I think this happens is that from a web (REST) point of view http://mydomain.com/somevalue
maps to an representation of "somevalue" while http://mydomain.com/somevalue/ maps to a listing of "somevalue".

While I see where you're coming from, I think our DevOps guys have worked around this by first making sure our calls to REST endpoints have the proper slashes and secondly by tweaking the query that they use to visualize data from Graphite/Graphana.

Hope this helps!

**Comment by jplock** [comment]
Closing as this is related to https://github.com/dropwizard/metrics
