### ISSUE TITLE
Add Spring Dependency Injection into Dropwizard

### ISSUE THREAD

**Issue by teamwork523** [dropwizard/dropwizard#1088]
I want to add Spring DI into my Dropwizard application. I have tried to import [Fallwizard](https://github.com/Fallwizard/Fallwizard), and [Spring Boot] (http://projects.spring.io/spring-boot/), but not working as expected. Therefore, I directly add Spring Servlet into /WEB-INF/web.xml as following:
```
    <servlet>
        <servlet-name>Spring</servlet-name>
        <servlet-class>org.springframework.web.servlet.DispatcherServlet</servlet-class>
        <init-param>
            <param-name>contextConfigLocation</param-name>
            <param-value>/WEB-INF/applicationContext.xml</param-value>
        </init-param>
        <load-on-startup>1</load-on-startup>
    </servlet>
    <servlet-mapping>
        <servlet-name>Spring</servlet-name>
        <url-pattern>/</url-pattern>
    </servlet-mapping>
```
However, it seems by default Dropwizard didn't recognize this file. Then I also tried to add Spring Servlet directly through:
```
public void run(ServicesAPIConfigurations conf, Environment env) {
...
env.getApplicationContext().addServlet("org.springframework.web.servlet.DispatcherServlet", "/");
....
}
```
But it gave the class not found exception for DispatcherServlet.

Do you have any suggestion on how to include Spring DI into Dropwizard? Thanks.

**Comment by jplock** [comment]
@jar349, any ideas on this one?  I know you've worked quite a lot with Fallwizard.

**Comment by arteam** [comment]
I've have had sucess with this approach:
````java
@Override
public void run(AppConfiguration configuration, Environment environment) throws Exception {
    AnnotationConfigApplicationContext context = new AnnotationConfigApplicationContext();
    context.getBeanFactory().registerSingleton("appConfiguration", configuration);
    context.register(SpringConfig.class);
    context.registerShutdownHook();
    context.refresh();

    // Resources
    for (Object resource : context.getBeansWithAnnotation(Path.class).values()) {
        environment.addResource(resource);
    }
    
    // Health checks
    for (HealthCheck healthCheck : context.getBeansOfType(HealthCheck.class).values()) {
        environment.addHealthCheck(healthCheck);
    }
    
    // Managed objects
    for (Managed managed : context.getBeansOfType(Managed.class).values()) {
        environment.manage(managed);
    }
}
````

**Comment by joschi** [comment]
I'm closing this issue since the questions are better asked in the [Fallwizard](https://github.com/Fallwizard/Fallwizard) project and it's not directly a problem with Dropwizard.

**Comment by jar349** [comment]
@teamwork523 @jplock Sorry I didn't respond yesterday; I try hard not to work on Sundays. :-)

I saw the issue that you posted for Fallwizard and will address it here.  Just responding here for closure.

**Comment by teamwork523** [comment]
Thank you @all for helping out. I will continue the discussion with @jar349 on the Fallwizard thread.
