### ISSUE TITLE
dropwizard-db 0.8.1 closed connections are returned to pool

### ISSUE THREAD

**Issue by TheTweak** [dropwizard/dropwizard#1089]
Hello guys, we have migrated to Dropwizard 0.8.1 from 0.6.2 recently and faced the following issue while using JDBI:
after database restart (Postgres), our application wasn't been able to restore connectivity to DB, all connections were closed and every time, after failed attempt to execute some SQL statement, returned back to pool. Pool is configured with all tests (on borrow, on return, on connect, while idle) disabled. Dropwizard 0.8.1 is using Tomcat DBCP 8.0.18 vs 7.0.37 on 0.6.2. Database configuration we are using is the same for both Dropwizard versions.
Dropwizard 0.6.2 is using 7.0.37 DBCP and is able to restore from DB restart, because PoolableConnection class performs explicit check if underlying SQL connection is closed:

     public synchronized void close() throws SQLException {
        if (_closed) {
            // already closed
            return;
        }

        boolean isUnderlyingConectionClosed;
        try {
            isUnderlyingConectionClosed = _conn.isClosed();
        } catch (SQLException e) {
            try {
                _pool.invalidateObject(this); // XXX should be guarded to happen at most once
            } catch(IllegalStateException ise) {
                // pool is closed, so close the connection
                passivate();
                getInnermostDelegate().close();
            } catch (Exception ie) {
                // DO NOTHING the original exception will be rethrown
            }
            throw (SQLException) new SQLException("Cannot close connection (isClosed check failed)").initCause(e);
        }
       ...

There is no such check in DBCP 8.0.18. 

Have anybody else faced this? We don't want to enable on borrow/on return validation checks just to overcome it.

P.S.: I've asked in Tomcat mailing list why they have removed this underlying connection check, will update this issue with response.

**Comment by TheTweak** [comment]
My question got answered on Tomcat mailing list and it don't relate to DBCP. 
The thing is that dropwizard-db 0.6.2 is using Tomcat DBCP's `GenericObjectPool`, which have this closed connection check upon return to pool, while dropwizard-db 0.8.1 is using Tomcat JDBC `ConnectionPool` which is more straightforward and don't have such check.
What was the reason of moving to Tomcat JDBC pool from DBCP?

**Comment by arteam** [comment]
Because of its better perfomance in concurrent environments, little size and more configuration options.  I would recommend to enable connection validation on borrow and to set an apropriate validation interval.

**Comment by pparth** [comment]
@arteam Is this going to be efficient? I thought that the Dropwizard 0.6.2 approach was to be as performant as possible.

**Comment by arteam** [comment]
@pparth I guess it's more about correctness than performance. If we know the database can be restarted during the work of the application, we should work in assumption that a connection can be invalid in any time. But we don't want to make validation every time a connection is borrowed, that's why a validation interval is needed.

By default Dropwizard configures the pool to make checks only in background, so this
should be most performant approach.

I guess, we can get the old mode by enabling a check on returning a connection to a pool, but I've never used this feature.

**Comment by TheTweak** [comment]
@arteam may be you could add `validator, validatorClassName` properties from Tomcat JDBC pool properties to DataSourceFactory, then we could write our own validator instead of just using SQL validation queries.

**Comment by TheTweak** [comment]
I can create PR with corresponding changes if you will take a look at it

**Comment by arteam** [comment]
Sure, I will gladly review it.
