### ISSUE TITLE
Registering LoggingFilter on Jersey Client

### ISSUE THREAD

**Issue by ra2085** [dropwizard/dropwizard#1093]
Requests cannot be logged because of the undelying apache http client implementation.

**Comment by arteam** [comment]
As far as I know Jersey's `LoggingFilter` works regardless of a connector implementation.
We even have a [test](https://github.com/dropwizard/dropwizard/blob/master/dropwizard-client/src/test/java/io/dropwizard/client/JerseyClientIntegrationTest.java#L286), which checks that `LoggingFilter` works with our connector.

Could you provide a snippet that demonstates the issue?

**Comment by ra2085** [comment]
It does work with the LoggingFilter constructor without parameters, however, I wish to log the request and response bodies/entities.

<code>client.register(new LoggingFilter(Logger.getLogger(MyTest.class.getName()), true));</code>

The Response body is logged, but the Request body just prints whitespaces.

**Comment by ra2085** [comment]
Disabling <code>gzipEnabledForRequests</code> solves the issue.

**Comment by hrishikesh-kumar** [comment]
JerseyClientConfiguration clientConfig = new JerseyClientConfiguration();
clientConfig.setGzipEnabled(false);
clientConfig.setGzipEnabledForRequests(false);

Client client = new JerseyClientBuilder(environment).using(clientConfig).build("myClient")
client.register(new LoggingFilter(Logger.getLogger(MyTest.class.getName()), true));
