### ISSUE TITLE
MultipartFeature Jersey Client

### ISSUE THREAD

**Issue by ra2085** [dropwizard/dropwizard#1094]
Cannot be used as intended because of the underlying apache http client implementation. Mime boundaries are not being sent properly.

**Comment by arteam** [comment]
You should disable chunked encoding for requests in the Jersey Client to work with MIME Multipart.
````java
JerseyClientConfiguration configuration = new JerseyClientConfiguration();
configuration.setChunkedEncodingEnabled(false);
Client client = new JerseyClientBuilder(RULE.getEnvironment())
           .using(configuration)
           .build("multipart-client");
````

Let me know, if it works for you. If not, please provide a test case, so we can reproduce the issue.

**Comment by ra2085** [comment]
Awesome. It does work. My bad. :(
