### ISSUE TITLE
AnnotationSensitivePropertyNamingStrategy Causing Deserialization Errors

### ISSUE THREAD

**Issue by gilbode** [dropwizard/dropwizard#1095]
I've got a few POJOs that have fields of type ObjectNode.  When I try to deserialize them w/ the Dropwizard ObjectMapper I get the following error from Jackson:

```
com.fasterxml.jackson.databind.JsonMappingException: Conflicting setter definitions for property "all": com.fasterxml.jackson.databind.node.ObjectNode#setAll(1 params) vs com.fasterxml.jackson.databind.node.ObjectNode#setAll(1 params)
```

I've tracked it down to AnnotationSensitivePropertyNamingStrategy.  Here's a reproducer:

```java
  public class AnnotationSensitiveExample {
    public String id;
    public ObjectNode json;
  }

  ObjectMapper mapper = new ObjectMapper();
  mapper.setPropertyNamingStrategy(new AnnotationSensitivePropertyNamingStrategy());
  AnnotationSensitiveExample deserialized =
        mapper.readValue("{ \"id\": \"1\", \"json\": { \"foo\": \"bar\", \"baz\": \"bing\" } }", AnnotationSensitiveExample.class);
```

If you remove the call to mapper.setPropertyNamingStrategy() or add a call to mapper.setPropertyNamingStrategy(null); after the 1st call, deserialization works fine.

**Comment by arteam** [comment]
Thanks for reporting this issue in the Jackson issue tracker. Let's wait what Tatu has to say. Maybe we can piggyback on a fix in jackson-databind.

**Comment by gilbode** [comment]
Looks like the issue is resolved in Jackson.
