### ISSUE TITLE
PermissiveEnumDeserializer doesn't support Jackson Enum features

### ISSUE THREAD

**Issue by christophercurrie** [dropwizard/dropwizard#1098]
Jackson has two features for Enum handling, `READ_ENUMS_USING_TO_STRING` and `WRITE_ENUMS_USING_TO_STRING`, that indicate that Enums should be de/serialized using the `toString()` value of the Enum, which can be more convenient than adding `@JsonValue` and `@JsonCreator` annotations. These annotations are currently ignored by `PermissiveEnumDeserializer` that's registered by `FuzzyEnumModule`.

I'm a little leery of what that deserializer is doing anyway. I get that it wants to allow different variations of enum constants over the wire, but it seems odd to make it a default. I'd prefer that it be an opt-in feature through an annotation on the Enum type, e.g.:

```
@FuzzyMatch
public enum MyEnum { ... }
```

and the deserializer would only activate for types that had the annotation. If not that, then perhaps an opt-out annotation, to allow the reverse?

**Comment by arteam** [comment]
Maybe we could respect `READ_ENUMS_USING_TO_STRING` feature in [PermissiveEnumDeserializers](https://github.com/dropwizard/dropwizard/blob/master/dropwizard-jackson/src/main/java/io/dropwizard/jackson/FuzzyEnumModule.java#L62)?
Something like this should be enough:
````java
if (config.hasDeserializationFeatures(
        DeserializationFeature.READ_ENUMS_USING_TO_STRING.getMask())) {
    return null;
}
````
If this feature enabled, we fallback to the native Jackson mechanism for deserializing enums.
What do you think?

**Comment by christophercurrie** [comment]
That solution would probably solve the issue as reported, and the rest of my commentary was a bit of a digression, anyway.

**Comment by prb** [comment]
IMHO, the `FuzzyEnumModule` should be removed and replaced with a note in ALL CAPS SHOUTING to remind people not to fill Dropwizard full of half-baked features that cause unexpected behavior and override behaviors of core libraries.  Dropwizard is an amalgam of frameworks, not a dumping ground.  Let Jackson be Jackson, Jersey be Jersey, etc.

**Comment by christophercurrie** [comment]
The original PR for the feature #340 mentions it as being designed to make config files more permissive. I'd be fine with it if the feature was restricted to config files. Back in the day I thought DW had different object mappers for configuration than for API serialization, perhaps that could be a compromise.
