### ISSUE TITLE
Config class locations

### ISSUE THREAD

**Issue by mattuuh7** [dropwizard/dropwizard#1103]
On the [doc](https://dropwizard.github.io/dropwizard/manual/configuration.html), it mentioned that config class should be in `META-INF` dir. where would you suggest putting this dir? should it be in `src/main/resources/` or `src/main/java`?

**Comment by arteam** [comment]
It should be on `src/main/resources/`. See for [example](https://github.com/dropwizard/dropwizard/tree/master/dropwizard-metrics/src/main/resources/META-INF/services)

**Comment by mattuuh7** [comment]
Thanks. Also from the [doc](https://dropwizard.github.io/dropwizard/manual/configuration.html), are both the factory classes and the actual widget classes required? what is the suggested break-down of properties between widget class and factory class?

**Comment by arteam** [comment]
Sorry, I don't follow you. You need this technique, only if you have some polymorphic confguration and you want to choose an implementation in runtime based on your YAML configuration. 

For example, you can have something like that:
```java
public interface MessageBroker {

    void sendMessage(String message);
}

public class ActiveMQMessageBroker implements MessageBroker {

    public String activeMqHost;

    @Override
    public void sendMessage(String message) {
        // Send a message to ActiveMQ
    }
}

public class RabbitMQMessageBroker implements MessageBroker {

    public String rabbitMqHost;

    @Override
    public void sendMessage(String message) {
        // Send a message to RabbitMQ
    }
}
```

Your code works with the `MessageBroker` interface without knowing about an implementation,
which can be changed in the configuration.

If you don't have such requriements, you can just use a plain object and Jackson will deserialize it
out of box.

**Comment by joschi** [comment]
Closing this issue. I think this discussion is better picked up on one of the mailing lists (https://groups.google.com/forum/#!forum/dropwizard-user or https://groups.google.com/forum/#!forum/dropwizard-dev).
