### ISSUE TITLE
Allow better customization of Jackson ObjectMapper

### ISSUE THREAD

**Issue by vzx** [dropwizard/dropwizard#1111]
Currently the only way to customize the Jackson `ObjectMapper` is either through the `io.dropwizard.Application#initialize` method's `bootstrap` parameter (using `bootstrap.getObjectMapper()`) , or the `io.dropwizard.Application#run` method's `environment` parameter (using `environment.getObjectMapper()`).
However in these cases, the `ObjectMapper` is already fully initialized using some default modules and settings, and there is no way for Jackson to remove modules from the `ObjectMapper`.

For example, I'm having a very strange issue with the `AfterburnerModule` and since I'm unable to make a reproducible test case for it, I just want to disable it (I don't need this module at all).

Similarly, I might want to configure the `JodaModule` using a different date format, which is also not possible right now.

As such it would be nicer if in the `initialize` method the `Bootstrap` exposes some builder which you can add to, but also remove from, and the final `ObjectMapper` is then built using the settings of this builder. This will allow users to for example remove undesired modules, or reconfigure existing modules by overwriting them with a new configuration.

Or perhaps there could be some configuration settings to indicate how the `ObjectMapper` should be configured.

**Comment by mattnelson** [comment]
There is support for setting your own data format.

```java
bootstrap.getObjectMapper().setDateFormat(new ISO8601DateFormat());
```

**Comment by vzx** [comment]
@mattnelson Thank you for your suggestion. However, the `JodaModule` does not seem to respect this setting. Image this small test code snippet:

```java
ObjectMapper om = new ObjectMapper()
        .disable(SerializationFeature.WRITE_DATES_AS_TIMESTAMPS)
        .setDateFormat(new SimpleDateFormat("YYYY-MM-dd"))
        .registerModule(new JodaModule());

String s = om.writeValueAsString(new Object() {
    public DateTime d = new DateTime();
});

System.out.println(s);
```

This outputs: `{"d":"2015-06-12T11:58:53.775Z"}`. Possibly, this is a bug in the `JodaModule` and should be reported there.

**Comment by arteam** [comment]
Yes, it's a limitation of  `JodaModule`. See this [issue](https://github.com/FasterXML/jackson-datatype-joda/issues/12). 

You need to plugin-in a custom serializer to make it works:
````java
Module module = new JodaModule().addSerializer(DateTime.class, 
    new JsonSerializer<DateTime>() {
    @Override
    public void serialize(DateTime value, JsonGenerator gen, 
                                   SerializerProvider serializers) throws IOException {
        gen.writeString(value.toString(DateTimeFormat.forPattern("YYYY-MM-dd")));
    }
});
ObjectMapper mapper = new ObjectMapper().registerModule(module);
System.out.println(mapper.writeValueAsString(new DateTime()));
````

It should possible to retrofit a mapper in such way in Dropwizard after #1112.

**Comment by vzx** [comment]
Thanks for the suggestion. Luckily, the existing `DateTimeSerializer` can be re-used though. Eg.

```java
JodaModule jodaModule = new JodaModule();
jodaModule.addSerializer(DateTime.class, new DateTimeSerializer(new JacksonJodaDateFormat(ISODateTimeFormat.dateTimeNoMillis().withZoneUTC())))
```

#1112 looks very promising.
