### ISSUE TITLE
JerseyClientConfiguration timeout not properly set on Client object from yaml

### ISSUE THREAD

**Issue by Sushisource** [dropwizard/dropwizard#1116]
Hi all,

AFAICT, dropwizard isn't actually setting the timeout values for jersey clients when they're specified in a config file. Here's my quick example (CatConfiguration is cut down for brevity):

```java
public class CatConfiguration extends Configuration {
  @Valid
  @NotNull
  @JsonProperty("jerseyClient")
  private JerseyClientConfiguration jerseyClientConfiguration;

  public JerseyClientConfiguration getJerseyClientConfiguration() {
    return jerseyClientConfiguration;
  }

  public void setJerseyClientConfiguration(JerseyClientConfiguration jcc) {
    this.jerseyClientConfiguration = jcc;
  }
}
```

Config file contains:
```yaml
jerseyClient:
  timeout: 3s
```

And when I build it (I've tried this with and without the "using" method)
```java
final Client jerseyClient = new JerseyClientBuilder(environment)
        .using(catCfg.getJerseyClientConfiguration()).build(getName());
System.out.println("Timeout:");
System.out.println(jerseyClient.getConfiguration().getProperty(ClientProperties.READ_TIMEOUT));
System.out.println(catCfg.getJerseyClientConfiguration().getTimeout());
```
This prints
```
Timeout:
null
3 seconds
```
So seems like it's read from the config just fine, but not actually set on the client object.

I fairly sure I haven't messed this up - is the timeout simply failing to be set? Right now I'm just manually setting the timeout as a temporary workaround. Let me know if I've done something wrong, otherwise hopefully this is an easy fix. Thanks!

**Comment by arteam** [comment]
We use our own Jersey Connector [implementation](https://github.com/dropwizard/dropwizard/blob/master/dropwizard-client/src/main/java/io/dropwizard/client/DropwizardApacheConnector.java), that's backed by the Apache HTTP Client. The timeout is actually is applied to it. See [there](https://github.com/dropwizard/dropwizard/blob/master/dropwizard-client/src/main/java/io/dropwizard/client/HttpClientBuilder.java#L225). 

Also our connectors ignores Jersey properties, so the call `jerseyClient.getConfiguration().getProperty(ClientProperties.READ_TIMEOUT)` will always return `null`.

**Comment by Sushisource** [comment]
Ah, ok. That said, I get read timeouts from something that takes more than 500ms to respond without my manual workaround, but I don't timeout with the workaround -- so something still seems fishy.

**Comment by arteam** [comment]
That's certainly strange. It would be great, if you could isolate your problem and provide a test case that reproduce it. AFAIK, we have a [test](https://github.com/dropwizard/dropwizard/blob/master/dropwizard-client/src/test/java/io/dropwizard/client/DropwizardApacheConnectorTest.java#L90) for this case and it works as expected. 

If you find a flaw in the code or in the test, please report.

**Comment by nickbabcock** [comment]
Shot in the dark, do you also have to set the `connectionTimeout`?

```yaml
jerseyClient:
  timeout: 3s
  connectionTimeout: 3s
```

**Comment by jplock** [comment]
Is this resolved by https://github.com/dropwizard/dropwizard/pull/1137?

**Comment by arteam** [comment]
I am closing this issue. Without a test case, we can't do much. 

Feel free to open a new issue against Dropwizard 0.8.5/0.9.1, if the problem still exists
