### ISSUE TITLE
Allow passing of Configuration object, not just resource path, for `DropwizardAppRule`

### ISSUE THREAD

**Issue by cowtowncoder** [dropwizard/dropwizard#1130]
When testing it is often much more convenient to just construct `Configuration` object that is needed, exactly as is, instead of hand-crafting a YAML file to store as resource, and/or add dot-path overrides.
But currently it seems that only resource path approach is supported.

I will try to come up with a patch that offers alternative mechanism to use where full Configuration POJO instance is passed as is.

**Comment by arteam** [comment]
Thanks. Squashed and applied to master.
