### ISSUE TITLE
Modifications of 'User-Agent' http header are ignored by DropwizardApacheConnector

### ISSUE THREAD

**Issue by parlovich** [dropwizard/dropwizard#1157]
When trying to set 'User-Agent' http header for ```WebTarget``` the changes actually don't take place and the request is always sent with 'User-Agent: <application name>(<client name>)'

That is due to DropwizardApacheConnector just ignores any modifications of 'User-Agent': https://github.com/dropwizard/dropwizard/blob/master/dropwizard-client/src/main/java/io/dropwizard/client/DropwizardApacheConnector.java#L131

Looks like it relates to a new Dropwizard configuration parameter ```httpClient.userAgent``` added in v0.7.1: Jun 18 2014

I guess that the proper behavior would be not to ignore user-agent if it was set by the user.
I suspect that the main problem was in inability to detect if the user-agent was set by the user or by jersey ```ClientRuntime``` (in a form of "Jersey/<version>").
However, even if there is no good way to workaround this then there should be option to turn off this Dropwizard feature. Let's say if ```httpClient.userAgent``` is set to ```null``` then ```DropwizardApacheConnector``` should not ignore User-Agent header.

**Comment by carlo-rtr** [comment]
Related discussion: https://groups.google.com/forum/#!topic/dropwizard-user/XmSTpzz8Xx8

**Comment by kkrushnyakov** [comment]
1. Added JerseyIgnoreRequestUserAgentHeaderFilter (ClientRequestFilter implementation) setting ignoreUserAgent flag in org.glassfish.jersey.client.ClientRequest to true
2. Updated DropwizardApacheConnector not to skip User-Agent header.

**Comment by kkrushnyakov** [comment]
Hello! I've made all corrections mentioned in your comments. Can you merge my fixes, please?

**Comment by kkrushnyakov** [comment]
Hello. I have added unit test you asked for. Can you check it and include this issue in 0.8.3 milestone to get it available with 0.8.3 release please?

**Comment by joschi** [comment]
Merged into `0.8.x` and `master` (7bbdb86f8ab7580c4d10d03a3620b34244c9ab87) branches.

**Comment by carlo-rtr** [comment]
@kkrushnyakov I just tried cutting a release for 0.8.4, which would include your changes but the tests don't pass on the releases/0.8.x branch.

```io.dropwizard.client.JerseyIgnoreRequestUserAgentHeaderFilterTest```

you mind taking a look?

**Comment by carlo-rtr** [comment]
I thought it might be related to jersey or http client versioning, but that didn't fix it.

https://github.com/dropwizard/dropwizard/pull/1236

**Comment by carlo-rtr** [comment]
nvm, I figured it out and merged it in
