### ISSUE TITLE
Non Deterministic Test Failure

### ISSUE THREAD

**Issue by carlo-rtr** [dropwizard/dropwizard#1158]
The below test failed for jdk7, but passed for jdk8, while cutting the RC

Tests in error: 
  JerseyClientIntegrationTest.testBufferedGzipPost:106->postRequest:140 » Processing

**Comment by joschi** [comment]
`JerseyClientIntegrationTest`didn't cause any problem in the past months, so I'll close this issue. Let's reopen it, if the problem resurfaces.
