### ISSUE TITLE
ContainerRequestFilter executed before Authentication happens

### ISSUE THREAD

**Issue by BernhardBln** [dropwizard/dropwizard#1159]
Hey,

when registering an AuthFactory and a ContainerRequestFilter (the latter via a dynamic feature), it seems the filter is called before the authentication happens.

Is this really wanted? I'd like to use the principal returned by the authenticator in my filter, but that's obviously not possible if the filter is called before.

My colleague says when programming directly against jetty, the authentication usually happens before any filter is triggered.

What's your opinion about that?

Bernhard

**Comment by carlo-rtr** [comment]
Dropwizard performs the authentication and authorization via a filter, which happens before the resource method is called. If you're registering another filter, you have to make sure it gets called after the authenticating filter

**Comment by joschi** [comment]
@BernhardBln What @carlo-rtr said, see https://jersey.java.net/documentation/latest/filters-and-interceptors.html#d0e10031

**Comment by BernhardBln** [comment]
Thanks for the link, joshi!

**Comment by BernhardBln** [comment]
Guys, sorry I have to get back to this - I still can't make it work. (Using Dropwizard 0.8.1, by the way).

I annotated my ContainerRequestFilter like this:

```
@Provider
@Priority(Priorities.AUTHORIZATION)
public class PrivilegeRestrictionFilter implements ContainerRequestFilter
```

And it still doesn't work (even if I put a priority of 15000), the Dropwizard Authentication is executed after this filter.

And when I look into the dropwizard-auth package, I actually don't see a Filter there...

Bernhard

**Comment by carlo-rtr** [comment]
What we discussed applies to 0.9.*

For 0.8.* auth happens in a jersey provider, which happens after all filters.
