### ISSUE TITLE
Powermock and Dropwizard

### ISSUE THREAD

**Issue by mattuuh7** [dropwizard/dropwizard#1169]
Hi team,
I have posted similarly on google group, but haven't got reply yet. I have been trying to use PowerMock with Dropwizard, but got a few problem get it working with liquibase and cannot load Junit ClassRules properly because PowerMockRunner does not extend ParentRunner. Any suggestion for an alternative? I need to mock static, that's why I need to use PowerMock. Also, the code I am trying to mock static from a dependency, so no option of using factory pattern to make the static code more testable.
Thanks,

**Comment by joschi** [comment]
As this is neither a bug report nor a feature request, I'm closing this issue. Please use the [dropwizard-user group](https://groups.google.com/forum/#!forum/dropwizard-user) for this kind of questions. Thanks!
