### ISSUE TITLE
documentation in getting started should have the root URI 

### ISSUE THREAD

**Issue by abhishekagarwal87** [dropwizard/dropwizard#1174]
I faced https://github.com/dropwizard/dropwizard/issues/1058 and only after debugging into the dropwizard code, did I realise the problem. But the getting-started guide says nothing about this. It should be modified accordingly so that others don't have to go through this problem.

**Comment by arteam** [comment]
The "Getting Started" guide presumes that the default server factory is used in configuration.
For it API endpoints are served for the root. For simple server factory it's different (from `/application`). Now we log the application/admin path during the application startup, which should reduce confusion.
