### ISSUE TITLE
Configuring the RedirectStrategy of HttpClientBuilder

### ISSUE THREAD

**Issue by jlordiales** [dropwizard/dropwizard#1186]
There's currently no way (as far as I could see) in Dropwizard's `HttpClientBuilder` of configuring the underlaying Apache's HttpClientBuilder `RedirectStrategy`.

I just had a use case yesterday where I wanted to completely disable redirects for POST (which by default follows 303's) but couldn't do it out of the box with the builder. 

Since I was already using DW's builder for the rest of my HTTP clients (and wanted to keep doing that) the best solution I could find was to create my own builder which extends `io.dropwizard.client.HttpClientBuilder` and override the `createClient` method to call `builder.disableRedirectHandling();` on the Apache's builder that is passed as a parameter to that method and then delegating to `super.createClient(builder, manager, name);`. 

But since `ConfiguredCloseableHttpClient` is package protected I had to create a `io.dropwizard.client` package inside my code base. Obviously an ugly hack but I couldn't find any other way to do it at the HttpClientBuilder level.

Given how trivial this would be to implement, it seems like an easy improvement. Any thoughts? I can submit a PR if you think this would be worth having.

**Comment by thesmith** [comment]
I stopped the Jersey client following requests by setting the follow_redirects property:

    final Client client = (new ForkedJerseyClientBuilder(environment))
                .using(conf)
                .build("blah")
                .property(ClientProperties.FOLLOW_REDIRECTS, Boolean.FALSE);

Does that help? This is obviously for `javax.ws.rs.client.Client`.

**Comment by arteam** [comment]
Thanks for you thorough report. I think we have two issues here:

* The first is that users can't override the `ConfiguredCloseableHttpClient createClient` method. 
Actually, I think it's a quite useful thing for production use, but not only for testing. We don't provide all possible options in the YML configuration, so users should have the ability to set them manually. We will expose some internal information in `RequestConfig`, but I don't see to much harm in doing so. Removing the `@VisibleForTesting` annotation from the method and making the `ConfiguredCloseableHttpClient` class public would be enough, I think.
Would you like to start a discussion or to submit a PR on this?

* The second is lack of the ability to set a custom redirect strategy. It seems to me as a useful option. I will gladly review a PR, if you submit it.

**Comment by arteam** [comment]
Oh, I didn't notice that you reported this issue in July. @jlordiales, sorry for a late reply. 

Anyway, my comments are still relevant.

**Comment by jlordiales** [comment]
No worries @arteam. I'll try to submit a PR this week or the next one. Thanks!

**Comment by jlordiales** [comment]
PR created for the Redirect strategy: https://github.com/dropwizard/dropwizard/pull/1281

**Comment by arteam** [comment]
Both are merged. Thanks for taking your time to tackle this issues.
