### ISSUE TITLE
Clone method in ChainedAuthFactory always set required to true

### ISSUE THREAD

**Issue by mtakaki** [dropwizard/dropwizard#1201]
The class `ChainedAuthFactory` always set the parameter `required` to true in the `clone` method. This is a snippet of the method:

```
@Override
public AuthFactory<Object, T> clone(boolean required) {
    ChainedAuthFactory<T> clone = new ChainedAuthFactory<>();
    for (AuthFactory<?, T> factory : factories) {
        clone.addChainedProvider(factory.clone(true));
    }
    return clone;
}
```

Instead of calling `factory.clone(true)`, it should be `factory.clone(required)`. This makes the authentication always required when `ChainedAuthFactory` is used.

**Comment by nickbabcock** [comment]
Closed by #1202
