### ISSUE TITLE
Apache HttpClient 4.4.x Certificate Bug

### ISSUE THREAD

**Issue by derrikcurran** [dropwizard/dropwizard#1208]
dropwizard-client 0.9.0-rc3 is using a version of Apache HttpClient (4.4.x) that causes a certificate error when connecting to googleapis.com (and others?) The issue has been fixed in HttpClient 4.5. See here: https://issues.apache.org/jira/browse/HTTPCLIENT-1613

**Comment by joschi** [comment]
Thanks for reporting this!
