### ISSUE TITLE
HTTP 404 status code logged as 200 in access logs

### ISSUE THREAD

**Issue by anuragkapur** [dropwizard/dropwizard#1209]
When using a `simple` server, all requests that do not include the `applicationContextPath` which return a 404 response code as seen by the client are logged as HTTP 200 in the access logs.

Example:

    $ curl -SI http://localhost:8080/membership/hello-world
    HTTP/1.1 404 Not Found
    Date: Fri, 07 Aug 2015 15:55:20 GMT
    Content-Type: text/html; charset=ISO-8859-1
    Cache-Control: must-revalidate,no-cache,no-store
    Content-Length: 306

In the access logs:

    0:0:0:0:0:0:0:1 - - [07/Aug/2015:15:55:20 +0000] "HEAD /membership/hello-world HTTP/1.1" 200 - "-" "curl/7.37.1" 0

**Comment by zodvik** [comment]
This is a bug in the jetty-server project itself and is not fixed as of the latest of 9.2.x release.

**Comment by a86c6f7964** [comment]
looks like this got fixed in 9.3 FYI

**Comment by arteam** [comment]
This should be fixed in Dropwizard 1.0 by #1036

**Comment by arteam** [comment]
Fixed by #1330
