### ISSUE TITLE
Resource @Valid validation

### ISSUE THREAD

**Issue by andrejserafim** [dropwizard/dropwizard#1213]
Hi,

I was struggling with @Valid annotation on resource methods like .put(@Valid foo).

Turns out if I add 

```xml
        <dependency>
            <groupId>org.glassfish.jersey.ext</groupId>
            <artifactId>jersey-bean-validation</artifactId>
            <version>2.19</version>
            <exclusions>
                <exclusion>
                    <groupId>org.hibernate</groupId>
                    <artifactId>hibernate-validator</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
```

I am getting an expected 422 response on invalid entities. 

Am I missing something? If not, would you mind adding this to the already very nice doc?

Thanks

**Comment by nickbabcock** [comment]
The current behavior is if you send an empty request body to a method that is annotated with `@Valid` and the request entity is not marked as Optional, a 422 will be thrown. This is not the same behavior as jersey's bean validation. Is this what is happening to you?

**Comment by andrejserafim** [comment]
Not really, invalid entities just propagate all the way to the resource code unless I include the above dependency. I can try replicating in a clean project if that helps.

**Comment by andrejserafim** [comment]
After some tinkering, I found a conflicting dependency - jersey-media-json-jackson was overriding the correct dropwizard and jersey behaviour.

**Comment by harshil07** [comment]
@andrejserafim i'm running into this as well. Can you share what the solution was? Did you just exclude the `jerysey-media-json-jackson` lib?

**Comment by andrejserafim** [comment]
Indeed, I had to - it's overriding jersey behaviour in all manner of unexpected ways, better to do without it.
