### ISSUE TITLE
No two hibernateBundles can listen in parallel to @UnitOfWork

### ISSUE THREAD

**Issue by helt** [dropwizard/dropwizard#1217]
given two active hibernate-bundles, it is not possible that both are used concurrently. The sketch below is roughly what i use atm. The problem is caused by HibernateBundle#run(), which - in my case - registers a ´UnitOfWorkApplicationListener´ instance two times as jersey singletons. So, as a result ´@UnitOfWork´ wont find any session when i access the BResource methods, because jersey only registers the first call.

https://github.com/dropwizard/dropwizard/blob/50d906e17bfb29cad76c6f7a2c24da8f2fa02003/dropwizard-hibernate/src/main/java/io/dropwizard/hibernate/HibernateBundle.java#L57

```java
public class BrokenApplication extends Application<MyConfiguration> {
	private final HibernateBundle<MyConfiguration> bundleA = new HibernateBundle<MyConfiguration>(A.class) {
		@Override
		public DataSourceFactory getDataSourceFactory(MyConfiguration configuration) {
			return configuration.getDatabaseFactoryA();
		}

		@Override
		protected String name() {
			return "hibernate.A";
		}
	};
	
	private final HibernateBundle<MyConfiguration> bundleB = new HibernateBundle<MyConfiguration>(B.class) {
		@Override
		public DataSourceFactory getDataSourceFactory(MyConfiguration configuration) {
			return configuration.getDataSourceFactoryB();
		}

		@Override
		protected String name() {
			return "hibernate.B";
		}

	};

	@Override
	public void initialize(final Bootstrap<MyConfiguration> bootstrap) {
		bootstrap.addBundle(bundleA);
		bootstrap.addBundle(bundleB);
	}

	@Override
	public void run(final MyConfiguration configuration, final Environment environment) {
		// each repo contains accessors to the Daos.

		final ARepository repoA = new ARepository(bundleA.getSessionFactory());
		environment.jersey().register(new AResource(repoA));

		final BRepository repo = new BRepository(bundleB.getSessionFactory());
		environment.jersey().register(new BResource(repo));
	}
}
```

**Comment by helt** [comment]
any thoughts anyone? Any hints which direction to take, so i can fix it and propose a pull request?

**Comment by FMPAR** [comment]
I am also experiencing this issue -  right now our only options are to explicitly deal with the sessions for the second bundle or try to incorporate a different container solution. A fix would be much appreciated.

**Comment by shankyty** [comment]
Do I have to still create two repo?
