### ISSUE TITLE
Add support for Logback's FixedWindowRollingpolicy to FileAppenderFactory in dropwizard-logging

### ISSUE THREAD

**Issue by dennyac** [dropwizard/dropwizard#1219]
I have noticed support for maxFileSize has been included in FileAppenderFactory using Size and Time based archiving in commit 343680b. 

With Size and Time Based Archiving (archivedLogFilenamePattern: -%d-%i) we have control on the size of each log file (it will rotate the logs and increment the index after maxFileSize is reached), but the archiveFileCount only applies to the number of days worth of files that should be maintained. So on any specific day, files will keep getting rolled over indefinitely with a new index when the maxFileSize is reached. These log files will continue to accumulate as long as it is within the number of days mentioned in archiveFileCount. So we will lose control on the number and size of log files on the host, and disk usage may be a concern. 

With [Fixed Window Rolling Policy](http://logback.qos.ch/manual/appenders.html#FixedWindowRollingPolicy) (archivedLogFilenamePattern: -%i), we have control on the size (maxFileSize) and the number of log files (archiveFileCount) that will reside on the host.

Proposed Approach: Pull Request - https://github.com/dropwizard/dropwizard/pull/1218
Include FixedWindowRollingPolicy in FileAppenderFactory. Rolling policy to be used will be based on the archivedLogFilenamePattern - 
Time Based Rolling Policy - /tmp/application-%d{yyyy-MM-dd}.log.gz
Size and Time Based Rolling Policy - /tmp/application-%d{yyyy-MM-dd}-%i.log.gz
Fixed Window Rolling Policy - /tmp/application-%i.log.gz

I hope you find this useful. I'm open to suggestions as well. Thanks.

**Comment by nickbabcock** [comment]
Closed by #1218
