### ISSUE TITLE
Humble question on licencing

### ISSUE THREAD

**Issue by nevson** [dropwizard/dropwizard#1226]
Sorry this might be a quite humble question but Dropwizard is licensed under `Apache License Version 2.0` and it depends on Jersey that is licensed under `CDDL + GPL License`. So if I write an application that uses Dropwizard then I've to open source it in case I'm distributing it in binary form as it depends indirectly (via Dropwizard) on Jersey or? Or do I've to just take care of the Apache License when distributing my application which means I could decide on whether I want to open source it or not?

Thanks in advance!

**Comment by ryankennedy** [comment]
Please don't use issues to ask questions. Questions can be directed to the [dropwizard-user Google Group](https://groups.google.com/forum/#!forum/dropwizard-user).
