### ISSUE TITLE
@JsonView Behavior

### ISSUE THREAD

**Issue by derrikcurran** [dropwizard/dropwizard#1238]
**EDIT:** I just updated to v0.9.0-rc4 and this issue seems to have been resolved. 

My apologies if I'm missing something here but I don't think the `@JsonView` annotation is working properly in v0.9.0-rc3.

If I add, for example, `@JsonView(Access.Elevated.class)`  to a class member and then return an instance of that class from a Jersey resource, the annotated member is serialized even without annotating the resource method. If I add `@JsonView(Object.class)` to the resource method, then the annotated class member is (correctly) not serialized. Because of this, I have to either add `@JsonView( ... )` to every resource method or to every class member. 

Other than being cumbersome, it's risky because forgetting the annotation could result in exposure of sensitive data.

**Comment by nickbabcock** [comment]
Since it looks like this behavior is fixed in v0.9.0-rc4 can this be closed?
