### ISSUE TITLE
swagger ui stuck at "fetching resource list:" (Uncaught TypeError: Cannot read property 'length' of null)

### ISSUE THREAD

**Issue by saurabhsyzhi** [dropwizard/dropwizard#1243]
I am trying to integrate swagger in the application and swagger ui is stuck at "fetching resource list: <URL>/api/swagger.json"

F12 on the browser indicates the below issue @ swagger-client.js line no. 626

Uncaught TypeError: Cannot read property 'length' of null

swagger-client.js: line no. 626
if(typeof param['enum'] !== 'undefined') {

I am using dropwizard-swagger 0.7 version with swagger-core / swagger-annotation / swagger-jaxrs / swagger-jersey2-jaxrs version of 1.5.1-M2.

I have tried to direct access the <URL>/api/swagger.json and I think the problem seems to be below "null" parameters returned in the json.

Any thoughts on the issue.

parameters: [
{
name: "type",
in: "query",
description: null,
required: false,
type: "string",
items: null,
collectionFormat: null,
default: null,
pattern: null,
format: null,
enum: null
}

**Comment by joschi** [comment]
Please file this issue in the appropriate project: https://github.com/federecio/dropwizard-swagger
