### ISSUE TITLE
Unable to load io.dropwizard.logging.LoggerFactory

### ISSUE THREAD

**Issue by lehcim** [dropwizard/dropwizard#1248]
Using 0.9-rc4, I see a lot of message like the following in the server log:

INFO  [2015-09-07 12:43:38,692] io.dropwizard.jackson.DiscoverableSubtypeResolver: Unable to load io.dropwizard.logging.LoggerFactory

In file META-INF/services/io.dropwizard.jackson.Discoverable there is a reference to io.dropwizard.logging.LoggerFactory, but there is no such class or interface in the source tree. However, there is an interface called LoggingFactory in the io.dropwizard.logging package, which implements Discoverable, thus I think it's only a typo (Logger vs Logging) in the service file (dropwizard-logging/.../META-INF/services/io.dropwizard.jackson.Discoverable)

I have not tested yet, and if you prefer a PR please let me know.

**Comment by lehcim** [comment]
Here is the PR. Please forgive me if something is wrong, this is my first pull request on github...

**Comment by joschi** [comment]
Closed by merging #1249.
