### ISSUE TITLE
Support multiple config files

### ISSUE THREAD

**Issue by tomakehurst** [dropwizard/dropwizard#125]
We'd find it really useful to be able to specify two config files at startup, one for defaults, one for environment-specific overrides.

Would you be interested in including this if we supply a patch?

**Comment by vvondra** [comment]
A nice touch would be able to override config files, or even by default be able to import them from one another.

config extended by config_prod.yml and config_staging.yml

**Comment by sirianni** [comment]
Layering config files is also important for separating out sensitive values (e.g. mounting a Kubernetes `Secret` in addition mounting a Kubernetes `ConfigMap`).  Or using the [Vault sidecar injector](https://www.vaultproject.io/docs/platform/k8s/injector).

Almost all modern java microservice frameworks have this feature.

**Comment by joschi** [comment]
@sirianni You can override any setting in the configuration file with a system property or with environment variables.

See also: [Using Secrets as environment variables](https://kubernetes.io/docs/concepts/configuration/secret/#using-secrets-as-environment-variables) and [Dropwizard -> Configuration -> Environment variables](https://www.dropwizard.io/en/release-2.0.x/manual/core.html#environment-variables).

**Comment by vvondra** [comment]
> Layering config files is also important for separating out sensitive values (e.g. mounting a Kubernetes `Secret` in addition mounting a Kubernetes `ConfigMap`). Or using the [Vault sidecar injector](https://www.vaultproject.io/docs/platform/k8s/injector).
> 
> Almost all modern java microservice frameworks have this feature.

it's three years since I touched this, but we found a way to plug in this behaviour with our own code: https://github.com/vvondra/dropwizard-config-importable
