### ISSUE TITLE
Wait for application shutdown until XYZ is done

### ISSUE THREAD

**Issue by m8r-ubnc5g** [dropwizard/dropwizard#1250]
The Problem is, that I fire a shutdown event and DW is shutting down before I can do some cleaning work before resource shutdown.

In my case, I have a loadbalancer ressource, polling every x seconds and submitting some loadbalancer informations to the DW apllication. I still want to run the application (and accept jobs) until loadbalancer excludes my DW application. After excluding the normal DW shutdown process (managed objects...) may be started.

I'm not sure, if I have not seen it yet or there is no way to to this. A "BeforeShutdownHandler" would be nice to handle all actions before application is stopped. On top a "stillAcceptsJobs" boolean trigger would be even nicer, so everyone can choose, if application will accept new jobs until "BeforeShutdownHandler" is finished or not. 

I can not use managed objects, because at the time this objects are stopped, the application does not accepts any new requests, so my loadbalancer resource is not callable any more.

Any external call with DW task (e.g. a shutdown task) is not my way of a clean shutdown. I want to be sure, that ,for every shutdown, DW can communicate with other applications (like loadbalancer or some other services) and the DW shutdown is deferred, until this cleaning task are done.

If there is another way to implement this behavior, please let me know.

**Comment by ryankennedy** [comment]
GitHub issues are not an appropriate place to ask questions. Please direct your question to the [dropwizard-user Google Group](https://groups.google.com/forum/#!forum/dropwizard-user).

**Comment by m8r-ubnc5g** [comment]
This was not intended as a question. It is more like a improvement to implemt sth. like a "BeforeShutdownHandler".

**Comment by ryankennedy** [comment]
What you're asking for isn't clear to me. Let's start a discussion on dropwizard-user and clear that up and verify there isn't an existing solution first. GitHub issues aren't a great place to have that kind of discussion.
