### ISSUE TITLE
ProxyServlet and BiDiGzipFilter produces incorrect request

### ISSUE THREAD

**Issue by dhagge** [dropwizard/dropwizard#1254]
When using a ProxyServlet in Dropwizard the BiDiGzipFilter correctly deserializes requests, however, when proxying them forwards ProxyServlet copies the content-encoding header into the proxyRequest but BiDiGzipFilter does not actually gzip up the request content.

    TransparentGzipProxyServlet proxyServlet = new TransparentGzipProxyServlet("http://localhost:9999", "/");
    environment.servlets().addServlet("MyProxyServlet", proxyServlet).addMapping("/whatever/*");

If another DW container is listening at http://localhost:9999 it will not be able to deserialize the payload since content-encoding header specifies gzip but the body isn't valid gzip format.

Note: if I register a BiDiGzipFilter via `environment.servlets().addFilter(..).addMappingForServletName(..)` it breaks deserialization if the initial request (since there seems to be 2 separate BiDiGzipFilter now registered on the proxy endpoints).

**Comment by dhagge** [comment]
In case anyone else is looking for a solution to this issue the following is a viable work around:

    package com.whatever;
    
    import javax.servlet.http.HttpServletRequest;
    
    import java.io.ByteArrayOutputStream;
    import java.io.IOException;
    import java.io.InputStream;
    import java.io.PushbackInputStream;
    import java.util.zip.GZIPInputStream;
    import java.util.zip.GZIPOutputStream;
    
    import com.google.common.base.Throwables;
    import com.google.common.io.ByteStreams;
    import lombok.extern.slf4j.Slf4j;
    import org.apache.commons.io.IOUtils;
    import org.apache.commons.lang.StringUtils;
    import org.eclipse.jetty.client.api.ContentProvider;
    import org.eclipse.jetty.client.api.Request;
    import org.eclipse.jetty.client.util.BytesContentProvider;
    import org.eclipse.jetty.http.HttpHeader;
    import org.eclipse.jetty.proxy.ProxyServlet;
    import org.eclipse.jetty.servlets.GzipFilter;
    
    /**
     * Transparent proxy servlet that supports gzip
     * <p/>
     * Created by damian.hagge on 9/14/15.
     */
    @Slf4j
    public class TransparentGzipProxyServlet extends ProxyServlet.Transparent {
    
        public TransparentGzipProxyServlet(String proxyTo, String prefix) {
            super(proxyTo, prefix);
        }
    
        /**
         * Dropwizard + jetty ProxyServlet handles proxy requests, however, if the original caller
         * sent a gzipped payload along with a "content-encoding: gzip" header, the header gets copied into the
         * proxyRequest but the body is not gzipped. This results in the target endpoint (e.g. the place the
         * request is proxied to) erroring out since it receives a gzip header but the body is not gzipped.
         * <p/>
         * This method customizes the request before it is proxied to gzip the body if the content-encoding specifies
         * that it should be gzipped but it is not.
         * <p/>
         * https://github.com/dropwizard/dropwizard/issues/1254
         * <p/>
         * @param proxyRequest The proxy request that will be sent on to the target endpoint
         * @param request The original request
         */
        @Override
        protected void customizeProxyRequest(Request proxyRequest, HttpServletRequest request) {
            String encoding = proxyRequest.getHeaders().get(HttpHeader.CONTENT_ENCODING);
            if (StringUtils.isNotBlank(encoding) &&
                    (encoding.toLowerCase().contains(GzipFilter.GZIP) ||
                            encoding.toLowerCase().contains(GzipFilter.DEFLATE))) {
                try {
                    // Use a pushbackstream to look ahead and read the gzip signature from the request
                    PushbackInputStream pb = new PushbackInputStream(request.getInputStream(), 2);
                    byte[] signature = new byte[2];
                    int bytesRead = pb.read(signature);
                    if (bytesRead != 2) {
                        throw new IllegalArgumentException(
                                "Request has gzip content-encoding but doesn't have data (2 bytes) to be read.");
                    }
                    pb.unread(signature); //push back the signature to the stream
    
                    if (!isGzipped(signature[0], signature[1])) {
                        log.debug("Request has gzip content-encoding but body is not gzipped. Gzipping...");
                        proxyRequest.content(createGzippingContentProvider(pb, request.getContentLength()));
                    } else {
                        log.trace("Request has gzip content-encoding and body is already gzipped.");
                    }
                } catch (IOException e) {
                    throw Throwables.propagate(e);
                }
            }
        }
    
        /**
         * Determine, based on the first two bytes of a payload, if the payload is gzipped
         * @param b1 First byte of the payload
         * @param b2 Second byte of the payload
         * @return True if the payload is gzipped, false otherwise
         */
        boolean isGzipped(byte b1, byte b2) {
            return (b1 == (byte) (GZIPInputStream.GZIP_MAGIC)) &&
                   (b2 == (byte) (GZIPInputStream.GZIP_MAGIC >> 8));
        }
    
        /**
         * Create a content provider that provides gzipped content
         * <p/>
         * @param source The non-gzipped source stream
         * @param sourceSize The size of the source stream
         * @return A content provider which provides gzipped content
         */
        ContentProvider createGzippingContentProvider(InputStream source, int sourceSize) {
            ByteArrayOutputStream byteOutput = null;
            GZIPOutputStream gzipOut = null;
            try {
                byteOutput = new ByteArrayOutputStream(sourceSize / 2);
                gzipOut = new GZIPOutputStream(byteOutput);
                ByteStreams.copy(source, gzipOut);
                gzipOut.finish(); // this writes the final gzip bytes
    
                /**
                 * Ideally we would not copy the bytes into memory via a byte buffer here and instead do something like:
                 *
                 *     // sourceStream --> zipperOutStream(->intermediateStream -)--> resultStream
                 *     final PipedInputStream resultStream = new PipedInputStream();
                 *     final PipedOutputStream intermediateStream = new PipedOutputStream(resultStream);
                 *     final GZIPOutputStream gzipOutStream = new GZIPOutputStream(intermediateStream);
                 *     final AtomicInteger byteSize = new AtomicInteger(0);
                 *     try {
                 *         IOUtils.copy(sourceStream, gzipOutStream); // or do this in a separate thread to prevent deadlocks?
                 *     } finally {
                 *         IOUtils.closeQuietly(gzipOutStream);
                 *         IOUtils.closeQuietly(intermediateStream);
                 *     }
                 *
                 * and then return an InputStreamContentProvider:
                 *
                 *     final Pair<InputStream, Integer> inputStreamAndSize = getGzipCompressedStream(request.getInputStream());
                 *     return new InputStreamContentProvider(inputStreamAndSize.getLeft()) {
                 *         @Override
                 *         public long getLength() {
                 *             return inputStreamAndSize.getRight();
                 *         }
                 *     };
                 *
                 * however, this (above) approach doesn't seem to be working.
                 */
                byte[] bytes = byteOutput.toByteArray();
                return new BytesContentProvider(bytes);
            } catch (IOException e) {
                throw Throwables.propagate(e);
            } finally {
                IOUtils.closeQuietly(gzipOut);
                IOUtils.closeQuietly(byteOutput);
            }
        }
    }

**Comment by nickbabcock** [comment]
Thanks for the solution, looks like #1177 may have solved it for the 0.9.0 release.
