### ISSUE TITLE
No configuration for setting PoolProperties.removeAbandoned in io.dropwizard.db.DataSourceFactory.java

### ISSUE THREAD

**Issue by dhankhar21** [dropwizard/dropwizard#1255]
There seems to be not any support for passing removeAbandoned parameter value to the tomcat jdbc pool through dropwizard 7 database config. Is there any way we can set this property?

**Comment by archanmishra** [comment]
we are facing the same issue with a lot of our DB threads going in abandoned state .

**Comment by anandagarwaal** [comment]
+1 facing the issue.
