### ISSUE TITLE
Make io.dropwizard.metrics.servlets.AdminServlet produce JSON

### ISSUE THREAD

**Issue by browtayl** [dropwizard/dropwizard#1256]
By default, `AdminServlet` produces a `text/html` page which links to the following resources:
* Metrics (`application/json`),
* Ping (`text/plain`),
* Threads (`text/plain`), and
* Healthcheck (`application/json`).

My team suggests that since [Dropwizard heavily favors JSON](http://www.dropwizard.io/manual/core.html#representations), it would be more consistent for `AdminServlet` to return `application/json`. The `text/html` resource could be replaced or selected via a configuration option.

The relevant code is in [lines 24-42 of AdminServlet.java](https://github.com/dropwizard/metrics/blob/master/metrics-servlets/src/main/java/io/dropwizard/metrics/servlets/AdminServlet.java#L24-L42). If the Dropwizard team considers this feature worthwhile, we are prepared to implement it and submit a pull request.

**Comment by ryankennedy** [comment]
Or you could submit a pull request that offers either HTML or JSON based on the Accept header.

Given I've personally never seen the AdminServlet used by anything other than a human being in the browser, I'd guess getting this fixed by someone other than yourself will be pretty low priority.

**Comment by jplock** [comment]
Closing due to lack of feedback
