### ISSUE TITLE
Dropwizard DataSourceFactory on with just DATABASE_URL

### ISSUE THREAD

**Issue by andersem** [dropwizard/dropwizard#1259]
Heroku and Dokku only offer a single DATABASE_URL when deploying an application. It would be convenient to create a DataSourceFactory using just this url.

The alternative is to parse the DATABASE_URL and pluck username and password from there, but this is error-prone and makes it hard to use different databases, like h2 in test.

Example database_url:

`DATABASE_URL=postgres://postgres:SOME_PASSWORD@172.17.0.1:5432/lolipop`

Example database-configuration:
```
database:
    driverClass: org.postgresql.Driver
    url: ${DATABASE_URL}
```

Also, see http://stackoverflow.com/questions/32705394/dropwizard-datasourcefactory-on-heroku-with-just-database-url

**Comment by andersem** [comment]
https://github.com/dokku/dokku-postgres/issues/22 shows a discussion about this for dokku

**Comment by arteam** [comment]
That's a reasonable feature request. #1260 should provide the ability to use inlined credentials.

**Comment by andersem** [comment]
Incredible response time!
