### ISSUE TITLE
WebSocketEnvironment

### ISSUE THREAD

**Issue by crudbug** [dropwizard/dropwizard#1262]
I am trying to integrate jetty 9 websockets with dw without any additional libraries. Has anybody done this ?

A WebSocketEnvironment similar to ServletEnvironment will be great feature for this.

**Comment by bripkens** [comment]
You can use WebSockets with Jetty using the `org.eclipse.jetty.websocket.servlet.WebSocketServlet` and the `configure` method:

```
  @Override
  public void configure(WebSocketServletFactory factory) {
    factory.setCreator(dataSocketCreator);
  }
```

**Comment by bripkens** [comment]
What do you think should a WebSocketEnvironment do?

**Comment by arteam** [comment]
WebSocket wiil not be supported in the Dropwizard core. Check out https://github.com/LivePersonInc/dropwizard-websockets and https://github.com/TomCools/dropwizard-websocket-jee7-bundle
