### ISSUE TITLE
Could you push the latest doc to dropwizard.io?

### ISSUE THREAD

**Issue by TurtleShip** [dropwizard/dropwizard#1271]
Hi,
Can you push the latest doc to dropwizard.io, especially the part around testing dropwizard?
Currently, the Dropwizard site tells you to use "GrizzlyTestContainerFactory" when your tests involve Auth/Context annotation. But you actually need to use "GrizzlyWebTestContainerFactory"

I see that this typo has already been fixed back in April, 2015 (https://github.com/dropwizard/dropwizard/commit/333dea7df2efda99a1d341cb2878fb59d354fb5e).
But the site still says to use "GrizzlyTestContainerFactory"

Thanks!
<img width="1552" alt="typo" src="https://cloud.githubusercontent.com/assets/3166423/10205661/62507242-6777-11e5-85ed-5002b4e3315c.png">

**Comment by joschi** [comment]
Thanks for reporting this. We'll update the documentation once Dropwizard 0.9.0 (which contains the fixed example) has been release.

**Comment by TurtleShip** [comment]
Sounds good to me :+1:

**Comment by joschi** [comment]
Documentation for Dropwizard 0.9.0 is now available at http://www.dropwizard.io/0.9.0/docs/

**Comment by TurtleShip** [comment]
Thanks! :+1:
