### ISSUE TITLE
Support for Jetty 9.3.x or HTTP 2 

### ISSUE THREAD

**Issue by mitemitreski** [dropwizard/dropwizard#1273]
Is there any specific issue why Jetty 9.3.x is not yet supported and with that HTTP 2 ? 
The only reasion why this might be an issue is that the miniamal java version would be 8. 
But since Java 7 has ended public updates(https://www.java.com/en/download/faq/java_7.xml) I don't really see the point it this.

Unless there is some parallel work on the same topic I could try and migrate both and make PR.

**Comment by joschi** [comment]
Jetty 9.3.x only supports Java 8. We will raise the baseline to Java 8 with Dropwizard 1.0.x, but for Dropwizard 0.8.x and 0.9.x, Java 7 is our target platform.

Please subscribe to #1036 to get updates about the update of Jetty.
