### ISSUE TITLE
CLI output on configuration exceptions should be more verbose

### ISSUE THREAD

**Issue by maffe** [dropwizard/dropwizard#1274]
My configuration contains a list of class names which are then dynamically loaded. If a class is not found, the output on the command line is not very helpful.

I run my project like this:
`$ java -jar target/myproject-1.0-SNAPSHOT.jar server config.yaml`

The output looks like this (using dropwizard 0.8.4):
> config.yaml has an error:
> * Failed to parse configuration at: myfoos.order; Instantiation of [simple type, class org.example.myproject.MyFooInfo] value failed: org.example.myproject.MyFooImpl (through reference chain: org.example.myproject.MyConfiguration["foo"]->org.example.myproject.MyFooInfo["order"])

`MyFooInfo` is used as a property in `MyConfiguration` and tries to load the classes specified by a constructor parameter which then throws a `ClassNotFoundException` because `org.example.myproject.MyFooImpl` is not found.

The output would be more helpful if it contained at least the class name of the root exception (I didn’t expect a `ClassNotFoundException` and therefore searched for other errors first) or maybe even the stacktrace.

I tried different strategies, but none of them is satisfying:
* Throwing the `ClassNotFoundException` directly: Output not very helpful like stated above
* Wrapping it in `RuntimeException` with a custom message: Custom message doesn’t appear, only the message from the `ClassNotFoundException`
* Throwing a `RuntimeException` with a custom message, but without a cause: command line output contains my message, but it’s bad practice to throw the stacktrace away

My current workaround is to catch, log and rethrow the `ClassNotFoundException` in `MyFooInfo` which is ugly and should not be necessary. Also, there could be other unhandled exceptions which will lead to command line output similar to the one given above.

**Comment by fexbraun** [comment]
Hi, can you please attach an example.

**Comment by nickbabcock** [comment]
Without a code example demonstrating actual vs expected behavior, there isn't too much we can do.
