### ISSUE TITLE
dropwizard-metrics-elasticsearch module?

### ISSUE THREAD

**Issue by rgbj** [dropwizard/dropwizard#1277]
I need to push metrics from a dropwizard application to an elasticsearch instance. https://github.com/dropwizard/dropwizard/blob/master/CONTRIBUTING.md#new-features says I should first bring the subject here: So, would a PR providing a dropwizard-metrics-elasticsearch module, similar to dropwizard-metrics-ganglia and dropwizard-metrics-graphite, be welcome?

TIA for any answer

**Comment by joschi** [comment]
@rgbj I think you should open an issue in the Metrics project: https://github.com/dropwizard/metrics

This being said, there are already existing metrics reporters for Elasticsearch, e. g. https://github.com/elastic/elasticsearch-metrics-reporter-java

**Comment by rgbj** [comment]
I had a look (and indeed, make us of right know) https://github.com/elastic/elasticsearch-metrics-reporter-java. I also found https://github.com/tomcashman/metrics-elasticsearch and https://github.com/dropwizard/dropwizard-elasticsearch. What I can't find in these is something akin to the class `io.dropwizard.metrics.graphite.GraphiteReporterFactory` tailored for elasticsearch, which would allow me to configure metrics-to-elasticsearch rather than code it in. E.g., I can't right now write:

    metrics:
      reporters:
        - type: elasticsearch
          host: some.host
          port: 9200

in my dropwizard app yaml configuration file. So that's what I had in mind.

**Comment by joschi** [comment]
Okay, got it.

Feel free to start such a project. As it doesn't have any hard dependencies into Dropwizard, I'd suggest running it in your own repository and adding it to the 3rd party listing at http://modules.dropwizard.io/

**Comment by rgbj** [comment]
That's what I was wondering -- will do it this way, then. Thanks for your answer, your time and dropwizard!
