### ISSUE TITLE
No logger config per file possible.

### ISSUE THREAD

**Issue by pandaadb** [dropwizard/dropwizard#1279]
Currently, I don't see an option to assign one Logger to a specific file appender. By default, DW will add every logger to the root logger. 

The way LoggingFactory is implemented also makes this hard to overwrite. I created a workaround/hack to solve this, but this is not ideal: 

see: http://stackoverflow.com/questions/27483442/dropwizard-doesnt-log-custom-loggers-to-file/33085996#33085996

Thanks,

Artur

**Comment by JensRantil** [comment]
I, too, find currently logger limitting; My usecase is that I need to have a separate file that only logs a certain logger. I need this while keeping the same loggers as usual for all other appenders.

**Comment by pandaadb** [comment]
I am closing this since dropwizard added support for logger config and separate appenders in 0.9.1
