### ISSUE TITLE
com.sun.jersey.spi.container.servlet.WebComponent$Writer.write taking long time

### ISSUE THREAD

**Issue by SeshuHSC** [dropwizard/dropwizard#1291]
com.sun.jersey.spi.container.servlet.WebComponent$Writer.write  process is taking more time  upto 4 mins. This is happening mostly when there is a lot of response in the service call.

com.sun.jersey.spi.container.servlet.WebComponent$Writer:write 199963

How to tune  the DW  to handle high response calls ?
Dropwizard version is 0.6.2

**Comment by joschi** [comment]
@SeshuHSC Please post to the [dropwizard-user mailing list](https://groups.google.com/forum/#!forum/dropwizard-user) for general questions like this. Additionally, Dropwizard 0.6.x isn't maintained anymore and you should upgrade to a more recent version of Dropwizard.
