### ISSUE TITLE
Fix Tests with LF Line Endings in Windows

### ISSUE THREAD

**Issue by nickbabcock** [dropwizard/dropwizard#1305]
Currently the tests will fail Windows because of 9f14b2e and 518d4b5

Having .gitattributes set to `auto` will convert `lf` to `crlf` on windows on checkout (and `crlf` to `lf` on checkin), which makes the tests fail (as the tests only check for `\n`). There are a couple solutions

### Solution 1:

Change gitattributes for mustache and freemarker files to force `lf` endings even on windows machines.

```
*.mustache eol=lf
*.ftl eol=lf
```

Not entirely thrilled with this solution as freemarker and mustache files would be treated special. We could set `eol=lf` for all file types, though carelessly doing it may have other tests, which rely on `System.lineSeparator()` to fail.

### Solution 2:

Keep on using `System.lineSeparator()` everywhere and put up with the annoyance it may bring

**Comment by joschi** [comment]
I don't have a Windows machine handy but @fexbraun wrote in #1286 and #1287 that the problems with building Dropwizard on Windows (or rather running the tests) had been fixed.

@nickbabcock Are you sure that this is caused by the `.gitattributes` file? IIRC setting `text=auto` should be good enough for fixing the original problem (also see https://help.github.com/articles/dealing-with-line-endings/).

**Comment by nickbabcock** [comment]
I think it's very subtle, so let me explain myself.

From the linked documentation:

> When text is set to "auto", the path is marked for automatic end-of-line
> normalization. If Git decides that the content is text, its line endings are
> normalized to LF on checkin.

This means that if I write something with crlf on Windows, it will be checked in as lf. But on a Windows checkout, git may decide to change the lf's to crlf's based on `core.autocrlf`. Relevant documentation:

> Git can handle this by auto-converting CRLF line endings into LF when you
> add a file to the index, and vice versa when it checks out code onto your
> filesystem

I have `core.autocrlf = true` on my machine, which is the default for my version of git.

@fexbraun may have had his problems fixed by having a couple global settings:

```
git config core.autocrlf false
git config core.eol lf
```

I tested this by doing a fresh `git clone` and trying to build.

**Comment by fexbraun** [comment]
I can see @nickbabcock 's point, although it is working on my machine.

@joschi the tests are about correct rendering of the views, not about git's line ending settings. 
So why not removing the line ending from the templates as suggested in
https://github.com/dropwizard/dropwizard/pull/1287
and
https://github.com/dropwizard/dropwizard/pull/1286
?

**Comment by joschi** [comment]
@fexbraun This would solve the specific problem with those two template files but it wouldn't prevent anyone from doing the same mistake again.

For the sake of getting Dropwizard out of the door I'll remove those particular line endings now.
