### ISSUE TITLE
ChainedAuthFilter throws NPE on no credentials

### ISSUE THREAD

**Issue by ferdy-lw** [dropwizard/dropwizard#1311]
The chained auth filter will throw a NullPointerException if none of the filters create a securityContext or throw a WebApplicationException. In this case the `firstException` will be null and the throw fails:

https://github.com/dropwizard/dropwizard/blob/master/dropwizard-auth/src/main/java/io/dropwizard/auth/chained/ChainedAuthFilter.java#L55

Is this expected behaviour? If we use auth filters must we set the securityContext or throw a WebApplicationException? Is this the same requirement for a single filter? How is this to work with `@Auth(required=false)`? There does not appear to be a test case for this scenario?

The old `chainedAuthFactory` did check for null:
https://github.com/dropwizard/dropwizard/blob/v0.8.4/dropwizard-auth/src/main/java/io/dropwizard/auth/ChainedAuthFactory.java#L104

**Comment by ferdy-lw** [comment]
After delving into it a little more it appears that this might be working as expected? `@Auth` does not support `required` any more. So to have optional injection of the principal is now not supported, in which case does this mean we must always have a final filter that will create a `securityContext` that must return a principal of the type expected (which must have some indication that it is not actually an authenticated principal)? This seems a little difficult to implement optionally protected resources now.

**Comment by jplock** [comment]
Per https://github.com/dropwizard/dropwizard/pull/1162, does it work if you add the `@PermitAll` annotation to the resource method?

**Comment by ferdy-lw** [comment]
No, it still fails with the NPE in the `ChainedAuthFilter`. If I do add the null check so it doesn't cause the NPE, it then fails further downstream when attempting to provide the principal to the `@Auth` annotation:

https://github.com/dropwizard/dropwizard/blob/master/dropwizard-auth/src/main/java/io/dropwizard/auth/AuthValueFactoryProvider.java#L67

The `@PermitAll` seems to still require a principal - and the docs imply that with `@PermitAll. All authenticated users will have access to the method.` 

#1162 uses the `PermitAllAuthorizer`, it doesn't address the Authenticator and the requirement that a securityContext must be added. The authorizer is used on the principal gotten from the securityContext.

I'm running into the issue that if I have any chained auth filters one of them must provide a security context or throw an exception otherwise I get an NPE. This means I can't mix resources that use `@Auth` with ones that don't (regardless of required or not).

**Comment by joschi** [comment]
@ferdy-lw Could you please provide a small, minimal Dropwizard application to reproduce this issue?

**Comment by ferdy-lw** [comment]
After reading through the source and the comments I think the way it currently works is fine, and with a little rehash of my auth strategy I was able to use my (cookie auth) filter and respond correctly.

The filter must throw an exception or set the `securityContext` - this make sense with the understanding that auth filters are _only_ used when a resource has a role annotation or `@Auth`; consequently, the filters must provide a security context or error, and this implies the responded error will be the first of the chained filters if they all fail.

While I like the new filtering, it makes for much simpler building authenticated (and authorized) principals, it does make it harder to have an optionally authenticated resource as you always have to provide a principal even with `@PermitAll`. If there are no credentials there really should be no principal.

Thanks for following up so quickly, the new auth filtering is a great enhancement.
