### ISSUE TITLE
Dropwizard gzip compression not working 

### ISSUE THREAD

**Issue by narunarthy-invn** [dropwizard/dropwizard#1313]
I'm using dropwizard  0.8.1 version and have added following compression parameters in config.yaml Also the HTTP Requet has a header "Accept-Encoding: gzip, deflate", And my output response is Application/Json and its size is approximately 32 KB and not compressed. I'don't see any ERROR logs for not initializing the compression on the server side.

server:
      gzip:
      enabled: true 
      minimumEntitySize: 256B 
      bufferSize: 8KB 

Following are the Request Headers:
 User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.80 Safari/537.36
      Origin: chrome-extension://hgmloofddffdnphfgcellkdfbfbjeloo
      Content-Type: application/x-www-form-urlencoded 
      Accept: */*
      Accept-Encoding: gzip, deflate
      Accept-Language: en-US,en;q=0.8,hi;q=0.6

Response Headers:
      Date: Wed, 28 Oct 2015 22:49:45 GMT 
      Access-Control-Allow-Origin: *
      Access-Control-Allow-Methods: GET, POST, DELETE, PUT, OPTIONS
      Content-Type: application/json 
      Transfer-Encoding: chunked

**Comment by joschi** [comment]
Please upgrade to Dropwizard 0.8.4 or 0.9.0 and check if the problem still exists there.

**Comment by arteam** [comment]
Please, open a new issue with a test case showing an unexpected behaviour. I can't reproduce the issue in 0.8.5/0.9.1.

**Comment by narunarthy-invn** [comment]
Upgraded to Dropwizard 0.8.4 and the compression is working.

**Comment by ankgoyalEXP** [comment]
I am facing the same issue with com.yammer.dropwizard 0.6.2. Is there any way to fix in this repo?

**Comment by joschi** [comment]
@ankgoyalEXP Dropwizard 0.6.x is not supported anymore. Please upgrade to a more recent version.
