### ISSUE TITLE
ConfigurationSourceProvider

### ISSUE THREAD

**Issue by fzakaria** [dropwizard/dropwizard#1314]
I found a configuration source provider that works on resources very useful since *src/main/resources* is already on the classpath.

    public class ResourceConfigurationSourceProvider implements ConfigurationSourceProvider {

        @Override
        public InputStream open(String path) throws IOException {
            return getClass().getClassLoader().getResourceAsStream(path);
        } 

    }

**Comment by fzakaria** [comment]
This issue is to see if thats worthwhile incorporating in the main dropwizard code. if so , I can send PR.

**Comment by joschi** [comment]
Thanks! I've added the class in 615048cdacdcab047dfb4919fdd73709ab00c1cd.
