### ISSUE TITLE
Migration 0.8 -> 0.9 / @Auth doesn't have required attribute any more

### ISSUE THREAD

**Issue by ahus1** [dropwizard/dropwizard#1320]
Dropwizard 0.8 had an attribute to `@Auth` so you could annotate a method with

```
@Auth(required = false)
```

Dropwizard 0.9 doesn't. The [Migration Guide](https://github.com/dropwizard/dropwizard/wiki/Upgrade-guide-0.8.x-to-0.9.x) doesn't describe how to solve this. I found a discussion #1162 about `@PermitAll` but I am not sure if I read it correctly and if this discussion is up to date with the release of 0.9. 

Please write a short paragraph in the migration guide on how to handle this. 

Thanks!

**Comment by natnan** [comment]
+1, can't use the new @Auth due to a requirement.

**Comment by ahus1** [comment]
I am maintaining a [keycloak-dropwizard library](https://github.com/ahus1/keycloak-dropwizard-integration). For [my examples](https://github.com/ahus1/keycloak-dropwizard-integration/blob/master/keycloak-dropwizard-jaxrs-example/src/main/java/de/ahus1/lottery/adapter/dropwizard/resource/DrawRessource.java) accessing SecurityContext directly worked. It might not work for other types of authentication.

The following code calls logout, but only if the user is currently logged in:

    @GET
    @Path("/logout")
    public LogoutView logout(@Context SecurityContext context) throws ServletException { 
        if (context.getUserPrincipal() != null) {
            request.logout();
        }
        return new LogoutView();
    }

**Comment by R-Gerard** [comment]
+1 for missing the `required = false` flag.

According to the 0.9 documentation:

>If you have a resource which is optionally protected (e.g., you want to display a logged-in user’s name but not require login), you need to implement a custom filter which injects a security context containing the principal if it exists, without performing authentication.

I'd rather not implement a new filter just because one of my APIs has optional auth. I looked into extending `OAuthCredentialAuthFilter`, but its constructor is private (so the class is essentially marked final), which forces me to copy-paste the implementation.  :disappointed: 

I'm considering just duplicating my API, one with auth and one without auth, but that's not very RESTful.

**Comment by natnan** [comment]
I don't know if it's a 1.0 issue or not, but it doesn't look like @ahus1's solution can work with Filters. Considering https://github.com/dropwizard/dropwizard/blob/master/dropwizard-auth/src/main/java/io/dropwizard/auth/oauth/OAuthCredentialAuthFilter.java#L38
```
        if (!authenticate(requestContext, credentials, SecurityContext.BASIC_AUTH)) {
            throw new WebApplicationException(unauthorizedHandler.buildResponse(prefix, realm));
        }
```
and https://github.com/dropwizard/dropwizard/blob/master/dropwizard-auth/src/main/java/io/dropwizard/auth/AuthFilter.java#L137
```
            final Optional<P> principal = authenticator.authenticate(credentials);
            if (!principal.isPresent()) {
                return false;
            }
```
, how the filter works is black&white. So, if `filter` is called, it will throw exception; if not, optional principal will not be assigned.

Am I missing something? Is there a way to make it work without implementing my own Filter? I want to not use my own Filter/Factories for a long time, but there is always a blocker :).
