### ISSUE TITLE
Error when running with no config file specified

### ISSUE THREAD

**Issue by lewisd32** [dropwizard/dropwizard#1321]
I'm trying to set up my `*Configuration` classes with defaults in the class, so I don't need to tell the app a config file when it's run in development.  However, when I run the app, I get this error:
```
default configuration has an error:
  * Unrecognized field at: database.healthCheckValidationTimeout
    Did you mean?:
      - logValidationErrors
      - removeAbandonedTimeout
      - validationQueryTimeout
      - initializationQuery
      - validationQuery
        [30 more]
```
I can see that `DataSourceFactory` has a `getHealthCheckValidationTimeout`, method, but I see no matching setter.  From what I see in the code, `getValidationQueryTimeout` and `setValidationQueryTimeout` read/write the same field as `getHealthCheckValidationTimeout`.
I'm unable to find the "default configuration" that specifies `database.healthCheckValidationTimeout` to attempt changing it to `database.validationQueryTimeout` and see if that works.
I think this is a bug, but I'm not sure.

**Comment by joschi** [comment]
@lewisd32 Which version of Dropwizard are you using?

**Comment by lewisd32** [comment]
I should have mentioned I was using 0.9.0, but it looks like you figured it out. Thanks! :)

**Comment by edulima** [comment]
wr
