### ISSUE TITLE
Wrong unit in FileAppenderFactory documentation

### ISSUE THREAD

**Issue by maffe** [dropwizard/dropwizard#1324]
[FileAppenderFactory](https://github.com/dropwizard/dropwizard/blob/master/dropwizard-util/src/main/java/io/dropwizard/util/Size.java) says `K` is a valid unit for `maxFileSize`, but [Size](https://github.com/dropwizard/dropwizard/blob/master/dropwizard-util/src/main/java/io/dropwizard/util/Size.java) requires `KB`.

Starting the application will fail:
> config.yaml has an error:
  * Failed to parse configuration at: logging.appenders.[1].maxFileSize; Instantiation of [simple type, class io.dropwizard.util.Size] value failed: Invalid size: 1K. Wrong size unit (through reference chain: org.example.MyConfig["logging"]->io.dropwizard.logging.DefaultLoggingFactory["appenders"]->java.util.ArrayList[1]->io.dropwizard.logging.FileAppenderFactory["maxFileSize"])

**Comment by nickbabcock** [comment]
This is closed by #1380, as it added `K` as a valid unit.
