### ISSUE TITLE
No session currently bound to execution context - for query in authenticator

### ISSUE THREAD

**Issue by harshil07** [dropwizard/dropwizard#1334]
Trying to upgrade to dropwizard 0.9.0/1. I have a OauthAuthenticator registered that is trying to make a database query but getting the following error.

```
ERROR [2015-11-09 20:05:38,080] com.hometeamcare.apiserver.error.ThrowableMapper: Caught exception
! org.hibernate.HibernateException: No session currently bound to execution context
! at org.hibernate.context.internal.ManagedSessionContext.currentSession(ManagedSessionContext.java:75) ~[hibernate-core-4.3.11.Final.jar:4.3.11.Final]
! at org.hibernate.internal.SessionFactoryImpl.getCurrentSession(SessionFactoryImpl.java:1014) ~[hibernate-core-4.3.11.Final.jar:4.3.11.Final]
! at io.dropwizard.hibernate.AbstractDAO.currentSession(AbstractDAO.java:36) ~[dropwizard-hibernate-0.9.1.jar:0.9.1]
! at io.dropwizard.hibernate.AbstractDAO.get(AbstractDAO.java:134) ~[dropwizard-hibernate-0.9.1.jar:0.9.1]
```

I have the `@UnitOfWork` annotation on the resource method. (This works with dropwizard 0.8.x)

After spending a little time in the debugger it essentially looks like a session is never opened i.e this line is never called. https://github.com/dropwizard/dropwizard/blob/master/dropwizard-hibernate/src/main/java/io/dropwizard/hibernate/UnitOfWorkApplicationListener.java#L96

The event type never matches `RESOURCE_METHOD_START` (https://github.com/dropwizard/dropwizard/blob/master/dropwizard-hibernate/src/main/java/io/dropwizard/hibernate/UnitOfWorkApplicationListener.java#L81). The last event type triggered before it tries to go into the authenticator filters is `REQUEST_MATCHED`, and then it throws the exception.

**Comment by paukiatwee** [comment]
I confirm this bug (DW 0.9.1). Anyway to fix this at DW level? Currently my workaround is manually open Hibernate Session see https://github.com/paukiatwee/budgetapp/blob/master/src/main/java/io/budgetapp/dao/AuthTokenDAO.java#L36

**Comment by arteam** [comment]
This is related to #1240. Currently `@UnitOfWork` works only for Jersey resources.
We will try to figure out something how to make it work transparently. Currently the only workaround
is manual transaction handling with `SessionFactory`.

**Comment by Allsimon** [comment]
It seems that I can reproduce this on 1.0.0-rc3-SNAPSHOT

**Comment by nickbabcock** [comment]
- Can you reproduce this on rc2?
- Can you reduce the code to just what reproduces the problem?

**Comment by Allsimon** [comment]
Yes I can reproduce it on RC2 too

```public class GrowwAuthenticator implements Authenticator<BasicCredentials, Users> {
    private final SessionFactory sessionFactory;

    public GrowwAuthenticator(SessionFactory sessionFactory) {
        this.sessionFactory = sessionFactory;
    }

    @Override
    public Optional<Users> authenticate(BasicCredentials credentials) throws AuthenticationException {
        Session session = sessionFactory.getCurrentSession(); // Crash here
        ... useless stuff ...
        return Optional.of(user);
    }
}```

Application class is :
```public class serverApplication extends Application<serverConfiguration> {
    private final HibernateBundle<serverConfiguration> hibernateBundle = new HibernateBundle<serverConfiguration>(Users.class) {
        @Override
        public DataSourceFactory getDataSourceFactory(serverConfiguration configuration) {
            return configuration.getDataSourceFactory();
        }
    };

    public static void main(final String[] args) throws Exception {
        new serverApplication().run(args);
    }

    @Override
    public String getName() {
        return "server";
    }

    @Override
    public void initialize(final Bootstrap<serverConfiguration> bootstrap) {
        bootstrap.addBundle(hibernateBundle);
        bootstrap.getObjectMapper().registerModule(new Hibernate5Module().disable(Hibernate5Module.Feature.USE_TRANSIENT_ANNOTATION));
    }

    @Override
    public void run(final serverConfiguration configuration,
                    final Environment environment) {
        environment.getObjectMapper().enable(SerializationFeature.INDENT_OUTPUT);

        environment.jersey().register(new SyncerResource(hibernateBundle.getSessionFactory()));
        environment.jersey().register(new AuthDynamicFeature(
                new BasicCredentialAuthFilter.Builder<Users>()
                        .setAuthenticator(new GrowwAuthenticator(hibernateBundle.getSessionFactory()))
                        .setAuthorizer(new GrowwAuthorizer())
                        .setRealm("SUPER SECRET STUFF")
                        .buildAuthFilter()));
        environment.jersey().register(RolesAllowedDynamicFeature.class);
    }
}```

Full project here: https://gitlab.com/Allsimon/Temp

**Comment by nickbabcock** [comment]
Thanks for the bug report. I'm re-opening this issue. How do you reproduce the bug? Is it every request that has the issue?

I'm curious if @arteam has the bandwidth to investigate because I'm totally unaccustomed to Hibernate :blush:

**Comment by Allsimon** [comment]
Yes, on every request :) On the reproduction project I published, you just have to GET  `localhost:8080/Sync/static` and it will happens

**Comment by yumingcao-okta** [comment]
Not sure why this PR is reopened, #1361 addressed this issue for me. @Allsimon you should use `UnitOfWorkAwareProxyFactory` when constructing authenticator.

**Comment by arteam** [comment]
Yes, @yumingcao-okta is right. Your authenticator should be created as
```java
GrowwAuthenticator authenticator = new UnitOfWorkAwareProxyFactory(hibernateBundle)
         .create(GrowwAuthenticator.class,  SessionFactory.class, 
                    hibernateBundle.getSessionFactory());
```

Also, you should not forget to annotate the method  `authenticate` with the `@UnitOfWork` annotation.
Probably we should make more clear in the documentation.

**Comment by henryptung** [comment]
@arteam Should this really be closed? To me, having the Hibernate transaction not span both authentication and actual execution is actually a bug. There is an opening here where an account can be deleted between authentication and execution. This may or may not cause violation of invariants, but is at least an unexpected thing to worry about, and at worst could cause very subtle, but severe security holes (e.g. unintended reinsertion of an account object via cascading).

While supporting creation of sessions/transactions in multiple places is a mostly-works approach, I'm very worried that the illusion of one-transaction-per-request (which I think is the intent of the API) can be risky.

**Comment by utsab-banerjee** [comment]
Hi, I am using environment.getJerseyResourceConfig().getContainerRequestFilters().add(new FilterClass(Dao)) to add a request filter but getting Hibernate exception. Same dao, when used within a resource is working fine.

**Comment by sunshineo** [comment]
@utsab-banerjee What is your dropwizard version? I'm using 1.0.0 and environment does not have a method "getJerseyResourceConfig()"

**Comment by harshil07** [comment]
i somewhat agree with @henryptung. It is a bit weird that it happens in different hibernate sessions. Also it leads to weird use cases where now the principal passed in to the resource is from a different session and calling accessors on foreign keys causes exceptions because the previous session has already expired but the object referenced is from that session. right now we circumvent those issues by re-querying the principal when needed.

**Comment by cmicali** [comment]
I agree auth and resource logic should happen in the same transaction.

Also, the dropwizard-auth docs should reference the `UnitOfWorkAwareProxyFactory` somewhere. This is a really common case and it was confusing the auth docs did not mention how to make hibernate work in the authenticator.

**Comment by arteam** [comment]
Thanks for pointing this out. Currently it's referenced only at the Dropwizard Hibernate module page.
As the `UnitOfWorkAwareProxyFactory` class created to provide a glue between authorization and declarative transactions, we should add some hint to it in the auth page as well. Good point about the migrations docs too.

Personally I view this class more like a kludge, because its purpose is not obvious for the Dropwizard users and we probably should have a more simple solution for declarative transactions outside the Jersey lifecycle, but currently I don't see any other alternative. Pull requests are welcome!

**Comment by yateam** [comment]
Hello, has this concern https://github.com/dropwizard/dropwizard/issues/1334#issuecomment-235998121 been addressed in any way? thanks

**Comment by yateam** [comment]
The following workaround might work for some cases (works for me, at least). 
Extend `UnitOfWorkEventListener` and in the `onEvent` handler, open session (`unitOfWorkAspect.beforeStart`) for all requests (don't check if `@UnitOfWork` is present). Also do that when `event.getType() == RequestEvent.Type.LOCATOR_MATCHED` rather than `RequestEvent.Type.RESOURCE_METHOD_START`. That way all filters will be included in the unit of work.

Of course, that works only if all the methods need to be transactional and only one database is going to be used (may be other factors?). But to be honest, that's a majority of simple CRUD systems.

**Comment by Pooja19934** [comment]
You can use ManagedSessionContext.bind() and then unbind after use. Pass sessionfacory instance of other hibernate bundle in the constructor dao
