### ISSUE TITLE
hk2 2.4.0-b31 has a malformed Maven pom (in hk2-parent)

### ISSUE THREAD

**Issue by rupertlssmith** [dropwizard/dropwizard#1335]
The HK2 issue can be found here:

https://java.net/jira/browse/HK2-277

A DW 0.9.1 project uses hk 2.4.0, which has a malformed line in its parent pom (the last one below):

<profile>
  <id>javadoc-jdk8+</id>
    <activation>
      <jdk>[1.8</jdk>

This causes the Maven project import to fail in IntelliJ. I can use 'mvn idea:idea' as a workaround, but its really annoying because that blows away all your project settings. Its much nicer to just hit the refresh button, or auto-refresh when the poms change.

If DW were bumped to 2.4.0-b32 or b33 the issue would be avoided.

**Comment by rupertlssmith** [comment]
The dependency comes through org.glassfish.jersey.core:jersey-server:jar:2.22.1, and unfortunately that seems to the be latest build available in maven central.

**Comment by rupertlssmith** [comment]
This can be worked around by excluding hk2 from dropwizard, in a projects pom.xml:

    <dependencyManagement>
        <dependencies>
            
            <dependency>
                <groupId>io.dropwizard</groupId>
                <artifactId>dropwizard-bom</artifactId>
                <version>${dropwizard.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>

            
            <dependency>
                <groupId>io.dropwizard</groupId>
                <artifactId>dropwizard-core</artifactId>
                <version>0.9.1</version>
                <exclusions>
                    <exclusion>
                        <groupId>org.glassfish.hk2</groupId>
                        <artifactId>hk2-api</artifactId>
                    </exclusion>
                    <exclusion>
                        <groupId>org.glassfish.hk2.external</groupId>
                        <artifactId>javax.inject</artifactId>
                    </exclusion>
                    <exclusion>
                        <groupId>org.glassfish.hk2</groupId>
                        <artifactId>hk2-locator</artifactId>
                    </exclusion>
                </exclusions>                
            </dependency>

Then explicitly import hk2 version 2.4.0-b33 instead.

**Comment by nickbabcock** [comment]
Related to #1325?

**Comment by joschi** [comment]
@nickbabcock Yes, it's the same bug. This will be fixed in the next Jersey version (which will depend on a more recent version of HK2).

**Comment by rupertlssmith** [comment]
Yep, same issue. I'll close this one.
