### ISSUE TITLE
Add support for 'layout-aware' Dropwizard Views

### ISSUE THREAD

**Issue by hotmeatballsoup** [dropwizard/dropwizard#1350]
I am using `dropwizard-views-freemarker` and am loving it so far, with one exception.

Freemarker doesn't natively support the concept of "**layouts**"; that is, ways of saying "*Hey, this page/FTL here uses a prescribed 'layout' that needs to be a applied at runtime.*" A typical layout might be:

    <HEADER>
    <BODY>
    <FOOTER>

With Freemarker, the only way to accomplish this layout is to repeat it (over and over again) inside each and every FTL file:

    fizz.ftl
    ======
    <#include "header.ftl">
    
    <#include "footer.ftl">

    buzz.ftl
    ======
    <#include "header.ftl">
    
    <#include "footer.ftl">

This repetition of importing the header/footer inside *each and every FTL* makes for annoying copy pasta that becomes a nightmare to maintain over time.

**Ideally**, there would be some way in Freemarker to define a layout:

    layout.ftl
    ========
    <#include "header.ftl">
    <@content>
    <#include "footer.ftl">

And then, for each page/view/FTL, you just say "*Freemarker, this FTL uses the 'layout.ftl' layout, so inject its content in lieu of the `<@content>` portion of that layout.*" That way, you might have pages that look like:

    fizz.ftl
    ======
    <#applyLayout "layout.ftl">
    

etc. Anyone with Grails experience will attest that this "layout" concept is well implemented in that framework. **Unfortunately, Freemarker does not support such a concept**, but there is a generally accepted solution for accomplishing it:

    layout.ftl
    ========
    <#include "header.ftl">
    <#include body>
    <#include "footer.ftl">

    // Then, in Java, every time you go to render a template (in this case, fizz):
    dataModel.put("body", "fizz.ftl");
    configuration.getTemplate("layout.ftl").process(dataModel, ostream);

---

### Feature request:
> Add the concept of "layout aware" Dropwizard views.

Since I am only (selfishly) interested in seeing this feature in DW Views Freemarker, and since I only have experience with Freemarker (not Mustache), I can only venture a guess as to how this would work in the Freemarker binding jar.

It does not appear possible to access the `ViewRenderer` nor the Freemarker `Configuration` class from any of the code that the application has access to. Instead, it seems that the DW `ViewBundle` looks for a Java service at runtime called `io.dropwizard.views.ViewRenderer` (which it looks for under `META-INF/services/`). So obviously, in the Freemarker binding jar, the value for this class-to-load is `io.dropwizard.views.freemarker.FreemarkerViewRenderer`.

Unless someone with better-trained-eyes-than-myself can weigh in here, I think this would require the addition of a whole new (optional) layout-aware set of classes:

    // Groovy pseudo-code
    abstract class LayoutAwareView extends View {
        String layoutName // 'layout.ftl'
    }

    class LayoutAwareFreemarkerViewRenderer extends FreemarkerViewRenderer {
        @Override
        void render(View view, Locale locale, OutputStream output) throws IOException {
            // Again, rough pseudo-code
            if(LayoutAwareView.isAssignableFrom(view.class)) {
                // Implement the generally-accepted Freemarker solution mentioned above using
                // the new 'view.layoutName' property.
            } else {
                // Implement normal FreemarkerViewRenderer functionality.
            }
        }
    }

The contents of the `dropwizard-views-freemarker#META-INF/services/io.dropwizard.views.ViewRenderer` file could then be:

    io.dropwizard.views.freemarker.FreemarkerViewRenderer
    io.dropwizard.views.freemarker.LayoutAwareFreemarkerViewRenderer

The only thing I haven't worked out so far would be how to make the selection of those two renderers configurable.

Thoughts? Criticisms? Hate mail?

**Comment by nickbabcock** [comment]
What's wrong with the generally accepted solution? I would prefer not to introduce complicated logic if the same behavior can already be done through the template.

**Comment by boncey** [comment]
I've come up with a simpler (in my opinion) way of doing layouts in Dropwizard/Freemarker.
I've posted my solution on StackOverflow, take a look and let me know if it helps please.
http://stackoverflow.com/questions/19664760/how-can-i-embed-one-dropwizard-with-freemarker-view-in-another-one/36412964#36412964

As an aside, it would be nice (for this) if [View#resolveName](https://github.com/dropwizard/dropwizard/blob/49ea3ed32b01c3990f00a878d665f2cbf384d00f/dropwizard-views/src/main/java/io/dropwizard/views/View.java#L55) could be made protected so it could be called from the TemplateView class in my solution.

**Comment by nickbabcock** [comment]
Ok, closing this because the solution exists.

@boncey, if you want to make a PR for the feature, go ahead and do so :smile:
