### ISSUE TITLE
Does dropwizard support Oracle Native Network Encryption?

### ISSUE THREAD

**Issue by CzarScar** [dropwizard/dropwizard#1351]
Hi all,

The database we connected to just change the connections to be encrypted. And as a result, our application which written with dropwizard(0.6.1) occurred an error said invalid database address.

Is there anyone who have met this issue? How can we make dropwizard application connect to database through the encryption connections?

**Comment by joschi** [comment]
Dropwizard 0.6.x (and 0.7.x for that matter) aren't supported anymore. You should upgrade to Dropwizard 0.9.1 for the latest supported release.

Dropwizard itself doesn't come with any JDBC or database drivers in general. In the end you probably "just" have to pull in the correct driver from Oracle to support SSL/TLS (Oracle Native Network Encryption).
