### ISSUE TITLE
Logback is used directly

### ISSUE THREAD

**Issue by t-oydna** [dropwizard/dropwizard#1367]
Currently both logback and slf4j are required dependencies in Dropwizard. And since you can only have one implementation of slf4j in your class path it's not possible to use slf4j-log4j12, for example.

As far as I understand it's suppose to be up to the developer as to what implementation of slf4j to use. I suggest that logback is not used directly but only through slf4j and that logback-classic, logback-core and logback-parent are added as runtime dependencies. This would make it possible to exclude then and use a different implementation.

From the [slf4j manual](http://www.slf4j.org/codes.html#multiple_bindings):
> Embedded components such as libraries or frameworks should not declare a dependency on any SLF4J binding but only depend on slf4j-api. When a library declares a compile-time dependency on a SLF4J binding, it imposes that binding on the end-user, thus negating SLF4J's purpose. When you come across an embedded component declaring a compile-time dependency on any SLF4J binding, please take the time to contact the authors of said component/library and kindly ask them to mend their ways.

</br>
<h5>My case:</h5>
<h6>If I chose to include both logback and slf4j-log4j12 the following messages are shown:</h6>

```
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/.../.m2/repository/org/slf4j/slf4j-log4j12/1.7.13/slf4j-log4j12-1.7.13.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/.../.m2/repository/ch/qos/logback/logback-classic/1.1.3/logback-classic-1.1.3.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.slf4j.impl.Log4jLoggerFactory]
```

```
Exception in thread "main" java.lang.IllegalStateException: Unable to acquire the logger context
    at io.dropwizard.logging.LoggingUtil.getLoggerContext(LoggingUtil.java:46)
    at io.dropwizard.logging.BootstrapLogging.bootstrap(BootstrapLogging.java:45)
    at io.dropwizard.logging.BootstrapLogging.bootstrap(BootstrapLogging.java:34)
    at io.dropwizard.Application.<init>(Application.java:24)
    ...
```

<h6>If I chose to include only slf4j-log4j12 and exclude logback the following messages are shown:</h6>

```
Exception in thread "main" java.lang.NoClassDefFoundError: ch/qos/logback/core/filter/Filter
    at io.dropwizard.Application.<init>(Application.java:24)
    ...
Caused by: java.lang.ClassNotFoundException: ch.qos.logback.core.filter.Filter
    at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
    at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    ... 4 more
```

As you can see neither approach works out.

**Comment by joschi** [comment]
> Currently both logback and slf4j are required dependencies in Dropwizard. And since you can only have one implementation of slf4j in your class path it's not possible to use slf4j-log4j12, for example.

Yes, and it's been designed that way. Dropwizard is using Logback for logging and wasn't designed to (easily) replace that.

**Comment by JamesXNelson** [comment]
So, basically, any other framework that is also opinionated about logging won't work in dropwizard?

**Comment by t-oydna** [comment]
As far as I know logback is the only native implementation of sl4j so the only possible conflict is with the adaptation layers (e.g. slf4j-log4j12).

BTW, here is the solution I ended up with, for anyone interested (works with any framework):

1 . Create a logback appender that redirects all its logs to your framework:
```
YourAppender implements ch.qos.logback.core.Appender.Appender<ILoggingEvent>
```
2 . Make this an appender in the configuration (loback.xml), probably the only one:
```
<configuration>
    <appender name="LoggingFramework" class="package.YourAppender"/>
    <root level="DEBUG">
        <appender-ref ref="LoggingFramework"/>
    </root>
</configuration>
```
3 . In your Dropwizard application (applies your logback configuration at the earliest possible point):
```
@Override
public void run(Configuration configuration, Environment environment) throws Exception {
   LoggerContext lc = (LoggerContext)LoggerFactory.getILoggerFactory();
   lc.reset();
   ContextInitializer ci = new ContextInitializer(lc);
   ci.autoConfig();
}
```
This has worked well for us. We lose some messages during startup, but still better than nothing.

**Comment by joschi** [comment]
> So, basically, any other framework that is also opinionated about logging won't work in dropwizard?

No, usually you can exclude the logging framework from other libraries and replace them with the appropriate SLF4J legacy bridge: http://www.slf4j.org/legacy.html

**Comment by jhalterman** [comment]
@joschi I think this issue was closed a bit too soon. 

As @t-oydna points out and as the slf4j manual describes, having an explicit dependency on logback or anything else can and will cause conflicts with other things on the classpath. I know of one project that was forced to abandon Dropwizard entirely because of this. In that project, Spark, which like Dropwizard also uses slf4j but instead opts for a log4j bridge, sets up the classpath and loads the log4j bridge before Dropwizard can attempt to load logback. Obviously slf4j complains, but since Dropwizard uses logback APIs directly, there is no way to make logging work for both Spark and Dropwizard. 

So two thoughts:

* There is absolutely no point in Dropwizard even using slf4j if it basically requires, through a dependency, usage of Logback. As the slf4j manual states, **this negates the purpose of slf4j**.
* The logback dependency, basically, makes Dropwizard's ability to log incompatible with any other technology that is similarly opinionated about logging and runs in the same process/classloader. 

Why limit potential adoption of Dropwizard and force users to abandon it over logging?

**Comment by joschi** [comment]
@jhalterman 
> There is absolutely no point in Dropwizard even using slf4j if it requires, through a dependency, usage of Logback.

SLF4J allows bridging other logging frameworks like log4j, commons-logging, or j.u.l which Logback itself doesn't. Additionally, Dropwizard allows for a deep integration of Logback, e. g. with jDBI or by allowing to configure it in the Dropwizard configuration (instead of having to write a custom `logback.xml` or `log4j.xml` file).

That being said, a pull request for abstracting the logging layer from Dropwizard in a backward-compatible way would be welcome.

**Comment by davireis** [comment]
For the record, I have been struggling with this as well. I work around the spark problem by using my own jars from spark modified to use logback instead of log4j. It is quite pain, but it works. However, there some scenarios where spark is brought through a dependency, and it gets harder to use the same trick. For example, currently I cannot run my code in spark notebook (https://github.com/andypetrella/spark-notebook) because of this.

**Comment by dav009** [comment]
sorry to pollute the issue. 

@davireis similar problem around here, with a different set of libs (Storm + logback + slf4j + log4j). Essentially the same thing, just wondering if you found a better work around than having your own spark-fork

**Comment by socketplugs** [comment]
@dav009, this worked for me :)
```javascript
configurations.all {
    // To prevent slf4j complaining about multiple logging implementations (and failing), trick gradle into providing only a single
    // implmentation (logback).
    resolutionStrategy.dependencySubstitution {
        // Substitute one module dependency for another
        substitute module('org.slf4j:slf4j-log4j12') with module('ch.qos.logback:logback-core:1.1.3')
        substitute module('org.slf4j:log4j-over-slf4j') with module('ch.qos.logback:logback-core:1.1.3')
    }
}
```

**Comment by imarios** [comment]
I really don't see why this issue is closed :(. I have nightmares every time I need to have Spark and Dropwizard work together.

**Comment by joschi** [comment]
@imarios You can either respect the decision or provide a PR. More whining doesn't help.

**Comment by arteam** [comment]
I think it's doable to achieve this goal, but it's rather hard from the technical point view. Would be great to see an initial prototype of splitting Dropwizard and Logback to see a scale of this change. Anyone who has bandwidth to work on this issue is very welcomed.

**Comment by imarios** [comment]
@joschi I agree, whining doesn't help. I wish I had the bandwidth to help here. Maybe have the ticket open so that someone can help to close it? If it's closed it means that is a non issue.

**Comment by aliakhtar** [comment]
This is REALLY frustrating.

**Comment by joschi** [comment]
As I said before, PRs to change this are welcome and can happily be discussed.

I'll lock this issue now.

**Comment by zackehh** [comment]
@t-oydna out of interest, could you please share your Appender impl?

**Comment by t-oydna** [comment]
Sure @zackehh , here you go:

**logback.xml**
```
<?xml version="1.0" encoding="UTF-8" ?>

<configuration>
    <appender name="log4j" class="{package}.LogbackToLog4jAppender"/>
    <root level="INFO">
        <appender-ref ref="log4j"/>
    </root>
</configuration>
```

**LogbackToLog4jAppender.java**
``` Java
public class LogbackToLog4jAppender implements Appender<ILoggingEvent> {
	@Override
	public void doAppend(ILoggingEvent event) {
		IThrowableProxy throwableProxy = event.getThrowableProxy();

		if (!(throwableProxy instanceof ThrowableProxy)) {
			// also true if throwableProxy is null
			log(event, null);
		}
		else {
			ThrowableProxy throwableProxyImpl = (ThrowableProxy)throwableProxy;
			Throwable t = throwableProxyImpl.getThrowable();

			log(event, t);
		}
	}

	protected void log(ILoggingEvent event, Throwable t) {
		Logger.getLogger(event.getLoggerName()).log(toLevel(event.getLevel()), event.getMessage(), t);
	}

	public static org.apache.log4j.Level toLevel(Level level) {
		return org.apache.log4j.Level.toLevel(level.levelInt);
	}

	@Override
	public boolean isStarted() {
		return true;
	}

	@Override
	public FilterReply getFilterChainDecision(ILoggingEvent arg0) {
		return FilterReply.ACCEPT;
	}
}
```
**Note**
This impementation is very ineffecient compared to creating a logger once since it has to look up the apropriate logger each time ( Logger.getLogger(...) ). It's important to set the minimum level in the logback configuration to a reasonably high level. If you set the level in log4j this appender higher than in logback this appender will look up the log4j logger for every log message, tell log4j to log and then log4j will ignore the message.

**Comment by zackehh** [comment]
@t-oydna awesome, that works just fine. Interesting about the logs swallowed at startup but I too can live without those for now :) thanks!

**Comment by JohnnyMarnell** [comment]
@socketplugs 's work around is a godsend and saved me! (if you're lucky enough to be using gradle)

**Comment by arteam** [comment]
Since Dropwizard 1.2.0 it's now possible run an app without Logback (#1900 and #2112)
