### ISSUE TITLE
Yaml property extension 

### ISSUE THREAD

**Issue by pandaadb** [dropwizard/dropwizard#1368]
Hi,

I would like to suggest an addition to the configuration for dropwizard projects to have base configs that can be extended. I am thinking of something like for example:

(1) configure base.yml to have a logging config that for example looks something like: 

     name: timerLog
     threshold: ALL
     archive: true
     archivedLogFilenamePattern: %{LOGPATH}
     archivedFileCount: 31
     timeZone: UTC
     logFormat: "%msg%n"

(2) have a property file that can be associated with the yaml file that defines properties 

    LOGPATH="path/to/my/log/file" 

(3) with the startup one can define the property location and the configuration will automatically expand the yaml file with those properties.

That way one can have deployment specific information. And that way people could run their app on specific hosts by specifying their config. 
Currently We have to copy/paste the entire yaml file and replace the properties that don't fit with the correct values.

**Comment by joschi** [comment]
You can already override settings via environment variables (http://www.dropwizard.io/0.9.1/docs/manual/core.html#environment-variables). If you absolutely want to read those properties from another file, you can write a similar `ConfigurationSourceProvider` which substitutes the values in your configuration file.

**Comment by earlye** [comment]
Alternatively, you could use this:

https://github.com/earlye/dropwizard-multi-config
