### ISSUE TITLE
Inconsistent `maxThreads` default for JerseyClient

### ISSUE THREAD

**Issue by natnan** [dropwizard/dropwizard#1375]
I might have misunderstood this completely but it felt wrong enough to create an issue here :).

Dropwizard's default `maxThreads` count is defaulted to 1024. While jersey client's is `128`. So, if you have a resource where you make some asynchronous request to another service and burst this resource with 1000 requests simultaneously, 872 of the requests will fail because of jersey client's thread pool reaching its limit. So, maybe, both `maxThreads` fields must have the same default value?

**Comment by jplock** [comment]
Instead of changing the default (as users may be relying on that), would you mind submitting a pull request to clarify the values in the documentation?

**Comment by natnan** [comment]
Sure, I wouldn't mind. But what kind of clarification should I add? Some warning like "warning: If you don't set this (`jerseyClient.maxThread`) high enough to match `server.maxThreads`, some requests may fail due to congestion on jersey client thread pool."?

**Comment by jplock** [comment]
I think your use-case only applies if you are creating another request from inside an existing resource.  So that's the main point of clarification I think.

**Comment by natnan** [comment]
Ah yes, of course. If it's used by a `Managed` service of sort, it's not relevant.
