### ISSUE TITLE
How could I get Dropwizard to hot deploy locally?

### ISSUE THREAD

**Issue by jansoren** [dropwizard/dropwizard#1378]
Running 'mvn clean install' every time before starting the application is consuming alot of time. Is there a good way to set up hot deploy of an Dropwizard application in Intellij?

**Comment by eserlan** [comment]
Just run the Application.main method in IntelliJ. Remember to add `server whatever.yml` to the program arguments.
Then you can run it in debug mode and it will hotdeploy your changes, as long as you dont change any signatures or some such. Then you have to restart the application. 

Way faster than running the maven commands each and every time you make a change

**Comment by jansoren** [comment]
Thanks mate :)
![start-app-in-intellij](https://cloud.githubusercontent.com/assets/1298854/11684131/b6f3b46a-9e6f-11e5-9bc4-cdab714aed42.jpg)

**Comment by JohnnyMarnell** [comment]
if I use IntelliJ and setup an Application with DropWizard main, I can debug and hit breakpoints, however if I make a change (not method sig) and save, it says compilation finished, but no changes :(

**Comment by rattrayalex** [comment]
Is hot deploy possible with Gradle?

**Comment by arteam** [comment]
Static resources should be reloaded without additional work. For Java code, you need a special JVM which allows redefine classes in runtime. For example, [DCEVM](https://github.com/dcevm/dcevm).
