### ISSUE TITLE
Naming of OptionalOffsetTimeArgumentFactory  and OptionalZonedTimeArgumentFactory

### ISSUE THREAD

**Issue by kilemensi** [dropwizard/dropwizard#1382]
Since `OptionalOffsetTimeArgumentFactory` and `OptionalZonedTimeArgumentFactory` handle `OffsetDateTime` and `ZonedDateTime` respectively, shouldn't they be named `OptionalOffsetDateTimeArgumentFactory` and `OptionalZonedDateTimeArgumentFactory`?

**Comment by jplock** [comment]
@joschi what do you think?

**Comment by joschi** [comment]
Yes, renaming those classes is fine. It was more of an oversight on my end rather than a conscious decision and the end users won't ever come in contact with those classes directly.

**Comment by jplock** [comment]
I submitted https://github.com/dropwizard/dropwizard/pull/1445 to address this
