### ISSUE TITLE
Removal/Deprecating/Opt-in option for Joda, Guava Optional and other Pre Java 8 libraries

### ISSUE THREAD

**Issue by kilemensi** [dropwizard/dropwizard#1383]
Since dropwizard 1.0 requires Java 8, shouldn't support for things like Joda Time, Guava Optional, etc. get removed from the main library? They could be moved to an external module just like Java 8 features are in an external module for the Dropwizard 0.9.x branch.

**Comment by jplock** [comment]
I'm not sure I agree with this approach, at least not for 1.0.  Maybe in a future release once the internal libraries improve support, but right now, this would break the upgrade path for a lot of users.

**Comment by arteam** [comment]
We discussed this in #1365 and came to the conclusion that we should not remove Guava `Optional` and `Joda-Time` support, because it might be a blocker issue for migrating existing applications to the 1.0.0 version. Unfortunately, we don't have a simple way to modularize support of these libraries, so supporting both in the core looks like a pragmatic approach.

**Comment by kilemensi** [comment]
@jplock / @arteam  Good to hear (and I respect) your views.

Just for the record, I will put my views here (even though the issue is closed).

I believe 1.0.0 is a great milestone for any library and it usually means *production ready* for most folks. If we enter this milestone with already "deprecated" libraries like Joda, it means they're going to have to be supported for the foreseable future which could be a year or more for such an important release.
I believe the fact Java 7 has already been EOLed, most of people using Dropwizard (especially those that will be upgrading to 1.0.0) will be on Java 8 already and having Guava by default is the wrong *default* on Java 8.

My 2 cents are:

 + If migration path is the overriding goal, lets do another 0.9.x release (and not 1.0.0 for now) only focusing on baselining on Java 8. I think this will allow for introduction of 1.0.0 by the end of the first quarter and may be all other libraries like JDBI will also be on Java 8 without Guava dependencies.

 + Lets make a hard breaking change for 1.0.0 now and backport whatever we can back to 0.9.x and do a final 0.9.x release with all compatible changes. This will give people still on 0.9.x branch time to refactor their code slowly for 1.x branch while allowing dropwizard to move forward without accumulating any deadwood.

**Comment by evnm** [comment]
Another consideration which arguably adds weight to @kilemensi's proposal is the fact that any post-1.x release that removes Guava and Joda APIs from Dropwizard would technically warrant a major version bump, as per semver. If there's truly a desire to roll forward with pure-JDK8 in the near term, a 0.9.x migration branch could be a good means of avoiding a hasty 2.0.0 release.

**Comment by jplock** [comment]
I agree on the semver-aspects of doing this breaking change now and you are correct in that we need some time period of marking all of the Joda and Guava classes as `@Deprecated` to give users a chance to migrate.  We're about to create 0.9.2 and we could do a follow-on release of 0.9.3 which includes a JDK bump to 1.8 and deprecates all of the Joda and Guava classes.  I'm not sure what other @dropwizard/committers think about this strategy.

**Comment by mattnelson** [comment]
Following semver the JDK bump should not be introduced on 0.9.

**Comment by evnm** [comment]
0.10.0, then?

**Comment by joschi** [comment]
Guava won't be removed anytime soon from Dropwizard, so we can still support the Guava variant of `Optional<T>`. The code is already there and it's working. I don't see any advantages removing it.

As for Joda-Time, I'm not dogmatic about its use. If someone provided a pull request to move support for Joda-Time into add-on modules and only support the Java Date/Time API (JSR-310) in the core libraries, I'm fine with it. Until then, I'd simply mark it as deprecated and remove it in Dropwizard 2.0.0 (in the far future) to simplify migration from Dropwizard 0.x to Dropwizard 1.x. But then again, Joda-Time is a quite stable library and shouldn't result in much maintenance work.

I'm totally against bumping the baseline of Dropwizard 0.9.x to Java 8. That's just not how the versioning should work. :wink:

**Comment by karussell** [comment]
@joschi can you elaborate on dropwizard and guava? Why isn't guava just an optional dependency? Have read that removing them was kind of 'considered' https://github.com/dropwizard/dropwizard/pull/1365#issuecomment-162184147

**Comment by joschi** [comment]
@karussell Guava is being used internally by Dropwizard itself and thus is a mandatory dependency.
