### ISSUE TITLE
Add imports in the example code blocks of the documentation 

### ISSUE THREAD

**Issue by vitorreis** [dropwizard/dropwizard#1390]
As a developer I would like to explicit be able to see the imports of the code example, often I need to search for the package of a specific class that is in the example.

What do you think about it?

**Comment by jplock** [comment]
That sounds great, would you mind submitting a pull request on the pages that need clarifying?

**Comment by vitorreis** [comment]
The time has passed and I already don't remember exactly in which page was the issue, so I am closing the issue.
Thanks, in the next one I will also doc which exactly is the page in order to remember and submit the fix
