### ISSUE TITLE
Support DropwizardClientRule with custom ObjectMapper config

### ISSUE THREAD

**Issue by rowanhill** [dropwizard/dropwizard#1393]
Hi,

As far as I can tell, it's not possible to apply any custom configuration to the ObjectMapper used by DropwizardClientRule's FakeApplication (since the application and its environment are kept private). Is this by design?

I'd like to register a Module and set some SerializationFeatures on the ObjectMapper used - without that, the JSON the client under test sends cannot be deserialized.

It looks like at the moment I'm forced to run a full integration test with DropwizardAppRule (which is a shame, as it's slower and much more difficult to manipulate). Is there any alternative, or if not, is there any argument against exposing the application and/or environment from DropwizardClientRule?

Thanks,
Rowan

**Comment by jplock** [comment]
I submitted https://github.com/dropwizard/dropwizard/pull/1446 to address this
