### ISSUE TITLE
Add support Jetty's System.inheritedChannel option

### ISSUE THREAD

**Issue by matsumana** [dropwizard/dropwizard#1409]
At the application deploy never stop the service, If add support Jetty's System.inheritedChannel option.

It Realize by [Server::Starter](https://github.com/kazuho/p5-Server-Starter).

I want to add DropWizard configure option about this feature.

# Introduce about Server::Starter

Server::Starter is superdaemon for hot-deploying server programs.  
And popular OSS in Japan.

## How to use Server::Starter

Run app by Server::Starter

e.g.

```
$ start_server --port=8080=0 -- java -jar /path/to/app.jar
```

`port: 8080`  
`fd: 0`

## First process

Server::Starte` is create socket.

![](https://i.gyazo.com/aa266ae7ef65aa2bddec0848744c73f0.png)

## Next process

fork and exec Jetty process.

![](https://i.gyazo.com/3be7a7187919d8f97eb04dcab6f14ec5.png)

And Jetty process refers Server::Starter shares socket.

![](https://i.gyazo.com/4b63b7d0af081ed39cb1bfbd08984f2d.png)

## When deploy new version app

Server::Starter lauches new process.
And new Jetty process refers Server::Starter shares socket too.
And kill old version app Jetty process.

![](https://i.gyazo.com/475cfe602145c4fd7b485458082029e3.png)

# FYI

* If call System.inheritedChannel, JVM can refer socket

[sun.nio.ch.InheritedChannel](http://grepcode.com/file/repository.grepcode.com/java/root/jdk/openjdk/8u40-b25/sun/nio/ch/InheritedChannel.java#143)

* Enable System.inheritedChannel in Jetty

[ServerConnector#setInheritChannel(boolean)](https://github.com/eclipse/jetty.project/blob/master/jetty-server/src/main/java/org/eclipse/jetty/server/ServerConnector.java#L312)

* I already customized the source in my repository

[matsumana/dropwizard](https://github.com/matsumana/dropwizard/tree/feature/jetty-inheritChannel)

**Comment by jplock** [comment]
This doesn't sound too complicated to me.  Would you mind submitting a pull request with your changes?

**Comment by matsumana** [comment]
I submited. Please review.

#1410

**Comment by arteam** [comment]
Closed via #410
