### ISSUE TITLE
Add JDBC url to PooledDataSourceFactory

### ISSUE THREAD

**Issue by benjamin-bader** [dropwizard/dropwizard#1413]
A Dropwizard module I maintain uses `DataSourceFactory#getUrl()` as part of its configuration; as of 0.9.0, the new interface `PooledDataSourceFactory` does not expose this info.  Per [a dropwizard-dev message](https://groups.google.com/forum/#!topic/dropwizard-dev/4-N8ahwLFy0), adding this to the new interface shouldn't be an issue for any current or future implementations - they all will be JDBC connection pools, and will all need a DB URL to function.

I have a PR ready, if nobody objects.

**Comment by jplock** [comment]
That sounds great
