### ISSUE TITLE
ClassCastException using @Valid on getter with Optional field

### ISSUE THREAD

**Issue by scho** [dropwizard/dropwizard#1432]
In our project, we have the situation that we internally store values in (Java8) ```Optional``` types in order to make it easier, to pick one over the other in case one is not set. Validation using ```@Valid``` fails though.

We are currently using DW ```0.9.2```.

Our solution for now is to not use Optional in this case. Then, everything works as expected.

Here is an example:
```java
class Record {
  private Optional<String> field;
  private Optional<String> alternativeForField;

  @NotNull
  @Valid
  public String getField(){
    return field.orElse(alternativeForField.orElse(null));
  }
}
```

Here is the stack trace:
```
Stacktrace was: java.lang.ClassCastException: java.lang.String cannot be cast to java.util.Optional
	at org.hibernate.validator.internal.engine.valuehandling.OptionalValueUnwrapper.handleValidatedValue(OptionalValueUnwrapper.java:20)
	at org.hibernate.validator.internal.engine.ValidatorImpl.getValue(ValidatorImpl.java:1609)
	at org.hibernate.validator.internal.engine.ValidatorImpl.validateCascadedConstraints(ValidatorImpl.java:622)
	at org.hibernate.validator.internal.engine.ValidatorImpl.validateInContext(ValidatorImpl.java:415)
	at org.hibernate.validator.internal.engine.ValidatorImpl.validate(ValidatorImpl.java:204)

```

**Comment by jplock** [comment]
Are you trying to deserialize your `Record` object with Jackson? Have you tried a Dropwizard 1.0.0 snapshot which supports Java8 natively?

**Comment by scho** [comment]
I deserialize it using Jackson and then I validate the record using Hibernate:
```java
Validation.byProvider(HibernateValidator.class).configure().buildValidatorFactory().getValidator().validate(record);
```
All the Java8 Optional stuff works with Jackson.

**Comment by joschi** [comment]
@scho With Dropwizard 0.9.x you'll need to add the [dropwizard-java8](https://github.com/dropwizard/dropwizard-java8) bundle to your project.

**Comment by nickbabcock** [comment]
I'm assuming this isn't an issue anymore, so I'l close this.

Reply back otherwise, and I'll open it back up.

**Comment by scho** [comment]
I've tried to reproduce with a minimal example, but I couldn't reproduce it. This issue is somehow related to our project setup, but I don't know what exactly caused it.

Thanks for looking into it anyways.

**Comment by scho** [comment]
FYI: Upgrading to dropwizard ```1.0.3``` finally fixed the issue for us.
