### ISSUE TITLE
Ability to add interceptors to Instrumented Apache's Http Client

### ISSUE THREAD

**Issue by skstronghold** [dropwizard/dropwizard#1441]
`HttpClientBuilder` for instrumented Apache's Http-Client doesn't provides an api to add interceptors. Vanilla `HttpClientBuilder` from Apache's Http-Client exposes this functionality via an API.

**Comment by jplock** [comment]
Are you interested in `addInterceptorFirst` and `addInterceptorLast` or `setHttpProcessor`?

**Comment by skstronghold** [comment]
`addInterceptorFirst` and `addInterceptorLast`. Basically, I want to intercept tracing info for each request/response using Zipkin.

**Comment by jplock** [comment]
Ok cool.  I'd love to see a `dropwizard-zipkin` bundle or something.  I found https://github.com/rojanu/dropwizard-brave which looks like it hooks into Jersey.

**Comment by jplock** [comment]
This is going to be difficult to implement without exposing a lot more of the internals of Apache's `HttpClientBuilder` into Dropwizard's.  If you'd like this functionality, could you please submit a pull request?  My main worry is we end up duplicating a lot of the options from Apache's builder into the Dropwizard builder and maintenance will be difficult.

**Comment by skstronghold** [comment]
I would love to work on this feature in my spare time. Can you give me a basic idea of what all needs to be done?

**Comment by jplock** [comment]
I'd start with forking this project in github and review https://github.com/dropwizard/dropwizard/blob/master/CONTRIBUTING.md.  Once your code is ready, feel free to submit a pull request against your fork/branch which we can review.

**Comment by jplock** [comment]
Completely forgot about this issue.  For anyone that ends up here, I'm maintaining https://github.com/smoketurner/dropwizard-zipkin now if people are interested in hooking into Zipkin.

**Comment by nickbabcock** [comment]
Solved by #1860 and dropwizard-zipkin.
