### ISSUE TITLE
Pickled Graphite reporter for Dropwizard Metrics

### ISSUE THREAD

**Issue by skstronghold** [dropwizard/dropwizard#1442]
Metrics library allows reporting of pickled metrics to Graphite. Having a Pickled Graphite reporter available in `dropwizard-metrics-graphite` will enables users to choose this functionality

**Comment by nickbabcock** [comment]
If you want to write this functionality I'll be more than happy to take a look at it. The graphite documentation does give the illusion that using the pickled format is much more efficient (so dropwizard users should have this option available to them), though I haven't seen the line based reporter ever be a problem.
