### ISSUE TITLE
Java 8 - OptionalValidatedValueUnwrapper supports Optional but no classes exist for OptionalInt, OptionalLong, etc

### ISSUE THREAD

**Issue by michaelbraun** [dropwizard/dropwizard#1447]
The Java 8 module `OptionalValidatedValueUnwrapper` supports only `java.util.Optional` and there should be additional classes created for `OptionalInt`, `OptionalLong`, and `OptionalDouble`. This is necessary so `@UnwrapValidatedValue` works and can unwrap `OptionalInt` variables for things like `@Min`, `@Max`, etc. Until this is resolved we need to use `Optional<Integer>`, `Optional<Long>`, `Optional<Double>` for validation to work.

**Comment by jplock** [comment]
I'll submit a PR to address this.

**Comment by jplock** [comment]
How should this work with invalid values? Throw an exception or just be empty?

**Comment by michaelbraun** [comment]
I would think it would work the exact same way as OptionalValidatedValueUnwrapper does for Optional<?> but instead it would do...

```java
@Override
    public Object handleValidatedValue(final OptionalInt optional) {
        if (optional.ifPresent()) {
           return optional.getAsInt(); //This should wrap as an Integer
        }
        return null;
    }
```

Something like that?
