### ISSUE TITLE
Hibernate in 1.0.0-Snapshot

### ISSUE THREAD

**Issue by VanDavv** [dropwizard/dropwizard#1450]
All the imports which worked fine in 0.9.2 are now incorrect in 1.0.0-Snapshot, where did the packages go?

**Comment by joschi** [comment]
@VanDavv What do you mean by incorrect? We've upgraded to Hibernate 5 in Dropwizard 1.0.0 while previous versions were using Hibernate 4.

**Comment by nickbabcock** [comment]
Closing due to lack of communication.
