### ISSUE TITLE
Redirect within WebApplicationException response no longer works

### ISSUE THREAD

**Issue by tumbarumba** [dropwizard/dropwizard#1453]
The change to "[Format WebApplicationException](https://github.com/dropwizard/dropwizard/commit/930443a5bc5760c3319bedf7b36e13810bf0dd8e#diff-235351c1b64afb2dba6188b2bd0c5386)" caused redirects in the response of WebApplicationException to no longer work.

I have created PR dropwizard/dropwizard#1452 to fix this issue.

**Comment by nickbabcock** [comment]
Closed by #1452
