### ISSUE TITLE
Default JerseyRootPath

### ISSUE THREAD

**Issue by qinfchen** [dropwizard/dropwizard#1454]
I noticed that with this PR, https://github.com/dropwizard/dropwizard/commit/c436e5e28406ece6ae1250be3268a638ed90bc5b, the default root path is changed from `/` to '/*'. Is that the expected? if so, should that be mentioned in the 1.0 changelog/release notes?

**Comment by jplock** [comment]
I believe they are equivalent, even though we've gone back and forth on this topic a lot.  :)

**Comment by qinfchen** [comment]
i see, thanks.
