### ISSUE TITLE
Recreating a Http Client throws IllegalArgumentException: A metric named * already exists

### ISSUE THREAD

**Issue by scho** [dropwizard/dropwizard#1457]
In our application, we re-create the http client using the `JerseyClientBuilder` from time to time because it's configured with Basic Authentication credentials, which may change over time.

Doing so after the first time throws a `IllegalArgumentException` though:
```
java.lang.IllegalArgumentException: A metric named org.apache.http.conn.HttpClientConnectionManager.my.package.available-connections already exists
```

Is their a way to prevent this from happening?

**Comment by joschi** [comment]
Sounds similar to #832 and #1258.

**Comment by scho** [comment]
We've experienced, that recreating clients from time to time is not a good idea, because it leaks resources (we even had performance issue). So all our clients are singletons now.
