### ISSUE TITLE
Allow Multiple Roles in Authorizer.authorize method 

### ISSUE THREAD

**Issue by akdev** [dropwizard/dropwizard#1458]
@RolesAllowed takes a string array as a parameter for roles however the Authorizer.authorize method takes a single string. It would be great if the Authorizer interface took an array of strings for roles as well.

**Comment by jplock** [comment]
Mind submitting a pull request to resolve this?

**Comment by prabhjot85** [comment]
I would like to take this up. However, want to understand the expectation on the possible implementations. In a real use case, the expectation would be that user has access on all roles OR at least one of those OR should both implementations need to be provided (in example app e.g.)?

**Comment by psamsotha** [comment]
Normally you would use the authorizer with the Jersey `RolesAllowedDynamicFeature`. How it works is that the filter gets the roles from the `@RolesAllowed` annotation, and iterates over the array, calling the `SecurityContext#isUserInRole(String role)` method each iteration. DW's implementation of `SecurityContext` simply delegates the `isUserInRole` call to the authorizer's` authorize method, passing in a single String. In pseudo code

```java
Authorizer authorizer ...
SecurityContext context ...
    @Override
    public boolean isUserInRole(String role) {
        return authorizer.authorize(role);
    }
...
RolesAllowed annotation ...
String[] roles = annotation.value();
for (String role: roles) {
     if (context.isUserInRole(role)) {
         ...
     }
}
```

So unless you plan on explicitly using/calling the authorizer yourself, I'm not sure what the use would be. @akdev do you have a specific use case for this? Just curious.

**Comment by akdev** [comment]
@psamsotha I think this solves my use case  thank you. An example like this in the docs would be very useful.
