### ISSUE TITLE
How to view custom 404 page

### ISSUE THREAD

**Issue by kedarjavalkar** [dropwizard/dropwizard#1461]
Hi, can anyone point me how to view my custom 404 page. I searched and tried implementing `ExceptionMapper<RuntimeException>` but this did not work. 
I'm using 0.8.1 version

**Comment by kedarjavalkar** [comment]
I got it working by
```
public class RuntimeExceptionMapper implements ExceptionMapper<NotFoundException> {
	@Override
	public Response toResponse(NotFoundException exception) {
		Response defaultResponse = Response.status(Status.OK)
				.entity(JsonUtils.getErrorJson("default response"))
				.build();

		return defaultResponse;
	}
}
```

This only works on incorrect APIs and not on resource calls

my steup : 
```
@Override
public void initialize(Bootstrap<WebConfiguration> bootstrap) {
	bootstrap.addBundle(new AssetsBundle("/webapp", "/", "index.html"));
}

@Override
public void run(WebConfiguration configuration, Environment environment) throws Exception {
	environment.jersey().register(RuntimeExceptionMapper.class);
	((AbstractServerFactory) configuration.getServerFactory()).setJerseyRootPath("/api/*");
	
	// Registering Resources
	environment.jersey().register(new AuditResource(auditDao));
	....
}
```

Now, 
`http://localhost:8080/api/rubish` goes through overridden ExceptionMapper method
`http://localhost:8080/rubish.html` results in default 404 page

how do i setup so that whenever unknown pages are requested dropwizard will show up a custom 404 page

**Comment by prabhjot85** [comment]
You can write an implementation of ContainerResponseFilter and tweak the response in the filter as per your requirement.

```
public class NotFoundResponseFilter implements ContainerResponseFilter {
    @Override
    public void filter(ContainerRequestContext requestContext, ContainerResponseContext responseContext) throws IOException {
        if(responseContext.getStatus() == 404){
            responseContext.setEntity("This page is not found;");
        }
    }
}
```
HTH

**Comment by kedarjavalkar** [comment]
Appreciate your help., but `http://localhost:8080/api/rubish` is caught using `ContainerResponseFilter`
I need to catch static html page requests that are failed(404).. the URL would be `http://localhost:8080/rubish.html`

**Comment by bladecatcher** [comment]
Can you try `http://localhost:8080/api/rubbish.html` ?

If that returns a valid response, maybe you could make your server rootPath "/" instead of "/api" ?

**Comment by kedarjavalkar** [comment]
Do you mean changing `bootstrap.addBundle(new AssetsBundle("/webapp", "/", "index.html"));` to
`bootstrap.addBundle(new AssetsBundle("/webapp", "/api", "index.html"));`  ?

I tried above change and this resulted into 
`java.lang.IllegalStateException: Multiple servlets map to path: /api/*: assets,org.glassfish.jersey.servlet.ServletContainer-2d82408` 
error which failed to start Dropwizard

**Comment by kedarjavalkar** [comment]
I changed server rootPath to "/" and now paths that are configured under resources are served as static html page request
Example: `http://localhost:8080/api/valid` is a registered resource's path and Dropwizard is looking for a similar page in assets directory

**Comment by michaelkrnac** [comment]
Iam also try to find a way to serve custom 404 pages for not available assets.

I found this post https://groups.google.com/forum/#!searchin/dropwizard-user/custom$20404%7Csort:relevance/dropwizard-user/mE17ednUCMM/ZuPKkhBdAAAJ

But it is not working for me


```
    @Override
    public void run(CertConfiguration configuration, Environment environment) {
    	
         // init Error pages
    	 final ErrorPageErrorHandler epeh = new ErrorPageErrorHandler();
         // 400 - Bad Request, leave alone
         epeh.addErrorPage(401, "/error/general-error");
         epeh.addErrorPage(402, "/error/general-error");
         epeh.addErrorPage(403, "/error/403");
         epeh.addErrorPage(404, "/error/404");
         epeh.addErrorPage(405, 499, "/error/general-error");
         epeh.addErrorPage(500, 599, "/error/general-error");
         environment.getApplicationContext().setErrorHandler(epeh);
         environment.getAdminContext().setErrorHandler(epeh);
         
         ErrorResource  errorResource = new ErrorResource();
         environment.jersey().register(errorResource);
```


Is there a way to set Custom 404 Error Pages?

**Comment by arteam** [comment]
Have you tried to set up your API on a different path, so `JsonProcessingExceptionMapper` doesn't kick in? It can be done with the `rootPath` parameter in the YML config. Another option is to try to disable default exception mappers by setting the `registerDefaultExceptionMappers` parameter to false.

**Comment by michaelkrnac** [comment]
Thanks a lot. Works for me.

1. Add to XYZconfig.yml
```
server:
  registerDefaultExceptionMappers: false
```

2. Add to XYZApplication.java

```
    @Override
    public void run(CertConfiguration configuration, Environment environment) {
    	
        // init Error pages
    	 final ErrorPageErrorHandler epeh = new ErrorPageErrorHandler();
         // 400 - Bad Request, leave alone
         epeh.addErrorPage(401, "/error/general-error");
         epeh.addErrorPage(402, "/error/general-error");
         epeh.addErrorPage(403, "/error/403");
         epeh.addErrorPage(404, "/error/404");
         epeh.addErrorPage(405, 499, "/error/general-error");
         epeh.addErrorPage(500, 599, "/error/general-error");
         environment.getApplicationContext().setErrorHandler(epeh);
         environment.getAdminContext().setErrorHandler(epeh);
         
         ErrorResource  errorResource = new ErrorResource();
         environment.jersey().register(errorResource);
```

3. Add to ErrorResource.java
```
@Path("/error")
public class ErrorResource {

    public ErrorResource () {
    }

    @Path("404")
    @GET
    @Timed
    @Produces(MediaType.TEXT_HTML)
    public Response error(){
        return Response.status(404).entity(new ErrorView()).build();
    }
```

Works with assets and API.
So maybe this issue can be closed?

**Comment by arteam** [comment]
Glad it works for you! I am closing the issue.

**Comment by kedarjavalkar** [comment]
Instead of returning VIEW, I am using `return Response.seeOther(new URI("/index.html")).build();`
Thanks all while I was offline :)
