### ISSUE TITLE
Validation failing

### ISSUE THREAD

**Issue by patrickreck** [dropwizard/dropwizard#1464]
I've followed the example [here](http://www.dropwizard.io/0.9.2/docs/manual/validation.html), however I am getting an empty `204 No Content` instead of a proper error message.

It's working as expected when I provide the name.

This is my resource method:
```
    @POST
    @Path("/register-user")
    public User registerUser(@Valid User user) {
        return user;
    }
```

This is my `User` model:
```
public class User {

    @NotEmpty
    private final String name;

    @JsonCreator
    public User(@JsonProperty("name") String name) {
        this.name = name;
    }

    @JsonProperty("name")
    public String getName() {
        return name;
    }

}
```

Am I doing something wrong, or is this not working as intended?

**Comment by joschi** [comment]
`@Valid` doesn't include a null-check, so maybe you want to add `@NotNull` to your method declaration.

If that's not what you mean, please elaborate on the problem and tell us which version of Dropwizard you're using and provide some example code.

**Comment by patrickreck** [comment]
I see. Adding `@NotNull` did the trick. I expected that it would be automatic since there is no default parameter. Thanks!
