### ISSUE TITLE
Poor documentation for file logging

### ISSUE THREAD

**Issue by KonstantinYegupov** [dropwizard/dropwizard#1465]
The documentation page http://www.dropwizard.io/0.9.2/docs/manual/configuration.html#file is missing:

* a straightforward description of default log rolling policy (happens at midnight etc)
* the maxFileSize option and description of "fixed window" policy

**Comment by KonstantinYegupov** [comment]
(maxFileSize is present in 0.9.2: https://github.com/dropwizard/dropwizard/blob/v0.9.2/dropwizard-logging/src/main/java/io/dropwizard/logging/FileAppenderFactory.java)

**Comment by jplock** [comment]
Mind submitting a pull request to clean it up?

**Comment by KonstantinYegupov** [comment]
It does not need code; you just need to regenerate the documentation from the code.

**Comment by joschi** [comment]
@KonstantinYegupov There's a little more involved, e. g. writing the actual documentation in https://github.com/dropwizard/dropwizard/blob/master/docs/source/manual/configuration.rst for example.

If you're simply looking for the Javadoc of Dropwizard 0.9.2, you'll find that at http://www.dropwizard.io/0.9.2/docs/about/javadoc.html
