### ISSUE TITLE
Validation being skipped on resource methods

### ISSUE THREAD

**Issue by guilhermemt21** [dropwizard/dropwizard#1470]
I realized on my upgrade from version 0.7 to 0.9 that validations are being skipped on resource methods. This seems to be a racing condition problem, since it is happening with some frequency, but not all the time. The JacksonMessageBodyProvider gets executed instead of my custom validation, and as a result no validation is performed.

Example:

    @POST
    @Timed
    @CacheControl(noCache = true, isPrivate = true, noStore = true)
    public Response create(@Context User user, **@Validation** AnyObject anyObject) {
        return ok().build();
    }

**Comment by nickbabcock** [comment]
I'm curious, have you tried 1.0? The [validation logic has been moved from Jackson to Jersey](#1251), so if there is a race condition still, it'd be in Jersey.

**Comment by guilhermemt21** [comment]
Hi @nickbabcock ,
I have not tried the 1.0 yet. Is it possible that a specific new dependency on 0.9.2 affects how custom validations work on resource?

I also suspect that my problem is in the server initialization. Once my server is up, all calls in the resource has the same behavior (or all requests run the my validator, or all skip).

**Comment by guilhermemt21** [comment]
@nickbabcock 

Somehow my validations started working after adding this two lines on my ValidationProvider:

@Provider
@Consumes(MediaType.APPLICATION_JSON)

It seems that now my own validations have precedence against JacksonJasonProvider and everything works like a charm =D
