### ISSUE TITLE
dropwizard-guice integration with Dropwizard 1.0.0

### ISSUE THREAD

**Issue by bladecatcher** [dropwizard/dropwizard#1473]
Hi, 
I'm using Hubspot's dropwizard-guice with DW 0.9.2 without any problems. However, I'm unable to upgrade to 1.0.0-SNAPSHOT, because of certain issues, which I've detailed here: [https://github.com/HubSpot/dropwizard-guice/issues/79#issuecomment-193982950](https://github.com/HubSpot/dropwizard-guice/issues/79#issuecomment-193982950) . Is there anyone who has been able to get this to work?

Thanks for the great library!

**Comment by bladecatcher** [comment]
I've decided to stop using dropwizard-guice, as the road ahead is unclear. I'm falling back on plain old Guice, creating the injector using 

```
injector = Guice.createInjector(...)
``` 

The main reason for using dropwizard-guice was so I could inject into Jersey2 resources. A workaround I've decided to use for now is to manually inject into jersey resources. for example:

```
ExampleResource r = new ExampleResource();
injector.injectMembers(r);
environment.jersey().register(r);
```

Of course, this also means that now I'm dealing with Singleton resource classes , which is not necessarily a bad thing!

**Comment by Randgalt** [comment]
FYI - I wrote a Dropwizard/Guice integration that (AFAIK) works with Dropwizard 1.0.0: http://soabase.io/guice.html

**Comment by spudone** [comment]
This alternative works well for us in 0.9.2 with Jersey 2 resources (appears to pick up where Hubspot left off):

https://github.com/xvik/dropwizard-guicey

**Comment by bladecatcher** [comment]
Thanks for linking me to soabase. Here are the issues I'd run into ,while trying to integrate it with Dropwizard 1.0.0-SNAPSHOT : https://github.com/soabase/soabase/issues/32
