### ISSUE TITLE
Client code generator

### ISSUE THREAD

**Issue by jansoren** [dropwizard/dropwizard#1475]
Hi,
I'm struggling to find a client code generator for Dropwizard apis that generates java code. Does this exist, or should we create one?

**Comment by nickbabcock** [comment]
Sorry, I'm not familiar with such a tool. If you find a tool or make one yourself, we'll be more than happy to add it to the docs.

**Comment by jansoren** [comment]
Just finished creating the code generator and refactored to only use jersey as you suggested @nickbabcock. You can find the plugin here - [REST API Codegenerator Maven Plugin](https://jansoren.github.io/restapi-codegen-maven-plugin/)

**Comment by nickbabcock** [comment]
Cool, is the plugin on maven central or another site? I tried installing the plugin locally as well and ran into the following error:

> 'No mojo definitions were found for plugin: no.jansoren:restapi-codegen-maven-plugin.'

Some current questions (it's ok if not implemented, just curious):

- Query/Form/Path/Cookie parameters?
- HTTP headers?
- Basic Authentication?
- Non-JSON endpoints?

**Comment by jansoren** [comment]
The plugin is not published on maven central yet. 
For now I've only covered the basics, and will later expand the plugin as I work on my application. Hopefully someone will create some pull requests :-)

I do not understand why you get that error. I just cleaned my `.m2` folder, cloned the plugin and ran `mvn clean install`. Did you add the plugin without building the jar locally?

**Comment by jansoren** [comment]
The [REST API Codegenerator Maven Plugin](https://github.com/jansoren/restapi-codegen-maven-plugin) now generates ReactJS code aswell 🙂
