### ISSUE TITLE
Joda Time in v1.0.0?

### ISSUE THREAD

**Issue by m-manu** [dropwizard/dropwizard#1486]
[Release notes of v1.0.0](https://github.com/dropwizard/dropwizard/releases/tag/v1.0.0-rc1) mentions "_Upgraded to Joda-Time 2.9.2_".

If we're targeting first-class Java 8 support in v1.0.0, why use Joda-Time at all? `java.time` library replaces `joda-time` project. 

https://jcp.org/en/jsr/detail?id=310
http://www.joda.org/joda-time/

**Comment by arteam** [comment]
See #1383. We decided to leave Joda-Time support in 1.0.0 to simplify migration of Dropwizard applications from 0.9.x to 1.0.x. Many applications still use Joda-Time extensively, and can't easily
switch to the new Date/Time API (JSR-310). Despite that Stephen Colebourne (the library author) advises users to migrate to the new API, he still maintains the project. So, in fact, Joda-Time has a big user base and constantly updated. For these reasons, we don't want to drop its support.
