### ISSUE TITLE
upgrade from 0.9.2 to 1.0.0-rc1 -- previously working tests fails in the bowels of jetty

### ISSUE THREAD

**Issue by raymerd** [dropwizard/dropwizard#1487]
After upgrade from the 0.9.2 bom to the 1.0.0-rc1 I get an exception from deep in the bowels of jetty.

First, the output from the test under 0.9.2
```
Running io.dropwizard.ext.tests.JettyCrossOriginIntegrationTest
INFO  [2016-03-22 16:31:41,931] org.eclipse.jetty.util.log: Logging initialized @1007ms
INFO  [2016-03-22 16:31:41,996] io.dropwizard.server.ServerFactory: Starting CORSApplication
INFO  [2016-03-22 16:31:42,003] io.dropwizard.server.SimpleServerFactory: Registering jersey handler with root path prefix: /
INFO  [2016-03-22 16:31:42,014] io.dropwizard.server.SimpleServerFactory: Registering admin handler with root path prefix: /admin
INFO  [2016-03-22 16:31:42,056] org.eclipse.jetty.setuid.SetUIDListener: Opened CORSApplication@fd0e5b6{HTTP/1.1}{0.0.0.0:8080}
INFO  [2016-03-22 16:31:42,058] org.eclipse.jetty.server.Server: jetty-9.2.13.v20150730
INFO  [2016-03-22 16:31:42,412] io.dropwizard.jersey.DropwizardResourceConfig: The following paths were found for the configured resources:

    NONE

INFO  [2016-03-22 16:31:42,413] org.eclipse.jetty.server.handler.ContextHandler: Started i.d.j.MutableServletContextHandler@4e628b52{/,null,AVAILABLE}
INFO  [2016-03-22 16:31:42,417] io.dropwizard.setup.AdminEnvironment: tasks = 

    POST    /tasks/log-level (io.dropwizard.servlets.tasks.LogConfigurationTask)
    POST    /tasks/gc (io.dropwizard.servlets.tasks.GarbageCollectionTask)

WARN  [2016-03-22 16:31:42,417] io.dropwizard.setup.AdminEnvironment: 
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!    THIS APPLICATION HAS NO HEALTHCHECKS. THIS MEANS YOU WILL NEVER KNOW      !
!     IF IT DIES IN PRODUCTION, WHICH MEANS YOU WILL NEVER KNOW IF YOU'RE      !
!    LETTING YOUR USERS DOWN. YOU SHOULD ADD A HEALTHCHECK FOR EACH OF YOUR    !
!         APPLICATION'S DEPENDENCIES WHICH FULLY (BUT LIGHTLY) TESTS IT.       !
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
INFO  [2016-03-22 16:31:42,420] org.eclipse.jetty.server.handler.ContextHandler: Started i.d.j.MutableServletContextHandler@173373b4{/admin,null,AVAILABLE}
INFO  [2016-03-22 16:31:42,426] org.eclipse.jetty.server.ServerConnector: Started CORSApplication@fd0e5b6{HTTP/1.1}{0.0.0.0:8080}
INFO  [2016-03-22 16:31:42,426] org.eclipse.jetty.server.Server: Started @1503ms
INFO  [2016-03-22 16:31:42,609] io.dropwizard.ext.tests.JettyCrossOriginIntegrationTest: JettyCrossOriginIntegrationTest target: http://localhost:8080/
127.0.0.1 - - [22/Mar/2016:16:31:42 +0000] "GET / HTTP/1.1" 404 43 "-" "CORSApplication (test client)" 62
INFO  [2016-03-22 16:31:42,821] io.dropwizard.ext.tests.JettyCrossOriginIntegrationTest: JettyCrossOriginIntegrationTest target: http://localhost:8080/
127.0.0.1 - - [22/Mar/2016:16:31:42 +0000] "DELETE / HTTP/1.1" 404 43 "-" "CORSApplication (test client)" 1
INFO  [2016-03-22 16:31:42,826] io.dropwizard.ext.tests.JettyCrossOriginIntegrationTest: JettyCrossOriginIntegrationTest target: http://localhost:8080/
127.0.0.1 - - [22/Mar/2016:16:31:42 +0000] "OPTIONS / HTTP/1.1" 200 - "-" "CORSApplication (test client)" 1
INFO  [2016-03-22 16:31:42,830] io.dropwizard.ext.tests.JettyCrossOriginIntegrationTest: JettyCrossOriginIntegrationTest target: http://localhost:8080/
127.0.0.1 - - [22/Mar/2016:16:31:42 +0000] "OPTIONS / HTTP/1.1" 404 43 "-" "CORSApplication (test client)" 1
INFO  [2016-03-22 16:31:42,833] io.dropwizard.ext.tests.JettyCrossOriginIntegrationTest: JettyCrossOriginIntegrationTest target: http://localhost:8080/
127.0.0.1 - - [22/Mar/2016:16:31:42 +0000] "DELETE / HTTP/1.1" 400 - "-" "CORSApplication (test client)" 1
INFO  [2016-03-22 16:31:42,836] io.dropwizard.ext.tests.JettyCrossOriginIntegrationTest: JettyCrossOriginIntegrationTest target: http://localhost:8080/
127.0.0.1 - - [22/Mar/2016:16:31:42 +0000] "OPTIONS / HTTP/1.1" 404 43 "-" "CORSApplication (test client)" 1
INFO  [2016-03-22 16:31:42,840] io.dropwizard.ext.tests.JettyCrossOriginIntegrationTest: JettyCrossOriginIntegrationTest target: http://localhost:8080/
127.0.0.1 - - [22/Mar/2016:16:31:42 +0000] "GET / HTTP/1.1" 404 43 "-" "CORSApplication (test client)" 2
INFO  [2016-03-22 16:31:42,843] io.dropwizard.ext.tests.JettyCrossOriginIntegrationTest: JettyCrossOriginIntegrationTest target: http://localhost:8080/
127.0.0.1 - - [22/Mar/2016:16:31:42 +0000] "OPTIONS / HTTP/1.1" 200 - "-" "CORSApplication (test client)" 0
INFO  [2016-03-22 16:31:42,850] org.eclipse.jetty.server.ServerConnector: Stopped CORSApplication@fd0e5b6{HTTP/1.1}{0.0.0.0:8080}
INFO  [2016-03-22 16:31:42,851] org.eclipse.jetty.server.handler.ContextHandler: Stopped i.d.j.MutableServletContextHandler@173373b4{/admin,null,UNAVAILABLE}
INFO  [2016-03-22 16:31:42,853] org.eclipse.jetty.server.handler.ContextHandler: Stopped i.d.j.MutableServletContextHandler@4e628b52{/,null,UNAVAILABLE}
Tests run: 8, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 1.647 sec
```

Now after the uprev of drop wizard
```
Running io.dropwizard.ext.tests.JettyCrossOriginIntegrationTest
INFO  [2016-03-22 16:39:03,339] org.eclipse.jetty.util.log: Logging initialized @1129ms
INFO  [2016-03-22 16:39:03,416] io.dropwizard.server.ServerFactory: Starting CORSApplication
INFO  [2016-03-22 16:39:03,422] io.dropwizard.server.SimpleServerFactory: Registering jersey handler with root path prefix: /
INFO  [2016-03-22 16:39:03,432] io.dropwizard.server.SimpleServerFactory: Registering admin handler with root path prefix: /admin
INFO  [2016-03-22 16:39:03,519] org.eclipse.jetty.setuid.SetUIDListener: Opened CORSApplication@158d255c{HTTP/1.1,[http/1.1]}{0.0.0.0:8080}
INFO  [2016-03-22 16:39:03,520] org.eclipse.jetty.server.Server: jetty-9.3.8.v20160314
INFO  [2016-03-22 16:39:03,851] io.dropwizard.jersey.DropwizardResourceConfig: The following paths were found for the configured resources:

    NONE

INFO  [2016-03-22 16:39:03,853] org.eclipse.jetty.server.handler.ContextHandler: Started i.d.j.MutableServletContextHandler@6eb82908{/,null,AVAILABLE}
INFO  [2016-03-22 16:39:03,861] io.dropwizard.setup.AdminEnvironment: tasks = 

    POST    /tasks/log-level (io.dropwizard.servlets.tasks.LogConfigurationTask)
    POST    /tasks/gc (io.dropwizard.servlets.tasks.GarbageCollectionTask)

WARN  [2016-03-22 16:39:03,861] io.dropwizard.setup.AdminEnvironment: 
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!    THIS APPLICATION HAS NO HEALTHCHECKS. THIS MEANS YOU WILL NEVER KNOW      !
!     IF IT DIES IN PRODUCTION, WHICH MEANS YOU WILL NEVER KNOW IF YOU'RE      !
!    LETTING YOUR USERS DOWN. YOU SHOULD ADD A HEALTHCHECK FOR EACH OF YOUR    !
!         APPLICATION'S DEPENDENCIES WHICH FULLY (BUT LIGHTLY) TESTS IT.       !
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
INFO  [2016-03-22 16:39:03,866] org.eclipse.jetty.server.handler.ContextHandler: Started i.d.j.MutableServletContextHandler@6c03fb16{/admin,null,AVAILABLE}
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 1.374 sec <<< FAILURE!
io.dropwizard.ext.tests.JettyCrossOriginIntegrationTest  Time elapsed: 1.373 sec  <<< ERROR!
java.lang.NoClassDefFoundError: org/eclipse/jetty/util/thread/NonBlockingThread
        at org.eclipse.jetty.io.SelectorManager.doStart(SelectorManager.java:258)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
        at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:132)
        at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:106)
        at org.eclipse.jetty.server.AbstractConnector.doStart(AbstractConnector.java:260)
        at org.eclipse.jetty.server.AbstractNetworkConnector.doStart(AbstractNetworkConnector.java:81)
        at org.eclipse.jetty.server.ServerConnector.doStart(ServerConnector.java:244)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
        at org.eclipse.jetty.server.Server.doStart(Server.java:384)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
        at io.dropwizard.cli.ServerCommand.run(ServerCommand.java:43)
        at io.dropwizard.cli.EnvironmentCommand.run(EnvironmentCommand.java:41)
        at io.dropwizard.cli.ConfiguredCommand.run(ConfiguredCommand.java:76)
        at io.dropwizard.testing.DropwizardTestSupport.startIfRequired(DropwizardTestSupport.java:197)
        at io.dropwizard.testing.DropwizardTestSupport.before(DropwizardTestSupport.java:115)
        at io.dropwizard.testing.junit.DropwizardAppRule.before(DropwizardAppRule.java:128)
        at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:46)
        at org.junit.rules.RunRules.evaluate(RunRules.java:20)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
        at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)
        at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)
        at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
        at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
        at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
        at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
        at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
Caused by: java.lang.ClassNotFoundException: org.eclipse.jetty.util.thread.NonBlockingThread
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        ... 31 more


Results :

Tests in error: 
  io.dropwizard.ext.tests.JettyCrossOriginIntegrationTest: org/eclipse/jetty/util/thread/NonBlockingThread

Tests run: 1, Failures: 0, Errors: 1, Skipped: 0
```
For the record, the boiler plate of my test case follows.
```
public class JettyCrossOriginIntegrationTest
{
    private static final String targetURLFormat         = "http://localhost:%d/";
    private static final Logger LOGGER                  = LoggerFactory.getLogger(JettyCrossOriginIntegrationTest.class);
    private static final String ALLOWED_HEADERS_LIST    = "*"; //"Accept, Content-Type, Content-Length, Authorization";
    private static final String ALLOWED_METHODS_LIST    = "GET, OPTIONS, PATCH, POST, PUT";
    private static final String GOOD_ORIGIN             = "allowed_host";
    private static final String BAD_ORIGIN              = "denied_host";

    public static class CORSApplication extends Application<Configuration>
    {

        @Override
        public void run(Configuration configuration, Environment environment) throws Exception {
            FilterRegistration.Dynamic filter = environment.servlets().addFilter("CORSFilter", CrossOriginFilter.class);

            filter.addMappingForUrlPatterns(EnumSet.of(DispatcherType.REQUEST), false, environment.getApplicationContext().getContextPath() + "*");
            filter.setInitParameter(ALLOWED_METHODS_PARAM, ALLOWED_METHODS_LIST);
            filter.setInitParameter(ALLOWED_ORIGINS_PARAM, GOOD_ORIGIN);
            filter.setInitParameter(ALLOWED_HEADERS_PARAM, ALLOWED_HEADERS_LIST);
            filter.setInitParameter(ALLOW_CREDENTIALS_PARAM, "true");
            filter.setInitParameter(CHAIN_PREFLIGHT_PARAM, "false");
            filter.setInitParameter(CrossOriginFilter.ACCESS_CONTROL_EXPOSE_HEADERS_HEADER, "true");
            //filter.setInitParameter(CrossOriginFilter.EXPOSED_HEADERS_PARAM, "X-AUTH-TOKEN");
        }
    }

    @ClassRule
    public static final DropwizardAppRule<Configuration> RULE =
        new DropwizardAppRule<>(CORSApplication.class,
                                    resourceFilePath("configs/jetty-cors-config.yml"));

    @BeforeClass
    public static void setUp()
    {
        System.setProperty("sun.net.http.allowRestrictedHeaders", "true");
        client = new JerseyClientBuilder(RULE.getEnvironment()).build("test client");
    }

    private String buildTargetURI()
    {
        final String targetURI = String.format(targetURLFormat, RULE.getLocalPort());

        LOGGER.info( "JettyCrossOriginIntegrationTest target: " + targetURI);
        return targetURI;
    }

    @Test
    public void allowedOriginPreflightOptions()
    {
        // when
        Response response = client.target( buildTargetURI()).request()
                                  .header("Origin", GOOD_ORIGIN)
                                  .header(ACCESS_CONTROL_REQUEST_METHOD_HEADER, "GET")
                                  .header(ACCESS_CONTROL_REQUEST_HEADERS_HEADER, "Content-Type")
                                  .options();

        // then
        MultivaluedMap<String, Object> headers = response.getHeaders();

        assertThat(headers).contains(MapEntry.entry(ACCESS_CONTROL_ALLOW_ORIGIN_HEADER, asList(GOOD_ORIGIN)));
        assertThat(headers).contains(MapEntry.entry(ACCESS_CONTROL_ALLOW_CREDENTIALS_HEADER, asList("true")));
        assertThat(headers).contains(MapEntry.entry(ACCESS_CONTROL_MAX_AGE_HEADER, asList("1800")));
        assertThat(headers).contains(MapEntry.entry(ACCESS_CONTROL_ALLOW_METHODS_HEADER, asList(ALLOWED_METHODS_LIST)));

        //uncomment this if headers are restricted
        //assertThat(headers).contains(MapEntry.entry(ACCESS_CONTROL_ALLOW_HEADERS_HEADER, asList(ALLOWED_HEADERS_LIST)));

    }
 // test class continues past this point
```

I've slimmed this down a bit and produced the smallest example I could from our actual code.

Thoughts? Guidance?

**Comment by joschi** [comment]
@raymerd Please make sure that there are no conflicting JARs on the class path of your project.

Are you using any third party dependencies in your project? What does the POM of your project look like?

**Comment by raymerd** [comment]
I'll break this up into multiple response for sake of readability ...

Parent pom has the following dependencies:
 
   <properties>
       
        <dropwizard.version>0.9.2</dropwizard.version>
        <junit.version>4.12</junit.version>
        <springplatform.version>2.0.3.RELEASE</springplatform.version>
   <properties>
   <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>io.dropwizard</groupId>
                <artifactId>dropwizard-bom</artifactId>
                <version>${dropwizard.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
            <dependency>
                <groupId>io.spring.platform</groupId>
                <artifactId>platform-bom</artifactId>
                <version>${springplatform.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>

    <dependencies>
        <dependency>
            <groupId>org.assertj</groupId>
            <artifactId>assertj-core</artifactId>
            <version>3.3.0</version>
            <scope>test</scope>
        </dependency>            
        <dependency>
            <groupId>junit</groupId>
            <artifactId>junit</artifactId>
            <version>${junit.version}</version>
            <scope>test</scope>
        </dependency>
    </dependencies>

**Comment by raymerd** [comment]
parent pom includes the bom's for dropwizard and spring platform
       `<!--<dropwizard.version>1.0.0-rc1</dropwizard.version>-->`
        `<dropwizard.version>0.9.2</dropwizard.version>`
        `<springplatform.version>2.0.3.RELEASE</springplatform.version>`

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>io.dropwizard</groupId>
                <artifactId>dropwizard-bom</artifactId>
                <version>${dropwizard.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
            <dependency>
                <groupId>io.spring.platform</groupId>
                <artifactId>platform-bom</artifactId>
                <version>${springplatform.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>

**Comment by raymerd** [comment]
The pom for the module with the failing test case contains the following dependencies.

	<dependencies>
		<dependency>
			<groupId>io.dropwizard</groupId>
			<artifactId>dropwizard-core</artifactId>
		</dependency>
		<dependency>
			<groupId>io.dropwizard</groupId>
			<artifactId>dropwizard-client</artifactId>
		</dependency>
		<dependency>
			<groupId>io.dropwizard</groupId>
			<artifactId>dropwizard-testing</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework</groupId>
			<artifactId>spring-core</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework</groupId>
			<artifactId>spring-beans</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework</groupId>
			<artifactId>spring-context</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework</groupId>
			<artifactId>spring-aspects</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework</groupId>
			<artifactId>spring-web</artifactId>
		</dependency>
	</dependencies>

**Comment by raymerd** [comment]
checking the dependency tree in mvn with the following command line: 

$micron-core draymer$ mvn dependency:tree | grep INFO | sed 's/\[INFO\]//g' | egrep '(\+\-)|(\\\-)' | sed 's/+\-//' | sed 's/\\\-//' | sed 's/\|//g' | sed 's/\ *//' | sort | uniq 

aopalliance:aopalliance:jar:1.0:compile
ch.qos.logback:logback-classic:jar:1.1.3:compile
ch.qos.logback:logback-core:jar:1.1.3:compile
com.fasterxml.jackson.core:jackson-annotations:jar:2.6.0:compile
com.fasterxml.jackson.core:jackson-core:jar:2.6.3:compile
com.fasterxml.jackson.core:jackson-databind:jar:2.6.3:compile
com.fasterxml.jackson.dataformat:jackson-dataformat-yaml:jar:2.6.3:compile
com.fasterxml.jackson.datatype:jackson-datatype-guava:jar:2.6.3:compile
com.fasterxml.jackson.datatype:jackson-datatype-jdk7:jar:2.6.3:compile
com.fasterxml.jackson.datatype:jackson-datatype-joda:jar:2.6.3:compile
com.fasterxml.jackson.jaxrs:jackson-jaxrs-base:jar:2.6.5:compile
com.fasterxml.jackson.jaxrs:jackson-jaxrs-json-provider:jar:2.6.3:compile
com.fasterxml.jackson.module:jackson-module-afterburner:jar:2.6.3:compile
com.fasterxml.jackson.module:jackson-module-jaxb-annotations:jar:2.6.3:compile
com.fasterxml:classmate:jar:1.1.0:compile
com.google.code.findbugs:jsr305:jar:3.0.1:compile
com.google.guava:guava:jar:18.0:compile
commons-codec:commons-codec:jar:1.10:compile
io.dropwizard.metrics:metrics-annotation:jar:3.1.2:compile
io.dropwizard.metrics:metrics-core:jar:3.1.2:compile
io.dropwizard.metrics:metrics-healthchecks:jar:3.1.2:compile
io.dropwizard.metrics:metrics-httpclient:jar:3.1.2:compile
io.dropwizard.metrics:metrics-jersey2:jar:3.1.2:compile
io.dropwizard.metrics:metrics-jetty9:jar:3.1.2:compile
io.dropwizard.metrics:metrics-json:jar:3.1.2:compile
io.dropwizard.metrics:metrics-jvm:jar:3.1.2:compile
io.dropwizard.metrics:metrics-logback:jar:3.1.2:compile
io.dropwizard.metrics:metrics-servlets:jar:3.1.2:compile
io.dropwizard:dropwizard-client:jar:0.9.2:compile
io.dropwizard:dropwizard-configuration:jar:0.9.2:compile
io.dropwizard:dropwizard-core:jar:0.9.2:compile
io.dropwizard:dropwizard-jackson:jar:0.9.2:compile
io.dropwizard:dropwizard-jersey:jar:0.9.2:compile
io.dropwizard:dropwizard-jetty:jar:0.9.2:compile
io.dropwizard:dropwizard-lifecycle:jar:0.9.2:compile
io.dropwizard:dropwizard-logging:jar:0.9.2:compile
io.dropwizard:dropwizard-metrics:jar:0.9.2:compile
io.dropwizard:dropwizard-servlets:jar:0.9.2:compile
io.dropwizard:dropwizard-testing:jar:0.9.2:compile
io.dropwizard:dropwizard-util:jar:0.9.2:compile
io.dropwizard:dropwizard-validation:jar:0.9.2:compile
javax.annotation:javax.annotation-api:jar:1.2:compile
javax.servlet:javax.servlet-api:jar:3.1.0:compile
javax.validation:validation-api:jar:1.1.0.Final:compile
javax.ws.rs:javax.ws.rs-api:jar:2.0.1:compile
joda-time:joda-time:jar:2.9:compile
junit:junit:jar:4.12:test
net.sourceforge.argparse4j:argparse4j:jar:0.6.0:compile
org.apache.commons:commons-lang3:jar:3.4:compile
org.apache.httpcomponents:httpclient:jar:4.5.1:compile
org.apache.httpcomponents:httpcore:jar:4.4.4:compile
org.aspectj:aspectjweaver:jar:1.8.8:compile
org.assertj:assertj-core:jar:3.3.0:test
org.eclipse.jetty.toolchain.setuid:jetty-setuid-java:jar:1.0.3:compile
org.eclipse.jetty:jetty-continuation:jar:9.2.13.v20150730:compile
org.eclipse.jetty:jetty-http:jar:9.2.13.v20150730:compile
org.eclipse.jetty:jetty-io:jar:9.2.15.v20160210:compile
org.eclipse.jetty:jetty-security:jar:9.2.15.v20160210:compile
org.eclipse.jetty:jetty-server:jar:9.2.13.v20150730:compile
org.eclipse.jetty:jetty-servlet:jar:9.2.13.v20150730:compile
org.eclipse.jetty:jetty-servlets:jar:9.2.13.v20150730:compile
org.eclipse.jetty:jetty-util:jar:9.2.13.v20150730:compile
org.eclipse.jetty:jetty-webapp:jar:9.2.13.v20150730:compile
org.eclipse.jetty:jetty-xml:jar:9.2.15.v20160210:compile
org.glassfish.hk2.external:aopalliance-repackaged:jar:2.4.0-b31:compile
org.glassfish.hk2.external:javax.inject:jar:2.4.0-b31:compile
org.glassfish.hk2:hk2-api:jar:2.4.0-b31:compile
org.glassfish.hk2:hk2-locator:jar:2.4.0-b31:compile
org.glassfish.hk2:hk2-utils:jar:2.4.0-b31:compile
org.glassfish.hk2:osgi-resource-locator:jar:1.0.1:compile
org.glassfish.jersey.bundles.repackaged:jersey-guava:jar:2.22.1:compile
org.glassfish.jersey.connectors:jersey-apache-connector:jar:2.22.1:compile
org.glassfish.jersey.containers:jersey-container-servlet-core:jar:2.22.1:compile
org.glassfish.jersey.containers:jersey-container-servlet:jar:2.22.1:compile
org.glassfish.jersey.core:jersey-client:jar:2.22.1:compile
org.glassfish.jersey.core:jersey-common:jar:2.22.1:compile
org.glassfish.jersey.core:jersey-server:jar:2.22.1:compile
org.glassfish.jersey.ext:jersey-bean-validation:jar:2.22.1:compile
org.glassfish.jersey.ext:jersey-metainf-services:jar:2.22.1:compile
org.glassfish.jersey.media:jersey-media-jaxb:jar:2.22.1:compile
org.glassfish.jersey.test-framework.providers:jersey-test-framework-provider-inmemory:jar:2.22.1:compile
org.glassfish.jersey.test-framework:jersey-test-framework-core:jar:2.22.1:compile
org.glassfish:javax.el:jar:3.0.0:compile
org.hamcrest:hamcrest-core:jar:1.3:test
org.hibernate:hibernate-validator:jar:5.2.2.Final:compile
org.javassist:javassist:jar:3.18.1-GA:compile
org.jboss.logging:jboss-logging:jar:3.3.0.Final:compile
org.mockito:mockito-core:jar:1.10.19:test
org.objenesis:objenesis:jar:2.2:compile
org.ow2.asm:asm-debug-all:jar:5.0.4:compile
org.slf4j:jcl-over-slf4j:jar:1.7.12:compile
org.slf4j:jul-to-slf4j:jar:1.7.12:compile
org.slf4j:log4j-over-slf4j:jar:1.7.12:compile
org.slf4j:slf4j-api:jar:1.7.12:compile
org.springframework:spring-aop:jar:4.2.5.RELEASE:compile
org.springframework:spring-aspects:jar:4.2.5.RELEASE:compile
org.springframework:spring-beans:jar:4.2.5.RELEASE:compile
org.springframework:spring-context:jar:4.2.5.RELEASE:compile
org.springframework:spring-core:jar:4.2.5.RELEASE:compile
org.springframework:spring-expression:jar:4.2.5.RELEASE:compile
org.springframework:spring-web:jar:4.2.5.RELEASE:compile
org.yaml:snakeyaml:jar:1.16:compile


I have no classpath set in my environment.

**Comment by joschi** [comment]
@raymerd You're pulling in different versions of Jetty dependencies. Dropwizard 1.0.0 upgraded to Jetty 9.3.x, which doesn't contain the `NonBlockingThread` class anymore.

I guess that the Spring platform or some other dependency is transitively pulling in an incompatible version of some Jetty dependency.

**Comment by raymerd** [comment]
I will look again at the artifacts in my .m2/repository and see what I can find.

**Comment by raymerd** [comment]
Ok, this is a head scratcher -- spring-web depends on jetty 9.3.7 ... the only place I can find the 9.2.x jetty components are transitive dependencies from jetty artifacts included by dropwizard artifacts or in spring boot, which I am not using. 

I will exclude spring boot from things and see what happens.

**Comment by raymerd** [comment]
To close this out for any other folks suffering through this.  The answer is to not use the spring platform "bom".  The simple trick of stating exclusions did not work. Simple direct dependencies does work.

There is joy in mudvill.  Thanks @joschi

**Comment by wsz87** [comment]
I had a quite similar problem after migration from 0.9.2 to 1.0.0 (stable version).
It seems that setting up CORS filter is a little bit different than it used to be.
In version 0.9.2 it looked like that:

            FilterRegistration.Dynamic filter = environment.servlets().addFilter("CORSFilter", CrossOriginFilter.class);

            filter.addMappingForUrlPatterns(EnumSet.of(DispatcherType.REQUEST), false, environment.getApplicationContext().getContextPath() + "*");


and now for 1.0.0:

            FilterRegistration.Dynamic filter = environment.servlets().addFilter("CORSFilter", CrossOriginFilter.class);

            filter.addMappingForUrlPatterns(EnumSet.of(DispatcherType.REQUEST), false, "*");

Context path (environment.getApplicationContext().getContextPath()) is not needed anymore in addMappingForUrlPatterns.
