### ISSUE TITLE
Missing rollbackOnReturn in DataSourceFactory

### ISSUE THREAD

**Issue by patrox** [dropwizard/dropwizard#1488]
While trying to set `rollbackOnReturn` to true in the config, I discovered that such field is not supported,
altough a bit similiar `commitOnReturn` is supported:

```
 * Unrecognized field at: database.rollbackOnReturn
    Did you mean?:
      - commitOnReturn
      - validationQuery
      - validationInterval
      - useFairQueue
      - removeAbandoned
        [30 more]
```

Both of them are available in the properties which can be set for the Tomcat JDBC Pool, which is used as a backing pool:

https://tomcat.apache.org/tomcat-9.0-doc/jdbc-pool.html#Tomcat_JDBC_Enhanced_Attributes

1.) Are there any reasons why it's not supported ?
2.) As I actually would like to have it - can I create a PR which will add it ?

**Comment by jplock** [comment]
No reason I can think of. Please submit a PR and we'll gladly review. Thanks!

**Comment by patrox** [comment]
Testing it right now - once the tests will pass, I'll post a PR.

**Comment by patrox** [comment]
@jplock when you'll have spare 5 minutes, could you please have a look at: https://github.com/dropwizard/dropwizard/pull/1489 ?

I've updated tests & javadoc, to cover the new field.
