### ISSUE TITLE
FileAppenderFactory doesn't support infinite archive option

### ISSUE THREAD

**Issue by devinrsmith** [dropwizard/dropwizard#1491]
`FileAppenderFactory` has

```java
    @Min(1)
    private int archivedFileCount = 5;
```

`TimeBasedRollingPolicy` specifies 

```java
  static final int INFINITE_HISTORY = 0;
```

But I can never set infinite history due to the constraint.

**Comment by joschi** [comment]
@devinrsmith Since there is no such thing as infinite disk space, aiming for an infinite number of archived files might not be the best option.

Are you using other (external) means of rotating the log files?

**Comment by devinrsmith** [comment]
Yes, we are using a different process to deal with deleting the logs.

I don't need `TimeBasedRollingPolicy`s removal machinery... and it seems like since they provide that option, DW should too.
