### ISSUE TITLE
Internal usages of Optional in 1.0.0?

### ISSUE THREAD

**Issue by jplock** [dropwizard/dropwizard#1492]
In 1.0.0, should we settle on using `java.util.Optional` instead of Guava Optional for consistency?

Ex:

- https://github.com/dropwizard/dropwizard/blob/master/dropwizard-jersey/src/main/java/io/dropwizard/jersey/sessions/Flash.java#L22
- https://github.com/dropwizard/dropwizard/blob/master/dropwizard-example/src/main/java/com/example/helloworld/core/Template.java#L17
- https://github.com/dropwizard/dropwizard/blob/master/dropwizard-util/src/main/java/io/dropwizard/util/JarLocation.java#L19
- https://github.com/dropwizard/dropwizard/blob/master/dropwizard-views/src/main/java/io/dropwizard/views/View.java#L51
- https://github.com/dropwizard/dropwizard/blob/master/dropwizard-db/src/main/java/io/dropwizard/db/PooledDataSourceFactory.java#L35
- https://github.com/dropwizard/dropwizard/blob/master/dropwizard-example/src/main/java/com/example/helloworld/resources/PersonResource.java#L50

etc.?  My vote would be to standardize on Java8's `Optional` but there may be some backward compatibility breaks if we do this.

**Comment by patrox** [comment]
@jplock: good idea, with switching to `j.u.Optional`, as:

* DW requires JDK8 anyway, so whoever is(will be) using DW is(will be) on JDK8
* according to [semver](http://semver.org) moving from 0.9.x to 1.0.0 might/will mean braking (incompatible) changes

**Comment by jplock** [comment]
I'll work on submitting a PR for this unless someone else beats me to it.

**Comment by patrox** [comment]
@jplock https://github.com/dropwizard/dropwizard/pull/1493
