### ISSUE TITLE
Add switch syntax to EnvironmentVariableLookup

### ISSUE THREAD

**Issue by jklukas** [dropwizard/dropwizard#1511]
While `EnvironmentVariableLookup` provides a mechanism to inject environment variables into a config, I often want to _switch_ on the env var rather than injecting the env var's value itself. 

It's my understanding that Linux and Windows both forbid the `=` character in environment variable names, which allows us to introduce a new switch syntax to `EnvironmentVariableLookup` without breaking backwards compatibility. 

Consider this YAML snippet:
```yaml
  switchSetting: ${DW_SWITCH_SETTING foo=value-if-foo bar=value-if-bar:-default-value}
```

Because this template contains a `=` character, it would be treated as a switch statement. Cases are separated from one another by whitespace. If `$DW_SWITCH_SETTING` is set to `foo`, then the above would resolve to:
```yaml
  switchSetting: value-if-foo
```

---

Would the community be open to a PR to add this functionality to `EnvironmentVariableLookup`?

I have [a working implementation](https://github.com/dropwizard/dropwizard/compare/master...jklukas:envvar-substitutor?expand=1) that I could polish for submission here.

cc @wrobstory

**Comment by joschi** [comment]
@jklukas I think this adds too much complexity to the configuration file syntax. It should be as simple as possible and this is clearly on the way to transform the simple (?) YAML syntax into a pseudo programming language.

If you need such complex logic in your configuration files, I suggest you'll use a configuration management solution like Ansible, Puppet, or Chef and create your configuration files from a template.

@dropwizard/committers Any other opinions?

**Comment by jplock** [comment]
Agreed. -1 one from me. Thank you for using dropwizard though.

**Comment by nickbabcock** [comment]
Can this be made into a [dropwizard module](http://modules.dropwizard.io/)?

**Comment by jklukas** [comment]
I'm not surprised this is considered too much complexity for base Dropwizard. Thanks for taking the time to consider.

I'll look into the possibility of making a dropwizard module or otherwise releasing this publicly. We've previously been templating configs with mustache and compiling them in a separate step before starting up a service, but the SubstitutingSourceProvider is a nice framework to allow filling out of the template within the same process. We're planning to continue down that path and would like to provide an option for others who want to do the same.

**Comment by jplock** [comment]
If there are method visibility scope changes or new interfaces to be created which would make it easier to do something like this in a module, please let us know.
