### ISSUE TITLE
Change HealthCheck json payload

### ISSUE THREAD

**Issue by arnaud-deprez** [dropwizard/dropwizard#1512]
Hi,

First thanks for your amazing work.
I'd like to propose an enhancement in the HealthCheck payload.

# Current situation
Currently the healthcheck payload, according to this configuration http://www.dropwizard.io/0.9.2/docs/manual/core.html#health-checks, is

```json
{"deadlocks":{"healthy":true},"database":{"healthy":true}}
```

The problem with this payload in a production environment is that we don't know directly if the whole system is healthy or not. Instead we have to check each healthcheck entry and check if the field healthy is true.

# Proposal solution
I think it would be better to have a payload similar to what we have with spring-boot.
For the same configuration in the spring-boot way, I'd have: 

```json
{"status": "UP", "deadlocks":{"status":"UP"},"database":{"status":"UP"}}
```
Where status can be UP, DOWN or UNKNOWN (for example in case we can't find HealthCheck).

I can see 2 advantage with this payload: 

1. There is a global status which is an aggregation of the others (it will be UP if all status is UP, DOWN otherwise). This way, with only one check we can check the system health.
1. It will be the same kind of payload than spring-boot which means we facilitate the life of OPS guys.

What do you think ?
I'd love to contribute it if you want to.

**Comment by mattnelson** [comment]
The health check implementation is supplied by https://github.com/dropwizard/metrics, this would need to  be proposed there. But the implementation already flexes the response status if any of the checks are not healthy.

https://github.com/dropwizard/metrics/blob/3.1-maintenance/metrics-servlets/src/main/java/com/codahale/metrics/servlets/HealthCheckServlet.java#L95-99

**Comment by arnaud-deprez** [comment]
Hi @mattnelson, sorry for my mistake.

By the way, I found this issue https://github.com/dropwizard/metrics/issues/663 which might be a good solution.

Thanks for the information, the status might be a good fit as spring does the same thing (even if they are using 503 instead of 500).
So I'll close this issue and put a +1 on https://github.com/dropwizard/metrics/issues/663.
