### ISSUE TITLE
Hook for writing final substituted config to disk

### ISSUE THREAD

**Issue by jklukas** [dropwizard/dropwizard#1514]
When using a SubstitutingSourceProvider or other ConfigurationSourceProvider that modifies the byte stream of the config file read from disk, it would be helpful to have a hook to write the final modified byte stream to disk (presumably somewhere in tmpDir).

I think the "final" byte stream is generated in [ConfigurationFactory.build()](https://github.com/dropwizard/dropwizard/blob/3d746d21c6e6656a59b26c2a7e92f19e1bb2e9b1/dropwizard-configuration/src/main/java/io/dropwizard/configuration/ConfigurationFactory.java#L90). I don't have a specific design in mind for such a hook, but what I'm looking for is a mechanism to provide a file path where the ConfigurationFactory will attempt to write the stream once it gets created.

This would be useful particularly in the case where the service fails to start up due to some syntax problem with the configuration file. If the stream has been modified, it can be difficult to tell from the source config what's wrong.

I'd be willing to do development work if somebody with more complete knowledge of dropwizard's config machinery can suggest a particular design that would be generically useful.

**Comment by brentryan** [comment]
My preference would be to just get this via a ConfigTask and/or a new config command. We have both of these in our implementation at Cvent and it's worked quite well so far.

**Comment by jklukas** [comment]
@brentryan - Can you go into a little more detail about that? I'm not familiar with ConfigTasks, and it looks like this might be an interface that no longer exists? Is this the same thing as a Task accessible through the admin http port?

**Comment by joschi** [comment]
@jklukas I think @brentryan is referring to (admin) tasks: http://www.dropwizard.io/0.9.2/docs/manual/core.html#tasks

Generally :+1: for this feature (either as a task or on startup).

**Comment by patrox** [comment]
a bit similiar issue: #1156

**Comment by glennmcallister** [comment]
While I too think this is a good idea, and very useful for debugging, be
careful about how you expose credentials. Depending on how and where this
information is exposed, you may end up revealing sensitive information that
was segregated for a reason. Just my 2 cents.

Glenn

**Comment by joschi** [comment]
@glennmcallister Very good argument, thanks for weighing in! Making this feature a task which is not available by default might be the best solution then. So the developers can decide themselves if they want to expose that functionality.

**Comment by jklukas** [comment]
An admin task that needs to be configured sounds like a reasonable approach.

**Comment by brentryan** [comment]
+1
