### ISSUE TITLE
Environment aware ViewRenderer

### ISSUE THREAD

**Issue by pacey** [dropwizard/dropwizard#1518]
I was looking at creating a Pebble view renderer and one of the nice features of Pebble is that you can crunch different parts of a template in parallel. This requires you building a ThreadPoolExecutor and passing it to the Pebble engine. I'd like to have the thread pool be managed by dropwizard and configured from the ViewRenderer. This is currently not possible as the Environment from the ViewBundle is not passed to the ViewRenderer's configure method.

I could quite easily make my own ViewBundle but I thought I'd ask if this is something that might be useful in the core dropwizard-views code. That way my pebble-views library could fit into the "existing" infrastructure along side the handlebars, freemarker etc views.

**Comment by nickbabcock** [comment]
Is this necessary, as wouldn't you just create a custom `ViewRenderer` that would deal with its own `ThreadPoolExecutor`?

**Comment by pacey** [comment]
You indeed could just create a `ThreadPoolExecutor` but I thought it would be nice to use a manged thread pool provided by Dropwizard using `Environment#managedExecutorService`.

**Comment by nickbabcock** [comment]
Ok I see what you mean -- I just had to re-aquiant myself the code. If this would provide tangible benefits then a patch would be accepted
