### ISSUE TITLE
Cannot use two different databases in the same resource method

### ISSUE THREAD

**Issue by vandanagopal** [dropwizard/dropwizard#1531]
I need to access two different databases in the same resource method. I have set up the yml file correctly and the two hibernate bundle variables. All that is working fine. But when it comes to my resource method, I can only annotate it with a UnitOfWork belonging to one hibernateBundle/sessionFactory, so accessing the other database gives a "No session was associated" error.

**Comment by joschi** [comment]
@vandanagopal Please post your question and ideally some accompanying code snippets to the [dropwizard-user mailing list](groups.google.com/forum/#!forum/dropwizard-user).

**Comment by vandanagopal** [comment]
Thanks, posted it on the user group.
