### ISSUE TITLE
Allow lazy loading of ConfigOverride values.

### ISSUE THREAD

**Issue by jkolash** [dropwizard/dropwizard#1532]
This code below is a current workaround the fact that values must be known ahead of time. We are running into an issue where we want to have port numbers be provided dynamically, but they won't be known ahead of time.

```
    static ConfigOverride dynamicConfig(String name, Supplier<String> valueSupplier) {
        ConfigOverride override = Mockito.mock(ConfigOverride.class);

        Mockito.doAnswer((inv)-> {
            ConfigOverride.config(name, valueSupplier.get()).addToSystemProperties();
            return null;
        }).when(override).addToSystemProperties();

        Mockito.doAnswer((inv)-> {
            ConfigOverride.config(name, valueSupplier.get()).removeFromSystemProperties();
            return null;
        }).when(override).removeFromSystemProperties();

        return override;
    }
```

We could easily change the current implementation of ConfigOverride to allow a Supplier instead of a value to work around this specific issue.

It seems like the ConfigOverride implementation isn't really great in terms of changing global system properties rather than having better scoping.

**Comment by nickbabcock** [comment]
Yeah if you want ConfigOverride to take in a supplier that's fine (submit a PR). As long as it doesn't break backwards compatibility, it'll be merged.
