### ISSUE TITLE
Can we inject any class in the filter associated with the dropwizard application

### ISSUE THREAD

**Issue by pritam620** [dropwizard/dropwizard#1533]

**Comment by joschi** [comment]
@pritam620 Could you please elaborate on this on the dropwizard-user mailing list?
https://groups.google.com/forum/#!forum/dropwizard-user

**Comment by pritam620** [comment]
@joschi  I have posted my query on the mailing list at https://groups.google.com/forum/#!topic/dropwizard-user/-zoKO4feIAE
