### ISSUE TITLE
Issues using dropwizard 1.0.0-rc2 with lombok

### ISSUE THREAD

**Issue by santanusinha** [dropwizard/dropwizard#1534]
Couple of issues I noticed, both i think were due to interactions between lombok and jackson:
1. If config classes have @AllArgsConstructor and @Builder annotation at class level, class level defaults are not prepopulated while parsing config YAML file. For example:
```
@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class TestConfig {
    @NotNull
    @NotEmpty
    private String value = "Hello";
}

//Used in config
public class MyConfig extends Configuration {
    @NotNull
    @Valid
    @Getter
    private TestConfig test = new TestConfig();
}
```
If the "test" section is omitted in the YAML, d/w will throw an error

2) Check the issue: https://github.com/FasterXML/jackson-databind/issues/1122

Both might be related as moving the @Builder to a clas level constructor in case 1 fixes the problem.

This breaks code written in even d/w version 0.9.2 and would seem like a critical to me.

Can jackson be upgraded before 1.0.0 release?

**Comment by jakeswenson** [comment]
What version of lombok are you using? Does it work if you change the type from string to something else? either that or try adding another field and let us/me know if it works. I work on paradoxical-io/jackson-lombok which should have been obsoleted with the jackson issue you mention, but we ran into errors with constructor selection.

**Comment by santanusinha** [comment]
Lombok version: 1.16.6

The issue does not depend on type. Adding fields also does not help.

**Comment by nickbabcock** [comment]
I upgraded the main branch to 2.7.4 in 3316980, did you have to give the snapshot a try?

**Comment by santanusinha** [comment]
Not yet. Will try and let you know.

----
Upset the established order, and everything becomes chaos. I'm an agent of
chaos. Oh and you know the thing about chaos, it's fair.

**Comment by nickbabcock** [comment]
I'm optimistically assuming the problem is resolved, if not, reply back.

**Comment by head-thrash** [comment]
Tested 1.0.0-rc2 with overriden jackson-databind, works fine.
