### ISSUE TITLE
NullPointerException when using @Valid with HttpClientConfiguration

### ISSUE THREAD

**Issue by danielfc** [dropwizard/dropwizard#1537]
I faced an NPE when adding `@Valid` to my HTTP client configuration:

```java
  @Valid
  @NotNull
  @JsonProperty("http")
  private HttpClientConfiguration httpClient;
```

The issue is due to `@UnwrapValidatedValue` that is validated for `userAgent` and it's not cleaned up for the next attribute so it tries to apply it to `maxConnections`, for example.

DW version: 0.9.2

```java
    //ValueContext.java #191
	public final Type getTypeOfAnnotatedElement() {
		return validatedValueHandler != null ? validatedValueHandler.getValidatedValueType( typeOfAnnotatedElement ) : typeOfAnnotatedElement;
	}
```

After validating the wrapped attribute, `validatedValueHandler` is no longer null and tries to do the same logic to an `int`, for example, failing in the method below:

```java
   //OptionalValidatedValueUnwrapper.java #26
    public Type getValidatedValueType(Type type) {
        ResolvedType resolvedType = this.resolver.resolve(type, new Type[0]);
        return ((ResolvedType)resolvedType.typeParametersFor(Optional.class).get(0)).getErasedType();
    }
```

In order to reproduce, just add `@Valid` to `HttpClientConfiguration`.

**Comment by nickbabcock** [comment]
I was not able to modify `dropwizard-example` to exhibit said behavior in 1.0 or 0.9.2

**Comment by joschi** [comment]
I'm closing this issue as the original author didn't respond.

@danielfc Feel free to add your comments and we can re-open the issue if's it still a problem in Dropwizard 1.0.0.
