### ISSUE TITLE
can't register exceptionmapper in 0.9.2

### ISSUE THREAD

**Issue by Tandolf** [dropwizard/dropwizard#1541]
**This is my exceptionmapper.**

`@Provider
public class RuntimeExceptionMapper implements ExceptionMapper \<Throwable\> {

    private static final Logger LOG = Logger.getLogger(RuntimeExceptionMapper.class.getName());

    @Override
    public Response toResponse(Throwable exception) {

        Response defaultResponse = Response.status(Response.Status.NOT_FOUND)
                .entity(new ErrorView("/500.mustache"))
                .build();

        if (exception instanceof WebApplicationException) {
            return handleWebApplicationException(exception, defaultResponse);
        }

        LOG.warn(exception.getMessage(), exception);
        return defaultResponse;
    }

    private Response handleWebApplicationException(Throwable exception, Response defaultResponse) {
        WebApplicationException webAppException = (WebApplicationException) exception;

        if (webAppException.getResponse().getStatus() == 404) {
            return Response
                    .status(Response.Status.NOT_FOUND)
                    .entity(new ErrorView("404.mustache"))
                    .build();
        }
        LOG.warn(exception.getMessage(), exception);

        return defaultResponse;
    }
}`

**i have defined:**
`registerDefaultExceptionMappers: false`
in my config.yml and i have checked that it doesn't register any default jersey exceptionmappers.

**I register my exceptionmapper with the lines:**
`RuntimeExceptionMapper runtimeExceptionMapper = new RuntimeExceptionMapper();
 environment.jersey().register(runtimeExceptionMapper);`

**but when i throw:**
`throw new WebApplicationException(response);`

**it deosn't trigger my exception mapper and i get a:**
`{
  "type": "error",
  "message": "No HTTP resource was found that matches the request URI xxxxxxxx."
}`
as response.

What have i missed? what have i done wrong? im loosing my mind here. Is there a bug?

**Comment by scho** [comment]
Isn't the whole idea with the `WebApplicationException` that you don't need an exception mapper?
Have you tried throwing a `RuntimeException`?

**Comment by Tandolf** [comment]
Yes i have tried runtimeexception, i even tried writing an customexception. And exceptionmapped it.

Its like it doesn't register providers at all.

**Comment by scho** [comment]
Have you tried changing the generic type from `Throwable` to something else?

**Comment by Tandolf** [comment]
Yes i have tried "RuntimeException", "NotFoundException" and my own "CustomException".

Is there any way to se that the exceptionmapper actually gets registered at startup

**Comment by scho** [comment]
It shows up in the log file on startup.

**Comment by Tandolf** [comment]
okey, just checked my log, apparantly it doesn't get listed as a provider at startup. Now the question is. Why.

**Comment by scho** [comment]
Have you tried registering `RuntimeExceptionMapper.class` instead of an instance of it?

**Comment by Tandolf** [comment]
yeah and it didn't work

**Comment by Tandolf** [comment]
Okey after much research this is what i have found out.

The order of registration matters. If you register Providers after resources they will not be registered. By raising the my provider to the top of all registered objects it suddenly got registered in the jersey environment.

But disabling Jersey exceptionmappers did work, next problem is that apperantly there is another exceptionmapper underneath that will map out an html-response and the log will log out a warning that there is already a mapper for those exceptions and this one apparently has priority over my mapper.

if not disabling jersey exceptions i get a json-object. when disabling i get an html-response that overrides my mapper.

If i know made an customexception everything suddenly works and i can build my own html.

Bare in mind im only a junior dev so i dont have enough experience concerning this. But if someone could shed some light over the multiple exceptionmappers then please do, i'd love to learn more about it.

**Comment by nickbabcock** [comment]
I was able to create a test project that shows that registration order does not matter (with and without `registerDefaultExceptionMappers=false`), so unless a test can be demonstrated (preferably within this repo), I'm closing this 

I do acknowledge that the docs in this area sorely needs some love, which yours truly will get to.

**Comment by helsing** [comment]
It seems Jersey internally handles any WebApplicationException prior to any custom registered exception mappers. I have not found any way to customize this behavior unfortunately. 
Have a look in the class org.glassfish.jersey.server.ServerRuntime and do a search for 'WebApplicationException' you'll find what happens.
