### ISSUE TITLE
Jackson NoSuchMethodError When Building

### ISSUE THREAD

**Issue by ezweave** [dropwizard/dropwizard#1545]
This was working fine last week, but coming back to do a new build yesterday, I now get some error business when the Test target is hit.  

`java.lang.NoSuchMethodError: com.fasterxml.jackson.annotation.JsonFormat$Value.empty()Lcom/fasterxml/jackson/annotation/JsonFormat$Value;`

Any ideas?

**Comment by ezweave** [comment]
Here's a slightly longer trace.

`java.lang.NoSuchMethodError: com.fasterxml.jackson.annotation.JsonFormat$Value.empty()Lcom/fasterxml/jackson/annotation/JsonFormat$Value;
	at com.fasterxml.jackson.databind.cfg.MapperConfig.<clinit>(MapperConfig.java:50)
	at com.fasterxml.jackson.databind.ObjectMapper.<init>(ObjectMapper.java:535)
	at com.fasterxml.jackson.databind.ObjectMapper.<init>(ObjectMapper.java:452)`

**Comment by joschi** [comment]
@ezweave This looks like some class path problem in your build. Which version of Dropwizard are you using? Which version of Maven? How does your POM look like and the output of `mvn dependency:tree` look like?

**Comment by ezweave** [comment]
Dropwizard 0.9.2, Maven 3.3.9.

Here is my output from `mvn dependency:tree`

`[INFO] io.thegist:the-gist:jar:1.1-SNAPSHOT
[INFO] +- com.alchemy.api:alchemyapi:jar:1.0:compile
[INFO] +- io.dropwizard:dropwizard-core:jar:0.9.2:compile
[INFO] |  +- io.dropwizard:dropwizard-util:jar:0.9.2:compile
[INFO] |  |  +- com.fasterxml.jackson.core:jackson-annotations:jar:2.6.0:compile
[INFO] |  |  +- com.google.guava:guava:jar:18.0:compile
[INFO] |  |  +- com.google.code.findbugs:jsr305:jar:3.0.1:compile
[INFO] |  |  \- joda-time:joda-time:jar:2.9:compile
[INFO] |  +- io.dropwizard:dropwizard-jackson:jar:0.9.2:compile
[INFO] |  |  +- com.fasterxml.jackson.core:jackson-core:jar:2.6.3:compile
[INFO] |  |  +- com.fasterxml.jackson.datatype:jackson-datatype-jdk7:jar:2.6.3:compile
[INFO] |  |  +- com.fasterxml.jackson.datatype:jackson-datatype-guava:jar:2.6.3:compile
[INFO] |  |  +- com.fasterxml.jackson.module:jackson-module-afterburner:jar:2.6.3:compile
[INFO] |  |  +- com.fasterxml.jackson.datatype:jackson-datatype-joda:jar:2.6.3:compile
[INFO] |  |  +- org.slf4j:slf4j-api:jar:1.7.12:compile
[INFO] |  |  \- ch.qos.logback:logback-classic:jar:1.1.3:compile
[INFO] |  +- io.dropwizard:dropwizard-validation:jar:0.9.2:compile
[INFO] |  |  +- org.hibernate:hibernate-validator:jar:5.2.2.Final:compile
[INFO] |  |  |  +- javax.validation:validation-api:jar:1.1.0.Final:compile
[INFO] |  |  |  +- org.jboss.logging:jboss-logging:jar:3.2.1.Final:compile
[INFO] |  |  |  \- com.fasterxml:classmate:jar:1.1.0:compile
[INFO] |  |  \- org.glassfish:javax.el:jar:3.0.0:compile
[INFO] |  +- io.dropwizard:dropwizard-configuration:jar:0.9.2:compile
[INFO] |  |  +- com.fasterxml.jackson.dataformat:jackson-dataformat-yaml:jar:2.6.3:compile
[INFO] |  |  |  \- org.yaml:snakeyaml:jar:1.15:compile
[INFO] |  |  \- org.apache.commons:commons-lang3:jar:3.4:compile
[INFO] |  +- io.dropwizard:dropwizard-logging:jar:0.9.2:compile
[INFO] |  |  +- io.dropwizard.metrics:metrics-logback:jar:3.1.2:compile
[INFO] |  |  +- org.slf4j:jul-to-slf4j:jar:1.7.12:compile
[INFO] |  |  +- ch.qos.logback:logback-core:jar:1.1.3:compile
[INFO] |  |  +- org.slf4j:log4j-over-slf4j:jar:1.7.12:compile
[INFO] |  |  +- org.slf4j:jcl-over-slf4j:jar:1.7.12:compile
[INFO] |  |  \- org.eclipse.jetty:jetty-util:jar:9.2.13.v20150730:compile
[INFO] |  +- io.dropwizard:dropwizard-metrics:jar:0.9.2:compile
[INFO] |  +- io.dropwizard:dropwizard-jersey:jar:0.9.2:compile
[INFO] |  |  +- org.glassfish.jersey.core:jersey-server:jar:2.22.1:compile
[INFO] |  |  |  +- org.glassfish.jersey.core:jersey-common:jar:2.22.1:compile
[INFO] |  |  |  |  +- org.glassfish.jersey.bundles.repackaged:jersey-guava:jar:2.22.1:compile
[INFO] |  |  |  |  \- org.glassfish.hk2:osgi-resource-locator:jar:1.0.1:compile
[INFO] |  |  |  +- javax.ws.rs:javax.ws.rs-api:jar:2.0.1:compile
[INFO] |  |  |  +- org.glassfish.jersey.media:jersey-media-jaxb:jar:2.22.1:compile
[INFO] |  |  |  +- javax.annotation:javax.annotation-api:jar:1.2:compile
[INFO] |  |  |  +- org.glassfish.hk2:hk2-api:jar:2.4.0-b31:compile
[INFO] |  |  |  |  +- org.glassfish.hk2:hk2-utils:jar:2.4.0-b31:compile
[INFO] |  |  |  |  \- org.glassfish.hk2.external:aopalliance-repackaged:jar:2.4.0-b31:compile
[INFO] |  |  |  +- org.glassfish.hk2.external:javax.inject:jar:2.4.0-b31:compile
[INFO] |  |  |  \- org.glassfish.hk2:hk2-locator:jar:2.4.0-b31:compile
[INFO] |  |  |     \- org.javassist:javassist:jar:3.18.1-GA:compile
[INFO] |  |  +- org.glassfish.jersey.ext:jersey-metainf-services:jar:2.22.1:compile
[INFO] |  |  +- org.glassfish.jersey.ext:jersey-bean-validation:jar:2.22.1:compile
[INFO] |  |  +- io.dropwizard.metrics:metrics-jersey2:jar:3.1.2:compile
[INFO] |  |  +- com.fasterxml.jackson.jaxrs:jackson-jaxrs-json-provider:jar:2.6.3:compile
[INFO] |  |  |  +- com.fasterxml.jackson.jaxrs:jackson-jaxrs-base:jar:2.6.3:compile
[INFO] |  |  |  \- com.fasterxml.jackson.module:jackson-module-jaxb-annotations:jar:2.6.3:compile
[INFO] |  |  +- org.glassfish.jersey.containers:jersey-container-servlet:jar:2.22.1:compile
[INFO] |  |  |  \- org.glassfish.jersey.containers:jersey-container-servlet-core:jar:2.22.1:compile
[INFO] |  |  +- org.eclipse.jetty:jetty-server:jar:9.2.13.v20150730:compile
[INFO] |  |  |  +- javax.servlet:javax.servlet-api:jar:3.1.0:compile
[INFO] |  |  |  \- org.eclipse.jetty:jetty-io:jar:9.2.13.v20150730:compile
[INFO] |  |  +- org.eclipse.jetty:jetty-webapp:jar:9.2.13.v20150730:compile
[INFO] |  |  |  \- org.eclipse.jetty:jetty-xml:jar:9.2.13.v20150730:compile
[INFO] |  |  \- org.eclipse.jetty:jetty-continuation:jar:9.2.13.v20150730:compile
[INFO] |  +- io.dropwizard:dropwizard-servlets:jar:0.9.2:compile
[INFO] |  |  \- io.dropwizard.metrics:metrics-annotation:jar:3.1.2:compile
[INFO] |  +- io.dropwizard:dropwizard-jetty:jar:0.9.2:compile
[INFO] |  |  +- io.dropwizard.metrics:metrics-jetty9:jar:3.1.2:compile
[INFO] |  |  +- org.eclipse.jetty:jetty-servlet:jar:9.2.13.v20150730:compile
[INFO] |  |  |  \- org.eclipse.jetty:jetty-security:jar:9.2.13.v20150730:compile
[INFO] |  |  +- org.eclipse.jetty:jetty-servlets:jar:9.2.13.v20150730:compile
[INFO] |  |  \- org.eclipse.jetty:jetty-http:jar:9.2.13.v20150730:compile
[INFO] |  +- io.dropwizard:dropwizard-lifecycle:jar:0.9.2:compile
[INFO] |  +- io.dropwizard.metrics:metrics-core:jar:3.1.2:compile
[INFO] |  +- io.dropwizard.metrics:metrics-jvm:jar:3.1.2:compile
[INFO] |  +- io.dropwizard.metrics:metrics-servlets:jar:3.1.2:compile
[INFO] |  |  \- io.dropwizard.metrics:metrics-json:jar:3.1.2:compile
[INFO] |  +- io.dropwizard.metrics:metrics-healthchecks:jar:3.1.2:compile
[INFO] |  +- net.sourceforge.argparse4j:argparse4j:jar:0.6.0:compile
[INFO] |  \- org.eclipse.jetty.toolchain.setuid:jetty-setuid-java:jar:1.0.3:compile
[INFO] +- io.dropwizard:dropwizard-testing:jar:0.9.2:compile
[INFO] |  +- junit:junit:jar:4.12:compile
[INFO] |  |  \- org.hamcrest:hamcrest-core:jar:1.3:compile
[INFO] |  +- org.mockito:mockito-core:jar:1.10.19:compile
[INFO] |  +- org.objenesis:objenesis:jar:2.2:compile
[INFO] |  +- org.assertj:assertj-core:jar:2.2.0:compile
[INFO] |  \- org.glassfish.jersey.test-framework.providers:jersey-test-framework-provider-inmemory:jar:2.22.1:compile
[INFO] |     +- org.glassfish.jersey.test-framework:jersey-test-framework-core:jar:2.22.1:compile
[INFO] |     +- org.glassfish.jersey.core:jersey-client:jar:2.22.1:compile
[INFO] |     \- org.ow2.asm:asm-debug-all:jar:5.0.4:compile
[INFO] \- org.mongojack:mongojack:jar:2.6.0:compile
[INFO]    +- org.mongodb:mongodb-driver:jar:3.2.1:compile
[INFO]    |  +- org.mongodb:bson:jar:3.2.1:compile
[INFO]    |  \- org.mongodb:mongodb-driver-core:jar:3.2.1:compile
[INFO]    +- com.fasterxml.jackson.core:jackson-databind:jar:2.7.1-1:compile
[INFO]    +- de.undercouch:bson4jackson:jar:2.7.0:compile
[INFO]    +- javax.persistence:persistence-api:jar:1.0.2:compile
[INFO]    \- commons-io:commons-io:jar:2.4:compile`

**Comment by joschi** [comment]
@ezweave Are you using the Maven Shade plugin (or a similar plugin) and with which configuration?

**Comment by jplock** [comment]
Could that Jackson 2.7.1 from the mongo driver be the problem?

**Comment by ezweave** [comment]
@joschi I am.  The config is pretty simple:

<plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-shade-plugin</artifactId>
        <version>2.3</version>
        <configuration>
          <createDependencyReducedPom>true</createDependencyReducedPom>
          <filters>
            <filter>
              <artifact>*:*</artifact>
              <excludes>
                <exclude>META-INF/*.SF</exclude>
                <exclude>META-INF/*.DSA</exclude>
                <exclude>META-INF/*.RSA</exclude>
              </excludes>
            </filter>
          </filters>
        </configuration>
        <executions>
          <execution>
            <phase>package</phase>
            <goals>
              <goal>shade</goal>
            </goals>
            <configuration>
              <transformers>
                <transformer implementation="org.apache.maven.plugins.shade.resource.ServicesResourceTransformer"/>
                <transformer implementation="org.apache.maven.plugins.shade.resource.ManifestResourceTransformer">
                  <mainClass>io.thegist.GistApplication</mainClass>
                </transformer>
              </transformers>
            </configuration>
          </execution>
        </executions>
      </plugin>

**Comment by ezweave** [comment]
@jplock that's what I'm thinking.  I don't know why it just started happening.

**Comment by jplock** [comment]
Can you try excluding Jackson-core there and falling back on the dropwizard version? I ran into a similar issue with the Riak client when trying to use 0.9.2 (https://github.com/basho/riak-java-client/issues/619). 

I'm wondering if we should do another 0.9.x release that just updates Jackson to 2.7.x since some of the methods changed. 

Thoughts @dropwizard-commiters?

**Comment by arteam** [comment]
Probably it makes sense to make another RC before the 1.0.0 release?

**Comment by joschi** [comment]
I'd vote for "fixing" (i. e. update Jackson) only in Dropwizard 1.0.0 and leave Dropwizard 0.9.x as it is now.

**Comment by ezweave** [comment]
Rolling it back fixed it.  MongoJack wanted to use it as well, which just exacerbated the issue.  Should I close this?

**Comment by jplock** [comment]
@ezweave yea I think we should close this for now and direct our efforts on releasing 1.0.0.  Thanks for the report though and for using Dropwizard.
