### ISSUE TITLE
dropwizard-jdbi: JodaDateTimeMapper needs index- and name-based constructors to map columns other than the 1st one

### ISSUE THREAD

**Issue by vdietsch** [dropwizard/dropwizard#1548]
the JodaDateTimeMapper is derived from TypedMapper which has a default constructor that uses column 1 for its mapping.

Our use case needs to map more than 1 column via a JodaDateTimeMapper, which won't work with the current code.

I'd suggest the only things necessary are the following constructor signatures:
```
    public JodaDateTimeMapper() {
// to prevent breaking existing usages.
    }

    public JodaDateTimeMapper(int index) {
        super(index);
    }

    public JodaDateTimeMapper(String name) {
        super(name);
    }

```

**Comment by joschi** [comment]
@vdietsch It's rather unlikely that we release another version of Dropwizard 0.9.x, but I've created a patch for this nonetheless.

FWIW, I'd recommend migrating to Dropwizard 1.0.0 as soon as it's available which also comes with a more recent version of jDBI.
