### ISSUE TITLE
dropwizard-testing: extract a resource testing helper class from ResourceTestRule

### ISSUE THREAD

**Issue by thomaslee** [dropwizard/dropwizard#1550]
`ResourceTestRule` is an excellent and easy way to test resources in Dropwizard, but sometimes JUnit rules aren't as convenient or flexible as "normal" helper classes might be in tests.

For example, I wanted most of the semantics of `ResourceTestRule`, but I wanted each test in the class to have a slightly different configuration. This is kind of a problem when using `ResourceTestRule` as you're basically "locked in" to the configuration passed to its constructor for entire test case/class.

I've got a rough implementation over in https://github.com/thomaslee/dropwizard/tree/tom_rsrc_test_helper but am opening this ticket for discussion (shame on me for starting on the patch before reading the guidelines for contributing).

The strategy taken is:
1. Extract `ResourceTestHelper` from `ResourceTestRule`.
2. Reimplement `ResourceTestRule` using the new `ResourceTestHelper` class.
3. Now `dropwizard-testing` users can choose the class most appropriate to their test(s).

Example usage winds up looking something like this:

https://github.com/thomaslee/dropwizard/blob/4e758c773631c5401af6e7a45b5d427b240dd66a/dropwizard-testing/src/test/java/io/dropwizard/testing/app/ResourceTestHelperTest.java#L11-L19

**Comment by nickbabcock** [comment]
Seems like a very nice addition, make a PR please :smile:

**Comment by evnm** [comment]
@thomaslee, is this still something you'd like to tackle?

**Comment by thomaslee** [comment]
Sorry, yes -- ought to be able to pick it up this weekend. 👍

**Comment by nickbabcock** [comment]
This is actually possible nowadays:

```java
@Test
public void TestA() throws Throwable {
    final ResourceExtension resource = Resource.builder()
            .addResource(new DummyResource())
            .build();

    try {
        resource.before();
        assertThat(resource.target("/myfoo").request().get(String.class))
                .isEqualTo("foo");
    } finally {
        resource.after();
    }
}

@Path("/")
public static class DummyResource {
    @GET
    @Path("/myfoo")
    public String foo() {
        return "foo";
    }
}
```
