### ISSUE TITLE
server attribute requestLog does not allow snake case

### ISSUE THREAD

**Issue by a86c6f7964** [dropwizard/dropwizard#1558]
in Dropwizard version 1.0.0-rc2 currently https://github.com/dropwizard/dropwizard/blob/49ea3ed32b01c3990f00a878d665f2cbf384d00f/dropwizard-core/src/main/java/io/dropwizard/server/AbstractServerFactory.java#L266 marks the name of the requestLog property to be explicitly camel case. I am using the SNAKE_CASE jackson extension and it is very un-intuitive to have one random property that is not snake case. 

In my app initialize I am doing
```
bootstrap.getObjectMapper().setPropertyNamingStrategy(PropertyNamingStrategy.SNAKE_CASE);
```
so that all jersey requests with json use snake case (which affects the configuration as well)

**Comment by nickbabcock** [comment]
The problem is that the `@JsonProperty("requestLog")` is needed, else it won't be de/serialized correctly because the property is named differently than what would be auto-detected.

```java
@JsonProperty("requestLog")
public RequestLogFactory getRequestLogFactory() {
    return requestLog;
}
```

And unfortunately the naming strategy only works in:

> in cases where they are not auto-detected and no explicit annotations exist for naming [[docs]](https://fasterxml.github.io/jackson-databind/javadoc/2.7/com/fasterxml/jackson/databind/PropertyNamingStrategy.html)

If there was a way to get the snake casing to work universally without breaking backwards compatibility, I would support that (have you tried [mixins](http://wiki.fasterxml.com/JacksonMixInAnnotations)?)

**Comment by a86c6f7964** [comment]
Ah, I think because of https://github.com/dropwizard/dropwizard/commit/05d3fcdb6f5e15a998b1bf68ce57d829f7c1e6fe I thought that this was new. This problem has been around for a while. Maybe you could do something like
```
/*package*/ void setRequestLog(RequestLogFactory requestLog) {
    this.requestLog = requestLog;
}
```
making it package local, so that jackson could use it, but not breaking any other people that are using the java apis.

**Comment by nickbabcock** [comment]
In the boostrapper you should be able to enable a feature on the mapper that allows for naming strategy to override the `JsonProperty`

```java
mapper.enable(MapperFeature.ALLOW_EXPLICIT_PROPERTY_RENAMING);
```

From the javadocs:

> Feature that when enabled will allow explicitly named properties (i.e., fields or methods annotated with JsonProperty("explicitName")) to be re-named by a PropertyNamingStrategy, if one is configured.
