### ISSUE TITLE
Enhancement to Lifecycle Setup Classes

### ISSUE THREAD

**Issue by isaki-x** [dropwizard/dropwizard#1563]
Greetings,

I noticed that the executor service factories provided in LifecycleEnvironment do not allow you to specify a ThreadFactory directory; instead you must invoke "threadFactory" on the returned builder object. However, the builder creates a default thread factory in its constructor which is waste of time and resources if the code has a ThreadFactory implementation it wants to use instead of your defaults.

I've forked your codebase and created the simplest patch possible to create the functionality I am asking for (which is to specify the thread factory up front to save startup time). This simply adds a constructor the executor builders that allows specifying a ThreadFactory (the existing constructors invoke these new constructors) and exposes this via two new factory methods in LifecycleEnvironment.

Ideally, the thread factory should only be created on the invocation of "build" but this requires a bit of work and may change the behavior for existing users who reuse builders. As such, I opted for the light touch approach specified above.

- isaki-x

**Comment by joschi** [comment]
Closed in #1570.
