### ISSUE TITLE
Enhance PooledDataSourceFactory Interface

### ISSUE THREAD

**Issue by tdakanalis** [dropwizard/dropwizard#1568]
It would be very helpful if the PooledDataSourceFactory interface defined the method:

```
ManagedDataSource build(MetricRegistry metricRegistry, HealthCheckRegistry healthCheckRegistry, String name);
```

Having that, different connection pooling libraries could register their build-in health checks to the registry. For example hikariCP has already implmemented the following health checks https://github.com/brettwooldridge/HikariCP/wiki/Dropwizard-HealthChecks

**Comment by joschi** [comment]
@tdakanalis The `*DataSourceFactory` doesn't have access to the `Environment` or `HealthCheckRegistry` instances of a Dropwizard application.

If you want to automatically register health checks, create a [`ConfiguredBundle<T>`](http://www.dropwizard.io/0.9.2/dropwizard-core/apidocs/io/dropwizard/ConfiguredBundle.html) which has access to the `Environment` instance via its `run()` method.
