### ISSUE TITLE
Can't register custom exceptionmapper

### ISSUE THREAD

**Issue by tanviapte** [dropwizard/dropwizard#1573]
Hi,
I am using dropwizard 0.9.2 for my REST API. Here is my setup.
This is the main app `VehicleService.java`
```
public void run(VehicleServiceConfiguration vehicleServiceConfiguration, Environment environment) throws Exception {
        ConcurrentMap<Integer, Vehicle> vehicleStore = new ConcurrentHashMap<>();
        IVehicleRepository vehicleRepo = new InMemoryVehicleRepository(vehicleStore);
        final VehicleResource resource = new VehicleResource(vehicleRepo);
        environment.jersey().register(new VehicleServiceExceptionMapper());
        environment.jersey().register(resource);
    }
```
So I am registering a `VehicleServiceExceptionMapper` which looks like this:
```
@Provider
public class VehicleServiceExceptionMapper implements ExceptionMapper<VehicleServiceException> {
    public Response toResponse(VehicleServiceException exception) {
        RuntimeException ex = exception.get();
        if (ex instanceof VehicleNotFoundException) {
            VehicleNotFoundException vnfe = (VehicleNotFoundException) ex;
            String responseType;
            if (vnfe.getType() == ResponseType.JSON) {
                responseType = "text/json";
            } else {
                responseType = "text/xml";
            }
            return Response.status(404).entity(vnfe.getMessage()).type(responseType).build();
        }
        return Response.status(500).entity(exception.getMessage()).type("text/json").build();
    }
}    
```
and I read other similar issues here on github and found out i need to disable the default exception mappers in my `config.yaml` like:
```
server:
  registerDefaultExceptionMappers: false
```

so after all this setup, I still don't see my exception mapper being called for `VehicleServiceExceptions`. Here is how I am throwing them:
in `VehicleResource.java`
```
@PUT
    @Consumes(MediaType.APPLICATION_JSON)
    public void updateJson(VehicleJson vehicle) {
        try {
            repository.update(new Vehicle(vehicle));
        } catch (NoSuchElementException ex) {
            throw new VehicleNotFoundException("vehicle id " + vehicle.getId() + " doesn't exist", ResponseType.JSON);
        }
    }
```
I tried adding the default exception mappers back in. When I do that, the `LoggingExceptionMapper` catches my exception and converts it to a default response. My code is here: [https://github.com/tanviapte/VehicleService](url)
From what I see this looks like an issue. I'd be happy to help fix it if there is one. Has anyone run in to this? Is there a known solution to this problem?

**Comment by softarn** [comment]
Possible duplicate: https://github.com/dropwizard/dropwizard/issues/1541

**Comment by nickbabcock** [comment]
Try explicitly registering your exception mapper in `run`. You also won't need to turn off registerDefaultExceptionMappers

Since this is not an issue with dropwizard itself, I'm closing this.
