### ISSUE TITLE
Dagger 2

### ISSUE THREAD

**Issue by Allsimon** [dropwizard/dropwizard#1580]
Is it possible to use Dagger 2 with dropwizard ? 

I keep getting `org.glassfish.hk2.api.UnsatisfiedDependencyException: There was no object available for injection at SystemInjecteeImpl`

[This blog post](https://metabroadcast.com/blog/dagger-through-a-wizard
https://github.com/ljeyaratnam/hello-world) explains how to do it but in [their repo ](https://github.com/ljeyaratnam/hello-world) dagger 2 isn't even used (DI is done by HK2)

My google-fu has failed to find other examples

**Comment by RohanNagar** [comment]
It is possible, I use it in my applications. Check out https://github.com/RohanNagar/thunder

**Comment by nickbabcock** [comment]
Thanks for the link, @RohanNagar. Closing this issue out as it doesn't appear to be an issue with Dropwizard

**Comment by Raghav2211** [comment]
@RohanNagar But this is only works on constructor injection not on field injection. Can you guide how to do via field injection?

**Comment by Raghav2211** [comment]
@RohanNagar  But when i've to change the version of dropwizard from 1.0.0 to 0.7 it works !! is glassfish depedency doing wrong in versioning?
