### ISSUE TITLE
make HealthCheckRegistry pluggable

### ISSUE THREAD

**Issue by gjesse** [dropwizard/dropwizard#1584]
Similar to how the ObjectMapper and MetricsRegistry can be customized/swapped in the bootstrap, I would like to be able do the same with HealthCheckRegistry.

We are attempting add some additional information to the existing health check output, and under the current setup it requires us to pass around a separate registry, which is cumbersome.

**Comment by jplock** [comment]
Will be fixed in 1.0.0 (or the next 1.0.0-rc release)
