### ISSUE TITLE
Unable to unit-test custom ConstraintViolationExceptionMapper

### ISSUE THREAD

**Issue by situokko** [dropwizard/dropwizard#1588]
Related to:
https://github.com/dropwizard/dropwizard/issues/710

If I have "registerDefaultExceptionMappers: false" in my server-configuration, I can replace default ConstraintViolationExceptionMapper with my own, it works ok.

However if I wish to unit-test responses created by that custom mappers, it is not possible with ResourceTestRule as it registers ConstraintViolationExceptionMapper in ResourceTestResourceConfig.configure(), so I cannot overwrite that with my own mapper.

I'd wish some way to change this behaviour.

**Comment by joschi** [comment]
@situokko Could you please post a minimal code example of what you're trying to do?

**Comment by nickbabcock** [comment]
This has been fixed in #1387 for 1.0, which will by default register default exception mappers in the in ResourceTestRule. This is a bug for dropwizard 0.9.x.

**Comment by situokko** [comment]
@nickbabcock Ohh, nice, my bad, didn't notice to set the version number, I am using 0.9.x. I'll switch to 1.0 once the final release comes out!

**Comment by joschi** [comment]
@situokko Feel free to give Dropwizard 1.0.0-rc3 a try.

**Comment by situokko** [comment]
@joschi This would have been the example code

`class MyResourceTest extends TestBase {
    @ClassRule
    public static final ResourceTestRule resources = ResourceTestRule.builder()
        .addProvider(new AuthValueFactoryProvider.Binder<User>(User.class))
        .addProvider(new RestExceptionMapper())
        .addProvider(new MyConstraintViolationExceptionMapper())
        .addResource(injector.getInstance(MyResource.class))
        .build()

    @Test
    public void testSomething() {
        Response res = doRequest(getUser(8).getEmail(), 81, [])

        assertThat(res.getStatus()).isEqualTo(422)

        //readEntity() will fail because response is not instanceof RestErrorView that MyConstraintViolationExceptionMapper
        //but the standard {error: [...]} produced by ConstraintViolationExceptionMapper
        def error = res.readEntity(RestErrorView.class)
        assertThat(error.errorCode).isEqualTo(RestException.ENTITY_VALIDATION_ERROR)
    }
}
`
