### ISSUE TITLE
Expose ability to override ServletConfig values (ex "healthcheckUri" and "pingUri")

### ISSUE THREAD

**Issue by tmack8001** [dropwizard/dropwizard#1589]
It would be great to be able to expose the ability via app.yml to override the AdminServlet.healthcheckUri and AdminServlet.pingServlet to some custom path that we want to expose these on our application. 

This is just a nice to have not a necessary thing as it is cosmetic. Thoughts here are that the codahale classes allow this to happen so they should be expose up through the DropWizard ApplicationConfig classes as well.

Reference: http://stackoverflow.com/questions/26528666/dropwizard-override-the-url-for-the-healthcheck-endpoint

**Comment by trasa** [comment]
It would be useful to override metrics-uri as well; our use case is that for reasons outside of our control we must provide metrics on a url other than :adminport/metrics and do so by adding another MetricsServlet to the environment.admin().

**Comment by cacsar** [comment]
I just ran into this as well, I had hoped to be able to do it via setting init parameters on env.getAdminContext.setInitParameter but it looked as though only a new empty config gets passed to AdminServlet. We have some healthcheck monitoring code that expects results under /health (like Spring),

**Comment by arteam** [comment]
Not a great solution, but you can register a custom health check servlet in `AdminEnvironment`
```java
environment.admin().addServlet("custom-health-check", 
new HealthCheckServlet(environment.healthChecks()))
                .addMapping("/health/*")
```

It will be served alongside the default health check servlet, but on another URI.

**Comment by cacsar** [comment]
Yep, I went with a line similar to that for the present. I'm reasonably interested in fixing it, but I'm not sure when I'll get to it.
