### ISSUE TITLE
Default showDetails in JsonProcessingExceptionMapper to true

### ISSUE THREAD

**Issue by jeremygehrshg** [dropwizard/dropwizard#1597]
After using Dropwizard for 5 months at work now, I discovered this option recently and it's saved hours of debugging and digging through stack traces since then.  It doesn't look like anything is gained by _not_ providing the error field and what the validation issue is, so I think showDetails should be set to true by default.  

Here is the class:
https://github.com/dropwizard/dropwizard/blob/ae9844a80a1ab273b7ccdb35d86fa624ee915d7a/dropwizard-jersey/src/main/java/io/dropwizard/jersey/jackson/JsonProcessingExceptionMapper.java

The same theme might also might apply to LoggingExceptionMapper, but I'm less sure that exposing e.getMessage() or something similar to the client would be the desired behavior.

**Comment by evnm** [comment]
Looking at the history of the file in question, the `showDetails` guard [was introduced in 2014](https://github.com/dropwizard/dropwizard/commit/4fec8a95cc4de3a8f2f87ea4e3437616f19a0d41). @joschi, do you remember what the motivator was for this?

If I were to guess, I'd assume it was to prevent cases where a pathological client could induce large response payloads if a developer was longwinded when writing exception messages. Debatable whether this is a realistic concern, but this file's history shows a similar tack being taken with regard to logging: https://github.com/dropwizard/dropwizard/commit/9f2df976b2b1fda7dfb19fbdfd0c670914791f8a

**Comment by joschi** [comment]
@evnm The idea was to prevent information leakage to malicious clients.

**Comment by jeremygehrshg** [comment]
@joschi How about default to showing the error message without the classpath and have the showDetails flag append the offending class?  I don't think an error message like this wouldn't be useful for anything malicious.

```
{
  "code": 400,
  "message": "Unable to process JSON",
  "details": "Unrecognized field \"foo\" not marked as ignorable"
}
```

**Comment by tmack8001** [comment]
I agree with @jeremygehrshg that providing some information regarding the failure wouldn't be "leaking potentially insecure implementation details" to a malicious actor. Having this available to be configured would greatly ease my integration efforts internally (e.g. having showDetail=true in a development and integration environment while leaving off in a staging and production environment). Instead I'm currently just re-registering this JsonExceptionMapper with jersey a second time and ignoring the warning. 

I'm not sure if defaulting to "true" is really the correct approach, but definitely exposing a way for downstream users to set it up in their configuration files would be ideal.

**Comment by arteam** [comment]
Addressed in #1705

**Comment by tmack8001** [comment]
hopefully this configuration value will help you out @jeremygehrshg once 1.1.0 is upon us

**Comment by jeremygehrshg** [comment]
It will, thanks @tmack8001
