### ISSUE TITLE
@Auth protects the resource but the user is null

### ISSUE THREAD

**Issue by SimonsUnikaNamn** [dropwizard/dropwizard#1609]
Hi,

I am having some issues with the @Auth User user returning null instead of the value which is given in the Authenticator. 

I have tracked it down to 

ParameterValueHelper.getParameterValues which finds a parameter but returns null. 

I am able to protect the resource by checking against a valid token in the authenticator but I am not able to retrieve the user in the resource.

Hope this makes sense

regards

**Comment by SimonsUnikaNamn** [comment]
Found that I had not registered the user class

**Comment by charbonnier666** [comment]
Hi Simons, how do you register user class ? I have same problem

**Comment by SimonsUnikaNamn** [comment]
I forgot but if you check the examples they have you should be able to figure it out, just go step by step. It was probable an extension or annotation of some sort

**Comment by charbonnier666** [comment]
Resolved, I miss this one:

`environment.jersey().register(new AuthValueFactoryProvider.Binder<>(User.class));`
