### ISSUE TITLE
CachingAuthenticator does not block subsequent requests for same authorization

### ISSUE THREAD

**Issue by windbender** [dropwizard/dropwizard#1614]
I have a situation where multiple requests hit the server at roughly the same time, each of these request is using the same authorization.

If the CachingAuthenticator does not yet have an entry for that authorization then each of these requests will fall through to the canonical authenticator.  Coded as it is, this is less efficient than it could be.

Perhaps this should be coded with the CacheLoader pattern, such that following concurrent requests to the cache are blocked until the canonical authenticator has returned a value??

**Comment by jplock** [comment]
We'll happily review a pull request if you can implement this in a backward compatible way and provide adequate tests.

**Comment by nickbabcock** [comment]
#1615 closes this
