### ISSUE TITLE
Running healthcheck on the same port as API routes (i.e. 8080)

### ISSUE THREAD

**Issue by darrenhaken** [dropwizard/dropwizard#1616]
I'd like to be able to run the healthcheck on the standard endpoint rather than via the admin port.
I am trying to set this up with ElasticBeanstalk and it's proving a challenge mapping multiple ports from a load balancer.

I couldn't see how to do this via the documentation. 

Can anyone help?

**Comment by jplock** [comment]
You can do this using the simple server instead of the default server.

**Comment by darrenhaken** [comment]
Do you have an example?






On Fri, Jul 1, 2016 at 5:44 PM -0700, "Justin Plock" <notifications@github.com> wrote:












You can do this using the simple server instead of the default server.

**Comment by darrenhaken** [comment]
It's ok I found one, thanks for your help!






On Fri, Jul 1, 2016 at 5:48 PM -0700, "Darren Haken" <darrenhaken@gmail.com> wrote:










Do you have an example?






On Fri, Jul 1, 2016 at 5:44 PM -0700, "Justin Plock" <notifications@github.com> wrote:












You can do this using the simple server instead of the default server.
