### ISSUE TITLE
Strings are not serialized as JSON by correctly

### ISSUE THREAD

**Issue by leeavital** [dropwizard/dropwizard#1618]
Using the following server on 1.0.0-rc3:

```
import io.dropwizard.Application;
import io.dropwizard.Configuration;
import io.dropwizard.setup.Environment;

import javax.ws.rs.GET;
import javax.ws.rs.Path;
import javax.ws.rs.Produces;
import javax.ws.rs.core.MediaType;

public class Main extends Application<Configuration> {
  public static void main(String[] args) throws Exception {
      new Main().run(args);
  }

    @Override
    public void run(Configuration configuration, Environment environment) throws Exception {
        environment.jersey().register(new TestResource());
    }

    @Path("/")
    public static class TestResource {

        @Path("json-test")
        @Produces(MediaType.APPLICATION_JSON)
        @GET
        public String ping() {
            return "pong";
        }
    }
}
```

I can do the following curl:

```
$HTTP/1.1 200 OK
Date: Sat, 02 Jul 2016 21:48:25 GMT
Content-Type: application/json
Vary: Accept-Encoding
Content-Length: 4

pong%                                                                                                                                                         
```

I think there should be quotes around `pong` to make it well-formed JSON.

**Comment by jplock** [comment]
You'll need to return either a JSON object or array to have the string quoted.

**Comment by leeavital** [comment]
@jplock a string is perfectly valid JSON right? Is there a reason that this is expected behavior?

**Comment by jplock** [comment]
Right, I agree, I just don't think Jackson has ever operated this way. There may be an configuration option to wrap standalone strings though.

**Comment by leeavital** [comment]
Hm. After doing some debugging, it looks like the request is hitting jersey's MessageBodyWriter before the Jackson one that dropwizard registers. 

I think the Jackson message body writer *would* add the quotes, because any Jackson ObjectMapper will add the quotes. 

Is there an easy way to change the ordering so the jackson one comes first?

**Comment by nickbabcock** [comment]
I don't think there is an easy solution to this [see [stackoverflow question](http://stackoverflow.com/questions/12476806/returning-the-json-representation-of-a-string-with-jersey)]

Alternatively, you can have the resource take in the Dropwizard configured mapper as an argument and use the mapper in the endpoint:

```java
private final ObjectMapper mapper;

public SampleResource(ObjectMapper mapper) {
    this.mapper = mapper;
}

@GET
@Path("/jackson")
@Produces(MediaType.APPLICATION_JSON)
public String jacksonString() throws JsonProcessingException {
    return mapper.writeValueAsString("pong");
}

@GET
@Path("/jersey")
@Produces(MediaType.APPLICATION_JSON)
public String jerseyString() {
    return "pong";
}
```
