### ISSUE TITLE
Compile errors on HttpClientBuilder in dropwizard-client-rc1.0.0-rc3

### ISSUE THREAD

**Issue by bruce-genhot** [dropwizard/dropwizard#1628]
The client library depends on metrics-httpclient-3.1.2,  but there is no method ```setValidateAfterInactivity``` in
 
https://github.com/dropwizard/metrics/blob/v3.1.2/metrics-httpclient/src/main/java/com/codahale/metrics/httpclient/InstrumentedHttpClientConnectionManager.java

you can see the compile issue from https://github.com/dropwizard/dropwizard/blob/v1.0.0-rc3/dropwizard-client/src/main/java/io/dropwizard/client/HttpClientBuilder.java, line 399

**Comment by arteam** [comment]
Please, check the version of Apache's `httpclient` in your classpath. The `setValidateAfterInactivity` method is defined in the `PoolingHttpClientConnectionManager` class and should be available since the version 4.4. Dropwizard currently uses version 4.5.2.

**Comment by bruce-genhot** [comment]
@arteam , OK, thanks, going to try that.

**Comment by bruce-genhot** [comment]
It works, thank you.
