### ISSUE TITLE
Return version of Dropwizard JAR on health endpoint

### ISSUE THREAD

**Issue by darrenhaken** [dropwizard/dropwizard#1635]
Is it possible to print the version of the Dropwizard JAR on the health check endpoint?

Or alternatively is there a version endpoint?

**Comment by jplock** [comment]
There isn't one exposed via the health check point as that would have to come from the metrics project.  Personally I've done https://github.com/smoketurner/notification/blob/master/notification-application/src/main/java/com/smoketurner/notification/application/resources/VersionResource.java in my services to expose this (even though its not over the admin port).

**Comment by vvondra** [comment]
It's as easy as to create a new `HealthCheck` implementation with 

```java
 @Override
    protected HealthCheck.Result check() throws Exception {
        return HealthCheck.Result.healthy(getClass().getPackage().getImplementationVersion());
    }
```

Adding this to core is a little tricky since it will print `null` if you did not package the code in a JAR

**Comment by darrenhaken** [comment]
This worked like a charm and it's certainly not needed for the framework
