### ISSUE TITLE
Validation not done with @FormParam NonEmptyStringParam

### ISSUE THREAD

**Issue by mskager** [dropwizard/dropwizard#1636]
```
@POST
@Consumes(MediaType.APPLICATION_FORM_URLENCODED)
public Response addCard(@FormParam("title") @UnwrapValidatedValue NonEmptyStringParam  title,
                        @FormParam("latitude") @NotNull Double latitude,
                        @FormParam("longitude") @NotNull Double longitude,
                        @FormParam("public") @UnwrapValidatedValue BooleanParam publicCard,
                        @FormParam("user_id") @NotNull Integer userId) {
```

The @NotNull notations are unnecessary because they don't work with Double, Boolean or Integer for @FormParams.

We are using Dropwizard version 0.9.3 and we are trying to validate String, double, boolean and int parameters for POST requests. Documentation states the following: "If you have an Optional field or parameter that needs validation, add the @UnwrapValidatedValue annotation on it." and "If you want q to evaluate to Optional.absent() in this situation, change the type to NonEmptyStringParam".

I've tried this but the parameters are not being evaluated. If I pass empty string or no value at all, no evaluation is being made. I expect a 400 Bad request returned to client. But instead I get 500 internal server error because null values are passed on to the method.  Am I missing something or is this a real issue?

Also, @UnwrapValidatedValue BooleanParam does not get evaluated.

Best Regards,
Marcus

**Comment by nickbabcock** [comment]
Hmm, I was not able to replicate any issue by modifying the [validation test cases](https://github.com/dropwizard/dropwizard/tree/38879e612027faf58d840faaeca547e71c9e4fdd/dropwizard-jersey/src/test/java/io/dropwizard/jersey/validation). Here is the checklist that I ran through:

I was able to confirm the following works on current master with form params (1.0.0):
- [x] `@NotNull Double`
- [x] `@NotNull @UnwrapValidatedValue(false) BooleanParam`
- [x] `@NotEmpty @UnwrapValidatedValue NonEmptyStringParam` with absent form param
- [x] `@NotEmpty @UnwrapValidatedValue NonEmptyStringParam` with empty form param

For 0.9.3:
- [x] `@NotNull Double`
- [x] `@NotNull @UnwrapValidatedValue(false) BooleanParam`
- [x] `@NotEmpty @UnwrapValidatedValue NonEmptyStringParam` with absent form param
- [x] `@NotEmpty @UnwrapValidatedValue NonEmptyStringParam` with empty form param

**Comment by mskager** [comment]
I had forgot to add @Produces(MediaType.APPLICATION_JSON). That solved the issue with @NotNull not being evaluated. Sorry for my confusion. Closing ticket.
