### ISSUE TITLE
CachingAuthorizer?

### ISSUE THREAD

**Issue by Jimexist** [dropwizard/dropwizard#1638]
There's already a `CachingAuthenticator` which is awesome, however there's no such thing as caching proxy for authorization yet. The reason/need for this stands similar to that of `CachingAuthenticator`.

I can think of some reasons why one does not want to do that (e.g. audit trails), but having such class would be a helpful option.

So is there a plan yet? Or specific reasons not to include one?

**Comment by evnm** [comment]
It seems to me that many of the concerns one could have about a `CachingAuthorizer` would apply also to `CachingAuthenticator`. For instance, concerns about auditability or credential-revocation are valid in either case. Arguably, the same logic that validates the existence of `CachingAuthenticator` supports the addition of a `CachingAuthorizer`—developers should be allowed to decide for themselves whether or not their application warrants Principal-caching.

I'm curious what the Dropwizard team thinks on the matter.

**Comment by jplock** [comment]
I think it's a good idea. If someone wanted to submit a PR for an optional implementation we'll happily review it.

**Comment by Jimexist** [comment]
thanks for the opinions and comments - I think that PR looks great to me!

**Comment by evnm** [comment]
This issue can now be closed, since #1639 was merged.

**Comment by joschi** [comment]
@evnm Thanks!
