### ISSUE TITLE
Add a factory for reporting with PickledGraphite

### ISSUE THREAD

**Issue by mwhipple** [dropwizard/dropwizard#1642]
Support for sending pickled graphite metrics was added to https://github.com/dropwizard/metrics/blob/3.2-development/metrics-graphite/src/main/java/com/codahale/metrics/graphite/PickledGraphite.java but a complementary factory implementation has not been added to Dropwizard.

(This is a reminder to myself to do this and submit a PR unless its done in the interim)

**Comment by nickbabcock** [comment]
Closing as a duplicate of #1442
