### ISSUE TITLE
Offer pool size increasing ExecutorService through ExecutorServiceBuilder

### ISSUE THREAD

**Issue by scho** [dropwizard/dropwizard#1643]
As described in #834, the situation of the ThreadPoolExecutor and its configuration `maximumPoolSize` is strange. Someone would assume, that new threads are spawn until `maximumPoolSize` is reached, but it does not behave this way. It only spawns new threads if the queue's bound is reached. This is counterintuitive.

Since it would be nice to a thread pool with incrementing number of threads based on load, I'd like to suggest to embed this into `ExecutorServiceBuilder`.

There are already a number of ways (some call them hacks ;)) to achieve this:
http://stackoverflow.com/questions/19528304/how-to-get-the-threadpoolexecutor-to-increase-threads-to-max-before-queueing

If this is something, the dropwizard community would like to see, I would go ahead and try out the one of the solutions described in the SO post.

Of course, any feedback is highly appreciated.

**Comment by evnm** [comment]
This behavior keeps coming up. In addition to #834, #1444 earlier this year updated `maximumPoolSize`'s default value and fixed a related logging issue.

Have you observed this issue causing problems for an application?

Without evidence starvation in production workloads, I don't think Dropwizard is the best home for a custom `ThreadPoolExecutor` implementation. Given that all existing usages of `ExecutorServiceBuilder` are separate from the main server thread pool, any lack of pool growth shouldn't _directly_ impact server throughput. There may be an impact if there's a dropwizard-client RPC in a request path, but this isn't a default case.

We should of course provide the ability to configure custom `ExecutorService`s wherever possible (e.g. [`JerseyClientBuilder.using(ExecutorService)`](https://github.com/dropwizard/dropwizard/blob/3ddb4a92b53e515609ab39c3ba228387b7ccaf61/dropwizard-client/src/main/java/io/dropwizard/client/JerseyClientBuilder.java#L175)), giving any applications that _are_ affected the ability to inject such a queue-size-aware executor.
