### ISSUE TITLE
MetricsReporters not running in EnvironmentCommand

### ISSUE THREAD

**Issue by jmif** [dropwizard/dropwizard#1653]
The reporters via their factory are initialized however it seems that the LifecycleEnvironment is not started and thus the managed reporter object never receives a call to `start()`.  Is this expected?  If so is there a way to achieve reporting metrics via a command? 

Dropwizard 0.9.2.

**Comment by evnm** [comment]
That's a good question.

Based on my reading of this code, `LifecycleEnvironment` [hands management off to Jetty](https://github.com/dropwizard/dropwizard/blob/ac9a7dcb755eff6e7ceec18fa662e107269a73de/dropwizard-lifecycle/src/main/java/io/dropwizard/lifecycle/setup/LifecycleEnvironment.java#L41), so the lifecycle of managed objects is tied to that of the server. In the case of `ServerCommand`, [when the Jetty server is started](https://github.com/dropwizard/dropwizard/blob/ac9a7dcb755eff6e7ceec18fa662e107269a73de/dropwizard-core/src/main/java/io/dropwizard/cli/ServerCommand.java#L43), the managed metrics reporter is too.

I suspect that the reasoning behind this was that metrics are only warranted for long-running processes and the `server` command is the main entry point for an application's long-running process.

To expose metrics in non-`server` commands, one would feasibly extend `LifecycleEnvironment` to handle managed objects differently.

**Comment by jmif** [comment]
Thanks for the information.  I'm currently using a command to run a long running worker inside of our drop wizard env.

Two questions:

1. Is this considered a bad use of a command and if so is there s recommended practice.

2. Would Dropwizard be interested in having support for something like this in LifecycleEnvironment?

On Thu, Jul 28, 2016 at 4:45 PM Evan Meagher

<
mailto:Evan Meagher <notifications@github.com>
> wrote:

a, pre, code, a:link, body { word-wrap: break-word !important; }

That's a good question.

Based on my reading of this code,

LifecycleEnvironment

https://github.com/dropwizard/dropwizard/blob/ac9a7dcb755eff6e7ceec18fa662e107269a73de/dropwizard-lifecycle/src/main/java/io/dropwizard/lifecycle/setup/LifecycleEnvironment.java#L41
, so the lifecycle of managed objects is tied to that of the server. In the case of

ServerCommand

,
https://github.com/dropwizard/dropwizard/blob/ac9a7dcb755eff6e7ceec18fa662e107269a73de/dropwizard-core/src/main/java/io/dropwizard/cli/ServerCommand.java#L43
, the managed metrics reporter is too.

I suspect that the reasoning behind this was that metrics are only warranted for long-running processes and the

server

command is the main entry point for an application's long-running process.

To expose metrics in non-

server

commands, one would feasibly extend

LifecycleEnvironment

to handle managed objects differently.

—

You are receiving this because you authored the thread.

Reply to this email directly,
https://github.com/dropwizard/dropwizard/issues/1653#issuecomment-236057482
, or

**Comment by evnm** [comment]
> 1. Is this considered a bad use of a command and if so is there s recommended practice.

By "a long running worker inside of our drop wizard env", do you mean that you'd like to run a long-running process within the same shell environment/on the same instance as a Dropwizard server?

You could alternatively use a [Task](http://www.dropwizard.io/1.0.0/docs/manual/core.html#tasks). It depends on whether you want your worker to run as its own process separate from your server application (use a Command) or if it can be run concurrently with your server, triggered by an endpoint on the server's admin port (use a Task).

> 2. Would Dropwizard be interested in having support for something like this in LifecycleEnvironment?

This is the second time to my knowledge that the topic of long-running, non-HTTP-server commands have come up recently (the other involved [running a gRPC server](https://github.com/dropwizard/dropwizard/pull/1666)). I think it's an interesting idea that should be discussed, but it would represent a concerted push to expand Dropwizard beyond solely supporting HTTP servers. Given that the project at its core trumpets simplicity and the Unix philosophy ("do one thing well"), I imagine this idea could be contentious.

**Comment by jmif** [comment]
Thanks for the information
