### ISSUE TITLE
How to set a maximum MultiPart Form Data size?

### ISSUE THREAD

**Issue by cgendreau** [dropwizard/dropwizard#1657]
I know `MultiPartFeature` is provided by the `jersey-media-multipart` library but I was wondering if it is possible to set `MultipartConfig` from the Dropwizard `Environment` object or in any other way?

**Comment by joschi** [comment]
@cgendreau If you're talking about [`@MultipartConfig`](https://docs.oracle.com/javaee/7/api/javax/servlet/annotation/MultipartConfig.html), that's not being used by JAX-RS/Jersey/Dropwizard directly as it's for Servlets and not JAX-RS resources.

**Comment by cgendreau** [comment]
My understanding is that I should create my own Servlet with `@MulipartConfig` and register it with `environment.admin().addServlet(...)` ?

My main goal is to set a limit on the `InputStream` I may receive:
```java
@POST
@Consumes(MediaType.MULTIPART_FORM_DATA)
public void uploadFile(@FormDataParam("file") final InputStream inputStream,
                                    @FormDataParam("file") final FormDataContentDisposition contentDispositionHeader){ ...}
```

**Comment by joschi** [comment]
@cgendreau You're mixing up pure Servlets (for which `@MultipartConfig` might work in the right environment) and JAX-RS resources.

There is no equivalent for `@MultipartConfig` in Jersey, as far as I know. You can check the `Content-Length` request header yourself and/or use a length limited input stream to read the request body:
* [`ByteStreams#limit(…)`](https://google.github.io/guava/releases/19.0/api/docs/com/google/common/io/ByteStreams.html#limit(java.io.InputStream, long))
* [`BoundedInputStream`](https://commons.apache.org/proper/commons-io/javadocs/api-2.5/org/apache/commons/io/input/BoundedInputStream.html)

**Comment by cgendreau** [comment]
ah yes sorry, there were 2 different things.

1) This is what I was referring to:
```
MultipartConfigElement mce = new MultipartConfigElement("/tmp", 10, 1, 10);
environment.getApplicationContext().addServlet(FileUploadServlet.class, "/upload").getRegistration().setMultipartConfig(mce);
```
`FileUploadServlet` is my own class.

2) This is indeed part of the JAX-RS resource I had and it is replaced by a plain `FileUploadServlet` in what I mentioned above. It was more a wish to be able to keep the JAX-RS resource but configure the underlying Servlet. This is becoming more a Jersey thing than Dropwizard. Thanks for your suggestions with limited/bounded `InputStream`, that should definitely work even I have to admit I'm not sure what will happen with the "rest" of the stream once we reach the limit (do we need to consume it or we can just return) but, this is again outside of the Dropwizard scope.

Thanks for you help @joschi

**Comment by cgendreau** [comment]
I have just tested a JAX-RS resource combined with a wrapped stream from [ByteStreams#limit(…)](https://google.github.io/guava/releases/19.0/api/docs/com/google/common/io/ByteStreams.html#limit(java.io.InputStream,%20long)) and it works perfectly with a proper Exception handling/mapping.

For the records, Apache [commons-fileupload](https://commons.apache.org/proper/commons-fileupload/streaming.html) can also work directly on a `HttpServletRequest` so it can be easily combined with a JAX-RS resource.

Sorry for the noise, at least it makes some kind of documentation for that.

**Comment by joschi** [comment]
@cgendreau 
> Sorry for the noise, at least it makes some kind of documentation for that.

Additional documentation in form of a pull request would be welcome. 😉

**Comment by pavelkokush** [comment]
One potential problem with ByteStreams#limit(…): It called only after jersey persist full file on disk in something like /var/xxx/MIMEyyy.tmp file. So for big files it will be time consuming and maybe not safe(if server disk not very big)

**Comment by paulrutter** [comment]
Related feature request https://github.com/eclipse-ee4j/jersey/issues/5570
