### ISSUE TITLE
ValidationMethod in dropwizard 1.0.0

### ISSUE THREAD

**Issue by hadi-misagh** [dropwizard/dropwizard#1665]
Upgrading dropwizard from 0.9.1 to 1.0.0. makes @ValidationMethod annotation stop working! any idea about this ?

**Comment by nickbabcock** [comment]
Can you post a short, reproducible snippet of code that demonstrates this issue.

**Comment by joschi** [comment]
@hadi-misagh Did you find the cause of your problem?

**Comment by hadi-misagh** [comment]
@joschi : Yes, in new version its mandatory to add @Valid annotation when you have @validated as well,
https://github.com/dropwizard/dropwizard/pull/1251#issuecomment-142645734

**Comment by hadi-misagh** [comment]
@nickbabcock : thanks , I just found your comment on this issue #1251 (comment). it fixed my issue
