### ISSUE TITLE
requestLog formats with %reqAttribute{someAttibuteName} work intermittently

### ISSUE THREAD

**Issue by tjcutajar** [dropwizard/dropwizard#1672]
When setting a request attribute in a resource and configuring it to be logged via a custom logFormat with %reqAttribute{someAttibuteName} the expected value only gets logged from time to time.

I've done a little digging and it seems [`prepareForDeferredProcessing()`](https://github.com/qos-ch/logback/blob/master/logback-access/src/main/java/ch/qos/logback/access/spi/AccessEvent.java#L576) gets called twice, once from [`io.dropwizard.request.logging.async.AsyncAccessEventAppenderFactory`](https://github.com/dropwizard/dropwizard/blob/3d746d21c6e6656a59b26c2a7e92f19e1bb2e9b1/dropwizard-request-logging/src/main/java/io/dropwizard/request/logging/async/AsyncAccessEventAppenderFactory.java#L22) and from [`ch.qos.logback.core.OutputStreamAppender`](https://github.com/qos-ch/logback/blob/658963544cc08059fc3cec48f5d35f650de5f6df/logback-core/src/main/java/ch/qos/logback/core/OutputStreamAppender.java#L205) where there's a race to set the attributeMap.

DW 1.0

**Comment by evnm** [comment]
Good catch. Pity this Logback codepath isn't thread-safe. Perhaps they're wanting to avoid synchronization because logging tends to be such a hot path. The `DeferredProcessingAware` interface could use a Javadoc.

If I'm understanding the issue correctly, then a fix would be to simply remove the `prepareForDeferredProcessing` invocation in Dropwizard: https://github.com/dropwizard/dropwizard/pull/1678

**Comment by arteam** [comment]
Closed via #1678

**Comment by tjcutajar** [comment]
@evnm @arteam On review this looks a bit trickier than just removing the `prepareForDeferredProcessing()` call. If you run the hello world application in dropwizard-example for instance and hit the /hello-world resource the logging of the requests themselves become inconsistent.

**Comment by tjcutajar** [comment]
There seems to be another race to call [`appendLoopOnAppenders`](https://github.com/qos-ch/logback/blob/658963544cc08059fc3cec48f5d35f650de5f6df/logback-core/src/main/java/ch/qos/logback/core/spi/AppenderAttachableImpl.java#L45) in [`RequestLogImpl`](https://github.com/qos-ch/logback/blob/658963544cc08059fc3cec48f5d35f650de5f6df/logback-access/src/main/java/ch/qos/logback/access/jetty/RequestLogImpl.java#L138) and [`AsyncAppenderBase`](https://github.com/qos-ch/logback/blob/658963544cc08059fc3cec48f5d35f650de5f6df/logback-core/src/main/java/ch/qos/logback/core/AsyncAppenderBase.java#L265) where they both end up calling `doAppend` in  [`UnsynchronizedAppenderBase`](https://github.com/qos-ch/logback/blob/658963544cc08059fc3cec48f5d35f650de5f6df/logback-core/src/main/java/ch/qos/logback/core/UnsynchronizedAppenderBase.java#L60).
