### ISSUE TITLE
It's too hard to turn off Gzip selectively

### ISSUE THREAD

**Issue by LeDominik** [dropwizard/dropwizard#1673]
I wanted to use [Jersey's SSE](https://jersey.java.net/documentation/latest/sse.html) support with Dropwizard 1.0 however just as described in [JERSEY-3000](https://java.net/jira/browse/JERSEY-3000) Dropwizard by _default_ has GZip-Compression. I somehow didn't want to go the easy way (_just turn off Gzip_), so I tried _a lot_:

* modifying response headers in JAX-RS by `@Context`ing all kind of ServletContexts
* intercepting in Jersey with a [Pre-Matching filter](https://jersey.java.net/documentation/latest/filters-and-interceptors.html#d0e9678) as well as a name-bound interceptor
* servlet filters

Digging deeper I finally hit the underlying [Jetty `GzipHandler`](http://www.eclipse.org/jetty/documentation/9.4.x/gzip-filter.html) which happens to have the perfect `excludedPath` (exclude a path from Gzip treatment) *and* [`excludedMimeTypes`](http://download.eclipse.org/jetty/9.3.9.v20160517/apidocs/org/eclipse/jetty/server/handler/gzip/GzipHandler.html) (exclude a MIME type) methods that would not require me to re-create the _positive_ whitelist of stuff that shall be Gzipped (supported in configuration)...

I guess this should be the result of `getApplicationContext().getGzipHandler()` but this one is `null` no matter where in the lifecycle. I ended up learning something about Jetty and came up with this (which works nicely):

```java
//env.getApplicationContext().getGzipHandler(); // <-- this is always null? why?!?
env.lifecycle().addServerLifecycleListener(new ServerLifecycleListener() {
	@Override
	public void serverStarted(Server server) {
		Handler handler = server.getHandler();
		LOG.debug("Disable GZip for SSE: Starting with handler {}", handler);
		while (handler instanceof HandlerWrapper) {
			handler = ((HandlerWrapper) handler).getHandler();
			LOG.debug("Disable GZip for SSE: Found handler {}", handler);
			if (handler instanceof BiDiGzipHandler) {
				LOG.info("Excluding mime-type {} from gzip compression handler", SseFeature.SERVER_SENT_EVENTS);
				((BiDiGzipHandler) handler).addExcludedMimeTypes(SseFeature.SERVER_SENT_EVENTS);
			}
		}
	}
});
```

I really think either MIME type `text/event-stream` should be excluded by default **or** flushing fixed somehow **or** at the blacklist be exposed for configuration **or** some special annotation to whitelist... No idea what is the most _idiomatic_ way...

**Comment by evnm** [comment]
Hello Dominik. Thanks for the report.

I'd rather not change default behavior. I think the best and least-surgical solution would be to simply add accessor methods for excluded paths and MIME types to `io.dropwizard.jetty.GzipHandlerFactory`. This could feasibly be included in the 1.1.0 release of Dropwizard.

Can you clarify what you mean by "flushing fixed somehow?"

Regarding the `getApplicationContext().getGzipHandler()` oddity, it makes sense that it would return `null`, because the GzipHandler installed by Dropwizard _wraps_ the application handler. I was just in this code the other day and noticed [this disclaimer](https://github.com/dropwizard/dropwizard/blob/master/dropwizard-core/src/main/java/io/dropwizard/setup/Environment.java#L182) in Environment.java. I'm not sure why methods intended for internal use were left `public`, but perhaps it was accidental that a path to the `getGzipHandler()` method was left open in the first place.

**Comment by LeDominik** [comment]
Thanks! Regarding flushing -- this is my theory: in the end you have a `org.glassfish.jersey.media.sse.EventOutput` on which implements a `ChunkedOutput<OutboundEvent>` on which you call [`write(event)`](https://jersey.java.net/apidocs/2.9/jersey/org/glassfish/jersey/server/ChunkedOutput.html#write(T)). If you look at the source of this you'll see that it writes out the event as mandated by the SSE standard and then calls [`flushQueue`](http://grepcode.com/file/repo1.maven.org/maven2/org.glassfish.jersey.core/jersey-server/2.19/org/glassfish/jersey/server/ChunkedOutput.java#ChunkedOutput.flushQueue%28%29).

I did not invest the time to find out exactly how this works but my _suspicion_ is (because the GZipHandler has no flush()) that there's just no mechanism to pass on the command: write out your buffers even if they're not yet filled up! So my nice SSE messages are hanging around in the 8kByte GZIP buffer...

Because AFAIK in general there's no reason why you couldn't compress that stream...

**Comment by evnm** [comment]
Would additional GzipHandlerFactory configuration not solve your problem, though? We should focus on a near-term solution which solves your problem before considering wider refactoring work.

While `GzipHandler` has no `flush` method, it does have [a method to enable/disable synchronous flushing](http://download.eclipse.org/jetty/9.3.9.v20160517/apidocs/org/eclipse/jetty/server/handler/gzip/GzipHandler.html#setSyncFlush-boolean-). Perhaps this too could be made configurable in Dropwizard.

This is an interesting case, given that a preference for small, timely messages is fundamentally at odds with message compressibility. It seems to me that the [`Deflator.SYNC_FLUSH`](http://docs.oracle.com/javase/8/docs/api/java/util/zip/Deflater.html#SYNC_FLUSH) behavior might be the closest available option to what you need.

**Comment by LeDominik** [comment]
Nice catch @evnm -- setting `setSyncFlush(true)` works nicely 👍 

However a very fun thing happens in Chrome (53.0.2785.57 beta (64-bit) on OS X to be precise)...

With sync flush enabled everything _works_ (JavaScript receives events) but while the thing is running the inspector _doesn't_ show the events:
<img width="322" alt="gzip with syncflush - no live preview" src="https://cloud.githubusercontent.com/assets/213234/17616211/96316e40-6073-11e6-97ed-2f5528e8fae7.png">
(if you click on preview it shows nothing. Once the stream has _ended_ the "EventStream" tab becomes available)

Turn the _compression off_ and you'll get a live preview:
<img width="308" alt="without compression - live preview 1" src="https://cloud.githubusercontent.com/assets/213234/17616213/96386254-6073-11e6-82cb-c6117b706fd4.png">
Live Preview:
<img width="285" alt="without compression - live preview 2" src="https://cloud.githubusercontent.com/assets/213234/17616212/9634e6b0-6073-11e6-9e8b-637ec3a3a628.png">

But that's really a non-issue. Thinking about it sync-flush is probably fine for most applications because typically we just have JAX-RS resources returning a full JSON (so no chunking at all, everything comes in one "big bang" -- sync-flush makes no difference in this situation) _or_ we're heading for streaming. Granted for big file-download or similar applications it's not-so-great when used incorrectly (= generating lot's of small things).

**Comment by evnm** [comment]
Weird. I have no idea how Chrome populates that EventStream tab, but I imagine that it's outside of Dropwizard's scope.

Shifting discussion over to your PR from here.

**Comment by jimm-porch** [comment]
If you wanted to just completely turn off GZIP in Dropwizard 1.x endpoints, how would you do it?  I'm trying to find out how to do it, it seems like the feature disappeared with 1.x

**Comment by evnm** [comment]
@jimm-porch [`server.gzip.enabled`](http://www.dropwizard.io/1.0.0/docs/manual/configuration.html#gzip) is still present in 1.x and should continue to work.
