### ISSUE TITLE
PoolingClientConnectionManager doesn't pick up HTTPS settings

### ISSUE THREAD

**Issue by moezubair** [dropwizard/dropwizard#1684]
Hi,
There is a bug in PoolingHttpClientConnectionManager that ignores the SSL settings :
https://java.net/jira/browse/JERSEY-3051

Is there a way of manually picking up the SSL settings with Dropwizard? 

Currently I was using:

```java
 private ClientFactory(JerseyClientBuilder builder) {
        PoolingHttpClientConnectionManager connectionManager = new PoolingHttpClientConnectionManager();
        connectionManager.setMaxTotal(100);
        connectionManager.setDefaultMaxPerRoute(20);
        builder.using(new ApacheConnectorProvider());
        builder.withProperty(ApacheClientProperties.CONNECTION_MANAGER, connectionManager);
        client = builder.build(clientName);
    }

**Comment by arteam** [comment]
Dropwizard's Jersey client actually uses the Apache HTTP client built from a YAML configuration file rather than the Jersey internal bridge. So this bug is not relevant to us. Please, see our [docs](http://www.dropwizard.io/1.0.0/docs/manual/configuration.html#tls) how to configure SSL.

**Comment by moezubair** [comment]
Thanks @arteam!

I am able to create a single client, but was not aware that you can also set connection management settings to have a connection pool.
