### ISSUE TITLE
Inconsistent request logging

### ISSUE THREAD

**Issue by tjcutajar** [dropwizard/dropwizard#1686]
I've created this on the back of #1672 where my late comments may have been missed.

The problem looks a bit trickier than just removing the prepareForDeferredProcessing() call. If you run the hello world application in dropwizard-example for instance and hit the /hello-world resource the logging of the requests themselves become inconsistent.

There seems to be another race to call [`appendLoopOnAppenders`](https://github.com/qos-ch/logback/blob/658963544cc08059fc3cec48f5d35f650de5f6df/logback-core/src/main/java/ch/qos/logback/core/spi/AppenderAttachableImpl.java#L45) in [`RequestLogImpl`](https://github.com/qos-ch/logback/blob/658963544cc08059fc3cec48f5d35f650de5f6df/logback-access/src/main/java/ch/qos/logback/access/jetty/RequestLogImpl.java#L138) and [`AsyncAppenderBase`](https://github.com/qos-ch/logback/blob/658963544cc08059fc3cec48f5d35f650de5f6df/logback-core/src/main/java/ch/qos/logback/core/AsyncAppenderBase.java#L265) where they both end up calling `doAppend` in  [`UnsynchronizedAppenderBase`](https://github.com/qos-ch/logback/blob/658963544cc08059fc3cec48f5d35f650de5f6df/logback-core/src/main/java/ch/qos/logback/core/UnsynchronizedAppenderBase.java#L60).

**Comment by tjcutajar** [comment]
Yeah a reproducer would be nice. I will report back if I manage to write a failing test.

**Comment by evnm** [comment]
I too saw your comment on #1672, but hadn't had a chance yet to reply.

I agree that a test case would be the best way to move forward. If possible, we should avoid further shots in the dark like #1678. Given that this latest race is seemingly within Logback itself, perhaps we should reach out to its maintainers. I'm curious if these issues have arisen before and if the Logback team will have any guidance.

**Comment by nickbabcock** [comment]
#1678 was merged.

**Comment by nickbabcock** [comment]
oops, I think I prematurely closed the issue, sorry

**Comment by mattnelson** [comment]
I'm not sure if I'm hitting this exact issue, but I've noticed that access logging looks to be broken with DW-1.0.1-SNAPSHOT. I created a repo with shaded jars against 1.0.0 and 1.0.1-SNAPSHOT. I haven't dug into it a whole lot yet, but I did try managing the logback/jetty versions back in sync with 1.0.0 and that did not resolve the issue.

https://github.com/mattnelson/dw-access-logging

**Comment by nickbabcock** [comment]
If I recall correctly, a synchronous logger will solve this problem, so maybe we should consider switching. Was the previous request logger (before the `dropwizard-request-logging` module) asynchronous? If not, I don't think we lose much by switching.

**Comment by evnm** [comment]
As far as I can tell, request logging has been handled asynchronously [since its inception](https://github.com/dropwizard/dropwizard/commit/8bb23a0fabc554cf542daf0367c1054802df7633).

I'm worried that defaulting to synchronous logging could induce performance issues. I believe that it would be a stopgap for this issue (and #1699), but some perf testing is in order before we introduce the change.

**Comment by tjcutajar** [comment]
Since this is not really reproducable anymore as the fix attempt was reverted in 1.0.2 i'll describe the original problem. If you define a custom request logFormat, e.g %reqAttribute{someAttibuteName}, and set a corresponding request attribute the expected value gets logged intermittently.

**Comment by nickbabcock** [comment]
Can this be closed? Logback has been updated for 1.1.0, which fixes synchronization bugs and @arteam looks to have had a fix in #1828 back for 1.0.5

**Comment by arteam** [comment]
Yes, this can be closed. Thanks for bringing this up!
