### ISSUE TITLE
Should serialize and deserialize hibernate @Transient properties

### ISSUE THREAD

**Issue by sunshineo** [dropwizard/dropwizard#1687]
I'm not sure if this is a Dropwizard issue or Jackson issue.
But the choice to NOT serialize or deserialize based on the hibernate annotation @Transient when I'm serializing and deserializing between Java objects and JSON is unreasonable to me especially when we have the annotation @JsonProperty that is just for that.

**Comment by evnm** [comment]
This seems to be a Jackson issue, specifically in relation to its [Hibernate module](https://github.com/FasterXML/jackson-datatype-hibernate). I think [this StackOverflow question](http://stackoverflow.com/questions/25713884/jpa-transient-annotation-and-json) may help lead you to an answer.

**Comment by ssunzulily** [comment]
How do I do the following in a dropwizard project?
```
Hibernate4Module hm = new Hibernate4Module();
    hm.disable(Feature.USE_TRANSIENT_ANNOTATION);
```

**Comment by sunshineo** [comment]
In the HibernateBundler, overwrite another method and put in those 2 lines.
