### ISSUE TITLE
Response created (HTTP 201) does not take config rootPath into account

### ISSUE THREAD

**Issue by burakdede** [dropwizard/dropwizard#1692]
When using root path for designing rest api with

    server:
      adminMinThreads: 1
      adminMaxThreads: 64
      rootPath: /api/*

I sometimes need to indicate to client that resource successfully created with the following response.

`return Response.created(URI.create("/category/" + categoryId)).build();`

What I expected is dropwizard to employ `rootPath` when forming full `Location` header url for new created entity which I think is `https://localhost:8080/api/category/1000`.

What I actually got is `https://localhost:8080/category/1000`. Is this expected behaviour by design, if not I can look into this.

> This may be related to #661

**Comment by evnm** [comment]
Have you tried setting [`server.applicationContextPath`](http://www.dropwizard.io/1.0.0/docs/manual/configuration.html#default) instead of `server.rootPath`?

**Comment by burakdede** [comment]
Yes I tried both ways

first by 
`env.getApplicationContext().setContextPath("api")`

second
`server:
  adminMinThreads: 1
  adminMaxThreads: 64
  applicationContextPath: /api/*`

Still no luck with path prefix on `Location`.

**Comment by evnm** [comment]
Remove the leading slash in the path you pass to `URI#create`.

As per [the documentation of `Response#created`](https://jersey.java.net/apidocs/2.11/jersey/javax/ws/rs/core/Response.html#created(java.net.URI)), the path must be relative. In your case, `"/category/..."` is an absolute path. See [JERSEY-2838](https://java.net/jira/browse/JERSEY-2838) for more information.

**Comment by burakdede** [comment]
Yes, I verified with my tests too and somehow I missed that Jersey bug.  Thanks anyway.
