### ISSUE TITLE
Dropwizard 1.0.0 doesn't support the subdirectory template inheritance

### ISSUE THREAD

**Issue by gongmingqm10** [dropwizard/dropwizard#1696]
Hey, 

We just updated the DropWizard from 0.9.3 to 1.0.0. But found the subdirectory mustache inheritance will fail. Below is the detailed behaviour.

Note: In the local development environment it is working, but when we deploy it via `java -jar project-SNAPSHOT.jar server integration`, we found it is not working anymore.

The main layout template: `views/layout.mustache`

```
<!DOCTYPE html>
<html lang="en-gb">
<head>
    <meta charset="utf-8">
    <title>Hello DropWizard</title>
</head>
<body>
{{$body}}{{/body}}
</body>
</html>
```

The sub page which inherent the layout but located in the subdirectory: `views/error-pages/not_found.mustache`

```
{{<../layout}}
{{$body}}
        <h1 class="error-page__title">
            Error 404 - page not found
        </h1>
        <div class="error-page__content">
            <p>We couldn't find the page you're looking for.</p>
        </div>
{{/body}}
{{/../layout}}
```

And this is the view we rendered it: `NotFoundView.java`

```
public class NotFoundView extends View {
    public NotFoundView() {
        super("error-pages/not-found.mustache");
    }
}
```

It was working in DropWizard 0.9.3. But we got the error when trying to reach this page when we upgraded it to 1.0.0.

The error message is below:

```
Caused by: javax.ws.rs.WebApplicationException: HTTP 500 Internal Server Error
	at io.dropwizard.views.ViewMessageBodyWriter.writeTo(ViewMessageBodyWriter.java:89)
	at coop.membership.portal.helpers.ViewMessageBodyWriterWithGlobalContext.writeTo(ViewMessageBodyWriterWithGlobalContext.java:63)
	at coop.membership.portal.helpers.ViewMessageBodyWriterWithGlobalContext.writeTo(ViewMessageBodyWriterWithGlobalContext.java:24)
	at org.glassfish.jersey.message.internal.WriterInterceptorExecutor$TerminalWriterInterceptor.invokeWriteTo(WriterInterceptorExecutor.java:265)
...
```

We suspect it's cause  by the magic `{{<../layout}} ...`, cause it's the only difference with other pages. We solved this problem by pulling the `not_found.mustache` out of the `error_pages` subdirectory.

But this should be an issue introduced by the newest 1.0.0 version.

**Comment by nickbabcock** [comment]
I can't replicate this with either relative or absolute paths. See [gist](https://gist.github.com/nickbabcock/286da838b5f305721b05340acfaa768e)

**Comment by gongmingqm10** [comment]
Hey Nick, how did you launch this App?

It works in our local environment where we launch it via Intellij. 

But it failed in the integration env where we start it via `java -jar test-SNAPSHOT.jar server integration`.

**Comment by nickbabcock** [comment]
Thanks for the info. I was testing the dropwizard test cases locally in intellij.

**Comment by matthewwoodruff** [comment]
Hey,

I'm working alongside @gongmingqm10 and carried out a little more research. 

Dropwizard 0.9.2 has a dependency on [spullara/mustache.java](https://github.com/spullara/mustache.java) version 0.8.17 but Dropwizard 1.0.0 uses 0.9.2

I've created a simple application [mustache-resolution](https://github.com/matthewwoodruff/mustache-resolution) to test the two versions of [spullara/mustache.java](https://github.com/spullara/mustache.java) in isolation and it appears as though versions 0.9.x don't support partial imports such as  `{{ ../partials/header }}` although 0.8.x versions do.

We've found a similar thread in the mustache.java forum and posted an update [here](https://groups.google.com/d/msg/mustachejava/84_oxOao8hM/0d4PW1L7AgAJ).
