### ISSUE TITLE
Broken query parameter extraction in POST requests

### ISSUE THREAD

**Issue by evnm** [dropwizard/dropwizard#1699]
See post-closure comments on #1606.

**Comment by nickbabcock** [comment]
What I can't figure out is that the `testBuild` runs flawlessly by itself (and on Travis), but fails when run with other tests 😕

**Comment by evnm** [comment]
Spent a bunch more time digging on this today, but still no solution. It seems to be related to how `o.e.jetty.server.Request` objects are recycled between requests.

To summarize, `Request` has a `recycle` method which nulls out the object's state (including the `_queryParameters` field) and is presumably meant to be run between individual HTTP requests. For some reason, `TaskServlet#doPost` is invoked prior to `Request#recycle`, which results in the request's query parameters not being extracted and the default empty map being used. 

Patching `o.e.jetty.server.Request` to remove [the `if (_queryParameters == null)` guard](https://github.com/eclipse/jetty.project/blob/9fd6d4354e7a6d5ea0b0a8fff47351ba37b9babd/jetty-server/src/main/java/org/eclipse/jetty/server/Request.java#L370) around the `extractQueryParameters()` method results in query parameters universally being extracted and the `SimpleServerFactoryTest#testBuild` passing.

It's unclear to me if this situation is a Jetty bug or the result of mismanagement of HTTP request lifecycles in `SimpleServerFactoryTest`. I fiddled with `httpRequest` helper method to ensure that all input/output buffers associated with requests are closed, but the test still fails.

**Comment by nickbabcock** [comment]
A few more hours of debugging as only let to the following insight: 

Changing `testBuild` to have three requests will fail every time when ran independently. eg:

```java
assertThat(httpRequest("GET", "http://localhost:" + port + "/service/test"))
        .isEqualTo("{\"hello\": \"World\"}");
assertThat(httpRequest("POST", "http://localhost:" + port + "/secret/tasks/hello?name=test_user"))
        .isEqualTo("Hello, test_user!");
assertThat(httpRequest("POST", "http://localhost:" + port + "/secret/tasks/hello?name=test_user"))
        .isEqualTo("Hello, test_user!");
```

And strangely, putting the GET request as the last request will make the test pass :confused:

**Comment by nickbabcock** [comment]
I extracted almost all the admin task servlet into a [self contained gist](https://gist.github.com/nickbabcock/318d233c293444cb4fc22a8a80947f1f) that doesn't import dropwizard and I'm unable to replicate the errors we're seeing.

**Comment by evnm** [comment]
Good find!

The `dropwizard-core` tests to pass if you set [set `asyncAppender.setNeverBlock(false);` in the `wrapAsync` method](https://gist.github.com/evnm/0960ea2c14f74b4081e5194180a82c0f). It appears the async logging queue is filling up during test runs, which perhaps tickles some race condition. I'm about to get on a flight and go on vacation, so can't dig any further today.

**Comment by evnm** [comment]
My last comment was a bit hasty. The tests still fail with `asyncAppender.setNeverBlock(false)`, albeit inconsistently. All indications continue to point towards a race condition hidden somewhere.

The best lead we have still seems to be the `AbstractAppenderFactory#wrapAsync` call, as pointed out by @nickbabcock above. It's invoked by the `ConsoleAppenderFactory` used for request logging. `dropwizard-logging` isn't used in this test class (because `SimpleServerFactoryTest` builds a `ServerFactory` directly from the configuration file), so we can ignore it.

The issue seems to stem from a bad interaction between Jetty's request-handling lifecycle, Logback's `RequestLogImpl`, and Logback's async appender functionality. I stumbled upon a familiar-sounding issue filed against [a Logback+Logstash encoder library](https://github.com/logstash/logstash-logback-encoder/issues/94) which calls out the same lack of thread-safety in Logback that's come up in relation to Dropwizard in #1672 and #1686.

When enabling DEBUG output for test runs in my branch which instruments jetty-server and dropwizard-{core,servlets}, I notice that an access event is not logged for the first GET request in `SimpleServerFactoryTest#testBuild`. With `ConsoleAppenderFactory#wrapAsync` removed, the test passes and both `testBuild` requests are logged.

So, the best inclination I have at this point is that `Request.recycle()` is not invoked within Jetty when an async appender is used for request logging. This prevents the shared `Request` object from clearing its request parameters. And thus when the `POST /secret/tasks/hello?name=test_user` request is handled, the empty query parameters from the prior `GET /service/test` are still used.

**Comment by nickbabcock** [comment]
I was only able to take a look at it once more in the meantime, but hadn't progressed anywhere. Since is non-trivial to debug, and not properly recycling requests is serious, maybe we should be asking ourselves some questions:

1. Is this happening in production for 1.0?
2. If not happening in production, and only for our test infrastructure, why? Why does Travis succeed?
3. If happening in production we should look for an immediate fix:
  - By reverting the request logging feature
  - Or marking affected request loggers as sync
  - Or (unlikely) find and push a fix to the appropriate upstream project.

**Comment by evnm** [comment]
1. As far as I'm aware of, the `SimpleServerFactoryTest#testBuild` case is the only reported instance of the issue. It's possible that it _is_ liable to affect production servers, but the likelihood thereof is low because `SimpleServerFactory` isn't used by default.
2. Without a root cause, it's hard to say why this issue would occur only in tests.
3. An immediate fix would be to enforce synchronous request logging. The impression I'm left with by this issue and #1686 is that we really need to reach out to the Logback maintainers for guidance on dealing with the library's use of mutable state.

**Comment by nickbabcock** [comment]
Reverting #1678 also fixed this issue.

**Comment by evnm** [comment]
Yikes. Unsettled by the number of fingerprints I'm leaving all over these Logback-related issues.

Perhaps we can patch Logback itself to make the `AccessEvent#prepareForDeferredProcessing` method idempotent. At the very least, we should seek guidance from the Logback maintainer(s) before burning more time on these issues.

**Comment by markelliot** [comment]
Doesn't really help, but I found an open logback ticket for this issue and proposed a patch here: https://github.com/qos-ch/logback/pull/336. I also mentioned this on the mailing list, but haven't heard back from any maintainers about if or when this would get merged.
