### ISSUE TITLE
connectionTimeout on io.dropwizard.client.JerseyClientConfiguration

### ISSUE THREAD

**Issue by fipp** [dropwizard/dropwizard#1706]
Hi, I'm running DropWizard 0.9.1 and have recently looked at the Integration Testing (JUnit) example located at this page:

http://www.dropwizard.io/0.9.1/docs/manual/testing.html#id2

My problem is that the `jerseyClient` i get from using `JerseyClientBuilder` defaults to a timeout of 500 ms. This is so short that some of my tests fails. 

Looking at `io.dropwizard.client.JerseyClientConfiguration`, I don't see any `connectionTimeout` attribute like in `io.dropwizard.client.HttpClientConfiguration`. Is this on purpose, or could it be updated to contain this attribute?

Cheers,
Terje Andersen

**Comment by nickbabcock** [comment]
Have you tried setting the properties `ClientProperties.READ_TIMEOUT` and `ClientProperties.CONNECT_TIMEOUT` via `withProperty`?

**Comment by nickbabcock** [comment]
Ignore my previous comment:

`JerseyClientConfiguration` derives from `HttpClientConfiguration`, which contains `timeout`, and you can set that to the appropriate value
