### ISSUE TITLE
Relative logfile location changed in 1.0

### ISSUE THREAD

**Issue by ajlanghorn** [dropwizard/dropwizard#1707]
Hi,

I recently upgraded a project from 0.9.3 to 1.0, and noticed some odd behaviour in terms of request logging. Previously, given an absolute path, logs would be written to a location based on the location of the JAR on disk. For instance, if I dumped my JAR in `/var/apps/foo`, and my logfile location was `logs/foo.log`, then I could expect my log file - on disk - to appear at `/var/apps/foo/logs/foo.log`.

With 1.0, it appears that the log files are created relative to the location from where the JVM process is started. This particular project uses Upstart to manage the running of the application, and the JVM process is started from inside Upstart. Therefore, the log file gets created relative to the Upstart log path, at `/var/log/upstart/foo.log`.

I've not yet fully worked out why this is, but I imagine the change might be due to a downstream dependency change. Any pointers to how to revert this back to the previous behaviour are welcome.

**Comment by ajlanghorn** [comment]
I think this might actually be an Upstart issue, and not a Dropwizard one. It's just that this behaviour has started to exhibit itself since we upgraded.

**Comment by evnm** [comment]
I think the takeaway here is "don't use relative paths". Dropwizard's `currentLogFilename` configuration field under `logging.appenders` gets plugged into Logback's [`FileAppender#setFile`](http://logback.qos.ch/apidocs/ch/qos/logback/core/FileAppender.html#setFile(java.lang.String)). This call boils down to `new java.io.File(currentLogFilename)`, meaning that relative paths are rooted in an application's working directory.

The Logback version went from 1.1.3 to 1.1.7 in the span of Dropwizard 0.9.3 to 1.0.0, but the behavior of `FileAppender#setFile` didn't fundamentally change between these releases. I can't say why this behavior would have changed for you, but in any case, I'd avoid using relative paths if you can.
