### ISSUE TITLE
x509 certificate validation fails unconditionally if no revocation check mechanism is configured

### ISSUE THREAD

**Issue by lpeterse** [dropwizard/dropwizard#1710]
I tried to setup HTTPS client certificate authentication and continuously experienced this kind of exception:

```
ERROR [2016-08-26 07:28:48,244] io.dropwizard.cli.ServerCommand: Unable to start server, shutting down
! sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
! at sun.security.provider.certpath.SunCertPathBuilder.build(SunCertPathBuilder.java:146)
! at sun.security.provider.certpath.SunCertPathBuilder.engineBuild(SunCertPathBuilder.java:131)
! at java.security.cert.CertPathBuilder.build(CertPathBuilder.java:280)
! at org.eclipse.jetty.util.security.CertificateValidator.validate(CertificateValidator.java:248)
! ... 15 common frames omitted
! Causing: java.security.cert.CertificateException: Unable to validate certificate: unable to find valid certification path to requested target
! at org.eclipse.jetty.util.security.CertificateValidator.validate(CertificateValidator.java:256)
! at org.eclipse.jetty.util.security.CertificateValidator.validate(CertificateValidator.java:189)
```

This error is quite generic and misleading and I spent a whole day figuring it out. One usually expects this kind of errors to be something about certificate chains or malconfigured x509 extensions.

The problem occurs already when enabling `validateCerts` (what no one does in regular HTTPS setup as the server does not need to care whether is own certificate is valid). The crux is in `org.eclipse.jetty.util.security.CertificateValidator` which clearly says

> Convenience class to handle validation of certificates, aliases and keystores Allows specifying Certificate Revocation List (CRL), as well as enabling CRL Distribution Points Protocol (CRLDP) certificate extension support, and also enabling On-Line Certificate Status Protocol (OCSP) support. IMPORTANT: at least one of the above mechanisms _MUST_ be configured and operational, otherwise certificate validation _WILL FAIL_ unconditionally.

Neither the Dropwizard documentation nor any tutorial / blog post ever pointed this out. I suggest to either add it to the documentation or to even add a check to config file validation that assures that at least one revocation check method (CRL, CRLDP or OCSP) is enabled.

**Comment by nickbabcock** [comment]
Thanks for looking into this. When we dropwizard upgraded to 1.0, we upgraded Jetty to 9.3.9.v20160517, which seemed to change some TLS/certificate settings (related: #1700 and potentially https://github.com/eclipse/jetty.project/issues/858).

Jetty, which prefers security by default, does not validate server and peer certificates without changing the settings. So it is interesting that Dropwizard chooses to validate by default. I've been kicking around aligning the defaults with Jetty, so users aren't overwhelmed by cryptic error messages.

The low hanging fruit here is adding in support for CRLDP and OSCP, as I believe those should be easy to add to the configuration. Not sure about the CRL.

**Comment by nickbabcock** [comment]
After thinking about this a bit, it's in my opinion we take the following steps:

- Unless the old behavior can be emulated (I couldn't even tell you what the old behavior was), change the defaults for `validateCerts` and `validatePeers` to `false` (before 1.1.0 rc)
- Document the broken behavior warning users that enabling these options will lead to breakage
- Update certificate validation configuration to support the various options (CRLDP, OSCP, and CRL) (not needed for 1.1.0)

This does not compromise on security as Jetty has the defaults as `false` and greatly decreases confusion with new Dropwizard users as the web moves towards HTTPs

**Comment by jplock** [comment]
Just ran into this myself.  +1

**Comment by nickbabcock** [comment]
I'm closing this issue as 1.0.6 and 1.1.x will disable cert and peer validation by default.

If specific validations are desired, new issues should be created for each desired validation, so they may be tracked better and to gauge interest.
