### ISSUE TITLE
Find the execution time of a code block using timers

### ISSUE THREAD

**Issue by mayooran99** [dropwizard/dropwizard#1711]
Is there a way that I can log the execution time of a code block, each time it is called? I do not want the mean rate and stuff of this timer as this method is not called that frequently but takes a considerable amount of time when called. So is there a way that I can print the execution time of each call? Also how can I get answers for the below questions

How can I investigate the reason for the spikes in the values?
How will I know when the Max time event occurred so that I can go through the logs and see the possible reasons?
Any help would be much appreciated.

**Comment by nickbabcock** [comment]
Hey @mayooran99, these are some pretty big questions and out of scope for the Dropwizard issues, but I'll give some hints off the top of my head.

- For simple timing you can use [Guava's Stopwatch](http://google.github.io/guava/releases/19.0/api/docs/com/google/common/base/Stopwatch.html)
- You can use [VisualVM](https://visualvm.java.net/), which comes with the jdk to profile the application
- For alerting purposes, the simplest method may be to output the metrics as CSV as it contains the metrics and the timestamps. More sophisticated reporting can be used with something like Graphite.
