### ISSUE TITLE
How to make entity listeners works with Hibernate 5?

### ISSUE THREAD

**Issue by bruce-genhot** [dropwizard/dropwizard#1726]
Hi

My application is built based on dropwizard 1.0 and hibernate5. I want to add listeners to my entities which are managed by hibernate, I am using JPA annotation '@EntityListeners', but I found that does not work for me, listeners were not invoked completely.

Can you help me with this ?  thank you.

**Comment by nickbabcock** [comment]
Have you tried posting this question to [`dropwizard-users`](https://groups.google.com/forum/#!forum/dropwizard-user)? This may not be a question for the issue tracker.

**Comment by vvondra** [comment]
@bruce-genhot  See if using the JPAIntegrator works for you

Save this line as a file called `src/main/resources/META-INF/services/org.hibernate.integrator.spi.Integrator`
```
org.hibernate.jpa.event.spi.JpaIntegrator
```

**Comment by ramsrib** [comment]
Hey, Can you guys add this in the (dropwizard-hibernate) documentation?

**Comment by vvondra** [comment]
My comment is a little outdated, since the hibernate-entitymanager package was merged into hibernate-core. Or did you try with the latest version and succeed?

**Comment by ramsrib** [comment]
yeah, I tried with the latest stable version (1.2.3) and it worked.
