### ISSUE TITLE
Runtime Configuration

### ISSUE THREAD

**Issue by qinfchen** [dropwizard/dropwizard#1728]
is any plan to split the existing configuration into startup time configuration and runtime configuration allowing admins to modify certain configuration without the need to restart the server, such as loggers.

**Comment by nickbabcock** [comment]
One can configure the logging levels through the admin task endpoint. Admittedly, not as powerful as having the entire configuration being modified at runtime (à la logback.xml)

There is not a plan to split into the configuration into two files.

**Comment by manuel-hegner** [comment]
How should to work in the end. Lets say you have your WatchService and it signals a changed config. Should DW now simply parse this file and override the fields of the existing config object? That would work without any kind of API changes, but is kind of risky. If the app changed any field in the config that is lost now. This could also create racing conditions. 
On the other hand the WatchService could throw an event. Maybe the Configuration base class could contain an update method that is called with the changed Configuration and the user has to implement it himself?
