### ISSUE TITLE
Add endpoint about revisions for Report

### ISSUE THREAD

**Issue by bruce-genhot** [dropwizard/dropwizard#1730]

**Comment by joschi** [comment]
@bretthoerner Could you please be a little (or a lot!) more verbose about what you want?

**Comment by bretthoerner** [comment]
Wrong person. :)

**Comment by joschi** [comment]
@bretthoerner True, sorry for that. 😉 

@bruce-genhot Could you please be a little (or a lot!) more verbose about what you want?

**Comment by nickbabcock** [comment]
Closing due to lack of information and response.
