### ISSUE TITLE
Feature req: allow per-metric filtering of convert...To() in graphite reporter

### ISSUE THREAD

**Issue by mrares** [dropwizard/dropwizard#1733]
Explanation:
Timers within an application come in various resolutions but the graphite reporter applies a general conversion over all, it would be nice to be able to apply multiple filtered conversions so that metrics can be published at convenient resolutions. For convenience reasons the most granular should apply.

How the setup would look like:
```
mms_units = new MetricFilter() {
        @Override
        public boolean matches(String name, Metric metric) {
            ....;
        }
    }

 reporter = GraphiteReporter.forRegistry(environment.metrics())
                .convertRatesTo(TimeUnit.SECONDS, )
                .convertDurationsTo(TimeUnit.MILLISECONDS) //This would default all metrics
                .convertDurationsTo(TimeUnit.MICROSECONDS, mms_units) //This would override the granularity for the filtered metrics
                .filter(MetricFilter.ALL)
                .build(graphite);

```

**Comment by joschi** [comment]
@mrares You probably want to create that issue in the [Dropwizard Metrics](https://github.com/dropwizard/metrics) project.
