### ISSUE TITLE
Discoverable bug for RequestLogFactory

### ISSUE THREAD

**Issue by jmoney8080** [dropwizard/dropwizard#1742]
Pretty sure that `META-INF.services` -> `META-INF/services` [here](https://github.com/dropwizard/dropwizard/tree/master/dropwizard-request-logging/src/main/resources/META-INF.services).  This is causing custom RequestLogFactories from not being discovered.

Workaround, in your project add a `io.dropwizard.jackson.Discoverable` file in `META-INF/services` with contents of `io.dropwizard.request.logging.RequestLogFactory` and everything is hunky-dory again!  

I *think* the only reason this works in 1.0 is because `RequestLogFactory` has a default impl class in the jackson annotation.

**Comment by nickbabcock** [comment]
Nice, did you want to send a PR to fix this?

Is it possible to write a test to ensure that this doesn't regress in the future?

**Comment by jmoney8080** [comment]
I have a PR for this: https://github.com/dropwizard/dropwizard/pull/1743
I'm unsure how to write a test case as Discoverable is kind of opt-in.  How would you recommend one?  Hard code a check for `META-INF.services`?

**Comment by nickbabcock** [comment]
This may be enough of a unit test (it'll fail without your PR) 💭 

```java
public class RequestLogFactoryTest {

    @Test
    public void isDiscoverable() throws Exception {
        assertThat(new DiscoverableSubtypeResolver().getDiscoveredSubtypes())
            .contains(LogbackAccessRequestLogFactory.class);
    }
    // ...
}
```

There are other tests worth looking at in dropwizard-logging

**Comment by jmoney8080** [comment]
Added test, ci is running…

**Comment by jmoney8080** [comment]
ci ran and github checks passed
