### ISSUE TITLE
@Context for HttpServletRequest in Features not injected with ResourceTestRule

### ISSUE THREAD

**Issue by victornoel** [dropwizard/dropwizard#1744]
Hi,

I am trying to use `ResourceTestRule` as following:
```
    @ClassRule
    public static final ResourceTestRule resources = ResourceTestRule.builder()
            .setTestContainerFactory(new JettyTestContainerFactory()).addResource(new UserSession())
            .addProvider(pac4jFeature()).build();
```

With `pac4jFeature()` returning a `Feature` that registers two `Feature`s, and one of these expects `HttpServletRequest` to be injected via `@Context` annotation. It works perfectly when executing dropwizard normally but not when executing the test.

I think it should work and I found some SO thread discussing it with solutions that resembles a lot what is implemented in `ResourceTestRule`, but maybe there is small differences I can't see [here](http://stackoverflow.com/questions/29386360/jersey2-unit-testing-httpservletrequest-is-null) and [here](http://stackoverflow.com/questions/17973277/problems-running-jerseytest-when-dealing-with-httpservletresponse).

**Comment by victornoel** [comment]
Nevermind, it seems that Jetty test framework does not support this functionality (according to https://java.net/jira/browse/JERSEY-2644) but using Grizzly2, it does work (with GrizzlyWebTestContainerFactory).

**Comment by joschi** [comment]
@victornoel FWIW, this is described in the Jersey documentation: https://jersey.java.net/documentation/latest/test-framework.html#d0e17451
