### ISSUE TITLE
@UnwrapValidatedValue is required for all *Param resource parameters

### ISSUE THREAD

**Issue by cmicali** [dropwizard/dropwizard#1745]
**The Issue**

Since the upgrade to Hibernate 5.x in dropwizard 1.0 the following code now fails at runtime:

``` java
@GET @Path("/long")
public Response receiveLong(@NotNull @QueryParam("long") LongParam longParam) {
    return Response.ok().build();
}
```

Hitting this endpoint with a null value causes the following runtime exception:

`HV000186: The constraint of type 'javax.validation.constraints.NotNull' defined on 'receiveLong.query param long' has multiple matching constraint validators which is due to an additional value handler of type 'io.dropwizard.jersey.validation.ParamValidatorUnwrapper'. It is unclear which value needs validating. Clarify configuration via @UnwrapValidatedValue.`

This happens because Hibernate Validator doesn't know if you want to apply `@NotNull` to `longParam` or the value inside of `LongParam`, since dropwizard has provided an unwrapper for that type. To fix this, you have to use `@UnwrapValidatedValue` to tell Hibernate Validator to which value the validation should be applied:

``` java
@GET @Path("/long")
public Response receiveLong(@UnwrapValidatedValue @NotNull @QueryParam("long") LongParam longParam) {
    return Response.ok().build();
}
```

In practice this means that you have to add this annotation to every `*Param` you use that also is required. This is required, but unnecessary, because you really **always** want the `@NotNull` to apply to the `LongParam` and not the value inside, because the `*Param` classes will throw the right validation exceptions if the value is null.

**Our Solution**

This was a breaking change for us when upgrading dropwizard from 0.8.x to 1.0, as we use the `*Param` classes a lot. Putting `@UnwrapValidatedValue` on every parameter felt very verbose and made things harder to read.

We added 2 things:
1. A maven plugin that scans for parameters not annotated post-compilation and adds the annotations using javaassist if they are missing.
2. A startup check to ensure every usage of `*Param` includes this annotation and fails if not. This at least prevents starting up with something that will fail at runtime.

I would be happy to submit this as a PR, but I have a few concerns.
1. The use of a maven plugin + javaassist is a little hacky. It's worked great for us, but feels like not the best solution.
2. [@UnwrapValidatedValue](https://docs.jboss.org/hibernate/stable/validator/api/org/hibernate/validator/valuehandling/UnwrapValidatedValue.html) is marked as experiemental, and unclear if this is something we should be handling like this long-term
3. The right solution is probably to add to Hibernate Validator a way to set a default for the unwrapping behavior for specific classes. So in this case, default to `unwrap=false` for all *Param classes. This is not possible today.

**Comment by cmicali** [comment]
Related conversation on dropwizard-user: https://groups.google.com/forum/#!topic/dropwizard-user/_miPvbYaqDY

**Comment by nickbabcock** [comment]
imo, for me, the end goal is to allow endpoints to look like:

```java
@GET @Path("/long")
public Response receiveLong(@QueryParam("long") LongParam longParam,
                            @QueryParam("long2") Optional<LongParam> longParam2) {
    return Response.ok().build();
}
```

Where the optional is either filled or absent (can't be null) and the `LongParam` can't be null either. Eliminate a whole class of bugs.

It was only until recently that Dropwizard could validate `*Param` annotations and the most reasonable way to do so was through utilizing `@UnwrapValidatedValue`. Yes it is experimental and yes we've been burned by it, but it's better than nothing<sup>[citation needed]</sup>

I'm partial to your solution of interpreting certain subset of classes or endpoints differently to reduce verbosity (choice 3).

**Comment by cmicali** [comment]
Let me look into getting to that end goal - though not backwards-compatible, I think that is the right way to do it. 

On #3, I'll also look into submitting a change to the HIbernate Validator project.

**Comment by nickbabcock** [comment]
Closing this issues as it appears due to staleness. The provided workaround should be sufficient.
