### ISSUE TITLE
Update jackson v2.7.6 -> v2.7.8

### ISSUE THREAD

**Issue by jmoney8080** [dropwizard/dropwizard#1747]
I'd like to propose an update to jackson to v2.7.8.  [Here](https://github.com/FasterXML/jackson/wiki/Jackson-Release-2.7.8) are the release notes.  Of particular interest is https://github.com/FasterXML/jackson-databind/issues/1383

**Comment by jmoney8080** [comment]
PR: https://github.com/dropwizard/dropwizard/pull/1746

**Comment by nickbabcock** [comment]
My anticipation is that for the next release on master (1.1) we'll be targeting Jackson 2.8

This may be worth considering for 1.0.x.
