### ISSUE TITLE
Could not retrieve/persist child entity !!!

### ISSUE THREAD

**Issue by princevijayakumar** [dropwizard/dropwizard#1748]
We are migrating spring boot rest service to drop wizard rest service.
also we are using Mongo DB with Jackson.
In a Entity(parent) we are Associating a child entity, But we could not Save/Retrieve the child object using "DBRef<AddressData, String> addreddData;"

While retrieving the Json response is shown below,
{
  "id": "57eb58a0cb101eff0cefec9f",
  "userid": "13",
  "username": "johnbecker",
  "password": "pass1234",
  "firstname": "John",
  "lastname": "Becker",
  "addreddData": {
    "id": {
      "time": 1475041440000,
      "new": false,
      "inc": 217050270,
      "timeSecond": 1475041440,
      "machine": -888135937
    },
    "collectionName": "address",
    "collectionKey": {
      "name": "address",
      "type": "model.AddressData",
      "keyType": "java.lang.String"
    }
  }
}

Similarily while saving Parent entity is persisting instead child entity is empty even though we are passing proper input JSON
{
    "userid": "13",
    "username": "johnbecker",
    "password": "pass1234",
    "firstname": "John",
    "lastname": "Becker",
    "addreddData": {
        "addressid": 13,
        "city": "Delhi",
        "country": "India",
        "state": "Delhi",
        "street": "9th main road"
    }
`}`

My Parent Entity :
`import org.hibernate.validator.constraints.NotEmpty;

import net.vz.mongodb.jackson.DBRef;
import net.vz.mongodb.jackson.Id;
import net.vz.mongodb.jackson.MongoCollection;
import net.vz.mongodb.jackson.ObjectId;

@MongoCollection(name = "user")
public class UserData {

```
@Id
@ObjectId
public String id;

@NotEmpty
public String userid;

@NotEmpty
public String username;

@NotEmpty
public String password;

@NotEmpty
public String firstname;

@NotEmpty
public String lastname;

@ObjectId
public DBRef<AddressData, String> addreddData;
```

}`

My Child Entity :

`import org.hibernate.validator.constraints.NotEmpty;

import net.vz.mongodb.jackson.Id;
import net.vz.mongodb.jackson.MongoCollection;
import net.vz.mongodb.jackson.ObjectId;

@MongoCollection(name = "address")
public class AddressData {

```
@Id
@ObjectId
public String id;

@NotEmpty
public int addressid;

@NotEmpty
public String street;

@NotEmpty
public String city;

@NotEmpty
public String state;

@NotEmpty
public String country;
```

}`

Please suggest some solution for retrieving/persisting the record in child object.

**Comment by nickbabcock** [comment]
Sorry for the late response but this doesn't sound like an issue with dropwizard and may a more appropriate post in [dropwizard-users](https://groups.google.com/forum/#!forum/dropwizard-user) list
