### ISSUE TITLE
StreamingOutput Resource not respecting flush, versions 0.8.x and later

### ISSUE THREAD

**Issue by jmeeks** [dropwizard/dropwizard#1752]
In DW versions 0.7.1 and before a StreamingOutput Resource will immediately return the HTTP response headers and any HTTP response body as soon as the OutputStream has `flush()` called.

In DW versions 0.8.x and later, it would appear that some sort of buffer is not respecting the `flush()` call. If not enough data is streamed, there will be no HTTP data is sent until the stream is closed.

Please see the code  below:

[dwex_07plus.tar.gz](https://github.com/dropwizard/dropwizard/files/501649/dwex_07plus.tar.gz)

Steps to reproduce (0.7.1):
1. Make sure that `dropwizard.version` is set to `0.7.1` in `pom.xml`.
2. Package it: `mvn clean package`
3. Start server: `java -jar target/dwex_07plus-0.0.1.jar server example.yml`
4. In separate console: ` curl -i http://localhost:8080/hello-world/streaming`
5. Note how the HTTP response headers and flushed data comes back ASAP.

Steps to reproduce (0.8.x and later):
1. Make sure that `dropwizard.version` is set to `0.8.0` or later in `pom.xml`.
2. Package it: `mvn clean package`
3. Start server: `java -jar target/dwex_07plus-0.0.1.jar server example.yml`
4. In separate console: ` curl -i http://localhost:8080/hello-world/streaming`
5. Note how not HTTP response headers nor flushed data comes back for some time (about 30s). After the delay, the response headers and all buffered data is returned and subsequent HTTP response body is written.

**Comment by nickbabcock** [comment]
Two possible solutions:

1. Set [`ServerProperties.OUTBOUND_CONTENT_LENGTH_BUFFER`](https://jersey.java.net/apidocs/2.22/jersey/org/glassfish/jersey/server/ServerProperties.html#OUTBOUND_CONTENT_LENGTH_BUFFER) -- from [stackoverflow](http://stackoverflow.com/a/34197824/433785)
2. Use [ChunkedOutput](https://jersey.java.net/documentation/latest/async.html#chunked-output), which may be a better idea as it will output the headers immediately.

Your endpoint becomes

```java
final ChunkedOutput<String> output = new ChunkedOutput<>(String.class);

executor.execute(() -> {
    try (ChunkedOutput<String> out = output) {
        for (int i = 0; i < 100; i++) {
            out.write(RandomStringUtils.randomAlphabetic(100) + counter.incrementAndGet());
            out.write(java.security.AccessController.doPrivileged(
                    new sun.security.action.GetPropertyAction("line.separator")));
            Thread.sleep(500);
        }
    } catch (InterruptedException | IOException e) {
    }
});

return output;
```

**Comment by jmeeks** [comment]
The ChunkedOutput solution is what I was looking for. Thanks!  For posterity...
```
package com.example.helloworld.resources;

import com.example.helloworld.core.Template;
import com.google.common.base.Optional;
import org.apache.commons.lang3.RandomStringUtils;
import org.glassfish.jersey.server.ChunkedOutput;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import javax.ws.rs.GET;
import javax.ws.rs.Path;
import javax.ws.rs.Produces;
import javax.ws.rs.QueryParam;
import javax.ws.rs.core.MediaType;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;
import java.util.concurrent.atomic.AtomicLong;

@Path("/hello-world")
@Produces(MediaType.APPLICATION_JSON)
public class HelloWorldResource {
    private static final Logger LOGGER = LoggerFactory.getLogger(HelloWorldResource.class);

    private static final ExecutorService executor = Executors.newCachedThreadPool();

    private static final String SEPARATOR = java.security.AccessController.doPrivileged(
            new sun.security.action.GetPropertyAction("line.separator"));

    private final Template template;
    private final AtomicLong counter;

    public HelloWorldResource(Template template) {
        this.template = template;
        this.counter = new AtomicLong();
    }

    @GET
    @Path("/streaming")
    @Produces(MediaType.TEXT_PLAIN)
    public ChunkedOutput<String> sayHelloStreamed(@QueryParam("name") Optional<String> name) {
        final ChunkedOutput<String> output = new ChunkedOutput<>(String.class, SEPARATOR);
        executor.execute(
                () -> {
                    try (ChunkedOutput<String> out = output) {
                        Thread.sleep(5000);  // Explicitly show the headers coming before any Response Body
                        for (int i = 0; i < 100; i++) {
                            out.write(RandomStringUtils.randomAlphabetic(100) + counter.incrementAndGet());
                            Thread.sleep(500);
                        }
                    } catch(Exception ex) {
                        System.out.println("Chunked output error!!!!!!");
                    }
                }
        );
        return output;
    }

}
```
