### ISSUE TITLE
Dependency convergence error when upgrading to 1.0 or 1.0.2

### ISSUE THREAD

**Issue by Wstunes** [dropwizard/dropwizard#1754]
After I change the version and run mvn clean install
I got this error message
Seems the dropwizard-jackson and dropwizard-jersey is in wrong configuration.

Dependency convergence error for com.fasterxml.jackson.core:jackson-annotations:2.7.6 paths to dependency are:
+-com.idf:admin:0.0.1-SNAPSHOT
  +-io.dropwizard:dropwizard-core:1.0.0
    +-io.dropwizard:dropwizard-util:1.0.0
      +-com.fasterxml.jackson.core:jackson-annotations:2.7.6
and
+-com.idf:admin:0.0.1-SNAPSHOT
  +-io.dropwizard:dropwizard-core:1.0.0
    +-io.dropwizard:dropwizard-jackson:1.0.0
      +-com.fasterxml.jackson.core:jackson-annotations:2.7.6
and
+-com.idf:admin:0.0.1-SNAPSHOT
  +-io.dropwizard:dropwizard-core:1.0.0
    +-io.dropwizard:dropwizard-jackson:1.0.0
      +-com.fasterxml.jackson.core:jackson-databind:2.7.6
        +-com.fasterxml.jackson.core:jackson-annotations:2.7.0
and
+-com.idf:admin:0.0.1-SNAPSHOT
  +-io.dropwizard:dropwizard-core:1.0.0
    +-io.dropwizard:dropwizard-jackson:1.0.0
      +-com.fasterxml.jackson.datatype:jackson-datatype-joda:2.7.6
        +-com.fasterxml.jackson.core:jackson-annotations:2.7.0
and
+-com.idf:admin:0.0.1-SNAPSHOT
  +-io.dropwizard:dropwizard-core:1.0.0
    +-io.dropwizard:dropwizard-jersey:1.0.0
      +-com.fasterxml.jackson.jaxrs:jackson-jaxrs-json-provider:2.7.6
        +-com.fasterxml.jackson.module:jackson-module-jaxb-annotations:2.7.6
          +-com.fasterxml.jackson.core:jackson-annotations:2.7.0

How to solve this please?
And is there a documentation about how to configure the request log in the new version?

**Comment by jmoney8080** [comment]
That's telling you that differentbtransitive versions of `jackson-annotations` are being brought in. 

If you exclude `jackson-annotations` from `dropwizard-core` and include it yourself in your pom.xml it should go away.
