### ISSUE TITLE
Possible documentation bug or confusing documentation

### ISSUE THREAD

**Issue by sorjon02** [dropwizard/dropwizard#1757]
On page: http://www.dropwizard.io/1.0.2/docs/manual/hibernate.html in the documentation an object of type UserDAO is created in the run method of the application class. The class does not occur anymore in the page, and I cannot find it as any official class on the Internet.

However another class is defined lower down on the page: PersonDAO. From the context I suspect that this is intended to be the same class, but can't confirm it.

Can you please have a look at this, and make any necessary clarifications.

Best regards...

**Comment by anandagarwaal** [comment]
#1777 Fixes this issue.
