### ISSUE TITLE
Error when using jersey-test-framework-provider-jetty in dropwizard 1.0.2

### ISSUE THREAD

**Issue by jbarnettwomply** [dropwizard/dropwizard#1758]
When trying to run tests in a JettyTestContainerFactory provided by jersey-test-framework-provider-jetty in a test class that extends JerseyTestNg.ContainerPerClassTest, we're getting the same `java.lang.NoSuchMethodError: org.eclipse.jetty.server.Response.getResponse(Ljavax/servlet/http/HttpServletResponse;)Lorg/eclipse/jetty/server/Response;` error reported in https://java.net/jira/browse/JERSEY-2940

Looking at our dependency tree and maven shade invocation outputs, all jersey jars at at 2.23.1, and all jetty jars are at 9.3.9.v20160517

It seems that the versions of jersey & jetty being depended on by dropwizard are not compatible, at least with respect to the test container (things appear to work for the regular server main())?

**Comment by jbarnettwomply** [comment]
rebuilding jersey-container-jetty-http with the diff applied in https://github.com/jersey/jersey/pull/243 appears to fix this issue, but not sure what other incompatibilities may lay elsewhere?

**Comment by nickbabcock** [comment]
Thanks for the report, duly noted.

Any reasons why you're not preferring the documentation recommended `GrizzlyWebTestContainerFactory`?

**Comment by jbarnettwomply** [comment]
We found that logging was more informative (stacktraces on serializations/other internal server errors) in the Jetty implementation, and maybe a couple of other things?  It's been a while.  It also just felt weird to test against grizzly but run against jetty in actual server usage.

**Comment by jbarnettwomply** [comment]
looks like this will be fixed in jersey 2.26 ( https://github.com/jersey/jersey/commit/b62aa3fb8f787fba54868e5346a837d661c2f500 )

**Comment by sudhirsrepo** [comment]
I able to resolve my Jersey + Jetty dependency issue. Hope it will help.


```
  <properties>

        <version.jersey>2.26-b03</version.jersey>

        <version.jetty>9.2.14.v20151106</version.jetty>

    </properties>
```


[Complete pom.xml Jersey + Jetty dependency](https://www.linkedin.com/pulse/rest-api-maven-dependency-jersey-jetty-sudhir-ranjan-pradhan?articleId=6280828869331206145#comments-6280828869331206145&trk=prof-post)

**Comment by nickbabcock** [comment]
This should be closed by the update to jersey 2.27 (on master). Let us know if still a problem

**Comment by jbarnettwomply** [comment]
Thanks Nick, we'll take a look -- is there an ETA for the next release of master?

**Comment by nickbabcock** [comment]
No sorry, Jersey 2.27 required a breaking change so we're still in the process of deciding what else should be included in the next release 😄
