### ISSUE TITLE
Error Implementing Dropwizard Logging with Appenders using Gradle

### ISSUE THREAD

**Issue by ganeshcse2991** [dropwizard/dropwizard#1759]
Hi I am trying to implement file and console logging with dropwizard. I have followed the docs and configured my config file as below.
```
logging:
level: INFO

appenders:
     -type: console
```
When I tried to run the server I am getting the below error.

```
**configuration.yml has an error:
Failed to parse configuration at: logging.appenders.[0]; Could not resolve type id 'console' into a subtype of [simple type, class io.dropwizard.logging.AppenderFactory<ch.qos.logback.classic.spi.ILoggingEvent>]: known type ids = [AppenderFactory]
at [Source: N/A; line: -1, column: -1] (through reference chain: com.whatever.Main["logging"]->io.dropwizard.logging.DefaultLoggingFactory["appenders"]->java.util.ArrayList[0])**
```

I am constructing the fatJar like below.

```
task fatJar(type: Jar) {
manifest {
    attributes 'Implementation-Title': 'Creating fatJar for Whatever',
            'Implementation-Version': version,
            'Main-Class': 'com.whatever.Main'
}
baseName = project.name + '-all'
from { configurations.compile.collect { it.isDirectory() ? it : zipTree(it) } }
with jar
}
```

I tried this [link](https://github.com/johnrengelman/shadow#merging-service-files) as suggested in [this](https://groups.google.com/forum/#!topic/dropwizard-user/rGwpZld3evY) group. And I am not sure how to proceed.

**Comment by joschi** [comment]
@ganeshcse2991 As you've already discovered, you need to merge the file from `META-INF/services` in your custom fat JAR.

**Comment by ganeshcse2991** [comment]
Can you help me on how to do it?

**Comment by joschi** [comment]
@ganeshcse2991 See https://www.yunspace.com/post/dropwizard-gradle-build-with-shadowjar/ for an example
