### ISSUE TITLE
NPE when a Jersey subresource locator method returns Class<Object>

### ISSUE THREAD

**Issue by mrdon2** [dropwizard/dropwizard#1761]
The following code will cause DW to throw an NPE:

`
@Path("/")
@Produces(MediaType.APPLICATION_JSON)
public class RootResource {

    private final Map<String, Class<Object>> resources;

    @SuppressWarnings("WeakerAccess")
    public RootResource() {
        this.resources = loadSubResourcesFromServiceLocator();
    }

    @Path("{key}")
    public Class<Object> getSubResource(@PathParam("key") String key) {
        return resources.get(key);
    }`

The NPE thrown: 

> ! java.lang.NullPointerException: null
! at io.dropwizard.jersey.DropwizardResourceConfig$EndpointLogger.populate(DropwizardResourceConfig.java:173)
! at io.dropwizard.jersey.DropwizardResourceConfig$EndpointLogger.populate(DropwizardResourceConfig.java:164)
! at io.dropwizard.jersey.DropwizardResourceConfig$EndpointLogger.populate(DropwizardResourceConfig.java:189)
! at io.dropwizard.jersey.DropwizardResourceConfig$EndpointLogger.populate(DropwizardResourceConfig.java:164)
! at io.dropwizard.jersey.DropwizardResourceConfig$EndpointLogger.populate(DropwizardResourceConfig.java:159)
! at io.dropwizard.jersey.DropwizardResourceConfig.getEndpointsInfo(DropwizardResourceConfig.java:130)
! at io.dropwizard.jersey.DropwizardResourceConfig.logComponents(DropwizardResourceConfig.java:80)
! at io.dropwizard.jersey.DropwizardResourceConfig$ComponentLoggingListener.onEvent(DropwizardResourceConfig.java:245)
! at org.glassfish.jersey.server.internal.monitoring.CompositeApplicationEventListener.onEvent(CompositeApplicationEventListener.java:74)

The workaround I've found is to instead return Class<? extends MarkerInterface> where MarkerInterface contains at least one method with a @GET or similar method.

**Comment by nickbabcock** [comment]
Are you using Dropwizard 1.0.2? I believe this issue was fixed recently  (by #1718)

**Comment by mrdon2** [comment]
Yep, 1.0.2 fixes it.  Thanks!
