### ISSUE TITLE
Build fails with 1.8.0_111

### ISSUE THREAD

**Issue by nickbabcock** [dropwizard/dropwizard#1779]
Currently looking into why the (travis) build fails with this version.

**Comment by joschi** [comment]
@nickbabcock It might be related to the ALPN boot stuff (for HTTP/2 support in Jetty). That's usually the culprit with new Java versions.

See https://www.eclipse.org/jetty/documentation/9.3.x/alpn-chapter.html#alpn-versions

**Comment by nickbabcock** [comment]
Yup that makes perfect sense since the tests fail on HTTP2 module. Do you know what the profile should be?

**Comment by joschi** [comment]
@nickbabcock You can try adding Java 8u111 to the POM profile and use the same version of alpn-boot that worked for Java 8u102.

https://github.com/dropwizard/dropwizard/blob/master/dropwizard-http2/pom.xml#L282-L290

**Comment by nickbabcock** [comment]
Ok, I'm testing it locally -- just finished getting a u111 machine. I'll push if it works.

**Comment by nickbabcock** [comment]
Build passed, so I'll close this, but it does look like there were a bunch of [test failures](https://travis-ci.org/dropwizard/dropwizard#L5983)...but they didn't fail the build 😕
