### ISSUE TITLE
Make HttpConfiguration#blockingTimeout configurable

### ISSUE THREAD

**Issue by CodingFabian** [dropwizard/dropwizard#1794]
Right now `org.eclipse.jetty.server.HttpConfiguration.setBlockingTimeout(long)`is not configurable via `io.dropwizard.jetty.HttpConnectorFactory`but it probably should be. -1 as default meaning block forever is probably not a good value.

**Comment by arteam** [comment]
Hi @CodingFabian!

Thanks for pointing on this omission. I've submitted a pull request to add this parameter to the configuration. Please have a look at #1795.

**Comment by CodingFabian** [comment]
Fixed via https://github.com/dropwizard/dropwizard/pull/1795 thanks
