### ISSUE TITLE
Add method ResourceTestRule#addResource(Supplier<?> lambda)

### ISSUE THREAD

**Issue by Tibor17** [dropwizard/dropwizard#1800]
I have injection f/w which imitates the CDI container using my `InjectionRunner`.
The f/w does not provide the instances of mocked beans at the creation time of `@Rule` `ResourceTestRule` because it is technically not possible in JUnit.
Simply update the `apply()` method in the way that the resources are taken from suppliers at the beginning of the method. This means we can lazily fetch the resources to the rule.
```
        public Builder addResource(Supplier<?> resource) {
            singletons.add(resource); -> change to Set of Suppliers
            return this;
        }
```

**Comment by joschi** [comment]
@Tibor17 Could you please provide some examples on how your framework would need to initialize and add resources in a test?

**Comment by Tibor17** [comment]
@joschi 
I have my project `javaee-samples` in my public repository. There is JUnit Runner which is a kind of very fast injector of Beans. The bean is wrapped with proxy after constructor of test class has finished.
Therefore I need the method called later because I am not able to provide the bean which we call the method `addResource()`. For you it should not be a problem because the JUnit evaluation method will have our beans ready by my framework but not at the time when initializing the field of Rule (it's the constructor of test class).

**Comment by Tibor17** [comment]
@joschi 
It looks like this:
```
@RunWith(InjectionRunner.class)
public class MyTest {
     @Inject
     private MyProductionResource resource;

     @Inject
     private Dao dao;
     ...

     @Rule
     public final ResourceTestRule resources = ResourceTestRule.builder()
            .addResource(resource)
            .build();

     @Test
     public void testRestResource() {
     }
}
```

**Comment by Tibor17** [comment]
The `resource` will be null. Therefore a new method should be added with `Producer` of Java 1.8.

**Comment by joschi** [comment]
@Tibor17 Please check out #2304 and give us feedback if that's sufficient for your needs.

On a side note, I'd argue that field injection is bad practice and should be replaced with constructor injection: http://olivergierke.de/2013/11/why-field-injection-is-evil/ 😉

**Comment by Tibor17** [comment]
@joschi
Thx I will try that.
Do you also deploy SNAPSHOTs to Maven Central?
When you plan a release?

**Comment by joschi** [comment]
> Do you also deploy SNAPSHOTs to Maven Central?

Yes, but only built from the `master` branch. Please check out the `issue-1800` branch yourself and build a snapshot from it.

**Comment by Tibor17** [comment]
@joschi 
Cool, it works:

```
@RunWith(InjectableRunner.class)
public class ResourceTest {
    @Inject
    private ReportAdapterService resource;

    @Rule
    public final ResourceTestRule RULE = ResourceTestRule.builder()
            .setTestContainerFactory(new GrizzlyWebTestContainerFactory())
            .addResource(() -> resource)
            .build();

    @Test
    public void shouldReceiveXml() {
        assertThat(RULE.target("/report-adapter/report/1")
                .request()
                .get(XyzReport.class))
                .isEqualTo(new XyzReport().setSomeData(5L));
    }
}```

**Comment by Tibor17** [comment]
@joschi 
Since it works fine, can you add it to releasenotes and use it in the nearest release version?
