### ISSUE TITLE
Base Factory class to build objects based Environment

### ISSUE THREAD

**Issue by jmoney8080** [dropwizard/dropwizard#1802]
In my projects, I basically have the following class copied/pasted everywhere

```
/**
 * Factory class for building returnable types provided the current {@code Environment}.
 * 
 * @see {link Environment}
 */
@JsonTypeInfo(use = JsonTypeInfo.Id.NAME, property = "type")
public interface EnvironmentProvidedFactory<T> extends Discoverable {

    T build(Environment environment);
}
```

I was looking at refactoring it to a shared library on our stack but wanted to ask here first.  Would this be useful for possibly others if this was added to dropwizard proper?

We have found it extremely useful for configuring **bundles** using this approach so we have a standard interface they all implement and can register as a type to be easily loaded and swapped out in the YAML.

**Comment by arteam** [comment]
I think it's an interesting approach for building reusable functionality, we could consider it in the core. Could you submit a pull request (just some sketch)?

**Comment by jmoney8080** [comment]
i'll give something a shot, maybe this weekend.
