### ISSUE TITLE
Upgrade DropWizard 1.0.x to Jersey 2.23.2

### ISSUE THREAD

**Issue by pkwarren** [dropwizard/dropwizard#1807]
Jersey 2.23.2 mostly contains documentation fixes, but it also includes an update to HK2 dependency which is purported to fix issues with @BeanParam / @FormParam when paired with dropwizard-guice: https://java.net/jira/browse/HK2-300

It would be nice if DropWizard 1.0.4 (or later) could be updated to the latest minor release of Jersey to resolve this issue.

**Comment by arteam** [comment]
Closed via #1808
