### ISSUE TITLE
DW 1.0.0, leaking connections with Mysql and JDBI

### ISSUE THREAD

**Issue by chrischarlton001** [dropwizard/dropwizard#1810]
Hi,
I've got a stateless restful webservice application which works fine (i.e. the functionality does not throw exceptions) but under some load, it seems to leak connections - one a minute or so. Over time, MySQL finally reaches a connection limit and blocks further connections (then the DW logger throws 'connection pool empty' type messages). I've got both interactive_timeout and wait_timeout set to 30 on the MySQL instance, and am reasonably sure I'm not opening connections (handles) and not closing them.
Are there Tomcat connection pool configuration options I should be using to free up connections (and where should they be entered? In the YML file I presume, but it is unclear in what form)  and why are they leaking in the first place? Any suggestions?
I'm running on MS Windows servers, and have around 1000 users accessing the DW app servers, with several queries per second.
Thanks
Chris

**Comment by nickbabcock** [comment]
More information will probably be needed. 

DW 1.0.3, Centos 6.x, Postgres 9.5 handling 50 req/s is fine. Below graph is current connection pooling stats.

![image](https://cloud.githubusercontent.com/assets/2106129/20142267/02b238f4-a662-11e6-8ef4-89d1b974a95c.png)

I have also have an app using MySql 5.5 but with DW 0.8.x not leaking connections.

Both apps use JDBI

**Comment by chrischarlton001** [comment]
Thanks for that. This isn;t a load or performance thing. I've got 2x app servers running averaging 15% CPU load, and a single MySQL server (5.7.14) running under about 20% load, so I don't think it is a raw capacity issue.
Do you know whether DW maintains its own connection pool internal to the stack? I.e. in the Tomcat Apache JDBC Connection pool package? Perhaps this is leaking, hence grabbing another connection from the DB when it needs the next one, and so on. As you can tell, I don;t know much about how that pool is configured or whether I can affect it.
Happy to provide any more info... and thanks for your interest
Chris

**Comment by nickbabcock** [comment]
Dropwizard internally uses the tomcat jdbc pool, and dropwizard is pretty dumb. It configures tomcat properties from the [config](http://www.dropwizard.io/1.0.3/docs/manual/jdbi.html), starts the pool with a wrapper, and passes that right to jdbi.

If you're confident there is a bug, I'd first try and see which library is at fault and isolate them with your app, so use JDBI without a pool. Or use the pool without jdbi.

**Comment by arteam** [comment]
Also you can try to enable the `logAbandoned` option, to test whether your application leaks connections (for example, doesn't close connections) or not. If there a leak, you can try to mitigate it with the `removeAbandoned` option.

**Comment by chrischarlton001** [comment]
Thanks for your comments - problem solved.
There was a clash between DW (Tomcat) connection pool management, and MySQL's connection pool management. A DBA had set  interactive_timeout and wait_timeout to 30 seconds. It looks like MySQL was trying to drop what it thought were idle/abandoned sessions - but DW didn't think they were (being managed as part of the pool). This caused DW to throw an error and grab a new connection - and the cycle continued. So the moral is - have one system or the other managing connection pools and not both (and watch your DBA's too!)

Thanks
