### ISSUE TITLE
Need finer-grain control of exception behaviour in view renderers

### ISSUE THREAD

**Issue by acwwat** [dropwizard/dropwizard#1811]
For background details, please refer to the following user group thread: https://groups.google.com/forum/#!topic/dropwizard-user/wy8ksKjz-HA

This issue is a feature request to enable finer-grain control over exceptions thrown when rendering views, so that one can use custom `ExceptionHandler`s to handle certain exception flows.

For example, when using Mustache a `MustacheNotFoundException` is thrown by the Mustache Java API when the template is not found. It is then wrapped/re-thrown as a `RuntimeException` by `MustacheViewRenderer`, which finally gets caught and re-thrown as a `WebApplicationException` with a generic "template error" response. The exception handler logic would ultimately catch this `WebApplicationException` will simply return the enclosed `Response` instead of filtering further. What I would like to be able to do is to somehow use an `ExceptionHandler` to catch a wrapped exception and inspect the cause which is the view implementation-specific exceptions (Mustache, Fremarker, etc.) In my case, I want to create a 404 error response with custom page instead of the generic 500 error response.

It achieve this, one can perhaps add a config option which `ViewMessageBodyWriter` uses to determine if the re-thrown `WebApplicationException` should include a `Response` or the caught exception in the cause. Then I have a choice to drill down into the exception causes and decide what to do with it in my custom `ExceptionHandler`. (But of course, this will not be view renderer agnostic by my own choice, as I am handling renderer-specific exceptions manually.)

Please let me know if more info is needed, otherwise I appreciate that you consider this as a feature request.

**Comment by acwwat** [comment]
Submitted PR #1820 with a possible implementation.

**Comment by arteam** [comment]
Closed via #1820
