### ISSUE TITLE
Custom appender for requestLog not working in 1.0.3

### ISSUE THREAD

**Issue by matthewjsummers** [dropwizard/dropwizard#1812]
We have a custom appender (it uses the logstash-encoder) to output logs in json.  This is working fine for:

logging:
  appenders:
    - type: console
    - type: logstash-file
      threshold: TRACE
      customFields: '{"service-name":"ms-iam"}'
      currentLogFilename: log/application-json.log
      archivedLogFilenamePattern: log/application-json-%d{yyyy-MM-dd}-%i.log.gz
      archivedFileCount: 7
      timeZone: Europe/Oslo
      maxFileSize: 10MB

However, when we try and add it to requestLog, no logging appears in the request log file.  Are custom appenders not supported for the requestLog?

server:
    requestLog:
    appenders:
    - type: console
    - type: logstash-file
      threshold: TRACE
      currentLogFilename: log/access-json.log
      archivedLogFilenamePattern: log/access-json-%d{yyyy-MM-dd}-%i.log.gz
      archivedFileCount: 7
      maxFileSize: 10MB

**Comment by arteam** [comment]
Hi @matthewjsummers,

Please check if your custom appender correctly works with logging events of the `IAccessEvent` type.
Now in Dropwizard 1.0.* normal and request logs are produced by different libraries (`logback-classic` and `logback-access` respectively). Ideally, your appender should be able to work both with `ILoggingEvent` and `IAccessEvent`. But not all do so (for example, the syslog appender #1801).

**Comment by matthewjsummers** [comment]
Hi @arteam 

The custom appender is simply an extension of FileAppender, that uses a LogstashLayout:

https://gist.github.com/matthewjsummers/65feb02d4e6a4822919e88f2b06e93f2

LogstashLayout should support both ILoggingEvents and IAccessEvents.  Is there anything that needs to be changed in the extended FileAppender, shown in the gist above?

**Comment by matthewjsummers** [comment]
Hi @arteam 
My bad - the underlying framework does support both, but you need to choose a LogstashAccessLayout. I think this just means we need two logappenders - one logging for ILoggingEvents and one for IAccessEvents.

Thanks for your help, closing this down.

**Comment by arteam** [comment]
Yes, I think it's a right approach. You need to create an additional appender with `LogstashAccessLayout` and make it discoverable. But we are thinking to return back old request logging (via `logback-classic` and custom logger) in the form a custom `RequestLogFactory`, because it looks like many people can't easily transit to `logback-access`. 

Thank you, too, for using Dropwizard and reporting the issue.

**Comment by mattnelson** [comment]
@arteam Is there an issue where the access logging implementations are being discussed? I have some thoughts on the subject and this issue doesn't feel like the right place.

**Comment by arteam** [comment]
@mattnelson I am going to create a pull request with a request logging factory implementation, we can discuss it there.

**Comment by arteam** [comment]
By the way, we released 1.0.4, which should provide the option to switch to the "old-style" request-logging with `logback-classic`. Docs are [here](http://www.dropwizard.io/1.0.4/docs/manual/configuration.html#classic-request-log).
