### ISSUE TITLE
healthcheck json is not pretty printed

### ISSUE THREAD

**Issue by mrkam** [dropwizard/dropwizard#1815]
I'd like to have my healthcheck response to be pretty printed.

The following code doesn't seem to affect it
`        environment.getObjectMapper().enable(SerializationFeature.INDENT_OUTPUT)`

How can I enable pretty printing of the healthcheck (i. e. the response of http://localhost:9081/healthcheck)

**Comment by arteam** [comment]
Hi @mrkam,

`HealthCheckServlet` uses own `ObjectMapper`, and you can't change it. But you can get your response pretty printed by passing the `pretty` query parameter to the the health check URI: `http://localhost:9081/healthcheck?pretty=true`.
