### ISSUE TITLE
could i replace jetty with another servlet container?

### ISSUE THREAD

**Issue by rosslight** [dropwizard/dropwizard#1818]
could i use tomcat as the servlet container?

**Comment by arteam** [comment]
Unfortunately, not. Dropwizard is tied to the Jetty server. You can package application as a war file, though to deploy it to another servlet container. See [wizard-in-a-box](https://github.com/rvs-fluid-it/wizard-in-a-box).

**Comment by rosslight** [comment]
Let me try package  application as a war file.
Thank you.
