### ISSUE TITLE
how to let LoggingFeature work?

### ISSUE THREAD

**Issue by rosslight** [dropwizard/dropwizard#1819]
when i use the LoggingFilter to log the request and response, that is ok.
env.jersey().register(new LoggingFilter(Logger.getLogger("InboundRequestResponse"), true));

but when i use LoggingFeature, i can not  get the log,could you tell me there is any thing wrong with the following code:
 env.jersey().register(new LoggingFeature(Logger.getLogger("RequestResponse"), LoggingFeature.Verbosity.PAYLOAD_ANY));

wait for your response

**Comment by arteam** [comment]
It should work if you specify a correct logging level for the `LoggingFeature`:
```java
environment.jersey().register(new LoggingFeature(Logger.getLogger("inbound"),
Level.INFO, LoggingFeature.Verbosity.PAYLOAD_ANY, 8192));

```

**Comment by rosslight** [comment]
When i add the Level.INFO, the LoggingFeature worked. 
Thank you.

**Comment by milansismanovic** [comment]
Sorry for the newby question: Where would you put the above code snippet in?

Is this in a class that extends Application like this (from the documentation https://jersey.github.io/documentation/latest/deployment.html#environmenmt.appmodel):
`public class MyApplication extends Application{...}
`
And where would this be in this class. 

I have the problem to not be able to start a class at startup from Jersey classes.

Help would be greatly appreciated.

Cheers,

milan

**Comment by arteam** [comment]
You should put in your Dropwizard's `Application.run` method implementation, not Jersey's. Rougly speaking, here: https://github.com/dropwizard/dropwizard/blob/master/dropwizard-example/src/main/java/com/example/helloworld/HelloWorldApplication.java#L82
