### ISSUE TITLE
sayHello() in the Getting Started/Resource class doesn't work out of the box

### ISSUE THREAD

**Issue by mcummingscb** [dropwizard/dropwizard#1821]
Using Java 1.8, I can't get this method to compile:
```
    public Saying sayHello(@QueryParam("name") Optional<String> name) {
        final String value = String.format(template, name.orElse(defaultName));
        return new Saying(counter.incrementAndGet(), value);
    }
```

I get incorrect parameter type errors on QueryParam, it doesn't matter if I'm using Java.util.Optional or google's Optional.  I found this SO post but it didn't fix the issue for me: http://stackoverflow.com/questions/27757877/simple-dropwizard-0-7-1-app-failing-over-optional-queryparam-w-java-8

**Comment by joschi** [comment]
@mcummingscb Which version of Dropwizard are you using?

**Comment by mcummingscb** [comment]
I'm using 1.0.4

**Comment by joschi** [comment]
@mcummingscb Please post the complete project you're using so that we can reproduce the issue.

**Comment by mcummingscb** [comment]
@joschi - it's the HelloWorld application from the Getting Started doc: http://www.dropwizard.io/1.0.3/docs/getting-started.html

**Comment by joschi** [comment]
@mcummingscb Please attach the complete project **you** are using.

**Comment by mcummingscb** [comment]
OK, I can't easily do that, my code is not open source.  What specifically do you want to see?  I'm using Java 1.8 and java.util.Optional.  I can try updating my dependencies and a different version of Dropwizard.

**Comment by mcummingscb** [comment]
OK, I checked out the dropwizard repo.  I can run the server and tests just fine from the command line.  However, I see the same incorrect parameter type error in my IDE.  I should have mentioned that that's where I see this issue with my project too, in IntelliJ.

**Comment by mcummingscb** [comment]
@joschi I suppose that this could be an IDE issue.

**Comment by joschi** [comment]
@mcummingscb 
> OK, I can't easily do that, my code is not open source.

So it's not the Hello World application from the Getting Started documentation…

**Comment by mcummingscb** [comment]
No, but I also git cloned the dropwizard repo and I see it there too. @joschi

**Comment by mcummingscb** [comment]
>OK, I checked out the dropwizard repo. 
^^^

**Comment by joschi** [comment]
@mcummingscb I'm closing this issue as it's not a problem with Dropwizard.

Make sure to use the correct language level and JDK in your IntelliJ IDEA project (Java 8).

**Comment by mcummingscb** [comment]
As I stated, this could be an issue with IntelliJ, I opened a forum question on their site too.  But. . . this is a heads up to you, anyone who used IntelliJ and Java 1.8 (maybe other versions), will see this.

Ha ha, you closed it.  OK.  I am using Java 1.8, the rest of my code is 1.8.

**Comment by joschi** [comment]
@mcummingscb Feel free to link to the discussion in the JetBrains forum or the issue in the JetBrains issue tracker, but I fail to see how this is a problem with Dropwizard.

**Comment by mcummingscb** [comment]
Agreed, I see now that it's not a Dropwizard issue (that wasn't immediately clear to me) yet is still an issue that someone can hit if they're using IntelliJ.  It's annoying if you're new to Dropwizard and bootstrapping a new project.

I found a way to disable these checks here: https://www.jetbrains.com/help/idea/2016.2/coding-assistance-for-rest-development.html

That will probably work fine but I will follow up if it doesn't.
