### ISSUE TITLE
could i get multiple result by jdbi?

### ISSUE THREAD

**Issue by rosslight** [dropwizard/dropwizard#1823]
i want to get multiple result set by the following code, how to get each result?
String strSql = "select * from department;select * from employee;select * from usersetting;";

**Comment by arteam** [comment]
You can't get multiple results with one query with JDBC, you should send 3 separate requests. Alternatively you can try to join your sets on the DB side with SQL `union` operation.

**Comment by rosslight** [comment]
Let me try the SQL union operation. but JDBC support the feather by set allowMultiQueries=true and i want to know if JDBI support the feature.

**Comment by arteam** [comment]
I see, this a MySQL specific feature. You can try pass it to your database connection URL and see how JDBI maps a returned  `ResultSet`.
