### ISSUE TITLE
RFC7230 compliance cannot be disabled in Jetty

### ISSUE THREAD

**Issue by dren-dk** [dropwizard/dropwizard#1824]
I'm terminating TLS in nginx, but I still want access to the full client certificate in my application, until I upgraded dropwizard I did that by putting the client certificate in a header in nginx by using this config line:
proxy_set_header X-SSL-CERT $ssl_client_cert;

The result is that nginx inserts a multi-line header value containing the PEM encoded client certifcate, something that has been deprecated by RFC7230 and although the issue has been known for years by nginx, no alternative has surfaced, see: https://bugs.eclipse.org/bugs/show_bug.cgi?id=483795

I would like to be able to turn off RFC7230 compliance in Jetty until I can get a compliant nginx deployed.

Would it be possible to add a httpCompliance field of the type org.eclipse.jetty.http.HttpCompliance to HttpConnectorFactory that will cause the org.eclipse.jetty.server.HttpConnectionFactory to be created with the specificed org.eclipse.jetty.http.HttpCompliance parameter?

**Comment by arteam** [comment]
Hi @dren-dk,

Yes, that's totally possible. Shouldn't be really hard to implement.

**Comment by dren-dk** [comment]
I've just created a pull request with the change as it did seem to be very straight forward.

**Comment by arteam** [comment]
Closed via #1825
