### ISSUE TITLE
It loses logs when the request log format is customized

### ISSUE THREAD

**Issue by Wstunes** [dropwizard/dropwizard#1827]
My dropwizard version is 1.0.4
Now my request log is like this in the base.yml
<pre><code>requestLog:
    appenders:
      - type: file
        currentLogFilename: ./logs/runtimeService-requests.log
        archive: true
        logFormat: "%h|%reqParameter{something}|%t|%s|%b|%U|%i{Referer}|%i{User-Agent}"
</pre></code>
The log format is customized because I want to get some parameters out in the url.
But the problem is that if I have a sequence of rapid requests to the server like 1000 requests, it only logs about 50 messages in the log file. I doubt it's because the log formatting costs much.

And if I try the classic request log configuration which generates logs in common log format, which does not meet my requirement. Like the following configuration.
<pre><code>requestLog:
    type: classic
</pre></code>

And send 1000 requests to the server. The 1000 request can be all logged into the log file. Nothing missing.

Why does it lose logs when I use custom request log format?
Now the documentation about request log has too many TODOs. Could someone please add some custom information to it?
And will it be same situation in the logging configuration in addition to the requestLog configuration?
Please help.

**Comment by Wstunes** [comment]
@arteam  Could you please have a look at this issue?

**Comment by arteam** [comment]
Hi @Wstunes,

This issue has already been reported in #1672 and #1678. For some reason using `reqParameter` in the request logging pattern leads to race conditions and inconsistent logging. We tried to fix this issue on the Dropwizard side, but unfortunately without success. We need some collaboration with the logback maintainers to figure out how to correctly fix it.

**Comment by Wstunes** [comment]
@arteam
ah Got it.
  And how long do you estimate it will take to contact the logback team and fix this issue? We encoutered this critical problem in prodution.
  Is there a workaround for now?what about I write a log appender on my own and get the request parameter in the url programmingly? Are there examples or documentations for the  customized log appender?

**Comment by arteam** [comment]
I tracked this issue to a buggy Logback converter (`RequestParameterConverter`) which don't work correctly with async appenders. I am going to create a PR which will replace it with a custom one. Let's see if it will help.

**Comment by arteam** [comment]
I sent #1828, it would be great if you could test it.

**Comment by Wstunes** [comment]
@arteam  I want to test it now. But I add dropwizard from the pom.xml. How can I add your latest change to my project and test it?

**Comment by arteam** [comment]
On a unix machine with Maven, you can do something like that:

* `git clone git@github.com:dropwizard/dropwizard.git`
* `git checkout -b fix_reqAttribute_request_logs origin/fix_reqAttribute_request_logs`
* `cd dropwizard-bom/ && mvn clean install`
* `cd ../ && mvn -DskipTests=true -P dev install`

This should install Dropwizard 1.0.5-SNAPSHOT into your local maven repository.

**Comment by Wstunes** [comment]
@arteam 
Thanks for the tutorial.
I've tested the new fix_reqAttribute_request_logs branch.
No logs are missing now. But another critical problem appears.
I just used the same log format in the base.yml like this
<pre><code>requestLog:
    appenders:
      - type: file
        currentLogFilename: ./logs/runtimeService-requests.log
        archive: true
        logFormat: "%h|%reqParameter{something}|%reqParameter{somethingelse}
</pre></code>

But in the request log file  it writes
%PARSER_ERROR[something]|%PARSER_ERROR[somethingelse]
The logback request parameter parser is not working fine.
Can you help fix this?

**Comment by Wstunes** [comment]
@arteam  
Hi I've done a deep test in your branch and found out the problem.
If the log format configuration in the base.yml contains a patternLayout like reqParameter and reqAttribute, the corresponding "RequestAttributeConverter.class" and "RequestParameterConverter.class" will invoke their start() method to register when the application is started.
But now you've overrided the original RequestParameterConverter to SafeRequestParameterConverter in the defaultConverterMap. I find when the application is on, the start() method in "RequestAttributeConverter.class" is invoked but nothing is invoked in the new "SafeRequestParameterConverter.class". This results in the PASERERROR.
So could you check what's wrong with it?
And Could you leave your contact information with me because it's a urgent issue for me . My email is wangshuogr@qq.com. Thanks

**Comment by arteam** [comment]
Hi @Wstunes,

Looks like the source of the error is that `SafeRequestParameterConverter` was not public. so Logback didn't pick it up. I've pushed a new commit to the `fix_reqAttribute_request_logs` branch. Could you please test again?

PS you can find my email address in git logs, fell free to contact me.

**Comment by Wstunes** [comment]
Hi @arteam 
The new change takes effect and the logging works fine and no logs are lost any longer!
Many thx for solving the problem.
I see this will be fixed in 1.0.5.
So when will 1.0.5 be released?
This is a big update and could the release come faster?

**Comment by arteam** [comment]
I can release 1.0.5 in an hour or something like that, so it should become available in a couple of hours in the Maven Central repository.

**Comment by arteam** [comment]
1.0.5 has been released. Please grab it when it becomes available and verify whether it fixes your issue or not.

**Comment by nickbabcock** [comment]
Is this issue related to #1699 / #1686?

**Comment by arteam** [comment]
#1686 is the same issue, I think. I'm not sure about #1699, but it could be related, because async logging called `ServletRequest.getParameterValues` which tried to access a Jetty request which was recycled.

**Comment by Wstunes** [comment]
@arteam
Thanks again for solving the reqParameter problem.
And I have another concern.
I'm afraid that reqAttribute or other parameters in the log format have the same problem.
So you can take care of it in later versions of dropwizard.

**Comment by arteam** [comment]
>  Thanks again for solving the reqParameter problem.

You're welcome. Glad it works for you.

>  I'm afraid that reqAttribute or other parameters in the log format have the same problem.

Actually, I don't think so! As I believe other parameters are copied for deferred processing and Logback converters access copied versions (this is true for attributes). I think I can try to contribute this change to Logback, so we can remove the hack in the future from Dropwizard.

**Comment by arteam** [comment]
FYI, I played a little bit with request logs, and I think `logback-access` it doesn't work correctly with `reqCookie{cookie}`. It reads cookies from the original request.

**Comment by arteam** [comment]
Closing, because the original issue seems to be resolved.
