### ISSUE TITLE
ConfiguredValidator - Accepting multiple validators

### ISSUE THREAD

**Issue by aminy** [dropwizard/dropwizard#1829]
I have a question about the ConfiguredValidator. It's mentioned in the code that having multiple validators is not allowed ([here](https://github.com/dropwizard/dropwizard/blob/7295c5faf42840325c161cc82ad4ed1db2bf8419/dropwizard-jersey/src/main/java/io/dropwizard/jersey/validation/DropwizardConfiguredValidator.java#L72))

I think it should be allowed. an example use case for that will be when validating multiple entities in a call:

```
public Response addBook(
@Auth @Validated(Validations.Existing.class) Author author,
@Validated(Validations.New.class) Book book) {}
```

This gives the ability to the entities themselves to define rules for validations inside the entity class.

If you think this is a good idea I might be able to add this and create a PR for it. 
If it's not a good idea, I appreciate if you can let me know what's the alternative approach.

**Comment by nickbabcock** [comment]
If I recall correctly, this is a limitation of the [HiberateValidator](http://hibernate.org/validator/), but I'd love to be proven wrong 😄

**Comment by aminy** [comment]
challenge accepted! 😉 
I will dig a bit deeper and get back to you on this thread with a possible solution or a workaround.

**Comment by nickbabcock** [comment]
Yes unfortunately you'll need to figure out a workaround with the mutually exclusive group validations.
