### ISSUE TITLE
ViewMessageBodyWriter eats exceptions, preventing the installed ExceptionMapper from mapping the exception

### ISSUE THREAD

**Issue by dren-dk** [dropwizard/dropwizard#1831]
When an exception happens outside the view code, it can be mapped to something reasonable by the ExceptionMapper.

When an exception happens when rendering a view prior to prior to eaea76a37e9a5ac667b99cd81c46353034e8473d all exceptions, except FileNotFoundException where thown out of the writeTo method and thus available for handling by the ExceptionMapper.

After the change to ViewMessageBodyWriter, all Exceptions are eaten and in stead a WebApplicationException is thrown without the original exception and with content, so the ExceptionMapper is prevented from providing customized errors.

Would it be possible to make this behavior configurable, so the original exception is in stead wrapped in an IOException and thrown out of writeTo method?

Or would it be better to always throw the wrapped exception and let an ExceptionMapper handle it?

**Comment by nickbabcock** [comment]
Does #1820 address any of your concerns?

**Comment by dren-dk** [comment]
Yes, that's exactly what I was missing, thank you for showing me that.
