### ISSUE TITLE
Allow debugging for `DropwizardTestSupport`

### ISSUE THREAD

**Issue by ClintEsteMadera** [dropwizard/dropwizard#1836]
Sometimes, when running integration tests locally, one might want to debug the integration test run (specially while developing the test code). I didn't find a way to do this so I'm presuming this is not possible at the moment. I believe this feature will be highly appreciated by most of the users of this class. Thanks.

**Comment by joschi** [comment]
@ClintEsteMadera You can use the standard debugging facilities of your IDE.

* https://www.jetbrains.com/help/idea/2016.2/debugging.html
* http://www.vogella.com/tutorials/EclipseDebugging/article.html
* https://maven.apache.org/components/surefire/maven-surefire-plugin/examples/debugging.html
* https://maven.apache.org/components/surefire/maven-failsafe-plugin/examples/debugging.html

**Comment by ClintEsteMadera** [comment]
sorry, that was embarrasing, I swear I tried once and it didn't work... anyway, thanks! ¯\\_(ツ)\_/¯
