### ISSUE TITLE
The polymorphic auth feature SHOULD NOT be used with any other AuthDynamicFeature. Doing so may have undesired effects.

### ISSUE THREAD

**Issue by huaweigu** [dropwizard/dropwizard#1844]
Hi,

I notice that there's one line in dropwizard doc *The polymorphic auth feature SHOULD NOT be used with any other AuthDynamicFeature. Doing so may have undesired effects.*

Are there any plans to support the coexistence of polymorphic and other dynamic feature? I have a use case, let's say, I have three auth filters, A1, A2 and B. 

A1 and A2 are supposed to be chained to protect some resources with principal A, 
B is used to protect other resources with principal B.

I'm using a chained auth filter (let's call it A) to register A1 and A2, then using polymorphic auth feature to register A and B. Is that the right way to do it? 

Thanks,
hw

**Comment by evnm** [comment]
Hello Huawei. Thanks for asking.

There are no such plans at this time. The chained+polymorphic approach you describe sounds like the right way to do what you want.

**Comment by huaweigu** [comment]
thanks!
