### ISSUE TITLE
dropwizard-forms: No injection source found for a parameter of type public...

### ISSUE THREAD

**Issue by 249043822** [dropwizard/dropwizard#1845]
As i used dropwizard1.0.5 or 1.0.3, added dropwizard-forms for multipart data, and i have configured MultipartBundle , but i still caused  No injection source found for a parameter of type public... exception
@POST
    @Path("uploadFile")
    @Consumes(MediaType.MULTIPART_FORM_DATA)
    @Produces(MediaType.TEXT_HTML)
    public String uploadFile(@FormDataParam("file") InputStream file,
            @FormDataParam("file") FormDataContentDisposition fileDisposition,

but if i use 

@POST
    @Path("uploadFile")
    @Consumes(MediaType.MULTIPART_FORM_DATA)
    @Produces(MediaType.TEXT_HTML)
    public String uploadFile(FormDataMultiPart multiPart

it works , so i don't understand why, maybe jersey should support both, can anyone help me? i thinks dropwizard does not  have clear docs about multipart data, so i'm confusing.

thanks!

**Comment by nickbabcock** [comment]
Please see #1847, which uses your example to show how to use dropwizard-forms.

**Comment by nickbabcock** [comment]
Closing this as OP has not responded and #1847 should been a good enough example
