### ISSUE TITLE
Do you plan to support hibernate multitenancy?

### ISSUE THREAD

**Issue by yateam** [dropwizard/dropwizard#1846]
Hibernate provides support for multitenant application. See [here](http://docs.jboss.org/hibernate/orm/5.2/userguide/html_single/Hibernate_User_Guide.html#multitenacy)
I sort of implemented it in my service: I added `@MultiTenantUnitOfWork` annotation which is similar to `@UnitOfWork` except that when it opens sessions it sets a tenant id:
`session = sessionFactory.withOptions().tenantIdentifier(tenantId).openSession();`
In order to make this work I had to completely rewrite dropwizard-hibernate in my application. 

I am interested if you planning to support hibernate multitenancy in dropwizard?

**Comment by nickbabcock** [comment]
[Looks like as you found](https://github.com/scottaj/dropwizard-auth-multitenancy-example), there are ways to support this already, but I'm sure we'd be happy to accept code that'll make this easier for either a third party module or through dropwizard itself.

**Comment by vaibhavdhawan** [comment]
Hi yateam, 
Do you mind sharing this code? i am trying to achieve multi-tenancy on a database level through hibernate.

**Comment by yateam** [comment]
Hi vaibhavdhawan, in my project I moved to a more traditional way of handling multitenancy - with one database and a `tenant_id` column in necessary tables. Although, I started as described in the first post I had to employ a more simplified approach - due to integration difficulties which I could not afford to spend time on in my relatively small project. 

All I have is a global tenant registry (`ThreadLocal<Tenant>`) where I store a tenant current for a request. And the tenant filter. See here for more details: https://github.com/scottaj/dropwizard-auth-multitenancy-example. I loosely followed that implementation.

**Comment by vaibhavdhawan** [comment]
Hi yateam, 

Thanks for the response. I did look at the source code and yes it is indeed a good way to implement multi tenancy at DB level. I tried to take it a notch higher and tried to make changes to the framework itslef. However still stuck with an exception deep in the framework.

**Comment by nickbabcock** [comment]
The idea for adding multi-tenancy in hibernate orm in dropwizard is a good and sound, it'll require an outside contributor to champion the cause all the way to a PR. If there is renewed interest in this topic, the issue can be re-opened. But until then, there is a workaround and this feature has proven to not be a high priority for time constrained dropwizard maintainers, and so will be closed.
