### ISSUE TITLE
Log when application was gracefully stopped

### ISSUE THREAD

**Issue by scho** [dropwizard/dropwizard#1849]
We currently ran into an issue with some of our `io.dropwizard.lifecycle.Managed` objects taking quite long to stop. When deploying, we kill the java process if it doesn't gracefully stop after some time. It took us some time to figure out, that the application did not stop gracefully.

So we increased the time to wait, until we treat the application as unstoppable. Then we checked the logs for the managed objects to figure out, if everything was stopped properly. Later, we added a dummy managed object as the first managed object, which just logs that it was stopped. Since it's the first one, it will be stopped last. So if it logs something, everything else was stopped properly.

What would have really helped in our situation (and would not be as hacky as adding the dummy managed object), would be a final log statement (similar to `io.dropwizard.server.ServerFactory:  Starting myApplication`) which is logged at the very end of the application's lifetime (after all managed instances were stopped).

What do you think about that? If this feature is something you guys wish to have, just point me into a direction and I'll provide a PR.

**Comment by evnm** [comment]
It seems to me that a solution to this within Dropwizard would be identical to what you're already doing in your application. I don't think the alternative of adding a `LifeCycle.Listener` to the Jetty server object would enforce the desired ordering guarantees.

We could add your dummy managed object (`ManagedShutdownLogger`?) as a public class that users would optionally use in their applications. I'm not sure that there's enough general utility from this feature to include it by default.

**Comment by scho** [comment]
Okay, thanks for the reply. I don't think it's worth adding the dummy managed object to dropwizard, if this is the only way of doing it.
