### ISSUE TITLE
Do you plan to add some DI framework as official module ?

### ISSUE THREAD

**Issue by wbf1013** [dropwizard/dropwizard#1850]
Now, we use the guice or spring is more difficult, and having some compatibility problem. so if official can integrating guice or spring will more effective

**Comment by joschi** [comment]
No, not in the near future.

This being said, [HK2](https://hk2.java.net/) is already included in Dropwizard due to Jersey.

**Comment by blling** [comment]
#2148  maybe will  use guice instad of hk2
