### ISSUE TITLE
Should jackson ParameterNamesModule be supplied?

### ISSUE THREAD

**Issue by mattnelson** [dropwizard/dropwizard#1852]
As part of the uplift to Java 8 for 1.x should the jackson parameter names module have been supplied by default?

https://github.com/FasterXML/jackson-modules-java8/tree/master/parameter-names

**Comment by nickbabcock** [comment]
Yeah that'd be a fine contribution, as long as everything remains backwards compatible 👍

**Comment by arteam** [comment]
Agreed, would be nice too see support for this module in the core as Dropwizard targets Java8 and the parameter module should be production ready. My only concern is the support of users who don't compile their code with the debug information.
