### ISSUE TITLE
HTTPS Connector doc does not accurately reflect Jetty 9.3 default value for excludedCipherSuites

### ISSUE THREAD

**Issue by rondagostino** [dropwizard/dropwizard#1853]
As per #1700 only TLS 1.2 is supported out-of-the-box with Dropwizard 1.0+ due to a code change in Jetty 9.3 (see https://github.com/eclipse/jetty.project/commit/0a1b0b2bc69ea7e7f5f44992f47a84f926cdeebb) that sets a very restrictive default `excludedCipherSuites` value, but the HTTPS Connector documentation shows the default value for `excludedCipherSuites` as being `(none)`. The documentation should accurately reflect the default, which is `^.*_RSA_.*_(MD5|SHA|SHA1)$`. (I guess regular expressions are supported, which the doc should also indicate.)

**Comment by rondagostino** [comment]
Duplicate of #1702

**Comment by rondagostino** [comment]
Actually, #1702 documents how to workaround the default value in Jetty 9.3 but does not actually fix the configuration guide, which still incorrectly states `(none)` instead of the Jetty 9.3 default of `^.*_RSA_.*_(MD5|SHA|SHA1)$`

**Comment by evnm** [comment]
Good catch. I took a stab at updating the documention in #1854.

**Comment by arteam** [comment]
#1854 has been merged to master. Thanks @rondagostino, for pointing out to this documentation mismatch.
