### ISSUE TITLE
Improve visibility for logging configuration options in documentation

### ISSUE THREAD

**Issue by dennyac** [dropwizard/dropwizard#1856]
I just recently discovered that with the logging configuration defaults for [Discarding Threshold](https://github.com/dropwizard/dropwizard/blob/7295c5faf42840325c161cc82ad4ed1db2bf8419/dropwizard-logging/src/main/java/io/dropwizard/logging/AbstractAppenderFactory.java#L69-L71), logging events of level TRACE, DEBUG and INFO will be discarded when the blocking queue has 20% capacity remaining.  

The documentation for discarding threshold and queue size options are hideen in the Dropwizard Javadocs in AbstractAppenderFactory. For more visibility, I feel it may be beneficial to include it [here](http://www.dropwizard.io/1.0.5/docs/manual/configuration.html#logging) or [here](http://www.dropwizard.io/1.0.5/docs/manual/core.html#logging). If others feel the same, I'll go ahead and raise a PR.

PS: I came across this blog entry regarding logback logging - http://blog.takipi.com/how-to-instantly-improve-your-java-logging-with-7-logback-tweaks/

**Comment by arteam** [comment]
Agreed, this is important information from the operation point of view. By default we discard some informational events to maintain the quality of service, but this trade-off could be not acceptable for some applications. You can go ahead and create a PR.

**Comment by arteam** [comment]
Closed by #1858
