### ISSUE TITLE
For migrations, construct and configure Database prior to instantiating Liquibase instance

### ISSUE THREAD

**Issue by nathklei** [dropwizard/dropwizard#1857]
The Liquibase constructor creates an instance of ChangeLogParameters, which configures its parameters based on the currently configured Database.  The result is that expressions are not properly expanded in change sets, for example a custom postgresql index:

CREATE INDEX my_jsonb_index ON ${database.defaultSchemaName}.my_jsonb_table USING GIN (my_jsonb_tbl)

Liquibase at this point has not been supplied the defaultSchemaName, and so inserts 'public'.

By Instantiating the Database before passing to the Liquibase constructor and configuring based on the Namespace, schema and catalog should be set before this point.

**Comment by arteam** [comment]
Closed by #1859
