### ISSUE TITLE
Safer and more flexible AbstractDAO for dropwizard-hibernate

### ISSUE THREAD

**Issue by dotCipher** [dropwizard/dropwizard#1862]
It might be nice to have either a different [AbstractDAO](https://github.com/dropwizard/dropwizard/blob/master/dropwizard-hibernate/src/main/java/io/dropwizard/hibernate/AbstractDAO.java) type that handles calls to things like `uniqueResult()` a bit better, since it currently throws a `HibernateException` if there is more than one row.

Could I extend the functionality to include other calls? or add a different type?  Things like allowing varargs for `Criteria` in other would make things a bit nicer to look at as well for implementing classes.

I end up having to write wrappers most of the time when I implement the `AbstractDAO`.

**Comment by arteam** [comment]
Please do, I think that would be nice. I personally not a big fan of Hibernate, but many Dropwizard users actively use this library. The main criteria for a contribution is too keep things backward compatible. Hibernate is not great in this regard, and I would like to not increase the burden of upgrading to a new version from the Dropwizard side.
