### ISSUE TITLE
405 Method Not Allowed doesn't include Allow headers

### ISSUE THREAD

**Issue by jaredkosanovic** [dropwizard/dropwizard#1866]
[The definition for the 405 response code](http://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html) indicates that it must include a list of valid methods for the requested resource. When I make a request using a method that's not the allowedMethods list in the configuration, I get a response with these headers:
Cache-Control →must-revalidate,no-cache,no-store
Content-Length →275
Content-Type →text/html;charset=iso-8859-1
Date →Wed, 28 Dec 2016 00:57:24 GMT

Conversely, making a request using a method that isn't in allowedMethods and isn't supported by my API returns these headers:
Content-Length →52
Content-Type →application/json
Date →Wed, 28 Dec 2016 00:54:28 GMT

This is with version 1.0.2 of Dropwizard.

Using 0.8.2 of Dropwizard, making a request using an forbidden method responds with the expected headers:
Allow →GET,OPTIONS
Cache-Control →must-revalidate,no-cache,no-store
Content-Length →327
Content-Type →text/html; charset=ISO-8859-1
Date →Fri, 23 Dec 2016 16:54:43 GMT

Can we add back functionality to include the Allow header as required by w3?

**Comment by arteam** [comment]
It looks like this functionality were removed by Jersey during a regular update and we picked it up without our knowledge. I will need to look up the reasons behind it in the Jersey changelogs. Maybe some folks had security concerns about exposing too much information for the bad guys poking around in the web with shell scripts.

**Comment by nickbabcock** [comment]
@arteam, I think this is actually a bug on our end as if I set `registerDefaultExceptionMappers: false` in the config, curl reports the following headers:

```
< HTTP/1.1 405 Method Not Allowed
< Date: Sat, 28 Jan 2017 05:40:23 GMT
< Allow: POST,OPTIONS
< Cache-Control: must-revalidate,no-cache,no-store
< Content-Type: text/html;charset=iso-8859-1
< Content-Length: 250
```

**Comment by nickbabcock** [comment]
I have a fix for this, I'll submit a PR later today for review.
