### ISSUE TITLE
dropwizard-testing 1.0.5 (and earlier) JARs from maven don't contain DAOTestRule

### ISSUE THREAD

**Issue by shashankchakelam** [dropwizard/dropwizard#1867]
I can see that the DAOTestRule.java file (https://github.com/dropwizard/dropwizard/blob/master/dropwizard-testing/src/main/java/io/dropwizard/testing/junit/DAOTestRule.java) was created on Aug 27 2016 but it's still not part of the latest Nov 2016 JAR on maven. Is this intentional or was this somehow missed?

I can see that there's an example (https://github.com/dropwizard/dropwizard/blob/master/dropwizard-example/src/test/java/com/example/helloworld/db/PersonDAOTest.java) that uses DAOTestRule but this currently doesn't work because dropwizard-testing doesn't contain it.

**Comment by joschi** [comment]
@shashankchakelam The referenced file is part of Dropwizard 1.1.0 (current `master` branch) and hasn't been backported to Dropwizard 1.0.x.
