### ISSUE TITLE
Assets Bundles with HTTP Basic Athentication 

### ISSUE THREAD

**Issue by sandakith** [dropwizard/dropwizard#1870]
Is there any information related to $Subject when it comes to dropwizard. 

Static contents are initialized as : 
        bootstrap.addBundle(new AssetsBundle("/assets", "/ui", "index.html"));

**Comment by sandakith** [comment]
HI All, Any information regarding "Static Asserts Bundles with HTTP Basic Auth" in dropwizard..?
It seems Jetty has a way to do this, I would like to know if there is a way in dropwizard. http://stackoverflow.com/questions/10750978/basic-http-auth-for-static-pages-in-jetty-8

**Comment by arteam** [comment]
You would need to extend `AssetServlet` and override the `doGet` method. There you can extract credentials from the `Authorization` header, verify them and return a  401 error in case they don't match. You can then create a custom `AssetBundle` and override  the  `createServlet` method in which return your custom servlet.

**Comment by sandakith** [comment]
Thank you for your reply. Is this something dropwizard could do in a future release soon. E.g., adding a parameter block in the config (with necessary details) to enable and disable assets basic auth? 

If there are no such plans, we could go ahead, try it out - if it works as expected and then possibly put a pull request ... please let us know.

**Comment by arteam** [comment]
I don't think that such a common scenario. Usually static resources are JS libraries, CSS and HTML templates, which rarely need to protected. In most cases, Dropwizard applications are deployed behind a web server like Nginx, where you can easily set authentification for a specific resource in an easy manner. 

Having said that, pull requests are always welcome. You can submit your code to discuss implementation ideas and bring an attention of other developers who may be interested in the same feature.
