### ISSUE TITLE
jetty 9.4 support

### ISSUE THREAD

**Issue by natnan** [dropwizard/dropwizard#1874]
I couldn't find any activity about jetty 9.4 and it seems 1.1.0 release will also be 9.3 based.

Any plans about it?

I'm asking mainly for unix domain socket support, which will probably require some dropwizard changes in order to support it with yaml. Or we can also live with our own ConnectorFactory until the changes are there I suppose.

**Comment by arteam** [comment]
I remember we tried to update Dropwizard to it in #1865, but stumbled upon on some issues with failed tests. Will try to investigate.
