### ISSUE TITLE
Serve dropwizard.io over HTTPS

### ISSUE THREAD

**Issue by evnm** [dropwizard/dropwizard#1878]
The project's website doesn't have an SSL cert. We should add one.

**Comment by arteam** [comment]
That would be great. AFAIK, the Dropwizard site is hosted via GitHub Pages, and they don't support HTTPS for custom domains. Even we get a certificate from Let's Encrypt, we can't set it up.

An alternative is to rent a machine from a cloud provider, install Nginx and and host the site via it, but it adds additional maintenance costs for us.

**Comment by joschi** [comment]
We might be able to leverage CloudFlare for this: https://blog.cloudflare.com/introducing-universal-ssl/

**Comment by joschi** [comment]
This being said, I've been thinking about moving the documentation to ReadTheDocs.org, which saves us from building the Sphinx documentation for every build ourselves and provides nice features like search.

This could probably also be fronted by CloudFlare for HTTPS on our custom domain.

**Comment by evnm** [comment]
The site is just static HTML, so we could host it directly out of an S3 bucket with an SSL'd ELB.

I like @joschi's Read The Docs idea.

**Comment by kishaningithub** [comment]
Firebase hosting offers free SSL to custom domains. I have used it for several of my client's static sites.

**Comment by zloster** [comment]
I've done some research recently about the static pages website hosting.
Let's start with this list: https://designrope.com/toolbox/static-web-hosting/ It covers most of the offers. Please note that some of the services are not functional anymore. Others were bought from the bigger players. For example DivShot was bought from Firebase.
Mine conclusion from reviewing the offers was that custom domain with custom SSL certificate (Let's encrypt or something else) is in the paid layers or the limits for the maximum allowed traffic are too low.

So `free` is not an option.

However one notable missing offer is from [GitLab pages](https://pages.gitlab.io/). They support custom SSL certificate on custom domains. They don't have hard limits on the traffic. Also have excellent deployment procedures with customizations (the basic option is to spin a Docker image in the cloud where the build runs, also it is possible to provide your own runner machines). They have [example project that's building `sphinx` documentation](https://gitlab.com/pages/sphinx). And here are the [logs from sample deploy](https://gitlab.com/pages/sphinx/builds/11365637) of the said site. I currently use GitLab pages with Let's Encrypt certificate for very small static site. The main hassle is the key rotation - I haven't automated it yet and there could be obstacles.

Other interesting options seem to be [Netlify offer](https://www.netlify.com/open-source/) for Open Source projects. They offer their Pro plan for free. I don't know if they have `sphinx` support and how the SSL keys rotation is working.

Of course the above options are worth considering if you try to go with `absolute` free way. I don't know what kind of traffic hits the dropwizard domain. The Amazon S3 and the similar bucket offers will cost something and are not predictable. Yes, it could be half a dollar a month. Or more. The key rotation procedure is manual again or will need custom implementation.

**Comment by nickbabcock** [comment]
Not sure when this was solved but it appears fixed 😅 

![image](https://user-images.githubusercontent.com/2106129/41328639-be251c00-6e8e-11e8-9235-885b73b7d349.png)
