### ISSUE TITLE
HibernateException: No CurrentSessionContext configured! with DW 0.8 -> 1.0.5 migration

### ISSUE THREAD

**Issue by jshort** [dropwizard/dropwizard#1879]
The Hibernate configuration for some unit tests of a project I'm working on no longer work when upgrading to 1.0.5 (Hibernate 4.3.x to 5.1).

The classic solution to HibernateException: No CurrentSessionContext configured! seems to be some configuration that we already have:

[Unit test code](https://github.com/carltonwhitehead/coner/blob/master/dropwizard-app/src/test/java/org/coner/hibernate/dao/AbstractDaoTest.java#L33)

The latest dropwizard docs don't mention anything about a change in how to bootstrap/configure hibernate.

The issue is exposed when calling `sessionFactory.getCurrentSession();` for the first time.

**Comment by jshort** [comment]
So I worked around it:

https://github.com/jshort/coner/commit/547320a9a4ef2ce40ad0a4952f6f8f103060d680#diff-d7fea026ac41251215bf751076924074

Note that by setting the db user/pass/url/driver directly in the Hibernate Configuration rather than using the dropwizard DataSourceFactory and a ConnectionProvider, everything works as it used to.

The code is, admittedly, much simpler/cleaner, but I still wonder if something changes in the DataSourceFactory since 0.8.0 such that this way of configuring hibernate to connect to hsqldb is no longer supported.  Or it might be Hibernate?

**Comment by jshort** [comment]
By the way, the DAOTestRule in master works in this case and is MUCH cleaner (have to add a few more invocations in the builder to use hsqldb vs h2).

When will this class make it into a release?

**Comment by arteam** [comment]
Thank you for the diff! I will try to poke around in your project a little bit to find a clue. I guess the source of the error stems from different mechanisms of initialization of `SessionFactory`. `HibernateModule` is initialized from a managed data source produced by `DataSourceFactory` and uses `DatasourceConnectionProviderImpl`, but `DAOTestRule` builds `SessionFactory` from the configuration at uses `DriverManagerConnectionProviderImpl`. 

Regarding your second question, `DAOTestRule will be part of 1.1.0 release. I can't give a precise ETA, but I think we will releases in a month or so.
