### ISSUE TITLE
Can't send mock object for testing POST action

### ISSUE THREAD

**Issue by s101d1** [dropwizard/dropwizard#1880]
Let's say I have an entity like this:

```
public class User {
    @JsonProperty
    private long id;

    public long getId() {
        return this.id;
    }

    public User() {
    }

    public User(long id) {
        this.id = id;
    }
}
```

Then assuming I have created UsersResource class with post action (POST /users) which accept the User entity, I created UsersResourceTest:

```
public class UsersResourceTest {

    private static final UserStore dao = mock(UserStore.class);

    @ClassRule
    public static final ResourceTestRule resources = ResourceTestRule.builder()
        .addResource(new UserResource(dao))
        .build();

     ...

    @Test
    public void testPostUser() {
        User user = mock(User.class);
        when(user.getId()).thenReturn(1L);
        final Response response = resources.client().target("/users").request().post(Entity.json(user));
        assertEquals(response.getStatus(), 201);
    }
}
```

When I run the test, I got error:

> ERROR [2017-01-13 12:03:18,502] org.glassfish.jersey.test.inmemory.InMemoryConnector: Error while writing entity to the output stream.
> ! java.lang.StackOverflowError: null
> ! at java.lang.ClassLoader.defineClass1(Native Method)
> ! at java.lang.ClassLoader.defineClass(ClassLoader.java:760)
> ! at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
> ! at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
> ! at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
> ! at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
> ! at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
> ! at java.security.AccessController.doPrivileged(Native Method)
> ! at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
> ! at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
> ! at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
> ! at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
> ! at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:697)
> ! ... 1011 common frames omitted
> ! Causing: com.fasterxml.jackson.databind.JsonMappingException: Infinite recursion (StackOverflowError) (through reference chain: org.mockito.internal.stubbing.InvocationContainerImpl["invocationForStubbing"]->org.mockito.internal.invocation.InvocationMatcher["invocation"]->org.mockito.internal.creation.bytebuddy.InterceptedInvocation["mock"]->...

But if I changed the code not to send mock object as post data, the test is working fine:

```
    @Test
    public void testPostUser() {
        User user = new User(1L);
        final Response response = resources.client().target("/users").request().post(Entity.json(user));
        assertEquals(response.getStatus(), 201);
    }
```

So how do I send mock object for testing post action? Is it not possible?

FYI I'm using dropwizard v1.0.5.

**Comment by joschi** [comment]
@s101d1 What's the code of `UserResource`? Why would you use a mock for a simple object like `User`?

**Comment by s101d1** [comment]
Just returning Response object with status 200.

**Comment by joschi** [comment]
@s101d1 This is an issue with trying to serialize mocked objects with Jackson, see https://stackoverflow.com/questions/22851462/infinite-recursion-when-serializing-objects-with-jackson-and-mockito for a possible solution.
