### ISSUE TITLE
Dropwizard from 1.0.0 to 1.0.5 JsonProperty

### ISSUE THREAD

**Issue by adrienpessu** [dropwizard/dropwizard#1881]
Hi folks,

I am trying to upgrade dropwizard on my project from 1.0.0 to 1.0.5 and I'm facing an issue with the annotation Jackson JsonProperty. The annotation can not be imported any more. I have seen in the change log that the jackson library have been upgraded in the version 1.0.3 of Dropwizard. It's seem to be the cause. The documentations of dropwizard and Jacksons mention the annotation, so I assume it's still usable.

Do someone have any clue?

Thank you in advance

Adrien

**Comment by joschi** [comment]
@adrienpessu My projects running Dropwizard 1.0.5 are still working and it should actually be a drop-in replacement.

How did you set up your project (i. e. what's your Maven POM or Gradle build file) and which error messages do you see, specifically?

**Comment by adrienpessu** [comment]
I have a compilation error because it can not find the Java class behind the annotation JsonProperty.

The dependencies in my pom.xml look like this : 

`<properties>
        <dropwizard.version>1.0.5</dropwizard.version>
    </properties>

    <dependencies>
        <dependency>
            <groupId>io.dropwizard</groupId>
            <artifactId>dropwizard-core</artifactId>
            <version>${dropwizard.version}</version>
        </dependency>
        <dependency>
            <groupId>io.dropwizard</groupId>
            <artifactId>dropwizard-auth</artifactId>
            <version>${dropwizard.version}</version>
        </dependency>
        <dependency>
            <groupId>com.github.toastshaman</groupId>
            <artifactId>dropwizard-auth-jwt</artifactId>
            <version>1.0.2-0</version>
        </dependency>
        <dependency>
            <groupId>org.bitbucket.b_c</groupId>
            <artifactId>jose4j</artifactId>
            <version>0.5.1</version>
        </dependency>
        <dependency>
            <groupId>org.mongodb.morphia</groupId>
            <artifactId>morphia</artifactId>
            <version>1.2.0</version>
        </dependency>
        <dependency>
            <groupId>com.jamierf.dropwizard</groupId>
            <artifactId>dropwizard-logging-loggly</artifactId>
            <version>0.8-SNAPSHOT</version>
        </dependency>
        <dependency>
            <groupId>com.smoketurner</groupId>
            <artifactId>dropwizard-swagger</artifactId>
            <version>1.0.5-4</version>
        </dependency>
        <dependency>
            <groupId>com.github.fge</groupId>
            <artifactId>json-patch</artifactId>
            <version>1.9</version>
        </dependency>

        <dependency>
            <groupId>junit</groupId>
            <artifactId>junit</artifactId>
            <version>4.12</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.mockito</groupId>
            <artifactId>mockito-core</artifactId>
            <version>2.0.82-beta</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.assertj</groupId>
            <artifactId>assertj-core</artifactId>
            <version>3.5.1</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>info.cukes</groupId>
            <artifactId>cucumber-junit</artifactId>
            <version>1.2.5</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>info.cukes</groupId>
            <artifactId>cucumber-java</artifactId>
            <version>1.2.5</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>io.dropwizard</groupId>
            <artifactId>dropwizard-testing</artifactId>
            <version>${dropwizard.version}</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>io.dropwizard</groupId>
            <artifactId>dropwizard-client</artifactId>
            <version>${dropwizard.version}</version>
            <scope>test</scope>
        </dependency>
    </dependencies>`

**Comment by TheWizz** [comment]
I'm using JsonProperty annotations in my DW 1.0.5 project. I see that the following dependency is included:

Group ID: com.fasterxml.jackson.core Artifact ID: jackson-annotations Version: 2.7.0

This artifact includes the JsonProperty class. If your problems persist, you may want to try adding this as en explicit dependency in your POM file.

**Comment by jshort** [comment]
[INFO] +- io.dropwizard:dropwizard-core:jar:1.0.5:compile
[INFO] |  +- io.dropwizard:dropwizard-util:jar:1.0.5:compile
[INFO] |  |  +- com.fasterxml.jackson.core:jackson-annotations:jar:2.7.8:compile

Works for me (just migrated from 0.8.0 => 1.0.5

**Comment by adrienpessu** [comment]
Even when I add in the pom.xml the dependency :
Group ID: com.fasterxml.jackson.core Artifact ID: jackson-annotations Version: 2.7.0

It does not work.

The output of `mvn dependency:tree` is :

`[INFO] com.xxxxx.xxxx.api:service:jar:1.0.0-SNAPSHOT
[INFO] +- io.dropwizard:dropwizard-core:jar:1.0.5:compile
[INFO] |  +- io.dropwizard:dropwizard-util:jar:1.0.5:compile
[INFO] |  |  +- com.fasterxml.jackson.core:jackson-annotations:jar:2.7.8:compile
[INFO] |  |  +- com.google.guava:guava:jar:19.0:compile
[INFO] |  |  +- com.google.code.findbugs:jsr305:jar:3.0.1:compile
[INFO] |  |  \- joda-time:joda-time:jar:2.9.4:compile
[INFO] |  +- io.dropwizard:dropwizard-jackson:jar:1.0.5:compile
[INFO] |  |  +- com.fasterxml.jackson.core:jackson-core:jar:2.7.8:compile
[INFO] |  |  +- com.fasterxml.jackson.core:jackson-databind:jar:2.7.8:compile
[INFO] |  |  +- com.fasterxml.jackson.datatype:jackson-datatype-guava:jar:2.7.8:compile
[INFO] |  |  +- com.fasterxml.jackson.datatype:jackson-datatype-jsr310:jar:2.7.8:compile
[INFO] |  |  +- com.fasterxml.jackson.datatype:jackson-datatype-jdk8:jar:2.7.8:compile
[INFO] |  |  +- com.fasterxml.jackson.module:jackson-module-afterburner:jar:2.7.8:compile
[INFO] |  |  +- com.fasterxml.jackson.datatype:jackson-datatype-joda:jar:2.7.8:compile
[INFO] |  |  \- ch.qos.logback:logback-classic:jar:1.1.7:compile
[INFO] |  +- io.dropwizard:dropwizard-validation:jar:1.0.5:compile
[INFO] |  |  +- org.hibernate:hibernate-validator:jar:5.2.4.Final:compile
[INFO] |  |  |  +- javax.validation:validation-api:jar:1.1.0.Final:compile
[INFO] |  |  |  +- org.jboss.logging:jboss-logging:jar:3.2.1.Final:compile
[INFO] |  |  |  \- com.fasterxml:classmate:jar:1.1.0:compile
[INFO] |  |  \- org.glassfish:javax.el:jar:3.0.0:compile
[INFO] |  +- io.dropwizard:dropwizard-configuration:jar:1.0.5:compile
[INFO] |  |  +- com.fasterxml.jackson.dataformat:jackson-dataformat-yaml:jar:2.7.8:compile
[INFO] |  |  |  \- org.yaml:snakeyaml:jar:1.15:compile
[INFO] |  |  \- org.apache.commons:commons-lang3:jar:3.4:compile
[INFO] |  +- io.dropwizard:dropwizard-logging:jar:1.0.5:compile
[INFO] |  |  +- io.dropwizard.metrics:metrics-logback:jar:3.1.2:compile
[INFO] |  |  +- org.slf4j:jul-to-slf4j:jar:1.7.21:compile
[INFO] |  |  +- ch.qos.logback:logback-core:jar:1.1.7:compile
[INFO] |  |  +- org.slf4j:log4j-over-slf4j:jar:1.7.21:compile
[INFO] |  |  +- org.slf4j:jcl-over-slf4j:jar:1.7.21:compile
[INFO] |  |  \- org.eclipse.jetty:jetty-util:jar:9.3.9.v20160517:compile
[INFO] |  +- io.dropwizard:dropwizard-metrics:jar:1.0.5:compile
[INFO] |  +- io.dropwizard:dropwizard-jersey:jar:1.0.5:compile
[INFO] |  |  +- org.glassfish.jersey.core:jersey-server:jar:2.23.2:compile
[INFO] |  |  |  +- org.glassfish.jersey.media:jersey-media-jaxb:jar:2.23.2:compile
[INFO] |  |  |  \- javax.annotation:javax.annotation-api:jar:1.2:compile
[INFO] |  |  +- org.glassfish.jersey.ext:jersey-metainf-services:jar:2.23.2:compile
[INFO] |  |  +- org.glassfish.jersey.ext:jersey-bean-validation:jar:2.23.2:compile
[INFO] |  |  +- io.dropwizard.metrics:metrics-jersey2:jar:3.1.2:compile
[INFO] |  |  +- com.fasterxml.jackson.jaxrs:jackson-jaxrs-json-provider:jar:2.7.8:compile
[INFO] |  |  |  +- com.fasterxml.jackson.jaxrs:jackson-jaxrs-base:jar:2.7.8:compile
[INFO] |  |  |  \- com.fasterxml.jackson.module:jackson-module-jaxb-annotations:jar:2.7.8:compile
[INFO] |  |  +- org.glassfish.jersey.containers:jersey-container-servlet:jar:2.23.2:compile
[INFO] |  |  +- org.eclipse.jetty:jetty-server:jar:9.3.9.v20160517:compile
[INFO] |  |  |  +- javax.servlet:javax.servlet-api:jar:3.1.0:compile
[INFO] |  |  |  \- org.eclipse.jetty:jetty-io:jar:9.3.9.v20160517:compile
[INFO] |  |  +- org.eclipse.jetty:jetty-webapp:jar:9.3.9.v20160517:compile
[INFO] |  |  |  \- org.eclipse.jetty:jetty-xml:jar:9.3.9.v20160517:compile
[INFO] |  |  \- org.eclipse.jetty:jetty-continuation:jar:9.3.9.v20160517:compile
[INFO] |  +- io.dropwizard:dropwizard-servlets:jar:1.0.5:compile
[INFO] |  |  \- io.dropwizard.metrics:metrics-annotation:jar:3.1.2:compile
[INFO] |  +- io.dropwizard:dropwizard-jetty:jar:1.0.5:compile
[INFO] |  |  +- io.dropwizard.metrics:metrics-jetty9:jar:3.1.2:compile
[INFO] |  |  +- org.eclipse.jetty:jetty-servlet:jar:9.3.9.v20160517:compile
[INFO] |  |  |  \- org.eclipse.jetty:jetty-security:jar:9.3.9.v20160517:compile
[INFO] |  |  +- org.eclipse.jetty:jetty-servlets:jar:9.3.9.v20160517:compile
[INFO] |  |  \- org.eclipse.jetty:jetty-http:jar:9.3.9.v20160517:compile
[INFO] |  +- io.dropwizard:dropwizard-lifecycle:jar:1.0.5:compile
[INFO] |  +- io.dropwizard.metrics:metrics-core:jar:3.1.2:compile
[INFO] |  +- io.dropwizard.metrics:metrics-jvm:jar:3.1.2:compile
[INFO] |  +- io.dropwizard.metrics:metrics-servlets:jar:3.1.2:compile
[INFO] |  |  \- io.dropwizard.metrics:metrics-json:jar:3.1.2:compile
[INFO] |  +- io.dropwizard.metrics:metrics-healthchecks:jar:3.1.2:compile
[INFO] |  +- io.dropwizard:dropwizard-request-logging:jar:1.0.5:compile
[INFO] |  |  \- ch.qos.logback:logback-access:jar:1.1.7:compile
[INFO] |  +- net.sourceforge.argparse4j:argparse4j:jar:0.7.0:compile
[INFO] |  \- org.eclipse.jetty.toolchain.setuid:jetty-setuid-java:jar:1.0.3:compile
[INFO] +- io.dropwizard:dropwizard-auth:jar:1.0.5:compile
[INFO] +- com.github.toastshaman:dropwizard-auth-jwt:jar:1.0.2-0:compile
[INFO] +- org.bitbucket.b_c:jose4j:jar:0.5.1:compile
[INFO] |  \- org.slf4j:slf4j-api:jar:1.7.6:compile
[INFO] +- org.mongodb.morphia:morphia:jar:1.2.0:compile
[INFO] |  +- org.mongodb:mongo-java-driver:jar:3.2.2:compile
[INFO] |  +- cglib:cglib-nodep:jar:2.2.2:compile
[INFO] |  \- com.thoughtworks.proxytoys:proxytoys:jar:1.0:compile
[INFO] +- com.jamierf.dropwizard:dropwizard-logging-loggly:jar:0.8-SNAPSHOT:compile
[INFO] |  +- ch.qos.logback.contrib:logback-json-classic:jar:0.1.2:compile
[INFO] |  |  \- ch.qos.logback.contrib:logback-json-core:jar:0.1.2:compile
[INFO] |  +- ch.qos.logback.contrib:logback-jackson:jar:0.1.2:compile
[INFO] |  \- org.logback-extensions:logback-ext-loggly:jar:0.1.2:compile
[INFO] +- com.smoketurner:dropwizard-swagger:jar:1.0.5-4:compile
[INFO] |  +- io.dropwizard:dropwizard-assets:jar:1.0.5:compile
[INFO] |  +- io.dropwizard:dropwizard-views:jar:1.0.5:compile
[INFO] |  +- io.dropwizard:dropwizard-views-freemarker:jar:1.0.5:compile
[INFO] |  |  \- org.freemarker:freemarker:jar:2.3.23:compile
[INFO] |  +- org.glassfish.jersey.media:jersey-media-multipart:jar:2.23.2:compile
[INFO] |  |  +- org.glassfish.jersey.core:jersey-common:jar:2.23.2:compile
[INFO] |  |  |  +- org.glassfish.jersey.bundles.repackaged:jersey-guava:jar:2.23.2:compile
[INFO] |  |  |  \- org.glassfish.hk2:osgi-resource-locator:jar:1.0.1:compile
[INFO] |  |  \- org.jvnet.mimepull:mimepull:jar:1.9.6:compile
[INFO] |  \- io.swagger:swagger-jersey2-jaxrs:jar:1.5.12:compile
[INFO] |     +- io.swagger:swagger-jaxrs:jar:1.5.12:compile
[INFO] |     |  +- io.swagger:swagger-core:jar:1.5.12:compile
[INFO] |     |  |  \- io.swagger:swagger-models:jar:1.5.12:compile
[INFO] |     |  |     \- io.swagger:swagger-annotations:jar:1.5.12:compile
[INFO] |     |  \- org.reflections:reflections:jar:0.9.10:compile
[INFO] |     |     \- com.google.code.findbugs:annotations:jar:2.0.1:compile
[INFO] |     \- org.glassfish.jersey.containers:jersey-container-servlet-core:jar:2.1:compile
[INFO] +- com.github.fge:json-patch:jar:1.9:compile
[INFO] |  \- com.github.fge:jackson-coreutils:jar:1.6:compile
[INFO] |     \- com.github.fge:msg-simple:jar:1.1:compile
[INFO] |        \- com.github.fge:btf:jar:1.2:compile
[INFO] +- junit:junit:jar:4.12:test
[INFO] |  \- org.hamcrest:hamcrest-core:jar:1.3:test
[INFO] +- org.mockito:mockito-core:jar:2.0.82-beta:test
[INFO] |  +- net.bytebuddy:byte-buddy:jar:1.4.8:test
[INFO] |  \- org.objenesis:objenesis:jar:2.4:test
[INFO] +- org.assertj:assertj-core:jar:3.5.1:test
[INFO] +- info.cukes:cucumber-junit:jar:1.2.5:test
[INFO] |  \- info.cukes:cucumber-core:jar:1.2.5:test
[INFO] |     +- info.cukes:cucumber-html:jar:0.2.3:test
[INFO] |     +- info.cukes:cucumber-jvm-deps:jar:1.0.5:test
[INFO] |     \- info.cukes:gherkin:jar:2.12.2:test
[INFO] +- info.cukes:cucumber-java:jar:1.2.5:test
[INFO] +- io.dropwizard:dropwizard-testing:jar:1.0.5:test
[INFO] |  \- org.glassfish.jersey.test-framework.providers:jersey-test-framework-provider-inmemory:jar:2.23.2:test
[INFO] |     +- org.glassfish.jersey.test-framework:jersey-test-framework-core:jar:2.23.2:test
[INFO] |     \- org.ow2.asm:asm-debug-all:jar:5.0.4:test
[INFO] \- io.dropwizard:dropwizard-client:jar:1.0.5:test
[INFO]    +- org.glassfish.jersey.core:jersey-client:jar:2.23.2:compile
[INFO]    |  +- javax.ws.rs:javax.ws.rs-api:jar:2.0.1:compile
[INFO]    |  +- org.glassfish.hk2:hk2-api:jar:2.5.0-b05:compile
[INFO]    |  |  +- org.glassfish.hk2:hk2-utils:jar:2.5.0-b05:compile
[INFO]    |  |  \- org.glassfish.hk2.external:aopalliance-repackaged:jar:2.5.0-b05:compile
[INFO]    |  +- org.glassfish.hk2.external:javax.inject:jar:2.5.0-b05:compile
[INFO]    |  \- org.glassfish.hk2:hk2-locator:jar:2.5.0-b05:compile
[INFO]    |     \- org.javassist:javassist:jar:3.20.0-GA:compile
[INFO]    +- org.apache.httpcomponents:httpclient:jar:4.5.2:test
[INFO]    |  +- org.apache.httpcomponents:httpcore:jar:4.4.4:test
[INFO]    |  \- commons-codec:commons-codec:jar:1.9:test
[INFO]    +- io.dropwizard.metrics:metrics-httpclient:jar:3.1.2:test
[INFO]    \- org.glassfish.jersey.connectors:jersey-apache-connector:jar:2.23.2:test
`

**Comment by joschi** [comment]
@adrienpessu 
> Even when I add in the pom.xml the dependency :
> Group ID: com.fasterxml.jackson.core Artifact ID: jackson-annotations Version: 2.7.0
> 
> It does not work.

That sounds more like an issue with your IDE and the output of `mvn dependency:tree` clearly shows that `jackson-annotations` is being pulled in.

FWIW, it's working for me as well (using Dropwizard 1.0.5 in a basic project with IntellIJ IDEA) and for @jshort, so I'll close this issue.

**Comment by adrienpessu** [comment]
I use IntelliJ too. When I execute `mvn clean compile` with the IDE or in command line it's the same result.

**Comment by adrienpessu** [comment]
I found it.
The issue come from my private repository. It download empty jar.

Thank you very much for helping me investigate.
