### ISSUE TITLE
FuzzyEnumModule break the @JsonProperty  deserialize logic for enum type

### ISSUE THREAD

**Issue by zizifn** [dropwizard/dropwizard#1888]
FasterXMLsupport the @JsonProperty for serialize/deserialize  enum type.
`public enum Event {
    @JsonProperty("forgot password")
    FORGOT_PASSWORD;
}`
refer code https://github.com/FasterXML/jackson-databind/commit/707db7a972e2d088647450f9a890c438fb735933

But it's seem FuzzyEnumModule  break the deserialize logic. In FuzzyEnumModule , it's can't deserialize "**forgot password**" to enum.

**Comment by arteam** [comment]
Thank you for reporting this problem. Unfortunately, it looks like we can't handle it transparently in FuzzyEnumModule (there is no Jackson option for this feature, so we can't delegate deserialization to Jackson in runtime). I guess a workaround is too provide a custom `ObjectMapper` during creation of your application in the `initialize` method. You can set it via `Bootstrap.setObjectMapper`.

**Comment by zizifn** [comment]
Thank for quick reply this issue.
I found another workaround by override `toString()` method.
`public enum Event { @JsonProperty("forgot password") FORGOT_PASSWORD{
 @Override
public String toString() {
return "forgot password";
}
}; }`
This looks complicated than @JsonProperty. But it's a workaround anyway.
If I can ask, why dropwizard override some deserialize instand of use Jackson directly?

**Comment by arteam** [comment]
For historical reasons, mostly. When Dropwizard started, Jackson didn't have advanced enum support, so `FuzzyEnumModule` was included in the project to support some scenarios which Jackson lacked.
With time Jackson improved, but we are now stuck with `FuzzyEnumModule` and can't remove it to maintain backward compatibility. Maybe we will remove it in Dropwizard 2.0, but not sooner.
