### ISSUE TITLE
UnixSocketConnector support

### ISSUE THREAD

**Issue by natnan** [dropwizard/dropwizard#1889]
Having bumped jetty to 9.4 (#1874), dropwizard can now support listening on unix domain sockets.

Currently, [HttpConnectorFactory](https://github.com/dropwizard/dropwizard/blob/66ef230d7587fe27204e3be90f90a703ef7726ae/dropwizard-jetty/src/main/java/io/dropwizard/jetty/HttpConnectorFactory.java#L526) is directly coupled to Jetty's ServerConnector class which is tcp-based. It also requires port configuration which is unnecessary for domain sockets.

A new ConnectorFactory with unix domain socket configuration would be great. https://github.com/eclipse/jetty.project/commit/7843b7348e6bd238595d0021e1740ac7e28ba18d

It's probably and hopefully possible to accomplish this by creating my own ConnectorFactory with a lot of duplication (or by inheriting HttpConnectorFactory if the access modifiers are right) thanks to the abstraction. But I think it's a relevant feature to support out of the box in dropwizard and is good to have it in the backlog.

**Comment by arteam** [comment]
That would be interesting. We already got HTTPS and HTTP/2 support, and we could try to provide a connector for Unix sockets as well. I guess the main use case is a Dropwizard server behing a HAProxy server on the same host.

**Comment by nickbabcock** [comment]
Yeah the folks behind Jetty [make it sound](https://webtide.com/unix-sockets-for-jetty-9-4/) like there would be a performance improvement as well (using HAProxy as an ssl terminator). It'd be interesting to quantify these statements 😄

**Comment by nickbabcock** [comment]
I did some performance tests with the new unix socket connector based on #1893. Individual requests seem to work fine, but when under a stress test (from `wrk`) I start receiving many errors:

```
org.glassfish.jersey.server.ServerRuntime$Responder: An I/O error has occurred while writing a response message entity to the container output stream.
! java.io.IOException: Broken pipe
! at jnr.enxio.channels.NativeSocketChannel.write(NativeSocketChannel.java:93)
! at org.eclipse.jetty.io.ChannelEndPoint.flush(ChannelEndPoint.java:279)
```

Even using the latest snapshot of 9.4.1 didn't seem to fix these errors. This is probably not the issue to report this problem, but I wanted to disseminate this info in case anyone was going to jump on the unix socket bandwagon 😄

**Comment by natnan** [comment]
Oh thanks. Do you know if there is any issue reported on the Jetty side?

**Comment by nickbabcock** [comment]
Potentially https://github.com/eclipse/jetty.project/issues/1263, but I'm working on a minimally reproducible test case using just jetty code

**Comment by nickbabcock** [comment]
Work can begin on this again as https://github.com/eclipse/jetty.project/issues/1281 was solved by working around a bug in the underlying jnr library.

**Comment by mbyczkowski** [comment]
Are there any plans to bring UnixSocketConnector support in the near future? It would make it easier to run dropwizard apps with a sidecar proxy (like Envoy).

**Comment by natan-abolafya** [comment]
now that dropwizard on jetty 11 and it seems the support isn't experimental anymore, any hope on this feature?
Or is it possible to create my own HttpConnectorFactory you think?
