### ISSUE TITLE
Can't find DAOTestRule.java  at dropwizard-testing maven 1.0.5 version jar

### ISSUE THREAD

**Issue by mutaherul** [dropwizard/dropwizard#1895]
Can't find DAOTestRule.java  at dropwizard-testing maven 1.0.5 version jar.

**Comment by joschi** [comment]
@mutaherul That's because it's only available in Dropwizard 1.1.x and later.

https://github.com/dropwizard/dropwizard/commits/master/dropwizard-testing/src/main/java/io/dropwizard/testing/junit/DAOTestRule.java

**Comment by mutaherul** [comment]
Thanks.
