### ISSUE TITLE
JSON configuration not working

### ISSUE THREAD

**Issue by manuel-hegner** [dropwizard/dropwizard#1896]
Heyo,
the manual states

> If your configuration file doesn’t end in .yml or .yaml, Dropwizard tries to parse it as a JSON file.

This seems to be no longer the case. In order to actually use a JSON configuration file I had to write a custom ConfigurationFactory.
```java
public class JSONConfigurationFactory<T> extends YamlConfigurationFactory<T> {

	private ObjectMapper mapper;
	private JsonFactory factory;

	public JSONConfigurationFactory(Class<T> klass, Validator validator, ObjectMapper objectMapper, String propertyPrefix) {
		super(klass, validator, objectMapper, propertyPrefix);
		
        // Sub-classes may choose to omit data-binding; if so, null ObjectMapper passed:
        if (objectMapper == null) { // sub-class has no need for mapper
            mapper = null;
            factory = null;
        } else {
            mapper = objectMapper.copy()
                    .enable(DeserializationFeature.FAIL_ON_UNKNOWN_PROPERTIES);
            factory = new JsonFactory();
        }
	}

	@Override
    public T build(ConfigurationSourceProvider provider, String path) throws IOException, ConfigurationException {
        try (InputStream input = provider.open(requireNonNull(path))) {
            final JsonNode node = mapper.readTree(factory.createParser(input));

            if (node == null) {
                throw new RuntimeException("Configuration at " + path + " must not be empty");
            }

            return build(node, path);
        }
    }
}
```

Maybe I am just misunderstanding something here and  it is simply my fault but I think this is either a bug or an outdated note in the documentation. I would be willing to fix the JSON support and submit a pull request if this is indeed a missing/bugged feature.

**Comment by scho** [comment]
Does the file end with `.json`? Which command do you use, `server`?
We've been using json configuration files since version `0.7.x` and currently, we are on `1.0.5`.

**Comment by manuel-hegner** [comment]
Oh that is interesting. When I start my server without the custom factory I get the error

```
Exception in thread "main" com.fasterxml.jackson.databind.JsonMappingException: YAML decoding problem: while scanning for the next token
found character 	 '\t(TAB)' that cannot start any token. (Do not use \t(TAB) for indentation)
 in 'reader', line 2, column 1:
    	"inputs": [
```

I am also currently on 1.0.5 and I start the server with `built.jar server config.json`

**Comment by scho** [comment]
Can you post the output from `mvn dependency:tree`?

**Comment by manuel-hegner** [comment]
Then I would argue that the missing tab support for JSON is a bug, because it should be valid. I would like to add a more explicit JSON parsing support to the ConfigurationFactory that supports tabs and other possible pitfalls, but I can't find the class where the JSON is parsed.

All I see is that YamlConfigurationFactory calls com.fasterxml.jackson.dataformat.yaml.YAMLParser. Does this parser also support JSON or is there a condition I overlooked?

Do you know of any relevant tests that I could adapt to parsing JSONs with tabs?
