### ISSUE TITLE
How do I get a host of the current application? 

### ISSUE THREAD

**Issue by yateam** [dropwizard/dropwizard#1902]
How do I get a host of the current application? 
I need full host, port, etc. in one of my services but I could not figure how I would get them in the application?

**Comment by joschi** [comment]
@yateam What exactly do you mean with "get a host of the current application"? Please elaborate and provide a use case for this.

**Comment by yateam** [comment]
By host I mean the same thing as what javax.servlet.ServletRequest returns when its getServerName is invoked - the host name of the server. I would like to get that hostname during application configuration phase - so I pass it to some internal services - which do not serve requests (like Resource classes do) - thus do not have a direct access to a server context object.

**Comment by joschi** [comment]
@yateam You could use [`HttpConnectorFactory#getBindHost()`](http://www.dropwizard.io/1.0.5/dropwizard-jetty/apidocs/io/dropwizard/jetty/HttpConnectorFactory.html#getBindHost--) and [`HttpConnectorFactory#getPort()`](http://www.dropwizard.io/1.0.5/dropwizard-jetty/apidocs/io/dropwizard/jetty/HttpConnectorFactory.html#getPort--) for this or simply get the system's IP address with `InetAddress.getLocalHost().getHostName()`;
