### ISSUE TITLE
Problem when handling path versions

### ISSUE THREAD

**Issue by omryhay-unibeam** [dropwizard/dropwizard#1903]
When using the "/api/v1-2-3" path pattern, one of the resource is not registered correctly and return 404 "Not Found" when issuing a request.

In the following example we should have two version of the same API:
```Java
@Path("/api/")
public class SomeResource
{
    @GET
    @Path("v1/some_resource")
    public Response getV1()
    {
        return Response.ok().entity("V1").build();
    }

    @GET
    @Path("v2/some_resource")
    public Response getV2()
    {
        return Response.ok().entity("V2").build();
    }
}
```

In this case calling "GET /api/v1/some_resource" will result in a "404 Not Found"  and calling "GET /api/v2/some_resource" will result in a "200 V2" response.

Thanks

**Comment by arteam** [comment]
Are you sure you don't have any resources or filters which might conflict with your provided resource? Could you please post what your Dropwizard applications prints during startup?

**Comment by omryhay-unibeam** [comment]
@arteam - After checking it with a test application, without any add-ons or bundles, it seems to be working.
