### ISSUE TITLE
Lombokify Dropwizard

### ISSUE THREAD

**Issue by manuel-hegner** [dropwizard/dropwizard#1907]
Hey,
what do you think about lombokifying Dropwizard? This would reduce to code overhead of many classes a lot without adding any dependencies to dropwizard directly. Because dropwizard requires a current version of Java the build process would not change much if at all. The process could be a gradual one that changes one class after another, replacing Setters and Getters.

The only downside I see is that users need to understand lombok to understand the dropwizard code. On the other hand the maven build could be changed to delombok the sources and use those for the packed sources.

If this is desirable for the Dropwizard project I would be willing to work on this.

**Comment by joschi** [comment]
@manuel-hegner You can use [Project Lombok](https://projectlombok.org/) with your Dropwizard project already.

As for pulling in Project Lombok into Dropwizard, the answer is no.
