### ISSUE TITLE
@UnitOfWork on subresource methods do not work

### ISSUE THREAD

**Issue by yateam** [dropwizard/dropwizard#1910]
Hello,

consider this resource 
```
@Path("root")
public class RootResource {
  @Path("sub")
  public SubResource sub() {
    return new SubResource();
  }
}

public class SubResource {
  @GET
  @UnitOfWork
  public String helloWorld() {
  }
}
```

During initialization `UnitOfWorkApplicationListener.UnitOfWorkEventListener` iterates over resources and their child resources in order to cache all resource methods annotated with `@UnitOfWork` into `methodMap`. Due to a possible Jersey issue, SubResource's methods won't make their way into that map. So basically, Hibernate Session won't exist within `UnitOfWork`-annotated method context. 

I worked this around by populating the map during requests:
```
if (eventType == RequestEvent.Type.RESOURCE_METHOD_START) {
  Method method = event.getUriInfo().getMatchedResourceMethod().getInvocable().getDefinitionMethod();
  UnitOfWork unitOfWork;
  if (methodMap.containsKey(method)) {
    unitOfWork = methodMap.get(method);
  } else {
    unitOfWork = method.getAnnotation(UnitOfWork.class);
    if (unitOfWork != null) {
      methodMap.put(method, unitOfWork);
    }
  }
  
  unitOfWorkAspect.beforeStart(unitOfWork);
```

**Comment by arteam** [comment]
Thank you for the detailed bug report! It was reported in #1806 as well.

**Comment by yateam** [comment]
Thanks! I actually  tried to look for similar bugs before submitting this one but did not see #1806

**Comment by nickbabcock** [comment]
Closing as a dupe
