### ISSUE TITLE
How can I get config value in yml file in normal java class?

### ISSUE THREAD

**Issue by jay-genhot** [dropwizard/dropwizard#1930]
I know we can get config value in yml file in the subclass of Application, but now I am trying to get the config value in other java normal class, I have tried to @Inject the ApiConfiguration to that normal java class, but it can not get the value. 

My question is : if possible to get the config value in the normal class? if yes. how?

Thank you.

**Comment by joschi** [comment]
@jay-genhot You have access to the `Configuration` object inside the [`Application#run`](http://www.dropwizard.io/1.0.6/dropwizard-core/apidocs/io/dropwizard/Application.html#run-T-io.dropwizard.setup.Environment-) method and can pass it to any other class from there.

You can also use HK2 for dependency injection, see https://gist.github.com/joschi/f706e394172988f9200b for an example.

**Comment by jay-genhot** [comment]
@joschi 
Hi , I still can not resolve my issue, my issue here is my normal java class is a util class, it does not managed by Application#run, and there is static field need the value from yml file. Code section below:
public class Util {
public static final String testValue = configuration.fields;
}

How can make this works? thank you very much.

**Comment by joschi** [comment]
@jay-genhot Make sure to initialize the static field in the `Application#run` method or transform it to a method parameter, so that the caller can provide the value.

Additionally, please move this discussion to the Dropwizard mailing list: https://groups.google.com/forum/#!forum/dropwizard-user
