### ISSUE TITLE
add ResourceTestRule.Builder#addResource(Class<?> clazz) method

### ISSUE THREAD

**Issue by yateam** [dropwizard/dropwizard#1934]
Now in order to add a request scoped resource to a test rule you need to use `addProvider(Class<?>)` method, e.g:
```
public static final ResourceTestRule RULE = ResourceTestRule.builder()
          .addProvider(SessionResource.class)
          .build();
```
This is a little bit confusing, since providers in Jersey terms are something which lay between the servlet and a resource.
`addResource(Object resource)` on the other hand adds only singletons, which sometimes does not really fit needs of an application.

**Comment by nickbabcock** [comment]
If I'm understanding you right, the request is to add an alias to `ResourceTestRule`:

```java
public Builder addResource(Class<?> klass) {
    providers.add(klass);
    return this;
}
```

to make it more understandable for those who register their resources the following way:

```java
@Override
public void run(MyConfiguration config, Environment env) {
    env.jersey().register(MyResource.class)
}
```

Correct? 😄

**Comment by yateam** [comment]
Yes, correct.

**Comment by nickbabcock** [comment]
I tried it out, and it worked without needing an override

```java    
@Rule
public final ResourceTestRule resourceTestRule = ResourceTestRule.builder()
        .addResource(MyResource.class)
        .build();
```

So I'm closing this issue as no longer necessary.
