### ISSUE TITLE
Jersey Client does not post form data correctly by default

### ISSUE THREAD

**Issue by MaxMao** [dropwizard/dropwizard#1935]
I am using dropwizard 1.0.6.

I used Jersey Client to send a post request to a server and it gzips the form data without setting proper headers. As a result, the server uses gzipped form data as plain data. When I do setGzipEnabledForRequests(false) it is working correctly.

Sample code
```
        WebTarget webTarget = client.target("http://httpbin.org/post");
        MultivaluedMap<String, String> formData = new MultivaluedHashMap<String, String>();
        formData.add("username", "guest");
        String response = webTarget.request().post(Entity.form(formData), String.class);
```

**Comment by arteam** [comment]
Thanks for the bug report! What do you mean by "without setting proper headers"? When I run your example I see that the client sends the `Content-Encoding` header as `gzip` and the `Content-Type` header as `application/x-www-form-urlencoded`, which is correct.

```
Feb 21, 2017 3:44:20 PM org.glassfish.jersey.logging.LoggingInterceptor log
INFO: 1 * Sending client request on thread main
1 > POST http://httpbin.org/post
1 > Content-Encoding: gzip
1 > Content-Type: application/x-www-form-urlencoded   

Feb 21, 2017 3:44:20 PM org.glassfish.jersey.logging.LoggingInterceptor log
INFO: 1 * Client response received on thread main
1 < 200
1 < Access-Control-Allow-Credentials: true
1 < Access-Control-Allow-Origin: *
1 < Connection: keep-alive
1 < Content-Length: 537
1 < Content-Type: application/json
1 < Date: Tue, 21 Feb 2017 14:44:20 GMT
1 < Server: nginx
{
  "args": {}, 
  "data": "", 
  "files": {}, 
  "form": {
    "\u001f\ufffd\b\u0000\u0000\u0000\u0000\u0000\u0000\u0000 -N-\ufffdK\ufffdM\ufffdM/M-.\u0001\u0000\ufffdJ\ufffdj\u000e\u0000\u0000\u0000": ""
  }, 
  "headers": {
    "Accept-Encoding": "gzip,deflate", 
    "Content-Encoding": "gzip", 
    "Content-Length": "34", 
    "Content-Type": "application/x-www-form-urlencoded", 
    "Host": "httpbin.org", 
    "User-Agent": "jersey-test"
  }, 
  "json": null, 
  "origin": "62.214.102.20", 
  "url": "http://httpbin.org/post"
}
```

**Comment by MaxMao** [comment]
I was expecting to see an unzipped version of "form" data in httpbin.org response. Maybe it's the server side which does not honor "gzip" Content-Encoding properly? My web server is not able to handle the zipped form data as httpbin.org.

**Comment by arteam** [comment]
I am not sure about how https://httpbin.org handles such requests, but I'm quite sure that an HTTP server can decode gzip-encoded requests. Please take a look at [JerseyClientIntegrationTest.java](https://github.com/dropwizard/dropwizard/blob/master/dropwizard-client/src/test/java/io/dropwizard/client/JerseyClientIntegrationTest.java). We have tests there for handling compressed content from the client with an embedded `com.sun.net.httpserver`.

**Comment by MaxMao** [comment]
ok, feel free to close this ticket then.
