### ISSUE TITLE
If a logback appender fails to initialize due to a warning, this warning is not displayed

### ISSUE THREAD

**Issue by wg-tsuereth** [dropwizard/dropwizard#1937]
In `io.dropwizard.logging.DefaultLoggingFactory.configure(...)`, errors encountered while setting up a log appender can be displayed by another (non-failing) appender.  This is done via the logback helper method `ch.qos.logback.core.util.StatusPrinter.printIfErrorsOccurred(LoggerContext)`.

As the name suggests, this prints errors, but not warnings.  We currently have a network appender which fails with a warning.  (That's a problem to file with another project.)

So, as a result of our appender failing with a warning rather than an error, and DefaultLoggingFactory only printing errors, we don't see any indication of the problem.

My suggested fix is pretty simple: in DefaultLoggingFactory, change-
```
StatusPrinter.printIfErrorsOccured(loggerContext);
```
to-
```
StatusPrinter.printInCaseOfErrorsOrWarnings(loggerContext, 0);
```

**Comment by nickbabcock** [comment]
This might be best done as a configuration option in `DefaultLoggingFactory` instead of changing it for all dropwizard users, unless it can be shown that the change should be the default.
