### ISSUE TITLE
List tasks

### ISSUE THREAD

**Issue by aaanders** [dropwizard/dropwizard#1940]
While trying to execute a task on the cli I realized the task names aren't easily accessible. They're logged on application startup but that's it as far as I can see. 

I opened https://github.com/dropwizard/dropwizard/pull/1939 to address this but probably I should have opened an issue to discuss beforehand.

The suggestion is to list all tasks by sending a GET request like this:
```
$ curl http://localhost:8081/tasks
echo
gc
log-level
```

Closing the PR for now. Let me know if I shuold re-open or if you have any other comments.

**Comment by joschi** [comment]
@aaanders Thanks for your contribution.

Feel free to re-open the PR and we'll take a look at it.
