### ISSUE TITLE
Dropwizard 1.0.6 is using SNAPSHOT version of Jetty

### ISSUE THREAD

**Issue by nmcc** [dropwizard/dropwizard#1943]
I'm using Dropwizard 1.0.6 on a production system, which is apparently experiencing some thread and memory leaking along with near-100% CPU usage. 

The profiler shown that the number of active threads is incrementing along time and that the threads are hitting the CPU at some locking mechanism on Jetty (sorry, I didn't take a snapshot at the profiler by then) 

The application receives about 460 calls/seconds from about 5 IP addresses at peak time and after a few hours we can already see the increasing CPU usage and thread count. After a few days, it start to get `java.lang.OutOfMemoryException`s due to heap limits.

As a mitigation measure, I've limited the `maxThreads` to 64 to prevent the thread pool from growing out of our control. I'm waiting to see how that comes out.

Nonetheless, I've noticed that dropwizard 1.0.6 is using a SNAPSHOT version of jetty 9.3, which made me wonder if it shouldn't be using a RELEASE version...

This is the line of the log at startup that dumps the jetty version
```
INFO  [2017-02-28 07:54:30,869] org.eclipse.jetty.server.Server: jetty-9.3.z-SNAPSHOT
```

**Comment by joschi** [comment]
@nmcc Dropwizard 1.0.6 is using Jetty 9.3.9.v20160517: https://github.com/dropwizard/dropwizard/blob/v1.0.6/dropwizard-bom/pom.xml#L29

You can see at https://github.com/eclipse/jetty.project/blob/jetty-9.3.9.v20160517/jetty-util/src/main/java/org/eclipse/jetty/util/Jetty.java#L30-L35 how the version string is being constructed.
