### ISSUE TITLE
HTTP/2 Support in dropwizard

### ISSUE THREAD

**Issue by ramsrib** [dropwizard/dropwizard#1946]
How to enable HTTP/2 support in dropwizard? I couldn't find any documentation or reference for to http2 connector.

By default, it's using HTTP/1.1 only.

```
INFO  [2017-03-03 03:33:49,374] org.eclipse.jetty.server.AbstractConnector: Started application@69c33ea2{SSL,[ssl, http/1.1]}{0.0.0.0:8443}
INFO  [2017-03-03 03:33:49,374] org.eclipse.jetty.server.AbstractConnector: Started admin@59e0d521{HTTP/1.1,[http/1.1]}{0.0.0.0:8081}
```

Note: I'm using 1.1.0-rc1 version of dropwizard.

**Comment by ramsrib** [comment]
Found an answer, 

Added the **dropwizard-http2** as maven dependency and added the following configuration to the yaml file.
```
- type: h2
  port: 8445
  keyStorePath: example.keystore
  keyStorePassword: example

```

After doing the above stuffs,  my server is not starting and failing with the below error:

```
INFO  [2017-03-03 03:50:31,286] io.dropwizard.server.DefaultServerFactory: Registering jersey handler with root path prefix: /
INFO  [2017-03-03 03:50:31,286] io.dropwizard.server.DefaultServerFactory: Registering admin handler with root path prefix: /admin
INFO  [2017-03-03 03:50:31,294] io.dropwizard.server.ServerFactory: Starting Application
**org/eclipse/jetty/alpn/ALPN$ServerProvider**
```

It seems like I've to manually add **alpha-boot** to the dependencies and i did that and now it's failing with this error:

`org.eclipse.jetty.alpn.ALPN must be on JVM boot classpath`

**Comment by ramsrib** [comment]
How to add **alpha-boot** in the JVM boot classpath?

**Comment by ramsrib** [comment]
This documentation clearly says **alpha-boot** should be on the JVM boot classpath to make it work.
http://dropwizard.readthedocs.io/en/latest/manual/configuration.html#http-2-over-tls

Is there a right way to set boot classpath on production servers? 

For Jetty server, adding an parameter **--add-to-start=http2** enables the http2 connector: 
http://www.eclipse.org/jetty/documentation/current/http2-enabling.html

**Comment by arteam** [comment]
Please see http://www.eclipse.org/jetty/documentation/current/alpn-chapter.html. You need to add the following parameter to your JVM startup command `java -Xbootclasspath/p:<path_to_alpn_boot_jar>`

**Comment by ramsrib** [comment]
Is it possible to enable http2 support in dropwizard without manually setting a alpn-boot jar (using -Xbootclasspath) in the classpath?

i.e Is it possible to add an parameter like jetty (--add-to-start=http2) to enable http2 support in dropwizard?

**Comment by joschi** [comment]
> Is it possible to enable http2 support in dropwizard without manually setting a alpn-boot jar (using -Xbootclasspath) in the classpath?

No.
