### ISSUE TITLE
Load Node dist inside Jetty & Dropwizard

### ISSUE THREAD

**Issue by charbonnier666** [dropwizard/dropwizard#1962]
Hi, I have a frontend in angularjs/nodejs, my question is can I load dist inside my dropwizard backend and jetty ? to launch only one server and have only one package

**Comment by arteam** [comment]
You can serve static resources from a JAR file with `AssetsBundle`. Dropwizard can't execute server-side JavaScript code though.

**Comment by charbonnier666** [comment]
@arteam  Alright, if I have a compiled distribution folder (only html, js (client-side), css, etc.) I can put in resources and I'll have under some path ready on start ?

**Comment by arteam** [comment]
Yes, you need to use `AssetsBundle` to configure that. Take at a looks at the `Serving assets` [part](http://www.dropwizard.io/1.0.6/docs/manual/core.html#serving-assets) of the docs.

**Comment by joschi** [comment]
I'm closing this issue as this topic is better discussed on the mailing list: https://groups.google.com/forum/#!forum/dropwizard-user
