### ISSUE TITLE
Restrict access to specified IP addresses

### ISSUE THREAD

**Issue by zheng-wang** [dropwizard/dropwizard#1966]
Is there any way in Dropwizard (I'm using 0.9.3) to restrict access to specified IP addresses? 

The bindHost parameter in configuration yml can only bind one IP address available on the machine where Dropwizard application runs, so can not satisfy my requirement. I want to specify any IP addresses, no matter local or remote.

Jetty can satisfy my requirement as can be seen [here](http://www.eclipse.org/jetty/documentation/current/ipaccess-handler.html). But I can't find an API in Dropwizard that allows me to add the IPAccessHandler.

**Comment by arteam** [comment]
It's possible, but quite boilerplate. Dropwizard is designed to be extended with servlets and filters, but not Jetty handlers. You need to declare a custom server factory:
```java
@JsonTypeName("ip-address")
public class IpAddressServerFactory extends DefaultServerFactory {

    @Override
    public Server build(Environment environment) {
        Server server = super.build(environment);
        InetAccessHandler inetAccessHandler = new InetAccessHandler();
        // Configure patterns from YML
        
        inetAccessHandler.setHandler(server.getHandler());
        server.setHandler(inetAccessHandler);
        return server;
    }
}
```

Then, register it as a SPI by creating a file with the name `io.dropwizard.server.ServerFactory` in your resources under the path `META-INF/services/` and write the full class name of the new factory (`com.example.helloworld.IpAddressServerFactory`) to it.

Then in our YAML config you can instruct Dropwizard to use this server factory by specifying the type `ip-access` type.
```yaml
server:
  type: ip-address
```

**Comment by zheng-wang** [comment]
Cool, thanks for such a detailed answer. I'll try it out.
