### ISSUE TITLE
Chinese characters garbled, where can you set up?

### ISSUE THREAD

**Issue by SandyJun** [dropwizard/dropwizard#1968]
@GET
    @Timed
    public Response test() {
            return Response.ok("返回中文汉字").build();
    }

Chinese characters garbled, where can you set up?

**Comment by SandyJun** [comment]
return Response.ok("返回中文汉字").header(HttpHeaders.CONTENT_TYPE,
                    MediaType.APPLICATION_JSON + ";charset=UTF-8").build();

This setting can be resolved, would like to know if there is a unified place can be set

**Comment by jplock** [comment]
This won't make it into 1.1.0, but I committed a CharsetFilter in https://github.com/dropwizard/dropwizard/pull/1948 that will add the UTF8 charset in the header.

**Comment by arteam** [comment]
Yes, that's a good advice. You can register a filter which will add the `charset` parameter to all your responses. Should be really simple to set up in your `Application.run()` method as 
```java
environment.jersey().register(CharsetUtf8Filter.class);
```

**Comment by SandyJun** [comment]
@jplock @arteam 
thank you very much
