### ISSUE TITLE
javax.el in jersey-bean-validation is older than the one in dropwizard-validation

### ISSUE THREAD

**Issue by vrolijken** [dropwizard/dropwizard#1974]
Which gives me warnings in my build when including dropwizard-jersey

**Comment by joschi** [comment]
@vrolijken Which version of Dropwizard are you using?

Just enforce using the version from `dropwizard-validation` and it should work. There's not much we can do about 3rd party libraries.

**Comment by vrolijken** [comment]
1.1.0, I'm busy crafting a pull request, did not expect feedback this fast ;-)
