### ISSUE TITLE
Consider making DropwizardSlf4jRequestLog.java public?

### ISSUE THREAD

**Issue by qinfchen** [dropwizard/dropwizard#1988]
We are doing some customizations on the top of the LogbackClassicRequestLogFactory class. Is it possible to make DropwizardSlf4jRequestLog public instead of package private?

**Comment by joschi** [comment]
@qinfchen Out of curiosity, what kind of customizations are necessary for your code?

**Comment by qinfchen** [comment]
We are extending LogbackClassicRequestLogFactory to have different types of request logs based on sensitivity level.

**Comment by qinfchen** [comment]
ping?
