### ISSUE TITLE
Request log async logging appender worker threads not stopped

### ISSUE THREAD

**Issue by reftel** [dropwizard/dropwizard#1994]
When a Dropwizard  is stopped, most async appender  worker threads are stopped, but it seems the request log one isn't. Consider the below test case. If the lines adding `server.requestLog.appenders: []` are included, the testcase passes. If the reqestLog appender list is kept at the default, it fails. Threads for ordinary appenders are terminated (the printouts from `test` show that they exist before shutdown), but the request log one isn't.

This would not be that much of a problem normally, but it gets in the way of writing testcases that use Elasticsearch's `ESIntegTestCase` together with a `DropwizardAppRule`, as `ESIntegTestCase` is rather picky on thread cleanup. 

```
import static org.assertj.core.api.Java6Assertions.assertThat;

import java.io.File;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.StandardOpenOption;
import java.util.Arrays;

import org.junit.AfterClass;
import org.junit.BeforeClass;
import org.junit.ClassRule;
import org.junit.Rule;
import org.junit.Test;
import org.junit.rules.TemporaryFolder;

import io.dropwizard.Application;
import io.dropwizard.Configuration;
import io.dropwizard.setup.Environment;
import io.dropwizard.testing.junit.DropwizardAppRule;

public class DropwizardThreadsIT {
    @ClassRule
    public static TemporaryFolder tmp = new TemporaryFolder();
    static File configFile;

    private static Thread[] beforeThreads;

    @BeforeClass
    public static void findThreads() throws IOException {
        beforeThreads = new Thread[Thread.activeCount()];
        Thread.enumerate(beforeThreads);
    }

    @BeforeClass
    public static void writeConfig() throws IOException {
        configFile = tmp.newFile();
        Files.write(configFile.toPath(), ("server:\n"
            + " applicationConnectors:\n"
            + " - type: http\n"
            + "   port: 0\n"
            + " adminConnectors:\n"
            + " - type: http\n"
            + "   port: 0\n"
//            + " requestLog:\n"
//            + "  appenders: []"
        ).getBytes(), StandardOpenOption.TRUNCATE_EXISTING);
    }

    @Rule
    public DropwizardAppRule<Configuration> app = new DropwizardAppRule<Configuration>(
        MyApp.class, configFile.getAbsolutePath()
    );

    public static class MyApp extends Application<Configuration> {
        public MyApp() {}

        @Override
        public void run(
            Configuration configuration, Environment environment
        ) throws Exception {}
    }

    @Test
    public void test() {
        Thread[] threads = new Thread[Thread.activeCount()];
        Thread.enumerate(threads);
        Arrays.asList(threads).forEach(System.out::println);
    }

    @AfterClass
    public static void checkThreads() {
        Thread[] threadsAfter = new Thread[Thread.activeCount()];
        Thread.enumerate(threadsAfter);
        assertThat(beforeThreads).contains(threadsAfter);
    }
}

```

**Comment by nickbabcock** [comment]
I just wanted to chime in and say that I can reproduce this and the behavior is a bug. I'm not sure what the fix should be. One possible solution is to combine request logging and regular logging (relevant issue #1731), so that when logging is stopped, request logging is also stopped.

Thanks for the report and the test case.

**Comment by yoavsreb98p6** [comment]
We are using async appenders too. It seems that in 1.2.0 those appenders are not closed as part of the `DefaultLoggerFactory.stop` method as they used to before, but instead the async appenders just being *flushed*. This means that command like db that don't set a shutdown hook, don't have a way to stop the async appenders. 
I am able to mitigate this by explicitly calling `LoggingUtils.LoggerContext.stop()` in case of DB commands.

**Comment by reftel** [comment]
This is still an issue as of version 1.3.14 and 2.0.0-rc5.

**Comment by reftel** [comment]
This is still an issue as of version 1.3.16 and 2.0.0-rc12.

**Comment by reftel** [comment]
This is still an issue as of version 1.3.18 and 2.0.1

**Comment by oeddyo** [comment]
also seeing this.
    LoggingUtil.getLoggerContext().stop();
 doesn't seem to help

1 thread leaked from SUITE scope at com.kalasearch.restful.SimpleRestfulTest: 
   1) Thread[id=19, name=AsyncAppender-Worker-async-console-appender, state=WAITING, group=TGRP-SimpleRestfulTest]
        at java.base@11.0.5/jdk.internal.misc.Unsafe.park(Native Method)
        at java.base@11.0.5/java.util.concurrent.locks.LockSupport.park(LockSupport.java:194)
        at java.base@11.0.5/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2081)
        at java.base@11.0.5/java.util.concurrent.ArrayBlockingQueue.take(ArrayBlockingQueue.java:417)
        at app//ch.qos.logback.core.AsyncAppenderBase$Worker.run(AsyncAppenderBase.java:289)


Note this should happen anywhere ES is integrated since ES is using Lucene's unit-testing framework which try to detect leaked threads. 

Can we re-open this please?

**Comment by joschi** [comment]
@oeddyo Could you please provide an example project to reproduce the issue?
