### ISSUE TITLE
`git fsck` fails

### ISSUE THREAD

**Issue by JensRantil** [dropwizard/dropwizard#1996]
Dropwizard has a broken commit:

```bash
$ git clone https://github.com/dropwizard/dropwizard.git
Cloning into 'dropwizard'...
remote: Counting objects: 123311, done.
remote: Compressing objects: 100% (24/24), done.
remote: Total 123311 (delta 1), reused 0 (delta 0), pack-reused 123280
Receiving objects: 100% (123311/123311), 46.11 MiB | 1.71 MiB/s, done.
Resolving deltas: 100% (78597/78597), done.
$ cd dropwizard
$ git fsck
Checking object directories: 100% (256/256), done.
error in commit 6fbf9def0293986beb2547a671f46148a5d2faf7: badDate: invalid author/committer line - bad date
Checking objects: 100% (123311/123311), done.
```

The problem is that the commit has an uncorrect author field:
```
$ git show --format=raw 6fbf9def0293986beb2547a671f46148a5d2faf7
commit 6fbf9def0293986beb2547a671f46148a5d2faf7
tree a452806b01d6ebd7d28cc3c85451ae1485f07257
parent 662010f5206fbe3d5390760501a8f48ffa9602ac
parent 2b2c23d52f348a16d9644acd08339992dfeca011
author Coda Hale <coda.hale@gmail.com> <coda.hale@gmail.com> 1305038239 -0700
committer Coda Hale <coda.hale@gmail.com> <coda.hale@gmail.com> 1305038239 -0700

    Merge pull request #3 from tommorris/patch-1

    added link to example application repository from README

```

Expected is:
```
...
author Coda Hale <coda.hale@gmail.com> 1305038239 -0700
committer Coda Hale <coda.hale@gmail.com> 1305038239 -0700
...
```

I discovered this because I have the following sections in my `.gitconfig` to make sure that my checkouts are correct:
```ini
[transfer]
        fsckobjects = true
[fetch]
        fsckobjects = true
[receive]
        fsckObjects = true
```

**Comment by joschi** [comment]
See #1995.

I'm not sure how to fix that without basically changing every following commit SHA-1 and thus tags and all.

@dropwizard/committers Any suggestions?

**Comment by ryankennedy** [comment]
Let me ping support@github.com to see if they have any suggestions/remediations short of disabling fsckobjects.

**Comment by ryankennedy** [comment]
Sent the following:

> We're not sure if this is related to the deletion but users with fsckobjects turned on are noticing problems cloning the repo (https://github.com/dropwizard/dropwizard/issues/1996). The problem is occurring with an old commit (from 2011). It's unclear if this is a new problem or if it's simply that news of the accidental deletion is causing more people to re-engage with the project and are now cloning the repo with fsckobjects enabled when it may have previously been disabled for them.

@JensRantil, had you successfully cloned the repo in the past with fsckobjects enabled? Is it possible this is the first time you've cloned with it turned on?

**Comment by JensRantil** [comment]
> had you successfully cloned the repo in the past with fsckobjects enabled?

No.

> Is it possible this is the first time you've cloned with it turned on?

This is the first time I clone it, I think.

**Comment by ryankennedy** [comment]
Okay, that makes me feel slightly better, then. I'm guessing it's unrelated to the repo deletion and has probably been around for a while. I guess we know what most contributors have fsckobjects set to. 😐

Having no real experience repairing git repos, I have no immediate suggestions for fixing. I'll wait a little longer to see it GH support responds with any recommendations.

**Comment by ryankennedy** [comment]
GitHub support confirmed that this has been around a while:

> As you suspected, this issue is popping up because some new cloners who have fsckobjects enabled are noticing it. There is a malformed commit in the history, and unless you want to rewrite the history (unlikely), the only solution is for the cloners to disable fsckObjects.
>
>To be clear, that malformed commit was already there, it wasn't introduced when the repo was restored.
>
>In case you're curious, there's an extra email address in the author and committer info:
>
>$ git cat-file commit 6fbf9def0293986beb2547a671f46148a5d2faf7 | egrep '^(author|committer)'
author Coda Hale <coda.hale@gmail.com> <coda.hale@gmail.com> 1305038239 -0700
committer Coda Hale <coda.hale@gmail.com> <coda.hale@gmail.com> 1305038239 -0700
Let us know if you have any other questions.

I think rewriting history is going to be dicey at best, so I'm going to close this and we'll just have to remember to let folks know.
