### ISSUE TITLE
Jetty refusing to start - Min and max threads to use for requests configuration

### ISSUE THREAD

**Issue by zloster** [dropwizard/dropwizard#1997]
According to [the docs](http://www.dropwizard.io/1.1.0/docs/manual/configuration.html#all) and [the source](https://github.com/dropwizard/dropwizard/blob/master/dropwizard-core/src/main/java/io/dropwizard/server/AbstractServerFactory.java#L218-L222) one should be able to configure the `minThreads` to 1 and `maxThreads` to 2. But using this exact configuration `Jetty` will refuse to start with the following message:

```
INFO  [2017-04-08 16:55:02,043] org.eclipse.jetty.server.Server: jetty-9.4.z-SNAPSHOT
ERROR [2017-04-08 16:55:02,124] io.dropwizard.cli.ServerCommand: Unable to start server, shutting down
! java.lang.IllegalStateException: Insufficient threads: max=2 < needed(acceptors=1 + selectors=2 + request=1)
! at org.eclipse.jetty.server.Server.doStart(Server.java:414)
! at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
! at io.dropwizard.cli.ServerCommand.run(ServerCommand.java:53)
! at io.dropwizard.cli.EnvironmentCommand.run(EnvironmentCommand.java:44)
! at io.dropwizard.cli.ConfiguredCommand.run(ConfiguredCommand.java:85)
! at io.dropwizard.cli.Cli.run(Cli.java:74)
! at io.dropwizard.Application.run(Application.java:89)
! at com.example.helloworld.HelloWorldService.main(HelloWorldService.java:31)
Insufficient threads: max=2 < needed(acceptors=1 + selectors=2 + request=1)
```

It seems that the HTTP connectors thread count configuration are connected with the `maxThreads` parameter. Jetty is adding the number of `acceptor` and `selector` threads and then calculates the acceptable minimum. This is the place where the [exception is thrown](https://github.com/eclipse/jetty.project/blob/4a674b9cc96de3e28d4fddf9abb8e7d1a456db96/jetty-server/src/main/java/org/eclipse/jetty/server/Server.java#L414).

Update 2:
In [this branch](https://github.com/dropwizard/dropwizard/compare/master...zloster:jetty-threads-config) I've added a simple test to illustrate the problem. The build in `dropwizard-core` will fail with:

```
Running io.dropwizard.server.ThreadConfigTest
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.182 sec <<< FAILURE! - in io.dropwizard.server.ThreadConfigTest
testBuild(io.dropwizard.server.ThreadConfigTest)  Time elapsed: 0.166 sec  <<< ERROR!
java.lang.IllegalStateException: Insufficient threads: max=2 < needed(acceptors=1 + selectors=2 + request=1)
        at io.dropwizard.server.ThreadConfigTest.testBuild(ThreadConfigTest.java:59)
```

Update: tested with Dropwizard 1.1.0 and Dropwizard 1.0.3

**Comment by evnm** [comment]
I'm not sure what we can do about this. I don't see it as a bug, but as an instance of misconfiguration. It's debatable whether it's Dropwizard's responsibility to guard against this, since Jetty already does so.

One option to preemptively prevent the failure would be to override the thread pool in `DefaultServerFactory` if we infer that the configured application connectors will impose a number of acceptor and selector threads that exceeds the user-configured `maxThreads`. But then we'd be lying to users in saying that they have full control over their server's thread count.

Otherwise, any further validation of `maxThreads` would have the same effect that you've observed—the server would fail at runtime with a configuration error.

Maybe we can present a more actionable error message than that emitted by Jetty. Or barring that, mention the case in the user manual with remediation steps. What do you think?

**Comment by zloster** [comment]
> I'm not sure what we can do about this. I don't see it as a bug, but as an instance of misconfiguration. It's debatable whether it's Dropwizard's responsibility to guard against this, since Jetty already does so.

I agree that it could be viewed as more of misconfiguration than a bug. The documentation definitely needs improvement in this area. Also a guard against this at validation level will require replication of the Jetty's calculation of the default number of acceptor and selectors threads or changes in Jetty to expose the result of it calculated defaults. The configuration is in at least 2 objects (the server config and the connectors configuration) if only HTTP connector is configured which complicates the validation logic. IMO too much work for insignificant gain.

> One option to preemptively prevent the failure would be to override the thread pool in DefaultServerFactory if we infer that the configured application connectors will impose a number of acceptor and selector threads that exceeds the user-configured maxThreads. But then we'd be lying to users in saying that they have full control over their server's thread count.
> 
> Otherwise, any further validation of maxThreads would have the same effect that you've observed—the server would fail at runtime with a configuration error.

Indeed this doesn't look like as a solution.

> Maybe we can present a more actionable error message than that emitted by Jetty. Or barring that, mention the case in the user manual with remediation steps. What do you think?

Please don't forget that I'm not familiar with Jetty's internals and many people will be in the same situation when reading the docs. Maybe adding one or two paragraphs with the following information. Feel free to correct me if I've mistaken something:

- Jetty (at least 9.3.x - 9.4.x family) is using a shared thread pool - [Jetty's manual](http://www.eclipse.org/jetty/documentation/current/architecture.html#basic-architecture) This includes the threads that will be processing the requests.
- Each connector (HTTP, HTTPS) consumes additional threads from the above thread pool. The defaults are max 4 threads if the CPU have many cores, less in the other cases. The formulas are already described in the HTTP connector documentation.
- minThreads and maxThreads configuration is **not** only for the request processing threads (because of the shared thread pool), so this should be clarified in the documentation.
- Jetty will throw `java.lang.IllegalStateException: Insufficient threads:xxx` in case of too aggressive limit on the thread counts.
- (This is the most unclear to me) Separate `admin` context for an application. Will it be using separate thread pool?

**Comment by evnm** [comment]
Would you be interested in taking a stab at adding some of this information to the user manual? I think it may suffice simply to flesh out the `maxThreads` documentation in [the configuration section](https://github.com/dropwizard/dropwizard/blob/master/docs/source/manual/configuration.rst).
