### ISSUE TITLE
Using @Valid annotation on resource methods that follow bean naming conventions causes unexpected behavior

### ISSUE THREAD

**Issue by scottaj** [dropwizard/dropwizard#2008]
Example project demonstrating bug [here](https://github.com/campspot/dropwizard-resource-validation-bug)

Basically, it you put the `@Valid` annotation on a resource method that follows bean naming conventions (starts with `get` and has no arguments) it will always run that resource method code whenever you call **any** other resource method in that class. If you call the problematic method it will run twice.

Here is a resource definition from the above sample project:

```Java
@Produces(MediaType.APPLICATION_JSON)
@Consumes(MediaType.APPLICATION_JSON)
@Path("/validated")
public class ValidatedResource {
    private final Logger logger = LoggerFactory.getLogger(ValidatedResource.class);

    @GET
    @Path("/foo")
    @Valid
    public Foo getFoo() {
        logger.info("######################### GET FOO");
        return new Foo("bloop");
    }

    @GET
    @Path("/bar")
    public Bar getBar() {
        logger.info("######################### GET BAR");
        return new Bar(27);
    }
}
```

If you do a `curl localhost:8080/validated/foo` and look at the logs from the Java server, you will see: 
```
INFO  [2017-04-12 22:13:59,083] com.campspot.resources.ValidatedResource: ######################### GET FOO
INFO  [2017-04-12 22:13:59,086] com.campspot.resources.ValidatedResource: ######################### GET FOO
0:0:0:0:0:0:0:1 - - [12/Apr/2017:22:13:59 +0000] "GET /validated/foo HTTP/1.1" 200 16 "-" "curl/7.51.0" 64
```

And if you do `curl localhost:8080/validated/bar` you will see:

```
INFO  [2017-04-12 22:14:02,676] com.campspot.resources.ValidatedResource: ######################### GET FOO
INFO  [2017-04-12 22:14:02,677] com.campspot.resources.ValidatedResource: ######################### GET BAR
0:0:0:0:0:0:0:1 - - [12/Apr/2017:22:14:02 +0000] "GET /validated/bar HTTP/1.1" 200 13 "-" "curl/7.51.0" 9
```

This seems like undesirable behavior. 

As a workaround, you can do any of the following:
 - rename `getFoo` to a non bean name e.g. `fetchFoo`
 - Remove the `@Valid` annotation
 - Add an argument to the `getFoo` method (like a query param)

**Comment by nickbabcock** [comment]
Wow, I'm shocked, yet at the same time, not surprised 😄 

I can take a peek at the validation code, but I can't think of what's needed to be fixed. We may have to file a request with the upstream Hibernate validator project, and document the conditions and the workarounds you mentioned. Thank you for the detailed report!

**Comment by scottaj** [comment]
Bummer, I'm not really surprised those bean naming assumptions are baked in there though.

We added the following test (using the reflections library) to our app to stop ourselves from footgunning this. It is pretty basic and doesn't check for the argument count portion of bean naming, but it might be useful for others in the future:

```java
package campspot.resources.v2;

import campspot.CampspotTest;
import com.google.common.collect.ImmutableSet;
import org.junit.Test;
import org.reflections.Reflections;
import org.reflections.scanners.MethodAnnotationsScanner;
import org.reflections.util.ClasspathHelper;
import org.reflections.util.ConfigurationBuilder;
import org.reflections.util.FilterBuilder;

import javax.ws.rs.DELETE;
import javax.ws.rs.GET;
import javax.ws.rs.POST;
import javax.ws.rs.PUT;
import java.lang.reflect.Method;

import static org.assertj.core.api.Assertions.assertThat;

public class ResourceBeanValidationBugTest extends CampspotTest {
  @Test
  public void resourceMethodsAreNotBeanMethods() {
    ConfigurationBuilder configuration = new ConfigurationBuilder()
      .setUrls(ClasspathHelper.forPackage("campspot.resources.v2"))
      .setScanners(new MethodAnnotationsScanner())
      .filterInputsBy(new FilterBuilder().includePackage("campspot.resources.v2"));

    Reflections reflections = new Reflections(configuration);

    ImmutableSet<Method> resourceMethods = ImmutableSet.<Method>builder()
      .addAll(reflections.getMethodsAnnotatedWith(GET.class))
      .addAll(reflections.getMethodsAnnotatedWith(POST.class))
      .addAll(reflections.getMethodsAnnotatedWith(PUT.class))
      .addAll(reflections.getMethodsAnnotatedWith(DELETE.class))
      .build();

    assertThat(resourceMethods.size()).as("No resource methods found, are you sure you entered the right package?").isGreaterThan(0);

    for (Method method : resourceMethods) {
      String errorMessage = String.format("Method %s in class %s should not start with 'get' or 'set'. Use 'fetch' and 'apply' instead. See https://github.com/dropwizard/dropwizard/issues/2008 for details.", method.getName(), method.getDeclaringClass().getName());
      boolean hasBeanName = method.getName().startsWith("get") || method.getName().startsWith("set");

      assertThat(hasBeanName).as(errorMessage).isFalse();
    }
  }
}
```

**Comment by nickbabcock** [comment]
@scottaj that's an interesting workaround and is probably worth having in the main code to prevent the user from shooting themselves in the foot. The only things worth changing for our use case would be to detect any `javax.ws.rs` annotation (and those on implemented interface) and IIRC we use `classmate` instead of `org.Reflections`
