### ISSUE TITLE
java.lang.UnsupportedClassVersionError: io/dropwizard/testing/junit/ResourceTestRule : Unsupported major.minor version 52.0

### ISSUE THREAD

**Issue by snehaldkshah** [dropwizard/dropwizard#2012]
**ISSUE 1 : 
**When I run the project using intellij Idea :**** 
java.lang.UnsupportedClassVersionError: io/dropwizard/testing/junit/ResourceTestRule : Unsupported major.minor version 52.0

I need to run this with openjdk-7.  it works if I installed jdk 8.

I am on ubuntu 14.04 my java version is  java version "1.7.0_121"
OpenJDK Runtime Environment (IcedTea 2.6.8) (7u121-2.6.8-1ubuntu0.14.04.3)
OpenJDK 64-Bit Server VM (build 24.121-b00, mixed mode)

--------------------------------------------------------------------------------------------------------------------------------------
**ISSUE 2 : 
**When I run the test cases with Mvn test:****
Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.19.1:test (default-test) on project  Execution default-test of goal org.apache.maven.plugins:maven-surefire-plugin:2.19.1:test failed: The forked VM terminated without properly saying goodbye. VM crash or System.exit called?
[ERROR] Command was /bin/sh -c cd /{project location} && "${}/bin/javac" -jar /{project location}/target/surefire/surefirebooter6114235873568686676.jar
/{project location}/target/surefire/surefire968074016071936762tmp 
/{project location}/target/surefire/surefire_08111057350409621610tmp

**Comment by arteam** [comment]
Dropwizard 1.0 and higher works only with JDK 1.8. If you have a hard requirement for Java 1.7, you can try to use Dropwizard 0.9.*.

**Comment by snehaldkshah** [comment]
Let me try it. thanks.
