### ISSUE TITLE
Make ThreadNameFilter optional

### ISSUE THREAD

**Issue by markelliot** [dropwizard/dropwizard#2013]
I'd like to sometimes disable ThreadNameFilter because I don't want to share actual request information outside of request logs, and I would like to, generally, include thread name in my service logs.

I'm happy to make a PR to add an option to disable the ThreadNameFilter in AbstractServerFactory, if this seems acceptable.

**Comment by janolaveide** [comment]
+1 on this one

**Comment by arteam** [comment]
I think it's a reasonable idea to give Dropwizard users to control over it. This filter is useful for debugging, but I can see why users may not want to use it because security reasons. I will accept a pull request for adding a switch to control this behavior.

**Comment by CodingFabian** [comment]
![screen shot 2017-05-08 at 15 14 27](https://cloud.githubusercontent.com/assets/176132/25805739/0ebaf348-3401-11e7-87a5-aca4272b8280.png)
I came across this as well during profiling. setName() is quite expensive. Depending on the timeline of 1.2, would it be possible to cherry pick this to 1.1? The change itself is quite straightforward.

**Comment by arteam** [comment]
Yes, that's possible. I will do a cherry pick today.

**Comment by CodingFabian** [comment]
@arteam is there any roadblock with backporting this to 1.1? happy to help.

**Comment by arteam** [comment]
Sorry, I thought I had already done that. Cherry-picked as 5f85ffab2f09e6ff43f88f8763ecbef147e2754e

**Comment by CodingFabian** [comment]
thank you!

**Comment by arteam** [comment]
I have released Dropwizard 1.1.1 to the Maven central repository.
