### ISSUE TITLE
Dropwizard ignoring  JsonProperty for the class used as HTTP POST METHOD parameter from <dependency>

### ISSUE THREAD

**Issue by snehaldkshah** [dropwizard/dropwizard#2015]
Example :
Any maven repository contains the class **resiterPara.java** with this following property. 
**resiterPara.java**
@JsonProperty("first_name")
 private String firstName;

In Drop wizard I have class with following structure: (POST METHOD TO REGISTER ENDPOINT)
@POST
    @Path("/register")
    @Produces(MediaType.APPLICATION_JSON)
    public Response register(**resiterPara** params) throws IOException {
        return exec.registerSite(params);
    }

**_Its gives me error while I am passing Json with the same name as JsonProperty contains_** 
{
  "first_name": "test"  
}

**_Its works fine with actual property name_:**
{
  "firstName": "test"  
}

**Why it is not working with JsonProperty?**

**Comment by nickbabcock** [comment]
Please check that your entities are properly annotated. This is just one example

```java
public class SnakeRepresentation {
    private String myName;

    @JsonProperty("my_name")
    public String getMyName() {
        return myName;
    }

    @JsonProperty("my_name")
    public void setMyName(String myName) {
        this.myName = myName;
    }
}
```

Also please use the [mailing list](https://groups.google.com/forum/#!forum/dropwizard-user) for these types of questions. We prefer to keep the issue tracker only for bugs/features related to dropwizard 😄

**Comment by snehaldkshah** [comment]
Hello NickBabcock,
My entities are properly annotated.
