### ISSUE TITLE
noob experience

### ISSUE THREAD

**Issue by flip111** [dropwizard/dropwizard#2020]
I thought it might be nice to read about the experience of a java noob diving into the dropwizard documentation.

* http://www.dropwizard.io/1.1.0/docs/getting-started.html#creating-a-configuration-class What is the purpose of this configuration class? With methods of setDefaultName it looks like a model to me, isn't this stuff suppose to go into entities?
* `When this class is deserialized from the YAML file` which yaml file? Why is it deserialized? Why are we now talking about yaml when the configuration file itself is litered with JsonProperty annotations?

in IRC dreamreal (Joseph Ottinger. Used to be the editor of Java Developer Journal and then TheServerSide.com) has to say the following about it

```
<flip111> what's the purpose of this Configuration class?  http://www.dropwizard.io/1.1.0/docs/getting-started.html#creating-a-configuration-class   i see in the example methods like setDefaultName .. seems more like a model to me ..
<dreamreal> it's a model for the *application*
<flip111> don't really want to model my application at this moment
<flip111> it also says  "When this class is deserialized from the YAML file, "  which YAML file ?
<dreamreal> you're going to write a YAML file.
<dreamreal> Well, default name is for the app to spit out by default. So that's your "application model."
<dreamreal> Like if your app is to say "Hello, world" where "world" is paramaterized, "world" is the "default name."
<flip111> spit out where ?
<dreamreal> I don't know what the tutorial does - but given dropwizrd, I'm assuming it's going to start a webapp where you hit http://localhost/something
<dreamreal> and yes, it'll be http://localhost:port/hello-world
<dreamreal> and yes, it'll be http://localhost:8081/hello-world based on the rest of the configuration
<flip111> ok that's not so obvious yet ..
<flip111> i'll make notes
<dreamreal> It is a tutorial that actually progresses as it goes along. I don't understand tutorial writers who do that, though.
<dreamreal> I mean, why don't they SAY "this is what we're working toward" at the very beginning?
<dreamreal> "Getting Started will guide you through the process of creating a simple Dropwizard Project: Hello World." ... no "We're going to say 'hello world' through an HTTP endpoint, allowing us to change defaults through configuration and using a data representation model that we can change to fit our needs..."
<dreamreal> that way, the "configuration" makes more sense and you know you're going to be creating something on the web...
```

* Loading templates and default values from YML seems not really necessary to get going, would be better if this was more obvious in the code itself. Later i would not put my html templates in yaml files anyway so i don't understand this choice for the tutorial.

-- edit and add more later maybe

**Comment by joschi** [comment]
@flip111 Thanks for your feedback!

> * http://www.dropwizard.io/1.1.0/docs/getting-started.html#creating-a-configuration-class What is the purpose of this configuration class? With methods of setDefaultName it looks like a model to me, isn't this stuff suppose to go into entities?
> * `When this class is deserialized from the YAML file` which yaml file? Why is it deserialized? Why are we now talking about yaml when the configuration file itself is litered with JsonProperty annotations?

I think these questions are answered in the very first paragraph of that section:

> Each Dropwizard application has its own subclass of the `Configuration` class which specifies environment-specific parameters. These parameters are specified in a YAML configuration file which is deserialized to an instance of your application’s configuration class and validated.

**Comment by flip111** [comment]
@joschi it's not clear what is meant here with "environment" and why methods like setDefaultName should go there. I mean "specifying environment variables" is a mean to what ends?

**Comment by stefan-kolb** [comment]
Why do we need such a configuration anyway? Think about a simple REST API that just returns stuff from JAX-RS resource classes. For me it is unclear why I want to pass default values through a configuration class? A minimal example should work without such a configuration class?!

**Comment by nickbabcock** [comment]
If every time you start your app, a field will always have the same value, then you are correct that you can do away with the configuration aspect of that field, and leave it hardcoded in the project.

It's only when you expect this field to take on different values on start up (think of accessing a DB on localhost vs a remote host) that it is helpful. The default value of the field could be "localhost" so that when the DB is deployed on localhost one can omit: `db_location: localhost` in their yaml file. Yet when the DB is moved to a different box, instead of having to recompile the application with the new location (if we had hardcoded it), one can just add `db_location: <ip>` to the configuration to override the default.

**Comment by nickbabcock** [comment]
Closing this as the original question appears answered. If not, and this is an issue with the Dropwizard project, let me know and I can re-open the issue.
