### ISSUE TITLE
Database and template property is compulsory in yaml file and the configurations 

### ISSUE THREAD

**Issue by snehaldkshah** [dropwizard/dropwizard#2029]
Error:

io.dropwizard.configuration.ConfigurationValidationException: config.yml has the following errors:
  * database.driverClass may not be null
  * database.url may not be null
  * template may not be empty

I don't want to keep template, defaultName, database properties. what should I do? It is compolsory to keep it in yaml and set getter and setter in configuration file?

Instead of this properties I want to configure my custom properties..

**Comment by arteam** [comment]
If you don't have a database or template section in your application configuration, Dropwizard should not require it in the YAML config. Could you post your configuration class?

**Comment by nickbabcock** [comment]
Closing this as the original question appears answered. If not, and this is an issue with the Dropwizard project, let me know and the issue can be re-opened.
