### ISSUE TITLE
Command line input along with server

### ISSUE THREAD

**Issue by itachi3** [dropwizard/dropwizard#2036]
Is it possible to accept more command line argument along with "server" command. 

Eg: java -jar {path_to_jar} server config.yml addtional_arg_name addtional_arg_value

**Comment by arteam** [comment]
You can extend `ServerCommand` and parse arguments in the `run` method. You may also consider to use system properties.

**Comment by nickbabcock** [comment]
Closing this as the question appears answered. If not, please respond to re-open.
