### ISSUE TITLE
HTML error responses

### ISSUE THREAD

**Issue by BenScholl** [dropwizard/dropwizard#2038]
It would be nice to have proper support for HTML error responses (and other non-JSON content types too). Writing your own `ExceptionMapper` gets most of the way but is a bit ugly, and it doesn't seem to work at all for `AbstractParam` validation.

I've put together a tentative solution consisting of an `ErrorResponseProvider` interface that can be hooked up to your app's error views.

```java
public interface ErrorResponseProvider {

    Response getResponse(ErrorMessage errorMessage);

    Response getValidationResponse(ValidationErrorMessage errors);

    boolean isAcceptable();
}

```

It works with `LoggingExceptionMapper` and `JerseyViolationExceptionMapper` and I've managed to integrate with `AbstractParam` too although that was a bit more tricky.

Here's an outline of the solution:
https://gist.github.com/BenScholl/95236ce186f05d0f5bdd46f1e5dc93ad

Any comments would be much appreciated.

Ben

**Comment by nickbabcock** [comment]
Hey, that's a good start! You're right that supporting arbitrary return types for errors has been a pain point. I'm open to improvement, as long as backwards compatibility is kept.

To get around the `AbstractParam` issue, it may prove prudent to define a custom exception and exception mapper and have `parse` wrap the thrown exception (and those that create their own abstract parameters and override the `error` method will need a migration path)

**Comment by BenScholl** [comment]
Thanks for the encouragement!

I don't really understand why `AbstractParam` puts a `Response` in the exceptions it raises. This stops them from getting mapped, as `ServerRuntime.Responder.mapException` doesn't map exceptions that have an entity attached.

If instead `AbstractParam` just wrapped up the error text in the `WebApplicationException`, then `LoggingExceptionMapper` would be able to handle these exceptions and create the proper response itself.

Nice simple solution ... or am I missing something?

**Comment by nickbabcock** [comment]
Thinking about it a little longer, I think if one provided a `MessageBodyWriter` that produces html for `ValidationErrorMessage`, `ErrorMessage`, etc, that would get one pretty far and `ErrorResponseProvider` wouldn't be needed.

I don't remember how Jersey determines the content type if it is not specified in the builder 🤔

**Comment by BenScholl** [comment]
Good point - that would be a much less intrusive approach.

Here's a `ViewEntityMessageBodyWriter` (suggestions for better names welcome...)
https://gist.github.com/BenScholl/e8568e59078565337f90a2e4d709d489

You just register separate instances to handle `ErrorMessage` and `ValidationErrorMessage` and it intercepts the appropriate responses. No need to mess about with `AbstractParam` and exception mappers.

I imagine most people using views would want this. Is it worth me putting together a pull request for dropwizard-views?

**Comment by nickbabcock** [comment]
Yeah if you want to prove it out with dropwizard-views that would be a good start! I can imagine people who are not using dropwizard-views interested as well.
