### ISSUE TITLE
Run dropwizard application after creating package with debian.

### ISSUE THREAD

**Issue by snehaldkshah** [dropwizard/dropwizard#2040]
Jenkins build create a single jar file, How can I run this app after that?

**java -jar test.jar  server config.yml** 
This above command is not going to work. because once Jenkins builds it its only offer single .jar file.

Do we need to ship .yml file and keystrore file with .jar file? Is there any alternative for this?

It that possible if can directly run with 
**java -jar test.jar**

**Comment by isaki-x** [comment]
You need to ship the jar and its dependencies (unless you are using a shaded/uber artifact, then you only need the single artifact) as well as any external resources. In this case, config.yml would be an external resource. You could hardcode the config path in your main as an alternative, but that makes testing really hard. If you want a simple start up, you could wrap your command in a simple executable with a default location for where you have deployed the config as pert of your deb install.

**Comment by nickbabcock** [comment]
Closing this as the original question appears answered. If not, and this is an issue with the Dropwizard project, let me know and the issue can be re-opened.
