### ISSUE TITLE
No error reported, but  "RuntimeExecutorsBinder$BackgroundSchedulerLiteral" message ends execution

### ISSUE THREAD

**Issue by dbaronster** [dropwizard/dropwizard#2044]
Hi,

Upgrading from DW 0.8.4 to 1.1.0-1, I followed the dropwizard/wiki/Upgrade-guides. On launch, all resources load cleanly and other startup activities log as expected, but the final three lines are:
```
INFO       [15:36:49.052] [main] o.e.j.s.AbstractConnector -  Started application@1178369d{HTTP/1.1,[http/1.1]}{0.0.0.0:8080} 
INFO       [15:36:49.053] [main] o.e.j.s.AbstractConnector -  Started admin@2313de2a{HTTP/1.1,[http/1.1]}{0.0.0.0:8081} 
org/glassfish/jersey/server/internal/RuntimeExecutorsBinder$BackgroundSchedulerLiteral
```
The app has terminated. What is this last line from jersey trying to tell me? Can I extract more detailed logging to find the error?
The end of the 8.4 startup log looked like this:

``` 
INFO       [16:17:22.442] [main] o.e.j.s.h.ContextHandler -  Started i.d.j.MutableServletContextHandler@4d527116{/,null,AVAILABLE} 
INFO       [16:17:22.452] [main] o.e.j.s.ServerConnector -  Started application@5e1f3c74{HTTP/1.1}{0.0.0.0:8080} 
INFO       [16:17:22.453] [main] o.e.j.s.ServerConnector -  Started admin@1e94fe1d{HTTP/1.1}{0.0.0.0:8081} 
INFO       [16:17:22.453] [main] o.e.j.s.Server -  Started @43754ms 
```

**Comment by t-tsutsumi** [comment]
@dbaronster Probably there is a problem with dependency definition. Please check whether an obsolete dependency (e.g. old Jersey) is defined in the pom.xml if using Maven.

**Comment by dbaronster** [comment]
With log level increased, I found that it was a ClassNotFound error on `RuntimeExecutorsBinder$BackgroundSchedulerLiteral`. Fixed by adding to pom:
```
<dependency>
  <groupId>io.dropwizard</groupId>
  <artifactId>dropwizard-jersey</artifactId>
  <version>1.1.0</version>
</dependency>
```

**Comment by dbaronster** [comment]
No, that was premature. I'm still getting `FAILED org.eclipse.jetty.server.Server@46147496: java.lang.NoClassDefFoundError: org/glassfish/jersey/server/internal/RuntimeExecutorsBinder$BackgroundSchedulerLiteral `

`pom.xml` has:

```
		<dependency>
			<groupId>io.dropwizard</groupId>
			<artifactId>dropwizard-jetty</artifactId>
			<version>1.1.0</version>
		</dependency>
		<dependency>
			<groupId>io.dropwizard</groupId>
			<artifactId>dropwizard-jersey</artifactId>
			<version>1.1.0</version>
		</dependency>
		<dependency>
			<groupId>org.glassfish.jersey.containers</groupId>
			<artifactId>jersey-container-jetty-servlet</artifactId>
			<version>2.25.1</version>
		</dependency>
		<dependency>
			<groupId>org.glassfish.jersey.media</groupId>
			<artifactId>jersey-media-multipart</artifactId>
			<version>2.25.1</version>
		</dependency>
```
I've tried removing dependencies to no avail.

**Comment by dbaronster** [comment]
Solution was here: https://github.com/smoketurner/dropwizard-swagger/issues/67
