### ISSUE TITLE
maven-shade-plugin has detected that some .class files are present in two or more JARs.

### ISSUE THREAD

**Issue by SimonsUnikaNamn** [dropwizard/dropwizard#2047]
Hi,

when running Dropwizard 1.1.0 without any other dependencies I get 

```
[WARNING] javax.el-2.2.4.jar, javax.el-3.0.0.jar define 74 overlappping classes:
[WARNING]   - com.sun.el.lang.ExpressionBuilder$NodeSoftReference
[WARNING]   - com.sun.el.parser.AstDiv
[WARNING]   - com.sun.el.parser.ELParserTokenManager
[WARNING]   - com.sun.el.parser.JJTELParserState
[WARNING]   - com.sun.el.MethodExpressionImpl
[WARNING]   - com.sun.el.parser.AstDotSuffix
[WARNING]   - com.sun.el.lang.FunctionMapperImpl$Function
[WARNING]   - com.sun.el.parser.AstChoice
[WARNING]   - com.sun.el.parser.AstOr
[WARNING]   - com.sun.el.parser.AstGreaterThan
[WARNING]   - 64 more...
[WARNING] javax.el-api-2.2.4.jar, javax.el-3.0.0.jar define 31 overlappping classes:
[WARNING]   - javax.el.ELException
[WARNING]   - javax.el.CompositeELResolver
[WARNING]   - javax.el.MethodInfo
[WARNING]   - javax.el.BeanELResolver$SoftConcurrentHashMap
[WARNING]   - javax.el.ELContext
[WARNING]   - javax.el.ELContextListener
[WARNING]   - javax.el.VariableMapper
[WARNING]   - javax.el.ValueReference
[WARNING]   - javax.el.CompositeELResolver$CompositeIterator
[WARNING]   - javax.el.ResourceBundleELResolver
[WARNING]   - 21 more...
[WARNING] maven-shade-plugin has detected that some .class files
[WARNING] are present in two or more JARs. When this happens, only
[WARNING] one single version of the class is copied in the uberjar.
[WARNING] Usually this is not harmful and you can skeep these
[WARNING] warnings, otherwise try to manually exclude artifacts
[WARNING] based on mvn dependency:tree -Ddetail=true and the above
[WARNING] output
[WARNING] See http://docs.codehaus.org/display/MAVENUSER/Shade+Plugin
```

when building the project.

regards

**Comment by t-tsutsumi** [comment]
I'd forgotten until seeing this PR, but It’s been on my mind for a while.

@jplock Are the following changes intended?
https://github.com/dropwizard/dropwizard/commit/18f8d48c7ce9dca4fb38f59a4ec411badde3667c#diff-caef1b6b9ef1c31a0d71011c4fcb8c27L396

**Comment by jplock** [comment]
Those warnings should be fine and yes those changes were intended as we started using the bom.

**Comment by t-tsutsumi** [comment]
@jplock Hmm, it seems to me that began using BOM is Jackson, not Jersey. Is this wrong?

**Comment by jplock** [comment]
we're using both BOM's now - https://github.com/dropwizard/dropwizard/blob/release/1.1.x/dropwizard-bom/pom.xml#L299 and https://github.com/dropwizard/dropwizard/blob/release/1.1.x/dropwizard-bom/pom.xml#L290

**Comment by t-tsutsumi** [comment]
Oh, I noticed that the above commit comment include `and simplify BOM`.  That means you did it together. Thanks a lot!

**Comment by SimonsUnikaNamn** [comment]
@jplock yeah things seems to be working but it is annoying to have those warnings in the build output, will this be fixed?

**Comment by arteam** [comment]
I think the issue should be fixed by #1976.  We will need to release a new 1.1, though.

**Comment by SimonsUnikaNamn** [comment]
Cool, thank you for an excellent framework :)

**Comment by nickbabcock** [comment]
Closing this as the question appears answered and fixed. If not, please respond to re-open.
