### ISSUE TITLE
@NotNull does not work with @Validated(Test.class) annotation

### ISSUE THREAD

**Issue by anujkumar04** [dropwizard/dropwizard#2049]
If I annotate a resource method param with @NotNull and @Valid and send a null entity, I correctly get a 400 back. If I annotate it with @NotNull and @Validated and send a null entity again it works. 
But If I annotate it with @NotNull and @Validated(TestValidated.class) and try to send a null entity, it does not do the null check.
Sample code:

```java
public class Person {
    @NotEmpty(groups = TestValidated.class)
    private String name;
    private String email;
}

public class HelloWorldApplication extends Application<HelloWorldConfiguration>{

 @Override
    public void run(HelloWorldConfiguration configuration,
            Environment environment) {
        environment.jersey().register(new HelloWorldResource());
        environment.jersey().register(new ValidationExceptionMapper());
        environment.jersey().enable(
                "jersey.config.beanValidation.enableOutputValidationErrorEntity.server");
    }

@Path("/hello")
@Produces(MediaType.APPLICATION_JSON)
public class HelloWorldResource {
    @POST
    public Person sayHello(@Validated @NotNull Person person) {
        String name = person.getName(); // get a NPE
        return new Person("test", "test@test.com");
    }
}
```

**Comment by nickbabcock** [comment]
All usages of `@Validated` must be accompanied by the corresponding `@Valid` annotation.

**Comment by anujkumar04** [comment]
issue still exist after adding @Valid 

```java
   @POST
    public Person sayHello(@Valid @Validated(TestValidated.class) @NotNull Person person) {
        String name = person.getName(); // get a NPE
        return new Person("test", "test@test.com");
    }
```

**Comment by nickbabcock** [comment]
Hmm, I can't seem to reproduce this, the validation works as expected.

Double check that the following line is needed (I'm not familiar with it)

```java
environment.jersey().enable(
                "jersey.config.beanValidation.enableOutputValidationErrorEntity.server");
```

Also what version of dropwizard?

**Comment by anujkumar04** [comment]
I commented that line but still have the same issue. I noticed that if I do not specify any group class it works, so
@Valid @Validated @NotNull : works
@Valid @Validated(TestValidated.class) @NotNull : does not work

```java
public interface TestValidated {
}
```

I am using:
```xml
  <dependencies>
    <dependency>
      <groupId>io.dropwizard</groupId>
      <artifactId>dropwizard-core</artifactId>
      <version>1.0.5</version>
    </dependency>
  </dependencies>
```

**Comment by nickbabcock** [comment]
- Does Dropwizard 1.1.x solve this issue (it shouldn't have an effect, but good to test)
- Can you modify [ValidatingResource.java](https://github.com/dropwizard/dropwizard/blob/master/dropwizard-jersey/src/test/java/io/dropwizard/jersey/validation/ValidatingResource.java) to produce a test case that fails?

**Comment by anujkumar04** [comment]
1.1.x does not solve this issue
