### ISSUE TITLE
Please add an example with foreign keys

### ISSUE THREAD

**Issue by shubh3794** [dropwizard/dropwizard#2050]
Hey.
I have been facing an issue in which I try to create an instance through POST api, the difference is that this instance has a foreign key, being a beginner in java, I'm finding it difficult to make a reference to that fk by passing it's id in Json request.

**Comment by nickbabcock** [comment]
Hello, this question may more appropriate for the [dropwizard-users group](https://groups.google.com/forum/#!forum/dropwizard-user). You may also [find this stackoverflow question](https://stackoverflow.com/questions/33295899/how-to-save-an-object-using-hibernate-as-persistence-with-a-foreign-key-using) useful.
