### ISSUE TITLE
JDBI: Extending DBI/DBIFactory

### ISSUE THREAD

**Issue by isaki-x** [dropwizard/dropwizard#2056]
Greetings,

I am experimenting with extending DBIFactory to inject custom argument and column mapper factories into a custom IDBI object (which currently extends DBI, but I could just as easily use a decorator pattern). I've run into two issues (and I only need to solve one of them).

1) DBIFactory returns DBI instead of IDBI
2) DBIFactory invokes the DBI constructor with no way to intercept and inject my own version.

I can create one or more of the following patches to address this:

**Change DBIFactory to return IDBI (Problem 1)**

This will break existing code for users of dropwizard-jdbi. As such, I don't really like this idea. Also, it would remove the visibility of the registration methods for column mappers and arguments, which isn't ideal. As a result, I think this idea is a non-starter. I put it out there as it could solve my issue in a non-optimal way.

**Allow custom DBI instance creation into DBIFactory (Problem 2)**

There are two ways we can do this. If we want to be traditional, we could set up a protected method (createDBI) that could be overridden by child classes and defaults to "new DBI()".

If we want to go with a more Java 8-esque approach, I could add a new constructor to DBIFactory that takes a Supplier<DBI> for generating new DBI instances. The current constructor would be updated to provide a default supplier. Then, the build method could just invoke "get" on the supplier to create new DBI instances and then operate on them as it currently does.

Please let me know your thoughts on this and I will create a patch and submit a pull request if any of this works for you. I'm open to alternatives as well; worst case I end up writing my own factory that decorates DBIFactory and returns my own IDBI implementation and updating the handful of places I reference DBIFactory to use my own object instead. I don't necessarily like this approach as I prefer to subclass DBI instead of decorating it.

Thank you!

**Comment by nickbabcock** [comment]
Related:

- We have [Jackson class](https://github.com/dropwizard/dropwizard/blob/c0d7379530df147c629b00798430bd73c8d7e7ab/dropwizard-jackson/src/main/java/io/dropwizard/jackson/Jackson.java) for configuring ObjectMapper
- We have [BaseValidator](https://github.com/dropwizard/dropwizard/blob/c0d7379530df147c629b00798430bd73c8d7e7ab/dropwizard-validation/src/main/java/io/dropwizard/validation/BaseValidator.java) and [Validators](https://github.com/dropwizard/dropwizard/blob/c0d7379530df147c629b00798430bd73c8d7e7ab/dropwizard-jersey/src/main/java/io/dropwizard/jersey/validation/Validators.java) for Hibernate Validator
- We don't seem to have anything configuring a DBI!

I only bring this up, as I always seem to forget to register the appropriate jdbi mappers, containers, etc in my test cases. 😥 

Maybe both of these problems can be solved with a `new` + `configure` mechanism like the Jackson class 🤔

**Comment by isaki-x** [comment]
You can do what you want already with a custom DBIFactory subclass; just override the build method to inject your stuff and return that. That's how I make sure my custom add-ons are the same for unit tests and production code.

My case is different; I want to actually have a custom DBI subclass that is returned by the factory so I can override several DBI methods to have custom functionality.

**Comment by nickbabcock** [comment]
If I understand you correctly, you should be able to create a factory that does not derive from `DBIFactory` and returns your custom DBI instance, no?

**Comment by isaki-x** [comment]
The issue there is I would lose all the nice setup DropWizard does; I would have to do it all myself (as in copy and paste DW code, and try to remember to keep it in sync; this is not ideal). I could of course decorate what is returned from DBIFactory in my custom factory to get my custom functionality. I prefer to subclass, hence why the two approaches I suggested are what I'm really looking for.

**Comment by nickbabcock** [comment]
> The issue there is I would lose all the nice setup DropWizard does

Yes, that is why I mentioned the `new` + `configure` mechanism, so that one doesn't need to sync anything for `DBI` instances.

**Comment by isaki-x** [comment]
I took a look at the Jackson class and a similar paradigm would not meet my needs as everything there is static and won't let me inject anything of my own. That being said, I think there is a way I can get us both what we want in DBIFactory (which is object method based and not static) by splitting the configuration out of the factory method and into a protected configure method; this would allow me override the build methods as I require and still invoke the DropWizard configuration on my subclass of DBI.

Would you find this approach agreeable?

**Comment by nickbabcock** [comment]
> I think there is a way I can get us both what we want

Perfect 😄

**Comment by arteam** [comment]
I like the approach with the protected method too.

Am 01.06.2017 17:42 schrieb "Nick Babcock" <notifications@github.com>:

**Comment by isaki-x** [comment]
@nickbabcock, Let's continue the discussion from #2067 regarding the `configure` method design here.

We have two goals which are relatively exclusive.

1. Allow simplistic configuration of argument factories by passing only the JDBC driver name.
2. Allow users to have custom configuration passed to their override of the configure method for added functionality.

How do we currently allow customization?

1. TimeZone data is created by an overridable method.
2. I opted to pass the PoolDataSourceFactory (which doubles as the config object) to configure for everything else as part of #2067.

I think we should unify the configuration/customization paradigms within this class (i.e. drop the time zone method altogether, but this will likely break code for anyone relying on being able to override that method). I don't your policy for introducing breaking changes with respect to version incrementation. But, this is a bit of a "cart before the horse" statement as I haven't pitched any of the ideas I've tried thus far.

Below you will find the two ideas I thought about and abandoned before deciding to let #2067 stand on its own and to move the discussion to a later time (now).

Let me know any thoughts/ideas you have.

**Abandoned Solution 1: Multiple Configure Methods**

We can create two configure methods, one with a `String` as the second parameter and one with the `PooledDataSourceFactory` second parameter.

Roughly, the code would work like this:

```Java
protected void configure(final DBI dbi, final PooledDataSourceFactory configuration) {
    this.configure(dbi, configuration.getDriverClass());
}

protected void configure(final DBI dbi, final String driverClazz) {
    // Configure body here
}
```

This approach has the issue of requiring a breaking change every time the configuration needs another piece of data as we would need to add parameters to the simple method. That, or we need to add more and more methods and add default values. This also doesn't lend itself to making TimeZone a function of a single configuration source.

**Abandoned Solution 2: Lambda**

This was the idea I floated in #2067; I abandoned it but I figured I'd share my reasoning here.

First, create a new interface.

```Java
@FunctionalInterface
public interface DBIArgumentConfig {
    String getDriverClass();
}
```

Then, have `PooledDataSourceFactory` implement this interface.

Finally, update DBIFactory to use this in the configure method:

```Java
protected void configure(final DBI dbi, final DBIArgumentConfig configuration) {
    // Code
}
```

Then, when you want to do something simple, you can do this:

```Java
// DBI created somewhere
final DBIFactory factory = new DBIFactory();
factory.configure(dbi, () -> "you.driver.class.Name");
```

While I appreciate the elegance of such a design, it suffers from the same problem as the first solution. We would break the ability to use this interface as a `@FunctionalInterface` if something else became required (such as time zone information).

**Comment by nickbabcock** [comment]
Oh no, I realized that I closed out of my browser too soon one day with a half finished reply. My apologies.

In brief, I had an idea of creating something akin to `dropwizard-testing-jdbi` where one would create a `TestDBIFactory` with sane defaults, eg:

```java
final DBI jdbi = new TestDBIFactory.builder()
    .driverClass(/* */)
    .timeZone(/* */)
    .newDbi();
```

With sane defaults, breaking changes would be small and if breaking changes are needed they should be ok as they are contained to a testing module

**Comment by isaki-x** [comment]
I want to let you know I haven't forgotten about this; I haven't had time to dig into it. I will try to get this soon.

**Comment by isaki-x** [comment]
So, if we were to go the route of created a test DBI factory (which by the way, I happen to like quite a bit) as you have suggested, I think the ideal place would be in the `dropwizard-testing` project. However, this currently only depends on `dropwizard-core` and I hesitate to force those using that project to pull in the dependencies required for `dropwizard-jdbi` for a feature they aren't currently using.

We could create a new project (`dropwizard-jdbi-testing`), but  that adds a bunch of a work for only one class.

The last option would be to place the test version into the source for `dropwizard-jdbi`.

Thoughts?

**Comment by isaki-x** [comment]
Unfortunately, I think there are going to be quite a few things required unless you want to just force the test version to H2 (which defeats the purpose of driverClass). What it seems like you are after is a builder pattern that hides the construction of `DataSourceFactory`. My local git repo has the `dropwizard-testing-jdbi` fully configured (BOM and dropwizard-parent are updated appropriately), but I'm not clear on the specific setup for the sane defaults you are looking for as well as exactly what functionality you are looking for (i.e. a JUnitRule, an extension to DBIFactory, a stand alone class to create DBI instances for testing, etc...).

Thanks!

**Comment by isaki-x** [comment]
Please let me know if you still want these changes; if not I'll close this issue. Thanks!

**Comment by nickbabcock** [comment]
It's a `DBI` that I'm after, not a `DataSourceFactory`

Take this use case:

- I have an application that uses a jdbi sql object with mappers, jdk8, and guava goodness
- An endpoint that inserts into the database
- A test that that calls said endpoint.

Currently I can test that the that the expected output from the endpoint is received but I would also like to query the actual db to make sure the correct data was persisted. This fails when the test tries to use any feature that is normally set by Dropwizard or the application. If only there was a way I could create a `DBI` that the application uses so I can test easier 😉

**Comment by isaki-x** [comment]
I think I understand now what you are going for. I've got some ideas to play with. I'll get back to you when I have some time to work on this. Thank you for the clarification!
