### ISSUE TITLE
Logging clears the current Thread's interrupted flag

### ISSUE THREAD

**Issue by dllx** [dropwizard/dropwizard#2058]
Consider the code
```java
Logger logger = LoggerFactory.getLogger("logger");
logger.info("msg1 {}-" + Thread.currentThread().isInterrupted(), Thread.currentThread().isInterrupted());
Thread.currentThread().interrupt();
logger.info("msg2 {}-" + Thread.currentThread().isInterrupted(), Thread.currentThread().isInterrupted());
logger.info("msg3 {}-" + Thread.currentThread().isInterrupted(), Thread.currentThread().isInterrupted());
Thread.interrupted();
```
When putting it into the `public static void main(String[] args)` method of the Dropwizard application's main Application class, it correctly prints
```
09:29:29.764 [main] INFO  logger - msg1 false-false
09:29:29.777 [main] INFO  logger - msg2 true-true
09:29:29.778 [main] INFO  logger - msg3 true-true
```
However, when putting it into the same class' `public void run(AppConfiguration, Environment)` method (or anywhere else later in the whole server application), it prints
```
INFO  [2017-05-12 07:24:38,072][main][] logger: msg1 false-false
INFO  [2017-05-12 07:24:38,072][main][] logger: msg3 false-false
```

As you see, when the thread's `interrupted` flag is set, one logging call is not written to the log, and what is much worse: the logging call clears the `interrupted` flag!

This can for example lead to background jobs not stopping (and the Dropwizard application hanging forever on shutdown), because the jobs don't notice they're interrupted.

This is against Dropwizard 0.9.2, but unfortunately, I cannot test it on the current 1.1.0 version now. However, I did not find an issue describing this bug, so I guess it may well be still present.

**Comment by nickbabcock** [comment]
Dropwizard 0.9 ships with Logback 1.1.3

[Logback 1.1.4 release notes](https://logback.qos.ch/news.html) contain

> restores the current thread's interrupt flag when catching an InterruptedException

Dropwizard 1.0 and 1.1 use later versions of Logback

**Comment by dllx** [comment]
Thank you! That's another incentive for us to upgrade our Dropwizard version.
(Simply changing the logback version via pom dependencies does not work, alas.)

**Comment by davidinjc** [comment]
Thank you for posting this, helped us zero in on why the interrupted flag was getting reset!
