### ISSUE TITLE
Change the log file charset

### ISSUE THREAD

**Issue by mi5c** [dropwizard/dropwizard#2060]
I noticed that the non-ascii characters in the Dropwizard application logFile are getting replaced with `?`.

For example, when you do:
```
            LOGGER.info("ä");
```
one would see:
INFO  [date] [logger] - ?

I believe this is because the log file uses us-ascii charset for us.
```
$ file -i our-service.log
our-service.log: text/plain; charset=us-ascii
```
I checked that the default charset on a host should be set to UTF-8
```
$ echo $LC_CTYPE
UTF-8
```

Is it possible to change the charset to UTF-8 for application log files?
I tried to add
```
    appenders:
           charset: UTF-8
```
to the file appender, but the Configuration did not like that.

I tested both dw0.7 and dw1.0.2

**Comment by nickbabcock** [comment]
Correct, there is no way to currently configure the charset for loggers. The logging factories (`ConsoleAppenderFactory` / `FileAppenderFactory`) that use a `LayoutWrappingEncoder` would need to call `layoutEncoder.setCharset()` with the configurable option.

That said, if no charset is set, Logback will use the default charset. I don't believe LC_CTYPE tells you the default Java charset. Try [printing out the default charset](http://stackoverflow.com/a/2677624/433785).

So my suggestions are:

- [Explicitly set the charset to UTF-8 and see if that makes a difference](http://stackoverflow.com/q/6031877/433785)
- And/or a pull request to add in a custom charset for loggers

**Comment by mi5c** [comment]
Hi @nickbabcock thanks for looking into this. Seems the setting the file encoding on jvm via
```
-Dfile.encoding=UTF8 or -Dfile.encoding=UTF-8
```

won't help, the log line will become
```
INFO [date] [logger] - <C3><A4>
```
which is a bit better, but I think a PR for the `LayoutWrappingEncoder` is still needed.
I have added a task for myself to investigate whether this fixes the issue.

Thanks again for your help!
