### ISSUE TITLE
How to disable Resource Logging

### ISSUE THREAD

**Issue by ruslander** [dropwizard/dropwizard#2064]
Hi There,

Using DropWizard in current project, good job guys, works like a charm.

I scanned documentation and all available info online a could not figure out how to turn off logging for only one particular logger. The one which produces following line

0:0:0:0:0:0:0:1 - - [22/May/2017:20:41:19 +0000] "GET /carrier/boardingPasses?airport=ATL&timestamp=2017-05-08T18%3A32%3A58.987Z&frequentFlyerNumber=1000000000 HTTP/1.1" 404 43 "-" "PostmanRuntime/3.0.11-hotfix.2" 2362 

It contains Personal Identifiable Information and for security compliance I'm not allowed to log it. It would be fine if I did not need any logs but that is not the case. 

Thank you!

**Comment by nickbabcock** [comment]
I believe you're talking for the request log:

```yaml
server:
  requestLog:
    appenders: []
```

You may update the log format as well to only print the url path and not query parameters.

**Comment by ruslander** [comment]
@nickbabcock here is how my config looks like 

server:
  requestLog:
    appenders:
      - type: console
      - type: file
        currentLogFilename: /var/log/application.log
        archive: false
        timeZone: UTC
  applicationConnectors:
    - type: http
      port: 8080
  adminConnectors:
    - type: http
      port: 8081

what I want is to disable that particular logger or filter out that line

**Comment by nickbabcock** [comment]
I guess I'm not sure what you are talking about when you mention a particular logger. The request log is a single logger. One can't filter specific endpoints from being logged out of the box (not without creating a custom logger)

**Comment by mattnelson** [comment]
You can implement a custom logging filter that can deny logging the request on the matched URI.

#1435

**Comment by nickbabcock** [comment]
@mattnelson great suggestion! This feature should definitely receive more attention in our docs, as it something even I forget about 😊
