### ISSUE TITLE
Getting started page code doesn't work

### ISSUE THREAD

**Issue by parasgithub** [dropwizard/dropwizard#2065]
The getting started page's code doesn't work - the Optional<String> parameter in the HelloWorldResource class causes an exception to be thrown on server start. The cause of the error can be seen here: https://github.com/dropwizard/dropwizard/issues/1115

Please modify the getting started tutorial to not use an Optional<String> parameter.

**Comment by arteam** [comment]
Could you print out your stack trace? We use Optionals in our examples [here](https://github.com/dropwizard/dropwizard/blob/master/dropwizard-example/src/main/java/com/example/helloworld/resources/HelloWorldResource.java) and it works. #1115 seems to be an issue with authentication.
