### ISSUE TITLE
Validation of associated entities

### ISSUE THREAD

**Issue by TheSprtCz** [dropwizard/dropwizard#2072]
In current version I found out that it is impossible to validate any associated entities for domain classes with `@ValidationMethod`.
To better demonstrate what is the problem, imagine situation like this:
You have two classes `SecretProject` and `User` and your goal is to allow only `Users` with permission `Admin` to be able to be associated to `SecretProject` so you choose to create `@ValidationMethod` which will check if `User` had the right permission.
(Code is 100% not complete with all annotations it should have, it there just as an example) 
```java
public class User {

  private Set<String> roles;

  public Set<String> getRoles() {
    return roles;
  }
}
```
```java
public class SecretProject {

  private User user;

  public User getUser() {
    return user;
  }

  @ValidationMethod(message = "Only admin can have SecretProject assigned.")
  public boolean isUserAdmin() {
    return user.getRoles().contains("ADMIN");
  }
}
```
You also create endpoint that will validate this entity before doing anything else, like this
```java
public Response create(@NotNull @Valid SecretProject project) {
   // DAO code
}
```
```js
{
   "user": {"id": 1}
}
```
But when using this endpoint with request entity specified above it throws NPE while validating because at the time of validation, Dropwizard didn't fetch `User`.

As use case I don't think it is that specific or that it doesn't make sense. Is there any workaround? Do I have to use different validation method? Do you think that it is feature that Dropwizard should have, or it is not in a scope of things that `@ValidationMethod` should do? Or am I wrong completely?

**Comment by jplock** [comment]
In terms of your example, it sounds like using the authorizers may be better suited to your use-case? http://www.dropwizard.io/1.1.0/docs/manual/auth.html#authorizer

**Comment by TheSprtCz** [comment]
No, I need to check `User` which is being sent, not `User` who is sending it.

**Comment by nickbabcock** [comment]
@TheSprtCz I can't repro this with the following code:

```java
@Path("/")
@Produces(MediaType.APPLICATION_JSON)
public class TestResource {
    @POST
    public String secret(@NotNull @Valid SecretProject project) {
        return "\"Success\"";
    }
}
```

```java
public class SecretProject {
    private ProjectUser user;

    @JsonProperty
    public ProjectUser getUser() {
        return user;
    }

    @JsonProperty
    public void setUser(ProjectUser user) {
        this.user = user;
    }

    @ValidationMethod(message = "Only admin can have SecretProject assigned.")
    public boolean isUserAdmin() {
        return user.getRoles().contains("ADMIN");
    }
}
```

```java
public class ProjectUser {
    private Set<String> roles;

    @JsonProperty
    public Set<String> getRoles() {
        return roles;
    }

    @JsonProperty
    public void setRoles(Set<String> roles) {
        this.roles = roles;
    }
}
```

```bash
$ curl -d '{ "user": { "roles": ["ADMIN"] } }' -H 'Content-Type: application/json' http://localhost:8080

Success

$ curl -d '{ "user": { "roles": ["MANAGER"] } }' -H 'Content-Type: application/json' http://localhost:8080

{"errors":["Only admin can have SecretProject assigned."]}
```

Is there something that I'm missing?

**Comment by TheSprtCz** [comment]
Your example will work and is not what is causing the problem. To make it not work you have to persist User to DB and refer it only by ID, which is enough to save him, like this.
```java
@Path("/")
@Produces(MediaType.APPLICATION_JSON)
public class TestResource {
    @POST
    public String secret(@NotNull @Valid SecretProject project) {
        return "\"Success\"";
    }
}
```
```java
public class SecretProject {
    private ProjectUser user;

    @JsonProperty
    public ProjectUser getUser() {
        return user;
    }

    @JsonProperty
    public void setUser(ProjectUser user) {
        this.user = user;
    }

    @ValidationMethod(message = "Only admin can have SecretProject assigned.")
    public boolean isUserAdmin() {
        return user.getRoles().contains("ADMIN");
    }
}
```
```java
public class ProjectUser {
    @Id
    private Long id;

    private Set<String> roles;

    @JsonProperty
    public Long getId() {
        return id;
    }

    @JsonProperty
    public void setId(Long id) {
      this.id = id;
    }

    @JsonProperty
    public Set<String> getRoles() {
        return roles;
    }

    @JsonProperty
    public void setRoles(Set<String> roles) {
        this.roles = roles;
    }
}
```
Now there will be problem, you don't have to send whole definition of User, you can send just this.
`curl -d '{ "user": { "id": 1 } }' -H 'Content-Type: application/json' http://localhost:8080`

You can also trick `@ValidationMethod` by sending `User` with different Roles than he has in DB, for example `User(id = 1)` with only Manager role can be sent like this and Validation will pass.
`curl -d '{ "user": { "id": 1, "roles":["ADMIN"] } }' -H 'Content-Type: application/json' http://localhost:8080`

**Comment by nickbabcock** [comment]
Ah, I didn't realize this question pertained to Hibernate ORM -- my biggest weakness 🤣

My only suggestions:

- Try disabling lazy loading in the `HibernateBundle`
- Ask around on the jackson or dropwizard mailing lists, as at first glance this doesn't appear to be an issue with dropwizard code (which simply deserializes the request body and then calls validation)

**Comment by TheSprtCz** [comment]
Thank you, lazy loading doesn't work because problem is that object is not fetched from Database at all.

I think there should be annotation like `@FetchFromDB` which would replace all associated entities from request body with actual entities from Database.

**Comment by nickbabcock** [comment]
My suggestion:

- Let jackson deserialize the request body into a POJO (this POJO doesn't have hibernate orm annotations)
- hibernate validator will validate said POJO
- in function, use orm and POJO together to get to desired object
- validate object
- throw exception if object failed validations

Unless someone with a deeper knowledge of hibernate + jackson informs us otherwise. To me, this is a good compromise between being explicit, readable, and concise.

**Comment by jplock** [comment]
I'd second this.  Separate the API representation from entity representation being persisted into the database.

**Comment by nickbabcock** [comment]
Closing as presented solutions are the recommended approach.
