### ISSUE TITLE
Dropwizard testing documentation is outdated

### ISSUE THREAD

**Issue by jottinger** [dropwizard/dropwizard#2074]
http://www.dropwizard.io/1.1.0/docs/manual/testing.html#non-junit

The JerseyClient code is incorrect; it looks like this might have been carried forward from an older version of the API.

**Comment by arteam** [comment]
Thanks for the report! Do you mean that `JerseyClientBuilder` doesn't accept a Dropwizard environment or there are some issues with the Jersey HTTP code? If former, then you need to use `JerseyClientBuilder` from the `dropwizard-client` module.

**Comment by jottinger** [comment]
The Jersey code wouldn't compile for me. I have dropwizard-core and dropwizard-testing included as project dependencies; does that not include dropwizard-client? If it does, then the JerseyClientBuilder code is, from the best I can tell, out of date.

**Comment by arteam** [comment]
> does that not include dropwizard-client
Yes, it does not. `dropwizard-client` is a module for building a Jersey or Apache HTTP client tied to the Dropwizard environment (so you can configure it from the YAML configuration). You can see it in detail here: http://www.dropwizard.io/1.1.0/docs/manual/client.html.

The confusion may come from the fact that there is a `JerseyClientBuilder` in the Jersey client itself, but it's not the same client which is mentioned in the docs. We could probably specify a right import in the code snippet.

**Comment by novaterata** [comment]
Just my 2c,, The client created using JerseyClientBuilder and RULE.environment actually works with the intended jackson configuration. The client from RULE.clent() seems to ignore the environment completely. So, maybe explaining the difference and use cases would help.

**Comment by arteam** [comment]
That looks like a bug, thanks for bringing this up! I've created #2277 to fix it. The client produced by `DropwizardAppRule` should use the `ObjectMapper` from the test environment.

**Comment by nickbabcock** [comment]
Closed by https://github.com/dropwizard/dropwizard/pull/2277
