### ISSUE TITLE
Logging with logstash-console appender

### ISSUE THREAD

**Issue by bastman** [dropwizard/dropwizard#2075]
Could you please provide a detailed documentation on how to configure logging using a console appender (json / logstash format).

Why? 
- jars are deployed into simple docker containers
- Following 12factor app manifesto we need to log everything into STDOUT/STDERR, where an agent can listen, transform, forward log messages to whatever log-aggregation-service.
- json / logstash format allows structuring log messages into a simple machine readable format.

After googleing for 2 days, I just gave up. It's much easier to get this run using spring-boot in favour of dropwizard. Since, I would like continue using dropwizard, please provide a complete documentation on how to achieve that. Thanks a lot :)

**Comment by joschi** [comment]
@bastman You could take a peek at https://github.com/Wikia/dropwizard-logstash-encoder as basis for your own code.

**Comment by nickbabcock** [comment]
Closing as the presented solution seems fine and dropwizard supports JSON log output since 1.3.0
