### ISSUE TITLE
Unable to get JsonView deserialization working

### ISSUE THREAD

**Issue by mrwilby** [dropwizard/dropwizard#2076]
There's a post on the mailing list from Tatu some time back which indicates this should work:

https://groups.google.com/forum/#!topic/jackson-user/QW4ZmFBIMLA

I have JsonView serialization working okay (i.e. for response values) but I am trying to use the same to guard against unwanted inputs, just like Tatu mentions in this post, i.e. the ParamView.class reference being used during deserialization to filter out unwanted inputs.

Similar idea here: http://lifelongprogrammer.blogspot.com/2015/09/using-jackson-view-to-protect-mass-assignment.html

The behaviour I see is that anything the client provides to the service is accepted and deserialized into the parameter object, even stuff I am not technically annotating with the appropriate view type.

Note that I have:

    environment.getObjectMapper().disable(MapperFeature.DEFAULT_VIEW_INCLUSION);

in my application's run() method.

The class in question is an immutable PoJo - it contains a getter (which is annotated with a JsonView class and JsonProperty - obviously) and the constructor, which is annotated with JsonProperty. I've also tried annotating the constructor argument with a property-scoped JsonView (same as the getter) but no difference in behaviour.

I'm using 1.1.0 BTW. 

Is this supposed to work? TIA!

**Comment by mrwilby** [comment]
Also perhaps this is a better question for the mailing list. Hmm

**Comment by nickbabcock** [comment]
Sorry to circle back to this issue so late, but everything should work fine. If not, upgrade to the latest dropwizard v1.3.x, post a reproducible example, and then we can examine if it's something dropwizard specific.
