### ISSUE TITLE
JerseyClientConfiguration timeout not working during SSL handshake error

### ISSUE THREAD

**Issue by agyan5** [dropwizard/dropwizard#2077]
During SSL handshake error, jerseyclient timeout is not coming into picture. Seeing the connections going beyond 30 seconds during SSL handshake, where time out is set to 1 sec.

**Comment by nickbabcock** [comment]
The first thing that comes to mind is that the [client has two timeouts](http://www.dropwizard.io/1.1.0/docs/manual/configuration.html#httpclient) (`timeout` and `connectionTimeout`). Have you tried both?

Also to aid my understanding, are you saying that a SSL handshake error causes the timeout, vice versa, or are these two different problems?

**Comment by agyan2** [comment]
We have been setting both timeout and connectionTimeouts. The problem which i see is that during SSL handshake, if the backend goes down, timeout is not terminating the connection.
On researching, saw this issue reported in HttpClient, and possible change in the usage, per the lasy comment on the thread.
https://issues.apache.org/jira/plugins/servlet/mobile#issue/HTTPCLIENT-1478

**Comment by nickbabcock** [comment]
I can't tell you how many times I've read that jira issue and each time I think I come away with a different conclusion based on recent comments. I guess I 'll leave this open for the time being, but if you come across a way that works please feel free to share and if we can do anything on Dropwizard's side to prevent these hung connections.
