### ISSUE TITLE
io.dropwizard.jetty.MutableServletContextHandler.requests metrics not accurate for async requests?

### ISSUE THREAD

**Issue by raynorchenfr** [dropwizard/dropwizard#2079]
I am using dropwizard 1.0.2, and when trying to export some metrics on RESTful request endpoints.

One of the metrics used is io.dropwizard.jetty.MutableServletContextHandler.requests.

The metrics seemed correct for synchronously handled requests. But for requests that are handled asynchronously, the number reported is almost always around 1.5e9 (nano seconds), which is around 1.5 seconds, even if the responses got returned relatively quickly. Is there a way to configure/fix this?

Thanks in advance.

**Comment by nickbabcock** [comment]
This was fixed in https://github.com/dropwizard/metrics/pull/1074 which landed in metrics 3.2.0, which is bundled in Dropwizard 1.1.0, so you will have to upgrade

**Comment by raynorchenfr** [comment]
@nickbabcock Thanks!
