### ISSUE TITLE
DropwizardClientRule does not support forms

### ISSUE THREAD

**Issue by pipiliang** [dropwizard/dropwizard#2083]
Hi, `DropwizardClientRule` does not support forms.

My test resource class is:
```
@Path("/")
public class FakeResource {
    @POST
    @Path("controllers")
    public Response addController(@FormDataParam("file") InputStream is){
        ...
    }
}
```
When I run the test case, an error occurs：
```
ERROR [2017-06-22 11:40:15,974] org.glassfish.jersey.internal.Errors: Following issues have been detected: 
WARNING: No injection source found for a parameter of type public javax.ws.rs.core.Response ... addControllerjava.io.InputStream) at index 0.
```
I tried adding the `MultiPartBundle` to the FakeApplication initialize method, the problem solved:
```
    @Override
    public void initialize(Bootstrap<Configuration> bootstrap) {
         bootstrap.addBundle(new MultiPartBundle());
         super.initialize(bootstrap);
    }
```

**Comment by nickbabcock** [comment]
Have you tried:

```java
@ClassRule
public static final DropwizardClientRule DW_RULE =
    new DropwizardClientRule(new FakeResource(), MultiPartFeature.class);
```

It's what I do 😊 

But you are right that `DropwizardClientRule` should probably accept bundles as well

**Comment by pipiliang** [comment]
I tried, still same error,  dw version is 0.8.0.
```
import org.glassfish.jersey.media.multipart.MultiPartFeature;
```

**Comment by nickbabcock** [comment]
Can you try with a newer version of dropwizard (1.1 or 1.0)?

I ask as I'm running 1.0 and 1.1 and the above snippet of code works.

**Comment by pipiliang** [comment]
Sorry to answer so late, for some reason can not switch to the newer version, so only by adding `MultiPartBundle` to solve it

**Comment by joschi** [comment]
@pipiliang Thanks for your feedback!

I'm closing this issue as the problem doesn't exist in recent Dropwizard releases.
