### ISSUE TITLE
Update Jackson to address Deserializer security vulnerability

### ISSUE THREAD

**Issue by msymons** [dropwizard/dropwizard#2085]
A Jackson Deserializer security vulnerability is detailed by:

FasterXML/jackson-databind#1599
https://github.com/FasterXML/jackson/wiki/Jackson-Release-2.8.9

Fixed by 
•	2.7.9.1 (for dropwizard 1.0.x branch)
•	2.8.9 (for dropwizard 1.1.x branch)
•	2.9.0.pr3

**Comment by evnm** [comment]
Thanks for submitting these, @msymons!

**Comment by BenScholl** [comment]
I **think** this won't affect most Dropwizard apps, unless they specifically set `objectMapper.enableDefaultTyping()` or do funky things with e.g. `@JsonTypeInfo`.

At least that's my understanding after reading the excellent paper at https://github.com/mbechler/marshalsec

For reference: https://github.com/FasterXML/jackson-docs/wiki/JacksonPolymorphicDeserialization

**Comment by arteam** [comment]
I think so too. Nevertheless, I've pushed bugfix releases 1.1.2 and 1.0.8 which update Dropwizard to the Jackson versions which are not affected by this vulnerability.
