### ISSUE TITLE
Due to caching of constraint violation messages wrong message is being displayed.

### ISSUE THREAD

**Issue by imochurad** [dropwizard/dropwizard#2090]
I have a bean, that has a field annotated with several validation annotations.
```@NotEmpty```
```@NotBlankElements```
One of them is a standard annotation, one is custom built. 
The problem is that if in the first call to API I place request that causes first validation to fail, it's constraint violation message gets cached for 1 hour time. Then I place request with slightly modified payload that causes second annotation to fail. But I get exactly the same constraint validation message. 
I would like these messages to exactly reflect what part of payload was wrong.

`ConstraintMessage.getMessage(violation, invocable);`
This is the place where I obtain bad error message. `violation` object itself is holding proper message.

**Comment by nickbabcock** [comment]
What version of dropwizard are you running? If it is not 1.0 or 1.1, can you try either of these versions?

I created a test and everything worked as expected:

```java
public class MultiRepresentation {
    @NotNull
    @MaxSize(value = 10)
    @JsonProperty
    private Size size;

    public Size getSize() {
        return size;
    }
}
```

The `MaxSize` annotation is a custom annotation like yours.

- When `size` is null, the `@NotNull` triggers
- When `size` is more than 10 bytes, `MaxSize` triggers

**Comment by imochurad** [comment]
My version of DW is 1.0

**Comment by nickbabcock** [comment]
Ok, I'll need a either a test case that demonstrates this issue or a more fleshed out example.

**Comment by rtti** [comment]
I have similar issue. 

```
@StringEnumeration(enumClass = ComparisonOperator.class)
    private String operator;
```

```
@Override
    public boolean isValid(String value, ConstraintValidatorContext context) {
        if (!AVAILABLE_ENUM_NAMES.contains(value)) {
            String message = String.format("%s is invalid. Valid values are: %s", value, AVAILABLE_ENUM_NAMES);
            context.disableDefaultConstraintViolation();
            context.buildConstraintViolationWithTemplate(message).addConstraintViolation();
            return false;
        }
        return true;
    }
```

I always get the same error message that was generated at the first time, regardless of new constraint message value.

Please take a look at ConstraintMessage.MESSAGES_CACHE. Probably it invalidates cache in wrong way

**Comment by nickbabcock** [comment]
Ah, I see, it's a custom annotation. Adding the invalid value to the violation message would defeat all caching attempts. I'm torn 😕 

Does this mean you in favor of removing the cache?

**Comment by imochurad** [comment]
Personally, to fix this problem I have copied dropwizard's `ConstraintMessage` and removed caching part from it and I'm using that class instead of one that framework provides.

**Comment by rtti** [comment]
> Ah, I see, it's a custom annotation. Adding the invalid value to the violation message would defeat all caching attempts. I'm torn 😕

Unfortunately no, invalid value is cached at the first time and further values cannot be appeared.
Maybe problem exists only with custom annotations.

My workaround is to define own  ` ExceptionMapper<JerseyViolationException>`.

**Comment by nickbabcock** [comment]
Thinking about this issue for a little bit, I've come to a conclusion. Removing caching to support custom validation annotations that include the invalid value in the message seems like it would cause more harm than good when focusing on performance (though I'm happy to be proven wrong).

I'm open to making either `ConstraintMessage` or the exception mapper more easily extensible to exclude caching if there is enthusiasm for that (though a new issue should be created)

In the meantime, I'll close this issue as the behavior is as desired.
