### ISSUE TITLE
Add ServiceUnavailableRetryStrategy to the client

### ISSUE THREAD

**Issue by stringy05** [dropwizard/dropwizard#2093]
HTTP Client allows you to setup a ServiceUnavailableRetryStrategy to deal with error responses from Origin servers. I'd like to add this to the Dropwizard client

Basically add this to HttpClientBuilder.java
```
    public HttpClientBuilder using(ServiceUnavailableRetryStrategy serviceUnavailableRetryStrategy) 
    {
        this.serviceUnavailableRetryStrategy = serviceUnavailableRetryStrategy;
        return this;
    }

    // ... then in createClient
 
    protected ConfiguredCloseableHttpClient createClient(
   
        ... snip ...

        if (serviceUnavailableRetryStrategy != null) {
            builder.setServiceUnavailableRetryStrategy(serviceUnavailableRetryStrategy);
        }


```

And the same sort of thing in JerseyClientBuilder.

**Comment by arteam** [comment]
After #2091 is merged, we could add support for `ServiceUnavailableRetryStrategy`.

**Comment by stringy05** [comment]
I'll do that tonight. I'll make it work the same way as the
HttpRequestRetryHandler, where it only actually takes effect if the retries
is > 0

**Comment by patrox** [comment]
Hi @stringy05, are you planning to add the support for this, as I'm also interested in this functionality.
I can create a PR, if you are not planning to do it.

**Comment by patrox** [comment]
@stringy05, @arteam I have created a PR adding support for configuring the `ServiceUnavailableRetryStrategy` while using either HttpClientBuilder, or JerseyClientBuilder.

Could you please have a look ? https://github.com/dropwizard/dropwizard/pull/2185

**Comment by stringy05** [comment]
Hi Patryk

I had actually done this change but hadn't finished the doco. I think I'd
added some changes to another class as well, maybe the JerseyClientBuilder

Yep, here's the commit:
https://github.com/stringy05/dropwizard/commit/18906dd087f36fc201597ec2891bac515795a687

I'd also started updating the documentation as well, might want to add that
as well

Cheers

Brock

**Comment by patrox** [comment]
Hi Brock,

so can I complete the PR, or do you want to do it ?
We are also interested in getting it merged :)
