### ISSUE TITLE
Microsoft AD/LDAP & Basic Authentication improvement

### ISSUE THREAD

**Issue by charbonnier666** [dropwizard/dropwizard#2099]
Hi all,
to make Microsoft LDAP with Active Directory basic authentication works in dropwizard i must include this project https://github.com/blackberry/Dropwizard-Active-Directory-LDAP-Authentication 

`<dependency>
<groupId>com.blackberry.bdp.dwauth</groupId>
   <artifactId>dwMsAdLdapAuth</artifactId>
   <version>0.1.1</version>
</dependency>`

and/or this library:

` 
        <dependency>
            <groupId>com.unboundid</groupId>
            <artifactId>unboundid-ldapsdk</artifactId>
            <version>3.0.0</version>
        </dependency>`

Maybe you can think of getting it in?

**Comment by joschi** [comment]
@charbonnier666 Not everyone is using LDAP and not everyone is using Active Directory.

What's wrong with using a third party library to fulfill your requirements?

**Comment by charbonnier666** [comment]
@joschi  simply to complete the authentication options, to find the right library I had to spend a bit of time. A tip for those who will be in the same situation ;)

**Comment by joschi** [comment]
@charbonnier666 Feel free to add a short sentence about this to the documentation or add the relevant library to the Dropwizard 3rd Party Modules directory: http://modules.dropwizard.io/thirdparty/
