### ISSUE TITLE
Performance issue with logback-acess

### ISSUE THREAD

**Issue by natnan** [dropwizard/dropwizard#2102]
There seems to be a serious issue with the logback-access change on dropwizard.
Unfortunately I don't have time to isolate the issue and provide a test case to reproduce it at the moment, but I will try to do that as soon as I have the time. I apologize for that but I think it's important enough to submit an issue anyway.

We have a test case for performance which involves 4 different dropwizard services which makes http requests to each other as well as serve requests from outside. We have realized that these services took a really big performance hit after dropwizard upgrade from 1.0.x to 1.1.x. After spending long time to figure out what's going on (insert microservices rant here), I realized that the bottleneck service was hitting the jetty maxThreads very quickly sometimes. Yet it was reporting only milliseconds in the request logs. So it means somewhere in jetty was hanging, leading to thread hogging.

Finally, via profiling the bottleneck service, I came across this:
![image](https://user-images.githubusercontent.com/5628051/28066888-23016966-663f-11e7-8c0e-5c757108b22d.png)
Jetty's BlockingArrayQueue is also used by `AsyncNCSARequestLog` it seems.

Reading the dropwizard documentation and release notes, decided to disable the request logging which fixed the performance and thread hogging problem. 

```
  requestLog:
    type: classic
```
also solves the problem.

Considering the complex nature of our 4 services and the running test which makes many requests to different services, there may be many things triggering this rather than logback-access having problems with heavy load. But there is definitely a problem here.

**Comment by natnan** [comment]
So far, my attempts to reproduce this on dropwizard-example project have failed.

**Comment by nickbabcock** [comment]
@natnan is this still an issue for you? Or have you just stuck with the classic request log implementation?

**Comment by natnan** [comment]
It's been on classic mode since then but it is a good time to switch back and test again. Though the architecture of our application has changed and it's no longer multiple services, so that may not trigger the issue we were having then. I'll get back with results later next week.

**Comment by natnan** [comment]
Stressing the system doesn't trigger the thread count jump on our single application. It might very well be because it's now single dropwizard application instead of 4 that communicate with each other, but since nobody else has come across this, I think we can close this issue. The most important part is that it's documented somewhere (here) and there is a workaround.
