### ISSUE TITLE
PolymorphicAuthDynamicFeature is incompatible with environment.servlets().addFilter

### ISSUE THREAD

**Issue by petr-bazant** [dropwizard/dropwizard#2106]
After I have upgraded to the 1.1.2 version and started to use PolymorphicAuthDynamicFeature for Multiple Principals and Authenticators use-case, my servlet filter (a simple filter watching gzip-errors) does not work anymore.

Set-up of (to be simple just one) authenticator:
```
    private static void setupAuth(Environment environment, AppIdProvider appIdProvider) {

        final AuthFilter<String, App> oauthApp = new OAuthCredentialAuthFilter.Builder<App>()
                .setAuthenticator(new AppAuthAuthenticator(appIdProvider))
                .setAuthorizer(new AppAuthorizer())
                .setPrefix("Bearer")
                .buildAuthFilter();

        final PolymorphicAuthDynamicFeature feature = new PolymorphicAuthDynamicFeature<>(
                ImmutableMap.of(
                        App.class, oauthApp));

        final AbstractBinder binder = new PolymorphicAuthValueFactoryProvider.Binder<>(
                ImmutableSet.of(App.class));

        environment.jersey().register(feature);
        environment.jersey().register(binder);

    }
```

And then an attempt to register a servlet filter:
```
environment.servlets().addFilter("gzip-error-filter",
                new ZipExceptionFilter()).addMappingForUrlPatterns(EnumSet.allOf(DispatcherType.class), false, "/*");
``` 

The result is that the "gzip-error-filter" servlet filter is not registered.

My suspicion is that it has something to do with the last paragraph with the note "The polymorphic auth feature SHOULD NOT be used with any other AuthDynamicFeature. Doing so may have undesired effects." on the bottom of http://www.dropwizard.io/1.1.2/docs/manual/auth.html.

It looks like a bug which prevents registering servlet filters when the PolymorphicAuthDynamicFeature is used.

**Comment by tmszdmsk** [comment]
@petr-bazant but aren't servlet filters completely isolated from Jersey context? I believe they share nothing.

**Comment by nickbabcock** [comment]
Sorry for getting back so late to this issue, but what @tmszdmsk alludes to is correct. Dropwizard itself adds servlet filters like `ThreadNameFilter` and `AllowedMethodsFilter`, which are not impacted by `PolymorphicAuthDynamicFeature` (a jersey feature)
