### ISSUE TITLE
Multiple servlets map to path /* error when using Assets

### ISSUE THREAD

**Issue by fgsilveira** [dropwizard/dropwizard#2107]
Good evening,

I'm rather new to Java and Dropwizard, but I'm trying to use this framework to create a REST server and a front-end using VueJS.

What I thought was to use Assets to serve an index.htm (eg: www.example.com/index.htm) and having a /js/ and /css/ folders to JavaScript and CSS files respectively, but when configuring Assets as below I get the error in "Multiple servlets map to path /*: static[mapped:JAVAX_API:null],io.dropwizard.jersey.setup.JerseyServletContainer-5d5160e6[mapped:EMBEDDED:null]".

The code I'm using to configure Assets is this one:

@Override
public void initialize(final Bootstrap<PhoenixConfiguration> bootstrap) {
    bootstrap.addBundle(new AssetsBundle("/assets", "/", "index.htm"));
}

My project [1] is basically the Hello World example with this Asset, I've tried to follow the manual as per [2] and as it wasn't working I've created a thread in dropwizard-user as you can see in [3], I've also searched for possible solutions on the group and found this [4] but that didn't work either.

I hope this is just a simple regression or a misconfiguration.

Regards,
  Flavio

[1]: https://github.com/fgsilveira/phoenix
[2]: http://www.dropwizard.io/1.1.2/docs/manual/core.html#serving-assets
[3]: https://groups.google.com/forum/#!topic/dropwizard-user/k53upUhORg4
[4]: https://groups.google.com/forum/#!topic/dropwizard-user/a_jNCLE7oXM

**Comment by isaki-x** [comment]
I ran into this exact problem and never found a simple fix. I have an effective workaround, however.

Basically, for root, I set up a redirect using a resource class that would handle the "/" and redirect to my index file.

In your example, you could do this (this is kind of a poor implementation, but it illustrates the concept):

```Java
@Path("/")
public class IndexResource {

    private static final String INDEX = "/index.htm";

    @GET
    public Response get() throws Exception {
        final URI tmp = new URI(INDEX);
        return Response.seeOther(tmp).build();
    }
}
```

Then, you would not include "/" in your asset bundle. However, you will still need set up index.html as an asset so the redirect has something to serve.

**Comment by fgsilveira** [comment]
Thanks for your feedback and workaround Scott! I will test this in a few minutes.

Do you see any possibility of "fixing" this in a better way? Or maybe this is a feature request?!

**Comment by isaki-x** [comment]
I haven't really dug into this part of the code base, so I'm not sure how easy a fix would be. I defer to the owners of the project for that. I strongly suspect it is not something straightforward to implement, but I could be wrong.

**Comment by arteam** [comment]
I am a little bit confused why the solution with:
```yaml
server:
  rootPath: /api
```

doesn't work for you.  With this configuration you serve your JS resources from the root, and your API from the `/api` path. Do you receive an error message when running a Dropwizard with such config?

**Comment by fgsilveira** [comment]
Hi Artem,

Yes, I receive the error message from subject when using this configuration. I tried /api, /api/ and /api/*, nothing changes. As I said on the first message, I don't much experience, all I can say is what I did and what I've tried already.

**Comment by arteam** [comment]
Okay, let's try to isolate the problem. Here is a simple Dropwizard app:

```java
public class ApiApplication extends Application<Configuration> {

    @Path("/test")
    public static class TestResource {

        @GET
        @Produces(MediaType.TEXT_PLAIN)
        public String test() {
            return "Hello";
        }
    }

    @Override
    public void initialize(final Bootstrap<Configuration> bootstrap) {
        bootstrap.addBundle(new AssetsBundle("/assets", "/", "index.htm"));
    }

    @Override
    public void run(Configuration configuration, Environment environment) throws Exception {
        environment.jersey().register(new TestResource());
    }

    public static void main(String[] args) throws Exception {
        new ApiApplication().run(args);
    }
}
```

Static file `example.txt` under the `/assets/` directory in app's resources
```
Example static asset file.
```

App config `config.yml`
```yaml
server:
  rootPath: /api
```

If I run it with `java -jar app.jar sevrer config.yml` the server starts and shows:
```
INFO  [2017-07-18 16:52:54,691] io.dropwizard.jersey.DropwizardResourceConfig: The following paths were found for the configured resources:

    GET     /api/test (com.example.helloworld.ApiApplication.TestResource)
```

I then check URI paths via curl and they work:
```
127.0.0.1 - - [18/Jul/2017:17:00:22 +0000] "GET /example.txt HTTP/1.1" 200 27 "-" "curl/7.47.0" 19
127.0.0.1 - - [18/Jul/2017:17:00:29 +0000] "GET /api/test HTTP/1.1" 200 5 "-" "curl/7.47.0" 45
```

Does it work for you?

**Comment by fgsilveira** [comment]
Yes Artem, it works, so maybe it was a confusion from my part, because by following the "Hello World" example and creating hello-world.yml I thought config.yml was only related to framework configurations, not directly related to the application itself. 

I'm sorry for all the noise, can you please evaluate if the documentation of the example could be improved in that sense?

**Comment by isaki-x** [comment]
I like the rootPath solution; I may look to utilize that when I have time to tackle some technical debt in my own applications!

**Comment by carldowns** [comment]
https://groups.google.com/forum/#!msg/dropwizard-user/a_jNCLE7oXM/J4B-R_FlYcEJ

The above works.
Recommend changing the rootPath to include a "/*" wildcard to match any Resource's @Path:

server:
    rootPath: /api/*
