### ISSUE TITLE
post commit action (UnitOfWork)

### ISSUE THREAD

**Issue by yateam** [dropwizard/dropwizard#2110]
Hello, 

is there any way to schedule some action after `UnitOfWork` commit is done? 
For example, I want to send an email only if a transaction is successful. How would I do it if a Jersey resource is wrapped with `@UnitOfWork`?
I could think of a workaround, where you put events in some sort of an EventBus, and if a request transaction is successful, then those events would execute. But maybe there are better options for Dropwizard?

Thanks!

**Comment by isaki-x** [comment]
The documentation gives a clue:

```Java
/**
 * When annotating a Jersey resource method, wraps the method in a Hibernate session.
 * <p>To be used outside Jersey, one need to create a proxy of the component with the
 * annotated method.</p.
 *
 * @see UnitOfWorkApplicationListener
 * @see UnitOfWorkAwareProxyFactory
 */
```

I would check out this issue:

https://github.com/dropwizard/dropwizard/pull/1361

My approach would be as follows (disclaimer: I've never used this functionality and haven't fully researched it):

- Remove `@UnitOfWork` resource in question from Jersey.
- Create new replacement resource for the URL that was removed.
- In the new replacement resource, give it access to the original resource and proxy described above.
- Invoke the original resource, check its status and any entities for custom handling, and return that `Response` to the caller.

There might be a better way than this, but this is what my superficial research led me to.

**Comment by yateam** [comment]
Thanks! Yes I know about UnitOfWork proxy.
Unfortunately such workaround could lead to issues described here:
https://github.com/dropwizard/dropwizard/issues/1334#issuecomment-235998121

**Comment by yateam** [comment]
Found a workaround - haven't checked it yet, but looks promising anyway.

In your DAO class (assuming you use Hibernate) , add a method something like this:
```
public User save(User user, Runnable afterCommit) {
    currentSession().getTransaction().registerSynchronization(new Synchronization() {
      @Override
      public void beforeCompletion() {
      }

      @Override
      public void afterCompletion(int status) {
        if (status == Status.STATUS_COMMITTED) {
          afterCommit.run();
        }
      }
    });
    return persist(user);
  }
```

Then the client might look something like this:
`userDAO.save(user, () -> emailGateway.sendNewUserEmail())`

**Comment by nickbabcock** [comment]
Closing as it looks like the question is answered. Let me know if not and if there is something that should be done inside Dropwizard.

**Comment by mlinsky** [comment]
Is this still needed? Is @UnitOfWork still not working?
