### ISSUE TITLE
Jackson dependency needs to be updated from 2.8.9 to 2.9.0

### ISSUE THREAD

**Issue by hugh-emerson** [dropwizard/dropwizard#2120]
Hi,

As confirmed in this https://github.com/FasterXML/jackson-modules-java8/issues/33, Jackson 2.8.9 has an error, which is fixed in 2.9.0.
Can you confirm whether this will be fixed in a new release of dropwizard soon?

Thanks,
Hugh

**Comment by joschi** [comment]
@hugh-emerson An upgrade to Jackson 2.9.0 has been scheduled for Dropwizard 1.2.0, see #2057.

There are no plans to upgrade to Jackson 2.9.0 in Dropwizard 1.1.x.

**Comment by arteam** [comment]
That's right. Nevertheless, If you want to try out Dropwizard with Jackson 2.9, I was going to make today a release candidate for Dropwizard 1.2 today and upload it to Maven Central.

**Comment by msymons** [comment]
The linked issue had a 2.8.10 milestone added on 21st June 2017 and I see that @joschi has already added a request there for a 2.8.x bugfix release.  So, watch for that bugfix and then Dropwizard 1.1.x can be updated.

**Comment by joschi** [comment]
Fixed in cefe3a9554551c847b0cc73714b0027784bc23cf
