### ISSUE TITLE
JerseyClientConfiguration in client manual is missing mutator

### ISSUE THREAD

**Issue by tasosz** [dropwizard/dropwizard#2125]
JerseyClientConfiguration in client manual is missing mutator, here:
[Dropwizard Client](https://github.com/dropwizard/dropwizard/blob/master/docs/source/manual/client.rst)

This is only minor issue, but easy/quick to fix.

Missing snippet:
```
    @JsonProperty("jerseyClient")
    public void setJerseyClientConfiguration(JerseyClientConfiguration jerseyClient) {
        this. jerseyClient = jerseyClient;
    }
```

**Comment by arteam** [comment]
Thank you for reporting this! Fixed in 6a4bf5b.
