### ISSUE TITLE
Content-Encoding response header is not set when set using FilterChain

### ISSUE THREAD

**Issue by namannigam** [dropwizard/dropwizard#2126]
Using the following version: 
```
<dependency>
    <groupId>io.dropwizard</groupId>
    <artifactId>dropwizard-core</artifactId>
    <version>1.1.2</version>
</dependency>
```
Our service is not able to add to Response Headers the header for Content-Encoding. 

The `GzipFilter` class we added is as: 
```
import javax.servlet.*;
import javax.servlet.http.HttpServletResponse;
import java.io.IOException;

public class GzipFilter implements Filter {
    public void doFilter(ServletRequest req, ServletResponse res, FilterChain chain)
            throws IOException, ServletException {
        HttpServletResponse response = (HttpServletResponse) res;
        response.setHeader("Content-Encoding", "gzip");
        chain.doFilter(req, res);
    }

    public void init(FilterConfig filterConfig) {
    }

    public void destroy() {
    }
}
```

and the configuration for `OurService extends Application<DocumentServiceConfig>` is as:

 ```
@Override
public void run(OurServiceConfig config, Environment environment) throws Exception {
    Injector injector = createInjector(config, environment);
    environment.jersey().register(injector.getInstance(StatsResource.class)); // Some resource 
    environment.servlets().addFilter("Gzip-Filter", GzipFilter.class)
            .addMappingForUrlPatterns(EnumSet.allOf(DispatcherType.class), true, "/*");
}
```

The issue is, we don't get the **Content-Encoding: gzip** in our response headers.

Just to add to the note, tried this with `dropwizard-core:1.2.0-rc1` and the behavior is same.

**Comment by arteam** [comment]
I believe Dropwizard does gzip compression automatically. The support for gzip is enabled by default (see http://www.dropwizard.io/1.1.2/docs/manual/configuration.html#gzip). So, if the client supports decompression by sending a request with the `Accept-Encoding:gzip` header, `org.eclipse.jetty.server.handler.gzip.GzipHandler` will compress the response and add the `Content-Encoding: gzip` header.

Why your custom filter doesn't work is not clear, maybe your filter is executed before the Jersey servlet and it rewrites the header.

**Comment by namannigam** [comment]
@arteam Assuming that the default response is gzipped from dropwizard. Even if I include the `Accept-Encoding:gzip` header. I don't get back a `Content-Encoding:gzip` in the response headers. 

> Why your custom filter doesn't work is not clear, maybe your filter is executed before the Jersey servlet and it rewrites the header.
Do you see any such changes from the shared code? Since we had not intentionally overridden the headers. Just wanted to set the value as such.

**Comment by arteam** [comment]
> Assuming that the default response is gzipped from dropwizard. Even if I include the Accept-Encoding:gzip header. I don't get back a Content-Encoding:gzip in the response headers

How big is your response? By default responses less than 256 bytes are not compressed. Also, only GET methods are compressed by default.

> Do you see any such changes from the shared code? Since we had not intentionally overridden the headers. Just wanted to set the value as such.

Your custom filter looks good considering all your Jersey resources return gzipped content by default.
I would debug filter chain to see why the header could be removed (and Jetty's `GzipHandler` since it's enabled by default).

**Comment by namannigam** [comment]
> How big is your response? By default responses less than 256 bytes are not compressed. Also, only GET methods are compressed by default.

Approximately 150KB. Using both GET and POST. Have tried enabling using 
```
  gzip:
     enabled: true
     minimumEntitySize: 256B
     bufferSize: 32KB
```
Still, won't work for me.

Would debug the FilterChain further for this. Thanks.

**Comment by namannigam** [comment]
Update - The additionally added ResponseHeader doesn't seem to be working but the default Response Headers from Dropwizard works fine. 
Our bad, the size we compared this against was the formatted content's size on Chrome. The raw content-length(size) pointed us to the correct metrics.

Closing this. Not an Issue.
