### ISSUE TITLE
Log resource validation failures

### ISSUE THREAD

**Issue by isaki-x** [dropwizard/dropwizard#2128]
So, it seems straightforward to log JSON processing errors (set DEBUG logging for `io.dropwizard.jersey.jackson.JsonProcessingExceptionMapper`). However, I don't see a way to easily log validation errors on the server side.

I suspect the class that should log it is `io.dropwizard.jersey.validation.JerseyViolationExceptionMapper`.

If I'm wrong and this is logged somewhere, please point me in the right direction. If not, please tell me if I have the right class and I will submit a pull request to add logging at the DEBUG level.

Thanks!

**Comment by nickbabcock** [comment]
Ah yes, that does look like to be an oversight, they should be more aligned! Yeah, I'll accept a PR for this.

**Comment by isaki-x** [comment]
Is JerseyViolationExceptionMapper the right spot?

**Comment by nickbabcock** [comment]
Yes it is!

**Comment by isaki-x** [comment]
Closing this issue; further discussion will be in the PR.
