### ISSUE TITLE
Guava 23 for DW 1.2?

### ISSUE THREAD

**Issue by CodingFabian** [dropwizard/dropwizard#2132]
Just checked the Release candidate. It is on Guava 22

I very much know how much of a pain Guava can be. Most of our codebases currently managed to settle on 23 as common denominator. Is there anything that holds back upgrading to 23 for DW 1.2?

**Comment by nickbabcock** [comment]
Looks like there is no breaking changes, so I'm :+1: for upgrading to gauva 23
