### ISSUE TITLE
FormDataParam default to null?

### ISSUE THREAD

**Issue by RohanNagar** [dropwizard/dropwizard#2139]
I have a method that accepts type Multipart Form Data. I want to be able to hit this endpoint sometimes without the specified `@FormDataParam("file")`, but right now when I leave it out the method returns a 400 bad request immediately. Is there a way I can set it up so that I can leave it out? Or is there some way I can set a default value for this (i.e. to null?). I wanted to try `@DefaultValue(null)` but the compiler didn't like that. Any help would be appreciated. My method declaration is below:

```java
@POST
@Path("/publish")
@Consumes(MediaType.MULTIPART_FORM_DATA)
public Response publish(@Auth Key key,
                          @QueryParam("email") String email,
                          @HeaderParam("password") String password,
                          @QueryParam("type") PublishType type,
                          @QueryParam("message") String message,
                          @FormDataParam("file") InputStream inputStream,
                          @FormDataParam("file") FormDataContentDisposition
                              contentDispositionHeader,
                          @FormDataParam("title") @DefaultValue("") String videoTitle) {
// code here
}
```

**Comment by lutzhorn** [comment]
What would be the `@DefaultValue` of a stream? What do you expect to happen?

**Comment by RohanNagar** [comment]
@lutzhorn I would expect the `@DefaultValue` of a stream to be null. In the case that I don't want to provide a value for it, I want it to be empty and to tell me that it is empty. I would like the chance to use the null value myself before it automatically returns a 400.

**Comment by lutzhorn** [comment]
`@DefaultParam` requires a `String` as `value`:

````java
@Target({ElementType.PARAMETER, ElementType.METHOD, ElementType.FIELD})
@Retention(RetentionPolicy.RUNTIME)
@Documented
public @interface DefaultValue {

    /**
     * The specified default value.
     */
    String value();
}
````

What would it mean to write something like this?

````java
@DefaultValue("foo") @FormDataParam("param1") InputStream param1
````

The string `foo` as a value for an `InputStream` makes no sense. I don't think what you want to do is possible using these annotations.

BTW, this question is not a Dropwizard question. It is about JAX-RS and `com.sun.jersey.contribs:jersey-multipart`. I suggest you close this issue here and check at [Jersey](https://github.com/jersey/jersey).

**Comment by RohanNagar** [comment]
I've opened an issue at [Jersey](https://github.com/jersey/jersey/issues/3652) but I'm not hopeful for a response, the response rate for issue questions there seem low. I suppose I can try on StackOverflow too. Thanks for the help, @lutzhorn.

**Comment by nickbabcock** [comment]
I agree that this would be a jersey issue, though I wonder if there is a workaround involving optionals:

```java
@FormDataParam("file") Optional<InputStream> inputStream,
```
I'm guessing it'll require a custom jersey body provider but it may be worth investigating 🤔

**Comment by RohanNagar** [comment]
@nickbabcock Good idea! I may look into that, I think that would be useful to have in other situations as well.
