### ISSUE TITLE
Is it safe to enable prudent mode on FileAppender ?

### ISSUE THREAD

**Issue by genz10** [dropwizard/dropwizard#2142]
Hello,

Is it safe to enable (by overriding) prudent mode in FileAppender ? 

because dropwizard disabled prudent mode by default shows in this [commit](https://github.com/dropwizard/dropwizard/blob/7322af7c3a32531ed3c05b188c128c73f611f3a9/dropwizard-core/src/main/java/com/yammer/dropwizard/logging/FileLoggingOutput.java)

Thanks.

**Comment by isaki-x** [comment]
That is some rather old code; I think the class you want is ```dropwizard-logging/src/main/java/io/dropwizard/logging/FileAppenderFactory.java```.

You should read the documentation on prudent: https://logback.qos.ch/manual/appenders.html

There are serious ramifications to setting this to true. If you are willing to pay the costs, it is probably safe. I will defer to the owners of this library to correct me if I am wrong.

Provided it is safe, it would be an easy PR to add an option for configuring prudent, with ```false``` being the correct default and documentation telling people not to change this unless they know what they are doing.

**Comment by genz10** [comment]
Yes,

I think I can accept those trade-off. Soon i'll submit PR regarding this configuration.

Thank for your answer @isaki-x

**Comment by isaki-x** [comment]
No problem! I took a look at your PR and while I'm not an owner of this repo it looks reasonable.

You will however need unit tests; your PR failed the coverage requirements.

**Comment by arteam** [comment]
Tracked in #2143
