### ISSUE TITLE
Update to Jersey 2.26

### ISSUE THREAD

**Issue by nickbabcock** [dropwizard/dropwizard#2148]
Looks like a new version came out a couple days ago. I believe Jersey is now Java 8 and implements jax-rs api 2.1, but I couldn't find rendered release notes.

There is bit of a migration -- I couldn't just update the pom 😄 

Migration doc is here: https://github.com/jersey/jersey/blob/12e5d8bdf22bcd2676a1032ed69473cf2bbc48c7/docs/src/main/docbook/migration.xml

EDIT: Quick thoughts:

We'll need to add

```xml
        <dependency>
            <groupId>org.glassfish.jersey.inject</groupId>
            <artifactId>jersey-hk2</artifactId>
        </dependency>
```

Also [where did AbstractContainerRequestValueFactory go?](https://github.com/jersey/jersey/issues/3630)

**Comment by joschi** [comment]
Since Jersey 2.26 brings a few breaking changes which require more changes to Dropwizard and 3rd party modules like dropwizard-guice, I'd suggest scheduling the upgrade to Dropwizard 2.0.0.

**Comment by mattnelson** [comment]
Here is a rendered version of the migration guide > https://jersey.github.io/documentation/latest/migration.html#mig-2.26

Would dropwizard have to do a major version bump when the two dependencies that would drive that decision only did a minor version (jaxrs-2.0 > 2.1 and jersey-2.25.1 > 2.2.6). And while not ideal, the adoption of new dependencies should not be hindered by 3rd party modules. That is the point of 3rd party modules, they are use at your own risk. If the changes are limited to a small subset of modules, the changes can be coordinated to limit the blast. But ultimately I don't care too much if the timeline for 2.0 is soon.

BTW, I have already pulled in jaxrs-2.1, without issue, in order to use [try-with-resources](https://github.com/jax-rs/api/issues/472)

**Comment by joschi** [comment]
@mattnelson Migrating from Jersey 2.25.1 to 2.26 is by far no minor upgrade and requires some breaking changes to Dropwizard.

**Comment by blling** [comment]
@joschi  Do you have any plan of impliment jersey-guice module ?

**Comment by euclio** [comment]
I believe this would fix the issue where `PATCH` is not supported natively by `JerseyTest`in Java 8.

https://stackoverflow.com/questions/29499106/using-patch-with-jersey-client-api-for-unit-testing

**Comment by mattnelson** [comment]
> I'd suggest scheduling the upgrade to Dropwizard 2.0.0.

What kind of timeline is expected on [2.0](https://github.com/dropwizard/dropwizard/milestone/18)? I searched and couldn't find any explicit documentation on the jersey support model regarding 2.25 EOL and/or patching of fixes. I have concerns on the technical debt of being stuck on 2.25.

***

> Do you have any plan of impliment jersey-guice module ?

That may be a little premature according to the [release notes](https://jersey.github.io/release-notes/2.26.html).
> Don't be mistaken - Jersey still runs on hk2. But it should be possible to get rid off that dependency when other container provides same functionality. As already mentioned, the motivation is to be able to integrate seamlessly with other frameworks, like cdi, guice, etc. This is still work in progress and there is one consequence: user has to provide Jersey injection implementation. The only one which is 100% ready right now is based on hk2:

**Comment by Tibor17** [comment]
If I used Jersey 2.26 I got 
`java.lang.NoSuchFieldError: INCLUDE_ALL`
It is thrown in dropwizard `Resource#before()` and the variable `test` is null. Constructor `new JerseyTest()` fails which calls method `configureDeployment()` overridden in dropwizard `Resource`.  The method `configureDeployment()` calls constructor `new DropwizardTestResourceConfig(configuration)` which finally throws `NoSuchFieldError` and here is the stack trace:

0 = {StackTraceElement@3460} "org.glassfish.jersey.server.ResourceConfig$State.<init>(ResourceConfig.java:114)"
1 = {StackTraceElement@3461} "org.glassfish.jersey.server.ResourceConfig.<init>(ResourceConfig.java:356)"
2 = {StackTraceElement@3462} "io.dropwizard.jersey.DropwizardResourceConfig.<init>(DropwizardResourceConfig.java:55)"
3 = {StackTraceElement@3463} "io.dropwizard.testing.common.DropwizardTestResourceConfig.<init>(DropwizardTestResourceConfig.java:33)"
4 = {StackTraceElement@3464} "io.dropwizard.testing.common.Resource$1.configureDeployment(Resource.java:188)"
5 = {StackTraceElement@3465} "org.glassfish.jersey.test.JerseyTest.<init>(JerseyTest.java:207)"
6 = {StackTraceElement@3466} "io.dropwizard.testing.common.Resource$1.<init>(Resource.java:180)"
7 = {StackTraceElement@3467} "io.dropwizard.testing.common.Resource.before(Resource.java:180)"
8 = {StackTraceElement@3468} "io.dropwizard.testing.junit.ResourceTestRule$1.evaluate(ResourceTestRule.java:99)"
9 = {StackTraceElement@3469} "org.junit.rules.RunRules.evaluate(RunRules.java:20)"
10 = {StackTraceElement@3470} "org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)"
11 = {StackTraceElement@3471} "org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)"

**Comment by joschi** [comment]
@Tibor17 Yes, because it's not compatible with Jersey 2.25.1 which is being used by Dropwizard 1.3.0 and 1.2.x.

**Comment by jbarnettwomply** [comment]
fwiw, https://github.com/jbarnettwomply/dropwizard/tree/jersey-2.26 is a work in progress on updating to 2.26.  currently not high priority for us, and running into issues with hk2 providers/binders, but if someone wants to pick up from there it may or may not be a helpful starting place

**Comment by isaki-x** [comment]
@mattnelson I've also been using `javax.ws.rs-api` 2.1 without issue for quite some time now (I have a dependency on it in a non-dropwizard library and it hasn't caused any issues by forcing this version in my managed dependencies).

**Comment by jplock** [comment]
@nickbabcock should we close this in favor of https://github.com/dropwizard/dropwizard/pull/2395 ?

**Comment by nickbabcock** [comment]
Yeah you can close this now or when #2395 is merged 😄

**Comment by jplock** [comment]
Closing in favor of #2395 👍
