### ISSUE TITLE
No way to assign custom error handlers.

### ISSUE THREAD

**Issue by thody** [dropwizard/dropwizard#215]
It would be great if there was a way to configure custom implementations of error handlers/representations.

Currently, it appears there's no way to override the behaviour of UnbrandedErrorHandler, which produces HTML representations of errors such as "Error 422 Unprocessable Entity", even when the Accept header is set to application/json.

Perhaps I'm just not aware of the approach to do this with the existing code?

**Comment by Cameronjmayfield** [comment]
For Dropwizard 0.8, you can eliminate default exception mappers with the following configuration in your *.yml file:
```
server:
    registerDefaultExceptionMappers: false
```
