### ISSUE TITLE
metrics-jdbi flagged by antivirus

### ISSUE THREAD

**Issue by manuel-hegner** [dropwizard/dropwizard#2157]
Hey,
today my maven build suddenly stopped working with some weird error messages. After some research i found that the antivirus blocks the bluid because of metrics-jdbi:3.2.2 jar file. Allegedly it contains the trojan Jamalky A!cl . This is most probably a fals positive, but I wanted to write it down here in case anyone else has the same error.

**Comment by nickbabcock** [comment]
Can you check if the sha1 of that file [matches what is on maven central](http://repo1.maven.org/maven2/io/dropwizard/metrics/metrics-jdbi/3.2.2/metrics-jdbi-3.2.2.jar.sha1)

> 77de34824fc106d0903ee7c85ce85bedd99ca68b

**Comment by manuel-hegner** [comment]
Oh yeah sorry. Of course I did that before assuming a false positive. The hash matches

**Comment by joschi** [comment]
@manuel-hegner Thanks for reporting this!

It looks like this is a false positive of your virus scanner. If you can spare some minutes, please contact the vendor of that software and let them know about it.
