### ISSUE TITLE
Jersey Jackson Integration

### ISSUE THREAD

**Issue by jmif** [dropwizard/dropwizard#2158]
I've been working to integrate `org.glassfish.jersey.security » oauth2-client` with my Dropwizard 1.1.2 app.  The `oauth2-client` package has dependency on ` org.glassfish.jersey.media » jersey-media-json-jackson`.

`jersey-media-jackson-json` has a class `JacksonFeature`.  This class [registers](https://github.com/jersey/jersey/blob/master/media/json-jackson/src/main/java/org/glassfish/jersey/jackson/JacksonFeature.java#L85) several `JacksonJaxbJsonProvider` related classes that seem to be overriding the Dropwizard JSON Providers.  For example, when I include this dependency the `JavaTimeModule` and `Jdk8Module` that are registered via `io.dropwizard.jackson.Jackson` are not included.

`JacksonFeature` attempts to [detect](https://github.com/jersey/jersey/blob/master/media/json-jackson/src/main/java/org/glassfish/jersey/jackson/JacksonFeature.java#L73) other registered features by looking for a `org.glassfish.jersey.internal.JSON_FEATURE` being set on the `FeatureContext`.

I'm able to disable this module with this line in my `Application#run` method:

```
environment.jersey().getResourceConfig().property(InternalProperties.JSON_FEATURE, "");
```

However this does not feel like the proper solution and I don't know enough about Jersey and the Jersey / Jackson integration to determine the proper way to fix this.  Is this something that Dropwizard should be setting or does the `JacksonFeature` need better detection?

**Comment by lutzhorn** [comment]
Are you using Maven? If yes, try to exclude the dependency of `oauth2-client` on `jersey-media-json-jackson`:

````xml
        <dependency>
            <groupId>org.glassfish.jersey.security</groupId>
            <artifactId>oauth2-client</artifactId>
            <version>2.26</version>
            <exclusions>
                <exclusion>
                    <groupId>org.glassfish.jersey.media </groupId>
                    <artifactId> jersey-media-json-jackson</artifactId>
                </exclusion>
            </exclusions>
        </dependency>

````

**Comment by nickbabcock** [comment]
Closing this as I'm assuming the question has been answered.

**Comment by dccarlos** [comment]
I have the same problem, if I exclude that `jersey-media-json-jackson` the OAuth2 client doesn't work
