### ISSUE TITLE
RxClient does not release connections

### ISSUE THREAD

**Issue by danpeter** [dropwizard/dropwizard#2162]
I am using a RxClient to make async requests but in one usecase I want to make a synchronous request. When doing this the thread seems to never be returned to the pool. 

Using metrics I see that leased-connections in the pool is forever growing until it is full. 

```
"org.apache.http.conn.HttpClientConnectionManager.accountClient.leased-connections": {
            "value": 265
        }
```

My code below, notice that I am NOT calling rx() on the client:

  ``` java
RxClient<RxObservableInvoker> client = new JerseyClientBuilder(environment)
.using(config)
.buildRx("accountClient", RxObservableInvoker.class);

Response response = client.target(uri)
.request()
.get()
```

Dropwizard 1.1.0

**Comment by nickbabcock** [comment]
Uh this would not be good, especially as `buildRx` is just a [one line wrapper](https://github.com/dropwizard/dropwizard/blob/e8f7f6c8c2008ed3ee2b7fb2d40b8f2bcf1874a0/dropwizard-client/src/main/java/io/dropwizard/client/JerseyClientBuilder.java#L321-L323) around Jersey code.  😟 

It'd probably either be an issue with Jersey or our [ApacheConnector](https://github.com/dropwizard/dropwizard/blob/e8f7f6c8c2008ed3ee2b7fb2d40b8f2bcf1874a0/dropwizard-client/src/main/java/io/dropwizard/client/DropwizardApacheConnector.java)

Does eschewing the RxClient and just making callback async requests exhibit the same behavior?

**Comment by danpeter** [comment]
Ok I think it is an issue of me not calling get(Class<T>) and not calling response,close();, thereby not closing the underlying connection. 

Consuming the response body correctly solved it.

**Comment by nickbabcock** [comment]
Phew, good to hear. It's happened to me too 😊
