### ISSUE TITLE
API changes report for Dropwizard

### ISSUE THREAD

**Issue by lvc** [dropwizard/dropwizard#2165]
The review of API changes for the Dropwizard library since 0.7.0 version: https://abi-laboratory.pro/java/tracker/timeline/dropwizard-core/

Hope it will be helpful for users and maintainers of the library.

The report is generated for jars found at http://central.maven.org/maven2/io/dropwizard/dropwizard-core/ according to https://wiki.eclipse.org/Evolving_Java-based_APIs_2.

Thank you.

![dropwizard-core-2](https://user-images.githubusercontent.com/1517837/31114058-e489d7fe-a824-11e7-8163-5690548e5bf2.png)
![dropwizard-core-1](https://user-images.githubusercontent.com/1517837/31114059-e48a7bdc-a824-11e7-97c0-2c3aeda76a1a.png)

**Comment by nickbabcock** [comment]
Thank you for taking the time to publish these reports, the results fall in line with what I'd expect (good to see 100% backwards compatibility 😄 ). I don't believe there is anything actionable here, so I'll close this issue, but feel free to respond if something should be addressed.

**Comment by joschi** [comment]
@lvc Thanks for sharing your results with us!

Any chance to get a similar report for all official Dropwizard artifacts? `dropwizard-core` only covers a tiny part of the functionality Dropwizard provides.

**Comment by lvc** [comment]
@joschi 

### Dropwizard

|Component | API report|
|:---:|:---:|
|Authentication|[view](https://abi-laboratory.pro/java/tracker/timeline/dropwizard-auth/)|
|Core|[view](https://abi-laboratory.pro/java/tracker/timeline/dropwizard-core/)|
|Database Support|[view](https://abi-laboratory.pro/java/tracker/timeline/dropwizard-db/)|
|HTTP Client|[view](https://abi-laboratory.pro/java/tracker/timeline/dropwizard-client/)|
|Metrics Support|[view](https://abi-laboratory.pro/java/tracker/timeline/dropwizard-metrics/)|
|Test Helpers|[view](https://abi-laboratory.pro/java/tracker/timeline/dropwizard-testing/)|

### Metrics

|Component | API report|
|:---:|:---:|
|Metrics Core|[view](https://abi-laboratory.pro/java/tracker/timeline/metrics-core/)|
|Metrics Graphite|[view](https://abi-laboratory.pro/java/tracker/timeline/metrics-graphite/)|
|Metrics JVM|[view](https://abi-laboratory.pro/java/tracker/timeline/metrics-jvm/)|
|Metrics Jackson|[view](https://abi-laboratory.pro/java/tracker/timeline/metrics-json/)|

Others will be added soon...

**Comment by joschi** [comment]
@lvc Awesome! Thank you so much!

**Comment by isaki-x** [comment]
That's awesome.
