### ISSUE TITLE
SubstitutingSourceProvider constructor only takes deprecated StrSubstitutor argument

### ISSUE THREAD

**Issue by ianferguson** [dropwizard/dropwizard#2171]
The [SubstitutingSourceProvider](https://github.com/dropwizard/dropwizard/blob/master/dropwizard-configuration/src/main/java/io/dropwizard/configuration/SubstitutingSourceProvider.java#L27) in dropwizard-configuration currently only has a single public constructor which takes an apache commons [StrSubstitutor](https://commons.apache.org/proper/commons-lang/apidocs/org/apache/commons/lang3/text/StrSubstitutor.html) object from the org.apache.commons.lang3.text package;

The StrSubstitutor class in that package was marked deprecated in favor of one in the [org.apache.commons.text package](https://commons.apache.org/proper/commons-text/javadocs/api-release/org/apache/commons/text/StrSubstitutor.html) as of apache commons 3.6, which is now the version brought in by the [Dropwizard Bom](https://github.com/dropwizard/dropwizard/blob/v1.2.0/dropwizard-bom/pom.xml#L46)

Ideally the SubstitutingSourceProvider would be updated to have a constructor or static factory method that takes a non-deprecated class for its configuration, either the one recommended by Apache or potentially a Dropwizard specific class that does not directly depend on apache commons.

**Comment by nickbabcock** [comment]
Ah that does appear to be an oversight on our part. Would you like to create a PR with your proposed fixes? Keeping the current (though deprecated) constructor would make this improvement a logical candidate to be included in a 1.2.1 release.

**Comment by ianferguson** [comment]
@nickbabcock I should probably be able to do that in the next week or two, yes.

**Comment by arteam** [comment]
I don't think we are going to fix it in 1.2.*. Warnings are not great, but I don't think it's worth to build a level of abstractions to solve a deprecation issue. The 1.3.0 version will use the new classes from `commons-text`.
