### ISSUE TITLE
When using JerseyClient dropwizard metric is not reflecting connection pool details

### ISSUE THREAD

**Issue by shankhanildas** [dropwizard/dropwizard#2172]
When using JerseyClient, apart from max-connections, all the other metric remains 0, like available-connections, leased-connections etc.

Is there an example of how to initiate the client? As of now, it's done in a standard manner -
final Client client = new JerseyClientBuilder(environment).using(config.getJerseyClientConfiguration())
                                                              .build(getName());

This may be similar to the issue(https://github.com/dropwizard/dropwizard/issues/789) but was not finding a concrete example with the metric publishing working fine. If the functionality is working, please provide some detail/example of how to achieve the same.

**Comment by nickbabcock** [comment]
For facilitation, what version of dropwizard are you using?

**Comment by shankhanildas** [comment]
As of now, dropwizard version 1.1.0

**Comment by nickbabcock** [comment]
Sorry for such the delay, but I can confirm your findings: it appears that since Dropwizard 1.1.0 (I have Dropwizard 1.0.x app that reports it fine) those metrics are zero. It may be the difference between sync and async http clients, as I haven't controlled for that yet.

**Comment by MaciejCiszewski** [comment]
I was not able to reproduce this bug in version 1.3 nor in 1.1.0.  Whenever I use the client created with:

final Client client = new JerseyClientBuilder(environment).using(config.getJerseyClientConfiguration())
.build(getName());

I could see that at least 'leased-connections' have non-zero value. After debugging I can see that metrics reflects perfectly the state of the connection pool. Are there any other conditions required to reproduce this bug?

**Comment by nickbabcock** [comment]
I just recently checked again and I must have been mistaken the first time (as I can see metrics dating back several years) where I can see non-zero metrics for both async and sync clients. So there is no bug here. Oftentimes the metric may report zero for short and fast requests.
