### ISSUE TITLE
Dropwizard passes soLingerTime to Jetty in seconds, while Jetty expects in milliseconds

### ISSUE THREAD

**Issue by mgtriffid** [dropwizard/dropwizard#2175]
When Dropwizard configures Jetty connector, it [passes configured soLingerTime in seconds](https://github.com/dropwizard/dropwizard/blob/master/dropwizard-jetty/src/main/java/io/dropwizard/jetty/HttpConnectorFactory.java#L558), and Jetty after that [divides that value by 1000](https://github.com/eclipse/jetty.project/blob/jetty-9.4.x/jetty-server/src/main/java/org/eclipse/jetty/server/ServerConnector.java#L398) (assuming those were milliseconds). So when developers configures soLingerTime as 300s, it is actually passed as 0 to Jetty, which is wrong.

**Comment by arteam** [comment]
Closed via #2176
