### ISSUE TITLE
Add possibility to configure Jetty's minRequestDataRate

### ISSUE THREAD

**Issue by mgtriffid** [dropwizard/dropwizard#2181]
[This parameter](https://github.com/eclipse/jetty.project/blob/4236f14955e828946c33f447fed3e65dfa8bfc1e/jetty-server/src/main/java/org/eclipse/jetty/server/HttpConfiguration.java#L493) can be useful if we want to protect our server from slow http DOS attacks.

**Comment by nickbabcock** [comment]
Agreed, sounds like a useful configuration for those who need it. I'd consider a PR if you or someone else would like to create one.

**Comment by patrox** [comment]
Hi @mgtriffid, @nickbabcock !

I also think it's a valuable configuration option, so I created a PR for that.
Could you please have a look ?

https://github.com/dropwizard/dropwizard/pull/2184
