### ISSUE TITLE
Content-Encoding: gzip header is not returned

### ISSUE THREAD

**Issue by kewats** [dropwizard/dropwizard#2182]
I am using Unirest for making api calls. I used "Accept-Encoding: gzip" header as part of my request. However, the response headers do not include "Content-Encoding: gzip". Am I doing something wrong here?

`HttpRequest restHttpRequest = Unirest.get("http://localhost:8080/foo/bar")
            .header("Accept-Encoding", "gzip")
            .queryString("param1", "val1");
    HttpResponse<String> httpResponse = restHttpRequest.asString();
    System.out.println(httpResponse.getHeaders().get("Content-Encoding"));`

Response size is bigger than the default minimumEntitySize. Would appreciate if you can provide any pointers. Thanks!

**Comment by arteam** [comment]
Hm, it should work. Could you post your YAML config and the code of the REST resource? Also, could you test that your client code works with http://httpbin.org/gzip?

**Comment by kewats** [comment]
Thanks @arteam. Not sure if you are looking for the server property from the yml alone or the entire content. Here is what I have under server:

`
server:
  applicationConnectors:
  - type: http
    port: 8080
  adminConnectors:
  - type: http
    port: 8081`

I have not used gzip configuration as I believe it is enabled by default.

Here is the skeleton of my REST resource code:

`@GET
@Path("/foo/bar")
@Produces(MediaType.APPLICATION_JSON)
public MyDataList getData() {
  return service.getData();
}`

Please let me know in case any more details are needed. Thanks!

**Comment by arteam** [comment]
This looks fine. Could you test with `curl` that the server doesn't return a `Content-Encoding: gzip` header? Something like `curl -v -H 'Accept-Encoding: gzip'  http://127.0.0.1:8080/foo/bar`. Could you check a `Content-Length` header in the response and verify that it's more than 256 bytes?

**Comment by arteam** [comment]
You could also try to enabled the debug level logging for gzip compression and see something suspicious in the output. You can do that in your config by
```yml
logging:
  loggers:
    org.eclipse.jetty.server.handler.gzip.GzipHttpOutputInterceptor: DEBUG
```

**Comment by kewats** [comment]
Logging was very useful, thanks! Looks like my response is getting compressed indeed, however not sure why response headers do not have "Content-Encoding: gzip".

> DEBUG [2017-10-23 12:23:16,031] org.eclipse.jetty.server.handler.gzip.GzipHttpOutputInterceptor: org.eclipse.jetty.server.handler.gzip.GzipHttpOutputInterceptor@57ed37d5 compressing java.util.zip.Deflater@687972c

**Comment by arteam** [comment]
Could you check with `curl` that the server returns the `Content-Encoding` header? Maybe your client under the hood automatically decodes gzip responses and strips the Content-Encoding header.

**Comment by kewats** [comment]
That's what it seems like. I will confirm on that as soon as I get a chance. But, surely compression is working fine for me. Many thanks for your help, I am closing this issue!

**Comment by durran-kelly** [comment]
Hello, I am also experiencing the same issue. Not only isn't Content-Encoding header not being returned, but my response is also not being encoded. I have been making my requests in Postman and have confirmed that it isn't automatically decoding the gzip responses and striping the Content-Encoding header by testing against http://httpbin.org/gzip, as well as a quick start of a spring boot application where I turned gzip encoding on. 

I also turned on logging and see this response:
DEBUG [2021-03-24 04:29:31,166] org.eclipse.jetty.server.handler.gzip.GzipHandler: GzipHandler@a2ddf26{STARTED,min=256,inflate=8192} handle Request(POST //localhost:8080/v1/volumes)@7d5ea0d4 **in null**
DEBUG [2021-03-24 04:29:31,167] org.eclipse.jetty.server.handler.gzip.GzipHandler: GzipHandler@a2ddf26{STARTED,min=256,inflate=8192} excluded by method Request(POST //localhost:8080/v1/volumes)@7d5ea0d4

The "in null" part is a little concerning. 

I have tried to explicitly enable gzipping through the config with no success (despite it being enabled by default). 

Can someone please tell me what I am doing wrong?  Thanks!!
