### ISSUE TITLE
Potential resource leak in ScanningHibernateBundle

### ISSUE THREAD

**Issue by patrox** [dropwizard/dropwizard#2188]
While playing a bit with [SonarQube](https://www.sonarqube.org/), I noticed (thanks to it), that there is [one place](https://github.com/dropwizard/dropwizard/blob/master/dropwizard-hibernate/src/main/java/io/dropwizard/hibernate/ScanningHibernateBundle.java#L43) where an instance of [`PackageNamesScanner`](https://github.com/jersey/jersey/blob/master/core-server/src/main/java/org/glassfish/jersey/server/internal/scanning/PackageNamesScanner.java) class (which implements `AutoClosable`) is not closed anywhere, which will result in not closing the resource which is referenced by this class [`compositeResourceFinder`](https://github.com/jersey/jersey/blob/master/core-server/src/main/java/org/glassfish/jersey/server/internal/scanning/PackageNamesScanner.java#L181).

A simple fix for that would be to create this instance of `PackageNamesScanner` within a try-with-resources block, so it will get automagically closed.

If this will be confirmed, I'm happy to provide a PR addressing this issue.

**Comment by patrox** [comment]
@joschi @nickbabcock @arteam Can I please ask one of you, for an opinion regarding the above ?

**Comment by nickbabcock** [comment]
Yeah, looks like an oversight. Apply your fix and if all the tests pass then I'd think it'd be good merge.
