### ISSUE TITLE
Version 1.1.6 not available on maven central

### ISSUE THREAD

**Issue by scho** [dropwizard/dropwizard#2194]
I get errors when building my project using `1.1.6`. Everything works fine with `1.1.5`. My assumption is, that the version was not properly published to maven central (see [maven central](https://search.maven.org/#search|gav|1|g%3A"io.dropwizard"%20AND%20a%3A"dropwizard-parent"), version `1.1.6` is not listed):

```
Non-resolvable import POM: Failure to find io.dropwizard:dropwizard-bom:pom:1.1.6 in ...
```

**Comment by joschi** [comment]
@scho Thanks for bringing this up!

Looks like we forgot to release the staging repository in Sonatype OSS.

I just did that and the release artifacts for Dropwizard 1.1.6 should soon be available.

**Comment by scho** [comment]
Cool, this was really fast. Thanks!
