### ISSUE TITLE
FreeMarker .ftlh and .ftlx files aren't working out of the box

### ISSUE THREAD

**Issue by ddekany** [dropwizard/dropwizard#2196]
FreeMarker recommends using ftlh and ftlx file extensions to turn on HTML and XML auto-escaping when its `incompatible_improvements` setting is at least 2.3.24. Currently it won't work, as `io.dropwizard.views.freemarker.FreemarkerViewRenderer.isRenderable` only matches the `.ftl` suffix.

**Comment by FredDeschenes** [comment]
Looks like we'd just need to separate the renderable template extensions from the configuration key used in `ViewBundle` (`getSuffix` would become `getConfigurationKey` or something like that).

Only issue I have is that it would now be weird to configure FreeMarker with the `.ftl` key when you might be rendering other file formats as well. We could change the configuration keys to be the name of the engine (ie: `freemarker` and `mustache`, which I think makes more sense anyway), but this would break compatibility. Any thoughts on this?

**Comment by ddekany** [comment]
Perhaps both the old file extension and the template engine name should be accepted, for backward compatibility, and if both key is used, that's an error.

While we are here, it's also a bit strange that the matching file extensions are hard-coded. I think that the matching file name patterns should be just a configuration option, and what's hard coded now should only be the default. A use case is file name patterns like `*.ftl.html`, or even just `*.html`. It's not standard, but some users do that, as they prefer templates to be associated with the HTML editor or viewer.

**Comment by FredDeschenes** [comment]
The configuration key change could also just be done for the next major version. It's weird, but it works and isn't really a big deal.

As for the configurable file extensions it would be pretty hard to implement cleanly with the current configuration setup for view renderers (the configurations just being maps that can have any value, although Mustache seems to only have 2 configurable options (but I'm not familiar with Mustache so I might be mistaken)). Would definitely be a good feature to have though.

**Comment by arteam** [comment]
I think something like that should be good to go:

```java
public interface ViewRenderer {
   default boolean isRenderable(View view) {
        return getSuffixes().stream()
            .anyMatch(s -> view.getTemplateName().endsWith(s));
    }

    @Deprecated
    default String getSuffix(){
        return "";
    }

    default Set<String> getSuffixes(){
        return ImmutableSet.of(getSuffix());
    }
```

```java
public class FreemarkerViewRenderer implements ViewRenderer {
    @Override
    public Set<String> getSuffixes() {
        return ImmutableSet.of(".ftl", ".ftlh", "ftlx");
    }
}
```

```java
public class ViewBundle extends ConfigurableBundle {
    @Override
    public void run(T configuration, Environment environment) throws Exception {
        Map<String, Map<String, String>> options = getViewConfiguration(configuration);
        for (ViewRenderer viewRenderer : viewRenderers) {
            for (Map.Entry<String, Map<String, String>> entry : options.entrySet()) {
                if (viewRenderer.getSuffixes().contains(entry.getKey())) {
                    viewRenderer.configure(entry.getValue());
                    break;
                }
            }
        }
    }
}
```

**Comment by FredDeschenes** [comment]
@arteam : This works but we risk having people overwriting their configuration if they decide to have let's say a `.ftl` key and a `.ftlh` key (whichever is second in `getSuffixes` would take precedence). We could also just document it properly if you think that's enough (most people would probably never run into this "issue" anyway).

We could also have `FreemarkerViewRenderer.configure` log a warning that the configuration is being set twice or attempt to merge both configs.

**Comment by FredDeschenes** [comment]
After reading a bit more about these extensions in Freemarker's documentation ([here](https://freemarker.apache.org/docs/dgui_misc_autoescaping.html) and [here](https://freemarker.apache.org/docs/pgui_config_outputformatsautoesc.html)), it seems that the feature requires Freemarker >= 2.3.24, whereas Dropwizard uses 2.3.23 ([which seems like it's the latest version before it became an incubating Apache project](https://search.maven.org/#search%7Cgav%7C1%7Cg%3A%22org.freemarker%22%20AND%20a%3A%22freemarker%22), but is over 2 years old). Should I take this opportunity to update to the latest 2.3.27-incubating version (everything appears to be working at first glance after the update)?

**Comment by ddekany** [comment]
Definitely update FreeMarker regardless of this issue. The incubating status has nothing to do with code stability/maturity; it's purely a branding/political thing. So using 2.3.23 makes as much sense as using any other random older version.

**Comment by ddekany** [comment]
@arteam: Note that it's not an exactly correct assumption that you only have to look at the file extension. It's mostly true, yes. But just consider `foo.ftl.html` (and I have seen it with non-FreeMarker templates as well). So regular expressions matched against the whole file name are better.

**Comment by arteam** [comment]
I am all for updating Freemaker. After some thinking, I do think a regex would be a better option. Maybe it makes sense to rename the `getSuffix` method to `getConfigurationKey` and then add a new method which will specify a regex for matching views. Unfortunately, it will break third-party views (if there any), but I think it's a reasonable trade-off for the 1.3 version. We can update the Mustache renderer which is shipped with Dropwizard.

**Comment by FredDeschenes** [comment]
Alright I'll go ahead and look at this this afternoon.

Just to recap:
- Update Freemarker and Mustache to latest versions
- Change `getSuffix` to `getConfigurationKey` (with `mustache` and `freemarker` as keys)
- Use regexes in `isRenderable` to match file names
- Update documentation

Anything else I missed?

**Comment by arteam** [comment]
Sound like a plan.
