### ISSUE TITLE
Timers with exponentially-decaying reservoirs

### ISSUE THREAD

**Issue by LukaszP1** [dropwizard/dropwizard#2212]
I've used Timers for meter API calls with different frequency which is chaging over time. I faced up problem with some metrics with low calls count, that old metrics are kept for very long time. In result, graphs in Graphite show inaccurate values - old ones.
The problem has been described in this article "Don’t use Timers with exponentially-decaying reservoirs in Graphite' (http://taint.org/2014/01/16/145944a.html).

Author said that:

>  In reality, if the frequency of updates to such a timer drops off, it could take a lot longer, and if you stop updating a timer which uses this reservoir type, it’ll never decay at all. The GraphiteReporter will dutifully capture the percentiles, min, max, etc. from that timer’s reservoir every minute thereafter, and record those to Graphite using the current timestamp — even though the data it was derived from is becoming more and more ancient.

Workaround suggested by author is:

> What we eventually did in our code was to use this Reporter class instead of GraphiteReporter; it clears all Timer metrics’ reservoirs after each write to Graphite. This is dumb and dirty, reaching across logical class boundaries, but at the same time it’s simple and comprehensible behaviour: with this, we can guarantee that the percentile/min/max data recorded at timestamp T is measuring events in that timestamp’s 1-minute window — not any time before that. This is exactly what you want to see in a time-series graph like those in Graphite, so is a very valuable feature for our metrics, and one that others have noted to be important in comparable scenarios elsewhere.

What is your reccomendation to deal with such problem?

**Comment by LukaszP1** [comment]
@joschi  Yes, you're right. L'm sorry - I'm new on github.
Is it possible to move this issue, or should I close this issue and open another in https://github.com/dropwizard/metrics ?

**Comment by joschi** [comment]
This issue was moved to dropwizard/metrics#1223
