### ISSUE TITLE
How to integrate i18n with dropwizard

### ISSUE THREAD

**Issue by Ryan-Miao** [dropwizard/dropwizard#2214]
Hi guys, we just use dropwizard in our project(expedia-epc). We have a problem to integrate i18n with dropwizard. 

We try just use `java.util.ResourceBundle` directly, but there seems lots of work we have to do.  We may want like use the i18n liken spring `ResourceBundleMessageSource`

Is there any official document about i18n usage with dropwizard?

**Comment by nickbabcock** [comment]
My knowledge is spotty, but I have an idea. Are you using [Dropwizard Views](http://www.dropwizard.io/1.2.0/docs/manual/views.html)? Currently only Freemarker supports builtin i18n, but one can implement their own `ViewRenderer` and Dropwizard will parse out the `Accept-Language` header and pass in the `Locale` where you can `ResourceBundle` as one normally would.

**Comment by arteam** [comment]
Yeah, I would use the same idea. I think [Trimou](https://github.com/trimou/trimou) also supports i18n and they have a Dropwizard integration: https://github.com/trimou/trimou/blob/master/extensions/dropwizard/src/test/java/org/trimou/dropwizard/views/TrimouViewRendererTest.java

**Comment by Ryan-Miao** [comment]
@nickbabcock Thank you,  I didn't make it clear before. I just want a Java side MessageResource, such as Spring MessageSource. 

I have finished it by just copy the Spring MessageResource. Here is my solution: [easy-i18n](https://github.com/Ryan-Miao/easy-i18n), and I have integrated it with my test:   https://github.com/Ryan-Miao/l4dropwizard/blob/master/src/main/java/com/test/domain/resource/LocalResource.java

**Comment by Ryan-Miao** [comment]
@arteam Thank you! It's very happy to hear the solution for view render. Currently, we just use Dropwizard as a web service. Maybe consider rendering page in the future.
