### ISSUE TITLE
High memory consumption in multi-core environment

### ISSUE THREAD

**Issue by aschilling** [dropwizard/dropwizard#2224]
Hi everybody,

first of all thank you all for your great work and your contributions!
I noticed that dropwizard consumes on average 3x more memory on a multi-cpu architecture than on my local machine. I already debugged this behavior a little bit and noticed that there are also 66 threads running on the remote server. Can you explain this behavior? Is it possible that Drowpwizards scales the number of threads and memory based on the current number of CPUs? Is there any way to adjust this behavior and scale down the memory consumption of Dropwizard.

I use Dropwizard in a Kubernetes environment so that Kubernetes can scale up itself it a high number of requests come in.

For the record I am using Dropwizard Version 1.1.2

Thank you
Andy

**Comment by nickbabcock** [comment]
Hey Andy. Off the top of my head I know that Jetty's acceptor and selector threads are based on the number of CPUs. You can [modify these](http://www.dropwizard.io/1.2.2/docs/manual/configuration.html) as necessary. You can also adjust the number of threads Dropwizard uses to service requests with `minThreads` and `maxThreads`

**Comment by arteam** [comment]
Yes, acceptor and selector threads are the most obvious culprit. Could you take a thread dump from the remote server and see what kind of threads are present?

**Comment by nickbabcock** [comment]
Closing due to lack of information. Feel free to provide new information to continue the discussion.
