### ISSUE TITLE
'@CacheControl' annotation can be added to types and methods, but only works on methods

### ISSUE THREAD

**Issue by FredDeschenes** [dropwizard/dropwizard#2226]
As the title says, the [`@CacheControl`](https://github.com/dropwizard/dropwizard/blob/master/dropwizard-jersey/src/main/java/io/dropwizard/jersey/caching/CacheControl.java#L15) annotation defines the 'TYPE' and 'METHOD' targets, but [`CacheControlledResponseFeature`](https://github.com/dropwizard/dropwizard/blob/master/dropwizard-jersey/src/main/java/io/dropwizard/jersey/caching/CacheControlledResponseFeature.java#L20) only checks if the annotation is present on methods. Should it work for both methods and types or only methods?

**Comment by arteam** [comment]
It's intended only for methods. I don't think it makes much sense to use it for resources, because they typically contain methods with different caching behaviors (a mix of GET and POST/PUT requests).

**Comment by FredDeschenes** [comment]
Yeah that's what I figured, thanks for the quick fix!
