### ISSUE TITLE
io.dropwizard.jersey.jsr310 is missing a ParamConverterProvider

### ISSUE THREAD

**Issue by bryanrcampbell** [dropwizard/dropwizard#2227]
I noticed that the dropwizard-jersey module has AbstractParam impls for the major java.time classes but does not have a ParamConverterProvider for those classes. Was it intentionally left out to encourage the usage of the AbstractParam directly or is this something that dw users should be expected to implement themselves.

Here's a few examples using a LocalDate QueryParam.

Using a custom ParamConverterProvider...
```
    @GET
    @Path("doSomething")
    public TestResponseObject @QueryParam("checkinDate") final LocalDate checkinDate) {
        ....
    }
```

Using an LocalDateParam...
```
    @GET
    @Path("doSomething")
    public TestResponseObject @QueryParam("checkinDate") final LocalDateParam checkinDate) {
        ....
    }
```

**Comment by nickbabcock** [comment]
I don't recall a reason why a `ParamConverterProvider` is missing for those. Probably an oversight. Did you want to take a crack at implementing it?
