### ISSUE TITLE
Tasks - Error's being logged as WARN

### ISSUE THREAD

**Issue by fipp** [dropwizard/dropwizard#2233]
The `io.dropwizard.servlets.tasks.TaskServlet.doPost()` method only catches `Exception`, not `Error`. So when an `AssertionError` is thrown for instance, it is handled by `org.eclipse.jetty.server.HttpChannel.handleException()`, which logs it as `WARN`.

I find it a bit strange that `Exceptions` in a DropWizard task are logged with level `ERROR`, whilst `Error` throwables are logged with level `WARN`. Intentional?

**Comment by nickbabcock** [comment]
Can you describe a scenario where an `AssertionError` is thrown?

**Comment by fipp** [comment]
I used it to verify that some variables was not null on a object (`assert foo.bar != null && foo.spam != null`), in a task that iterated over these objects and performed HTTP requests to a remote REST API.

After reading up on what AssertionError should actually be used for, I've changed my logic to throw an Exception instead.

But isn't that besides the point? If the code used in a task throws an Error, shouldn't it be logged a bit more aggressively than a WARN? I'd argue that an Error is more serious than a Exception, which is logged as ERROR?

**Comment by nickbabcock** [comment]
> But isn't that besides the point? If the code used in a task throws an Error, shouldn't it be logged a bit more aggressively than a WARN? I'd argue that an Error is more serious than a Exception, which is logged as ERROR?

The angle I was coming from were errors are so serious should they even be caught, logged, and responded to? But since `LoggingExceptionMapper` essentially catches `Throwable` -- to be consistent one would expect tasks to behave the same way.

So feel free to update `TaskServlet` with the appropriate code 😄

**Comment by fipp** [comment]
Perhaps Errors can be caught, logged (as ERROR), and rethrown? I'll make a suggestion in a PR. 

Thanks for your input!
