### ISSUE TITLE
dropwizard-jdbi creating query with concat generate NullPointerException

### ISSUE THREAD

**Issue by grugna** [dropwizard/dropwizard#2237]
this query works fine:
"SELECT cd.display_name AS name
        FROM city_dct as cd 
        WHERE cd.display_name LIKE :partialName"

this query does not:
"SELECT cd.display_name AS name, concat('-',cd.city_cd) AS dbIDMultiKey 
        FROM city_dct as cd 
        WHERE cd.display_name LIKE :partialName"

I attached the stack trace, the exception is thrown inside the rosettamapper, but I debugged it and the problem is when the metadata is generated the tableName and the other metadata attribute for the select concat are null.

<img width="912" alt="screen shot 2017-12-28 at 7 58 49 pm" src="https://user-images.githubusercontent.com/11066420/34425069-16bfc1e6-ec29-11e7-9390-1f15e3dae4b5.png">

**Comment by joschi** [comment]
@grugna Please provide a minimal example with (vanilla) Dropwizard or file an issue in the repository for Rosetta: https://github.com/HubSpot/Rosetta

**Comment by joschi** [comment]
Closed in favor of HubSpot/Rosetta#50.
