### ISSUE TITLE
Unable to validate nested configs via annotations

### ISSUE THREAD

**Issue by alexplischke** [dropwizard/dropwizard#2241]
Let's say that I have a main config as such:

``` java
public class MyLovelyConfig extends Configuration {

  @NotNull
  @JsonProperty("mongoDB")
  private MongoDBConfig mongoDBConfig;
}
```

Upon service start, Dropwizard validates this property 'mongoDB 'and spits out the corresponding error if it was indeed null. Works as advertised, great!

Now, what's MongoDBConfig? It's another nested config.

``` java
public class MongoDBConfig {
  
  @NotNull
  @JsonProperty
  private List<String> nodes;
}
```

Now, if the 'nodes' here are not specified in the config, I was expecting an error message as well. Except I am not getting any. I tried it again with MongoDBConfig extending the Configuration class, but the result was still the same.

Is a nested config validation simply not supported (yet)?

EDIT:

I dug a little further and it looks like this feature is not supported when I look at the following method:
io.dropwizard.configuration.BaseConfigurationFactory#validate

``` java
    private void validate(String path, T config) throws ConfigurationValidationException {
        if (validator != null) {
            final Set<ConstraintViolation<T>> violations = validator.validate(config);
            if (!violations.isEmpty()) {
                throw new ConfigurationValidationException(path, violations);
            }
        }
    }
```
Essentially only the main config is validated. I don't see Java's Validator performing nested lookups.

Would it be possible to request this as a feature for Dropwizard?

**Comment by nickbabcock** [comment]
Have you tried adding `Valid` annotation to `MongoDBConfig`?

**Comment by alexplischke** [comment]
I did not! 👍 

Awesome, that worked. Thanks a lot!
