### ISSUE TITLE
DropwizardResourceConfig not logging Interface Resources

### ISSUE THREAD

**Issue by frederic-h** [dropwizard/dropwizard#2244]
Why are Interface Resources not logged on startup?

Line of code in question:
https://github.com/dropwizard/dropwizard/blob/502fd326041787f25190338f56365409a01567b0/dropwizard-jersey/src/main/java/io/dropwizard/jersey/DropwizardResourceConfig.java#L131

**Comment by nickbabcock** [comment]
I believe it is because one is supposed to register the implementing resources and when logged, the lines include the info from the interface.

pseudo-code:

```java
@Path("/another")
public static interface ResourceInterface {
    @GET
    public String bar();
}

public static class ImplementingResource implements ResourceInterface {
    @Override
    public String bar() {
        return "";
    }
}

env.jersey().register(new ImplementingResource())
```

logs

> GET     /another (ImplementingResource)

**Comment by frederic-h** [comment]
While that works my scenario looks a little different. I am registering the interface and have the underlying HK2 (over a bridge to Weld) resolve the actual (or mock for tests) implementation.

**Comment by joschi** [comment]
@frederic-h Could you please provide a minimal project to reproduce the issue and describe what you'd expect Dropwizard to behave?

**Comment by frederic-h** [comment]
@joschi https://github.com/frederic-h/dw-interfaces-log

**Expected Log**
```
INFO  [2018-02-05 09:12:58,784] io.dropwizard.jersey.DropwizardResourceConfig: The following paths were found for the configured resources:

    GET     /extra (service.api.ExtraResource)
    GET     /hello (service.api.HelloResource)
    
```

**Actual Log**
```
INFO  [2018-02-05 09:13:43,298] io.dropwizard.jersey.DropwizardResourceConfig: The following paths were found for the configured resources:

    GET     /extra (service.api.ExtraResource)

```
