### ISSUE TITLE
Jersey declarative-linking `@InjectLink` is not initialized

### ISSUE THREAD

**Issue by novaterata** [dropwizard/dropwizard#2252]
This is a Kotlin project, so attribute injected fields are `lateinit var`:
```kotlin
    @InjectLink(resource = FooResource::class)
    lateinit var foo: URI
```
which is the equivalent of:
```java
    @InjectLink(resource = FooResource.class)
    URI foo;
```
This behavior happens in both the latest 1.3.0-rc4 and 1.2.0
I've included the 1.25.1 version of declarative-linking in my gradle dependencies
I no longer get the class not found errors and I've registered

I have this in my run method:
```kotlin
        val jersey = environment.jersey()
        
        val resourceConfig = jersey.resourceConfig
                .packages(javaClass.`package`.name)
        resourceConfig
                .register(DeclarativeLinkingFeature::class)
```

But the InjectLink fields are ignored.
I'm filing this here, because based on everything I've read online, including mutliple examples with dropwizard, this should work.

**Comment by novaterata** [comment]
Really, I just want to know the recommended way of including HATEOAS links to resources in entities. We have singleton resources in a nested topology that is incompatible with stuff like JSON.API that require everything to be a collection of stuff with ids. I'm frankly baffled that my problem is so unique

**Comment by arteam** [comment]
Hm, I don't think you need to enable scanning for the package where the representation class is located.I think you can just enable `DeclarativeLinkingFeature` on the resource config returned by `environment.jersey()`. If Jersey still doesn't pick up the annotation, I would point breakpoints to `ResponseLinkFilter` and `HeaderProcessor` and run the app in the debug mode. Maybe there's some issue in annotation scanning for classes generated by the Kotlin compiler.

**Comment by novaterata** [comment]
I did try just registering on the main jersey(),  thanks for the debug tips

**Comment by novaterata** [comment]
The problem was the use of `DeclarativeLinkingFeature::class` instead of `DeclarativeLinkingFeature()`, for some reason using either a KClass or adding `.java` and getting the Class does not register the feature. Only passing the feature as an instance works.
