### ISSUE TITLE
Using maven-jlink-plugin with Dropwizard 1.3.0rc5 fails due to transitive dependencies

### ISSUE THREAD

**Issue by rbjorklin** [dropwizard/dropwizard#2255]
Tried building the `dropwizard-example` repo with the [maven-jlink-plugin](https://maven.apache.org/plugins/maven-jlink-plugin/) out of curiosity and it fails with:

`[ERROR] Failed to execute goal org.apache.maven.plugins:maven-jlink-plugin:3.0.0-alpha-1:jlink (default-jlink) on project dropwizard-example: The given dependency ~/.m2/repository/org/jboss/spec/javax/transaction/jboss-transaction-api_1.2_spec/1.0.1.Final/jboss-transaction-api_1.2_spec-1.0.1.Final.jar does not have a module-info.java file. So it can't be linked. -> [Help 1]`

This seems to be a transitive dependency:

    mvn dependency:tree
    [INFO] +- io.dropwizard:dropwizard-hibernate:jar:1.3.0-rc5-SNAPSHOT:compile                               
    [INFO] |  +- io.dropwizard:dropwizard-db:jar:1.3.0-rc5-SNAPSHOT:compile                                   
    [INFO] |  |  \- org.apache.tomcat:tomcat-jdbc:jar:8.5.24:compile                                          
    [INFO] |  |     \- org.apache.tomcat:tomcat-juli:jar:8.5.24:compile                                       
    [INFO] |  +- com.fasterxml.jackson.datatype:jackson-datatype-hibernate5:jar:2.9.3:compile                 
    [INFO] |  +- com.github.arteam.jadira:usertype.core:jar:6.0.1.GA-jdk9:compile                             
    [INFO] |  |  +- org.hibernate:hibernate-entitymanager:jar:5.2.1.Final:compile                             
    [INFO] |  |  \- com.github.arteam.jadira:usertype.spi:jar:6.0.1.GA-jdk9:compile                                                                                                                                      
    [INFO] |  \- org.hibernate:hibernate-core:jar:5.2.12.Final:compile                                        
    [INFO] |     +- org.hibernate.javax.persistence:hibernate-jpa-2.1-api:jar:1.0.0.Final:compile             
    [INFO] |     +- antlr:antlr:jar:2.7.7:compile                                                             
    [INFO] |     +- org.jboss.spec.javax.transaction:jboss-transaction-api_1.2_spec:jar:1.0.1.Final:compile

Which seems to have [fixed the problem](https://github.com/jboss/jboss-transaction-api_spec/pull/5) and made a new release with the tag `jboss-transaction-api_1.2_spec-1.1.1.Final`.

Is this something dropwizard want to fix before making an official 1.3.0 release?

**Comment by rbjorklin** [comment]
Created an issue in the [hibernate issue tracker](https://hibernate.atlassian.net/browse/HHH-12270) for this.

**Comment by arteam** [comment]
We could exclude `jboss-transaction-api_1.2_spec` from the Hibernate dependency and declare a new version with the `Automatic-Module-Name` tag in the manifest file. I think we can wait for a response from the Hibernate guys. If they won't make a new release, we will fix it on our side.
