### ISSUE TITLE
Update AbstractDAO to use JPA CriteriaQuery API

### ISSUE THREAD

**Issue by ramsrib** [dropwizard/dropwizard#2259]
Hibernate's Criteria API (org.hibernate.Criteria) was deprecated and the dropwizard's AbstractDAO class was using that API. It also causes logs to be flooded with this warning.

`WARN org.hibernate.orm.deprecation: HHH90000022: Hibernate's legacy org.hibernate.Criteria API is deprecated; use the JPA javax.persistence.criteria.CriteriaQuery instead`

Is there any plans to refactor AbstractDAO to use JPA Criteria API?

**Comment by arteam** [comment]
You can use the `criteriaQuery` method on `AbstractDao` to access the JPA Criteria API. Maybe we should mark the `criteria` method as deprecated,

**Comment by ramsrib** [comment]
>> Maybe we should mark the criteria method as deprecated,
That would be better.

**Comment by arteam** [comment]
Can you use `currentSession().getCriteriaBuilder()`?

**Comment by ramsrib** [comment]
yeah, I started using currentSession() to build my queries. I feel Criteria Builder is too verbose (too many lines) to build simple queries. 

Is there a way to build a typed query against hibernate entities without using Criteria Builder?

**Comment by scottaj** [comment]
As far as the OT question goes: 

We ran into this. We've started using typed HQL queries instead of the new criteria API wherever possible and have had really good results from that.

**Comment by nickbabcock** [comment]
Looks like the original question has been answered! Respond back if that's not the case.
