### ISSUE TITLE
Dropwizard 1.3.0rc5 fails with UnsupportedClassVersionError on Java 8

### ISSUE THREAD

**Issue by ramsrib** [dropwizard/dropwizard#2261]
It seems like Dropwizard 1.3.0rc5 is compiled with JDK 9 and it's failing on JDK 8. Not sure whether it's intentional or not.

> Exception in thread "main" java.lang.UnsupportedClassVersionError: io/dropwizard/Application has been compiled by a more recent version of the Java Runtime (class file version 53.0), this version of the Java Runtime only recognizes class file versions up to 52.0
> 	at java.lang.ClassLoader.defineClass1(Native Method)

**Comment by arteam** [comment]
Thank you for reporting it! It looks we indeed released 1.0.5 build against JDK 9. I will release 1.0.6 build with JDK 8 and change the build profile, so even the build machine always compiles Dropwizard with the 1.8 target.

**Comment by arteam** [comment]
1.3.0-rc6 has been released. Please check it out:

* https://github.com/dropwizard/dropwizard/releases/tag/v1.3.0-rc6
* http://central.maven.org/maven2/io/dropwizard/dropwizard-core/1.3.0-rc6/dropwizard-core-1.3.0-rc6.pom

**Comment by ramsrib** [comment]
Thanks!.. 1.3.0-rc6 fixed the issue.
