### ISSUE TITLE
ProxyServlet does not set Content-Length correctly for gzipped content

### ISSUE THREAD

**Issue by jplace** [dropwizard/dropwizard#2268]
I have a Dropwizard application that uses a Jetty ProxyServlet to forward HTTP traffic. This works great when the HTTP traffic is not gzipped. When the HTTP traffic is gzipped, the proxy forwards a bad HTTP request.

The problem appears to be that when Dropwizard receives a gzipped HTTP request, the BiDiGzipHandler processes the request before the ProxyServlet. When the BiDiGzipHandler runs, it decompresses the payload and strips the `Content-Encoding: gzip` header. It does not modify the `Content-Length` header to reflect the length of the decompressed payload. When the ProxyServlet processes the request, it blindly copies the now incorrect `Content-Length` header (that reflects the length of the gzipped payload). It forwards the decompressed payload as the body though. When the request is received, you can see that the `Content-Length` does not reflect the length of the actual HTTP body.

I set up a simple test to demonstrate the problem.

I am running Dropwizard 1.0.0. I configured a ProxyServlet to forward all HTTP traffic matching the _/echo_ path.

```
// Register echo proxy
ServletRegistration echoServletRegistration =
    environment.servlets().addServlet("EchoServlet", new ProxyServlet.Transparent());
echoServletRegistration.addMapping("/echo/*");
echoServletRegistration.setInitParameter("prefix", "/echo");
echoServletRegistration.setInitParameter(
    "proxyTo", "http://localhost:47899");
```

I CURLed a normal HTTP POST to Dropwizard and used netcat to print what the proxy forwarded:

_test.sh_
```
#!/bin/bash

curl --data '@data.txt' \
     -H "Content-Type: application/json" \
     -X POST \
     http://localhost:8080/echo
```

_data.txt_ (length 19 bytes)
```
Hello, Dropwizard!
```

_netcat output_
```
$ nc -l 47899
POST / HTTP/1.1
User-Agent: curl/7.57.0
Accept: */*
Content-Type: application/json
Via: http/1.1 Jordans-MacBook-Pro.local
X-Forwarded-For: 127.0.0.1
X-Forwarded-Proto: http
X-Forwarded-Host: localhost:8080
X-Forwarded-Server: 127.0.0.1
Host: localhost:47899
Content-Length: 18

Hello, Dropwizard!
```

You can see the problem when I did the same thing gzipped.

_gzip-test.sh_
```
#!/bin/bash

curl --data-binary '@data.txt.gz' \
     -H "Content-Type: application/json" \
     -H "Content-Encoding: gzip" \
     -X POST \
     http://localhost:8080/echo
```

_data.txt.gz_ (length 48 bytes)
```
ã∫Ù}Zdata.txtÛHÕ……◊Qp) /(œ¨J,JQ‰}9¡∂
```

_netcat output_
```
$ nc -l 47899
POST / HTTP/1.1
User-Agent: curl/7.57.0
Accept: */*
Content-Type: application/json
Via: http/1.1 Jordans-MacBook-Pro.local
X-Forwarded-For: 127.0.0.1
X-Forwarded-Proto: http
X-Forwarded-Host: localhost:8080
X-Forwarded-Server: 127.0.0.1
Host: localhost:47899
Content-Length: 48

Hello, Dropwizard!
```

I'm not really sure how to proceed. I think what I'd like is to remove the BiDiGzipHandler from the filter chain so the proxy just passes along the gzipped payload. Alternatively, I'm fine with passing the unzipped payload through the proxy if that's easier.

Is this a bug? Is there a work around in the meantime?

Thank you for all your help!

**Comment by arteam** [comment]
Thank you for reporting this! 

First, you can disable request compression and decompression in the application configuration: http://www.dropwizard.io/1.2.2/docs/manual/configuration.html#gzip.  Unfortunately, we don't have option to disable only decompression. 

Second, it indeed looks like a bug in `BiDiGzipHandler`. It seems reasonable that it should strip the `Content-Length` header from the request and return -1 in its `getContentLength` method, because the actual content is generated dynamically. This way, the request can proxied like a chunked request.

**Comment by jplace** [comment]
Wow, thanks for the prompt response!

For others out there:

I resolved to disable gzip for the entire Dropwizard app, then register a `GZipEncoder` with just my Jersey servlet.

```
environment.jersey().register(GZipEncoder.class);
```

This lets me support gzip in my Jersey resources, but avoid gzip in my proxy servlet.
