### ISSUE TITLE
Form parameters missing from Jersey client when gzip compression enabled.

### ISSUE THREAD

**Issue by aedwards-act** [dropwizard/dropwizard#2280]
When I make a web request, using the suggested Jersey client builder, to submit an urlencoded form, I get a 400 response back from my target telling me expected fields are missing

e.g.

```
final Entity<Form> form = Entity.form(
                new Form()
                        .param( "grant_type", "client_credentials" )
                        .param( "client_id", config.getConsumerKey() )
                        .param( "client_secret", config.getConsumerSecret() ) );

new JerseyClientBuilder(environment).using(config.getJerseyClientConfiguration())
                                                              .build(getName())
                                                              .target(config.getOauthAuthenticationAddress())
                                                              .post( form, String.class );
```

Causes a 400 response, 'missing parameter grant_type'

However making the same request from a client constructed using the default javax client builder works, as does disabling Gzip in the jersey client configuration e.g.
```
final JerseyClientConfiguration jerseyClientConfiguration = new JerseyClientConfiguration();
jerseyClientConfiguration.setGzipEnabledForRequests( false );
```

This is using version 1.2.2 of drop-wizard.

**Comment by aedwards-act** [comment]
There was a similar issue raised previously https://github.com/dropwizard/dropwizard/issues/1935 it was closed as their were integration tests proving the behavior works, however they only seem to test posting application/json
https://github.com/dropwizard/dropwizard/blob/master/dropwizard-client/src/test/java/io/dropwizard/client/JerseyClientIntegrationTest.java#L208

**Comment by arteam** [comment]
Thanks for reporting this. I wrote a unit test of posting a compressed form and it looks like the client works correctly:
```java
httpServer.createContext("/form", httpExchange -> {
            try {
                Headers requestHeaders = httpExchange.getRequestHeaders();
                assertThat(requestHeaders.getFirst(HttpHeaders.CONTENT_TYPE)).isEqualTo("application/x-www-form-urlencoded");
                assertThat(requestHeaders.getFirst(HttpHeaders.CONTENT_ENCODING)).isEqualTo(GZIP);
                assertThat(requestHeaders.getFirst(HttpHeaders.ACCEPT_ENCODING)).isEqualTo(GZIP_DEFLATE);
                System.out.println(CharStreams.toString(new InputStreamReader(new GZIPInputStream(httpExchange.getRequestBody()))));
                httpExchange.sendResponseHeaders(200, 0);
                httpExchange.getResponseBody().write("OK".getBytes());
            } finally {
                httpExchange.close();
            }
        });
        httpServer.start();

        Client client = new JerseyClientBuilder(new MetricRegistry())
            .using(Executors.newSingleThreadExecutor(), JSON_MAPPER)
            .build("test-form-post");
        Response result = client
            .target("http://localhost:" + httpServer.getAddress().getPort() + "/form")
            .request()
            .post(Entity.form(new Form()
                .param("grant_type", "client_credentials")
                .param("client_id", "tomas")
                .param("client_secret", "pa$$")));
        System.out.println(result.getStatus());
        System.out.println(result.readEntity(String.class));
        client.close();
```

Are you sure that the server supports compressed POST requests?

**Comment by aedwards-act** [comment]
I believe it is, but I'm not certain. I will try to find out.
I would have expected a 415 response from the server if it was not supported.

**Comment by aedwards-act** [comment]
@arteam I notice in your unit test that you're not asserting the form parameters, but you seem to be printing them out? I assume you were using the printout to verify that the form parameters were correct?

**Comment by arteam** [comment]
Right, I just verified that it prints correct data by taking a look on it.

**Comment by aedwards-act** [comment]
Issue seems to be that the server we're talking to doesn't support gzip encoding and doesn't handle it gracefully. Closing issue.
