### ISSUE TITLE
Add support to configure SessionDataStore

### ISSUE THREAD

**Issue by ramsrib** [dropwizard/dropwizard#2281]
As of now, there is no way to configure the SessionDataStore in dropwizard. Though jetty provides some useful implementation of SessionDataStore (like jdbc, file & etc), dropwizard doesn't allow these configurations.

It will be really useful, if dropwizard adds support for this.

**Comment by arteam** [comment]
Thanks for the proposal! If I'm not mistaken sessions are usually considered as an anti-pattern in REST backend systems because of scalability and state management issues. But I guess there are users who are willing to use Dropwizard in a more classic approach with session cookies instead of bearer tokens.

**Comment by ramsrib** [comment]
yeah, sometimes sessions are useful too. Anyways, I looked at the DefaultServerFactory to include option to configure SessionDataStore.  I'm not successful with that, any suggestions or hacks to enable `session-store-jdbc` jetty module in dropwizard?

**Comment by brentryan** [comment]
You can see how we got sessions working with couchbase at Cvent here https://github.com/cvent/dropwizard-couchbase-sessions

You can do the same thing with jdbc or any other session backed system you need to implement.

**Comment by asamaraw** [comment]
@ramsrib, you can achieve this using JDBCSessionDataStore in Dropwizard 1.2.2.

**Comment by ramsrib** [comment]
@asamaraw How do you use JDBCSessionDataStore with dropwizard? I couldn't find any example.

**Comment by asamaraw** [comment]
@ramsrib, here you go https://gist.github.com/asamaraw/7cce23eb76cc06eba9ffef4033bf415f
