### ISSUE TITLE
Release notes not updated with 1.2.2, 1.2.3 and 1.2.4

### ISSUE THREAD

**Issue by lazee** [dropwizard/dropwizard#2282]
No release notes for the latest 1.2.x version?

https://github.com/dropwizard/dropwizard/blob/master/docs/source/about/release-notes.rst

**Comment by arteam** [comment]
Thanks for reminding it to upgrade the website! In the meantime you can take a look at the release notes at the GitHub releases page:
* https://github.com/dropwizard/dropwizard/releases/tag/v1.2.2
* https://github.com/dropwizard/dropwizard/releases/tag/v1.2.3
* https://github.com/dropwizard/dropwizard/releases/tag/v1.2.4

**Comment by jplock** [comment]
Working on a PR for this, will submit it shortly.
