### ISSUE TITLE
Include OWASP dependency check for vulnerabilities as part of standard build

### ISSUE THREAD

**Issue by 1605200517** [dropwizard/dropwizard#2295]
It would be great to have a report for vulnerabilities as part of the Dropwizard build.

https://github.com/jeremylong/DependencyCheck

**Comment by joschi** [comment]
@1605200517 Care to create a pull request for that?

**Comment by 1605200517** [comment]
@joschi thanks for anticipating this proposal -   I would like to, there is not much to do, I am not just sure where (to which build profile) to add this one:

```
<plugin>
	<groupId>org.owasp</groupId>
	<artifactId>dependency-check-maven</artifactId>

	<configuration>
		<format>ALL</format>
	</configuration>
	<executions>
		<execution>
			<goals>
				<goal>check</goal>
			</goals>
		</execution>
	</executions>
</plugin>
```

**Comment by joschi** [comment]
@1605200517 Please create a proper pull request. You don't have to put the plugin into a specific Maven profile.

https://help.github.com/articles/about-pull-requests/

**Comment by 1605200517** [comment]
https://github.com/dropwizard/dropwizard/pull/2296

**Comment by 1605200517** [comment]
@joschi strange enough, locally it builds after enforced cache updates.
