### ISSUE TITLE
Issues with default JerseyClientBuilder

### ISSUE THREAD

**Issue by andrewoh531** [dropwizard/dropwizard#2302]
I've started using Dropwizard (1.2.4) recently and have been getting some weird behavior using the Jersey Client obtained through Dropwizard. I've followed the configuration steps from here (http://www.dropwizard.io/1.2.2/docs/manual/client.html#jersey-client) and have not overwritten any of the default configurations in my `.yml`. 

When I retrieve the client via Dropwizard's `JerseyClientBuilder` to make a request I get a 403 response return. When I retrieve the client via `javax.ws.rs.client.ClientBuilder` the request goes through fine.

I'm calling the downstream like:
```java

Order order = new Order(); 
// Set values within order (left out for readability)

client.target("https://sample.com")
            .path("/orders")
            .request()
            .header("Authorization", "XXX")
            .post(Entity.json(order));
```

Order is a simple POJO that looks like below with each of the classes within it being simple POJOs:
```java
public class Order {
    private Amount totalAmount;
    private Consumer consumer;
    private Merchant merchant;
    // Getters and setters for each of the variables above
}
```

The client is instantiated like below in `Application.run` with client1 getting 403 and client2 getting a successful response:
```java
final Client client1 = new JerseyClientBuilder(environment).using(configuration.getJerseyClientConfiguration()).build(getName());
final Client client2 = ClientBuilder.newBuilder().build();
```

Another funny behavior with the client instantiated through the `JerseyClientBuilder` is that when I convert the `order` object into a JSON string using `Jackson.newObjectMapper().writeValueAsString(order)` request fails. When the JSON string has `\n` characters via `Jackson.newObjectMapper().writerWithDefaultPrettyPrinter().writeValueAsString(order)` the request succeeds.

Is there a configuration I need to set somewhere or is this possibly a bug?

**Comment by arteam** [comment]
Thanks for the report! Could you enable debug logs, run the test again, and post the logs? Dropwizard's `JerseyClientBuilder` actually uses Apache HTTP Client which provides a lot of debug information about HTTP requests.

I think we have 2 separate issues: 
* `JerseyClientBuilder` presumably overwrites the `Authorization` header of your requests and you get a 403 error;
* For some reason the server you're connecting accepts only formatted JSON.

**Comment by andrewoh531** [comment]
Here are the debug logs below. I can see the `Authorization` being sent (value replaced for obvious reasons). The unformatted JSON works in POSTMAN so I don't think it's the server either. If there's anything you can point me to I'd appreciate it.

DEBUG [2018-03-13 20:53:27,844] org.apache.http.client.protocol.RequestAddCookies: CookieSpec selected: ignoreCookies
DEBUG [2018-03-13 20:53:27,849] org.apache.http.client.protocol.RequestAuthCache: Auth cache not set in the context
DEBUG [2018-03-13 20:53:27,851] com.codahale.metrics.httpclient.InstrumentedHttpClientConnectionManager: Connection request: [route: {s}->https://api-stg.Server.com:443][total kept alive: 0; route allocated: 0 of 1024; total allocated: 0 of 1024]
DEBUG [2018-03-13 20:53:27,876] com.codahale.metrics.httpclient.InstrumentedHttpClientConnectionManager: Connection leased: [id: 0][route: {s}->https://api-stg.Server.com:443][total kept alive: 0; route allocated: 1 of 1024; total allocated: 1 of 1024]
DEBUG [2018-03-13 20:53:27,878] org.apache.http.impl.execchain.MainClientExec: Opening connection {s}->https://api-stg.Server.com:443
DEBUG [2018-03-13 20:53:27,956] org.apache.http.impl.conn.DefaultHttpClientConnectionOperator: Connecting to api-stg.Server.com/104.17.109.19:443
DEBUG [2018-03-13 20:53:27,956] org.apache.http.conn.ssl.SSLConnectionSocketFactory: Connecting socket to api-stg.Server.com/104.17.109.19:443 with timeout 500
DEBUG [2018-03-13 20:53:28,130] org.apache.http.conn.ssl.SSLConnectionSocketFactory: Enabled protocols: [TLSv1, TLSv1.1, TLSv1.2]
DEBUG [2018-03-13 20:53:28,131] org.apache.http.conn.ssl.SSLConnectionSocketFactory: Enabled cipher suites:[TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256, TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256, TLS_RSA_WITH_AES_128_CBC_SHA256, TLS_ECDH_ECDSA_WITH_AES_128_CBC_SHA256, TLS_ECDH_RSA_WITH_AES_128_CBC_SHA256, TLS_DHE_RSA_WITH_AES_128_CBC_SHA256, TLS_DHE_DSS_WITH_AES_128_CBC_SHA256, TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA, TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA, TLS_RSA_WITH_AES_128_CBC_SHA, TLS_ECDH_ECDSA_WITH_AES_128_CBC_SHA, TLS_ECDH_RSA_WITH_AES_128_CBC_SHA, TLS_DHE_RSA_WITH_AES_128_CBC_SHA, TLS_DHE_DSS_WITH_AES_128_CBC_SHA, TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256, TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256, TLS_RSA_WITH_AES_128_GCM_SHA256, TLS_ECDH_ECDSA_WITH_AES_128_GCM_SHA256, TLS_ECDH_RSA_WITH_AES_128_GCM_SHA256, TLS_DHE_RSA_WITH_AES_128_GCM_SHA256, TLS_DHE_DSS_WITH_AES_128_GCM_SHA256, TLS_ECDHE_ECDSA_WITH_3DES_EDE_CBC_SHA, TLS_ECDHE_RSA_WITH_3DES_EDE_CBC_SHA, SSL_RSA_WITH_3DES_EDE_CBC_SHA, TLS_ECDH_ECDSA_WITH_3DES_EDE_CBC_SHA, TLS_ECDH_RSA_WITH_3DES_EDE_CBC_SHA, SSL_DHE_RSA_WITH_3DES_EDE_CBC_SHA, SSL_DHE_DSS_WITH_3DES_EDE_CBC_SHA, TLS_ECDHE_ECDSA_WITH_RC4_128_SHA, TLS_ECDHE_RSA_WITH_RC4_128_SHA, SSL_RSA_WITH_RC4_128_SHA, TLS_ECDH_ECDSA_WITH_RC4_128_SHA, TLS_ECDH_RSA_WITH_RC4_128_SHA, SSL_RSA_WITH_RC4_128_MD5, TLS_EMPTY_RENEGOTIATION_INFO_SCSV]
DEBUG [2018-03-13 20:53:28,131] org.apache.http.conn.ssl.SSLConnectionSocketFactory: Starting handshake
DEBUG [2018-03-13 20:53:28,269] org.apache.http.conn.ssl.SSLConnectionSocketFactory: Secure session established
DEBUG [2018-03-13 20:53:28,269] org.apache.http.conn.ssl.SSLConnectionSocketFactory:  negotiated protocol: TLSv1.2
DEBUG [2018-03-13 20:53:28,269] org.apache.http.conn.ssl.SSLConnectionSocketFactory:  negotiated cipher suite: TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
DEBUG [2018-03-13 20:53:28,269] org.apache.http.conn.ssl.SSLConnectionSocketFactory:  peer principal: CN=Server.com, O="CloudFlare, Inc.", L=San Francisco, ST=CA, C=US
DEBUG [2018-03-13 20:53:28,269] org.apache.http.conn.ssl.SSLConnectionSocketFactory:  peer alternative names: [Server.com, *.Server.com]
DEBUG [2018-03-13 20:53:28,269] org.apache.http.conn.ssl.SSLConnectionSocketFactory:  issuer principal: CN=CloudFlare Inc ECC CA-2, O="CloudFlare, Inc.", L=San Francisco, ST=CA, C=US
DEBUG [2018-03-13 20:53:28,273] org.apache.http.impl.conn.DefaultHttpClientConnectionOperator: Connection established 192.168.43.35:53818<->104.17.109.19:443
DEBUG [2018-03-13 20:53:28,273] org.apache.http.impl.conn.DefaultManagedHttpClientConnection: http-outgoing-0: set socket timeout to 500
DEBUG [2018-03-13 20:53:28,273] org.apache.http.impl.execchain.MainClientExec: Executing request POST /v1/orders HTTP/1.1
DEBUG [2018-03-13 20:53:28,273] org.apache.http.impl.execchain.MainClientExec: Proxy auth state: UNCHALLENGED
DEBUG [2018-03-13 20:53:28,276] org.apache.http.headers: http-outgoing-0 >> POST /v1/orders HTTP/1.1
DEBUG [2018-03-13 20:53:28,276] org.apache.http.headers: http-outgoing-0 >> Authorization: Basic SECRET
DEBUG [2018-03-13 20:53:28,276] org.apache.http.headers: http-outgoing-0 >> Content-Type: application/json
DEBUG [2018-03-13 20:53:28,276] org.apache.http.headers: http-outgoing-0 >> Content-Encoding: gzip
DEBUG [2018-03-13 20:53:28,276] org.apache.http.headers: http-outgoing-0 >> Transfer-Encoding: chunked
DEBUG [2018-03-13 20:53:28,276] org.apache.http.headers: http-outgoing-0 >> Host: api-stg.Server.com
DEBUG [2018-03-13 20:53:28,276] org.apache.http.headers: http-outgoing-0 >> Connection: Keep-Alive
DEBUG [2018-03-13 20:53:28,276] org.apache.http.headers: http-outgoing-0 >> User-Agent: Sample Server Integration (Sample Server Integration)
DEBUG [2018-03-13 20:53:28,276] org.apache.http.headers: http-outgoing-0 >> Accept-Encoding: gzip,deflate
DEBUG [2018-03-13 20:53:28,306] org.apache.http.wire: http-outgoing-0 >> "POST /v1/orders HTTP/1.1[\r][\n]"
DEBUG [2018-03-13 20:53:28,306] org.apache.http.wire: http-outgoing-0 >> "Authorization: Basic SECRET[\r][\n]"
DEBUG [2018-03-13 20:53:28,306] org.apache.http.wire: http-outgoing-0 >> "Content-Type: application/json[\r][\n]"
DEBUG [2018-03-13 20:53:28,306] org.apache.http.wire: http-outgoing-0 >> "Content-Encoding: gzip[\r][\n]"
DEBUG [2018-03-13 20:53:28,306] org.apache.http.wire: http-outgoing-0 >> "Transfer-Encoding: chunked[\r][\n]"
DEBUG [2018-03-13 20:53:28,306] org.apache.http.wire: http-outgoing-0 >> "Host: api-stg.Server.com[\r][\n]"
DEBUG [2018-03-13 20:53:28,306] org.apache.http.wire: http-outgoing-0 >> "Connection: Keep-Alive[\r][\n]"
DEBUG [2018-03-13 20:53:28,306] org.apache.http.wire: http-outgoing-0 >> "User-Agent: Sample Server Integration (Sample Server Integration)[\r][\n]"
DEBUG [2018-03-13 20:53:28,306] org.apache.http.wire: http-outgoing-0 >> "Accept-Encoding: gzip,deflate[\r][\n]"
DEBUG [2018-03-13 20:53:28,306] org.apache.http.wire: http-outgoing-0 >> "[\r][\n]"
DEBUG [2018-03-13 20:53:28,306] org.apache.http.wire: http-outgoing-0 >> "a[\r][\n]"
DEBUG [2018-03-13 20:53:28,306] org.apache.http.wire: http-outgoing-0 >> "[0x1f][0x8b][0x8][0x0][0x0][0x0][0x0][0x0][0x0][0x0][\r][\n]"
DEBUG [2018-03-13 20:53:28,308] org.apache.http.wire: http-outgoing-0 >> "b3[\r][\n]"
DEBUG [2018-03-13 20:53:28,308] org.apache.http.wire: http-outgoing-0 >> "[0x85][0x8e][0xc1][0xe][0x82]0[0xc][0x86][0xdf][0xa5]g[0x2][0x8b][0xf1]"'[0x89][0x9e]<p[0xe3][0x1][0xe6],B[0xc2]6[0xd2]u[0x12]Bxw;A[0xaf][0xee][0xd4][0xfe][0xfd][0xbe]v[0xb][0xb0]g=T[0xd6]G[0xc7]P.[0xa0][0xf7][\n]"
DEBUG [2018-03-13 20:53:28,308] org.apache.http.wire: http-outgoing-0 >> "[0xe]*?)[0xc8][0xc0]D"tf[0x96][0xa8]j[0xae][0xb0]J[0xe2]][0x88][0x16])[0xe1]c[0xe7][0x1d][0xd6][0xd1][0xde]S[0xb][0xea][0xa8][0xf6]'[0xe2][0xb3][0xa1][0xab][0xb5][0xc5] [0x93][0x9b]G[0x89]B$'[0x81][0xf4][0x97][0xef][0x8e][0xc][0xd0][0xea]~[0x90][0x88]1[0xf0]Y[0xb7][0x8c]4[0xea]97[0xde][0xa6][[0x82][0x98]No_#|[0xf4][0x84][0x86][0xc5]m{[0xb2][\r]%[0xab]c[0x1e]CY[0x14][0xd3]4[0xe5]_8[0xc9][0x85][0xd9](9[0xf0][0xf3][0xb4]38[0xfc][0xd3]>[0x10][0xac][0xeb][0x1b]U[0x92][0xaa][0xbc][0x1a][0x1][0x0][0x0][\r][\n]"
DEBUG [2018-03-13 20:53:28,308] org.apache.http.wire: http-outgoing-0 >> "0[\r][\n]"
DEBUG [2018-03-13 20:53:28,308] org.apache.http.wire: http-outgoing-0 >> "[\r][\n]"
DEBUG [2018-03-13 20:53:28,381] org.apache.http.wire: http-outgoing-0 << "HTTP/1.1 403 Forbidden[\r][\n]"
DEBUG [2018-03-13 20:53:28,381] org.apache.http.wire: http-outgoing-0 << "Date: Tue, 13 Mar 2018 20:53:35 GMT[\r][\n]"
DEBUG [2018-03-13 20:53:28,381] org.apache.http.wire: http-outgoing-0 << "Content-Type: text/html; charset=UTF-8[\r][\n]"
DEBUG [2018-03-13 20:53:28,381] org.apache.http.wire: http-outgoing-0 << "Transfer-Encoding: chunked[\r][\n]"
DEBUG [2018-03-13 20:53:28,381] org.apache.http.wire: http-outgoing-0 << "Connection: keep-alive[\r][\n]"
DEBUG [2018-03-13 20:53:28,381] org.apache.http.wire: http-outgoing-0 << "Set-Cookie: __cfduid=d8effcc657ba5bfbaa780fa24639da5251520974415; expires=Wed, 13-Mar-19 20:53:35 GMT; path=/; domain=.Server.com; HttpOnly; Secure[\r][\n]"
DEBUG [2018-03-13 20:53:28,381] org.apache.http.wire: http-outgoing-0 << "X-Frame-Options: SAMEORIGIN[\r][\n]"
DEBUG [2018-03-13 20:53:28,381] org.apache.http.wire: http-outgoing-0 << "Strict-Transport-Security: max-age=15552000[\r][\n]"
DEBUG [2018-03-13 20:53:28,381] org.apache.http.wire: http-outgoing-0 << "Expect-CT: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"[\r][\n]"
DEBUG [2018-03-13 20:53:28,381] org.apache.http.wire: http-outgoing-0 << "Server: cloudflare[\r][\n]"
DEBUG [2018-03-13 20:53:28,381] org.apache.http.wire: http-outgoing-0 << "CF-RAY: 3fb1640e0b47657b-SYD[\r][\n]"
DEBUG [2018-03-13 20:53:28,381] org.apache.http.wire: http-outgoing-0 << "Content-Encoding: gzip[\r][\n]"
DEBUG [2018-03-13 20:53:28,381] org.apache.http.wire: http-outgoing-0 << "[\r][\n]"
DEBUG [2018-03-13 20:53:28,381] org.apache.http.wire: http-outgoing-0 << "830[\r][\n]"
DEBUG [2018-03-13 20:53:28,381] org.apache.http.wire: http-outgoing-0 << "[0x1f][0x8b][0x8][0x0][0x0][0x0][0x0][0x0][0x0][0x3][0xc5]Xmo[0xdb]8[0x12][0xfe][0xee]_1e[0x81][0xed][0x97][0xc8][0xb2][0xd3]4m[0x1d]IE[0x9a]f[0xb7]9[0xf4][0xb0]E_p[,[\n]"
DEBUG [2018-03-13 20:53:28,381] org.apache.http.wire: http-outgoing-0 << "[0x83][0xa6]F[0x12]c[0x8a][0xd4][0x92][0x94]_vo[0xd4][0xfd][0x86][0xfd]c[0xb][0x92][0xb2]#;N[0xfa][0x82];\[0xf2][0xc5][0xe4][0xc][0x1f][0xce]<[0x9a][0x19][0xe][0x99]<x[0xf5][0xf3][0xc5][0x87]Oo/[0xa1][0xb2][0xb5][0xc8][0x6][0xc9][0x83]([0xfa][0x95][0x17] ,\][0xc2][0xd3][0xcf][0x19]$N[0x0]LPcR"Utm[0x80][0xe3])([0x91]s$ [0xa8],S[0x82]2[0xfa][0xf8][0x9e]d[0x90]<[0xf8][0x15]e[0xce][0x8b][0xcf]Qt[0x3][0xd5][0xe1][0x0][0x1c][0x86]z[0xfa]mP[0xcf][0xee][0x81]z[0xf6][\r]P[0xa5][0xed][0xd0][0xdc][0xc4]!/o[0xa3]D[0xd1].R[0x85]4[0xcf][0x6][0x89][0xe5]V`vn-J[0xcb][0x95][0x84]w[0xf8][[0xcb]5[0xe6][0xf][0xe0][0xdf]p!T[0x9b][0x17][0x82]jL[0xe2][0xa0]7[0x18]$5Z[\n]"
DEBUG [2018-03-13 20:53:28,381] org.apache.http.wire: http-outgoing-0 << "[0xac][0xa2][0xda][0xa0]M[0xc9][0xc7][0xf]?F[0xcf][0x8][0xc4]Y'[0xa8][0xac]m"[0x7][0xb1]H[0xc9][0x85][0x92][0xe]5[0xfa][0xb0]n[0x90][0x0][0xb][0xa3][0x94]X\[0xd9][0xd8][0x19]|[0xb6][0x85][0xb9][0xf][0xe5][0x97][0xe8][0xe3]yt[0xa1][0xea][0x86]Z>[0x13]}[0xa0][0xab][0xcb][0xf4]2/[0xf1][0x88]UZ[0xd5][0x98][0x8e]{[0x0][0x92][0xd6][0x98][0x12][0xad]f[0xca][0x9a][0xde][\n]"
DEBUG [2018-03-13 20:53:28,381] org.apache.http.wire: http-outgoing-0 << "[0xa9][0xb8][0xcc]qu[0x4]R[0x15]J[0x8][0xb5][0xbc][0xb5]d[0xc1]q[0xd9](m{[0x8b][0x96]<[0xb7]U[0x9a][0xe3][0x82]3[0x8c][0xfc][0xe0][0x88]Kn9[0x15][0x91]aT`:>[0xaa][0xe9][0x8a][0xd7]m[0xbd][0x19][0x7]T[0xc1][0xe5][0x1c]4[0x8a][0x94][0x18][0xbb][0x16]h*DK[0x80][0xe7])a[0xc5]4LE[0xcc][0x18][0x2][0x95][0xc6]"%1[0xcb]e[0xc4]J[0x1e][0x7]Q[0xcc][0x8a]!j[0xad][0xb4][0x19]z%[0xbb]n[0xb0][0xe3][0xce][0x8f]k[0xcc]9M[0x89]a[0x1a]Q[0x1e]5Z]#s[0x1f]0[0xec][0xbd][0x93][0x7][0xcf]?gw[0x1b][0xf3][0xe8][0xc6][0x18][0x8e][0xce][0x9e]G_[0xb4][0x87][0xe3][0xb7][0x9b][0xb4][0x1b]{[0x1e]r}6S[0xf9][0xfa][0x8f][0x9a][0xea][0x92][0xcb][0xc9][0xe8][0xac][0xa1]y[0xce]e9[0x19][0xfd][0x99][0x4][0x13][0xfa]n[0xe1][0xc6]/[0xc3]4ol[0x1f][0xea][0x9a].h[0x98]%`4[0xeb];[0xe2]gM|[0xfd][[0x8b]z=[0xac][0xb9][0x1c]^[0x1b][0x92]%[0x9d] [0xbb]#[0xd3][0xfc]^[0xe3]Q[0x97]k[0xdf][0xb5][0xe3][0xef][0xd8]Xuh[0xc3][0xfd][0xa4][0xfc][0x1e]pV[0xc][0x99][0xaa]k[0xb5][0x7]>[0x18][0xc][0x92][0xb8]Kr[0xc7]l6[0x0]Hr[0xbe][0xe8]"0Zj[0xda]4[0xa8][0x89][0x9b][0xef]$][0x1]aED[0x5]j[0xb][0x9b][0x1f][0x91][0xff][0xf0]n[0xc8][0x94][0x9a]s[0xc][0xe3].[0x96][0xc3][0x8c][0xd7]#[0x90]SK#[0xab][0xa9]4[0x82]Zt[0xe5][0x87][0xce][0x4]N[0x83][0x92]![0xd9][[0x81][0xd4] [0x84]i[0xe8][0xa6][0x87]I[0x9c][0xf3]E[0xcf][0x8e][0xce]B[0xbf]K[0x94][0xa3][0xa5]\[0xb8],[0xde]Z[0xb7]#[0xd8]s[0xe4][0x96]+[0x9d][0xd8]Y[0xef][0xd8][0x8][0xbf][0x2][0x82]Z[0xa0]v[0x9][0xbf]][0xea]*[0xf3][0xf8][0x96][0x13][0xac][0xa2]B[0xa0],q[0xea][0x0][0x4][0x97]H[0xb2][0x9f]%B[0xad]4[0x82][0xb1][0xd8]$q5[0xee]C[0x1c][0xf7][0xb6]7[0xed][0xec]fUb[0x1a]*o[0xe3][0xab][0xba][0x11]hqj[0x90]MY[0x85]l[0xbe]%j#[0x2][![0x18]d[0xad][0xe6]v[\r]^[0x7][0xac][0x2][0xca][0x18][0x1a][0x93][0xc4][0xe]6[0x3]ZX[0xd4][\r]][0xbb]pH[0xe2][0xea]xK[0x88][0xa7][0xd7][0x5][0x1b][0xc4][0xc3][0x8e][0x3][0x17]mAz[0x98]5[0x13]R[0xd7][0xb3][0xc6][0xcb]J[0xf0][0xb2][0xf2][0xf1][0xc0]hcYE#W[0x1d])[0x97]=[0xda][0xef]"[0xbe][0xa7]pK[0x85])[0xd1][0xd6][0xd2][0x80]][0xaa][0x1d][0xb5];[0x14]"
DEBUG [2018-03-13 20:53:28,384] org.apache.http.headers: http-outgoing-0 << HTTP/1.1 403 Forbidden
DEBUG [2018-03-13 20:53:28,384] org.apache.http.headers: http-outgoing-0 << Date: Tue, 13 Mar 2018 20:53:35 GMT
DEBUG [2018-03-13 20:53:28,384] org.apache.http.headers: http-outgoing-0 << Content-Type: text/html; charset=UTF-8
DEBUG [2018-03-13 20:53:28,384] org.apache.http.headers: http-outgoing-0 << Transfer-Encoding: chunked
DEBUG [2018-03-13 20:53:28,385] org.apache.http.headers: http-outgoing-0 << Connection: keep-alive
DEBUG [2018-03-13 20:53:28,385] org.apache.http.headers: http-outgoing-0 << Set-Cookie: __cfduid=d8effcc657ba5bfbaa780fa24639da5251520974415; expires=Wed, 13-Mar-19 20:53:35 GMT; path=/; domain=.Server.com; HttpOnly; Secure
DEBUG [2018-03-13 20:53:28,385] org.apache.http.headers: http-outgoing-0 << X-Frame-Options: SAMEORIGIN
DEBUG [2018-03-13 20:53:28,385] org.apache.http.headers: http-outgoing-0 << Strict-Transport-Security: max-age=15552000
DEBUG [2018-03-13 20:53:28,385] org.apache.http.headers: http-outgoing-0 << Expect-CT: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
DEBUG [2018-03-13 20:53:28,385] org.apache.http.headers: http-outgoing-0 << Server: cloudflare
DEBUG [2018-03-13 20:53:28,385] org.apache.http.headers: http-outgoing-0 << CF-RAY: 3fb1640e0b47657b-SYD
DEBUG [2018-03-13 20:53:28,385] org.apache.http.headers: http-outgoing-0 << Content-Encoding: gzip

**Comment by arteam** [comment]
@andrewoh531 Please try to disable gzip compressing of request via the `gzipEnabledForRequests` property [1]. Maybe the server doesn't accept compressed requests.

[1] http://www.dropwizard.io/1.3.0/docs/manual/configuration.html#jerseyclient

**Comment by nickbabcock** [comment]
Closing this as the appears the issue could be solved. Let us know if not.
