### ISSUE TITLE
DropWizard 1.2.4 released?

### ISSUE THREAD

**Issue by pkwarren** [dropwizard/dropwizard#2306]
Has DropWizard 1.2.4 been officially released? The dropwizard.io site still references 1.2.2 - just making sure this is ready for consumers to pick up.

**Comment by joschi** [comment]
@pkwarren Yes, Dropwizard 1.2.3 and 1.2.4 have officially been released:
* https://github.com/dropwizard/dropwizard/releases/tag/v1.2.3
* https://github.com/dropwizard/dropwizard/releases/tag/v1.2.4

Unfortunately it looks like the documentation hasn't been updated yet. I'll take a look at it.

**Comment by joschi** [comment]
The documentation for Dropwizard 1.2.3 and 1.2.4 is now available online:
* http://www.dropwizard.io/1.2.3/docs/
* http://www.dropwizard.io/1.2.4/docs/

**Comment by pkwarren** [comment]
Thanks @joschi!
