### ISSUE TITLE
org.glassfish.jersey.internal.Errors Parameter 1 of type FooResource is not resolvable to a concrete type

### ISSUE THREAD

**Issue by novaterata** [dropwizard/dropwizard#2307]
This is a kotlin project using dropwizard 1.3.0
I have some resources with constructors with abstract parameters.

    FooResource(private val repository: Repository<String,ByteArray>){
        \\...
    }

Where Repository is an Interface

I get a bunch of warnings like:

```
5:09:40.108 [main] [] WARN  org.glassfish.jersey.internal.Errors - The following warnings have been detected: WARNING: Parameter 1 of type com.foo.Repository<? su
per java.lang.String, byte[]> from public com.foo.FooResource(com.foo.Repository<? super java.lang.String, byte[]>) is n
ot resolvable to a concrete type.
```
But the program works fine.
I assume this warning has something to do with the supported DI framework / IoC containers, but I use manual injection and don't care about this.

Why is this warning being logged? 
How do I disable this check?

UPDATE: I think this has to do with kotlin adding a wildcard to String

**Comment by hheg** [comment]
I'm getting almost the same problem.
WARN   [22:06:12.763] [main] o.g.j.i.Errors -  The following warnings have been detected: WARNING: Parameter authFilterClass of type java.lang.Class<? extends javax.ws.rs.container.ContainerRequestFilter> from private final java.lang.Class<? extends javax.ws.rs.container.ContainerRequestFilter> io.dropwizard.auth.AuthDynamicFeature.authFilterClass is not resolvable to a concrete type.

**Comment by joschi** [comment]
@novaterata @hheg Please provide a minimal example we can use to reproduce the issue.

**Comment by psimonazzi** [comment]
I see the same warning as @hheg, in a plain Java project.
Here is a minimal test project that uses the same code found in the Authentication chapter of the documentation.

[dropwizard-test1.zip](https://github.com/dropwizard/dropwizard/files/1856646/dropwizard-test1.zip)

`./gradlew installDist`
`./build/install/dw-test/bin/dw-test`

You shoud see the warning in the logs.

**Comment by johannesheinz** [comment]
+1
Same here. I also used the code snippets about Authentication in the docs.

**Comment by VibyJocke** [comment]
+1
I'm getting the same warning with a Java 8 project using Dropwizard 1.3.0 and 1.3.1. The authentication is implemented according to the OAuth2 example in the docs.

**Comment by SoftwAal** [comment]
+1

**Comment by glfp** [comment]
+1

**Comment by cuzz22000** [comment]
Still seeing this warning with v1.3.3 on Java 8.

**Comment by nickbabcock** [comment]
The move to v1.3.3 eliminated these warnings for my projects. Can you share a java 8 repo that is a complete dropwizard project that minimally reproduces this issue?

**Comment by cuzz22000** [comment]
Sorry false alarm my bad.. imported module for swagger is importing v1.3.1 dependancies for auth. assets, and views. Tested with refreshed dependancies for module on DW v1.3.3 and warnings have vanished.

For reference repo can be found here -> https://github.com/cuzz22000/dropwizard-ornament

**Comment by nickbabcock** [comment]
Excellent, Java 10 / Kotlin users, let us know if you're still experiencing this warning with v1.3.3.

**Comment by novaterata** [comment]
Kotlin user and OP. I am still experiencing this.

**Comment by novaterata** [comment]
[dropwizard-2307.zip](https://github.com/dropwizard/dropwizard/files/2115505/dropwizard-2307.zip)
Finally got around to creating a repo project. Just run with `gradlew run` and you'll see the warning in the logs

**Comment by joschi** [comment]
@novaterata The problem seems to be the definition of the interface `Repository`, or more specifically the generic parameters and the byte code the Kotlin compiler generates from that.

The following diff "solves" the warning from Jersey (by making the first generic parameter `K` less precise):
```diff
--- src/main/kotlin/Repository.kt.orig	2018-06-19 18:45:51.000000000 +0200
+++ src/main/kotlin/Repository.kt	2018-06-19 18:46:04.000000000 +0200
@@ -1,4 +1,4 @@
-interface Repository<in K, V> {
+interface Repository<K, V> {
     operator fun set(key: K, metadata: Map<String, String>, value: V)
     operator fun get(key: K): V
 }
```

**Comment by novaterata** [comment]
@joschi Thanks, I'll try it

**Comment by novaterata** [comment]
So, In addition to the use of  covariant Generics (in keyword) causing this in Kotlin, The use of functional type, e.g. K -> V, (UriInfo, String) -> URI, etc. , Will also result in the warning. I got around this by replacing my injected functional interfaces with explicit interface implementations. It's ugly, but a simple workaround. I'll close for now even though it still seems like a bug somewhere.

**Comment by joschi** [comment]
@novaterata I'm not sure it is a real bug and not some incompatibility between the Java and the Kotlin type systems (generics). With Jersey being a Java framework without explicit support for Kotlin, that might pose a problem.

**Comment by mikeholler** [comment]
I'm just encountering this myself with the following resource:

```
@Path("/event-category")
@Produces(MediaType.APPLICATION_JSON)
class EventCategoryResource(
    val clock: Clock,
    val eventCategoryDAOFactory: (UUID) -> EventCategoryDAO
) {
```

Specifically, the warning is,

```
WARN   [2019-08-02 19:31:25,879 | -]  org.glassfish.jersey.internal.Errors: The following warnings have been detected: WARNING: Parameter 2 of type kotlin.jvm.functions.Function1<? super java.util.UUID, ? extends com.example.rest.db.dao.organization.EventCategoryDAO> from public com.example.rest.resources.external.EventCategoryResource(java.time.Clock,kotlin.jvm.functions.Function1<? super java.util.UUID, ? extends com.example.rest.db.dao.organization.EventCategoryDAO>) is not resolvable to a concrete type.
```

Is this warning harmful? What are the negative ramifications here?

**Comment by mikeholler** [comment]
Here's a list of our Dropwizard dependencies, in case it's helpful:

![Screenshot from 2019-08-02 15-32-44](https://user-images.githubusercontent.com/1164112/62397238-dfdc5400-b53a-11e9-9856-a7bd1591a374.png)

**Comment by novaterata** [comment]
Sorry it's been awhile. I think it is harmful, but I don't remember why. I
think all you have to do to avoid it, is not use a default value for that
second parameter. Just inject the lambda.

**Comment by novaterata** [comment]
Oh sorry again. Just realized that was the type signature, not a default
value. I think you need to use a named Interface instead of the functional
type.

**Comment by mikeholler** [comment]
Thanks for the quick response!

> I think you need to use a named Interface instead of the functional
type.

That's disappointing... I'd prefer to use the functional type of course (which is technically an interface itself -- a `Function1`). Do you mean an interface with no generics at all?

I'd be really interested to understand how this is harmful, though, if you're able to remember.

**Comment by novaterata** [comment]
I believe this is a regression in kotlin maybe that stopped generating
something jersey needed for type validation. Again, it's been awhile, and
it might be fixed on the latest of everything ::shrug:: I don't remember
the harm. Might prevent resource registration, it might just be the
warnings.
