### ISSUE TITLE
dropwizard-announce list?

### ISSUE THREAD

**Issue by willp-bl** [dropwizard/dropwizard#2308]
Hi,

It would be great if there was a dropwizard-announce list that we could use to get a notification of new releases etc.  (I'm aware of dropwizard-user)

Thanks

**Comment by joschi** [comment]
@willp-bl You could subscribe to the Releases ATOM feed on GitHub: https://github.com/dropwizard/dropwizard/releases.atom

Combined with a service such as https://blogtrottr.com/, you'll have the Dropwizard release announcements delivered into your mailbox. 😉 

Other than that, we currently don't plan to create a dedicated announcement mailing list.

**Comment by willp-bl** [comment]
I'll try that, thanks
