### ISSUE TITLE
Hidden variable method behind static method

### ISSUE THREAD

**Issue by thogar-computer** [dropwizard/dropwizard#2309]
I have just notice that if I have the following; 

``` java
@GET
@Path("instances/{type}")
@Timed	
public String instanceType(@PathParam("type") Optional<String> type) 
{
	return "you found the URL GET instances/"+type.get();
}	

@POST
@Path("instances/apples")
@Timed	
public String postInstanceApples(@HeaderParam("Authorization") Optional<String> auth, Apples data) 
{		
	return "you found the URL POST instances/apples";	
}	
	
@POST
@Path("instances/oranges")	
@Timed	
public String postInstanceOranges(@HeaderParam("Authorization") Optional<String> auth, Oranges data) 
{
	return "you found the URL POST instances/oranges";
}
```

I get a 405 error when I try GET /instance/apples
This seems odd behaviour, I would have thought dropwizard would first look at the incoming request’s method (GET/POST) then try and match the URL.  
However is seems that the URL is matched first, then the method. Is this the correct behaviour? 

I have attached a zip file with a coded example showing the problem.. 
[testDrop.zip](https://github.com/dropwizard/dropwizard/files/1819192/testDrop.zip)

**Comment by lutzhorn** [comment]
>  However is seems that the URL is matched first, then the method. Is
> this the correct behaviour?

Yes, that's how JAX-RS is specified: 
https://abhirockzz.wordpress.com/2015/03/02/quick-peek-at-jax-rs-request-to-method-matching/

Lutz
