### ISSUE TITLE
Testing metric presence using ResourceTestRule

### ISSUE THREAD

**Issue by gmariotti** [dropwizard/dropwizard#2314]
Hi, I'm writing an integration test to see if a resource method marked with `@Metered` correctly creates and updates a metric in the `MetricRegistry`. I thought that the code
```
MetricRegistry metrics = new MetricRegistry();

@Rule
ResourceTestRule resource = ResourceTestRule.builder()
  .addResource(HelloWorldResource())
  .addProvider(InstrumentedResourceMethodApplicationListener(metrics)
  .build();
```
would made the trick but that's not true. Any idea how I could do it?

**Comment by joschi** [comment]
@gmariotti `ResourceTestRule` doesn't instantiate a full Dropwizard application but only loads the given JAX-RS resource into an in-memory server which doesn't support all features and lifecycle phases of Dropwizard.

**Comment by gmariotti** [comment]
Thanks @joschi. I imagine that the only possible solution is to use the `DropwizardAppRule`, am I correct?

**Comment by joschi** [comment]
@gmariotti Yes, as of Dropwizard 1.3.0 that's the way to go.
