### ISSUE TITLE
Enhance the metric to include timestamp

### ISSUE THREAD

**Issue by db-vmw** [dropwizard/dropwizard#2319]
Currently, some of the metric reporters support timestamp with metric as well. The dropwizard metrics like Guage, Timers etc should support even timestamp as one of the members (Timestamp should be an optional member). Let me know any comments. 
Example use case is: suppose say, we want to run a validation after an event has occurred and send the validation result as guage value once the validation completes. Now, in this scenario, the event will any ways be sent as metric (no need of timestamp here) but, while sending the validation result, it makes more sence to include the timestamp at which the event has occurred. This will help in correlating the validation metric with the event metric. 
Let me know comments. If not, I can contribute to include timestamp as a member to Metric family specially for guage.
Timestamp can be an optional member to the metric type.

**Comment by joschi** [comment]
@db-vmw Please create an issue in the Dropwizard Metrics project at https://github.com/dropwizard/metrics/issues.
