### ISSUE TITLE
Space after log level

### ISSUE THREAD

**Issue by PixxelP** [dropwizard/dropwizard#2322]
`[23:00:26 2018-04-04] [INFO ] Started @2689ms`

Is there supposed to be a space after the log level? If this is the case is there anyway of removing it?

`logFormat: "[%d{HH:mm:ss yyyy-MM-dd}] [%-5level] %msg%n"`

This is my logging format in the `config.yml`.

**Comment by nickbabcock** [comment]
Doesn't `[%-5level]` mean to pad out to 5 spaces if the text is shorter than 5 (and INFO is 4 in length)?

**Comment by joschi** [comment]
@nickbabcock Yes, that's exactly what it means.

@PixxelP See https://logback.qos.ch/manual/layouts.html#formatModifiers for details about the format modifiers in the `logFormat` setting.

**Comment by PixxelP** [comment]
Thanks for the info!
