### ISSUE TITLE
How to set a maximum MultiPart Form Data size without persisting full file on disk?

### ISSUE THREAD

**Issue by LeducH** [dropwizard/dropwizard#2327]
I want to check the file size before the file is persisted in the backend. I used a POST Multipart upload. 

After checking the issue #1657 the solution was to [ByteStreams.limit](https://google.github.io/guava/releases/19.0/api/docs/com/google/common/io/ByteStreams.html#limit%28java.io.InputStream,%20long%29). But as @pavelkokush mentioned that would mean to persist the file first. 

So I was wondering how the file size check could be implemented.

**Comment by pavelkokush** [comment]
I do not know about special dropwizard features... But file will not be persisted on disk automatically if you work directly on HttpServletRequest 
```
@POST
@Consumes("multipart/form-data")
void upload(@Context HttpServletRequest request);
```
Then you can use [ServletFileUpload](https://commons.apache.org/proper/commons-fileupload/apidocs/org/apache/commons/fileupload/servlet/ServletFileUpload.html)
```
ServletFileUpload upload = new ServletFileUpload();
upload.setSizeMax(XXX);
upload.setFileSizeMax(YYY);
InputStream inputStream = upload.getItemIterator(request).next().openStream();
```
 It will throw exception when you read inputStream if any limits reached.

**Comment by isaki-x** [comment]
I would do one of the following using the request input stream:

- Maintain a buffer in memory that tracks and track how much data has been read (you may wish to have a pool of reusable buffers for memory/gc reasons) that will throw if the limit is exceeded. I'd implement them using some sort of close/finish mechanic that on close, if no errors found, dump the buffer to disk.
- Write to disk and if the limit is exceeded, close the write handle and nuke the file (thus you don't write the entire payload if you don't have to).

**Comment by LeducH** [comment]
Thanks  for your notes. Let me be a concrete. So consider the example  [link](https://github.com/juanpabloprado/dw-multipart/blob/master/src/main/java/com/juanpabloprado/dw/examples/resources/FileResource.java)
@isaki-x 
Where would I integrate the in memory buffer? 

@pavelkokush 
I assume I need to add an additional argument to the `uploadFile` method to be able to the ServletFileUpload

**Comment by isaki-x** [comment]
@LeducH You would need to have it in your resource. A simple implementation would be to have some sort of buffer object, which could be as simple as a byte[] stored in a ThreadLocal. You could also just simply allocate a byte[] on every request as well.

You would need to read the stream yourself (and modify my simple example to match your work):

```Java
private final ThreadLocal<byte[]> cache;

public YourConstructor(final int maxFileSize) {
    super();

    Preconditions.checkArgument(maxFileSize > 0);

    this.cache = ThreadLocal.withInitial(() -> new byte[maxFileSize]);
}

@POST
@Path("/post/file")
@Consumes("application/octet-stream")
public Response postTheFile(final InputStream requestStream) throws IOException {
    final byte[] buffer = cache.get();
    int read = requestStream.read();
    int i = 0;
    for (; read != -1 && i < buffer.length; ++i) {
        buffer[i] = (byte) read;
        read = requestStream.read();
    }

    if (read != -1) {
        // Error, I'll just throw, you do what you want
        throw new IOException("Max File Exceeded");
    }

    // This method needs to know how far into the buffer to go.
    this.writeFile(buffer, i); 
}
```

This is based on this: https://stackoverflow.com/questions/10326460/how-to-avoid-outofmemoryerror-when-uploading-a-large-file-using-jersey-client

I don't know if it will work as I've never actually tried this. Let me know if this completely fails and I'll try to come up with something else.

**Comment by LeducH** [comment]
The funny thing is I tried this method that you proposed.  As you might see further down the bad think is sometimes when the files are to large it takes quite long. There was a hint to look into the WriteInterceptor. 

When I found something I will post my findings


```
@POST
  @Consumes(MediaType.MULTIPART_FORM_DATA)
  public Response uploadFile(
      @FormDataParam("file") InputStream uploadedInputStream,
      @FormDataParam("file") FormDataContentDisposition fileDetail)
      throws IOException {
    String fileName = fileDetail.getFileName();
    String uploadedFileLocation = uploadPath + fileName;

    Long size = writeToFile(uploadedInputStream, uploadedFileLocation);
     return Response.ok(size).build();
  }

  // save uploaded file to new location
  private Long writeToFile(InputStream uploadedInputStream, String uploadedFileLocation)
      throws IOException {
    int read;
    final int BUFFER_LENGTH = 1024;
    final byte[] buffer = new byte[BUFFER_LENGTH];
    long size = 0;
    OutputStream out = new FileOutputStream(new File(uploadedFileLocation));
    while ((read = uploadedInputStream.read(buffer)) != -1) {
      out.write(buffer, 0, read);
      size += read;
      if (size > 2 * 1014 * 1024) {
        LOGGER.info("FileMetaData size exceeds 2MB");
        throw new BadRequestException("Server unavaible");
      }
    }
    out.flush();
    out.close();
    return size;
}
```

**Comment by nickbabcock** [comment]
I'm closing this issue as the solutions presented seem sufficient. If there is a proposal to better handle these situations in Dropwizard, then I'm game to listen
