### ISSUE TITLE
Add exception mapper for constraint violation in hibernate orm

### ISSUE THREAD

**Issue by ramsrib** [dropwizard/dropwizard#2332]
I'm trying to map the `ConstraintViolation` exception from hibernate to return `409` http response, but the jersey exception mapper is not able to catch it.

```
@Provider
public class MyExceptionMapper implements ExceptionMapper<JerseyViolationException> {

  private static final Logger LOGGER =
      LoggerFactory.getLogger(JerseyViolationExceptionMapper.class);

  public Response toResponse(final JerseyViolationException exception) {
    LOGGER.debug("Handled by custom exception mapper", exception);
    return Response.status(409).build();
  }
}
```

Actual Exception:
```

0:0:0:0:0:0:0:1 - - [25/Apr/2018:19:05:53 +0000] "POST /users HTTP/1.1" 500 110 "-" "curl/7.54.0" 12
ERROR [2018-04-25 19:05:53,100] io.dropwizard.jersey.errors.LoggingExceptionMapper: Error handling a request: c96f7625a7326594
! org.h2.jdbc.JdbcSQLException: Unique index or primary key violation: "UK_21GCRPXWQST2MVHVQ4MO8F6UY_INDEX_B ON PUBLIC.USER_INFO(NAME) VALUES ('sri', 1)"; SQL statement:
! /* insert com.dropwizard.example.User */ insert into user_info (name, number, id) values (?, ?, ?) [23505-197]
! at org.h2.message.DbException.getJdbcSQLException(DbException.java:357)
! ...
! at org.hibernate.engine.jdbc.internal.ResultSetReturnImpl.executeUpdate(ResultSetReturnImpl.java:175)
! ... 74 common frames omitted
! Causing: org.hibernate.exception.ConstraintViolationException: could not execute statement
! at org.hibernate.exception.internal.SQLStateConversionDelegate.convert(SQLStateConversionDelegate.java:112)
! ... 66 common frames omitted
! Causing: javax.persistence.PersistenceException: org.hibernate.exception.ConstraintViolationException: could not execute statement
! at org.hibernate.internal.ExceptionConverterImpl.convert(ExceptionConverterImpl.java:149)
! ...
! at java.base/java.lang.Thread.run(Thread.java:844)
```

Created an example to demonstrate this issue (with test case).
https://github.com/ramsrib/dropwizard-exception-mapper-example

I think the **hibernate** wraps the `ConstraintViolationException` with `PersistenceException`. And the exception binder only looks for the exact exception type and it's not able to find and so throws 500 .

**Comment by nickbabcock** [comment]
Thank you for the code sample and the test that demonstrates the issue. Much appreciated.

The `ExceptionMapper<JerseyViolationException>` is intended for catching validations dealing with the data / parameters supplied in the request or response. It's tied to Jersey.

AFAIK, Jersey doesn't unwrap causes of an exception to find exception mapper.

If you would like to customize the response for a `PersistenceException` then you should define `ExceptionMapper<PersistenceException>`. Now, should Dropwizard provide a default implementation for handling `PersistenceException` -- that's a good question.

**Comment by ramsrib** [comment]
Thanks for the detailed response. Default `PersistenceException` handler will be really useful.

**Comment by nickbabcock** [comment]
What logic do you think should be in this handler? Does a constraint violation mean 400 response, and anything else a 500? I'll need someone more familiar with all the exceptions that Hibernate ORM can throw and how to interpret them to sketch out an implementation.

I also think the lowest risk would be to introduce an opt-in exception mapper (eg. it is not registered by the Hibernate bundle by default, but we provide an implementation for those that want it), so that this could be introduced in a minor dropwizard release without worry of backwards incompatibility.

**Comment by ramsrib** [comment]
400 (Bad request) is the proper response code (though 409 also makes sense). Yeah, Opt-in exception mapper along with documentation will be good enough. I updated my example ( https://github.com/ramsrib/dropwizard-exception-mapper-example) with proper exception mapper.

If that sounds good, i can create a pull request with that exception mapper.

**Comment by nickbabcock** [comment]
Yeah, how about you create the pull request so that there will be more eyes on it for any potential discussions.

**Comment by alex-shpak** [comment]
@ramsrib 

As an option you can extend `JerseyViolationExceptionMapper`
```
@Provider
class ValidationExceptionMapper extends JerseyViolationExceptionMapper {

    @Override
    public Response toResponse(JerseyViolationException exception) {
        Response response = super.toResponse(exception);
        // ...
        return response;
    }
}
```

Worked for me
