### ISSUE TITLE
Form based authentication

### ISSUE THREAD

**Issue by richmidwinter** [dropwizard/dropwizard#2343]
Any chance of having form based authentication added to dropwizard-auth?

**Comment by nickbabcock** [comment]
I like the thought of form based authentication in dropwizard to go along with the basic / oauth implementations, but time is short and it looks like an outside contributor will need to champion this issue. Until then I'm closing the issue and I'd recommend looking into adding something like [pac4j](https://www.pac4j.org/index.html) (and [login form demo](https://github.com/pac4j/dropwizard-pac4j-demo)) onto your dropwizard application to take advantage of their features.
