### ISSUE TITLE
@NotEmpty fields in config break the configuration

### ISSUE THREAD

**Issue by krutsko** [dropwizard/dropwizard#2353]
We are building a Core library on top of dropwizard, it provides some default, basic values for configurations, and allow to specific service to override them.  

We got several breaking changes after https://github.com/dropwizard/dropwizard/commit/207c3cbc98131463bc28cbf6cab814f44af1ece2#diff-e5126a75b90a2bf1ce64a60b923c8eadR343

For example:
```
-    @NotNull	
-    private String driverClass = null;

+    @NotEmpty
+    private String driverClass = "";
```

driverClass has an empty string in Core config. But now, a specific service which don't use database, cannot validate the config, until provides some dummy value.

Of course, we can find a workaround for this, just want to point your attension to our usecase. 
Maybe, it worth to not be so strict with validation rules.

**Comment by arteam** [comment]
Thanks, I will take a look where we use empty strings with `@NotEmpty` and whether null values makes sense like in such cases.
