### ISSUE TITLE
JerseyClientBuilder not working with resteasy-client

### ISSUE THREAD

**Issue by aneto-core** [dropwizard/dropwizard#2361]
If you use JerseyClientBuilder with resteasy-client dependency:

```
<dependency>
    <groupId>org.jboss.resteasy</groupId>
    <artifactId>resteasy-client</artifactId>
    <version>3.5.1.Final</version>
</dependency>
```

occurs an Exception:

```
javax.ws.rs.ProcessingException: java.lang.ClassCastException: org.jboss.resteasy.client.jaxrs.internal.ClientRequestContextImpl cannot be cast to org.glassfish.jersey.client.ClientRequest
```

To reproduce you can put the maven dependency of resteasy-client on [dropwizard-example](https://github.com/dropwizard/dropwizard/tree/master/dropwizard-example) and use like that:

```
javax.ws.rs.client.Client client = new JerseyClientBuilder(environment)
        .using(configuration.getJerseyClientConfiguration())
        .build(getName());

client.target("http://www.google.com.br").request().get();
```

**Comment by joschi** [comment]
@aneto-core Dropwizard is an opinionated framework which only support Jersey as a JAX-RS implementation. RESTeasy (or any other JAX-RS implementation) is not and will not be supported by Dropwizard.

**Comment by omaric** [comment]
This makes me sad as someone who is using Dropwizard with Keycloak, which is hardcoded to use RESTEasy in their client.

Note that Dropwizard supports both Apache HttpClient and Jersey Client, at least, according to the documentation.
