### ISSUE TITLE
Could not configure template exception handler

### ISSUE THREAD

**Issue by monler** [dropwizard/dropwizard#2372]
Hi,
I am using dropwizard 1.0.5 with freemarker for some web pages. As suggested by [Freemarker](https://freemarker.apache.org/docs/pgui_config_errorhandling.html), I am trying to change  template exception handler configuration from **_debug_** to **_rethrow_**. I follow the steps decribed in [Dropwizard-Views configuration](https://www.dropwizard.io/1.0.5/docs/manual/views.html) with different configurations;
  
```
views:
  .ftl:
    template_exception_handler: rethrow
```
```
views:
  .ftl:
    templateExceptionHandler: rethrow
```
```
views:
  .ftl:
    TemplateExceptionHandler: rethrow
```
Also, I try version 1.3.2 with following configurations;
```
views:
  freemarker:
    template_exception_handler: rethrow
```
```
views:
  freemarker:
    templateExceptionHandler: rethrow
```
```
views:
  freemarker:
    TemplateExceptionHandler: rethrow
```
But I am seeing the error on the page as; 

> FreeMarker template error (DEBUG mode; use RETHROW in production!)

What should I do to configure this? What am I missing?

**Comment by nickbabcock** [comment]
Freemarker currently does not allow you to change this setting through [`Configuration::setSetting`](https://github.com/apache/freemarker/blob/43d0658410b65f489597d6950da0abe3970a7ea0/src/main/java/freemarker/template/Configuration.java#L3202), so it's not possible at the moment. A change will need to be made to dropwizard or freemarker to accommodate.

**Comment by monler** [comment]
Ah, that's a bummer :(
Thanks anyway.
I was trying to prevent users seeing the template errors. I find out that freemarker has a feature which is [attempt-recover](https://freemarker.apache.org/docs/ref_directive_attempt.html). It solves my issue at least for now.

**Comment by nickbabcock** [comment]
Excellent, I'll close this for now, but if someone needs this as a feature in the future, and freemarker still doesn't support setting it through `Configuration::setSetting` then we can reopen this issue.

**Comment by rogatty** [comment]
It would be great to have this implemented one way or another. I created a ticket in Freemarker issue tracker: https://issues.apache.org/jira/browse/FREEMARKER-103

**Comment by ddekany** [comment]
But, you can set the `template_exception_handler` though `Configuration::setSetting`. I'm nor sure why's not working. Something that's maybe a sign of the real problems is if you didn't get an exception for the incorrect attempt,  `TemplateExceptionHandler=rethrow`. That's not a valid setting name with `T`, and FreeMarker then throws an exception.

**Comment by rogatty** [comment]
@ddekany you're right, I've tried it and it works as expected. I was confused by the fact that it's not anywhere in the `Configuration::setSetting` method. I suspect @monler didn't pass configuration from the yaml file to `getViewConfiguration` method.
Thanks!
