### ISSUE TITLE
UUIDParam not checking structure of input

### ISSUE THREAD

**Issue by StephenSouness** [dropwizard/dropwizard#2374]
UUIDParam appears to be passing the String representation directly through to the UUID.fromString method, which does not validate its input.

This allows clients to supply an invalid value which should be rejected.

We can verify the behaviour of UUID.fromString as follows:

  UUID originalUuid = UUID.randomUUID();
  UUID mutatedUuid = UUID.fromString(originalUuid + "1234");
  assertEquals(originalUuid.toString(), mutatedUuid.toString());

**Comment by nickbabcock** [comment]
I'm a bit confused. The test case that you present never passes for one of two reasons (depending on the random UUID:

- Overflow in parsing `originalUuid + "1234"`
- original != validated so `assertEquals` fails

**Comment by StephenSouness** [comment]
Sorry for my confusing naming convention there.  I originally copied and pasted without checking that the wording made sense - I have now edited the issue to indicate that the second UUID can be regarded as "mutated".

I only ran the test a couple of times myself, so only witnessed that the original and mutated values were never equal.

I don't think that the possibility of two outcomes detract from the reported issue though.

**Comment by nickbabcock** [comment]
Ah I may have misunderstood. Is the issue that `UUID.fromString` _does_ validate the input, but it is too lax? If so, what are your expectations? What are (languages / RFCs / frameworks) you comparing against? Do you have a suggestion in mind?

Additionally, use hardcoded UUIDs in examples instead of random so that I can more easily follow along

**Comment by StephenSouness** [comment]
My bad.  I could have specified a much simpler mutation and never triggered the overflow.

I'm not sure if there is a preferred approach to validating UUID - perhaps a regular expression would suffice?  Then throw an exception if the input does not match.

**Comment by nickbabcock** [comment]
> perhaps a regular expression would suffice

Maybe, but I'm wary of crafting regular expressions. I would hate for a couple weeks after a release to get a bunch of reports about how valid UUIDs are being rejected. Not saying this isn't the correct approach, but it's something to consider.

> Another alternative that I have just come across involves comparing the UUID's toString value against the original input String.

That's interesting. I hadn't thought of that. Could work.

**Comment by StephenSouness** [comment]
100% agree.

The regular expression approach is a little bit complex, particularly if catering for an edge case (nil/null value).

**Comment by joschi** [comment]
@StephenSouness @nickbabcock Would it be sufficient to check for the length of the input additionally to using it with `UUID#fromString()`?
This would solve the problem with the ignored suffixes and it's relatively cheap to check.

**Comment by nickbabcock** [comment]
Yes that sounds good to me.

**Comment by StephenSouness** [comment]
Cheap is good.

👍
