### ISSUE TITLE
registerDefaultExceptionMappers: false still maps ValidationExceptionMapper

### ISSUE THREAD

**Issue by andrewoh531** [dropwizard/dropwizard#2380]
We've configured Dropwizard not to register default exception mappers by setting `registerDefaultExceptionMappers: false` in the `yml` file. However it's still mapping `org.glassfish.jersey.server.validation.internal.ValidationExceptionMapper` and is messing with our catch-all exception handler.

Why is this not excluded and is there a way to remove it?

**Comment by nickbabcock** [comment]
`registerDefaultExceptionMappers` is for toggling if dropwizard should register its own exception mappers, it doesn't make reference to any of Jersey's internal exception mappers (eg: `ValidationExceptionMapper`).

I looked into it a little bit, and I'm not sure if using standard dropwizard code if `ValidationExceptionMapper` will be registered in the first place. Looking at the Jersey source code, it appears it is only registered if `ValidationFeature` is registered (which dropwizard doesn't). So I'd check if you're are registering either `ValidationFeature` or `ValidationBinder` (and if so, remove them)

**Comment by andrewoh531** [comment]
Thanks! I did some more digging around and it appears it's registered by Jersey. Here's an open issue against Jersey on the issue: https://github.com/jersey/jersey/issues/3425

I was hoping there might be a more elegant way but looks like there isn't :(

**Comment by ktalebian** [comment]
@andrewoh531 did you ever fix this issue?
