### ISSUE TITLE
Rules and Class Rules with Cucumber-JVM and Dropwizard

### ISSUE THREAD

**Issue by ralemy** [dropwizard/dropwizard#2387]
I have Cucumber as my testing framework, developing in IntellijIDEA IDE, and was trying to use the DAOTestRule class to test my hibernate persistence layer. I noticed that the before() and after() functions don't get called.

Further investigation revealed it is a known issue and that Cucumber ignores @Rule and @ClassRule annotations when gathering its annotated functions from step classes. Therefore, the following class will give an error:

    public class MyTestSteps {

    Person saved;
    Person unsaved;
    PersonDAO personDAO;

    @Rule
    public DAOTestRule myDAORule = DAOTestRule
            .newBuilder()
            .addEntityClass(Person.class)
            .build();

     @Before("@DAOTests")
     public void beforeDaoTests(){
            personDAO = new PersonDAO(myDAORule.getSessionFactory());
     }
    
    @Given("^I have an Object to persist$")
    public void iHaveAnObjectToPersist() throws Throwable {
        unsaved = new Person("John", "Doe");
    }

    @When("^I save it using the DAO$")
    public void iSaveItUsingTheDAO() throws Throwable {
       saved = myDAORule.inTransaction(() -> personDAO.create(unsaved));
      
    }

    @Then("^It is added to the database$")
    public void itIsAddedToTheDatabase() throws Throwable {
        Assert.assertThat(saved.getId(),greaterThan(0L));
    }
    }
The error would be on the DAO.create() function:

    org.hibernate.HibernateException: No session currently bound to execution context

I can't call the before() and after() myself, since they are protected. so one way is to wrap DAOTestRule in a new object, expose the before() and after(), and call them in the @Before and @After functions:

    ....
    public MyExtendedDAOTestRule myDAORule = MyExtendedDAOTestRule
            .newBuilder()
            .addEntityClass(Person.class)
            .build();

    @Before("@DAOTest")
    public void beforeDaoTests() throws Throwable {
        myDAORule.before();
    }

    @After("@DAOTest")
    public void afterDaoTests() {
        myDAORule.after();
    }
    ....

And it will work. is this the simplest/only way? is there an important reason for before and after to be protected?

**Comment by ralemy** [comment]
That is awesome and makes perfect sense. Thanks, Nick. 

Should I submit a pull request then, and if the changes were not too much perhaps you approve it?

**Comment by nickbabcock** [comment]
Yes, submit a PR and then I can take a look. If you find any more classes that can be cucumberized at no cost, go ahead and do so.

**Comment by nickbabcock** [comment]
Dropwizard is still puts Junit first for testing, so most likely additional testing frameworks would be asked to be third party modules. We can incorporate anything needed in the core to allow for additional testing frameworks.
