### ISSUE TITLE
Hibernate: DataSourceFactory dynamic passwords

### ISSUE THREAD

**Issue by DrMattFaulkner** [dropwizard/dropwizard#2388]
Hi,

I'm looking at using rotation passwords for database connection. Currently the database password is hardcoded in the config.yml. Can someone point me in the right direction so I can make this rotating ?

**Comment by nickbabcock** [comment]
Oh man, I think this may be a tough ask -- a use case that dropwizard will probably not cater to:

- Other than logging there is no way to change configuration settings at run time
- You'd have to create your own database configuration class that had a mechanism for updating the password
- You'd have to figure out if tomcat jdbc supports it or use another connection pool ([hikaricp supports it unofficially](https://github.com/brettwooldridge/HikariCP/issues/879)) or play it simple and allocate a connection per request.

This looks like no small task 😄

**Comment by DrMattFaulkner** [comment]
FYI the use case here is for AWS and to use IAM Auth Token instead of passwords. With the tokens rotating. 

Once a connection is created I think it's OK for that to "hang" around even after a password change. But any new connections would need to pickup the new details.

I will take a look and see if this is something that can easily be done.

**Comment by nickbabcock** [comment]
I'm going to close this issue, as there is no apparent further action on the Dropwizard side. Feel free to continue posting in this issue if one happens to successfully use dynamic passwords.
