### ISSUE TITLE
Remove Joda Time in 2.0.0?

### ISSUE THREAD

**Issue by rbjorklin** [dropwizard/dropwizard#2396]
Tracking issue for 2.0.0 milestone to consider replacing joda-time with `java.time`.

See previous discussion in #1486.

threeten-extra for missing features: http://www.threeten.org/threeten-extra/
SO write-up on differences: https://stackoverflow.com/a/24635657/4092025
Time library comparison: http://time4j.net/tutorial/appendix.html

**Comment by nickbabcock** [comment]
Currently `java.time` and jodatime are both supported in Dropwizard. What are the reasons for dropping jodatime?

**Comment by rbjorklin** [comment]
Wasn't aware that both were supported. Thanks!

**Comment by isaki-x** [comment]
I like the idea of splitting jodatime support into dedicated modules (similar to what's being discussed for Guava) to minimize dependencies for those using DropWizard but not jodatime.

**Comment by nickbabcock** [comment]
Yeah I'll re-open this since there is discussion on the removing guava as a dependency
