### ISSUE TITLE
Dropwizard with no logback + Log4j 1.x +  Log4jALA 

### ISSUE THREAD

**Issue by reksomu371** [dropwizard/dropwizard#2412]
Is there good integration point for Dropwizard with no logback and to use log4j 1.x instead log4j 2.x which will redirect the logs to Azure LogAnalytics using  Log4jALA appender. I tried to following the dropwizard no logback dependency, to use SLF4J to use external logging, i.e Log4j2.x as provided by Arteam demo app. 

Log4jALA appender library which uses log4j 1.x, so need to use Dropwizard with nologback and use log4j 1.x. I tried my best, it doesn't log message to external logging instead uses default.

https://github.com/ptv-logistics/Log4jALA

Logs are not redirecting to Log4jALA, console and file.

gradle.build snippet:
dependencies {
    compile ("io.dropwizard:dropwizard-core:1.3.0") {
        exclude group: 'org.eclipse.jetty.orbit'
   		exclude group:"ch.qos.logback", module:"logback-core"    
   		exclude group:"ch.qos.logback", module:"logback-classic"    
   		exclude group:"ch.qos.logback", module:"logback-access"    
   		exclude group:"org.slf4j", module:"log4j-over-slf4j"  
    }
    compile "io.dropwizard:dropwizard-assets:1.3.0"
    compile "io.dropwizard:dropwizard-client:1.3.0"
    compile "io.dropwizard:dropwizard-testing:1.3.0"
    compile "com.fasterxml.jackson.datatype:jackson-datatype-jsr310:2.6.3"
    compile "org.projectlombok:lombok:1.16.2"
    compile "javax.servlet:javax.servlet-api:3.1.0"
    compile "com.microsoft.azure:azure-storage:$azureStorageVersion"
    compile "com.pros.cloud.security:cloud-auth-client-dropwizard-pre1:$loginPortalClientVersion"
    compile "com.microsoft.azure:applicationinsights-core:$appInsightsSdkVersion"
    compile group: 'com.github.ptv-logistics', name: 'log4jala', version: "1.0.4"
    compile 'org.owasp.esapi:esapi:2.0.1'
    compile "org.jsoup:jsoup:$jsoupVersion"
    compile 'net.jodah:failsafe:1.0.5'
    testCompile group: 'io.dropwizard', name: 'dropwizard-testing', version: "$dropwizardVersion"
    testCompile 'junit:junit:4.12'
    testCompile 'org.mockito:mockito-core:1.9.5'
}

**Comment by nickbabcock** [comment]
Closing this issue as it appears that you've found arteam's sample project where he defines a substitute logging provider: https://github.com/arteam/dropwizard-nologback/issues/2

While dropwizard team has given the flexibility for the community to bring their own logging, we don't write individual guides. If the community would like to contribute guides to our documentation we'd welcome the contribution.
