### ISSUE TITLE
Logging MDC variables in jetty request log

### ISSUE THREAD

**Issue by simarpreets** [dropwizard/dropwizard#2422]
Hi, 

I want to log some of the attributes from `MDC` into request log.
Dropwizard, by default, uses `logback-access` which doesn't support logging `MDC` variables (https://logback.qos.ch/manual/layouts.html#logback-access).

Is there a way to add some custom data(user-info, request params) to request logs?

**Comment by joschi** [comment]
Duplicate of #2419
