### ISSUE TITLE
Is it possible to register resources outside the default subroute?

### ISSUE THREAD

**Issue by Rafael-Simonelli** [dropwizard/dropwizard#2423]
I have an Application with base URL Pattern set as follows:

`environment.jersey().setUrlPattern("/api/some-info/*");`

But now I need to register my authentication resource and I need it to be outside the `"/api/some-info/*"` subroute. Is it possible? How can I do so?

Thanks.

**Comment by nickbabcock** [comment]
No, I don't think you can as authentication is registered through jersey and if jersey can't listen outside the registered path, you can't use the same authentication logic.

**Comment by Rafael-Simonelli** [comment]
Ok, thanks for the reply!
