### ISSUE TITLE
How can I monitor the InstrumentedQueuedThreadPool ("dw")

### ISSUE THREAD

**Issue by patrox** [dropwizard/dropwizard#2424]
As described, I would like to have access to the threadpool which is used to handle the incoming requests for the application endpoint.

This is needed as I would like to use Prometheus [`QueuedThreadPoolStatisticsCollector`](https://github.com/prometheus/client_java/blob/master/simpleclient_jetty_jdk8/src/main/java/io/prometheus/client/jetty/QueuedThreadPoolStatisticsCollector.java#L23).

Is there any non-intrusive way of capturing the metrics from this thread pool, without having access to it ?

**Comment by nickbabcock** [comment]
Yes (you must wait until the server starts up before having access to the threadpool)

```java
public void run(Configuration config, Environment env) throws Exception {
    env.lifecycle().manage(new Managed() {
        @Override
        public void start() throws Exception {
            env.getApplicationContext().getServer().getThreadPool();
        }

        @Override
        public void stop() throws Exception {

        }
    });
}
```

**Comment by patrox** [comment]
Thanks @nickbabcock - that makes sense, as I was trying to access it too soon and it turned out to be not created (yet).

Cheers!
