### ISSUE TITLE
acceptQueueSize defaults to an incomplete value from somaxconn on Linux

### ISSUE THREAD

**Issue by donicek** [dropwizard/dropwizard#2429]
A call to io.dropwizard.jetty.NetUtil.getTcpBacklog() reads just the first digit of /proc/sys/net/core/somaxconn on Linux, effectively making the default acceptQueueSize just 1 or 2 (depending on the actual value of somaxconn; verified with 128 and 2048). This in turn results in increased number of failed connections to DW (connection timeouts) when the server is under stress. This seems to be a regression between 0.9.x. and 1.0.x (because in 0.9.x, somaxconn was not explicitly used as a source of a default value).

The issue seems to be specifically in Files.readAllBytes(paths.get('/proc/sys/net/core/somaxconn')), in that the SeekableByteChannel in readAllBytes is treating the /proc fs as a regular file, which it is not (seeks aren't possible, nor filesize can be read ahead). Thus, in effect it only reads the first byte of somaxconn (instead of the entire string value), passing it without any further warning into acceptQueueSize as a default.

**Comment by nickbabcock** [comment]
Thank you for reporting this, I can confirm this is a bug. I have somaxconn set to 128 and the following diff will make this test fail:

```diff
--- a/dropwizard-jetty/src/test/java/io/dropwizard/jetty/NetUtilTest.java
+++ b/dropwizard-jetty/src/test/java/io/dropwizard/jetty/NetUtilTest.java
@@ -54,6 +54,7 @@ public class NetUtilTest {
     public void testOsSetting() {
         assumeThat(System.getProperty(OS_NAME_PROPERTY), containsString("Linux"));
         assumeThat(isTcpBacklogSettingReadable(), is(true));
+        assertThat(NetUtil.getTcpBacklog()).isGreaterThan(2);
         assertNotEquals(-1, NetUtil.getTcpBacklog(-1));
     }
```

**Comment by OndraZizka** [comment]
Quick verification in Groovy:
```
import java.nio.file.Files;
import java.nio.file.Paths;

new String(Files.readAllBytes(Paths.get("/proc/sys/net/core/somaxconn")));
```
