### ISSUE TITLE
acceptQueueSize default value bug

### ISSUE THREAD

**Issue by OndraZizka** [dropwizard/dropwizard#2431]
The documentation at https://www.dropwizard.io/1.3.5/docs/manual/configuration.html says that `acceptQueueSize` default is "OS default". If fact, though, it reads only the first byte of what the OS returns, at least on Linux.

`Files.readAllBytes(Paths.get("/proc/sys/net/core/somaxconn"));` reads just the first byte, not the entire value of somaxconn. That's a bug in Dropwizard. It results in `2` if somaxconn is set to `2048`.

(Found by Petr Kacer)

**Comment by nickbabcock** [comment]
Yes, the bug has been fixed. Those affected should change `acceptQueueSize` in their configuration

**Comment by OndraZizka** [comment]
Thanks! Fixed where?

**Comment by OndraZizka** [comment]
Goto it: https://github.com/dropwizard/dropwizard/pull/2430

**Comment by OndraZizka** [comment]
Duplicates https://github.com/dropwizard/dropwizard/issues/2429
