### ISSUE TITLE
How to start a executable dropwizard jar as a Windows Service / Linux Service

### ISSUE THREAD

**Issue by iotech-longtran** [dropwizard/dropwizard#2433]
can anyone help me? thanks

**Comment by nickbabcock** [comment]
It really depends on your platform. You can create a [system v init script](https://github.com/fhd/init-script-template) or [systemd service file](https://www.freedesktop.org/software/systemd/man/systemd.service.html). Sorry this question is bit out of scope for the issue board and is a more general java question + platform specific. There should be plenty of resources out there to help (eg. [Running a Java process from Systemd](https://superuser.com/questions/944244/running-a-java-process-from-systemd))
