### ISSUE TITLE
Hamcrest upgrade planned?

### ISSUE THREAD

**Issue by volphy** [dropwizard/dropwizard#2437]
Is there Hamcrest upgrade to 2.0.0.0 planned?

Hamcrest 2.x supports Java 7+ better (`@SafeVarargs`) and improved support for Java 8 i 9 is being discussed.

Hamcrest 1.x is not developed anymore.

**Comment by joschi** [comment]
@volphy Feel free to provide a pull request fro the upgrade.

**Comment by volphy** [comment]
I have created one:
https://github.com/dropwizard/dropwizard/pull/2443

**Comment by joschi** [comment]
@volphy Thanks for your contribution!

After thinking a little longer about the issue, I'd prefer to remove Hamcrest from Dropwizard completely. It's only been used in tests and shouldn't "bleed" into the public artifacts of Dropwizard.

After the removal of Hamcrest, it's completely up to the users of Dropwizard which matching library they want to use. Dropwizard itself is using AssertJ.

**Comment by volphy** [comment]
Good idea. I agree that Hamcrest does not need to be in Dropwizard's BOM.
