### ISSUE TITLE
*Question* Understanding the relation between jersey client and server 

### ISSUE THREAD

**Issue by oliver-steinbrecher** [dropwizard/dropwizard#2438]
I'd like to understand the relation between the dropwizard jersey server and the client in order to pass authentication details to a downstream service call.  There should be some way for linking the ContainerRequest and the ClientRequest . But I'm struggling with setting this up. 

My working setup:
- dropwizard 1.3.5
- Weld CDI linked with the jersey HK2 internal CDI

**Comment by joschi** [comment]
@oliver-steinbrecher Which details make you struggle?

Also feel free to use the Dropwizard user mailing list for generic questions:
https://groups.google.com/forum/#!forum/dropwizard-user

**Comment by oliver-steinbrecher** [comment]
I'd like to implement a scenario like this:
https://stackoverflow.com/questions/24995307/jersey-2-filter-uses-container-request-context-in-client-request-filter 

The idea is to have a proper client filter which can access the containerRequestContext. The container context then contains authentication details which I an reuse in the clients downstream call. 
```
public class RequestIdClientRequestFilter implements ClientRequestFilter {

    private ContainerRequestContext containerRequestContext;

    public RequestIdClientRequestFilter(ContainerRequestContext containerRequestContext) {
        this.containerRequestContext = containerRequestContext;
    }

    @Override
    public void filter(ClientRequestContext clientRequestContext) throws IOException {
        String value = containerRequestContext.getProperty("property-name");
        clientRequestContext.getHeaders().putSingle("MyHeader", value);
    }
}
```
