### ISSUE TITLE
Async JerseyHttpClient max threads and maxconnections

### ISSUE THREAD

**Issue by arpit728** [dropwizard/dropwizard#2440]
In jersey client configuration there are two parameters as described below.

maxThreads: 128
maxConnections: 1024

If I am making http calls asynchronously can this 128 threads acquire 1024 http connections. If not then it will not make any sense to keep maxConnections > maxThreads then why there default values are given that way.

**Comment by minisu** [comment]
I suggest that you read [this section](https://hc.apache.org/httpcomponents-client-ga/tutorial/html/connmgmt.html) of the Apache HTTP Client documentation. It explains how connections are managed and how they relate to threads.
