### ISSUE TITLE
Efficient readiness check

### ISSUE THREAD

**Issue by aschilling** [dropwizard/dropwizard#2447]
Hi everybody,

I am developing a microservice using Dropwizard which runs within Kubernetes. Kubernetes has the concept of readiness checks which allows it to assess whether a service is ready to receive incoming requests.

Is there any functionality in Dropwizard which can be used to assess wether the service is ready to serve external requests? I know that I could use period curls of a public API endpoint such as version, however, I was hoping that there is a lightweight alternative for such functionality. Maybe some mechanism which corresponds with the following startup message of the jetty server

`INFO  [2018-07-27 15:10:51,036] org.eclipse.jetty.server.Server: Started @9738ms` 

Best regards
Andreas

**Comment by joschi** [comment]
> Is there any functionality in Dropwizard which can be used to assess wether the service is ready to serve external requests?

@aschilling That's pretty much what health checks are for:
https://www.dropwizard.io/1.3.5/docs/manual/core.html#health-checks

**Comment by isaki-x** [comment]
If you want the exact second the thing is available, add a `Managed` object that is the very last thing you register in your `run` method for your application that drops a file or some other thing that lets you know its ready. You could also send your logging to syslog and watch that way or just grep the log.

Rough idea:

```Java
public class HelloWorld implements Managed {
    @Override
    public void stop() throws Exception {
        // Tear down notification?
    }

    @Override
    public void start() throws Exception {
        // Do your notification here.
    }
```
