### ISSUE TITLE
Dropwizard sessions leak memory

### ISSUE THREAD

**Issue by dannyqiu** [dropwizard/dropwizard#2455]
From what I have gathered, the recommended way to support sessions in Dropwizard is to add a `SessionHandler()` to the environment:

```java
environment.servlets().setSessionHandler(new SessionHandler());
```

This however, leads to a memory leak with `org.eclipse.jetty.server.session.SessionData` objects not being cleaned up. I have set the max inactive interval and session cache eviction policy to `SessionCache.EVICT_ON_INACTIVITY`, which means that session should expire after 1s of inactivity. Profiling the live objects on the heap in jmap show the following, after repeated `curl` requests to the server:

```console
num   #instances      #bytes  class name
-----------------------------------------------------------------------------------------------
31:         1315      126240  org.eclipse.jetty.server.session.SessionData
43:         1315       63120  org.eclipse.jetty.server.session.Session
44:         1315       63120  org.eclipse.jetty.server.session.Session$SessionInactivityTimeout
```

These session objects are never cleaned up and eventually lead to an OOM.

After a little bit of investigation, the issue seems to be coming from https://github.com/dropwizard/dropwizard/blob/master/dropwizard-jetty/src/main/java/io/dropwizard/jetty/ContextRoutingHandler.java#L18
The class extends `AbstractHandler` instead of `AbstractHandlerContainer` (and doesn't override https://github.com/eclipse/jetty.project/blob/jetty-9.4.x/jetty-server/src/main/java/org/eclipse/jetty/server/handler/AbstractHandlerContainer.java#L74). This is necessary for the session cleanup, because the children `SessionHandler` for all contexts need to be discovered by the jetty server.

The cleanup is triggered by jetty hosuekeeper's call to `scavenge()` in the `SessionHandler()`
- https://github.com/eclipse/jetty.project/blob/jetty-9.4.x/jetty-server/src/main/java/org/eclipse/jetty/server/session/SessionHandler.java#L1276
- https://github.com/eclipse/jetty.project/blob/jetty-9.4.x/jetty-server/src/main/java/org/eclipse/jetty/server/session/DefaultSessionIdManager.java#L472
- https://github.com/eclipse/jetty.project/blob/jetty-9.4.x/jetty-server/src/main/java/org/eclipse/jetty/server/session/DefaultSessionIdManager.java#L525

The call to `_server.getChildHandlersByClass(SessionHandler.class);` returns an empty list because when examining the chain of handlers, `ContextRoutingHandler` hides the fact that it contains `MutableServletContextHandler` because it doesn't expose its children handlers correctly.

I think the solution would be to have `ContextRoutingHandler` extend `AbstractHandlerContainer` and override `expandChildren(...)`, but I will defer to the maintainers, who will probably understand this better!

---
Update:
It seems that more than just the session data contains a memory leak - there is a also a leak with the `SSLSessionImpl`, which shows in jmap:

```console
num   #instances      #bytes  class name
-----------------------------------------------------------------------------------------------
 6:       188528    19661252  sun.security.ssl.SSLSessionImpl
28:       188528     3095728  sun.security.ssl.SSLSessionId
```

**Comment by jplock** [comment]
Thank you for the detailed write up!

**Comment by jplock** [comment]
@dannyqiu I created https://github.com/dropwizard/dropwizard/pull/2460 to fix this issue.  Could you see if that fixes the issue you were experiencing?

**Comment by jraylee** [comment]
Thanks for the quick response @jplock. I tested out your patch and can confirm that I no longer see the memory leak and sessions are getting cleaned up as expected.
