### ISSUE TITLE
Include all apache ConnectionPool metrics

### ISSUE THREAD

**Issue by leoconco** [dropwizard/dropwizard#2459]
Current implementation of the ManagedPooledDataSource in dropwizard-db misses the metrics for created, borrowed, reconnected, released, releasedIdle, returned and removeAbandoned metrics, we should include them.

**Comment by jplock** [comment]
Mind submitting a pull request?

**Comment by leoconco** [comment]
Sure, added https://github.com/dropwizard/dropwizard/pull/2475

**Comment by joschi** [comment]
Closed via #2475.
