### ISSUE TITLE
https://dropwizard.io has invalid certificate

### ISSUE THREAD

**Issue by kisg** [dropwizard/dropwizard#2477]
https://dropwizard.io has invalid certificate (looks like it is a certificate from github.com)

https://www.dropwizard.io works fine.

**Comment by joschi** [comment]
Thanks for reporting this.

GitHub currently doesn't support multiple CNAMEs and thus also doesn't support multiple (or wildcard) SSL certificates via GitHub Pages:
https://help.github.com/articles/troubleshooting-custom-domains/#multiple-domains-in-cname-file

FWIW, http://dropwizard.io/ already redirects to https://www.dropwizard.io:
```text
$ curl -I http://dropwizard.io/
HTTP/1.1 301 Moved Permanently
Server: GitHub.com
Date: Sun, 02 Sep 2018 16:32:00 GMT
Content-Type: text/html
Content-Length: 178
Location: https://www.dropwizard.io/
X-GitHub-Request-Id: C0EB:4A13:3CD02B2:4EE8200:5B8C1080
```
