### ISSUE TITLE
Invalid FormDataBodyPart of request in TeeFilter

### ISSUE THREAD

**Issue by aschilling** [dropwizard/dropwizard#2478]
Hi everybody,

when using the TeeFilter to log request contents as it is described in here (https://logback.qos.ch/manual/layouts.html#AccessPatternLayout) there is a problem in dropwizard.

In particular when issuing a POST request, there is the attribute "org.glassfish.jersey.media.multipart.FormDataMultiPart" in the ServletRequest. Moreover, if one calls the method getFields() to iterate over the various FormDataBodyPart of the request it is possible to call getName() on any FormDataBodyPart. 

To do so I am using the following request:

```
FormDataMultiPart multiPartRequest = (FormDataMultiPart) request.getAttribute("org.glassfish.jersey.media.multipart.FormDataMultiPart");
            
Map<String,List<FormDataBodyPart>> fields = multiPartRequest.getFields();
            for (String key:fields.keySet()){
                System.out.println(key);
                
                for(FormDataBodyPart pname : fields.get(key)){
                    System.out.println(pname.getName());
                    System.out.println(pname.getValue());
                }
```

However, when calling the method getValue() on any FormDataBodyPart the following exception occurs:

```
java.lang.IllegalStateException: No multipart config for servlet org.eclipse.jetty.server.Request.getParts(Request.java:2331)
org.eclipse.jetty.server.Request.getParts(Request.java:2319)
```
This is even more strange, as there is no field of type binary in the request.

Best regards
Andy

**Comment by nickbabcock** [comment]
If you remove TeeFilter usage does the code work?

**Comment by nickbabcock** [comment]
Without further context or a minimal reproducible example, this issue will be closed
