### ISSUE TITLE
BiDiGzipHandler should use interceptor pattern, not wrapped input/output streams

### ISSUE THREAD

**Issue by joakime** [dropwizard/dropwizard#2479]
This is a request to reevaluate the BiDiGzipHandler.

The current BiDiGzipHandler attempts to wrap the input/output streams to accomplish what the old BiDiGzipFilter used to do.

The wrapping of servlet input streams and output streams as performed by BiDiGzipHandler is not compatible with Servlet 3.1 and Async I/O.

The Jetty project's own GzipHandler (supporting decompression of request bodies, and compression of response bodies) is performed via the interceptor features / patterns present in Jetty, to allow the Servlet 3.1 Async I/O features to function properly.

Is it still needed?  the built-in GzipHandler does a lot now.
Is 'deflate' support still needed? (in the Eclipse Jetty's experience less than 0.01% of requests use deflate exclusively, and nearly 100% of requests that declare that they accept compression use gzip, with a small (and growing) number supporting brotli (which has no java solution yet).

**Comment by joakime** [comment]
Has 2.0.0 been started on a branch I can look at?

**Comment by jplock** [comment]
@joakime `master` is currently targeted for 2.0.0 but we haven't released any release candidates yet due to https://github.com/dropwizard/dropwizard/issues/2418.  If you'd be willing to submit a PR, we'll happily review it.  Thanks!

**Comment by nickbabcock** [comment]
Other than `BiDiGzipHandler` stripping `Content-Length: x` after the input has been inflated, and `BiDiGzipHandler` and supporting deflate, `GzipHandler` is a drop in replacement (I commented out the couple tests for those) and everything passed.

I'm fine with moving past deflate, but I'm not so sure I understand jetty not stripping content-length if the content-encoding header is also stripped.

**Comment by joakime** [comment]
@nickbabcock regarding not stripping `Content-Length`, that is an excellent question.  I'll consult with @gregw and see what's going on.

**Comment by nickbabcock** [comment]
Excellent, seems like the next version of jetty will have this fix. Until released, I'll mark this issue as blocked
