### ISSUE TITLE
Upgrade to Jetty 9.4.12

### ISSUE THREAD

**Issue by joakime** [dropwizard/dropwizard#2480]
Jetty 9.4.12 is now out.

It includes many bug fixes and improvements to HTTP/2 and general security.

If you choose to upgrade to Jetty 9.4.12, please be aware of the changed default Cipher exclusion list.

See eclipse/jetty.project#2807 for details.

**Comment by nickbabcock** [comment]
I'm all for upgrading to Jetty 9.4.12, but I do have one concern about the change in the default cipher exclusion list. The change in the exclusion list from 9.2 to 9.3 (dropwizard 0.9 to 1.0) effectively disallowed java 7 clients. We obviously don't want to blindside anyone with a patch bump (9.4.11 to 9.4.12), so I'm assuming this cipher suite change must be extremely minor, as in clients that support `TLS_RSA_*` already support more secure ciphers, so they won't care if it is disabled.

**Comment by joakime** [comment]
The general policy is to have defaults that follow industry practices for security.
The change from 9.2 to 9.3 followed industry practice.

The change from 9.4.11 to 9.4.12 has the same potential impact, the more locked down the cipher suite the less likely old clients that haven't updated themselves will be able to connect.

Upgrading to Java 11 will essentially cause the same exclusions as 9.4.12 on the server side (RSA ciphers are disabled), but in the Java 11 case it's disabled at the JVM.
Upgrading to Java 12 will cause all DES ciphers to be disabled at the JVM too.

The kind of change that 9.4.12 brings to the table isn't new.
The default behaviors have to be secure.
It's up to the individual deployments to evaluate the new security reality by configuring their own environment to make themselves intentionally vulnerable.

**Comment by nickbabcock** [comment]
Oh yeah, I wholeheartedly agree with Jetty's secure by default policies, I just want to make sure there is enough communication on our side that basically says "by default, enforces tls clients to support forward secrecy", so that if users check the release notes they at least have that in the back in of their minds when issues crop up.
