### ISSUE TITLE
Extra logging on Health Check

### ISSUE THREAD

**Issue by ldm810** [dropwizard/dropwizard#2483]
Currently, I have my logging set to `INFO` level.
I am overriding the `execute` method of each custom Health Check I implement. In that override, I log error messages, if the health check is unhealthy. However, I still do not see stack traces when the health check returns a 500. I assume this is because the `deadlock` healthcheck is returning false.

Is there a way to log the deadlock healthcheck or Even better, log the result of the healthcheck when it is unhealthy?

**Comment by nickbabcock** [comment]
> log the result of the healthcheck when it is unhealthy

Generically, no. You could only get that functionality for the health checks you create, by manually logging the exception. https://github.com/dropwizard/metrics is a more appropriate repo to talk about logging on unhealthy health checks.

**Comment by ldm810** [comment]
Thanks @nickbabcock
