### ISSUE TITLE
Register InjectValidatorBundle by Default

### ISSUE THREAD

**Issue by nickbabcock** [dropwizard/dropwizard#2484]
#2432 solves #2234, but it is a bundle that has to be registered for users that want the context injection in constraint validators. The bundle doesn't appear to have any downsides (backwards compatible, no new dependencies), so I am of the mind that the bundle should be registered by default. However, no other dropwizard bundles are registered by default (does that mean this bundle can be implemented in another way?). So I think there are a couple outcomes possible:

1. Register the bundle by default
2. Keep current method of having users register the bundle
3. Implement the feature not via a bundle and register it by default

Thoughts?

**Comment by jplock** [comment]
If 3. is possible, I'd probably lean toward that.  Otherwise 1. if there are no downsides.

**Comment by alex-shpak** [comment]
Hi!

As I mentioned in PR, I didn't find way to share instance of `MutableValidatorFactory` between `initialize` and `run` methods, that's why it's implemented as `Bundle`

**Comment by nickbabcock** [comment]
Initially I tried to see if we could register it in `AbstractServerFactory`, but that lacks access to the bootstrap class.

While not my first place to fit the code, inside `EnvironmentCommand::run` I was able to get the following to work (eg: run the e2e injection validation test without the bundle)

```diff
         bootstrap.run(configuration, environment);
+
+        final ConstraintValidatorFactory factory = bootstrap.getValidatorFactory().getConstraintValidatorFactory();
+        if (factory instanceof MutableValidatorFactory) {
+            environment.jersey().register(new GetResourceContextFeature(context -> {
+                ConstraintValidatorFactory validatorFactory = context
+                    .getResource(InjectingConstraintValidatorFactory.class);
+
+                ((MutableValidatorFactory)factory).setValidatorFactory(validatorFactory);
+            }));
+        }
+
         application.run(configuration, environment);
```

@alex-shpak do you think something like could work, and make sense?

**Comment by alex-shpak** [comment]
@nickbabcock Hi!
Yes, this should work. I didn't want to intrude into `EnvironmentCommand.run()` method since it's nice and clean now.

To make it nice I see two options:
1. Change `Environment` constructor to accept `ValidatorFactory`. This requires changing quite of tests code. This looks like more proper solution, but more changes. Also I'm not sure what to do with `Environment.setValidator()` method.
2. Add additional constructor for `Environment` that accepts `ValidatorFactory` and calls original constructor as well as validator logic. Like this:
```java
public Environment(String name,
                       ObjectMapper objectMapper,
                       ValidatorFactory validatorFactory,
                       MetricRegistry metricRegistry,
                       @Nullable ClassLoader classLoader,
                       HealthCheckRegistry healthCheckRegistry) {
        this(name, objectMapper, validatorFactory.getValidator(), metricRegistry, classLoader, healthCheckRegistry);

        ConstraintValidatorFactory constraintValidatorFactory =
            validatorFactory.getConstraintValidatorFactory();

        if (constraintValidatorFactory instanceof MutableValidatorFactory) {
            jersey().register(new SetValidatorFactoryFeature(
                (MutableValidatorFactory) constraintValidatorFactory
            ));
        }

    }

    public static class SetValidatorFactoryFeature implements Feature {

        @Inject
        private ResourceContext context;

        private final MutableValidatorFactory mutableValidatorFactory;

        public SetValidatorFactoryFeature(MutableValidatorFactory mutableValidatorFactory) {
            this.mutableValidatorFactory = mutableValidatorFactory;
        }

        @Override
        public boolean configure(FeatureContext featureContext) {
            ConstraintValidatorFactory originalFactory =
                context.getResource(InjectingConstraintValidatorFactory.class);

            mutableValidatorFactory.setValidatorFactory(originalFactory);
            return true;
        }
    }
```

I can create PR for preferable case!

**Comment by alex-shpak** [comment]
I created two PRs https://github.com/dropwizard/dropwizard/pull/2521 and https://github.com/dropwizard/dropwizard/pull/2522 to solve this, both of them works
