### ISSUE TITLE
NoClassDefFoundError: com/google/common/util/concurrent/FutureFallback

### ISSUE THREAD

**Issue by james-millner** [dropwizard/dropwizard#2485]
Hi,

I'm having trouble upgrading to later versions of Dropwizard. The error I'm getting is:

NoClassDefFoundError: com/google/common/util/concurrent/FutureFallback 

I can see that the class has been deprecated, but what version of Guava is Dropwizard using? My pom configuration currently looks like this: 
`<dependency>
  <groupId>io.dropwizard</groupId>
  <artifactId>dropwizard-core</artifactId>
  <version>1.3.5</version>
</dependency>
<dependency>
  <groupId>io.dropwizard</groupId>
  <artifactId>dropwizard-views-freemarker</artifactId>
</dependency>
<dependency>
  <groupId>io.dropwizard</groupId>
  <artifactId>dropwizard-auth</artifactId>
</dependency>`

**Comment by joschi** [comment]
https://github.com/dropwizard/dropwizard/blob/7acede06f2df73f1db80461e44ba23708eb6bdd5/dropwizard-bom/pom.xml#L22

**Comment by james-millner** [comment]
@joschi Even if I declare a dependency for Guava Version 24.0-jre before my Dropwizard dependencies I still receive the same issue.

Does this require that I remove the independent dependencies and simply provide a reference to the dropwizard-bom?

**Comment by james-millner** [comment]
@joschi After further analysis it looks like FutureFallback has been removed in Guava versions 20 & above
