### ISSUE TITLE
Conflicting guava library on classpath

### ISSUE THREAD

**Issue by Tibor17** [dropwizard/dropwizard#2486]
I am using dropwizard and querydsl and they have conflict because the version of guava library is different and incompatible classes.
Please use `maven-shade-plugin` and reallocate the packages `com.guava.common` to `com.querydsl.core.com.google.common` which avoids these problems in many projects and many conflicting dependencies.
It is better than removing guava and better than writing own utilities.

**Comment by joschi** [comment]
Thanks for your feedback.

I'd recommend posting general feedback like this and questions about using Dropwizard to the dropwizard-user mailing list: https://groups.google.com/forum/#!forum/dropwizard-user

FWIW, Dropwizard 2.0.x will get rid of the dependency to Guava, see #2400.
