### ISSUE TITLE
Support json log exception type configuration

### ISSUE THREAD

**Issue by mattnelson** [dropwizard/dropwizard#2489]
The exception log format defaults[1,2] to root cause first for all types(console,file,json,etc...). With the non-json types the layout can be overridden to standard stack traces. JSON log format it not currently configurable. Can the option to configure exception implementations be added?

* `exception`
  * https://logback.qos.ch/manual/layouts.html#ex
  * https://github.com/qos-ch/logback/blob/v_1.2.3/logback-classic/src/main/java/ch/qos/logback/classic/pattern/ThrowableProxyConverter.java
* `xException`
  * https://logback.qos.ch/manual/layouts.html#xThrowable
  * https://github.com/qos-ch/logback/blob/v_1.2.3/logback-classic/src/main/java/ch/qos/logback/classic/pattern/ExtendedThrowableProxyConverter.java
* `rootException`
  * https://logback.qos.ch/manual/layouts.html#rootException
  * https://github.com/qos-ch/logback/blob/v_1.2.3/logback-classic/src/main/java/ch/qos/logback/classic/pattern/RootCauseFirstThrowableProxyConverter.java

`exception` and `xException` appear be identical due to the extended packaging data[3] being disabled by default.

[1] https://www.dropwizard.io/1.3.5/docs/manual/configuration.html#logging
[2] https://github.com/dropwizard/dropwizard/blob/v1.3.5/dropwizard-json-logging/src/main/java/io/dropwizard/logging/json/EventJsonLayoutBaseFactory.java#L92
[3] https://logback.qos.ch/manual/configuration.html#packagingData

**Comment by nickbabcock** [comment]
It looks like json exception logging is somewhat configurable if someone where to override `EventJsonLayoutBaseFactory::createThrowableProxyConverter` (ie define your own logging type like `json2`), but if you have something else in mind, I'm open to suggestions!

**Comment by mattnelson** [comment]
@nickbabcock Any objections if I start working on this? Do you have any other suggestions for resolving this within dropwizard? I could impleent it internally with a custom type like you mentioned, but I would like to solve upstream if possible.

**Comment by nickbabcock** [comment]
Certainly, go ahead! The design makes sense (keeping the same terminology as logback to make it easier to look up what each field's effect is). Hopefully you can leverage a lot of logback's code to implement your idea. If it needs 2k of code to implement, I might have reservations if the feature is really worth the maintenance cost 😄

**Comment by arteam** [comment]
Closed via #2501
