### ISSUE TITLE
Preventing the assets from being compiled into the Jar

### ISSUE THREAD

**Issue by JorricksTU** [dropwizard/dropwizard#2494]
Hello everyone,

I was looking for a way to disable the static assets being compiled into the jar file.
Why? I am making changes to the javascript and css files while I'm running the server, however, I need the calculated results that the API provides me. Hence it's a bit of an annoying process to rebuild and launch the whole package for every change.

I've looked into this post: https://github.com/dropwizard/dropwizard/issues/54 , however, I can not seem to get this work.
Is there a newly updated method or should I open a support ticket for the fact that I get 404's using this the above-shown technique?

**Comment by nickbabcock** [comment]
If you are looking to serve static assets from files, you're probably best to register [Jetty's DefaultServlet](https://www.eclipse.org/jetty/javadoc/current/org/eclipse/jetty/servlet/DefaultServlet.html) via `environment.servlets().addServlet(...)`

**Comment by nickbabcock** [comment]
Closing this issue. If the provided solution is not appropriate, please respond to have this issue reexamined.
