### ISSUE TITLE
Upgrade jetty to latest 9.4.12 in 1.2.x release

### ISSUE THREAD

**Issue by debraj-manna** [dropwizard/dropwizard#2495]
Jetty has already been upgraded to 9.4.12 in master. Can we also upgrade the jetty in 1.2.x release?

**Comment by joschi** [comment]
@debraj-manna Jetty 9.4.12 introduced some breaking changes and in the interest of backwards-compatibility, we won't back-port this update into Dropwizard 1.2.x or 1.3.x.

**Comment by bobtiernay-okta** [comment]
This version of Jetty fixes a critical SSL performance bug that pegs CPU. I think it would be useful to point this out in the docs if not backported.

When is the ETA of the 2.0.0 release which includes the fix? Currently I’ve had to override the Jetty versions in the pom which isn’t ideal.

**Comment by arteam** [comment]
Jetty 9.4.12 is a pretty big release: even the Jetty developers reach out to us help to upgrade. There's also some traction in upgrading to it: I've seen reports of major bugs in Jetty 9.4.11 and questions from users about it, so I think it warrants to be included in Dropwizard before 2.0.0.

I will try to cut a minor release, if it doesn't break compatibility, otherwise we can do a 1.4.* release.

**Comment by debraj-manna** [comment]
Thanks @arteam .

If you can provide us some idea by when can we expect the minor 1.2.x release with Jetty 9.4.12 or 1.4.* It will really help us.

**Comment by mattnelson** [comment]
YMMV, but we used dependencyManagement to uplift to 9.4.12.v20180830 a few weeks back and didn't notice any apparent regressions.

@arteam @joschi Do you have an idea of the breaking changes to look for?

https://www.eclipse.org/lists/jetty-announce/msg00124.html

**Comment by debraj-manna** [comment]
@arteam - Can we reopen this issue?

**Comment by arteam** [comment]
Done

**Comment by boatmisser** [comment]
Is there any further update on either the 2.0.0 release date or a potential 1.4.* update with jetty 9.4.12?

**Comment by debraj-manna** [comment]
> Is there any further update on either the 2.0.0 release date or a potential 1.4.* update with jetty 9.4.12?

I am also interested to know the same.

**Comment by martinmalek** [comment]
Bump

**Comment by arteam** [comment]
Sure, I can make another 1.4.* release.

**Comment by volphy** [comment]
If reaching stable 2.0.0 is going to take some time, it makes sense to create 1.4 branch.

**Comment by debraj-manna** [comment]
@arteam - Any idea when can we expect a 1.2.x release with Jetty 9.4.12 ?

**Comment by joschi** [comment]
Sorry, there won't be another Dropwizard 1.2.x release. Please upgrade to Dropwizard 1.3.x.

This being said, Dropwizard 1.3.9 will come with Jetty 9.4.14.v20181114, see #2592.

**Comment by debraj-manna** [comment]
@joschi - 1.3.8 is using jetty 9.4.11. Any idea when can we expect 1.3.9 to be released ?
