### ISSUE TITLE
DropwizardTestSupport sets ConfigurationFactoryFactory to early

### ISSUE THREAD

**Issue by manuel-hegner** [dropwizard/dropwizard#2496]
in [DropwizardTestSupport](https://github.com/dropwizard/dropwizard/blob/fb58944deddfa2925adb2fd4a3b4c3dba5998cd7/dropwizard-testing/src/main/java/io/dropwizard/testing/DropwizardTestSupport.java#L221) the test support class sets the bootstrap ConfigurationFactoryFactory before initializing the application. Should this not happen after the initialization since the application itself could change the FactoryFactory?

**Comment by nickbabcock** [comment]
Is there a use case where an application sets their factory in initialization and then a test overrides that one? I have a thought brewing, but if you have a specific example that you're encountering, I'd love to hear it. All tests pass either way.

**Comment by manuel-hegner** [comment]
We set the factory to a JSONConfigurationFactoryFactory in our app so that the config is parsed as json instead of yaml.

**Comment by nickbabcock** [comment]
Yes that would lead to an incorrect order. Makes sense, feel free to create a PR with the change + test so that we don't regress on that behavior
