### ISSUE TITLE
Database connections active after database disconnected/reconnected

### ISSUE THREAD

**Issue by shterrett** [dropwizard/dropwizard#2499]
After a database went down and was restarted, the database pool was almost completely in use. Typically, the stats are `pool_size: 9; active: 1`; however, after the restart they were `pool_size: 9, active: 8`. The actual workload had not changed.

I have tried various combinations of the `checkConnection...` parameters, but all of them consistently leave `pool_size: N; active: N-1` after a database restart. The `checkConnection...` parameters do impact the stats by reducing N, often below the minimum threshold. 

We observed this with Oracle DB; however, I have also reproduced it with PostgreSQL.

I have created a [minimal reproduction](https://github.com/shterrett/dropwizard-db-test) that can be used to observe this behavior.

**Comment by arteam** [comment]
I am wondering if it might be an artifact of poor handling of networking failures by the Tomcat JDBC pool. I believe the HikariCP author run some tests: https://github.com/brettwooldridge/HikariCP/wiki/Bad-Behavior:-Handling-Database-Down, and found that the Tomcat JDBC pool can stuck during re-connecting to the database until the OS drops the TCP connections by the system timeout.
