### ISSUE TITLE
Include default requestLog format string in documentation

### ISSUE THREAD

**Issue by novaterata** [dropwizard/dropwizard#2500]
I'm trying to just slightly tweak the requestLog, but I can't for the life of my find the default format string. Please include it in the entry for requestLog

**Comment by nickbabcock** [comment]
Yes, it is missing and should be added to the documentation. For the time being, the request log format is:

```
%h %l %u [%t{dd/MMM/yyyy:HH:mm:ss Z, <tz-id>] "%r" %s %b "%i{Referer}" "%i{User-Agent}" %D
```
