### ISSUE TITLE
how to debug in IntelliJ IDEA ?

### ISSUE THREAD

**Issue by honglou2001** [dropwizard/dropwizard#2510]
how to debug in IntelliJ IDEA ? could some provide some info about this? thanks .

**Comment by honglou2001** [comment]
debug a restful API (via HTTP request).   could you provide some info about this? thanks

**Comment by RohanNagar** [comment]
What do you want to know? You can start the application in IntelliJ and then issue a [curl](https://linux.die.net/man/1/curl) request to the HTTP you want to test.

**Comment by RohanNagar** [comment]
Maintainers, you can probably close this issue..
