### ISSUE TITLE
ConfiguredCommand termination 

### ISSUE THREAD

**Issue by lfoppiano** [dropwizard/dropwizard#2518]
Dear everybody, 
    I have a question. I'm developing an application which has a part of it that is ran via command line (e.g. the database preparation).

In order to do that I have set up a set of ConfiguredCommands which I have exteded to do my stuff, however I expect the application to terminate once the command has ran. 

How can I do that? Just call System.exit(1) at the end or is there a more elegant way? 
BTW I'm using version 1.3.5 with java 8.

**Comment by joschi** [comment]
> In order to do that I have set up a set of ConfiguredCommands which I have exteded to do my stuff, however I expect the application to terminate once the command has ran.

And it will do so, unless there's something preventing the JVM to exit.

Maybe you could provide a minimal example to reproduce your issue?

**Comment by lfoppiano** [comment]
Thanks @joschi for the tip, indeed seems a problem from my code (when left the command empty it works as expected).
