### ISSUE TITLE
No such servlet JerseyServletContainer 

### ISSUE THREAD

**Issue by ansarisufiyan777** [dropwizard/dropwizard#2520]
I am facing this issue rarely when I start the application on the prod environment after running two or three times it is getting failed to start the server, and then when I restart the application it works.

I have attached the screenshot of the error.

![dropwizard servelet](https://user-images.githubusercontent.com/16426709/46477526-769b8f80-c808-11e8-9c8e-13028f836785.PNG)

Thanks

**Comment by joschi** [comment]
@ansarisufiyan777 Could you provide a minimal example project which we can use to reproduce the issue?

**Comment by ansarisufiyan777** [comment]
Hi @joschi,
Since this error is not coming in the local environment, I can't really depict the same in the example project. Can you please explain here the possible scenarios which can generate the above error.

Thanks

**Comment by ansarisufiyan777** [comment]
Found the issue, I was doing my environment setup on a different thread not on the `main` thread, I moved all the environment setup to the main thread, I feel now it is working fine as expected.

`environment.healthChecks().register("subscription", new SubscriptionHealthCheck());

        environment.jersey().register(new SubscriptionResource());
        environment.jersey().register(new CacheResource());

        environment.getApplicationContext().getServletHandler().addServletWithMapping(
                SubscriptionWebServlet.class, "/events/*"
        );


        environment.getApplicationContext().getServletHandler().addServletWithMapping(
                RecoveryWebServlet.class, "/replayRequest/*"
        );`
