### ISSUE TITLE
DropwizardTestSupport should clean system properties (config overrides) on service startup failure

### ISSUE THREAD

**Issue by coderunner** [dropwizard/dropwizard#2523]
We had a few test classes using both `DropwizardAppRule` and `DropwizardClientRule` (`DropwizardClientRule` around `DropwizardAppRule`). The service started by the `DropwizardAppRule` would fail on startup because of some environment problem. The _config override_ properties would stick around for the following tests causing unexpected behavior.

The problem seems to be that in the `before` method, overrides are set as system properties but are not cleaned/reset in case the service fails to start.

```java
import com.fasterxml.jackson.annotation.JsonProperty;
import io.dropwizard.Application;
import io.dropwizard.Configuration;
import io.dropwizard.setup.Environment;
import io.dropwizard.testing.ConfigOverride;
import io.dropwizard.testing.DropwizardTestSupport;
import io.dropwizard.testing.ResourceHelpers;
import org.junit.Test;
import org.junit.runners.model.Statement;

import static junit.framework.TestCase.assertNull;

public class IntTestReproduce {

    @Test
    public void dropwizardTestSupportShouldCleanSystemPropertiesOnServiceStartupFailure() {
        assertNull(System.getProperty("dw.dummyProperty"));

        final DropwizardTestSupport<TestConfiguration> testSupport = new DropwizardTestSupport<>(TestService.class,
                        ResourceHelpers.resourceFilePath("config.yml"),
                        ConfigOverride.config("dummyProperty", "dummy"));

        try {
            testSupport.before();
        } catch (Exception e) {
            // expected since the service will throw on startup
        }

        // Since ExternalResource will not call `after()` on exception, maybe DropwizardTestSupport should
        // clean system properties. Otherwise the properties stick around and might affect the following tests.
        assertNull(String.format("System property is not null. The value is [%s]",
                System.getProperty("dw.dummyProperty")),
                System.getProperty("dw.dummyProperty"));
    }

    public static class TestService extends Application<TestConfiguration> {

        @Override
        public void run(TestConfiguration testConfiguration, Environment environment) throws Exception {
            throw new RuntimeException("fail");
        }

    }
    public static class TestConfiguration extends Configuration {

        private String dummyProperty;
        @JsonProperty("dummyProperty")
        public String getDummyProperty() {
            return dummyProperty;
        }

        public void setDummyProperty(String dummyProperty) {
            this.dummyProperty = dummyProperty;
        }

    }

    private static final Statement TEST_STATEMENT = new Statement() {
        @Override
        public void evaluate() {

        }
    };
}
```

**Comment by nickbabcock** [comment]
Sorry to circle back on this so late, but I'm actually stumped on how the you're able to have the config overrides leak into other tests, as `DropwizardAppRule` removes them in the junit's `@After` life cycle, and according to the docs

> All `@After` methods are guaranteed to run even if a Before or Test method throws an exception

It's equivalent to:

```java
try {
    testSupport.before();
} catch (Exception e) {
} finally {
    testSupport.after();
}
```

Let me know if this issue is still prevalent and if a slightly better test case can be written (as `testSupport.after()` was omitted)

**Comment by coderunner** [comment]
@nickbabcock This has been a while and I've shift gears since then, but IIRC the problem is exactly that the `after` method is not called (and the clean up not performed on system properties) when the service fails/throws in the `run` method. This is not so bad because this is really an edge case that should not happen, but when it does, it makes the troubleshooting difficult since unrelated tests start failing as well.

**Comment by nickbabcock** [comment]
You are absolutely right, I didn't realize that that junit [documents that discrepancy](https://junit.org/junit4/javadoc/4.12/org/junit/rules/ExternalResource.html), so if `ExternalResource::before` throws, then `after` is disabled. This is a bug in dropwizard and will be fixed. Thank you!
