### ISSUE TITLE
Update release-notes.rst for 1.3.6 and 1.3.7

### ISSUE THREAD

**Issue by bobtiernay-okta** [dropwizard/dropwizard#2527]
It looks like these were never documented in https://github.com/dropwizard/dropwizard/blob/master/docs/source/about/release-notes.rst . Would be nice to add so that folks can understand the high level change set.

**Comment by bobtiernay-okta** [comment]
Thanks!

**Comment by carlzogheib** [comment]
Is there a reason why https://www.dropwizard.io/1.3.6/docs/ and https://www.dropwizard.io/1.3.7/docs/ are not a thing?
