### ISSUE TITLE
Dropwizard-example (Sorry for reissue my problem)

### ISSUE THREAD

**Issue by charbonnier666** [dropwizard/dropwizard#2531]
Sorry for re-post my problem...
I wish to have a working dropwizard-example project, but even i get branch 1.3.x and put 1.3.7 version on pom.xml i have some errors and problems building it... which (and where) i can get a working version ?

Thanks for your support 👍

**Comment by joschi** [comment]
@charbonnier666 Please post these kind of issues to the Dropwizard User mailing list at https://groups.google.com/forum/#!forum/dropwizard-user
