### ISSUE TITLE
Jersey configuration has a null Temp Dir?

### ISSUE THREAD

**Issue by Gaudon** [dropwizard/dropwizard#2532]
> WARN  [2018-10-17 13:10:23,882] org.glassfish.jersey.media.multipart.internal.MultiPartReaderClientSide: Cannot create temporary files. Multipart attachments will be limited to "4,096" bytes.

The path being provided to File.createTempFile is "C:\WINDOWS\MIME###########.tmp"

MultiPartReaderClientSide [tempDir is null]
```
if (properties.getBufferThreshold() != -1) {
    try {
        File.createTempFile("MIME", (String)null, tempDir != null ? new File(tempDir) : null).delete();
    } catch (IOException var5) {
        LOGGER.log(Level.WARNING, LocalizationMessages.TEMP_FILE_CANNOT_BE_CREATED(properties.getBufferThreshold()), var5);
    }
}
```

I don't remember this happening before , is this something I'm supposed to have configured in dropwizard to be passed to jersey? Is it an IDE/System property that dropwizard looks for (IntelliJ IDE).

Cheers

**Comment by nickbabcock** [comment]
I believe this is outside of Dropwizard's domain. Most online help points to stackoverflow: https://stackoverflow.com/questions/27589379/jersey-client-creation-error

You may have to play with it to get it to work. Let us know what the solution is / was and if it's something dropwizard should fix.
