### ISSUE TITLE
Authenticator : access request path

### ISSUE THREAD

**Issue by n1b0r** [dropwizard/dropwizard#2534]
Hello

Is there a way to get the requested url in my custom Authenticator ?

My auth mecanism needs the requested url to check if user is allowed to access resource.

nib

**Comment by FredDeschenes** [comment]
Don't know if this is still relevant, but you could write your own `AuthFilter`. The [`authenticate`](https://github.com/dropwizard/dropwizard/blob/master/dropwizard-auth/src/main/java/io/dropwizard/auth/AuthFilter.java#L132) method gives you access to the `ContainerRequestContext` which has the `URIInfo`.

But why not just use an [authorizer](https://www.dropwizard.io/1.3.9/docs/manual/auth.html#authorizer)?

**Comment by n1b0r** [comment]
Thanks for the information.
