### ISSUE TITLE
dropwizard-json-logging - add method, linenumber to loggerName

### ISSUE THREAD

**Issue by tapifolti** [dropwizard/dropwizard#2539]
While: dropwizard-json-logging is great, I miss the method and line number from the 'loggerName'.  As I see it is available in the ILoggingEvent's CallerData, as it is possible to log it in text with 'logFormat'.

**Comment by lutzhorn** [comment]
Which data of `ILoggingEvent` or of `StackTraceElement[] callerData = event.getCallerData();` do you want to include?

**Comment by tapifolti** [comment]
I would like to reproduce this log info, e.g.:
com.lateralreality.projectservice.admintasks.scheduled.GeneralReportResultToWebShop.reportProjectsOfWebShop:247 
which consist of: <fully qualified class name>.<method name>:<line number of the source code>

Right now I can access only the loggerName which is the  <fully qualified class name>, So method and line number would also be desirable.

**Comment by lutzhorn** [comment]
[`getCallerData`](https://logback.qos.ch/apidocs/ch/qos/logback/classic/spi/ILoggingEvent.html#getCallerData()) returns an [`StackTraceElement[]`](https://docs.oracle.com/javase/7/docs/api/java/lang/StackTraceElement.html?is-external=true). This is an array containing the stacktrace. Which element in this array would contain the call stack element you are interested in?

**Comment by tapifolti** [comment]
based on doc of StackTraceElement[]: "The frame at the top of the stack represents the execution point at which the stack trace was generated. " I suppose that is the log line of the code, which code location would be required. So the index is: 0.
