### ISSUE TITLE
How to override individual exception mappers

### ISSUE THREAD

**Issue by philipzhaoTS** [dropwizard/dropwizard#2552]
See comment here.
I want to override the `new LoggingExceptionMapper<Throwable>() {}`

But how do I do so? Is there any doc about it. I also use Dropwizard-Guicy with Guice injection.

https://github.com/dropwizard/dropwizard/blob/fb58944deddfa2925adb2fd4a3b4c3dba5998cd7/dropwizard-core/src/main/java/io/dropwizard/setup/ExceptionMapperBinder.java#L14

**Comment by nickbabcock** [comment]
Here are three examples of how to do it:

https://github.com/dropwizard/dropwizard/blob/a47351cae948e88d02b3367bf380121f54124305/dropwizard-e2e/src/main/java/com/example/app1/App1.java#L28-L55

So to override exception mappers, register your own.

Dropwizard-Guicy is outside the scope of this repo, so if you have an issue with the implementation, report it to that project appropriately.

**Comment by philipzhaoTS** [comment]
thank you for the example! That really helps!
