### ISSUE TITLE
Environment.lifecycle().executorService(...) might create single-threaded pools

### ISSUE THREAD

**Issue by efimovandr** [dropwizard/dropwizard#2553]
Following snippet suddenly creates a pool with at most one worker thread instead of N:
```
ExecutorService executorService = environment.lifecycle()
     .executorService("my-pool-%d")
    .maxThreads(N)
    .build();
```
Here is why: https://github.com/kimchy/kimchy.github.com/blob/master/_posts/2008-11-23-juc-executorservice-gotcha.textile

**Comment by minisu** [comment]
Confirmed. This code takes 10 seconds to execute (but only 1 second if you add `.minThreads(10)`):

```java
@Override
public void run(TestingConfiguration configuration, Environment environment) throws Exception {
    ExecutorService executorService = environment
        .lifecycle()
        .executorService("testing")
        .maxThreads(10)
        .build();

    long startTime = currentTimeMillis();
    CountDownLatch countDownLatch = new CountDownLatch(10);

    for(int i = 0; i < 10; i++) {
        executorService.submit(() -> {
            try {
                Thread.sleep(1000);
            } catch (InterruptedException e) {
                e.printStackTrace();
            }
            countDownLatch.countDown();
        });
    }

    countDownLatch.await();
    System.out.println("Done in " + (currentTimeMillis() - startTime) + " ms");
}
```

**Comment by xiaodong-xie** [comment]
If more fine grained controls are needed, probably need to set both `minThreads` and `workQueue`.

**Comment by minisu** [comment]
When looking closer, there's actually a [log.warn](https://github.com/dropwizard/dropwizard/blob/master/dropwizard-lifecycle/src/main/java/io/dropwizard/lifecycle/setup/ExecutorServiceBuilder.java#L102) printed if a user does this misconfiguration.

**Comment by efimovandr** [comment]
I think the API provided is misleading and people will keep making this mistake.

**Comment by nickbabcock** [comment]
> I think the API provided is misleading and people will keep making this mistake.

Now would be a great time if we want to rethink this. So if you have an idea or implementation in mind, I'd love to hear it, as I would agree it is easy to fall into this trap

**Comment by sergeiwp** [comment]
I think it makes sense to keep method naming closer to ThreadPoolExecutor, i.e. `coreThreads()` instead of `minThreads()`. Also worth referring [ThreadPoolExecutor doc](https://docs.oracle.com/javase/7/docs/api/java/util/concurrent/ThreadPoolExecutor.html) for the fields meaning.

**Comment by dennyac** [comment]
I've attempted to change the default behavior in this PR - https://github.com/dropwizard/dropwizard/pull/2797

We this change we will only have single-threaded pools if a user explicitly provides an unbounded queue.

Not opposed to changing naming conventions to match ```ThreadPoolExecutor``` if needed, but I feel minThreads/maxThreads seem like more meaningful names.
