### ISSUE TITLE
Why anonymous update allowed to log-level?

### ISSUE THREAD

**Issue by p-upadhyay** [dropwizard/dropwizard#2562]
Allowing an anonymous/unauthorized user to change the log-level is not a great security practice. Only authorized users should be able to modify the log-level. 

curl -X POST -d "logger=ROOT&level=DEBUG" localhost:8081/tasks/log-level

**Comment by nickbabcock** [comment]
No need to expose your admin port. You can also `setSecurityHandler` on the admin servlet

**Comment by p-upadhyay** [comment]
Okay. So It is not recommended to run admin port on the same port as the application? I thought with 'simple' server type, dropwizard allows that. Please correct me if I'm wrong.

**Comment by nickbabcock** [comment]
> It is not recommended to run admin port on the same port as the application

IMO, that's an opinionated question. No right or wrong answer, just tradeoffs. 

> You can also `setSecurityHandler` on the admin servlet

^You'll want this for a `simple` server type
