### ISSUE TITLE
Allow unknown JSON properties by default?

### ISSUE THREAD

**Issue by minisu** [dropwizard/dropwizard#2567]
Before 2.0.0 is released, what do you think of disabling `DeserializationFeature.FAIL_ON_UNKNOWN_PROPERTIES` by default?

**Arguments for:**

 - Most, if not all, Dropwizard projects that I’ve seen disables it.
 - It follows Postel’s law (_be conservative in what you send, be liberal in what you accept_).
 - All other JSON libraries that I know allows unknown properties by default: GSON, the json package in Go and Json.NET. Spring Boot (which uses Jackson) also disables it by default.

**Arguments against:**

 - Breaks backwards compatibility (although no services should stop working).
 - Not Jackson default behavior (although e.g. the existing `FuzzyEnumModule` also makes Jackson less strict than its defaults).

Thoughts?

**Comment by nickbabcock** [comment]
Huh, those are some pretty good arguments for changing the behavior. I support this change, as it seems it will bring dropwizard in line with the ecosystem at large (though becoming disjointed with default jackson behavior may be unexpected). As long as it's clearly documented how to revert the behavior, the change seems sensible. But I'd wait to see if there are additional opinions before further action.

**Comment by jplock** [comment]
I’d be supportive of this.

**Comment by kravchik** [comment]
Great, and now, how to disable it back?)
