### ISSUE TITLE
DropwizardAppRule Test

### ISSUE THREAD

**Issue by shail** [dropwizard/dropwizard#2582]
I have a test which relies on DropwizardAppRule.

```
public class WebServiceTest extends FievelTestBase {
  @ClassRule
  public static final DropwizardAppRule<WebServiceConfigurationJson> RULE =
      new DropwizardAppRule<>(
          WebService.class,
          "./flux/resources/src/main/resources/config/test.yaml");

  @Test
  public void testBasicServiceHealth() {
    String path = WebServiceTest.class.getResource("/config/test.yaml").getPath();
    Client client = JerseyClientBuilder.createClient();

    Response response =
        client
            .target(String.format("http://localhost:%d/health", RULE.getLocalPort()))
            .request()
            .get();

    assertEquals(200, response.getStatus());
  }
}
```
When there is an issue with the server running, all I get from the test is a `NullPointerException` when i call `RULE.getLocalPort()`. Is there a way to print the logs or better visualize the error from this test?

This is dropwizard 1.0.6 so might be fixed in later versions, but just curious anyways.

**Comment by isaki** [comment]
If the app fails to start you get NPE from various methods even in 1.3.5. I wonder if there is a way we can fail the entire test file if the rule/test app fails to bootstrap itself with an appropriate error.

**Comment by shail** [comment]
@isaki Yeah it would be great if we could print out some more information as well. But I didn't see anything in DropwizardAppRule that would allow for that

**Comment by nickbabcock** [comment]
Can the test case be expanded a bit? 

Given:

```java
public class MyTestClass {
    public static class MyApp extends Application<Configuration> {
        @Override
        public void run(Configuration configuration, Environment environment) throws Exception {
            throw new RuntimeException("EEK");
        }
    }

    @ClassRule
    public static final DropwizardAppRule<Configuration> RULE =
            new DropwizardAppRule<>(MyApp.class, new Configuration());

    @Test
    public void testBasicServiceHealth() {
        RULE.getLocalPort();
    }
}
```

I see the expected runtime exception, not an NPE

**Comment by joschi** [comment]
Closed due to inactivity.
