### ISSUE TITLE
SSL CONFIG EXTERNAL ERROR

### ISSUE THREAD

**Issue by nyoakaway** [dropwizard/dropwizard#2588]
Hi, I'm trying to set up my DropWizzard (running GraphHopper) for external access.

I generated the certificate, I already validated it with my validating company, already configured the .jks and my config file is as follows:

```
# Dropwizard server configuration
server:
  
applicationConnectors:
  
- type: http
    
port: 8080
    
bindHost: 192.168.0.223
  

- type: https
    
port: 8443
    
bindHost: 192.168.0.223
    
keyStorePath: rota_monisat_com_br.jks
    
keyStorePassword: *****
keyStoreType: JKS
    
validateCerts: false
    
supportedProtocols: [TLSv1, TLSv1.1, TLSv1.2]
```

But I can not do external access, the sub-domain is already configured for Ipfixo, the ip ports are already addressed because I can not execute it on https.

If I access the URL via HTTP (http://rota.monisat.com.br:8080) the memso accesses normally, I need to access it via HTTPS now.

In the console appears the SSL being executed with the configurations of the same one.
![ssl](https://user-images.githubusercontent.com/42919302/50609869-250ea980-0eb8-11e9-9442-cebc1964cae0.png)

**Comment by nickbabcock** [comment]
Hello it's not clear from the description what is wrong. The screenshot looks fine. You'll need to provide more info. Preferably, you're on the box where the service is hosted executing curl or openssl s_client to show us these errors.

**Comment by nyoakaway** [comment]
Hi Nick, exactly, it appears that this is okay! But accessing Url via HTTPS does not just open, as if there was no SSL installed! I do not know if there is any other procedure or some other way to try to reinstall the certify!

**Comment by joschi** [comment]
@nyoakaway Maybe your version of cURL (or OpenSSL) is too old, also see this StackOverflow answer when searching for the error message:
https://stackoverflow.com/a/38824090

Try using a more current version which supports TLS 1.0 or higher.
