### ISSUE TITLE
Issue with Java 11

### ISSUE THREAD

**Issue by keirlawson** [dropwizard/dropwizard#2589]
When generating a simple project using the maven archetype and building/running with Java 11, I get the following exceptions whenever I try to run the jar:

```
WARNING: HK2 service reification failed for [org.glassfish.jersey.jaxb.internal.XmlRootElementJaxbProvider$General] with an exception:
MultiException stack 1 of 2
java.lang.NoClassDefFoundError: javax/xml/bind/PropertyException
```

**Comment by namannigam** [comment]
@keirlawson Could be related to https://stackoverflow.com/questions/43574426/how-to-resolve-java-lang-noclassdeffounderror-javax-xml-bind-jaxbexception-in-j

**Comment by keirlawson** [comment]
Yep, I would assume it is the same issue.

**Comment by serhiypal** [comment]
you need to add JAXB to the classpath since Java 11 has couple of deprecated modules removed
```
            <dependency>
                <groupId>javax.xml.bind</groupId>
                <artifactId>jaxb-api</artifactId>
                <version>${jaxb.api.version}</version>
            </dependency>
            <dependency>
                <groupId>org.glassfish.jaxb</groupId>
                <artifactId>jaxb-runtime</artifactId>
                <version>${jaxb.runtime.version}</version>
            </dependency>
```

**Comment by serhiypal** [comment]
are you upgrading runtime or compile time to Java 11 as well?

**Comment by keirlawson** [comment]
I get this issue regardless of whether I compile with JDK 8 or 11, running against 11.

Adding your snippet to the POM resolves the issue, however it would be great if Dropwizard could support Java 11 without the need for workarounds.

**Comment by RohanNagar** [comment]
@keirlawson I believe changes have been made in Dropwizard to support Java 11 in the next release (v2.0.0 ?)

**Comment by serhiypal** [comment]
@keirlawson , `1.3.x` does not support Java 11 (removed deprecated modules, asm), so you can run on Java 11 bytecode compiled at 8th level adding libraries mentioned above. To support Java 11 there was a bump of jersey, hk2 that transitively lead to asm, that caused a lot of changes in code base as jersey API "slightly" changed and everything is going to be addressed in `2.0.0` which we are waiting for.

**Comment by DrMattFaulkner** [comment]
Any news on when 2.0.0 will be released? Or even a version with backports for compatibly with JDK11?

**Comment by joschi** [comment]
@DrMattFaulkner Feel free to give Dropwizard 2.0.0-rc1-SNAPSHOT a try and provide some feedback about it works for you.

**Comment by RohanNagar** [comment]
@joschi is there a `2.0.0-rc1-SNAPSHOT` version for all Dropwizard components? Seems like there is not one for the `dropwizard-testing` artifact:

```
[ERROR] Failed to execute goal on project api:
Could not resolve dependencies for project com.sanctionco.thunder:api:jar:2.1.1-SNAPSHOT:
Could not find artifact io.dropwizard:dropwizard-testing:jar:2.0.0-rc1-SNAPSHOT
```

**Comment by joschi** [comment]
@RohanNagar Yep, it's there:
https://oss.sonatype.org/content/repositories/snapshots/io/dropwizard/dropwizard-testing/2.0.0-rc1-SNAPSHOT/

**Comment by RohanNagar** [comment]
Thanks, I just forgot to include the snapshot repo in my pom 🤦

**Comment by serhiypal** [comment]
is there any timeline of getting `2.0.0` released (alpha, beta, testing) so we could plan roadmap accordingly?

**Comment by joschi** [comment]
@serhiypal The more people test the SNAPSHOTs and the release candidates, the faster Dropwizard 2.0.0 will be released.

**Comment by timmolter** [comment]
@joschi I just updated to 2.0.0-rc1-SNAPSHOT and tested everything on my demo Dropwizard app (<https://github.com/knowm/XDropWizard>) and found everything to work after changing a method signature in `Task`, which I use in my scheduled jobs Dropwizard extension (<https://github.com/knowm/dropwizard-sundial>).

**Comment by joschi** [comment]
@timmolter Thanks for the feedback!

**Comment by joschi** [comment]
Since Dropwizard 2.0.0-rc1 seems to work with Java 11, I'll close this issue.

Please leave a comment here if you found a problem with running Dropwizard 2.0.0-rc1 (or later) with Java 11.

**Comment by RichardBradley** [comment]
I'm getting this error when running integration tests using `io.dropwizard:dropwizard-testing:2.1.12`
This does not appear to break anything, just fills the log with `NoClassDefFoundError` and long stack traces.
I'm on Java 11

```
MultiException stack 1 of 2
java.lang.NoClassDefFoundError: javax/xml/bind/PropertyException
	at java.base/java.lang.Class.getDeclaredConstructors0(Native Method)
	at java.base/java.lang.Class.privateGetDeclaredConstructors(Class.java:3137)
	at java.base/java.lang.Class.getDeclaredConstructors(Class.java:2357)
	at org.jvnet.hk2.internal.Utilities$3.run(Utilities.java:1354)
```

It doesn't seem to break anything, and my app doesn't do this when it runs; just in test

Does anyone know how I should fix?
Should I add these jaxb dependencies in test only?

**Comment by RichardBradley** [comment]
I have worked around by adding a compile dep on:
```
            <dependency>
                <groupId>javax.xml.bind</groupId>
                <artifactId>jaxb-api</artifactId>
                <version>2.4.0-b180830.0359</version>
            </dependency>
```
