### ISSUE TITLE
How to create Httpsession in ContainerRequestFilter 

### ISSUE THREAD

**Issue by pradeep3188** [dropwizard/dropwizard#2612]
My application is a restful web application and want to create HttpSession in one of Rest filter which is created by using ContainerReqestFilter,
Some one can help us

**Comment by nickbabcock** [comment]
Hmm, you mean something along the lines of:

```java
public class MyFilter implements ContainerRequestFilter {
    @Context
    HttpServletRequest webRequest;

    @Override
    public void filter(ContainerRequestContext containerRequestContext) throws IOException {
        final HttpSession session = webRequest.getSession(true);
    }
}
```

Closing this as this is more of a jersey issue than dropwizard.
