### ISSUE TITLE
Noisy logback on startup

### ISSUE THREAD

**Issue by dreamysx** [dropwizard/dropwizard#2618]
I am using v 0.8.0 and got below log:
13:45:41,882 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Could NOT find resource [logback.groovy]
13:45:41,882 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Could NOT find resource [logback-test.xml]
13:45:41,882 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Could NOT find resource [logback.xml]
13:45:41,883 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Setting up default configuration.
13:45:45,533 |-INFO in ch.qos.logback.classic.jul.LevelChangePropagator@4e28bdd1 - Propagating ERROR level on Logger[ROOT] onto the JUL framework
13:45:45,535 |-INFO in ch.qos.logback.classic.jul.LevelChangePropagator@4e28bdd1 - Propagating WARN level on Logger[com.gs.security.gsauthn] onto the JUL framework
13:45:45,535 |-INFO in ch.qos.logback.classic.jul.LevelChangePropagator@4e28bdd1 - Propagating DEBUG level on Logger[com.gs.finrisk.clear] onto the JUL framework
13:45:45,535 |-INFO in ch.qos.logback.classic.jul.LevelChangePropagator@4e28bdd1 - Propagating DEBUG level on Logger[com.gs.appkit] onto the JUL framework
13:45:45,553 |-INFO in c.q.l.core.rolling.TimeBasedRollingPolicy - No compression will be used
13:45:45,554 |-INFO in c.q.l.core.rolling.TimeBasedRollingPolicy - Will use the pattern /local/scratch/logs/clear-cpm-finrefprocessor/clear-cpm-finrefprocessor-%d.log for the active file
13:45:45,560 |-INFO in c.q.l.core.rolling.DefaultTimeBasedFileNamingAndTriggeringPolicy - The date pattern is 'yyyy-MM-dd' from file name pattern '/local/scratch/logs/clear-cpm-finrefprocessor/clear-cpm-finrefprocessor-%d.log'.
13:45:45,560 |-INFO in c.q.l.core.rolling.DefaultTimeBasedFileNamingAndTriggeringPolicy - Roll-over at midnight.
13:45:45,567 |-INFO in c.q.l.core.rolling.DefaultTimeBasedFileNamingAndTriggeringPolicy - Setting initial period to Mon Jan 28 13:45:45 EST 2019
13:45:45,570 |-ERROR in ch.qos.logback.core.rolling.RollingFileAppender[file-appender] - File property must be set before any triggeringPolicy or rollingPolicy properties
13:45:45,570 |-ERROR in ch.qos.logback.core.rolling.RollingFileAppender[file-appender] - Visit http://logback.qos.ch/codes.html#rfa_file_after for more information
13:45:45,573 |-INFO in ch.qos.logback.core.rolling.RollingFileAppender[file-appender] - Active log file name: /local/scratch/logs/clear-cpm-finrefprocessor/clear-cpm-finrefprocessor.log
13:45:45,573 |-INFO in ch.qos.logback.core.rolling.RollingFileAppender[file-appender] - File property is set to [/local/scratch/logs/clear-cpm-finrefprocessor/clear-cpm-finrefprocessor.log]
13:45:45,578 |-INFO in ch.qos.logback.classic.AsyncAppender[async-file-appender] - Attaching appender named [file-appender] to AsyncAppender.
13:45:45,578 |-INFO in ch.qos.logback.classic.AsyncAppender[async-file-appender] - Setting discardingThreshold to 51

**Comment by joschi** [comment]
> I am using v 0.8.0 and got below log:

Please upgrade to Dropwizard 1.3.8 and check if the problem still exists.
