### ISSUE TITLE
Unable to test Async request

### ISSUE THREAD

**Issue by gukkes** [dropwizard/dropwizard#2633]
I'm currently unable to write any unit test on methods that are annotated with @ManagedAsync.
I'm aware of ticket #1099, but even when using the Grizzly Test Container it fails with:

Test ignored.

java.lang.NullPointerException
	at java.util.Objects.requireNonNull(Objects.java:203)
	at io.dropwizard.testing.common.Resource.after(Resource.java:213)
	at io.dropwizard.testing.junit.ResourceTestRule$1.evaluate(ResourceTestRule.java:102)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)

I've attached a small gradle project to illustrate the issue.
[case.zip](https://github.com/dropwizard/dropwizard/files/2831599/case.zip)

**Comment by nickbabcock** [comment]
This test case passes just fine:

```java
public class ManagedAsyncTest {
    @ClassRule
    public static final ResourceTestRule resources = ResourceTestRule.builder()
            .addResource(new DummyResource())
            .setTestContainerFactory(new GrizzlyWebTestContainerFactory())
            .build();

    @Test
    public void test1() {
        assertThat(resources.target("/async").request().get(String.class))
                .isEqualTo("foobar");
    }

    @Path("/")
    public static class DummyResource {
        @GET
        @Path("/async")
        @ManagedAsync
        public void async(@Suspended final AsyncResponse ar) {
            ar.resume("foobar");
        }
    }
}
```

I believe you may be missing the `@Suspended final AsyncResponse ar` parameter

**Comment by gukkes** [comment]
Yes that was missed definitely! Thank you for pointing this out.
However, I've tried with your example as well and the error remains the same both in Eclipse, Intellij even with Maven or Gradle.

**Comment by nickbabcock** [comment]
I've uploaded the repo here: https://github.com/nickbabcock/dropwizard-2633

Once you figure out the issue or a reasonable time has passed I will delete the repo

**Comment by gukkes** [comment]
It is related to some dependency trickery with the Maven BOM in dependenyManagement-section. If you put the exact same versions, without the BOM it simply does not work. Still need to find a working solution in Gradle.

**Comment by nickbabcock** [comment]
Specifying exact versions works for me, so not sure if it is a bom issue

```xml
    <dependencies>
        <dependency>
            <groupId>io.dropwizard</groupId>
            <artifactId>dropwizard-core</artifactId>
            <version>1.3.8</version>
        </dependency>
        <dependency>
            <groupId>io.dropwizard</groupId>
            <artifactId>dropwizard-testing</artifactId>
            <version>1.3.8</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.glassfish.jersey.test-framework.providers</groupId>
            <artifactId>jersey-test-framework-provider-grizzly2</artifactId>
            <scope>test</scope>
            <version>2.25.1</version>
        </dependency>
    </dependencies>
```

**Comment by gukkes** [comment]
We used the latest grizzly 2.28

**Comment by nickbabcock** [comment]
Don't. Jersey 2.28 is not supported in Dropwizard 1.3.x. Dropwizard 2.0 will support it.

**Comment by gukkes** [comment]
Can be closed. Relying on 2.25.1 solves the issue.
