### ISSUE TITLE
2.x Snapshot Availability

### ISSUE THREAD

**Issue by whitfin** [dropwizard/dropwizard#2646]
I'm curious if there is a 2.x snapshot available anywhere? I can't seem to find anything beyond [1.4.0-SNAPSHOT](https://oss.sonatype.org/content/repositories/snapshots/io/dropwizard/dropwizard-bom/), but it looks like there should be an `rc1` somewhere.

I'm trying to test compatibility of the rest of my codebase with JDK 11, so it would be nice if this snapshot was available to help out whilst waiting for the eventual 2.x release.

**Comment by joschi** [comment]
SNAPSHOT versions should be built again as of b218e3e6e6a59a3749ac6411c93bfded91a080b8.
