### ISSUE TITLE
[2.0.0-rc1] Error with AbstractBinder

### ISSUE THREAD

**Issue by FredDeschenes** [dropwizard/dropwizard#2685]
I had to change my imports for `AbstractBinder` from `org.glassfish.hk2.utilities.binding` to `org.glassfish.jersey.internal.inject` as was done in 8eb57d0, but could not find anything about this in either the [migration guide](https://github.com/dropwizard/dropwizard/wiki/Upgrade-guide-1.3.x-to-2.0.x) or [Jersey's release notes](https://jersey.github.io/release-notes/2.28.html). It's pretty confusing since the old class is still available so there's no compilation errors. I was wondering if Dropwizard has a dependency on something it shouldn't (ie: the old lib) that should be removed to force a compilation error.

**Comment by joschi** [comment]
@FredDeschenes Jersey 2.26 introduced an abstraction layer for dependency injection:
https://jersey.github.io/release-notes/2.26.html

Up until now, the HK2 is the only (stable) implementation available for this abstraction. 🙄

We should definitely add this to the migration guide.

**Comment by FredDeschenes** [comment]
Ah I look at the release notes for 2.27 and 2.26, that explains it. Thanks!
