### ISSUE TITLE
Allow null validationQuery

### ISSUE THREAD

**Issue by slivkamiro** [dropwizard/dropwizard#2702]
tomcat jdbc allows validationQuery to be null, see https://tomcat.apache.org/tomcat-9.0-doc/jdbc-pool.html . In that case it will validate connections by isValid() method on Connection object.

In our company, we get our database logs flooded by SELECT 1 queries, causing not being able to hold more than one day of logs. This is caused by setting up checkConnectionWhileIdle and other connection checks (which we want to keep) and the fact that in dropwizard it is not possible to set validationQuery to null. This setting, causing the call to isValid(), would help for drivers which implement this method by not executing the query.

I would happily help with implementation of this.

**Comment by jplock** [comment]
Happy to review a PR for this
