### ISSUE TITLE
Issue with newest version of JDBI (v3.6.0)

### ISSUE THREAD

**Issue by colin-armstrong** [dropwizard/dropwizard#2717]
The latest version of Dropwizard (v1.3.9) is incompatible with the newest version of JDBI (v3.6.0).  The issue is related to the removal of JdbiSteams from JDBI core which Dropwizard still relies on.

Rolling back to JDBI v3.5.0 fixes the issue.  Hopefully the next Dropwizard release will resolve this.

**Comment by joschi** [comment]
jDBI has been updated in #2601.
