### ISSUE TITLE
Connection resets under highly concurrent traffic

### ISSUE THREAD

**Issue by DrMattFaulkner** [dropwizard/dropwizard#2735]
Hi All,

I'm using Apache Bench [1] to push some load through a vanilla dropwizard application. I'm hitting the admin ping resource with around 250 concurrent connections for a duration of about 30 seconds [2]. During these tests I see "connection resets" [3]. This test is NOT using keep-alive and so every request is creating a new TCP socket. 

With keep-alives turned on the tests pass with flying colours. 

Is there any advice / guidance as to the max number new of connections  / second? And / or is there some configuration settings that I can I tweak to set / discover this limit. I've tried `maxThreads ` with no success.

Thanks for any advice.

[1] https://httpd.apache.org/docs/2.4/programs/ab.html
[2] ab -c 250 -t 30 -n 10000000 http://localhost:8081/admin/ping
[3] `This is ApacheBench, Version 2.3 <$Revision: 1826891 $>
Copyright 1996 Adam Twiss, Zeus Technology Ltd, http://www.zeustech.net/
Licensed to The Apache Software Foundation, http://www.apache.org/

Benchmarking localhost (be patient)
apr_socket_recv: Connection reset by peer (54)
Total of 14514 requests completed`

**Comment by joschi** [comment]
@DrMattFaulkner Thanks for writing this up!

Which version of Dropwizard have you been using? What was the exact configuration you've been using in your Dropwizard application?

And finally, could you please try repeating the benchmarks with Dropwizard 2.0.0-rc1?

**Comment by mattnelson** [comment]
Was this tested with OSX? There are [some](https://serverfault.com/a/806918) [issues](https://stackoverflow.com/a/1217100) with ab.

Can it be reproduced with [vegeta](https://github.com/tsenart/vegeta) or [wrk](https://github.com/wg/wrk) or [siege](https://github.com/JoeDog/siege)?

**Comment by DrMattFaulkner** [comment]
Only just seen these replies. 

@joschi  I've been using version 1.3.9 of dropwizard. The configuration is standard:

`server:
  type: simple
  applicationContextPath: /
  adminContextPath: /admin
  connector:
    type: http

logging:
  level: INFO
  loggers:
    com.genesys: DEBUG
`

Let me repeat the tests with DW 2. I have tried something other than ab, but let me repeat those tests to get up to date information.

**Comment by joschi** [comment]
@DrMattFaulkner Did you find time to re-run the tests with Dropwizard 2.0.0-rc1?
