### ISSUE TITLE
Update conscrypt documentation

### ISSUE THREAD

**Issue by mattnelson** [dropwizard/dropwizard#2736]
The conscrypt documentation will appear to need a slight tweak to the recommended way of registering the provider.

https://github.com/eclipse/jetty.project/issues/3551
https://www.dropwizard.io/1.3.9/docs/manual/core.html#man-core-bootstrapping

**Comment by mattnelson** [comment]
One additional note depending on which version of conscrypt is used. The current docs do not call out supported conscrypt versions. Since the current dropwizard minimum runtime target is 8, there is a disconnect between default supported protocols.

> If you are using Conscrypt with Java 8, you must exclude TLSv1.3 protocol as it is now enabled per default with Conscrypt 2.0.0 but not supported by Java 8.

https://www.eclipse.org/jetty/documentation/9.4.x/configuring-ssl.html#conscrypt

**Comment by joschi** [comment]
@mattnelson Thanks for reporting this!

Would you be able to contribute a pull request applying the documentation changes for Conscrypt you've described?
