### ISSUE TITLE
Upgrade Jetty to version 9.2.28, 9.3.27, 9.4.17 or higher.

### ISSUE THREAD

**Issue by mpbalmeida** [dropwizard/dropwizard#2745]
The configuration of a Jetty server may be leaked as part of a HTTP 404 response. This is due to the DefaultHandler class producing an error page during an exception.

More information on https://github.com/eclipse/jetty.project/issues/3555

**Comment by mzamani1** [comment]
It looks like `9.4.17` is used in the `2.0.0` rc, but not in `1.3.9` (`9.4.14` is used). Is this worth patching the `1.3.x` series?

**Comment by joschi** [comment]
Closed by eec03a99e077ce06c053d4e61b64d913d9469fd3
