### ISSUE TITLE
No release changes list for 1.3.10

### ISSUE THREAD

**Issue by chris-orchard** [dropwizard/dropwizard#2747]
I've seen 1.3.10 has been released but there's no details on the release page https://github.com/dropwizard/dropwizard/releases to show what's changed as per past releases.

From looking at the commits (https://github.com/dropwizard/dropwizard/commits/release/1.3.x) I think this is just a bump of Jetty from 9.4.14.v20181114 to 9.4.17.v20190418.

Am I right and are there any other notable changes?

**Comment by joschi** [comment]
Maybe @arteam can add the release notes.

**Comment by arteam** [comment]
I was not able to deploy in to Maven central yesterday because of Sonatype's Nexus issues.  Will try to do it today and add the release notes.

**Comment by mecorusfc** [comment]
Because of vulnerabilities that just popped on our scans this morning, we need this version to get Jetty past version 9.4.15 (9.4.17 should be good).  We need to respond to these vulnerabilities quickly.  Thanks

**Comment by Fox32** [comment]
The changelog was updated, but I'm missing a line mentioning this commit:

https://github.com/dropwizard/dropwizard/commit/78e194fc13a929ab7ab3b28211c19775419c51a7

**Comment by chris-orchard** [comment]
Release notes also seem to be missing for 1.3.10 at:
https://www.dropwizard.io/1.3.9/docs/about/index.html (this is the page that About Dropwizard >> goes to. https://www.dropwizard.io/1.3.10/docs/about/index.html gives a 404)
