### ISSUE TITLE
ConfiguredBundle no longer supports interfaces

### ISSUE THREAD

**Issue by strmer15** [dropwizard/dropwizard#2759]
Prior to DropWizard 2.0.0, it was possible to use a configuration interface in a ConfiguredBundle to indicate that you expected a certain subset of configuration to be passed in which implemented that interface; in the 2.0.0-rc1 version of dropwizard, the ConfiguredBundle type parameter is now set to `T extends Configuration` making that no longer possible.

```
public class MyBundle implements ConfiguredBundle<HasMyConfig> {

    @Override
    public void initialize(final Bootstrap bootstrap) {
    }

    @Override
    public void run(final HasMyConfig myConfig, final Environment environment) {
    }
}
```
```
public interface HasMyConfig {

    @NotNull
    @Valid
    @JsonProperty("mine")
    MyConfig getMyConfig();
}
```

The documentation still notes it as supported:
https://dropwizard.readthedocs.io/en/rtd/manual/core.html#bundles

And the migration guide does not make any mention of this breaking change:
https://dropwizard.readthedocs.io/en/rtd/manual/upgrade-notes/upgrade-notes-2_0_x.html

Could you please either a) update the documentation to reflect the change (and hopefully a workaround to enable this some other way) or b) revert the change to ConfiguredBundle's type parameter to resolve this?

**Comment by joschi** [comment]
Refs #2516

**Comment by joschi** [comment]
@strmer15 Thanks for reporting this! The old state will be restored once #2760 has been merged.

**Comment by strmer15** [comment]
Thanks for the quick fix!
