### ISSUE TITLE
"Malformed" http.rootPath in configuration does not raise a warning/error

### ISSUE THREAD

**Issue by fge** [dropwizard/dropwizard#276]
Hello,

I have (mistakenly) overridden the default `http.rootPath`, which is `/*`, with `/sv` -- no `/*` at the end.

When I call the URIs of my resources, they all return 404, however at startup the resource URIs are "recognized":

```
INFO  [2013-03-06 11:46:30,293] com.yammer.dropwizard.config.Environment: 

    GET     /sv/hello-world/hi.html (com.alexeypro.samples.resources.HelloWorldResource)
    GET     /sv/hello-world/hi.json (com.alexeypro.samples.resources.HelloWorldResource)
```

When ready:

```
$ wget -S -O /dev/null http://localhost:8080/sv/hello-world/hi.json
--2013-03-06 12:48:05--  http://localhost:8080/sv/hello-world/hi.json
Resolving localhost (localhost)... 127.0.0.1
Connecting to localhost (localhost)|127.0.0.1|:8080... connected.
HTTP request sent, awaiting response... 
  HTTP/1.1 404 Not Found
[etc etc]
```

**Comment by ajeeshpu** [comment]
is this really done? I am running dropwizard 0.8 and I still spent another hour with the rootPath.

**Comment by joschi** [comment]
@ajeeshpu The `rootPath` setting (which is really different from the `applicationContextPath` and `adminContextPath` settings) was added back in #665.
