### ISSUE TITLE
The JUnit5 example described in java doc of DropwizardAppExtension doesn't actually work

### ISSUE THREAD

**Issue by tristanbuckner** [dropwizard/dropwizard#2763]
This section in the java docs describing using a single Application instance to run all your tests:
```
Using DropwizardAppExtension at the suite level can speed up test runs, as the application is only started and stopped once for the entire suite:

 public class MySuite {
   public static final DropwizardAppExtension<MyConfig> DROPWIZARD = new DropwizardAppExtension<>(...);
 }
 
If the same instance of DropwizardAppExtension is reused at the suite- and class-level, then the application will be started and stopped once, regardless of whether the entire suite or a single test is executed.

 @ExtendWith(DropwizardExtensionsSupport.class)
 public class FooTest {
   public static final DropwizardAppExtension<MyConfig> DROPWIZARD = MySuite.DROPWIZARD;

   public void testFoo() { ... }
 }

 @ExtendWith(DropwizardExtensionsSupport.class)
 public class BarTest {
   public static final DropwizardAppExtension<MyConfig> DROPWIZARD = MySuite.DROPWIZARD;

   public void testBar() { ... }
 }
```
This doesn't actually work for any subsequent tests using the client() method. client() will return the previously closed client and not open a new one. I have a PR that can fix this behavior by setting the client instance to null after it's closed, but what's happening still isn't what's described in the java doc.

Every time the after() method is called DropwizardTestSupport stops the application, and the subsequent call to before() will start a new instance of the application. You're better off just not using the extension and manually starting the app (I'm not sure if there are any negative effects  from not calling shutdown explicitly when tests complete, but there is a listener interface that could allow you to manually call after() if that's important).

**Comment by tristanbuckner** [comment]
https://github.com/dropwizard/dropwizard/pull/2764

**Comment by tristanbuckner** [comment]
I'm straining to imagine a case that would work. You would need every test class to start at the same time and complete at the same time. If one rewrote the junit launcher to join on all tests being completed before calling afterAll(). But in most cases, parallel integration tests are hard to make work since they tend to involve state.

**Comment by nickbabcock** [comment]
Agreed, let's update the docs to remove any mention of the this feature

**Comment by nickbabcock** [comment]
Hmm the original feature implementation: https://github.com/dropwizard/dropwizard/pull/1411

Maybe the example has the right idea but wrong implementation. It does look like junit supports suite level class rules: https://stackoverflow.com/q/349842/433785 (I learned something new today 😄 )
