### ISSUE TITLE
Publish documentation for Dropwizard 1.3.11

### ISSUE THREAD

**Issue by joschi** [dropwizard/dropwizard#2771]

**Comment by natnan** [comment]
It's probably not the place but didn't want to create another issue for this.
Will 1.3.11 be published on maven when the documentation is ready?

**Comment by joschi** [comment]
@natnan I guess @arteam can answer that since he ran the release.

**Comment by arteam** [comment]
1.3.11 should be published. Sonatype has had some issues  with the staging repo and I had to republish it yesterday.
