### ISSUE TITLE
Upgrade Jackson to version 2.9.9 or higher

### ISSUE THREAD

**Issue by mpbalmeida** [dropwizard/dropwizard#2779]
Due to a new vulnerability found in jackson 2.9.8 it is needed to upgrade to jackson 2.9.9 or higher

More information at: https://snyk.io/vuln/SNYK-JAVA-COMFASTERXMLJACKSONCORE-174736

**Comment by joschi** [comment]
@mpbalmeida Thanks for raising this issue! I've cherry-picked the respective commit from `master` (#2777).

Fixed via 11a421fa64595615663e91ebe9239f3ac5d37576

**Comment by mpbalmeida** [comment]
When will you release this version? My pipeline is all red.

**Comment by joschi** [comment]
@mpbalmeida You can temporarily override the Jackson BOM version in your projects to already pull in the latest version of the Jackson dependencies.

**Comment by mpbalmeida** [comment]
Yeah, that's what I did. But it would be nice to have this security issue
deployed.
