### ISSUE TITLE
command parameters without arguments

### ISSUE THREAD

**Issue by lfoppiano** [dropwizard/dropwizard#2814]
Hi, 
   I'm wondering whether it's possible to have a command line with a parameter that doesn't require any argument. I could not figure out if it's possible. 

Could you advice? 

Thank you 
Luca

**Comment by pstackle** [comment]
Hi @lfoppiano,
Argparse4j is the underlying library that is used for parsing arguments. It looks like you can add an argument with an action of `Arguments.storeTrue()` which would allow you to not have a value for the argument. 
https://argparse4j.github.io/usage.html#arguments-storetrue-and-arguments-storefalse

Is that what you are looking for?

**Comment by lfoppiano** [comment]
@pstackle thanks! That solved the issue.
