### ISSUE TITLE
Test asynchronous JAX-RS method

### ISSUE THREAD

**Issue by lutzhorn** [dropwizard/dropwizard#2815]
Consider an asynchronous JAX-RS method, part of an `OkResource`:

```java
@GET
@Path("/ok")
@ManagedAsync
public void getOk(@Suspended final AsyncResponse asyncResponse) {
    asyncResponse.resume("OK");
}
```

Dropwizard, based on Jersey, provides the useful `ResourceTestRule`. A test class for the above method would contain an instance of this rule.

```java
@ClassRule
public static ResourceTestRule RULE = ResourceTestRule.builder()
  .addResource(new OkResource())
  .build();
```

A test method for the JAX-Rs method would look like

```java
@Test
public void testGetOk()  {
    Response response = RULE.target("/ok).request().get();
    // assert ...
}
```

For *synchronous* JAX-RS methods this works fine. But for ***asynchronous*** JAX-RS like above this approach does not work:

> WARN  [2019-06-26 09:15:15,811] org.glassfish.jersey.test.inmemory.InMemoryConnector: Asynchronous server side invocations are not supported by InMemoryContainer.

Is there a different way to test asynchronous JAX-RS methods without having to directly call the method (`getOk` in this case) with a mocked `AsyncResponse`?

**Comment by joschi** [comment]
@lutzhorn Have you tried using another test container?

https://jersey.github.io/documentation/2.28/test-framework.html#d0e17501

**Comment by lutzhorn** [comment]
I will try that, thank you.

**Comment by lutzhorn** [comment]
Works. Maybe I should read [the documentation](https://www.dropwizard.io/1.3.12/docs/manual/testing.html#test-containers) before opening an issue :)
