### ISSUE TITLE
Upgrade to Jersey 2.29

### ISSUE THREAD

**Issue by runeflobakk** [dropwizard/dropwizard#2817]
Just wanted to give a heads up that Jersey 2.29 was just released
http://blog.supol.cz/?p=144
Would be great if the new DW version 2 could support the new Jersey version!

Thank you!

**Comment by joschi** [comment]
See #2813

**Comment by runeflobakk** [comment]
Thank you.

I tried to "override" the jersey-bom (i.e. define it in my own dependencyManagement _before_ the dropwizard-bom) to try it together with 2.0.0-rc. I inspected my dependency graph to verify I got Jersey 2.29 artifacts. When running I got some ClassNotFoundExceptions, so I preemptively assumed something more had to be done in DW to support the new Jersey version, but I have probably got some incompatible dependencies I didn't notice.

I have now tried my application with the latest DW master revision, built with Jersey bumped to 2.29, and everything works 👍 

Sorry for the noise. Just close this issue.
