### ISSUE TITLE
Potential apache client version mismatch on 2.0.0-rc4

### ISSUE THREAD

**Issue by natnan** [dropwizard/dropwizard#2823]
A couple of my tests started failing after upgrading from rc3 to rc4 with this when I try to create a Jersey client.

```
! java.lang.NoSuchMethodError: org.apache.http.client.config.RequestConfig$Builder.setNormalizeUri(Z)Lorg/apache/http/client/config/RequestConfig$Builder;
! at io.dropwizard.client.HttpClientBuilder.createClient(HttpClientBuilder.java:351)
! at io.dropwizard.client.HttpClientBuilder.buildWithDefaultRequestConfiguration(HttpClientBuilder.java:302)
! at io.dropwizard.client.JerseyClientBuilder.buildConfig(JerseyClientBuilder.java:418)
! at io.dropwizard.client.JerseyClientBuilder.build(JerseyClientBuilder.java:370)
! at io.dropwizard.client.JerseyClientBuilder.build(JerseyClientBuilder.java:360)
```

Might be https://github.com/dropwizard/dropwizard/pull/2813 changed something with jersey client, or it could be that I have some dependency breaking it though I can't see one just yet.

**Comment by joschi** [comment]
@natnan Could you please post a minimal example to reproduce the problem?

The tests in [`HttpClientBuilderTest`](https://github.com/dropwizard/dropwizard/blob/2df5f0d5b32206d8b55b1a9e8d17422e0b798710/dropwizard-client/src/test/java/io/dropwizard/client/HttpClientBuilderTest.java) seem to work.

**Comment by natnan** [comment]
Hmm, it must be something else in my project overriding the apache client version then. I'll try to reproduce.

**Comment by Fox32** [comment]
> Hmm, it must be something else in my project overriding the apache client version then. I'll try to reproduce.

We had the same issue because we were overriding the apache http client version, thanks for that pointer!

**Comment by natnan** [comment]
yeah this explains probably. I'll start hunting them down. Thanks.
![image](https://user-images.githubusercontent.com/5628051/60970579-91b0a800-a322-11e9-9539-9d25d355162b.png)
