### ISSUE TITLE
Misuses of cryptographic APIs

### ISSUE THREAD

**Issue by mhp0rtal** [dropwizard/dropwizard#2824]
Hi
The following lines have cryptographic API misuses. <br> File name => dropwizard-client/src/main/java/io/dropwizard/client/DropwizardSSLConnectionSocketFactory.java: Line number => 137: API name => KeyStore:Second parameter should never be of type java.lang.String.<BR> File name => dropwizard-client/src/main/java/io/dropwizard/client/DropwizardSSLConnectionSocketFactory.java: Line number => 142: API name => KeyStore:Second parameter should never be of type java.lang.String.<BR> File name => dropwizard-client/src/main/java/io/dropwizard/client/DropwizardSSLConnectionSocketFactory.java: Line number => 133: API name => KeyStore:Second parameter should never be of type java.lang.String.<BR>

**Comment by reneploetz** [comment]
The user was probably running this tool or some variant: https://github.com/CROSSINGTUD/CryptoAnalysis / https://github.com/eclipse-cognicrypt/CogniCrypt

If I understand correctly, the message is misleading - the plugin does not trigger on the keystore api usage itself, but on the loadKeyStore parameter for the passworrd which is converted into a char array.
See also: https://github.com/eclipse-cognicrypt/CogniCrypt/issues/224

**Comment by mhp0rtal** [comment]
Thanks for replying
