### ISSUE TITLE
Dropwizard Example Application doesn't build for 1.3.13 

### ISSUE THREAD

**Issue by borislavib** [dropwizard/dropwizard#2851]
> Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.22.1:test (default-test) on project dropwizard-example: There are test failures.

Is the error I get when I try 

> mvn package

 in the root directory. 

Is there a simple hello world application? I'm looking for the most basic variant? Dropwizard-example has a lot of issues when downloaded and tried out of the box build.  

To name a few. Dropwizard 1.3.13 doesn't find this
> import io.dropwizard.util.Sets;

EchoTask extends PostBodyTask doesn't override execute properly. execute() gets ImmutableMultimap<String, String>, **not** Map<String, List<String>>. 

Am I missing something ? 

The only change is this in the pom below.  

                <groupId>io.dropwizard</groupId>
                <artifactId>dropwizard-bom</artifactId>
                <version>1.3.13</version>

**Comment by joschi** [comment]
@borislavib Make sure you're not checking out "master" or any 2.x branch, but the correct tag: https://github.com/dropwizard/dropwizard/tree/v1.3.13

**Comment by borislavib** [comment]
@joschi You can delete this issue. Thanks.
