### ISSUE TITLE
Not RESTFul services

### ISSUE THREAD

**Issue by lavinj87** [dropwizard/dropwizard#2875]
Is there a way to take advantage of all the good features of drop wizard such as yaml configuration, logging, healtchecks, metrics and so on for a not restful service?

For instance for a real-time processing service using Kafka?

Kind regards

**Comment by joschi** [comment]
@lavinj87 You can try overriding the `Application#addDefaultCommands()` method in your application:
```java
public class MinimalApplication extends Application<Configuration> {
    @Override
    protected void addDefaultCommands(Bootstrap<Configuration> bootstrap) {
        bootstrap.addCommand(new CheckCommand<>(this));
    }
}
```

**Comment by cricket007** [comment]
You're not required to register any RESTful resources, you could simply map `GET / -> return (200, "OK")`

How would you get healthchecks without starting an HTTP server?

There is a Kafka bundle in the works - https://github.com/dropwizard/dropwizard-kafka
