### ISSUE TITLE
Http2WithCustomCipherTest is failing

### ISSUE THREAD

**Issue by relaxkeren** [dropwizard/dropwizard#2881]
I tried to build dropwizard with command `mvn clean verify` from mater and branch release/1.3.x and both got failed test Http2WithCustomCipherTest. 

`ERROR] Failures: 
[ERROR]   Http2IntegrationTest.testHttp2ManyRequests:53->AbstractHttp2Test.performManyAsyncRequests:71 expected:<[tru]e> but was:<[fals]e>
[ERROR] Errors: 
[ERROR]   Http2IntegrationTest.testHttp11:40 » Processing javax.net.ssl.SSLHandshakeExce...
[ERROR]   Http2IntegrationTest.testHttp2:48 » Execution java.io.IOException: Broken pipe
[ERROR]   Http2WithCustomCipherTest.testHttp2WithCustomCipher:33 » Execution java.io.IOE...
[INFO] 
[ERROR] Tests run: 10, Failures: 1, Errors: 3, Skipped: 0
`

What's the right command to make a dropwizard build? or is it just it's broken?

**Comment by joschi** [comment]
Try building and installing all relevant Dropwizard Maven modules by running `./mvnw install` in the root directory of the project.
