### ISSUE TITLE
Dropwizard JDBI 1.0.5  NullPointerException in NamePrependingStatementRewriter#rewrite:18

### ISSUE THREAD

**Issue by klehrke-sonatype** [dropwizard/dropwizard#2892]
We're using dropwizard 1.0.5 and we're getting an intermittent NPE. We're using postgresql. I am curious if this has been found or resolved in another version. Since it is intermittent, it's hard to test later versions for the same problem. Any insight would be helpful.

Method Signature
`@SqlQuery(MATCH_FETCH_ALL + " OFFSET :offset LIMIT :limit") Collection<Match> getMatches( @Bind("id") final Integer id, @Bind("offset") final Integer offset, @Bind("limit") final Integer limit);`

`ERROR [0&limit=10] [ggingExceptionMapper] - Error handling a request: dee1473ed0fd2500 java.lang.NullPointerException: null ---> at io.dropwizard.jdbi.NamePrependingStatementRewriter.rewrite(NamePrependingStatementRewriter.java:18) --->at org.skife.jdbi.v2.SQLStatement.internalExecute(SQLStatement.java:1296) --->at org.skife.jdbi.v2.Query.fold(Query.java:173) --->at org.skife.jdbi.v2.Query.list(Query.java:82) --->at org.skife.jdbi.v2.sqlobject.ResultReturnThing$IterableReturningThing.result(ResultReturnThing.java:253) --->at org.skife.jdbi.v2.sqlobject.ResultReturnThing.map(ResultReturnThing.java:46) --->at org.skife.jdbi.v2.sqlobject.QueryHandler.invoke(QueryHandler.java:43) --->at org.skife.jdbi.v2.sqlobject.SqlObject.invoke(SqlObject.java:212) --->at org.skife.jdbi.v2.sqlobject.SqlObject$3.intercept(SqlObject.java:127) --->at org.skife.jdbi.v2.sqlobject.CloseInternalDoNotUseThisClass$$EnhancerByCGLIB$$f5b2410c.getMatches(<generated>) --->at MatchService.getMatches(MatchService.java:420)`

**Comment by jplock** [comment]
Are you able to use a newer version of DW that ships with a newer JDBI?

**Comment by klehrke-sonatype** [comment]
it's a lot more effort/risk to upgrade it to test out an intermittent bug, but if you think it's fixed in later versions, then I think that's the answer.  Unfortunately, even if I personally test it, I wont know for some time if its fixed because of how intermittent it is.

**Comment by joschi** [comment]
@klehrke-sonatype There won't be anymore bugfixes for Dropwizard 1.0.x.

Please upgrade to Dropwizard 1.3.14 and check if the problem still exists. FWIW, the upgrade should be rather straight forward.
