### ISSUE TITLE
HOWTO change response body of 403 Forbidden?

### ISSUE THREAD

**Issue by lutzhorn** [dropwizard/dropwizard#2904]
Let a resource method be annotated with `@RolesAllowed(value = { "USER" })`. The principal does not have this role so a `403 Forbidden` response is returned.

The body of this response has `Content-Type: application/json`:

```json
{
  "code": 403,
  "message": "User not authorized."
}
```

How can I change the content type of this response and return a custom body?

A possible use case could be to return a `text/html` response body which contains HTML that explains that the user is not authorized.

**Comment by skradel** [comment]
RolesAllowedDynamicFeature throws ForbiddenException as-needed; to provide the user with something different, you'd want to suppress the built-in ExceptionMappers and provide your own ExceptionMapper to create some other JAX-RS Response; this is already possible as noted in the default Dropwizard configuration options.

In any event this issue should likely be closed as an inappropriate venue for posing implementation questions.
