### ISSUE TITLE
Jackson Afterburner causes JVM warnings on Java 9 and beyond 

### ISSUE THREAD

**Issue by alexey-wg2** [dropwizard/dropwizard#2909]
When creating ObjectMapper instances with the `Jackson.newObjectMapper` method the Jackson’s Afterburner module is  registered causing the following JVM warning:

```
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.fasterxml.jackson.module.afterburner.util.MyClassLoader (file:.m2/repository/com/fasterxml/jackson/module/jackson-module-afterburner/2.9.9/jackson-module-afterburner-2.9.9.jar) to method java.lang.ClassLoader.findLoadedClass(java.lang.String)
WARNING: Please consider reporting this to the maintainers of com.fasterxml.jackson.module.afterburner.util.MyClassLoader
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
```

Please see more detailed information here:
https://github.com/FasterXML/jackson-modules-base/issues/37

It would be good to have an option in Dropwizard to disable the Afterburner module, or configure it not `setUseValueClassLoader(false)`, or use alternative Jackson Blackbird module https://github.com/stevenschlansker/jackson-blackbird.

One possible solution I can think of is to add a JackonModuleConfigService service provider interface which would return the Jackson module instances being registered, so the application can disable or reconfigure each individual module.

**Comment by whitfin** [comment]
I would personally recommend against using the custom Blackbird module; at least for the time being. It's very new, and it would generally be a bad idea to rely on something which doesn't necessarily have a proven maintenance path.

If `setUseValueClassLoader(false)` does work (and it seems so from the thread), then this is likely the better solution. It appears there might be small-ish performance hits, but I suppose we can't avoid it?
