### ISSUE TITLE
Validation for configuration constructor

### ISSUE THREAD

**Issue by maffe** [dropwizard/dropwizard#2931]
Given this class
```
public class MyConfig extends Configuration {

  private final Map<String, String> map;

  public MyConfig(@NotNull @JsonProperty("map") final Map<String, String> map) {
    this.map = Map.copyOf(map);
  }
}
```
a `NullPointerException` occurs if the configuration file does not contain the key `map`. `@NotNull` on the constructor parameter should prevent this, but this annotation only works on the field, which is too late. (Adding `@Valid` to the constructor does not seem to have any effect.)

I’m using Dropwizard 2.0.0-rc10.

**Comment by maffe** [comment]
😟

**Comment by maffe** [comment]
…

**Comment by joschi** [comment]
@maffe Code contributions welcome. 😉

Also, have you tried adding `@JsonCreator` to your constructor? Otherwise Jackson might not use it at all.

**Comment by maffe** [comment]
> Also, have you tried adding `@JsonCreator` to your constructor? Otherwise Jackson might not use it at all.

The parameterized (and only) constructor is used as long as the path to the config file is given on the command line:
https://github.com/dropwizard/dropwizard/blob/4e467e6f4de50dab897586727627e02ef0793788/dropwizard-core/src/main/java/io/dropwizard/cli/ConfiguredCommand.java#L125-L127 Even the `@JsonProperty` is not necessary when compiled with `-parameters`. The only problem is the validation which happens only after constructing.
