### ISSUE TITLE
Auto-pay for domain dropwizard.io

### ISSUE THREAD

**Issue by zhenik** [dropwizard/dropwizard#2933]
Hi, can not access documentation of dropwizard [https://dropwizard.io](https://dropwizard.io)

Problem domain registration expired:
```
nslookup https://dropwizard.io
Server:		10.0.0.1
Address:	10.0.0.1#53
** server can't find https://dropwizard.io: NXDOMAIN
```

```
Domain Name: DROPWIZARD.IO
Registry Domain ID: D503300000040506768-LRMS
Registrar WHOIS Server: whois.101domain.com
Registrar URL: https://www.101domain.com
Updated Date: 2019-09-17T23:32:55Z
Creation Date: 2013-09-17T23:30:21Z
Registry Expiry Date: 2019-09-17T23:30:21Z
Registrar Registration Expiration Date:
```

**Comment by jplock** [comment]
Thanks! I believe @joschi is trying to get it updated to point to Read The Docs in preparation for the DW 2.0.0 release.

**Comment by sudev** [comment]
Is there an IP or backup site through which I can access the docs? 

I tried dropwizard.github.io and it's redirecting to the same domain.

**Comment by sudev** [comment]
> Is there an IP or backup site through which I can access the docs?
> 
> I tried dropwizard.github.io and it's redirecting to the same domain.

Got it https://dropwizard.readthedocs.io
Thanks

**Comment by jplock** [comment]
https://dropwizard.github.io/dropwizard/1.3.14/docs/ should also work

**Comment by jplock** [comment]
https://dropwizard.io/ seems to be working again.  Closing.
