### ISSUE TITLE
Purpose of PULL_REQUEST_TEMPLATE.md ? (Remove if not required)

### ISSUE THREAD

**Issue by ravir2r91** [dropwizard/dropwizard#2934]
We can remove this file incase there is no plan to declare a template for PR's.

**Comment by devoto13** [comment]
Well, it is used as a template for the pull request. I.e. defines the content users see, when they create a pull request: 

<img width="757" alt="image" src="https://user-images.githubusercontent.com/823594/65253933-c2b81080-dafb-11e9-9a41-03889c96c0b7.png">

**Comment by ravir2r91** [comment]
Got it! Pops up when creating the PR, was expecting something while browsing through the repo. Thanks, it explains. Will close the issue.
