### ISSUE TITLE
Support the simple: „Ignore unrecognized arguments“ use case | aka: Support executing Java 9+ Module applications

### ISSUE THREAD

**Issue by lingocoder** [dropwizard/dropwizard#2942]
### Proposed Support

Please refactor *Dropwizard* to support executing a main class in a JPMS module by implementing the simple ability to ignore unrecognized arguments? An *argparse4j* contributor [*offered this as a basis*](https://github.com/argparse4j/argparse4j/issues/46#issuecomment-122288220) for this proposed ability.

### Context

Several new command line options were introduced to the Java Development Kit to support Java 9's Jigsaw feature. Two of those are the *`--module-path`* and the *`-m`* switches. Used together, they make it possible to execute a *`Main-Class`* of a Java application exposed by a Jigsaw module.

[*This is the `java` tool's description*](http://bit.ly/JavaRefrnc) of the usage of those options:

```
$java --help
Usage: java [options] <mainclass> [args...]
           (to execute a class)
   ...
   or  java [options] -m <module>[/<mainclass>] [args...]
       java [options] --module <module>[/<mainclass>] [args...]
           (to execute the main class in a module)
   ...
 Arguments following the main class, source file, -jar <jarfile>,
 -m or --module <module>/<mainclass> are passed as the arguments to
 main class.
``` 

### The Problem

Popular Java build tools append the following „*immutable system properties*“ to the end of every Java command that application developers explicitly specify:

```
<developer_supplied_java_args>...-Dfile.encoding=x-mac-roman -Duser.country=FR -Duser.language=fr -Duser.variant 
```

For example, consider the following *Dropwizard* application command line that would be produced by a build tool:

```
java --module-path build/libs/my.dropwizard.module.jar -m my.dropwizard.module/io.my.DropwizardApp db status my_dropwizard_app.yml -Dfile.encoding=x-mac-roman -Duser.country=FR -Duser.language=fr -Duser.variant
```

*Dropwizard* uses *argparse4j* to implement its underlying CLI feature. The above „*`db status`*“ arguments are legal *Dropwizard* arguments. However, the „*`-D...`*“ system properties — *appended to the command by the build tool* — cause *Dropwizard* to fail to execute the application. Through *argparse4j*, *Dropwizard* reports an „*`unrecognized arguments: -Dfile.encoding...`*“ error to *`stderr`*:

```
...
[ERROR] [system.err] unrecognized arguments: '-Dfile.encoding=x-mac-roman'
[ERROR] [system.err] usage: java -jar authentication-application.jar
[ERROR] [system.err]        db status [-h] [--migrations MIGRATIONS-FILE]
[ERROR] [system.err]        [--catalog CATALOG] [--schema SCHEMA] [-v] [-i CONTEXTS] [file]
[ERROR] [system.err]
[ERROR] [system.err] Check for pending change sets.
[ERROR] [system.err]
[ERROR] [system.err] positional arguments:
[ERROR] [system.err]   file                   application configuration file
[ERROR] [system.err]
[ERROR] [system.err] optional arguments:
[ERROR] [system.err]   -h, --help             show this help message and exit
...
```

The combination of three popular Java technologies (*Dropwizard*, *argparse4j*, *Gradle*) makes it practically impossible to use a modern JDK's *`--module-path`* and *`-m`* options. When those three are used together they break any JPMS-architected application that needs to execute an application in a module. That is because the implementation details of each one, combines with the other two, to produce a situation that does not comply with the JPMS specification.

### Steps to Reproduce

1. Clone or download [*this project*](https://bit.ly/mrJarZard)
2. Follow the setup instructions in that project's *`README`*, to configure and run the *Dropwizard* application
3. In the *`build.gradle`* located in the project's root directory, find the *`mrjar{}`* block of the *`project('authentication-application'`*) section of the script (*[go to line 96](http://bit.ly/mrJarWizL96)*)
4. Edit the *`mrjar`* block to be this:

    ```
    mrjar{
        main = 'com.alexkudlick.authentication.application.AuthenticationApplication'
        isModular = true
        moduleName = 'com.alexkudlick.authentication.application'
    } 
    ```
5. Open a terminal in the root directory of the project
6. Enter *`./gradlew -i -Dconsole=verbose --debug authentication-application:run`*
7. Observe the *`[ERROR] [system.err] unrecognized arguments: '-Dfile.encoding=windows-1252'`* failure message

### Expected Behavior

Just like the *Dropwizard/argparse4j* project in *Steps To Reproduce* section above, [*this other demo project*](http://bit.ly/mrJarularity) likewise implements a JPMS module that can be executed from the command. It, likewise, is built and ran using the *Gradle* build tool. However, the differences are <br /> 
 
* the latter is not implemented with *Dropwizard/argparse4j* <br />
* the later, therefore, ***is*** compliant with the *`java`* tool's expectations for executing a main class in a module <br />
* its [*`mrjar{}` configuration*](http://bit.ly/etSvcsL37) has an *`isModular = true`* property <br /> 

 That is to say: *Unlike the Dropwizard/argparse4j project, the other project Just Works because it — as expected — simply ignores any command line arguments passed to it that it's not interested in*.

### What Have You Tried So Far?

I have raised similar requests with both [*the argparse4j project*](https://github.com/argparse4j/argparse4j/issues/121) and [*the Gradle project*](https://github.com/gradle/gradle/issues/10825) .

TIA :+1:

**Comment by joschi** [comment]
@lingocoder After reading the issue and thinking a bit about it, I don't see anything for us to do.

The build tool in question seems to create the parameters for the invocation of `java` in the wrong order.

Even if the command-line argument parser used by Dropwizard was lenient and would ignore the unknown parameters, the result would still be wrong.

You already quoted it in your issue description:
> ```
> $java --help
> Usage: java [options] <mainclass> [args...]
>            (to execute a class)
>    ...
>    or  java [options] -m <module>[/<mainclass>] [args...]
>        java [options] --module <module>[/<mainclass>] [args...]
>            (to execute the main class in a module)
>    ...
>  Arguments following the main class, source file, -jar <jarfile>,
>  -m or --module <module>/<mainclass> are passed as the arguments to
>  main class.
> ```

**Comment by lingocoder** [comment]
Hey thanks for looking into this, @joschi.

> „*The build tool in question seems to create the parameters for the invocation of java in the wrong order...*“

Yeah, having thought about it further since opening this issue, it is pretty obvious that is a bug on Gradle's part. 

> „...*If the parameters setting system properties aren't provided before the `<mainclass>`, `-m`, `--module`, or `-jar` arguments, they won't be interpreted correctly by the JVM (`java`).*...“

Absolutely joschi! The peculiar thing about it is: Gradle *does* add those exact same properties to the beginning of the command line when they detect it's a regular *`--classpath`* command and not a *`--module-path`* command. Go figure!

Gradle seems to have taken a curiously anti-JPMS module stance for some reason. It almost seems like they're trying to intentionally throw a monkey wrench in any kind of widespread adoption of Java 9<sup>+</sup> modules. They do have [*a competing technology*](http://bit.ly/GrdlModlMetaData) that they would rather the Java developer community adopt over Java's built-in module system after all. So who can say?

**Comment by joschi** [comment]
> Gradle seems to have taken a curiously anti-JPMS module stance for some reason. It almost seems like they're trying to intentionally throw a monkey wrench in any kind of widespread adoption of Java 9+ modules.

Or maybe it's just a bug because not that many people are building projects using the JPMS with Gradle yet.

> They do have a competing technology that they would rather the Java developer community adopt over Java's built-in module system after all. So who can say?

You're mixing up dependency meta-data (what they're addressing with Gradle Module Metadata, not only for Java) and code modularity (with JPMS or OSGi).
