### ISSUE TITLE
Backport SLF4J Marker support to 1.3.x

### ISSUE THREAD

**Issue by toadzky** [dropwizard/dropwizard#2960]
I need the marker in my log aggregation stuff. It got added to the 2.x branch at the end of August (#2899). Are you guys ok with backporting to the 1.3.x branch?

**Comment by joschi** [comment]
@toadzky Would you provide a pull request for backporting this feature?
Would upgrading to Dropwizard 2.0.0 be an option for your application?

**Comment by toadzky** [comment]
Upgrading to 2.0 shouldn't be a problem once it's released. I can make a PR to backport it.

**Comment by toadzky** [comment]
any idea when the PR might get merged and released?

**Comment by joschi** [comment]
This will be part of Dropwizard 1.3.17.
