### ISSUE TITLE
Javadoc links on Dropwizard site don't work

### ISSUE THREAD

**Issue by mzamani1** [dropwizard/dropwizard#2970]
Clicking on any of the links on the Javadocs section of the Dropwizard site (https://www.dropwizard.io/en/stable/about/javadoc.html) leads to a "This page does not exist" error message.

http://dropwizard.io/en/dropwizard-core/apidocs/index.html

<img width="932" alt="Screen Shot 2019-10-08 at 11 23 50 AM" src="https://user-images.githubusercontent.com/2602978/66422200-1d87ae00-e9be-11e9-99be-32925cfbebd9.png">

**Comment by joschi** [comment]
@mzamani1 Thanks for reporting!

Links to the Javadoc should be fixed now.
