### ISSUE TITLE
Duration, SizeUnit could implement Serializable

### ISSUE THREAD

**Issue by cartermckinnon** [dropwizard/dropwizard#2971]
I often use `Duration` and `SizeUnit` for configuration parameters. Because these classes do not implement `java.io.Serializable`, they cause issues when Jackson isn't the serializer. For example, they cause exceptions in Spark jobs when utilized as part of the task (i.e. in a lambda).

I believe that implementing `Serializable` on these classes is low impact, since the interface is purely semantic. Adding a `serialVersionUID ` would be the only other change. Happy to PR this if someone agrees?

**Comment by mattnelson** [comment]
For Duration I would recommend using the JDK instead, which is already serializable. In fact it may be worth the discussion to see if dropwizard's Duration should be deprecated or modified to extend the JDK Duration.

https://docs.oracle.com/javase/8/docs/api/java/time/Duration.html

**Comment by cartermckinnon** [comment]
My use case is solely configuration; I prefer something friendly like `5 minutes` (in YAML, an environment variable, etc.) instead of the ISO-8601 duration format (`PnDTnHnMn.nS`). I agree that the JDK option should be chosen when possible, but I think the two implementations have different goals. There are various work arounds for this, so maybe it's not worth addressing upstream at this point. 🤷‍♂

**Comment by cartermckinnon** [comment]
Thank you, @joschi!
