### ISSUE TITLE
io.dropwizard.Configuration should lazy create server/metrics object

### ISSUE THREAD

**Issue by philipzhaoTS** [dropwizard/dropwizard#2973]
https://github.com/dropwizard/dropwizard/blob/master/dropwizard-core/src/main/java/io/dropwizard/Configuration.java#L65

The server/metric object is eager to be created. And this lead to setting up the chain of HTTP connector. If client does not want to use server command, this would result bringing up an HTTP server without actually using it.

I would suggest that we should lazy create this object when we needed to use it. 
For example, if client want to create **simple** instead of **default**. And it had to destroy **DefaultServerFactory** object first.

**Comment by pstackle** [comment]
Hi @philipzhaoTS, 
The line you indicated is actually creating a factory class and is not actually creating the server itself or any connectors. The server and connectors are only created when the `ServerFactory.build()` method is called, which is only called by the `ServerCommand` when it is run (https://github.com/dropwizard/dropwizard/blob/master/dropwizard-core/src/main/java/io/dropwizard/cli/ServerCommand.java#L49).

In terms of **simple** vs **default**, the way that Dropwizard has Jackson load configuration does not result in `DefaultServerFactory` being instantiated if `type: simple` is specified. The `DefaultServerFactory` object would only be created if `type: default` is specified or if the whole `server` section of the app's configuration .yml file was left off.

For more details about the startup process, you can check out the [Dropwizard Internals](https://www.dropwizard.io/en/stable/manual/internals.html) page.

**Comment by philipzhaoTS** [comment]
Thank you so much for responding this.

I saw this as part of my log: 
INFO  [2019-10-25 17:15:38,460] io.dropwizard.server.DefaultServerFactory: Registering jersey handler with root path prefix: /
INFO  [2019-10-25 17:15:38,463] io.dropwizard.server.DefaultServerFactory: Registering admin handler with root path prefix: /

Not sure why this was output and whether it was trying to create some http server in the back.

I used my own FooCommand class that extends EnvironmentCommand class, which extends ConfiguredCommand. And the command does not use any http server at all. 

Just to confirm when I use this, no http server is created.

**Comment by pstackle** [comment]
Those lines are logged when `DefaultServerFactory.configure(Environment)` method is called: https://github.com/dropwizard/dropwizard/blob/master/dropwizard-core/src/main/java/io/dropwizard/server/DefaultServerFactory.java#L181

That method is called from the `EnvironmentCommand.run(Bootstrap<T> bootstrap, Namespace namespace, T configuration)` method: https://github.com/dropwizard/dropwizard/blob/master/dropwizard-core/src/main/java/io/dropwizard/cli/EnvironmentCommand.java#L40

It isn't until the `ServerFactory.build(Environment)` method is called that the Jetty server would even be instantiated much less started (which isn't called by anything except for the `ServerCommand`).

**Comment by philipzhaoTS** [comment]
Cool, I can close this bug then.
