### ISSUE TITLE
Maven won't run tests

### ISSUE THREAD

**Issue by jumahuaca** [dropwizard/dropwizard#2982]
Hey,
I realized that shade maven plugin won't include test classes so if build a fat jar i can't run unit tests in that build. 
I've google a lot but I don't find a way to build a fat jar and run my tests in the same build. Is there another way to do it?

**Comment by joschi** [comment]
@jumahuaca That's intentional. Why should test classes ever end up in a production artifact?

If you really want to have that (I think you probably don't), you can configure Maven accordingly.

**Comment by jumahuaca** [comment]
I think shade has an option but is not working: https://stackoverflow.com/questions/5149130/how-can-i-configure-the-maven-shade-plugin-to-include-test-code-in-my-jar
It seems not a crazy thing to build the jar an run the tests (it's maven default). Can you tell me how do you do? You always use maven profiles?

**Comment by joschi** [comment]
@jumahuaca I run `./mvnw verify`.
