### ISSUE TITLE
dropwizard-testing JUnit 5 extensions documentation

### ISSUE THREAD

**Issue by dotTrench** [dropwizard/dropwizard#2995]
The current documentation (1.3.X) does not mention the built in support for JUnit 5 extensions added in #2166. 

Documentation for 2.0.0 has an example of DropwizardClientExtension, but it there's no references or examples of ResourceExtensions, DropwizardAppExtension or DAOTestExtension.

**Comment by joschi** [comment]
@dotTrench The JUnit 5 extension is documented in the current master branch which Dropwizard 2.0.x will be based on:

https://www.dropwizard.io/en/latest/manual/testing.html

**Comment by cricket007** [comment]
Those docs still seem to only include `DropwizardClientExtension`, though
