### ISSUE TITLE
Dropwizard 2.0: JDBI performance degradation

### ISSUE THREAD

**Issue by Alexey1Gavrilov** [dropwizard/dropwizard#3001]
I have noticed a significant performance degradation (> 25%) during the migration to Dropwizard 2.0 both in production and testing due to a newer JDBI version. The upstream issue: https://github.com/jdbi/jdbi/issues/1619

**Comment by Alexey1Gavrilov** [comment]
Resolved in JDBI 3.11.0! Newer version of JDBI provides significant performance improvement!

**Comment by stevenschlansker** [comment]
Please use `3.11.1` instead, the `.0` had a bug :)
