### ISSUE TITLE
Application doesn't throw exceptions

### ISSUE THREAD

**Issue by jay-ouellette** [dropwizard/dropwizard#3014]
`io.dropwizard.Application` doesn't throw exceptions so they can't be caught and logged.

Its very important to know why the app crashed but nothing shows-up in the logs if you call `System.exit()` bypassing all catch blocks.

Overriding `onFatalError()` doesn't work because `onFatalError()` doesn't provide the error message.

Users can catch and Exceptions and call System.exit() if they like that behavior.

**Comment by reneploetz** [comment]
I do not understand why you cannot see any logs.

Cli.run will call onError of the specific command:
https://github.com/dropwizard/dropwizard/blob/master/dropwizard-core/src/main/java/io/dropwizard/cli/Cli.java#L82

... as well as showing the error if the arguments could not be parsed:
https://github.com/dropwizard/dropwizard/blob/master/dropwizard-core/src/main/java/io/dropwizard/cli/Cli.java#L92

And Commands have a default handling of printing that stacktrace:
https://github.com/dropwizard/dropwizard/blob/master/dropwizard-core/src/main/java/io/dropwizard/cli/Command.java#L69
