### ISSUE TITLE
2.0.0 regression: @UriInfo always returns http as scheme

### ISSUE THREAD

**Issue by BenRomberg** [dropwizard/dropwizard#3023]
This used to work in 1.3.x, but no longer seems to work in 2.0.0-rc12:

```
public class TestApplication extends Application<Configuration> {
    @Override
    public void run(Configuration configuration, Environment environment) throws Exception {
        environment.jersey().register(TestResource.class);
    }

    public static void main(String[] args) throws Exception {
        new TestApplication().run(args);
    }

    @Path("/")
    public static class TestResource {
        @GET
        public String printUriInfoScheme(@Context UriInfo uriInfo) {
            return uriInfo.getBaseUri().getScheme();
        }
    }
}
```

Always returns "http", even if called using a https URL (e.g. using ngrok).

**Comment by joschi** [comment]
@BenRomberg Please describe your HTTPS setup in a little bit more detail.

Where is the TLS connection terminated? In a proxy in front of the Dropwizard application or are is the Dropwizard application providing the TLS termination itself (and serves something via HTTPS)?

**Comment by BenRomberg** [comment]
It's a proxied setup, without any TLS connection bound to Dropwizard. Relevant headers:
```
X-Forwarded-Proto: https
X-Forwarded-For: 1.2.3.4
Host: somehost.ngrok.io
```

So probably `X-Forwarded-Proto` is no longer respected?

**Comment by joschi** [comment]
> So probably `X-Forwarded-Proto` is no longer respected?

See `useForwardedHeaders`: https://www.dropwizard.io/en/latest/manual/configuration.html#connectors

**Comment by BenRomberg** [comment]
Thanks, that seems to solve it! Seems to have changed from true to false by default between 1.3 and 2.0.

Other than that, our upgrade to 2.0.0 went really smooth so far - thanks for keeping Dropwizard up to date :+1:

**Comment by creationw** [comment]
I had a similar issue:
My TLS terminate at Load Balancer. That is: client-->LB, this is TLS; from LB -->Backend Dropwizard Application: it is http, no https. 

The client is sending a request to: https://my-dns.com; my-dns.com is the DNS for the public IPs of my Load Balancer. 

- When I configured useforwardedHeaders to false:  the dropwizard application only see request as **http**://my-dns.com;
- 
- When I configured useforwardedHeaders to true:  the dropwizard application only see request as **https**://my-dns.com;

Any clue? My application needs to use useforwardedHeaders to false, but the request schema changes from https to http when I configure useforwardedHeaders to false

**Comment by joschi** [comment]
@creationw If you want to customize the behavior of the HTTP connector, you can create your own [`HttpConnectorFactory`](https://www.javadoc.io/doc/io.dropwizard/dropwizard-jetty/latest/io/dropwizard/jetty/HttpConnectorFactory.html) and override the [`HttpConnectorFactory#buildHttpConfiguration()`](https://www.javadoc.io/doc/io.dropwizard/dropwizard-jetty/latest/io/dropwizard/jetty/HttpConnectorFactory.html#buildHttpConfiguration--) method in which you can register your own customizer similar to Jetty's [`ForwardedRequestCustomizer`](https://www.eclipse.org/jetty/javadoc/current/org/eclipse/jetty/server/ForwardedRequestCustomizer.html).
