### ISSUE TITLE
Feature request: Use Hibernate JPA in AbstractDAO

### ISSUE THREAD

**Issue by ceqi** [dropwizard/dropwizard#3042]
Currently the AbstractDAO is using Hibernate native API. May I suggest we use Hibernate JPA instead.

The reasons are:

1. As per the Hibernate 6.0.0 Alpha 3 release notes: Hibernate makes less dependence on SessionFactory. [https://in.relation.to/2019/11/24/600-Alpha3-release/](url)
2. JPA, now Jakarta Persistence, is the standard API.
3. Developers who are new to dropwizard will get onboard faster, JPA is a subset of
Hibernate implementation and potentially more developers know about JPA than native API.

**Comment by joschi** [comment]
@ceqi Thanks for reporting this!

Would you be able to provide a PR illustrating the change which we can use as a basis for discussion?

**Comment by ceqi** [comment]
@joschi Sure, I'll start working on it. 
New to Dropwizard & Hibernate, I may have loads of questions 😃

**Comment by ceqi** [comment]
Apoligies for me faulty claim. 

I checked the source code and found out 
that the wrapper methods are using JPA API when possible.
So I'm closing this feature request.
