### ISSUE TITLE
InstrumentedHandler is incompatible with Jetty version in 2.0.0-rc13

### ISSUE THREAD

**Issue by skradel** [dropwizard/dropwizard#3045]
Asynchronous responses raises an exception from com.codahale.metrics.jetty9.InstrumentedHandler because DISPATCHED is not a member of enum type org.eclipse.jetty.server.HttpChannelState.State (org.eclipse.jetty:jetty-server:9.4.23.v20191118)

> WARN  o.e.jetty.server.HttpChannelState - java.lang.NoSuchFieldError: DISPATCHED while invoking onComplete listener com.codahale.metrics.jetty9.InstrumentedHandler$7@66d27937

**Comment by skradel** [comment]
See also https://github.com/eclipse/jetty.project/issues/4169

**Comment by joschi** [comment]
@skradel Thanks for reporting this!

Could you please check if the problem still exists with Dropwizard 2.0.0-rc14?

**Comment by skradel** [comment]
This appears quieted in metrics-jetty9:4.1.2 although one can't help noticing the conspicuous presence of:

> private HttpChannelState.State DISPATCHED_HACK;
