### ISSUE TITLE
Update documentation for testing with JUnit5

### ISSUE THREAD

**Issue by orevial** [dropwizard/dropwizard#3051]
Dropwizard already supports JUnit5 since 2 years now but the documentation still points to JUnit4. 
It would be nice to add JUnit5 info as the default documentation and to rename the actual ["JUnit" part](https://dropwizard.readthedocs.io/en/stable/manual/testing.html#id2) to "JUnit4" or "JUnit4 compatibility".

More generally, entire documentation about testing could mention JUnit5 instead of / in addition to actual JUnit4 doc

**Comment by joschi** [comment]
@orevial I absolutely agree!

Would you be able to provide a PR which addresses some of this issue?
It doesn't have to be perfect or cover 100% of the changes.

**Comment by cricket007** [comment]
I found a related issue last month. At the time, it simply said refer to the Javadoc of the extension classes (which was good enough), but proper docs would be great 👍

**Comment by orevial** [comment]
Yes I have started a PR, I will try to submit it by the end of the week !

**Comment by orevial** [comment]
PR submitted, let me know if that sounds good

**Comment by joschi** [comment]
Addressed in #3062.
