### ISSUE TITLE
Length validation in example doesn't work

### ISSUE THREAD

**Issue by acsbendi** [dropwizard/dropwizard#3053]
I created the simple example app based on the [Getting Started guide](https://www.dropwizard.io/en/stable/getting-started.html), and I run into a problem. The `Saying` class has the `@Length(max = 3)` annotation on its `content` property (see [here](https://github.com/dropwizard/dropwizard/blob/ecb4331543d17ee5bbea6e940ee947a33feb3622/dropwizard-example/src/main/java/com/example/helloworld/api/Saying.java#L9)), The guide states 
> Lastly, the bean leverages validation to ensure the content size is no greater than 3.

This, to my understanding, should prevent any attempt to assign a string longer than 3 characters to the `content` property.

However, this does not seem to work. For example, when running `curl localhost:8080/hello-world`, the `content` will be `"Hello, Stranger!"` which is clearly longer than 3 characters. 

Please let me know if I'm misunderstanding something.

**Comment by skradel** [comment]
I'm inclined to agree with you that the example given in the Getting Started guide is somewhat nonsensical; type "Saying" is only used as a return value type from a resource method, whereas most validation situations are more concerned with validating user input, e.g. validating a POSTed bean or validating URL query parameters.

That said, adding the annotation to the resource method as "public @Valid Saying sayHello" could be used to show a more unusual usage to generate HTTP 5xx errors, where the server found the user's request acceptable but was unable to generate a valid response.

**Comment by acsbendi** [comment]
@skradel Yes, it could be simply removed. I just had the assumption that it's there to show some functionality, disregarding whether it actually makes sense or not. But then again, it didn't seem to have any.

Even that version with the `@Valid` annotation would be better I think, because at least the `@Length(max = 3)` would have some functionality.

**Comment by joschi** [comment]
@acsbendi Thanks for reporting this!

Would you or @skradel be able to provide a PR to improve our example project?

**Comment by acsbendi** [comment]
@joschi You're welcome!

Do you think it's enough to just remove this annotation and the related text? Or do you have an idea for a more useful way of having this annotation?

**Comment by acsbendi** [comment]
Fixed in #3082.
