### ISSUE TITLE
Add support for Java8 date/time in @QueryParam

### ISSUE THREAD

**Issue by beena-yatin-kanyal** [dropwizard/dropwizard#3057]
`@QueryParam` annotation for `LocalDateTimeParam` datatype is throwing parsing exception for valid ISO format dates.
```
"2019-09-30T21:34:54+0000"
"2019-09-30T21:34:54.000Z"
"2019-09-30T21:34:54Z"
"2019-09-30T21:34:54+00:00"
"2019-09-30T21:34:54+05:30"
"2019-09-30T21:34:54-05:30"
"2019-09-30T21:34:54"
"2019-09-30T21:34:54+0500"
```
Also tried `Optional<LocalDateTimeParam>` option but still the same error. Please check and let us know when this'll be addressed. 

Exception logs-
```
{
    "code": 400,
    "message": "Parameter is invalid: Text '2019-10-30T12:07:12Z' could not be parsed, unparsed text found at index 10"
}
```

**Comment by joschi** [comment]
@beena-yatin-kanyal Thanks for reporting this!

Which version of Dropwizard are you using?
Could you please provide a minimal project or a test case to reproduce your issue?

**Comment by beena-yatin-kanyal** [comment]
@joschi  - We are using dropwizard version - 1.3.16 below is the sample code we are using to send the string via the postman. 

Postman request - `{{protocol}}://{{baseUrl}}:{{somePort}}/myconnector/myuri/timestamp?start-date-time={{startDateTime}}&end-date-time={{endDateTime}}`

```
@Path("/timestamp")
    @CacheControl(noCache = true)
    public Response checkTimestamp(
            @Nullable @QueryParam("start-date-time") final Optional<LocalDateTimeParam> startDateTime,
            @Nullable @QueryParam("end-date-time") final Optional<LocalDateTimeParam> endDateTime,
            @Context final UriInfo uriInfo) {
        LOGGER.info("Reading the start timestamp: {} and end timestamp: {}.", startDateTime, endDateTime);
        return Response.status(Response.Status.OK).entity(Collections.emptyList()).build();
    }
```
For start and end DateTime samples you can refer to the initial thread. Let me know if you need any further information.

**Comment by skradel** [comment]
Have you tried not wrapping the param in Optional (whatever flavor of Optional it is, possibly unsupported here)?  The exception you provided doesn't definitively suggest a datetime parsing problem.

**Comment by beena-yatin-kanyal** [comment]
@skradel - I already tried that but it says incompatible operand type.

**Comment by cricket007** [comment]
I've been able to use Instant class for query param dates

**Comment by pkwarren** [comment]
Of all the examples provided, only `2019-09-30T21:34:54` can be parsed by `java.time.LocalDateTime.parse` without throwing a DateTimeParseException (because it doesn't specify zone information). All of the values that specify a time zone should be parsed with ZonedDateTimeParam instead of LocalDateTimeParam.

The examples `2019-09-30T21:34:54+0000`, `2019-09-30T21:34:54`, `2019-09-30T21:34:54+0500` can't be parsed as a ZonedDateTime (either the timezone is invalid or not specified).
