### ISSUE TITLE
Custom ExceptionMapper mapper is not catching swagger validation

### ISSUE THREAD

**Issue by ktalebian** [dropwizard/dropwizard#3083]
I have a custom exception mapper:

```java
@Provider
public class AppExceptionMapper implements ExceptionMapper<Exception> {
    @Context
    private HttpServletRequest httpRequest;
  
    @Override
    public Response toResponse(final Exception e) {
        if (e instanceof ValidationException) {
           // return a custom Response here
        } 
        // other mappers
    }
}
```

And have it registered as `environment.jersey().register(new AppExceptionMapper());`

This would work when in my code I do `throw new ValidationException(...)`. However, I have swagger annotations for validating the request:

```java
@POST
public void doSomething(@Valid @NotNull final SomeObject object);
```

When this validation fails, my custom exception mapper does not catch it, and the generic exception is returned. I put a breakpoint inside `ValidationException`, and swagger does throw this exception, but for some reason, my exception mapper is not catching it.

How come?

**Comment by reneploetz** [comment]
(These are likely not swagger annotations, but javax.validation / hibernate-validator annotations.)

As you also commented in https://github.com/dropwizard/dropwizard/issues/2380 and https://github.com/eclipse-ee4j/jersey/issues/3425 I would assume you tried to register this exact class in Jersey.

Did you try the approach stated in the upstream ticket you commented on?
```
environment.jersey().register(new AbstractBinder() {
    @Override
    protected void configure() {
        bind(CustomExceptionMapper.class).to(ExceptionMapper.class).in(Singleton.class);
    }
});
```

Note that the referenced `CustomExceptionMapper`class must implement `ExceptionMapper<ValidationException>` and therefore use `javax.validation.ValidationException` as parameter to `toResponse` to override the default jersey implementation. This means you cannot use a generic exception mapper for the whole application.
