### ISSUE TITLE
Potential memory leak

### ISSUE THREAD

**Issue by carlbolduc** [dropwizard/dropwizard#3094]
Dropwizard version: 1.3.17
JDK version: 11

We have a REST API built on top of Dropwizard. This API is used by two websites and there are around 5000 active users (not concurrent). Since we started getting more users, we also started to have memory problems on our servers. We have two API servers, each have 1 GB of RAM and their only purpose is to run the API. CPU usage is extremely low, the only issue we have is with memory.

When we start the service, the server used memory is around 500 MB. Then, slowly, the used memory increases to over 900 MB and our user start having problem logging in. Since this is a REST API, we aren't keeping any data so my assumption is that the memory usage should remain stable.

Here is a snapshot of the memory on December 12:
```
 num     #instances         #bytes  class name (module)
-------------------------------------------------------
   1:         94232        8849440  [B (java.base@11.0.4)
   2:         83376        2001024  java.lang.String (java.base@11.0.4)
   3:         11925        1409680  java.lang.Class (java.base@11.0.4)
   4:         39832        1274624  com.codahale.metrics.WeightedSnapshot$WeightedSample
   5:          9254        1172952  [I (java.base@11.0.4)
   6:           862        1013584  [C (java.base@11.0.4)
   7:         31533        1009056  java.util.concurrent.ConcurrentHashMap$Node (java.base@11.0.4)
   8:         11279         992552  java.lang.reflect.Method (java.base@11.0.4)
   9:         40068         961632  java.util.concurrent.ConcurrentSkipListMap$Node (java.base@11.0.4)
```

Here is another snapshot for the same server on January 5:
```
 num     #instances         #bytes  class name (module)
-------------------------------------------------------
   1:         13377       19390000  [I (java.base@11.0.4)
   2:        107254       10724240  [B (java.base@11.0.4)
   3:         76634        2452288  com.codahale.metrics.WeightedSnapshot$WeightedSample
   4:         95478        2291472  java.lang.String (java.base@11.0.4)
   5:         76927        1846248  java.util.concurrent.ConcurrentSkipListMap$Node (java.base@11.0.4)
   6:         76636        1839264  java.lang.Double (java.base@11.0.4)
   7:         12236        1444728  java.lang.Class (java.base@11.0.4)
   8:           875        1296120  [C (java.base@11.0.4)
   9:         11573        1018424  java.lang.reflect.Method (java.base@11.0.4)
```

The only thing I can see in there is that `WeightedSnapshot` keeps getting bigger over time. Is this normal?

My only workaround for now is to restart the server once a week. I would appreciate any input to help me troubleshoot this.

**Comment by joschi** [comment]
@carlbolduc Your snapshot shows a lot of byte (`[B`) and integer (`[I`) arrays using up most of the memory.

The `WeightedSample` instances only use 2.4 MiB of memory in your snapshot from January 5.

Could you provide a little more detail about your application, for example the specific JVM settings you're using to run it?

How exactly did you create the top-9 lists?

**Comment by carlbolduc** [comment]
@joschi I'll try to share as much as I can. The project is in a private repo so I cannot share the actual code.

This top 9 is generated using the following command: `jmap -histo:live pid`
I can't dump everything since the server is not having enough memory to perform the dump.

The application is started by a service running the following command: `java -Xms512m -Xmx512m -jar api.jar server config.yml'`

The project is built using Gradle. Here is the list of libraries in the project:
jaxb-api (JDK 11 compatibility)
jaxb-runtime (JDK 11 compatibility)
dropwizard-core
dropwizard-jdbi3
dropwizard-migrations
dropwizard-forms
dropwizard-auth
postgresql
aws-java-sdk-s3
dropwizard-template-config
argon2-jvm
okhttp

All the routes are secured through a token Authenticator. The Authorizer returns the roles of the user and each route is protected by roles. Most of the routes will query the database and return data to the user initiating the request.

**Comment by carlbolduc** [comment]
What is the recommended Garbage Collection algorithm for Dropwizard based REST API? I think that the default one is G1 GC in Java 11. Since the memory slowly ramps up, I was wondering if it could be related to a lack of garbage collection instead of a memory leak.

**Comment by vinitgaikwad0810** [comment]
@carlbolduc Would you mind sharing the resolution?

**Comment by carlbolduc** [comment]
I was using an AWS server with 1 GB of RAM. I switched to a server with 2GB of RAM and the problem completely disappeared. I remember seeing in a forum a suggestion  to give something around 6 GB to the Dropwizard process which prompted me to try a bigger server.

**Comment by anmol1vw13** [comment]
@carlbolduc How are you giving 6GB to dropwizard with 2GB of ram? Is 6GB a typo?

**Comment by carlbolduc** [comment]
@anmol1vw13 I'm giving 1 GB to the Dropwizard process. When I saw the recommendation to give around 6 GB to the Dropwizard process, I realized that my 1 GB server was most likely too small. I started by increasing the server RAM capacity to 2 GB to see if it would help and the problem disappeared.

**Comment by gbanusi** [comment]
> When we start the service, the server used memory is around 500 MB. Then, slowly, the used memory increases to over 900 MB

So you are saying that now it doesn't increase to over 900MB? I have a similar problem, but my server starts at 100MB and increases to 900MB. We also have AWS 1GB

**Comment by carlbolduc** [comment]
@gbanusi We have switched to a 2GB server (from a 1GB server), we are using t3.small instances. The app is started with the following parameters:
`java -Xms1g -Xmx1g -jar ...`

The java process will still go beyond 1GB though, it's currently using 1264MB of RAM. However, we don't end up in the situation where the servers becomes unresponsive, even after several weeks of up time. We do restart the servers when there is an update which happens almost every week.
