### ISSUE TITLE
Support for dropwizard metrics 5

### ISSUE THREAD

**Issue by deathwarrior60** [dropwizard/dropwizard#3099]
Does the support for dropwizard metrics v5 is planned ?

Regards

**Comment by joschi** [comment]
@deathwarrior60 Dropwizard Metrics 5.0.x is in fact older than any recent release of Dropwizard Metrics 4.1.x and not actively worked on.

Dropwizard will eventually support Dropwizard Metrics 5.x, if there's a stable and maintained release of it.

**Comment by deathwarrior60** [comment]
Understood.
Thanks
