### ISSUE TITLE
jackson-databind-2.9.10.1

### ISSUE THREAD

**Issue by shubhankar1114** [dropwizard/dropwizard#3107]
There is a vulnerability issue in dropwizard version - 1.3.17

![image](https://user-images.githubusercontent.com/52689846/72719706-59760600-3b9e-11ea-9860-2fe470e76264.png)

**Comment by joschi** [comment]
@shubhankar1114 Thanks for reporting this!

The issue has been addressed in #3100 and will be released with [Dropwizard 1.3.18](https://github.com/dropwizard/dropwizard/milestone/53).
