### ISSUE TITLE
HttpServletRequest no longer contains scheme

### ISSUE THREAD

**Issue by ljl** [dropwizard/dropwizard#3118]
Since dropwizard 2.0 `HttpServletRequest` injected by `@Context` no longer contains scheme

See image:
![Skjermbilde 2020-01-29 kl  16 24 23](https://user-images.githubusercontent.com/414079/73370209-25909400-42b4-11ea-8c92-fa0897e8830c.png)

This causes a problem, even though we terminate SSL before the app, we still want to get the URI a client requested. 

One example is Hawk tokens. They are created on the client using the URI you want to request and some shared secret. Then it is recreated on the server using the requested URI and the same secret and compared. However since the scheme is no longer in the request it default to `http://` and if the client requested a `https://` url we wont be able to match the token.

**Comment by pkwarren** [comment]
I wonder if this is a side effect of the change in #2748 added in 2.0. You might want to try setting `useForwardedHeaders=true` for your HTTP connector to restore the old behavior.

**Comment by ljl** [comment]
Setting `useForwardedHeaders=true ` worked

**Comment by joschi** [comment]
@ljl Thanks for the update!

I'll close the issue since the question has been answered by @pkwarren.
