### ISSUE TITLE
default value not applied to optional parameter type

### ISSUE THREAD

**Issue by chris-orchard** [dropwizard/dropwizard#3123]
I'm updating my application from 1.3.16 to dropwizard 2 and have changed the parameter on a method from a `LongParam` to `OptionalLong` as detailed in the deprecation warning for `LongParam`. 

I've also changed my code to call `getAsLong()` now that the parameter type no longer has a `get()` method.  Here's the code following updating to dropwizard 2. 

```
	@ExceptionMetered
	@GET
	@Path("/search")
	@Timed
	@ApiOperation(
			value="search",
			tags="Search",
			notes="Searches all records")
	@ApiResponses(value =
			{ @ApiResponse(code = 400, message = "'fromId' parameter is mandatory") })
	public ResultPage<Result> search(
			@Auth final ServiceUser user,
			@QueryParam("fromId") @DefaultValue("0") final OptionalLong fromId,
			@QueryParam("department") final Set<String> departments,
			@QueryParam("area") final Set<String> areas) {

		final Long idFrom = fromId.getAsLong();
		final List<Result> records = tenancyDao.execute(idFrom, departments, areas);

		return new ResultPageFactory<Result>(pageLimit).build(records);
	}
```

However now my `DefaultValue` annotation on the parameter no longer seems to be getting set when no value is passed to the parameter. This causes the exception from `fromId.getAsLong()` but I would expect it to always have a value due to the default value:
```
! java.util.NoSuchElementException: No value present
! at java.util.OptionalLong.getAsLong(OptionalLong.java:118)
```

Debugging through has led me to [this line in `SingleValueExtractor`](https://github.com/eclipse-ee4j/jersey/blob/2.29.1/core-server/src/main/java/org/glassfish/jersey/server/internal/inject/SingleValueExtractor.java#L61):
```
return fromString((value == null && isDefaultValueRegistered()) ? getDefaultValueString() : value);
```

At this point `value` is `""` (empty string) so although `isDefaultValueRegistered()` is `true`, it uses `value` instead of the default value.

**What do I need to do to get it to use the default value when none is set, as it did with dropwizard 1.3.x?**

Note before I updated my code to use `OptionalLong` I was getting `java.lang.NumberFormatException: For input string: ""` from [this line in `AbstractParam`](https://github.com/dropwizard/dropwizard/blob/release/2.0.x/dropwizard-jersey/src/main/java/io/dropwizard/jersey/params/AbstractParam.java#L35) when the `LongParam` constructor was called, but the cause was the same: my param had a value of empty string instead of the default.

**Comment by pkwarren** [comment]
I've tried to reproduce this with a testcase in dropwizard and with a simple hello world app with DropWizard 2.0.0 and 2.0.1 and am not able to recreate the issue. In all cases the `@DefaultValue` annotation is being used and the code is working as expected.

Would it be possible for you to provide a testcase to reproduce the problem? Without knowing more details, I'm wondering if there might be different versions of DropWizard libraries on the classpath.

**Comment by chris-orchard** [comment]
Apologies for the long reply but these are taken form my notes from debugging the differences and I thought they might help you pinpoint the issue? 

---

I've further debugged the stacktrace for my app with both the old and new library versions, and with the new libraries tried my parameter type as both `LongParam` and `OptionalLong`.

Combinations tested:

1. dropwizard 1.3.16 and `LongParam`
2. dropwizard 2.0.0 and `LongParam`
3. dropwizard 2.0.0 and `OptionalLong`


My initial comment that [this line in `SingleValueExtractor`](https://github.com/eclipse-ee4j/jersey/blob/2.29.1/core-server/src/main/java/org/glassfish/jersey/server/internal/inject/SingleValueExtractor.java#L61) was where the error occurred was wrong:
```
return fromString((value == null && isDefaultValueRegistered()) ? getDefaultValueString() : value);
```

There seems to be little changed here between Jersey **2.25.1** (being included when using dropwizard 1.3.16) and **2.29.1** (included when using dropwizard 2.0.0) in this area (except line numbers) and the above code behaves the same for all 3: `value` is always `""` and this gets passed to `fromString`.

Stepping in further, the issue with the default value not being set is here where the result of `convert` is checked in
[`AbstractParamValueExtractor.fromString`](https://github.com/eclipse-ee4j/jersey/blob/2.29.1/core-server/src/main/java/org/glassfish/jersey/server/internal/inject/AbstractParamValueExtractor.java#L107)
```
    protected final T fromString(String value) {
        T result = convert(value);
        if (result == null) {
            return defaultValue();
        }
        return result;
    }
```

The value of `result` returned form `convert` is different in each of the above tests as follows: 
1. `result = null`. So calls `defaultValue()` and works correctly.
2. Exception thrown from `convert` so Exception throws up from here and never calls through to my method. 
3. `result = OptionalLong.empty` this is not `null` so is returned as `result`, `defaultValue()` is not called. Call continues through to my method and gives the error when I call `fromId.getAsLong()`, as you'd expect from an `OptionalLong.empty` parameter value due to it having `isPresent=false`. 



Stepping further in the difference is what `convert` resolves to in each case.

This line in `org.glassfish.jersey.server.spi.internal.ParameterValueHelper.getParameterValues(List<ParamValueFactoryWithSource<?>>, ContainerRequest)` has changed to this in [2.29.1](https://github.com/eclipse-ee4j/jersey/blob/2.29.1/core-server/src/main/java/org/glassfish/jersey/server/spi/internal/ParameterValueHelper.java#L64):
```
                params[index++] = paramValProvider.apply(request);
```
Previously it called this in [2.25.1](https://github.com/jersey/jersey/blob/2.25.x/core-server/src/main/java/org/glassfish/jersey/server/spi/internal/ParameterValueHelper.java#L90):
```
                params[index++] = paramValProvider.provide();
```

This means that `convert` is following a different execution in each and seems responsible for the different values returned as follows:

1.
```
AbstractParamConverterProvider$1.fromString(String) line: 49	
SingleValueExtractor<T>(AbstractParamValueExtractor<T>).convert(String) line: 139	
SingleValueExtractor<T>(AbstractParamValueExtractor<T>).fromString(String) line: 130	
SingleValueExtractor<T>.extract(MultivaluedMap<String,String>) line: 84	
QueryParamValueFactoryProvider$QueryParamValueFactory.provide() line: 89	
ParamValueFactoryWithSource<T>.provide() line: 71	
ParameterValueHelper.getParameterValues(List<ParamValueFactoryWithSource<?>>) line: 90	
```
 
2. 
```
AbstractParamConverter<T>._fromString(String) line: 50	
AbstractParamConverter<T>.fromString(String) line: 36	
SingleValueExtractor<T>(AbstractParamValueExtractor<T>).convert(String) line: 116	
SingleValueExtractor<T>(AbstractParamValueExtractor<T>).fromString(String) line: 107	
SingleValueExtractor<T>.extract(MultivaluedMap<String,String>) line: 61	
QueryParamValueParamProvider$QueryParamValueProvider.apply(ContainerRequest) line: 78	
QueryParamValueParamProvider$QueryParamValueProvider.apply(Object) line: 65	
ParamValueFactoryWithSource<T>.apply(ContainerRequest) line: 50	
ParameterValueHelper.getParameterValues(List<ParamValueFactoryWithSource<?>>, ContainerRequest) line: 64	
```

3. 
```
OptionalLongParamConverterProvider$OptionalLongParamConverter.fromString(String) line: 30	
OptionalLongParamConverterProvider$OptionalLongParamConverter.fromString(String) line: 26	
SingleValueExtractor<T>(AbstractParamValueExtractor<T>).convert(String) line: 116	
SingleValueExtractor<T>(AbstractParamValueExtractor<T>).fromString(String) line: 107	
SingleValueExtractor<T>.extract(MultivaluedMap<String,String>) line: 61	
QueryParamValueParamProvider$QueryParamValueProvider.apply(ContainerRequest) line: 78	
QueryParamValueParamProvider$QueryParamValueProvider.apply(Object) line: 65	
ParamValueFactoryWithSource<T>.apply(ContainerRequest) line: 50	
ParameterValueHelper.getParameterValues(List<ParamValueFactoryWithSource<?>>, ContainerRequest) line: 64	
```

One difference is that in 1. the [1.3.16 version of `AbstractParamConverter.fromString`](https://github.com/dropwizard/dropwizard/blob/release/1.3.x/dropwizard-jersey/src/main/java/io/dropwizard/jersey/params/AbstractParamConverterProvider.java#L49) does an explicit call to `com.google.common.base.Strings.isNullOrEmpty(value)`, and so returns `null` for empty string. This check here seems to be responsible for making it then use the default value.

This has changed in [2.0.0](https://github.com/dropwizard/dropwizard/blob/v2.0.0/dropwizard-jersey/src/main/java/io/dropwizard/jersey/params/AbstractParamConverterProvider.java) and it no longer has a check for empty string.
However from the traces above it doesn't actually appear to be called called anymore - the trace for 2. calls through to `io.dropwizard.jersey.params.AbstractParamConverter<T>.fromString` instead - and there's [no empty string checking here](https://github.com/dropwizard/dropwizard/blob/release/2.0.x/dropwizard-jersey/src/main/java/io/dropwizard/jersey/params/AbstractParamConverter.java#L36) - it just blows up with the exception.
 
Similarly in case 3. [`io.dropwizard.jersey.optional.OptionalLongParamConverterProvider.OptionalLongParamConverter.fromString(String)`](https://github.com/dropwizard/dropwizard/blob/release/2.0.x/dropwizard-jersey/src/main/java/io/dropwizard/jersey/optional/OptionalLongParamConverterProvider.java#L30) has no explicit empty string check. The parse error results in an `OptionalLong.empty` as detailed earlier.

So there appears to be no equivalent code in 2.0.0 (at least with the rest of my config) that does this explicit empty string check for either 2. or 3. that appears needed to get it to then use the deafult value.  



Does that give you any ideas what it might be or how to fix this? Or does this differ from your hellow world example if you set breakpoints and debug from here? 

If not I'll take a look at trying to create a simple reproduceable for this.


---

> I'm wondering if there might be different versions of DropWizard libraries on the classpath.

I've checked the gradle build scan for my application and all dropwizard dependencies are at 2.0.0 (for test 2. and 3.).

**Comment by pkwarren** [comment]
Thanks for the explanation. I had tested providing and not providing a value but hadn't tried an empty value. Here's what I see with various inputs (where `n/a` means it doesn't matter what value is provided):

|Parameter Value|Default Value|Result|
|-|-|-|
|`"1"`|`n/a`|`OptionalLong.of(1L)`|
|||`OptionalLong.empty()`|
||`"0"`|`OptionalLong.of(0L)`|
|`""`||`OptionalLong.empty()`|
|`""`|`"0"`|`OptionalLong.empty()`|
|`"invalid"`|`n/a`|`OptionalLong.empty()`|
||`""`|`OptionalLong.empty()`|
||`"invalid"`|`OptionalLong.empty()`|

It sounds like the desired behavior for your use case is to use the `@DefaultValue` when the parameter is specified (but with an empty string).

If I compare to Jersey's handling of Long value, I get the following:

|Parameter Value|Default Value|Result|
|-|-|-|
|`"1"`|`n/a`|`1L`|
|||`null`|
||`"0"`|`0L`|
|`""`||null|
|`""`|`"0"`|`0L`|
|`"invalid"`|n/a|null|
||`""`|null|
||`"invalid"`|null|

Here's the part which makes Long work: https://github.com/eclipse-ee4j/jersey/blob/472436d3eca7940b05da0c006685e28057b28a33/core-common/src/main/java/org/glassfish/jersey/internal/inject/ParamConverters.java#L61-L64

So Long and OptionalLong differ in the behavior of how they handle an empty string. Making this change would break backwards compatibility with anyone relying on the current behavior so that will need to be considered.

One option for your use case might be to just use a `long` primitive parameter if the `@DefaultValue` is always 0.

**Comment by chris-orchard** [comment]
Thanks for that explanation and looking into this further.

> It sounds like the desired behavior for your use case is to use the `@DefaultValue` when the parameter is specified (but with an empty string).

Yes that's correct, but only because that's the behaviour I see currently in my application with dropwizard 1.3.16 and `LongParam` parameter types. 

However I'm still unclear why the behaviour appears to have changed between dropwizard 1.3.16 and 2.0.0 versions when still using `LongParam`? 

Ideally I just want to update my libraries to the dropwizard 2.0.x versions, and minimise the other code changes in my next application version. In my previous post this is what tests 1. and 2. were based on: just updating libraries for my project with no other changes.

Here's the simplified results from my testing of this use case:

Test | dropwizard | Param Type | Parameter Value | Default Value | Result
-- | -- | -- | -- | -- | --
1 | 1.3.16 | `LongParam` | `""` | `"0"` | `0L`
2 | 2.0.0 | `LongParam` | `""` | `"0"` | `java.lang.NumberFormatException: For input string: ""`
3 | 2.0.0 | `OptionalLong` | `""` | `"0"` | `OptionalLong.empty()`

It's the difference between 1 and 2 that appears to be a bug / regression for me from my testing, and is causing my issue with updating to dropwizard 2.0.0.

I only tried 3. (swapping one method to `OptionalLong`) to see if it resolved my issues.

 
> One option for your use case might be to just use a `long` primitive parameter if the `@DefaultValue` is always 0.

Yes that might work, and be less refactoring than with changing everywhere to `OptionalLong`. But preferably I'd continue using `LongParam` for now to avoid this refactoring and breaking lots of tests in my project in the process.

**Comment by chris-orchard** [comment]
@pkwarren Thanks for the help and quick turnaround on this. I see it's merged to master. When's the next release including this expected to be?
