### ISSUE TITLE
Missing jdbi2 module release

### ISSUE THREAD

**Issue by cleiner** [dropwizard/dropwizard#3129]
The jdbi2 module mentioned in the [2.0.x upgrade guide](https://github.com/dropwizard/dropwizard/wiki/Upgrade-guide-1.3.x-to-2.0.x#support-for-jdbi-2x-moved-out-of-dropwizard-core-modules) is not available on Maven Central. I've already opened an [issue](https://github.com/dropwizard/dropwizard-jdbi/issues/1) in its repository, but fear it has gone unnoticed... ?

**Comment by joschi** [comment]
@cleiner Thanks for the reminder! I planned to release dropwizard-jdbi over the weekend.

I'll close this issue and track it in the original repository.
