### ISSUE TITLE
JPMS - split package `io.dropwizard.validation`

### ISSUE THREAD

**Issue by willpdp** [dropwizard/dropwizard#3131]
`io.dropwizard.validation` is a split package between dropwizard-core and dropwizard-validation. 
 Because of that I wasn't able to compile my app as a JPMS module.

[using 2.0.1] I tested moving `io/dropwizard/validation/InjectValidatorFeature.class` from dropwizard-core.jar into dropwizard-validation.jar and my app can build using JPMS and seems to run ok.

That's probably not the right fix for this but it got rid of the split package issue.  Could `io.dropwizard.validation` have a different package name in dropwizard-core or should that class move into dropwizard-validation?

**Comment by joschi** [comment]
Refs #3233

**Comment by joschi** [comment]
Closed via #3233.
