### ISSUE TITLE
Support for setting SameSite attribute on HttpSession JSESSIONID cookie

### ISSUE THREAD

**Issue by LouiseEH** [dropwizard/dropwizard#3138]
Hi,

A Chrome update will cause the SameSite cookie attribute to be set to lax be default, if it is not set.
I need to set the value to "None", but as far as I can see, the SameSite attribute cannot currently be set via e.g. javax.servlet.SessionCookieConfig.

C.f. https://github.com/eclipse/jetty.project/issues/4247 Jetty is enabled from version 9.4.27 to handle configuration of the SameSite attribute, but the latest dropwizard version uses 9.4.25.

When version 9.4.27 is used, I believe the attribute can be set via:
environment.getApplicationContext().getServletContext().setAttribute(HttpCookie.SAME_SITE_DEFAULT_ATTRIBUTE, "NONE");

Thanks,
-Louise

**Comment by joschi** [comment]
@LouiseEH Thanks for reporting this!

Dropwizard 2.0.9 is using Jetty 9.4.28.v20200408, so I think this issue has been solved:
https://github.com/dropwizard/dropwizard/blob/v2.0.9/dropwizard-dependencies/pom.xml#L52

**Comment by LouiseEH** [comment]
Yes great, thanks
