### ISSUE TITLE
Security issue

### ISSUE THREAD

**Issue by pwntester** [dropwizard/dropwizard#3153]
What would be a secure email alias to report a security issue?

Note: would be a nice to set a [security policy](https://help.github.com/en/github/managing-security-vulnerabilities/adding-a-security-policy-to-your-repository)

**Comment by joschi** [comment]
@pwntester Thank you very much for raising this issue! 👍

We've added our security policy to this project:
https://github.com/dropwizard/dropwizard/security/policy

Please send your message to dropwizard.committers+security@gmail.com and we'll respond as fast as possible.

**Comment by pwntester** [comment]
Nice, thank you!
