### ISSUE TITLE
There is no way to shut down the JMXReporter created by Bootstrap

### ISSUE THREAD

**Issue by dteller** [dropwizard/dropwizard#3154]
https://github.com/dropwizard/dropwizard/blob/ce6348e8aa89bdc63314d7563fbc3062fbb2232c/dropwizard-core/src/main/java/io/dropwizard/setup/Bootstrap.java#L89

The JMXReporter returned on that line isn't saved so there is no way to clean it up.
That causes a memory leak when the application is restarted in the same JVM.

**Comment by mattnelson** [comment]
> That causes a memory leak when the application is restarted in the same JVM.

How are you restarting a dropwizard application without restarting the JVM?

**Comment by dteller** [comment]
We have another thread that stops and restarts the services. We are running a number of them in the same JVM.

**Comment by dteller** [comment]
The fact that the bootstrap JmxReporter is registered with the jmx bean means it can never be garbage collected nor can the metricsRegistry. That means the class loader can't be either.

**Comment by joschi** [comment]
@dteller Would the change in #3156 help you? That way you could call `JmxExporter#stop()` in your JVM process before reloading the application.

**Comment by dteller** [comment]
It absolutely would solve my problem. Thanks
