### ISSUE TITLE
javassist dependency not needed in dropwizard-validation

### ISSUE THREAD

**Issue by ljnelson** [dropwizard/dropwizard#3206]
Removing the `javassist` dependency from `dropwizard-validation/pom.xml` results in no errors.  Is there a reason that it is in there?

**Comment by joschi** [comment]
@ljnelson You are right, javassist isn't required in dropwizard-validation.

It is used in dropwizard-jersey and dropwizard-hibernate, though.

**Comment by joschi** [comment]
This issue has been resolved by #3202.
