### ISSUE TITLE
Asm version problem in 2.0.3 (dropwizard-dependencies BOM)

### ISSUE THREAD

**Issue by xvik** [dropwizard/dropwizard#3212]
This is **not a dropwizard issue**, but I'm sure many will face this with the new 2.0.3 release.

In my case, gradle build failed like this:

```
> Could not resolve all files for configuration ':pmd'.
   > Could not find org.ow2.asm:asm:${asm.version}.
     Required by:
         project : > net.sourceforge.pmd:pmd-java:6.21.0
```

This is hk2 issue: `dropwizard-dependencies` now (since 2.0.3) include [hk2-bom](https://github.com/eclipse-ee4j/glassfish-hk2/blob/master/bom/pom.xml), which does not declare `asm.version` property, but declares dependencies with it. 

HK2 related issue is: https://github.com/eclipse-ee4j/glassfish-hk2/issues/470

The workaround is obviously to declare `asm.version` to `7.2`.

In case of gradle, for spring dependency-management plugin it would look like:

```groovy
dependencyManagement {
    imports {
        mavenBom ("io.dropwizard:dropwizard-dependencies:2.0.3") {
            bomProperty 'asm.version', '7.2'
        }
    }
```

**Comment by joschi** [comment]
@xvik Thanks for reporting this issue!

It looks like a problem in the HK2 BOM itself. I've opened an issue in their issue tracker and we'll see how we can provide a fix on our side.

**Comment by joschi** [comment]
@xvik @izrobin @sherifzain Could you please verify that the problem has been resolved in Dropwizard 2.0.4 which we released today?

**Comment by xvik** [comment]
Back to normal. Thank you!

**Comment by sherifzain** [comment]
Much better now. Thanks for the quick fix 🙌
