### ISSUE TITLE
Slightly more memory is used for 2.0.x

### ISSUE THREAD

**Issue by karussell** [dropwizard/dropwizard#3257]
We've [recently upgraded from dropwizard 1.3.12 to 2.0.8](https://github.com/graphhopper/graphhopper/pull/1998) and observed that it uses 10-20MB more memory than before. I.e. our test were happy with "-Xmx100m" and now require at least "-Xmx110m" to avoid a frequent failure. It seems to be like a small thing, but when you just compare the "framework overhead" then this increase is substantial.

Is this expected? If not, I can try to create a reproducer with some hello world sample.

**Comment by joschi** [comment]
> Is this expected? If not, I can try to create a reproducer with some hello world sample.

The increased memory requirements are not expected.

We upgraded a lot of external libraries between Dropwizard 1.3.x and 2.0.x, so it wouldn't totally catch me by surprise if one of those requires more memory.

If you have the time to provide a reproducible analysis, you're welcome to do so. 😃

**Comment by karussell** [comment]
I cannot build the examples module. I checkout out `release/2.0.x` branch and ran `./mvnw clean package` but it always gives me something like

```
dropwizard-logging: Compilation failure
[ERROR] /home/peter/Documents/quell/examples/dropwizard/dropwizard-logging/src/test/java/io/dropwizard/logging/UdpSocketAppenderFactoryTest.java:[49,20] error: An unhandled exception was thrown by the Error Prone static analysis plugin.
[ERROR]      Please report this at https://github.com/google/error-prone/issues/new and include the following:
[ERROR]   
[ERROR]      error-prone version: 2.3.4
[ERROR]      BugPattern: Finally
[ERROR]      Stack Trace:
[ERROR]      java.lang.NoSuchFieldError: label
```

Do you have a minimal test repo instead?

**Comment by karussell** [comment]
Will try the archetype: https://github.com/dropwizard/dropwizard/tree/master/dropwizard-archetypes

**Comment by karussell** [comment]
Ok, cannot reproduce it with this. Both versions start fine with ~7mb and fail with ~6mb. (I had to make sure that I used jdk8 or the old default GC otherwise more was required)

So it is likely a problem of the updated dependencies.
