### ISSUE TITLE
Overlapping resources

### ISSUE THREAD

**Issue by henryeason** [dropwizard/dropwizard#3261]
Getting overlapping resource errors with Maven when using Dropwizard 2.0.8. I assume this is maybe a problem with Jersey and cannot be fixed easily.

**Warning from maven:**
[WARNING] jersey-common-2.30.1.jar, jersey-server-2.30.1.jar define 1 overlapping resources: 
[WARNING]   - META-INF/services/org.glassfish.jersey.internal.spi.AutoDiscoverable
[WARNING] jackson-databind-2.10.3.jar, jackson-dataformat-yaml-2.10.3.jar define 1 overlapping resources: 
[WARNING]   - META-INF/services/com.fasterxml.jackson.core.ObjectCodec
[WARNING] jdbi3-guava-3.12.2.jar, jdbi3-jodatime2-3.12.2.jar, jdbi3-sqlobject-3.12.2.jar define 1 overlapping resources: 
[WARNING]   - META-INF/services/org.jdbi.v3.core.spi.JdbiPlugin
[WARNING] jersey-bean-validation-2.30.1.jar, jersey-media-jaxb-2.30.1.jar, jersey-metainf-services-2.30.1.jar, jersey-server-2.30.1.jar define 1 overlapping resources: 
[WARNING]   - META-INF/services/org.glassfish.jersey.internal.spi.ForcedAutoDiscoverable
[WARNING] jersey-container-servlet-2.30.1.jar, logback-classic-1.2.3.jar define 1 overlapping resources: 
[WARNING]   - META-INF/services/javax.servlet.ServletContainerInitializer
[WARNING] jackson-datatype-guava-2.10.3.jar, jackson-datatype-jdk8-2.10.3.jar, jackson-datatype-joda-2.10.3.jar, jackson-datatype-jsr310-2.10.3.jar, jackson-module-afterburner-2.10.3.jar, jackson-module-jaxb-annotations-2.10.3.jar, jackson-module-parameter-names-2.10.3.jar define 1 overlapping resources: 
[WARNING]   - META-INF/services/com.fasterxml.jackson.databind.Module
[WARNING] dropwizard-core-2.0.8.jar, dropwizard-jetty-2.0.8.jar, dropwizard-logging-2.0.8.jar, dropwizard-metrics-2.0.8.jar, dropwizard-request-logging-2.0.8.jar define 1 overlapping resources: 
[WARNING]   - META-INF/services/io.dropwizard.jackson.Discoverable
[WARNING] jackson-core-2.10.3.jar, jackson-dataformat-yaml-2.10.3.jar define 1 overlapping resources: 
[WARNING]   - META-INF/services/com.fasterxml.jackson.core.JsonFactory
[WARNING] maven-shade-plugin has detected that some class files are
[WARNING] present in two or more JARs. When this happens, only one
[WARNING] single version of the class is copied to the uber jar.
[WARNING] Usually this is not harmful and you can skip these warnings,
[WARNING] otherwise try to manually exclude artifacts based on
[WARNING] mvn dependency:tree -Ddetail=true and the above output.
[WARNING] See http://maven.apache.org/plugins/maven-shade-plugin/

**Comment by joschi** [comment]
@henryeason You have to properly merge the files in `META-INF/services` with a suited resource transformer in the maven-shade-plugin:
https://maven.apache.org/plugins/maven-shade-plugin/examples/resource-transformers.html#ServicesResourceTransformer

**Comment by henryeason** [comment]
Thanks! Always forget to add this :+1:
