### ISSUE TITLE
Documentation: Task execute method has changed

### ISSUE THREAD

**Issue by barthanssens** [dropwizard/dropwizard#3277]
When upgrading from 1.3 to 2.0.9, I've noticed that the execute method signature has slightly changed to `execute(Map<String,List<String>> parameters, PrintWriter output)`, but this is not mentioned in the migration guide, nor in the manual https://www.dropwizard.io/en/latest/manual/core.html#tasks

**Comment by joschi** [comment]
@barthanssens Good catch, thanks a lot!
