### ISSUE TITLE
Objenesis question

### ISSUE THREAD

**Issue by lilaja** [dropwizard/dropwizard#3299]
Hi, Perhaps it is a stupid question - but why do you need this dependency ?
https://github.com/dropwizard/dropwizard/blob/c1a0af1c73be52f3a3c267e9deb7a0bd8e0c270c/dropwizard-dependencies/pom.xml#L62

**Comment by joschi** [comment]
@lilaja Good catch, thanks! 😃

The dependency is indeed unused.
