### ISSUE TITLE
ResourceExtension or ResourceTestRule both create null objects in Dropwizard 2.0.9

### ISSUE THREAD

**Issue by yongish** [dropwizard/dropwizard#3306]
Following the testing guide in https://www.dropwizard.io/en/latest/manual/testing.html#testing-resources. Using ResourceExtension or ResourceTestRule both create null objects. No such issues with Dropwizard 1.3.23.
```
    @Rule
    public final ResourceExtension resources = ResourceExtension.builder()
            .addResource(new HelloWorldResource(null, "Hello, %s!", "Stranger"))
            .build();
```
```
java.lang.NullPointerException
	at java.base/java.util.Objects.requireNonNull(Objects.java:221)
	at io.dropwizard.testing.common.Resource.getJerseyTest(Resource.java:184)
	at io.dropwizard.testing.common.Resource.target(Resource.java:164)
	at io.dropwizard.testing.junit5.ResourceExtension.target(ResourceExtension.java:65)
	at com.example.helloworld.resources.HelloWorldResourceTest.testGetPerson(HelloWorldResourceTest.java:18)
```

Uploaded example here.
https://github.com/yongish/resource_extension_null/blob/master/src/test/java/com/example/helloworld/resources/HelloWorldResourceTest.java#L12

**Comment by joschi** [comment]
@yongish You're trying to use the class rule (JUnit 4.x) with a JUnit 5.x test.
Please use the [`ResourceExtension`](https://javadoc.io/static/io.dropwizard/dropwizard-testing/2.0.9/io/dropwizard/testing/junit5/ResourceExtension.html) instead.

Example:
https://github.com/dropwizard/dropwizard/blob/655f8ac6f8586a8a0d49d217f0846deefb45de21/dropwizard-testing/src/test/java/io/dropwizard/testing/junit5/PersonResourceTest.java#L27-L47

This is unfortunately badly documented at the moment, so please provide your input in PR #3062. 😃
