### ISSUE TITLE
Logging Application Build Version during StartUp

### ISSUE THREAD

**Issue by fazeem84** [dropwizard/dropwizard#3313]
I would like to Log Build Version Number along with the Application Name during the server start up.
This can be done in two ways 
  1. By Reading Implementation-Version property from Manifest file
  2. By introducing new file in META-INF(for this to work build plugin needs to be introduced ) to store build info
@joschi I would like to know your thoughts on introducing this feature
I can work on this feature if everybody interested

**Comment by joschi** [comment]
I'm not convinced that this change should be in the core project as the information people usually want to log on startup is very specific to each project.

Maybe you want to log the commit and the branch from which the application was built and a unique identifier to the build in your CI. Maybe you want to log the Maven GAV coordinates.
