### ISSUE TITLE
Liquibase: CreateViewGenerator generates incorrect SQL for PostgreSQL

### ISSUE THREAD

**Issue by roryodonnell** [dropwizard/dropwizard#3346]
Migration from 1.3 to 2.0 exposes issue with view replacement. Not a dropwizard issue, but creating a placeholder to track and incorporate when fixed
https://github.com/liquibase/liquibase/issues/1042

**Comment by zUniQueX** [comment]
Seems like there is some progress now. Hopefully, this will get fixed soon.

**Comment by rhowe** [comment]
Liquibase fix merged last week. I assume that means it'll be in 4.19.0

**Comment by zUniQueX** [comment]
Liquibase 4.19 is released and includes the fix.
