### ISSUE TITLE
DW 1.3.25 fail with java.lang.NoClassDefFoundError: org/eclipse/jetty/io/ByteBufferOutputStream

### ISSUE THREAD

**Issue by vkravets** [dropwizard/dropwizard#3440]
Hi after last update of 1.3 my app fail to run. After small investigation I've found the dropwizard-bom don't use jetty bom https://github.com/eclipse/jetty.project/tree/jetty-9.4.x/jetty-bom which will store all versions which is needed for jetty related artifacts

I don't have chance to look at DW 2.0, so maybe the same issue exists there

**Comment by vkravets** [comment]
```xml
            <dependency>
                <groupId>org.eclipse.jetty</groupId>
                <artifactId>jetty-bom</artifactId>
                <version>${jetty.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
```

After it we can define all jetty dependencies without version like
```xml
            <!-- Jetty -->
            <dependency>
                <groupId>org.eclipse.jetty</groupId>
                <artifactId>jetty-server</artifactId>
            </dependency>
            <dependency>
                <groupId>org.eclipse.jetty</groupId>
                <artifactId>jetty-util</artifactId>
            </dependency>
            <dependency>
                <groupId>org.eclipse.jetty</groupId>
                <artifactId>jetty-webapp</artifactId>
            </dependency>
...
```

**Comment by pstackle** [comment]
The `jetty-bom` is used in the `dropwizard-dependencies` module which, starting in Dropwizard v2, takes over management of third party libraries from the `dropwizard-bom`
