### ISSUE TITLE
Spanner support - invalid properties passed through to Spanner JDBC driver

### ISSUE THREAD

**Issue by surfsoft** [dropwizard/dropwizard#3461]
I'm experimenting with an existing DropWizard application to see how easy it might be to configure it to use Google's Spanner database. I’m running against the Spanner emulator and when I start the application I get an error thrown by the Spanner JDBC driver as follows:

```
com.google.cloud.spanner.jdbc.JdbcSqlExceptionFactory$JdbcSqlExceptionImpl: INVALID_ARGUMENT: Invalid properties found in connection URI: password, hibernate.dialect, user
```

The Spanner JDBC driver doesn’t like the fact that these properties are being passed down to it and throws an exception. I've checked that the version of Hibernate used by DropWizard 2.0.6 is compatible with the Spanner JDBC library.

Rather than trying to detail the configuration of my application I thought I’d start by asking if Spanner is explicitly supported by DropWizard, and if there are any known issues regardless of if there is explicit support or not.

**Comment by joschi** [comment]
@surfsoft Thanks for reporting this!

> Rather than trying to detail the configuration of my application I thought I’d start by asking if Spanner is explicitly supported by DropWizard, and if there are any known issues regardless of if there is explicit support or not.

Spanner isn't explicitly supported by Dropwizard, but neither are PostgreSQL, MySQL, or any other specific database.
Dropwizard supports JDBC, though, and if there's a valid and working JDBC driver for Spanner, it should work with Dropwizard (or more precisely with `dropwizard-db`).

So please share some details about your application and how you're integrating Spanner, so that we can investigate whether we need to change something in Dropwizard or if there's a simple fix for your application.

**Comment by surfsoft** [comment]
I can't drop our production code, I'll put together a small project and upload to github that reproduces the issue I'm having and post a link to it in the next day or so. My specific issue is actually working via Hibernate and the official JDBC driver with the spanner emulator

**Comment by surfsoft** [comment]
[This repository](https://github.com/surfsoft/dropwizard-spanner-demo) has a minimalist DropWizard application that depends on the official Spanner JDBC driver and associated dialect.

There's a [second branch called H2](https://github.com/surfsoft/dropwizard-spanner-demo/tree/H2), which differs only in the dependencies (H2 instead of Spanner) and hibernate configuration.

The H2 version of the application starts up successfully. The Spanner version throws an exception - `com.google.cloud.spanner.jdbc.JdbcSqlExceptionFactory$JdbcSqlExceptionImpl: INVALID_ARGUMENT: Invalid properties found in connection URI` as described at the start of my original post

**Comment by surfsoft** [comment]
Throwing an exception is the expected behaviour for the Google Spanner JDBC driver - there's a discussion about that over in [the google cloud java project](https://github.com/googleapis/google-cloud-java/issues/6671)

**Comment by joschi** [comment]
Have you tried removing the offending properties from your configuration?

https://github.com/surfsoft/dropwizard-spanner-demo/blob/master/config/demo.yml#L3-L4
https://github.com/surfsoft/dropwizard-spanner-demo/blob/master/config/demo.yml#L15-L18

If you still want to override Hibernate settings, you can do so by sub-classing `SessionFactoryFactory` and passing it to `HibernateBundle`.

https://github.com/dropwizard/dropwizard/blob/v2.0.13/dropwizard-hibernate/src/main/java/io/dropwizard/hibernate/SessionFactoryFactory.java#L105-L106
https://github.com/dropwizard/dropwizard/blob/v2.0.13/dropwizard-hibernate/src/main/java/io/dropwizard/hibernate/HibernateBundle.java#L41-L45

**Comment by surfsoft** [comment]
Most of these properties can't be removed. I'll look at your alternative suggestion. Having to create a subclass of `SessionFactoryFactory` to get it working with Spanner was not something I had in mind to be honest. It's internal of DropWizard.

At this stage does this classify as a defect ("doesn't work out of the box with Spanner") or a feature request ("please support Spanner without the need for a work-around")?

**Comment by joschi** [comment]
> Most of these properties can't be removed.

You can set the Hibernate-specific properties in a `hibernate.properties` file as described at [Legacy Bootstrapping](https://docs.jboss.org/hibernate/stable/orm/userguide/html_single/Hibernate_User_Guide.html#appendix-legacy-bootstrap).


> At this stage does this classify as a defect ("doesn't work out of the box with Spanner") or a feature request ("please support Spanner without the need for a work-around")?

It's the decision of the developers of the Spanner JDBC driver (googleapis/google-cloud-java#6671) to fail on unknown properties which makes using Spanner harder than MySQL, PostgreSQL, or multiple other databases.

We can classify this as a bug, but unless you're willing to provide a fix yourself, I'm not sure if Dropwizard will change its behavior in `dropwizard-db` and `dropwizard-hibernate` anytime soon.

**Comment by pstackle** [comment]
To add a bit, from a quick scan of the [JDBC spec](https://jcp.org/aboutJava/communityprocess/mrel/jsr221/index3.html), it refers to a set of "Standard Data Source Properties" (section 9.6.1) which includes `user` and `password`. It goes on to say:
> DataSource implementations may augment this set with implementation-specific properties.

I interpret that as meaning that the Spanner JDBC driver should at least support `user` and `password` properties being set.
