### ISSUE TITLE
Remove deprecated "optimize" compiler flag

### ISSUE THREAD

**Issue by matthias-mueller** [dropwizard/dropwizard#3466]
I just got distracted by a compiler flag in the parent pom, so I thought I'd file an issue here.

"optimize" is a deprecated compiler flag - [see here](https://maven.apache.org/plugins/maven-compiler-plugin/compile-mojo.html#optimize).

... but it is still used in the parent POM:
* https://github.com/dropwizard/dropwizard/blob/master/dropwizard-parent/pom.xml#L25
* https://github.com/dropwizard/dropwizard/blob/master/dropwizard-parent/pom.xml#L87

**Comment by joschi** [comment]
@matthias-mueller Would you be able to create a pull request for the removal of this maven-compiler-plugin setting? 😃
