### ISSUE TITLE
logFormat configuration inconveniences

### ISSUE THREAD

**Issue by cleiner** [dropwizard/dropwizard#3481]
There are two non-obvious limitations in the appender configuration:

1) When using the **layout** option to set a custom `LayoutFactory`, the **logFormat** is always ignored. I think it would be more consistent to apply the **logFormat** to all layouts that derive from `PatternLayoutBase` and otherwise emit a warning if both options are set. That is, changing `AbstractAppenderFactory.buildLayout()` to something like

```java
        if (layout == null) {
            layoutBase = defaultLayoutFactory.build(context, timeZone);
        } else {
            layoutBase = layout.build(context, timeZone);
        }
        if (!Strings.isNullOrEmpty(logFormat)) {
            if (layoutBase instanceof PatternLayoutBase) {
                ((PatternLayoutBase<E>)layoutBase).setPattern(logFormat);
            } else {
                LOGGER.warn("Ignoring 'logFormat', because 'layout' does not extend PatternLayoutBase");
            }
        }
```

2) When setting a **logFormat** that includes time zone information (like the default `LogbackAccessRequestLayout`), the time zone is a fixed part of the string and may contradict the configured **timeZone** option. Maybe the **logFormat** could contain some kind of placeholder (e.g. `<timeZone>`) that gets automatically replaced with the correct value from the **timeZone** option?

**Comment by alishahusain** [comment]
I'm a first-time contributor to this repository and would like to take on this issue. For #2, should I use a hardcoded String replace or use a specific library? Thanks!
