### ISSUE TITLE
DropwizardSupport with customised jackson support

### ISSUE THREAD

**Issue by nheitz** [dropwizard/dropwizard#3501]
I've stumbled across a problem that is extremely difficult to reproduce in simple code.  

Quite simply, if a dropwizard server is bootstrapped for a unit test via DropwizardSupport, no matter what modules are registered in client or server code, java.time.Instant is not serialized properly.  Instead of printing either epoch time, or ISO date format, jackson/jersey are serializing   like this:
````
      "featureTime": {
            "epochSecond": 1602516947,
            "nano": 202000000
        }
````

This does not get read properly then by a client using the same bean definition.

THe same code works perfectly when running as a standalone server.  Something about running in DropwizardSupport is messing up customised serialization.

Dropwizard 2.0.13
Jackson 2.10.5
Java 8

**Comment by joschi** [comment]
> if a dropwizard server is bootstrapped for a unit test via DropwizardSupport

Do you mean [`DropwizardTestSupport`](https://github.com/dropwizard/dropwizard/blob/v2.0.13/dropwizard-testing/src/main/java/io/dropwizard/testing/DropwizardTestSupport.java)?

**Comment by nheitz** [comment]
Apologies....I do indeed mean DropwizardTestSupport.

Further attempts to investigate suggest that jackson, while still doing the serialisation, no longer finds registered modules, and so falls back to the least common denominator.

**Comment by joschi** [comment]
> Quite simply, if a dropwizard server is bootstrapped for a unit test via DropwizardSupport

@nheitz Could you please elaborate on what you're doing exactly? Maybe share your test code.

**Comment by nheitz** [comment]
I'm going to have to close this.  I can't reproduce on a a simpler application setup, so I must deduce that it is some kind of dependency collision.
