### ISSUE TITLE
NPE in AnnotationSensitivePropertyNamingStrategy.nameForField

### ISSUE THREAD

**Issue by arpit-pp** [dropwizard/dropwizard#3514]
Guava's RangeHelper calls AnnotationSensitivePropertyNamingStrategy.nameForField with null value of AnnotatedField which is causing NPE.
Should dropwizard have null check before accessing AnnotatedField's methods?

https://github.com/FasterXML/jackson-datatypes-collections/issues/79

**Comment by joschi** [comment]
@arpit-pp Thanks for reporting this!
