### ISSUE TITLE
Dropwizard SonarQube properties inherited 

### ISSUE THREAD

**Issue by enda-odonohoe** [dropwizard/dropwizard#3531]
We are using 

<parent>
  <groupId>io.dropwizard</groupId>
  <artifactId>dropwizard-dependencies</artifactId>
  <version>2.0.14</version>
</parent>

as specified here: https://www.dropwizard.io/en/latest/manual/upgrade-notes/upgrade-notes-2_0_x.html

The recent changes for https://github.com/dropwizard/dropwizard/pull/3493 have broken our SonarQube Jenkins pipeline the properties specified for sonarqube are getting used in our project.

[INFO] Project key: dropwizard_dropwizard
[INFO] Base dir: /var/lib/jenkins/tmp/workspace/DEV
[INFO] Working dir: /var/lib/jenkins/tmp/workspace/DEV/target/sonar
[INFO] Load project settings for component key: 'dropwizard_dropwizard'
...
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  05:29 min
[INFO] Finished at: 2020-10-27T22:02:00Z
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.sonarsource.scanner.maven:sonar-maven-plugin:3.2:sonar (default-cli) on project xxx: Failed to load the default quality profiles: No organization with key 'dropwizard' ->

**Comment by enda-odonohoe** [comment]
FYI: My workaround was to specify the following properties:

		<sonar.projectKey>xxx</sonar.projectKey>
		<sonar.organization>default-organization</sonar.organization>
		<sonar.host.url>https://xxx/sonarqube</sonar.host.url>
		<sonar.moduleKey>${project.groupId}:${project.artifactId}</sonar.moduleKey>

**Comment by joschi** [comment]
@enda-odonohoe Thanks for reporting this!

> io.dropwizard dropwizard-dependencies 2.0.14
> as specified here: dropwizard.io/en/latest/manual/upgrade-notes/upgrade-notes-2_0_x.html

Suggesting to use `dropwizard-dependencies` as a Parent POM probably wasn't one of my smartest ideas. 😅 

I'll see if we can move the SonarQube properties further down the module hierarchy so that they won't be inherited when using `dropwizard-dependencies` as Parent POM.

**Comment by enda-odonohoe** [comment]
It simplified the project files quite a bit using it as a parent pom.  We use some jetty libs that for websockets that we had to bump the rev every time we changed the dropwizard version, now it keeps in sync.

**Comment by joschi** [comment]
@enda-odonohoe Would you please check if the linked PR would reasonably solve your issue with the SonarQube properties?

Unfortunately I didn't find a way to remove `sonar.moduleKey` from the actual POM file.

**Comment by enda-odonohoe** [comment]
@joschi I looked at the effective pom with that branch and everything looks good.  Thanks!
