### ISSUE TITLE
Automatically include file argument (or add documentation) on ConfiguredCommand

### ISSUE THREAD

**Issue by pablo-silverback** [dropwizard/dropwizard#3669]
`ConfiguredCommand` does not include the configuration file argument automatically but makes you call `addFileArgument` on bootstrap.

Failing to call this method your command will complain that you're passing a file argument and none is expected.

This is not documented anywhere:

<img width="771" alt="Screen Shot 2021-01-26 at 14 33 47" src="https://user-images.githubusercontent.com/77513079/105881638-847e0b80-5fe3-11eb-919d-1135d59662d4.png">

It would be a good idea to either:

- automatically accept the file argument (this is what the docs say, btw)

<img width="1028" alt="Screen Shot 2021-01-26 at 14 37 38" src="https://user-images.githubusercontent.com/77513079/105882166-1ab23180-5fe4-11eb-86ed-f54e1ee47797.png">

- document that the call to `addFileArgument` is needed.

**Comment by joschi** [comment]
@pablo-silverback Do you mean this?
https://github.com/dropwizard/dropwizard/blob/7385a7d7a3a1f0670d5fda376b8cdf516d7c7b30/dropwizard-core/src/main/java/io/dropwizard/cli/ConfiguredCommand.java#L47-L68

That's also how the `check` command (`CheckCommand` class) works:
https://github.com/dropwizard/dropwizard/blob/v2.0.18/dropwizard-core/src/main/java/io/dropwizard/cli/CheckCommand.java

**Comment by pablo-silverback** [comment]
@joschi Exactly that. I believe it should be called always after the `configure` method, or the docs should read something like:

> by default Dropwizard will treat the last argument as the path to the YAML __unless you override the `configure` method. In that case you should call addFileArgument yourself__

With the not so crazy hypothesis that most people will override the `configure` method, the docs are misleading (they sure mislead me)

**Comment by joschi** [comment]
@pablo-silverback I would expect people to call the parent's method if they're overriding a method, i. e. call `super(subparser)` if they're overriding the `configure(Subparser)` method.

If you don't call `super`, you're basically saying that you're not interested in inheriting the behavior of the parent class.

**Comment by pablo-silverback** [comment]
I believe we can agree it doesn't make sense to have a `ConfiguredCommand` without a configuration file. 

Right now not only this is __possible__ (which I personally think it's a bug that needs fixing) but it's also _very likely_ to do it by mistake, if you forget to call `super` or call `addFileArgument` yourself.

> If you don't call super, you're basically saying that you're not interested in inheriting the behavior of the parent class.

This assumes knowledge of what the superclass do. There's not a single case (at least on the docs) on the Dropwizard library where you need to call super in overridden methods (e.g. Application, Configuration, Healthchecks, etc.). They just work. ConfiguredCommand doesn't, and it's not even documented.

**Comment by joschi** [comment]
> ConfiguredCommand doesn't, and it's not even documented.

@pablo-silverback It's right in the documentation: https://www.dropwizard.io/en/release-2.0.x/manual/core.html#configured-commands

<img width="946" alt="Excerpt of the documentation for ConfiguredCommand" src="https://user-images.githubusercontent.com/43951/106246901-20d82600-620f-11eb-9331-407f7100e035.png">

**Comment by pablo-silverback** [comment]
I stand by my opinion that it is a bug to have a `ConfiguredCommand` with no configuration file and that it's easy to miss the super call, since it's the only class in the whole package that requires you to call `super` on override.

When I say it's not documented I mean that the fact that avoiding the `super` call will result in your command not working at all is not explicit.

**Comment by joschi** [comment]
@pablo-silverback Would you create a pull request to change `ConfiguredCommand` or the documentation accordingly?

**Comment by pablo-silverback** [comment]
Sure, I can do that. You think changing the code to avoid the super call is out of the question?

**Comment by joschi** [comment]
> You think changing the code to avoid the super call is out of the question?

At least for Dropwizard 2.0.x, I wouldn't want to change it.

It's fine for Dropwizard 2.1.x if it doesn't involve too many changes.

 Maybe introduce a `doConfigure(Subparser)` method which will add the file argument and then calls `configure(Subparser)`?

**Comment by fernandezpablo85** [comment]
@joschi do you think we can improve this by throwing an exception here? Seems like the condition is being checked but the command run continues:

https://github.com/dropwizard/dropwizard/blob/master/dropwizard-core/src/main/java/io/dropwizard/cli/ConfiguredCommand.java#L136

I believe dropwizard should exit with an exception if "file" argument is null there.

**Comment by joschi** [comment]
> I believe dropwizard should exit with an exception if "file" argument is null there.

Who says that a `ConfiguredCommand` has to get its configuration from a file?

**Comment by pablo-silverback** [comment]
From where else could it get the configuration? Isn't the purpose of ConfiguredCommand to read a configuration file?
