### ISSUE TITLE
Syslog appender intermittently losing messages from a Dropwizard command

### ISSUE THREAD

**Issue by TimothyMDean** [dropwizard/dropwizard#3685]
I have two different DropWizard components, currently using DW 2.0.16. One component is a fairly typical HTTP service. The other is just a CLI application, implementing a handful of DW commands. Both are configured to use the syslog appender to send certain messages to an Rsyslog service (running in CentOS 8.2)

The messages generated from the HTTP service are all arriving at the Rsyslog service as expected, and getting handled correctly. But the messages generated from the CLI commands are intermittently not arriving. Sometimes about half of them arrive and get logged, sometimes less than that.

My guess is that DropWizard's use of an async appender is causing the log messages to be queued for a worker thread to eventually pick up, but that thread is failing to pick up all the messages because the command completes and exits quickly. But that is just a theory that is consistent with the limited data I have.

Looking for ideas to find out of this is a DropWizard bug, or a misconfiguration on my part. And most importantly, I am eager to find a workaround.

**Comment by TimothyMDean** [comment]
Additional note - In order to prove to myself that this was not a case of UDP packets getting lost, I used `tcpdump` to monitor the UDP traffic on my node. As I suspected, the cases where syslog messages were missing showed no UDP traffic hitting the network layer. 

So this really looks to be something happening on the Java side, either in Dropwizard or the underlying Logback implementation.

**Comment by TimothyMDean** [comment]
As a workaround, I have found that adding this to my command code before exiting seems to fix things up:

```
LoggingUtil.getLoggerContext().stop();
```

**Comment by zUniQueX** [comment]
If it's something related to #3677, we probably should reset all appenders before exiting. Therefore we could extend `ConfiguredBundle.cleanup()` to call the `reset()` method of the `LoggingFactory`.

**Comment by zUniQueX** [comment]
Actually `DefaultLoggingFactory.reset()` seems to do too much. Therefore manually stopping the logger context and appenders should be faster on command cleanup.

**Comment by zUniQueX** [comment]
> As a workaround, I have found that adding this to my command code before exiting seems to fix things up:
> 
> ```
> LoggingUtil.getLoggerContext().stop();
> ```

After revisiting this, I think this should be done manually. Users are permitted to use logging throughout the whole application, i.e. they can override `Application#onFatalError` and use a logger in it. Therefore we can't generally stop the `LoggerContext` at any point in the framework.

However, we could improve the handling on asynchronous cleanup in a `ConfiguredCommand` and explicitly flush all appenders, if a configuration is provided. See #5094

**Comment by zUniQueX** [comment]
@TimothyMDean Could you please verify, if the problem persists? As we have another appender flush on application shutdown, this may be enough to get your logs. Then you don't have to disable logging completely.

**Comment by TimothyMDean** [comment]
@zUniQueX Unfortunately I can no longer verify this. I have changed employers since reporting the issue, and I no longer have access to the source code.

**Comment by zUniQueX** [comment]
@TimothyMDean Thanks for the fast reply. I'll then close this for now.
