### ISSUE TITLE
CachingAuthorizer cannot rely on ContainerRequestContext as is

### ISSUE THREAD

**Issue by cyberdelia** [dropwizard/dropwizard#3714]
`CachingAuthorizer` currently rely on `ContainerRequestContext` `hashCode`/`equals` implementation which are the default `Object` implementations, defeating the purpose of the cache entirely.

The best option might be for `CachingAuthorizer` to provide a way to provide a custom `AuthorizationContext` of some sort.

**Comment by cyberdelia** [comment]
I'm happy to give this a shot, I'm welcome alternative options in the meantime.

**Comment by joschi** [comment]
> `CachingAuthorizer` currently rely on `ContainerRequestContext` `hashCode`/`equals` implementation which are the default `Object` implementations, defeating the purpose of the cache entirely.

The purpose of `CachingAuthorizer` is caching the authorization result within one request.

Any `Authorizer` implementation could use any attribute of `ContainerRequestContext` to decide whether a specific request/subject should be authorized or not, so caching over multiple requests might lead to wrong authorization results.

**Comment by cyberdelia** [comment]
Exactly, but if each `Authorizer` could have a method to provide something like an `AuthorizationContext` that contains the specific values used by it to authorize the request based on a given `ContainerRequestContext`. We could be able to safely cache across multiple similar requests.
