### ISSUE TITLE
The dropwizard-dependencies bom has declared some dependencies with scope

### ISSUE THREAD

**Issue by nicholas-s-perkins** [dropwizard/dropwizard#3769]
Hello Dropwizard folks.

When importing the dropwizard-dependencies BOM, we noticed two dependencies in the BOM have a declared scope of `runtime`:
- `jakarta.activation-api`
    - https://github.com/dropwizard/dropwizard/blob/master/dropwizard-dependencies/pom.xml#L165
- `jakarta.xml.bind-api`
    - https://github.com/dropwizard/dropwizard/blob/master/dropwizard-dependencies/pom.xml#L176

Usually with published BOMs like this you don't want to include scope since it will override the scope of transitive dependencies of projects that import the BOM and that can have confusing side effects.

Is this something that could be changed?

We have to currently explicitly override this for our apps to use the dropwizard-dependencies BOM because otherwise it breaks a few of our imported libraries that have one of these two dependencies.

Thanks!

**Comment by joschi** [comment]
@nicholas-s-perkins Thanks for reporting this!

You're absolutely right, the `dropwizard-dependencies` BOM shouldn't force specific dependency scopes on its consumers.

We'll change that with Dropwizard 2.1.0 so that users of Dropwizard 2.0.x won't get surprised by the sudden change.

> We have to currently explicitly override this for our apps to use the dropwizard-dependencies BOM because otherwise it breaks a few of our imported libraries that have one of these two dependencies.

Out of curiosity, which dependency scopes are you using for `jakarta.activation:jakarta.activation-api` and `jakarta.xml.bind:jakarta.xml.bind-api` in your projects?

**Comment by nicholas-s-perkins** [comment]
I appreciate the quick response!

> Out of curiosity, which dependency scopes are you using for jakarta.activation:jakarta.activation-api and jakarta.xml.bind:jakarta.xml.bind-api in your projects?

@joschi We just declared the dependencies it in the DependencyManagement block like this without the scope, and that seems to provide the behavior we wanted.
```xml
<dependencyManagement>
    <dependencies>
        <dependency>
            <groupId>io.dropwizard</groupId>
            <artifactId>dropwizard-dependencies</artifactId>
            <version>${dropwizard.version}</version>
            <scope>import</scope>
            <type>pom</type>
        </dependency>
        <!-- BOM FIXES -->
        <dependency>
            <groupId>jakarta.xml.bind</groupId>
            <artifactId>jakarta.xml.bind-api</artifactId>
            <version>${jakarta.xml.bind-api.version}</version>
        </dependency>
        <dependency>
            <groupId>jakarta.activation</groupId>
            <artifactId>jakarta.activation-api</artifactId>
            <version>${jakarta.activation-api.version}</version>
        </dependency>
    </dependencies>
</dependencyManagement>
```

We have a few imports that use the libs.  For example we do some xml/SOAP stuff and use some xml annotations with jackson so we expected it to be `compile` scope:
```
[INFO] +- com.fasterxml.jackson.jaxrs:jackson-jaxrs-json-provider:jar:2.10.5:compile
[INFO] |  +- com.fasterxml.jackson.jaxrs:jackson-jaxrs-base:jar:2.10.5:compile
[INFO] |  \- com.fasterxml.jackson.module:jackson-module-jaxb-annotations:jar:2.10.5:compile
[INFO] |     +- jakarta.xml.bind:jakarta.xml.bind-api:jar:2.3.2:compile
[INFO] |     \- jakarta.activation:jakarta.activation-api:jar:1.2.1:compile
```
