### ISSUE TITLE
Improve documentation for `useForwardedHeaders` setting.

### ISSUE THREAD

**Issue by joschi** [dropwizard/dropwizard#3783]
Dropwizard 2.0.x introduced the `useForwardedHeaders` setting for the HTTP connector:
https://www.dropwizard.io/en/release-2.0.x/manual/configuration.html#http

This has caused some confusion in the past when people were using their Dropwizard applications behind a proxy which terminated SSL/TLS connections.

The introduction of this setting should be added to the Dropwizard 2.0.x upgrade guide.

References:

- https://github.com/dropwizard/dropwizard/issues/2663
- https://github.com/dropwizard/dropwizard/pull/2748
- https://github.com/dropwizard/dropwizard/issues/3023
- https://github.com/dropwizard/dropwizard/issues/3782
- https://www.javadoc.io/doc/org.eclipse.jetty/jetty-server/9.4.38.v20210224/org/eclipse/jetty/server/ForwardedRequestCustomizer.html

**Comment by zUniQueX** [comment]
@joschi is this still needed? It would be good to have up-to-date and clear docs, but I wonder, if we should now modify the migration guide for 2.0.x as this is out for over 2 years and we are not far away from releasing 2.1.0.
