### ISSUE TITLE
Upgrade httpclient version 4.5.13 to httpclient5 version 5.0.3 to fix WS-2019-0379

### ISSUE THREAD

**Issue by sagarkal** [dropwizard/dropwizard#3851]
Hi,

Dropwizard depends on Apache httpclient version 4.5.13. But Apache is no longer releasing any new versions of httpclient. Instead they are now maintaining [httpclient5](https://mvnrepository.com/artifact/org.apache.httpcomponents.client5/httpclient5) whose latest version (at the time of this writing) 5.0.3 depends on version 1.13 of commons-codec that contains the fix for the security issue WS-2019-0379.
Could Dropwizard please move to httpclient5 version 5.0.3 (or higher) in its next minor version release?

**Comment by joschi** [comment]
I think you're referring to https://www.whitesourcesoftware.com/vulnerability-database/WS-2019-0379.

>  Could Dropwizard please move to httpclient5 version 5.0.3 (or higher) in its next minor version release?

No, that's not possible. Neither Jersey Connectors for Apache HttpClient version 2.33 nor version 3.0.x supports Apache HttpClient 5.x.

- https://mvnrepository.com/artifact/org.glassfish.jersey.connectors/jersey-apache-connector/2.33
- https://mvnrepository.com/artifact/org.glassfish.jersey.connectors/jersey-apache-connector/3.0.1
- https://eclipse-ee4j.github.io/jersey.github.io/documentation/2.33/user-guide.html#d0e4973

What we can do, though, is force a newer version of Apache Commons Codec into Dropwizard's dependency tree.

**Comment by joschi** [comment]
I've also created a ticket at the Apache HttpClient JIRA: https://issues.apache.org/jira/browse/HTTPCLIENT-2150

**Comment by sagarkal** [comment]
Hi @joschi thanks for taking care of this, sorry for the delayed response. I had disabled all Github notifications by mistake
