### ISSUE TITLE
ContextRoutingHandler doesn't implement expandChildren

### ISSUE THREAD

**Issue by yoshuaNahar** [dropwizard/dropwizard#3873]
After implementing Jetty's Session Management, I noticed that the DefaultSessionIdManager isn't scavenging sessions. The HouseKeeper is running, but apparently the SessionHandler isn't found.

De debug log only shows these:
```
2021-04-13 11:50:26,881 INFO  [main]  o.e.j.s.session: node0 Scavenging every 11000ms
2021-04-13 11:50:37,888 DEBUG [Session-HouseKeeper-4ab9d160-1]  o.e.j.s.session: node0 scavenging sessions
2021-04-13 11:50:48,904 DEBUG [Session-HouseKeeper-4ab9d160-1]  o.e.j.s.session: node0 scavenging sessions
```

In DefaultSessionIdManager, the server can't find the SessionHandler.
```
public Set<SessionHandler> getSessionHandlers()
{
    Set<SessionHandler> handlers = new HashSet<>();
    Handler[] tmp = _server.getChildHandlersByClass(SessionHandler.class); // <-- returns an empty array
    ...
```

The `getChildHandlersByClass` checks the Handler and eventually ends up at the `ContextRoutingHandler`. This class extends `AbstractHandlerContainer` but doesn't override `expandChildren` so Jetty can't continue looking for the SessionHandler.

_This is primarily an issue for scavenging the sessions from my `JDBCSessionDataStore`. Setting the SessionCache eviction policy to `EVICT_ON_INACTIVITY` will remove the sessions from the Cache, but that solves half the problem._

The solution would probably be to change the class to extend from `HandlerCollection` or to just override the `expandChildren` method.

My DW version is: 2.0.18, and using SimpleServerFactory.

**Comment by joschi** [comment]
@yoshuaNahar Thanks for reporting this!

We'll fix the issue in the next version of Dropwizard 2.0.x by implementing `expandChildren()` in `ContextRoutingHandler`.

**Comment by rhowe** [comment]
For anyone doing archaeology in future, this looks related to an earlier report: https://github.com/dropwizard/dropwizard/issues/2455
