### ISSUE TITLE
Add configuration for AdminServlet capabilities

### ISSUE THREAD

**Issue by mschechter-bellese** [dropwizard/dropwizard#3876]
The `AdminServlet` provides a number of features/functions, including thread dumps and CPU profiling. The latter two have the potential to create a denial-of-service attack on a server if a malicious actor were able to access those endpoints somehow. It's theoretically possible even if the endpoints are not exposed externally.

It would be great to be able to disable the various operational endpoints dynamically based on configuration. That would allow developers to leave the functionality on in non-production environments for diagnostic purposes, and reduce the exposed API for production to limit vulnerability.

An example of this type of configuration can be seen in the [Spring Boot Actuator](https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#production-ready-endpoints), which allows each provided endpoint to be controlled independently.

Thanks in advance!

**Comment by joschi** [comment]
@mschechter-bellese This is a very sensible idea. Would you be able to provide a pull request with an initial implementation for this?

Keep in mind that the `AdminServlet` is coming into Dropwizard via Dropwizard Metrics, so you have to adapt both projects.
https://github.com/dropwizard/metrics/blob/release/4.1.x/metrics-servlets/src/main/java/com/codahale/metrics/servlets/AdminServlet.java

**Comment by mschechter-bellese** [comment]
@joschi - I will see what I can do.

Could you please let me know if there is any documentation or examples of similar patterns in Dropwizard that I can use for this type of functionality? That will help minimize cycle time once there's a pull request to review.

Thanks!

**Comment by mschechter-bellese** [comment]
@joschi,

There's a [pull request](https://github.com/dropwizard/metrics/pull/1891) for the `AdminServlet` changes ready to go. Could you please take a look at that when you get a chance and let me know if it's going in the right direction?

Thanks!

**Comment by mschechter-bellese** [comment]
@joschi, 

Could you please let me know what configuration example patterns you'd like me to follow when I implement this? There are a lot of options available now, and I'd like to create something that cleanly integrates with the rest of Dropwizard.

Thanks!

**Comment by mschechter-bellese** [comment]
@joschi / @arteam,

I've done some digging into this, and think I have a solution. Unfortunately, the best way I can find to do it would be a breaking change in `AbstractServerFactory`.

In `Environment`, an instance of `AdminEnvironment` is currently created; this is only used in one place in the production code that I can find. However, it has all the Dropwizard-specific content needed to build the `AdminServlet` using the current code. It also contains an `AdminFactory` instance created from the externalized YAML configuration.

I think the best place to read in the configuration options for the `AdminServlet` is via the `AdminFactory`, and adding options there is safe as long as reasonable defaults are provided (or `null`/missing values are handled well in `AbstractServerFactory`).

## Proposed Solutions

It looks like there are two ways to achieve this:

1. Modify the signature of `createAdminServlet` to `createAdminServlet(Server, AdminEnvironment)`
2. Add a protected variable of type `AdminEnvironment` in `AbstractServerFactory` that can be injected, and then reference it in `createAdminServlet` to get the additional information

I'd much prefer the first path, as it's much cleaner and simplifies future expansion. I can understand why the second option would be preferable (at least in the short term) to avoid breaking changes.

Could you please let me know if you have a preference as to which path to take?

Thanks!

**Comment by mschechter-bellese** [comment]
I've found a simpler way to deal with the configuration without introducing any backwards-compatibility issues. Could you please take a look at the new pull request and let me know if you see any issues?

**Comment by mschechter-bellese** [comment]
@joschi / @arteam,

Could you please let me know when you might be able to get to the [pull request](#4007)? I'd like to be able to address any issues you find.

Thanks!
