### ISSUE TITLE
Configurable applicationContextPath for DropwizardClient

### ISSUE THREAD

**Issue by a5huh** [dropwizard/dropwizard#3891]
[DropwizardClient](https://github.com/dropwizard/dropwizard/blob/master/dropwizard-testing/src/main/java/io/dropwizard/testing/common/DropwizardClient.java#L29) forces the application context path to be `/application`

It will be helpful if this can be configurable.

**Comment by joschi** [comment]
@a5huh Could you please describe your use case for the configurable base URI in `DropwizardClient`?

`DropwizardClient` is starting a Dropwizard `Application` with a [`simple` server connector](https://www.dropwizard.io/en/release-2.0.x/manual/configuration.html#simple) which provides the configured JAX-RS resources under the `/application` path prefix.

Maybe you're looking for the [`dropwizard-client`](https://www.dropwizard.io/en/release-2.0.x/manual/client.html) package instead?

**Comment by a5huh** [comment]
Let's say you have have a class `A` and it uses class `B` to perform all the http calls. Let's say that you can only provide a host name/ip and port number to class `B`. It makes it impossible to use `DropwizardClient` for testing due to the forced application context.

The scenario above is what I have to work with due to our service discovery, which returns hostname and ports only.

**Comment by joschi** [comment]
@a5huh Unfortunately I cannot follow.

`io.dropwizard.testing.common.DropwizardClient` is explicitly only meant to test JAX-RS resources and is not an HTTP client at all. The naming could definitely be improved. 😉 

Could you elaborate on your use case with a more specific example or at least describe what classes `A` and `B` are and what they're doing?
