### ISSUE TITLE
Drop Wizard v2.0.21 has issues with SSL buffering

### ISSUE THREAD

**Issue by ireneWork** [dropwizard/dropwizard#3983]
We are seeing issues with DW v2.0.21 when the server is set up as https.

To reproduce the issue:

1) Create a simple `TestResource.java`

```java
@Path("/test")
public final class TestResource {
 
    @POST
    @Path("/text/sleep/{time}")
    @Consumes(MediaType.TEXT_PLAIN)
    @Produces(MediaType.APPLICATION_JSON)
 
    public Response textData(@NotNull @PathParam("time") long time, @NotNull String data) {
        try {
            Thread.sleep(time * 1000);
        } catch (InterruptedException e) {
            return Response.serverError().build();
        }
        return Response.ok().build();
    }
}
```
2) Create a DW Application that registers the above resource and runs as **https** simple server
3) Run the application
4) Sample file of different sizes for the curl command can be created using (sample ~10MB): base64 /dev/urandom | head -c 10000000 > file.txt
5) curl command: `for i in {1..10}; do curl -k -v -X POST -H 'Expect:' -H "Content-Type: text/plain" -d @file.txt "  "https://hostname:port/path_to_resource/test/text/sleep/3"; done`

**v2.0.21:**

```
> Content-Type: text/plain
> Content-Length: 9870130
>
* SSL write: error -5961 (PR_CONNECT_RESET_ERROR)
* TCP connection reset by peer
* Closing connection 0
curl: (55) TCP connection reset by peer
```

**V2.0.20:**

Doesn't have issues

A bug with SSL buffering was introduced in Jetty 9.4.39 and this is a version that DW uses in 2.0.21

https://github.com/eclipse/jetty.project/issues/6152#issuecomment-817134632

As per above link It's supposed to be fixed  in Jetty 9.4.40.v20210413. So it may be the cause for that issue

**Comment by joschi** [comment]
Closed via https://github.com/dropwizard/dropwizard/pull/3976.
