### ISSUE TITLE
Allow for command-line overrides of configuration parameters

### ISSUE THREAD

**Issue by codahale** [dropwizard/dropwizard#40]
As @bradhouse said on the mailing list:

> I reguarly launch services with Foreman and usually launch multiple instances at the same time. Each instance needs a different port.
> 
> A more serious issue is if you want to run a DW service on something like Heroku. You must bind on the port they define via the $PORT environment variable. If you cannot pass this on the CLI you cannot run on their service. System.getenv("PORT") also works, but there are no bind points in DW to alter a Configuration instance prior to Jetty start. Not surprising as the DW approach strongly favours immutable configuration.

**Comment by tahaiqbalkhan9** [comment]
But calling with argument `-Ddw.server.connector.port=$PORT` throws error `* Incorrect type of value at: server.connector.port; is of type: String, expected: int`. 
I mean how can I do type safety check while providing environment variable ?
