### ISSUE TITLE
Http/2 with TLSv1.3

### ISSUE THREAD

**Issue by HaiderRazvi** [dropwizard/dropwizard#4066]
The following line of code prohibits the ability to use TLSv1.3 with H2 connectors. If you agree, can this please be fixed? Thank you.

https://github.com/dropwizard/dropwizard/blob/33d0dd89f6330f06fc81a29fa058fc70fd9d9f7d/dropwizard-http2/src/main/java/io/dropwizard/http2/Http2ConnectorFactory.java#L94

**Comment by joschi** [comment]
@HaiderRazvi Thanks for reporting this!

A fix will be available in the next version of Dropwizard 2.0.x. 😄

**Comment by HaiderRazvi** [comment]
Thanks so much. Appreciate the super quick response and fix.
