### ISSUE TITLE
Configuration by things other than files

### ISSUE THREAD

**Issue by DorianGray** [dropwizard/dropwizard#409]
I have seen people suggest classpath loading for yaml files to solve problems similar to the one I have encountered. They have been shot down, for good reason, since they were only hanging themselves in the long run. I suppose should begin by presenting my case...

I have written a module for dropwizard 0.7-SNAPSHOT that allows rewriting configuration(even nested deeply in the factory methods and things) by environment variables via reflection. The variables are loaded based on a prefix, by default "APP". To configure the first applicationConnector section's "port", for example, you would set the environment variable APP_SERVER_APPLICATIONCONNECTORS_0_PORT=80.

The reason I have written this is so that I can use operating system standard locations and formats for configuration. I also plan on releasing this under the apache license as soon as I have it production ready.

That being said, It is quite difficult at this juncture to extend literally every configuration factory class just to set up defaults. I am open to other suggestions, like maybe allowing configuration via a map in application.initialize or something.

**Comment by carlo-rtr** [comment]
I think this will help achieve what your looking for
http://dropwizard.io/manual/core.html#environment-variables
