### ISSUE TITLE
DropwizardAppExtension does not cleanup database resources

### ISSUE THREAD

**Issue by isaki** [dropwizard/dropwizard#4097]
When a suite of tests is torn down, the open database connections to PostgreSQL remain. Thus, when multiple suites are run from the same regression artifact, eventually the tests exceed the maximum connections configured for the PostgreSQL database.

I will attempt to look into why this is happening, but if someone has an answer/workaround already, I would appreciate it.

**Related Version Information:**

- Dropwizard: 2.0.23
- JDBI: 3.20.1
- PostgreSQL JDBC Driver: 42.2.22
- Liquibase: 4.4.0

EDIT: The idle connections not being cleaned all last executed `/* Health Check */ SELECT 1`.

**Comment by isaki** [comment]
The issue is not in fact DropWizard but is Liquibase; forcing Liquibase to 4.3.5 fixes the issue.

**Comment by joschi** [comment]
> The issue is not in fact DropWizard but is Liquibase; forcing Liquibase to 4.3.5 fixes the issue.

Thanks for the update!

Did you open a bug report with Liquibase which we could follow?
