### ISSUE TITLE
encryption of keyStore Password

### ISSUE THREAD

**Issue by camechis** [dropwizard/dropwizard#410]
Add the capability to have the password for keystores in the YAML file be encrypted.  I believe Jetty has the capability/tools for this.

**Comment by carlo-rtr** [comment]
I think the right thing to do is take the dbpassword out of your configuration and use a template variable which is substituted by environment variables.

http://dropwizard.io/manual/core.html#environment-variables
https://github.com/dropwizard/dropwizard/commit/f61215e72ff6a7aadab9f5687bb4f4e43325a576
