### ISSUE TITLE
How to create configuration property of type Duration

### ISSUE THREAD

**Issue by RohanNagar** [dropwizard/dropwizard#4188]
Hi, I was looking for some documentation on how to use `java.time.Duration` as a configuration property but couldn't find any. I have the following configuration:

```java
@Valid @JsonProperty("operationTimeout")
private final Duration operationTimeout;
```

And in my YML file I have:

```yml
operationTimeout: 20s
```

but when I try to read this, I get an error:

```
Incorrect type of value at: requestOptions.operationTimeout; is of type: String, expected: Duration
```

What is the correct way to specify a `Duration` in the yml file? Thanks for your help!

**Comment by mattnelson** [comment]
Does using a ISO8601 duration format work?

```yaml
operationTimeout: PT20S
```

**Comment by RohanNagar** [comment]
@mattnelson yes! That works, thanks so much.

**Comment by joschi** [comment]
For more readable durations in your configuration files, you can also use [`io.dropwizard.util.Duration`](https://javadoc.io/static/io.dropwizard/dropwizard-util/2.0.24/io/dropwizard/util/Duration.html).

**Comment by RohanNagar** [comment]
Thanks @joschi, this is perfect.
