### ISSUE TITLE
Sonar security vulnerabilities

### ISSUE THREAD

**Issue by zUniQueX** [dropwizard/dropwizard#4279]
Sonar suggests not to throw an `IOException` from a servlet method because the stack trace could be exposed. Would it be correct to catch these exceptions and just log their messages?

If the exceptions are really intended, we could suppress the Sonar warnings with `@SuppressWarnings("java:S1989")`.

**Comment by saraswathy-krish** [comment]
Hi @zUniQueX , I am interested to know more about this issue and would love to work on it.

**Comment by zUniQueX** [comment]
Hi @saraswathy-krish. In the Sonar report there are security issues because IOExceptions are thrown from servlet methods. I just wanted to discuss, how we should handle these warnings.

If we catch those exceptions and log them, we would modify public APIs and therefore introduce a breaking change.

If we don't do anything about this, Sonar describes the possibility of denial-of-service attacks or information exposure.

I think, that both alternatives are not optimal, but I'd prefer being secure and therefore would catch the exceptions.
