### ISSUE TITLE
Dropwizard-jetty/core pulls in javax.servlet transitively

### ISSUE THREAD

**Issue by jtvd78** [dropwizard/dropwizard#4290]
At my workplace, we are currently transitioning from Dropwizard 1.x to 2.x (2.0.20 in particular). At the same time, we are replacing all the javax dependencies in our codebase with jakarta dependencies. One thing we noticed is that while Dropwiard has made an effort to depend only on jakarta dependencies, it still manages to transitively pull in some of the older javax dependencies, specifically javax.servlet:javax.servlet-api.

Now, I am not very comfortable with maven -- we use Gradle at work, so I can only provide a reproducible example in gradle terms, but I imagine everything is transferable. Take this example build.gradle file:
```
apply plugin: 'java'

dependencies {
    implementation 'io.dropwizard:dropwiard-core:2.0.25'
}
```
Then, I can execute the `:dependencies` task on the project and gradle will list a tree of all dependencies (including transitive) for the project. If we search specifically for javax dependencies using the following command, we can see that javax.servlet-api is in fact pulled in transitively (even though after looking through Dropwizard's POMs that there is a large effort to exclude javax.servlet-api from the transitive dependencies elsewhere). 
```
# Command:
./gradlew :dependencies --configuration runtimeClasspath | grep javax -B 5

# Output:
       +--- io.dropwizard:dropwizard-metrics:2.0.25
       |    +--- io.dropwizard:dropwizard-lifecycle:2.0.25
       |    |    +--- com.google.code.findbugs:jsr305:3.0.2
       |    |    +--- org.slf4j:slf4j-api:1.7.32
       |    |    +--- org.eclipse.jetty:jetty-server:9.4.43.v20210629
       |    |    |    +--- javax.servlet:javax.servlet-api:3.1.0
```
You can see jetty-server pulls in javax.servlet-api here, or at least that's what the dependency tree is saying here. In fact, in [dropwizard-lifecycle's POM](https://github.com/dropwizard/dropwizard/blob/v2.0.25/dropwizard-lifecycle/pom.xml#L24-L33) we can see that javax.servlet-api has been excluded. So why is it showing up here? Well, it's because there are other projects which depend on jetty-server, either directly or transitively which don't exclude javax.servlet-api. 

From what I could dig up, the two culprits (at least in DW 2.0.20) are explicit dependencies on metrics-jetty9 and jetty-security. It seems that DW 2.0.23 fixed the jetty9 issue with [this commit](https://github.com/dropwizard/dropwizard/commit/4307b06daf5d35d7297c71ecec3c1024105d7d02), though 2.0.25 still depends on jetty-security without excluding javax.servlet-api (jetty-security depends on jetty-server which depends on javax.servlet-api)

Take for example the following build.gradle file and we run the same command as above. 
```
apply plugin: 'java'

dependencies {
    implementation 'io.dropwizard:dropwiard-jetty:2.0.25'
}
```
Running the same command as above, we get the following output:
```
       +--- org.eclipse.jetty:jetty-io:9.4.43.v20210629
       |    \--- org.eclipse.jetty:jetty-util:9.4.43.v20210629
       +--- org.eclipse.jetty:jetty-security:9.4.43.v20210629
       |    \--- org.eclipse.jetty:jetty-server:9.4.43.v20210629
       |         +--- javax.servlet:javax.servlet-api:3.1.0
```

It appears DW depends on jetty-security twice, in [dropwizard-core](https://github.com/dropwizard/dropwizard/blob/v2.0.25/dropwizard-core/pom.xml#L122-L125) and [dropwizard-jetty](https://github.com/dropwizard/dropwizard/blob/v2.0.25/dropwizard-jetty/pom.xml#L56-L59). I believe we can fix this issue if we exclude javax.servlet-api from both of these dependency declarations. 

Personally, I find it quite crazy how much manual dependency management needs to go on to avoid pulling in these old javax dependencies. It seems like Dropwizard is going through a lot of work to exclude these dependencies individually from each transitive dependency which may still be depending on them. In gradle world, we can just do something like below and we don't have to worry about javax.servlet-api polluting our classpath ever. I find it hard to believe maven dependencyManagement can't do something similar (though, as I said, I am not skilled with working directly with maven). 
```
configurations.all {
    exclude group: 'javax.servlet'
}
```

Even if we are able to resolve this issue with these two new exclusions, I am still curious if there is a way to blanket exclude these javax dependencies from ever being pulled in transitively, so that so much manual (and error-prone) work doesn't need to happen to exclude them. Further, perhaps for even more confidence that these javax (and other) excluded dependencies aren't included in the in the final dependency tree, what if Dropwizard added to the build some kind of check on the resolved dependencies to ensure that the final classpath does not contain any offending dependencies? IMO if there is a problem with a POM in that it pulls in a javax dependency, the build should fail. 

Sorry for the long-winded issue. I wanted to provide as much detail as I could to try to best outline the issue I was seeing and provide reproducible examples and a potential solution (I haven't actually verified that the two exclusions I mentioned completely resolve the issue). 

Thank you

**Comment by joschi** [comment]
@jtvd78 Thanks for reporting this!

I'm unable to reproduce the issue with Maven:

**`pom.xml`:**
```xml
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>io.dropwizard.github</groupId>
    <artifactId>issue-4290</artifactId>
    <version>1.0.0-SNAPSHOT</version>
    <packaging>jar</packaging>
    <dependencies>
        <dependency>
            <groupId>io.dropwizard</groupId>
            <artifactId>dropwizard-jetty</artifactId>
            <version>2.0.25</version>
        </dependency>
    </dependencies>
</project>
```

**Dependency tree:**
```text
# mvn -B -V dependency:tree|grep servlet-api
[INFO]    +- jakarta.servlet:jakarta.servlet-api:jar:4.0.4:compile
```

<details>
<summary>
Full output of `mvn -B -V dependency:tree`
</summary>

```text
# mvn -B -V dependency:tree
Apache Maven 3.8.2 (ea98e05a04480131370aa0c110b8c54cf726c06f)
Maven home: /usr/local/Cellar/maven/3.8.2/libexec
Java version: 11.0.12, vendor: Azul Systems, Inc., runtime: /Users/joschi/.asdf/installs/java/zulu-11.50.19/zulu-11.jdk/Contents/Home
Default locale: de_DE, platform encoding: UTF-8
OS name: "mac os x", version: "11.5", arch: "x86_64", family: "mac"
[INFO] Scanning for projects...
[INFO]
[INFO] ------------------< io.dropwizard.github:issue-4290 >-------------------
[INFO] Building issue-4290 1.0.0-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO]
[INFO] --- maven-dependency-plugin:2.8:tree (default-cli) @ issue-4290 ---
[INFO] io.dropwizard.github:issue-4290:jar:1.0.0-SNAPSHOT
[INFO] \- io.dropwizard:dropwizard-jetty:jar:2.0.25:compile
[INFO]    +- io.dropwizard:dropwizard-jackson:jar:2.0.25:compile
[INFO]    |  +- com.google.guava:guava:jar:30.1.1-jre:compile
[INFO]    |  |  +- com.google.guava:failureaccess:jar:1.0.1:compile
[INFO]    |  |  +- com.google.guava:listenablefuture:jar:9999.0-empty-to-avoid-conflict-with-guava:compile
[INFO]    |  |  +- org.checkerframework:checker-qual:jar:3.8.0:compile
[INFO]    |  |  +- com.google.errorprone:error_prone_annotations:jar:2.5.1:compile
[INFO]    |  |  \- com.google.j2objc:j2objc-annotations:jar:1.3:compile
[INFO]    |  +- com.github.ben-manes.caffeine:caffeine:jar:2.9.2:compile
[INFO]    |  +- com.fasterxml.jackson.core:jackson-core:jar:2.10.5:compile
[INFO]    |  +- com.fasterxml.jackson.datatype:jackson-datatype-guava:jar:2.10.5:compile
[INFO]    |  +- com.fasterxml.jackson.datatype:jackson-datatype-jsr310:jar:2.10.5:compile
[INFO]    |  +- com.fasterxml.jackson.datatype:jackson-datatype-jdk8:jar:2.10.5:compile
[INFO]    |  +- com.fasterxml.jackson.module:jackson-module-parameter-names:jar:2.10.5:compile
[INFO]    |  +- com.fasterxml.jackson.module:jackson-module-afterburner:jar:2.10.5:compile
[INFO]    |  \- com.fasterxml.jackson.datatype:jackson-datatype-joda:jar:2.10.5:compile
[INFO]    |     \- joda-time:joda-time:jar:2.9.9:compile
[INFO]    +- io.dropwizard:dropwizard-logging:jar:2.0.25:compile
[INFO]    |  +- io.dropwizard.metrics:metrics-logback:jar:4.1.25:compile
[INFO]    |  +- org.slf4j:jul-to-slf4j:jar:1.7.32:compile
[INFO]    |  +- ch.qos.logback:logback-core:jar:1.2.5:compile
[INFO]    |  +- ch.qos.logback:logback-classic:jar:1.2.5:compile
[INFO]    |  +- io.dropwizard.logback:logback-throttling-appender:jar:1.1.3:compile
[INFO]    |  +- org.slf4j:log4j-over-slf4j:jar:1.7.32:runtime
[INFO]    |  \- org.slf4j:jcl-over-slf4j:jar:1.7.32:runtime
[INFO]    +- io.dropwizard:dropwizard-util:jar:2.0.25:compile
[INFO]    +- io.dropwizard:dropwizard-validation:jar:2.0.25:compile
[INFO]    |  +- com.fasterxml:classmate:jar:1.5.1:compile
[INFO]    |  +- org.hibernate.validator:hibernate-validator:jar:6.1.7.Final:compile
[INFO]    |  |  \- org.jboss.logging:jboss-logging:jar:3.3.2.Final:compile
[INFO]    |  \- org.glassfish:jakarta.el:jar:3.0.4:runtime
[INFO]    +- io.dropwizard.metrics:metrics-core:jar:4.1.25:compile
[INFO]    +- com.fasterxml.jackson.core:jackson-annotations:jar:2.10.5:compile
[INFO]    +- com.fasterxml.jackson.core:jackson-databind:jar:2.10.5.1:compile
[INFO]    +- com.google.code.findbugs:jsr305:jar:3.0.2:compile
[INFO]    +- jakarta.validation:jakarta.validation-api:jar:2.0.2:compile
[INFO]    +- org.eclipse.jetty:jetty-io:jar:9.4.43.v20210629:compile
[INFO]    +- org.eclipse.jetty:jetty-security:jar:9.4.43.v20210629:compile
[INFO]    +- org.eclipse.jetty:jetty-server:jar:9.4.43.v20210629:compile
[INFO]    +- org.eclipse.jetty:jetty-util:jar:9.4.43.v20210629:compile
[INFO]    +- org.slf4j:slf4j-api:jar:1.7.32:compile
[INFO]    +- jakarta.servlet:jakarta.servlet-api:jar:4.0.4:compile
[INFO]    +- org.eclipse.jetty:jetty-servlet:jar:9.4.43.v20210629:compile
[INFO]    |  \- org.eclipse.jetty:jetty-util-ajax:jar:9.4.43.v20210629:compile
[INFO]    +- org.eclipse.jetty:jetty-servlets:jar:9.4.43.v20210629:compile
[INFO]    |  \- org.eclipse.jetty:jetty-continuation:jar:9.4.43.v20210629:compile
[INFO]    \- org.eclipse.jetty:jetty-http:jar:9.4.43.v20210629:compile
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  1.053 s
[INFO] Finished at: 2021-09-24T16:00:17+02:00
[INFO] ------------------------------------------------------------------------
```
</details>

I can, however, reproduce the described behavior with Gradle 7.2:

**`build.gradle`:**
```groovy
plugins {
  id 'java'
}

repositories {
    mavenLocal()
}

dependencies {
    implementation 'io.dropwizard:dropwizard-jetty:2.0.25'
}
```

```text
# gradle -v

------------------------------------------------------------
Gradle 7.2
------------------------------------------------------------

Build time:   2021-08-17 09:59:03 UTC
Revision:     a773786b58bb28710e3dc96c4d1a7063628952ad

Kotlin:       1.5.21
Groovy:       3.0.8
Ant:          Apache Ant(TM) version 1.10.9 compiled on September 27 2020
JVM:          11.0.12 (Azul Systems, Inc. 11.0.12+7-LTS)
OS:           Mac OS X 11.5 x86_64
```
```text
# gradle dependencyInsight --dependency servlet-api

> Task :dependencyInsight
jakarta.servlet:jakarta.servlet-api:4.0.4
   variant "compile" [
      org.gradle.status              = release (not requested)
      org.gradle.usage               = java-api
      org.gradle.libraryelements     = jar (compatible with: classes)
      org.gradle.category            = library

      Requested attributes not found in the selected variant:
         org.gradle.dependency.bundling = external
         org.gradle.jvm.environment     = standard-jvm
         org.gradle.jvm.version         = 11
   ]

jakarta.servlet:jakarta.servlet-api:4.0.4
\--- io.dropwizard:dropwizard-jetty:2.0.25
     \--- compileClasspath

javax.servlet:javax.servlet-api:3.1.0
   variant "compile" [
      org.gradle.status              = release (not requested)
      org.gradle.usage               = java-api
      org.gradle.libraryelements     = jar (compatible with: classes)
      org.gradle.category            = library

      Requested attributes not found in the selected variant:
         org.gradle.dependency.bundling = external
         org.gradle.jvm.environment     = standard-jvm
         org.gradle.jvm.version         = 11
   ]

javax.servlet:javax.servlet-api:3.1.0
\--- org.eclipse.jetty:jetty-server:9.4.43.v20210629
     +--- io.dropwizard:dropwizard-jetty:2.0.25
     |    \--- compileClasspath
     \--- org.eclipse.jetty:jetty-security:9.4.43.v20210629
          +--- io.dropwizard:dropwizard-jetty:2.0.25 (*)
          \--- org.eclipse.jetty:jetty-servlet:9.4.43.v20210629
               \--- io.dropwizard:dropwizard-jetty:2.0.25 (*)

(*) - dependencies omitted (listed previously)
```

**Comment by jtvd78** [comment]
Thank you for looking into this further. Do you think the maven-enforcer banned dependencies rule would have found this? 
https://maven.apache.org/enforcer/enforcer-rules/bannedDependencies.html

**Comment by joschi** [comment]
@jtvd78 The dependency resolution algorithm of Maven is working differently than the one of Gradle.

As demonstrated by the minimal Maven project in https://github.com/dropwizard/dropwizard/issues/4290#issuecomment-926656976, Maven doesn't transitively pull in `javax.servlet:javax.servlet-api`, so that the Maven Enforcer plugin wouldn't detect any banned dependencies.
