### ISSUE TITLE
Add flattening to AccessJsonLayout

### ISSUE THREAD

**Issue by georgespalding** [dropwizard/dropwizard#4396]
Today there are three categories of information that end up as nested objects/dictionaries in the json formatted access logs (when configured):

* requestHeaders
* responseHeaders
* requestAttributes

For simplicity and alignment across other micro-services in out setup, the ability to flatten these nested objects into the root json object would be VERY nice.

The use-case here is to emit access logs aligned across micro-services implemented using different technologies. 
Other options would be to do post-processing of the logs downstream, but  IMO it is much preferred to emit logs the way you want them to look right away:

To get the json logs formatted right from the start, would mean that there is no extra work downstream:
- No need to figure out how to filter/transform externally
- Explain why there are extra post processing steps [to the team]
- In the worst case explain to the "enterprise logging department" somewhere in the org to do an extra transformation.

**Comment by georgespalding** [comment]
This issue is a retrofit for https://github.com/dropwizard/dropwizard/pull/4386

**Comment by zUniQueX** [comment]
@georgespalding After you closed your PR, do we need this any more?

**Comment by georgespalding** [comment]
While the feature made it quite flexible, my feeling was that the configuration was quite complicated to get right.
I ended up implementing a specialized `AbstractJsonLayoutBaseFactory´ that generates exactly the json format that suited the requirements. (Side note the req was to emit logs suitable for ingestion in GCP logging, specifically this: https://cloud.google.com/logging/docs/reference/v2/rest/v2/LogEntry#HttpRequest)

**Comment by georgespalding** [comment]
While the feature made it quite flexible, my feeling was that the configuration was quite complicated to get right.
I ended up implementing a specialized `AbstractJsonLayoutBaseFactory´ that generates exactly the json format that suited the requirements. (Side note the req was to emit logs suitable for ingestion in GCP logging, specifically this: https://cloud.google.com/logging/docs/reference/v2/rest/v2/LogEntry#HttpRequest)
