### ISSUE TITLE
Allow for using external logback.xml configuration

### ISSUE THREAD

**Issue by kartech** [dropwizard/dropwizard#448]
I'd like to add some custom appenders (like Whisper) that require specialized configuration. Does dropwizard allow you to move all logging configuration outside of yaml to logback's own xml configuration file?

If you don't please consider doing so. Otherwise you are trying to unnecessarily wrap another library into your yaml and will always play catchup to logback.

**Comment by skradel** [comment]
FWIW, I have not found dropwizard 0.8 to discover any AppenderFactory implementations from the classpath, but adding a custom META-INF/services/io.dropwizard.logging.AppenderFactory has an effect.  Bit clunky and a lot of extra work to create the custom factory compared to simply using logback.xml however...

**Comment by brentryan** [comment]
This is the only reason we maintain our own fork of dropwizard.  We like everything else, but having native support for a logback.xml file is still far superior for our needs then what we can do in YAML.  

Our fork basically removes the dropwizard logging functionality and now we just rely on plain old logback and life is good.

**Comment by mjallday** [comment]
@skradel / @brentryan - care to share that particular code?

**Comment by dennyac** [comment]
@mjallday Check out this repository - https://github.com/Wikia/dropwizard-logstash-encoder . Contains an implementation. Be sure to check out the open pull requests as well.

**Comment by redarqas** [comment]
+1

**Comment by brentryan** [comment]
@mjallday Here's our fork of dropwizard that allows us to just use the native logback system with dropwizard.  https://github.com/cvent/dropwizard/tree/v0.7-cvent

With this we simply pass in -Dlogback.configurationFile=logback.xml on startup and we have full logging capabilities.

Makes it easy for us to use open source json logging encoders for our integration with splunk

        <encoder class="ch.qos.logback.core.encoder.LayoutWrappingEncoder">
            <layout class="ch.qos.logback.contrib.json.classic.JsonLayout">
                <jsonFormatter class="ch.qos.logback.contrib.jackson.JacksonJsonFormatter">
                    
                    <prettyPrint>false</prettyPrint>
                </jsonFormatter>
                <timestampFormat>yyyy-MM-dd'T'HH:mm:ss.SSS'Z'</timestampFormat>
                <timestampFormatTimezoneId>UTC</timestampFormatTimezoneId>
                <appendLineSeparator>true</appendLineSeparator>
            </layout>
        </encoder>
