### ISSUE TITLE
Cannot reconfigure JacksonMessageBodyProvider

### ISSUE THREAD

**Issue by DorianGray** [dropwizard/dropwizard#450]
I was looking for a way to work around https://github.com/dropwizard/dropwizard/issues/231 and I found that calling JacksonMessageBodyProvider.removeUntouchable(String.class) would do just that!

Unfortunately,JacksonMessageBodyProvider is added to the jersey environment after the initialization process. This occurs in AbstractServerFactory.createAppServlet.

Is there a way I can access this provider in a clean way? Or, will a dropwizard change be necessary to allow me to access this particular provider?

**Comment by carlo-rtr** [comment]
You can create your own server factory, extending one of the 
 existing ones. You will need to register it in META-INF/services

in ServerFactory.build(environment)
delegate to the existing one, afterwards overwrite the JacksonProvider

```
        JacksonMessageBodyProvider jacksonMessageBodyProvider
                = new JacksonMessageBodyProvider(environment.getObjectMapper(), environment.getValidator());
        jacksonMessageBodyProvider.addUntouchable(String.class);
        environment.jersey().register(jacksonMessageBodyProvider);
```
