### ISSUE TITLE
useProxyProtocol should be mentioned in Dropwizard Configuration Reference

### ISSUE THREAD

**Issue by boecko** [dropwizard/dropwizard#4512]
As #1176 is already implemented since v2.0.0 this nice feature should be mentioned on the Configuration Reference Page.

https://www.dropwizard.io/en/latest/manual/configuration.html#http

That's it ;)

**Comment by joschi** [comment]
@boecko Thanks for reporting this!

Would you like to create a pull request to add documentation for this configuration setting?

**Comment by boecko** [comment]
@joschi done
