### ISSUE TITLE
Dropwizard 2.0.25 -> 2.0.26 dependency issue causing surefire errors

### ISSUE THREAD

**Issue by brentryan** [dropwizard/dropwizard#4538]
We recently tried upgrading from 2.0.25 to 2.0.26 and some of our maven modules fail to compile with this error:

```
Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:3.0.0-M5:test
org.apache.maven.surefire.booter.SurefireBooterForkException: There was an error in the forked process
```

Any idea what dependency changes might be related to this?

**Comment by joschi** [comment]
> ```
> org.apache.maven.surefire.booter.SurefireBooterForkException: There was an error in the forked process
> ```

Any chance finding out what the error was?

**Comment by brentryan** [comment]
It's still not clear what's causing it. It only happens once we update to 2.0.26 and it happens consistently with certain java projects during "mvn verify" phase which eventually executes "maven-surefire-plugin:3.0.0-M5:test". To make things worse, we haven't been able to reproduce locally. It only happens in our build farm which runs inside a docker container.

**Comment by mattnelson** [comment]
Does it happen with 2.0.28?

**Comment by brentryan** [comment]
yes

**Comment by brentryan** [comment]
I've been able to get things working on 2.0.28 while using an older version of junit dependencies (what's used in 2.0.25):
```
            <dependency>
                <groupId>org.junit.jupiter</groupId>
                <artifactId>junit-jupiter-api</artifactId>
                <version>5.7.2</version>
            </dependency>
            <dependency>
                <groupId>org.junit.platform</groupId>
                <artifactId>junit-platform-commons</artifactId>
                <version>1.7.2</version>
            </dependency>
            <dependency>
                <groupId>org.junit.platform</groupId>
                <artifactId>junit-platform-engine</artifactId>
                <version>1.7.2</version>
            </dependency>
            <dependency>
                <groupId>org.junit.vintage</groupId>
                <artifactId>junit-vintage-engine</artifactId>
                <version>5.7.2</version>
            </dependency>
```

I'll have to dig into specifics as to why.

**Comment by brentryan** [comment]
It looks like this issue is related to `maven-surefire-plugin` version 3.0.0-M5 AND latest versions of junit. I've been able to confirm that it works fine with maven-surefire-plugin 2.22.2 and latest versions of junit.

Since dropwizard itself only uses 2.22.2, it seems like this is an issue with the surefire plugin. This could make sense since it's only a milestone release currently. We originally pushed towards using this version because we wanted to get unit test code coverage results working and there's other bugs in 2.22.2 that stopped jacoco from working.

Does the dropwizard community have any recommendations for code coverage tools?

**Comment by zUniQueX** [comment]
I just tested this and when using the `maven-surefire-plugin` with version `3.0.0-M5` there seems to be an issue with the Jersey client:
```
[ERROR] WARNING: Illegal reflective access by org.glassfish.jersey.client.internal.HttpUrlConnector$3
```
However, this is just an error in the logs and the tests run fine. I just don't know, if this could fail on different JDKs or Maven versions.

**Comment by brentryan** [comment]
I've opened a ticket with surefire plugin here https://issues.apache.org/jira/browse/SUREFIRE-1971
