### ISSUE TITLE
Undertow Support?

### ISSUE THREAD

**Issue by Nano-GG** [dropwizard/dropwizard#475]
Hello,

After see some amazing performance about undertow.io 
- http://www.techempower.com/benchmarks/previews/round9/#section=data-r9&hw=peak&test=json
- http://undertow.io/

I want ask if is possible use Undertow instead Jetty, i guess this should boost the Dropwizard performance.

I also want to know why Dropwizard dont appear on Fortunes/Data Updates/PlainText

Thanks for your time.

**Comment by uromahn** [comment]
Hello!
is there an update to this question and the answer above?
We are now two years further down the road and Untertow has significantly matured and shows some great performance figures over Jetty.
Also integrating with Untertow shouldn't be too complex, IMHO.

Thanks for your consideration. :)
