### ISSUE TITLE
Question: Jackson update to 2.13 for Dropwizard 2.x?

### ISSUE THREAD

**Issue by christopher-cudennec** [dropwizard/dropwizard#4982]
Hi @joschi !

Do you plan to upgrade the 2.x branch to Jackson 2.13? Are there any known issues that prohibit the upgrade?

Thanks for the great work and for clarification! 😃 

Christopher

**Comment by zUniQueX** [comment]
Hi @christopher-cudennec!

We are currently preparing the release of version 2.1.0, in which Jackson 2.13.2 will be used.

**Comment by christopher-cudennec** [comment]
Thanks for the quick response @zUniQueX !

Do you have a document for migration / incompabilities between 2.0 and 2.1?
We're currently using [2.0.28](https://github.com/SDA-SE/sda-dropwizard-commons/blob/master/sda-commons-dependencies/build.gradle#L10).

Thanks,

Christopher
