### ISSUE TITLE
Upgrade to Hibernate ORM 6.0.x

### ISSUE THREAD

**Issue by joschi** [dropwizard/dropwizard#5168]
- https://hibernate.org/orm/releases/6.0/
- https://in.relation.to/2022/03/31/orm-60-final/

**Comment by zUniQueX** [comment]
As far as I can see in the migration guide, the integration shouldn't be a big problem for us. Maybe some users have to migrate their code.

However, [Jackson doesn't seem to support Hibernate 6 yet](https://github.com/FasterXML/jackson-datatype-hibernate).

**Comment by zUniQueX** [comment]
[Issue at Jackson](https://github.com/FasterXML/jackson-datatype-hibernate/issues/158) to track the status of Hibernate 6 support.
