### ISSUE TITLE
Use Logback instead of log4j

### ISSUE THREAD

**Issue by klauern** [dropwizard/dropwizard#52]
This is more a suggestion than a bug, but I've been using [Logback](http://logback.qos.ch/) for my logging, and was curious if this was on the horizon or worth switching to?  It is positioned to be the successor to log4j, and as such, they even provide a pretty lengthy explanation on [why you should switch](http://logback.qos.ch/reasonsToSwitch.html).

Anyways, love the project, and I'm itching to use it at work.

**Comment by seven-qi** [comment]
@christophercurrie  Curious about how you're dealing with the logger. The current version is hard coded to use logback, if I want to use log4j in my system, how should I do it? Thanks!
