### ISSUE TITLE
admin interface hangs on 24-core machine

### ISSUE THREAD

**Issue by jbyler** [dropwizard/dropwizard#523]
_Primary symptom_: on a machine with 22 or more cores and the default server configuration, the admin interface accepts TCP connections and then never processes the requests, causing a browser to hang forever.  This can happen on any machine given the wrong config parameters.

Details:
- Server thread configuration must adhere to the following invariants, determined through debugging and trial and error:
  - `maxThreads` > ∑ (`acceptorThreads` + `selectorThreads`) over all `applicationConnectors`
  - `adminMaxThreads` > ∑ (`acceptorThreads` + `selectorThreads`) over all `adminConnectors`
- Presumably what this means is that `maxThreads` _includes_ all the `acceptorThreads` and `selectorThreads`, and what's left over is used for handling requests. If there's nothing left over, the requests queue up and never get handled.
- If this invariant is not satisfied, either the `applicationConnectors` or the `adminConnectors` (respectively) will accept TCP connections but then never handle them
- DropWizard's defaults for `maxThreads` (1024) and `adminMaxThreads` (64) are fixed, while the defaults for `acceptorThreads` (#CPUs/2) and `selectorThreads` (#CPUs) vary on different machines.
- So on a machine with 22 or more cores and an admin interface with 2 connectors (one for HTTP, one for HTTPS), the invariant doesn't hold for the admin interface.  With 342 or more cores and 2 connectors, it won't hold for the application interface.

There are potentially 3 parts to this bug:
- DropWizard defaults should probably be made so they work on all modern hardware.
- DropWizard should probably validate the configuration and fail to start if an invariant isn't satisfied, rather than silently hanging.
- Perhaps the invariant should be documented.
- Alternatively, the meaning of the parameters could be changed so that they are independent.  Using `maxThreads` only for processing requests (and not for selector threads and acceptor threads) might be more intuitive.

Tested with version `v0.7.0.rc3`.

How to reproduce: use the `dropwizard-example` application on a 24-core machine, or use the following server config on any machine:

```
server:
  minThreads: 2
  maxThreads: 2
  applicationConnectors:
    - type: http
      port: 8080
      acceptorThreads: 1
      selectorThreads: 1
  adminConnectors:
    - type: http
      port: 8081
      acceptorThreads: 1
      selectorThreads: 1
```

App starts successfully, but requests to either the application or the admin interface hang.

**Comment by vishvananda** [comment]
This seems to be fixed for maxThreads but not adminMaxThreads.

If maxThreads is set too low, it errors as expected.

If adminMaxThreads is set to something far too low (say 2), the service will happily start without displaying an error message from jetty and then not be able to deal with requests. It also hangs on shutdown for the full 30 second timeout while it is waiting for jetty to shutdown.

I suspect either the admin connector is taking a different route through jetty and skipping the exception, or the exception is getting eaten somewhere on the dropwizard side. 

Using dropwizard 0.9.1 fwiw
