### ISSUE TITLE
Cannot inject a custom principal into unauthenticated request

### ISSUE THREAD

**Issue by matthias-mueller** [dropwizard/dropwizard#5265]
When a method in a Jersey resource has a parameter (for instance of some type `User`) annotated with `@Auth` and authentication fails, the following exception is thrown:

```
ERROR [2022-05-02 08:34:03,534] io.dropwizard.jersey.errors.IllegalStateExceptionMapper: Error handling a request: 1fa109dc501e3397
! java.lang.IllegalStateException: Cannot inject a custom principal into unauthenticated request
! at io.dropwizard.auth.PrincipalContainerRequestValueFactory.provide(PrincipalContainerRequestValueFactory.java:25)
! at io.dropwizard.auth.AuthValueFactoryProvider.lambda$createValueProvider$1(AuthValueFactoryProvider.java:51)
! at org.glassfish.jersey.server.spi.internal.ParamValueFactoryWithSource.apply(ParamValueFactoryWithSource.java:50)
```

While I can clearly see where this is coming from, I am not sure that it is always practical. It seems that Dropwizard requires authentication prior to injecting a principal, which is somewhat reasonable for many scenarios. For a particular application, I need a resource that also accepts anonymous (e.g. `null`) users to serve public content (whereas authenticated and authorized users see the public content plus X with X being the protected content).

As a workaround, I could append an AnonymousAuthenticator at the end of an Auth Chain and let this one create the `User` object. If Chained authentication is not necessary, a separate code path in a dedicated authenticator might also do the job (but is a dead end as soon as the application requires an additional authentication mechanism.)

So in general I can mitigate my particular problem in some ways but none of them feels 100% right. Is there a good reason why Dropwizard does not simply inject a NULL Principal if authentication cannot be performed?

**Comment by zUniQueX** [comment]
@matthias-mueller You can use an `@Auth Optional<T>` principal for your endpoint. This will let unauthenticated users pass. But you can check, if the principal is present, and add custom logic for this case.

**Comment by matthias-mueller** [comment]
Thanks for the hint @zUniQueX - While I can confirm that `@Auth Optional<T>` is working, I see some general issues with the control flow and the interplay of `@Auth`, `@PermitAll`, `@RolesAllowed` and `Optional<Principal>`. I have created four simple cases below.

__Resource Class__
```java
@Path("/test/example")
public class ExampleResource {

    private static final Logger LOGGER = LoggerFactory.getLogger(ExampleResource.class);

    public ExampleResource() {
    }

    @GET
    @Path("/optional-user")
    public String getOptionalUser(
            @Context final UriInfo requestUri, @Auth final Optional<JWTUser> user
    ) {
        LOGGER.info("found user {}", user);
        return Objects.toString(user);
    }

    @GET
    @Path("/nullable-user")
    public String getOptionalUser(
            @Context final UriInfo requestUri, @Auth final JWTUser user
    ) {
        LOGGER.info("found user {}", user);
        return Objects.toString(user);
    }

    @GET
    @Path("/optional-user-with-roles-allowed")
    @PermitAll
    public String getOptionalUserWithRolesAllowed(
            @Context final UriInfo requestUri, @Auth final Optional<JWTUser> user
    ) {
        LOGGER.info("found user {}", user);
        return Objects.toString(user);
    }

    @GET
    @Path("/nullable-user-with-roles-allowed")
    @PermitAll
    public String getNullableUserWithRolesAllowed(
            @Context final UriInfo requestUri, @Auth final JWTUser user
    ) {
        LOGGER.info("found user {}", user);
        return Objects.toString(user);
    }

}

```

__Test Class__
```java
@ExtendWith(DropwizardExtensionsSupport.class)
public final class RestServerExampleTest extends RestServerTestAbstract {


    private static final Logger LOGGER = LoggerFactory.getLogger(RestServerExampleTest.class);

    private static final DropwizardAppExtension<PermissionsRestServerConfiguration> EXT;

    static {
        LOGGER.info(ready);
        EXT = new DropwizardAppExtension<>(PermissionsRestServer.class, ResourceHelpers.resourceFilePath("permissions.yml"), updateDbConfig());
    }

    @Test
    public void getOptionalUser() {
        RestAssured.given()
                .contentType(MediaType.APPLICATION_JSON)
                .when()
                .get("/test/example/optional-user")
                .then()
                .statusCode(HttpStatus.OK_200);
    }

    @Test
    public void getNullableUser() {
        RestAssured.given()
                .contentType(MediaType.APPLICATION_JSON)
                .when()
                .get("/test/example/nullable-user")
                .then()
                .statusCode(HttpStatus.OK_200);
    }

    @Test
    public void getOptionalUserWithRolesAllowed() {
        RestAssured.given()
                .contentType(MediaType.APPLICATION_JSON)
                .when()
                .get("/test/example/optional-user-with-roles-allowed")
                .then()
                .statusCode(HttpStatus.UNAUTHORIZED_401);
    }

    @Test
    public void getNullableUserWithRolesAllowed() {
        RestAssured.given()
                .contentType(MediaType.APPLICATION_JSON)
                .when()
                .get("/test/example/nullable-user-with-roles-allowed")
                .then()
                .statusCode(HttpStatus.UNAUTHORIZED_401);
    }

}
```

__Test Results__
* getOptionalUser - __200 OK__
* getNullableUser - __500__ 
* getOptionalUserWithRolesAllowed - __200__ 
* getNullableUserWithRolesAllowed - __500__ 

__Observations__
> getOptionalUser
* works as expected

> getNullableUser 
* "Cannot inject a custom principal into unauthenticated request"
* this error is misleading because DW can actually inject a custom principal into an unauthenticated request (see `getOptionalUser`). It just refuses to do that if the target type is not an `Optional<T>`. At least there is no technical reason why DW cannot not inject NULL values if no principal could be obtained.
* Personal comment: That decision is at least arguable, because it forces people to use `<Optional>` in their APIs

> getNullableUserWithRolesAllowed
* "Cannot inject a custom principal into unauthenticated request"
* There should not be any injection attempt at all because `@PermitAll` already forbids access by unauthenticated users
* DW should return __401__-Unauthorized. The inability to authenticate a user is already a sufficient condition for the `@PermitAll` check and any code inside `@PermitAll getOptionalUserWithRolesAllowed()` would never be executed within that request

> getOptionalUserWithRolesAllowed
* The user could not be authenticated but is actually granted access - I would not expect this to happen with `@PermitAll`

__@RolesAllowed__
* If `@PermitAll` is substituted with `@RolesAllowed({'A'})` code `403 - Forbidden` is returned
* `401 - Unauthorized` - request has not been applied because it lacks valid authentication credentials for the target resource
* `403 - Forbidden` - the server understood the request but refuses to authorize it...If authentication credentials were provided in the request, the server considers them insufficient to  grant access
* Source: https://www.freecodecamp.org/news/http-401-error-vs-http-403-error-status-code-responses-explained/
* So if DW distinguishes between `401` and `403` returning a `401` seems more appropriate if no principal could be obtained

(Edited)

p.s.: https://stackoverflow.com/a/43393182
> The `@PermitAll`, `@RolesAllowed`, etc are only ways of Jersey handling authorization. It is expected that there already be an authenticated user. How Jersey checks this is by getting the principal from the servlet request. If there is no principal, then it is assumed that there is not authenticated user, and then will not allow anyone through, even if you have @PermitAll, __as even @PermitAll requires a user to be authenticated.__

**Comment by matthias-mueller** [comment]
(had to edit the above examples due to some code errors)

**Comment by zUniQueX** [comment]
@matthias-mueller Thanks for providing the test cases. Unfortunately, the `@RolesAllowed` things are a bit tricky. Jersey states in [its JavaDoc](https://eclipse-ee4j.github.io/jersey.github.io/apidocs/2.35/jersey/org/glassfish/jersey/server/filter/RolesAllowedDynamicFeature.html):
> If the &#64;PermitAll annotation is declared and is not overridden then this filter will not be applied.

[The implementation](https://github.com/eclipse-ee4j/jersey/blob/master/core-server/src/main/java/org/glassfish/jersey/server/filter/RolesAllowedDynamicFeature.java#L83) literally does nothing with this annotation. So the endpoints annotated with `@PermitAll` should behave the same as the corresponding non-annotated ones do (at least from Jersey's point of view).

The exception with the non-optional principal is a thing of definition in my opinion. If the message "Cannot inject a custom principal into unauthenticated request" is issued, an other definition than yours could be that a principal is defined as such only if it is _valid_, e.g. not `null`. Then the message is correct that no principal can be injected. Therefore the handling with the `Optional<T>` principal types is provided, as this allows the declaration that the principal may be unset.

**Comment by matthias-mueller** [comment]
On the 401 vs 403 return code question I have created a jersey issue: https://github.com/eclipse-ee4j/jersey/issues/5062 because their [JavaDoc](https://eclipse-ee4j.github.io/jersey.github.io/apidocs/2.35/jersey/org/glassfish/jersey/server/filter/RolesAllowedDynamicFeature.html) is ambiguous (The combination `403 (Not Authenticated)` is not defined in RFC7235)

**Comment by matthias-mueller** [comment]
@zUniQueX Thanks for the explanation! The [Jersey specification](https://download.oracle.com/otndocs/jcp/common_annotations-1_3-mrel3-spec/) on that annotation is not much clearer than the JavaDoc. It boils down to whether an unauthenticated user has a security role or not. (Which is not within the scope of this issue.)

It seems that [Spring](https://www.baeldung.com/spring-security-expressions#3-permitall-denyall) uses the same conventions as DW - so there is probably little surprise for developers (except for non Jersey experts like me).

**Comment by zUniQueX** [comment]
> On the 401 vs 403 return code question I have created a jersey issue: https://github.com/eclipse-ee4j/jersey/issues/5062 because their [JavaDoc](https://eclipse-ee4j.github.io/jersey.github.io/apidocs/2.35/jersey/org/glassfish/jersey/server/filter/RolesAllowedDynamicFeature.html) is ambiguous (The combination `403 (Not Authenticated)` is not defined in RFC7235)
> 

@matthias-mueller Thanks. As this is then a documentation problem on Jersey's side only, I'll close this issue, as we don't have to track their status on that topic here.
