### ISSUE TITLE
initialOverallState does not transition to true when there are no registered checks

### ISSUE THREAD

**Issue by oneadr-3773** [dropwizard/dropwizard#5266]
In the new health check functionality introduced in Dropwizard 2.1.0, if you set:
```yaml
health:
  initialOverallState: false
```
but have no checks registered for a specific type (either `alive` or `health`), then the overall state will never transition to `true`.

This is because the overall app state is calculated by `HealthCheckManager` only when there is a state change from a health check:
https://github.com/dropwizard/dropwizard/blob/dd25ab7b61052721af2ebec54a6b8da5ced30edd/dropwizard-health/src/main/java/io/dropwizard/health/HealthCheckManager.java#L161
https://github.com/dropwizard/dropwizard/blob/dd25ab7b61052721af2ebec54a6b8da5ced30edd/dropwizard-health/src/main/java/io/dropwizard/health/HealthCheckManager.java#L197

And if there aren't any checks, then no state change triggers and the state is never recalculated (even though the counter of failed checks is actually zero).

I guess that Dropwizard must do an explicit test and in case there aren't any checks registered, consider that the condition is satisfied (technically it is) and instantly set the respective flag (`isAppAlive` or `isAppHealthy`) to `true`.

**Comment by zUniQueX** [comment]
Hi @oneadr-3773. Thanks for reporting this.

I'm not completely convinced this is a general issue. The [`initialOverallState` flag only sets the `isAppHealthy` field](https://github.com/dropwizard/dropwizard/blob/release/2.1.x/dropwizard-health/src/main/java/io/dropwizard/health/HealthCheckManager.java#L144) and not the `isAppAlive` field. Therefore the application should be reported as alive, but not as ready. And as only checks with type `ready` are affected by this, I would suggest not to set the `initialOverallState` to `false`, if you don't have a health check for this type in your application :wink:

The framework has no restriction on when to add a health check. Maybe one would want to spawn a service from within the application and register the health check afterwards. Then it wouldn't be correct to set the application's health state to `true` before the health check gets registered. For this case the current behavior is correct and necessary.

**Comment by oneadr-3773** [comment]
Hi. I understand your explanation, and I do think it makes sense, however I think there are some subtleties worth discussing. I believe that depending on how you interpret the setting you'll have a specific mental model and then the implemented behaviour may be surprising.

I understand that there are no restrictions on when to add a health check. However, the framework also can't know if and/or when a new health check will be registered. Therefore you *could* have a mental model in which `initialOverallState` means `false` until every *registered health check[1] at the point in time when `run()` finishes* had the chance to run at least once (i.e., do not optimistically assume the healthy state).

For example, imagine you do have two health checks, A and B, registered early during startup. What the current implementation will do if you set `initialOverallState` to `false` is to stay `false` until both health checks run at least once. This is completely fine and expected. But note that the framework *can't* know that the code at runtime will register a third health check, C, in some unspecified point in the future. Obviously it won't "wait" for C to show up and be healthy in order to transition to the initial state to `true`, as that is impossible and no sane developer can have that expectation.

Therefore I do think that if you have a similar case, where you don't have any health check, then the framework should not "wait" for an unspecified future health check that may or may not come, it is consistent with the previous case for the framework just immediatelly transition to `true` as it waited for all health checks *that it knew about* once the `run()` method finishes (which would be the natural "checkpoint" given that the servlet just becomes exposed on that point). In this particular case, as there is no health check, then there is no *failing* health check, so no need to the app health to remain `false` once `run()` finishes. Naturally, if a new health check does end up being registered in the future, then the overall health state will transition accordingly.

I do understand that is not how's implemented, and I do think the current implementation makes sense under the circumstances you have explained, but to be honest I'm not convinced that will be the most likely mental model that developers will have in mind when they read the documentation. To me a much less surprising mental model would be:
> `initialOverallState` is the assumed state of the health of the app until all health checks registered at the point in time when the `run()` method finishes execution become healthy.

I feel that this behaviour would be the one that is most aligned with developers' expectations. As an anedoctal data point, my team was experimenting with the new health functionality and encountered this behaviour accidentaly and we were all unanimously convinced that it was a bug -- and it was what motivated me to post here.

I understand that we are basically discussing two edge cases and arguing which one is more likely to happen without data to back it up. I also understand that API design is not an exact science, and a decision must be made, and once made and shipped it's not easy to change it. That said, if you are convinced that the current implementation is the least surprising then I would suggest that the existing documentation for this area could be improved [2]. In particular, it should explicitly say something like:
> `initialOverallState` is the assumed state of the health of the app *until there is at least one health check registered* and *all registered health checks become healthy*. Note that if no health check is ever registered, then the state will never transition to `true` and in this case it should be left in its default (`true`) state.

To conclude, I hope that I am bringing some interesting new perspective and useful suggestions. Maybe this is already something you have considered during API design and made an informed trade-off about (or maybe not). Personally, as an user of your project I would have made a different trade-off (and so my colleagues, I believe) but that's the nature of API design. Either way, let me know what your thoughts are.

[1] All health checks are of type `ready` for the sake of discussion.
[2] It's completely understandable, this being a totally new feature, that the documentation can lag behind a bit. IMHO the new health functionality is a bit under-documented right now, and some details you can only figure out by experimentation and/or inspecting Dropwizard's source code.

**Comment by zUniQueX** [comment]
@oneadr-3773 Thanks for the detailed explanation. As our `README` states, the framework provides `opinionated` code, so this basically is what you said.

> I do understand that is not how's implemented, and I do think the current implementation makes sense under the circumstances you have explained, but to be honest I'm not convinced that will be the most likely mental model that developers will have in mind when they read the documentation.

The problem thereby is that we shipped with this implementation and that your suggestion would now be incompatible to that. But we could think of changing this with the 3.0.0 release. As I'm not a core developer of the `dropwizard-health` module, I'd refer to @natalie-zamani and @pstackle for that.

Anyway, the documentation should be up-to-date. As you mentioned, the current documentation doesn't fully explain the `initialOverallState`, so we would be happy to receive a PR on that.

**Comment by oneadr-3773** [comment]
Totally understood. My main goal was to bring this to your attention. I agree that changing the behaviour of a shipped version must be a very high bar and this certainly does not qualify, but maybe it's something you would consider tweaking in a future major release.
