### ISSUE TITLE
environment.jersey().register() should allow filter registration

### ISSUE THREAD

**Issue by timrobertson100** [dropwizard/dropwizard#528]
The following does not add a filter:

``` java
environment.jersey().register(new ResponseTimestampingFilter());
```

Instead, filters need to be added using:

``` java
environment.jersey().getResourceConfig().getContainerResponseFilters().add(new ResponseTimestampingFilter());
```

This seems like it might be a bug?

**Comment by sysmat** [comment]
in dropwizard v 0.8.x you just register filter to jersey:

1) CustomContainerResponseFilter implement ContainerResponseFilter
2) environment.jersey().register(new CustomContainerResponseFilter());

**Comment by VSJTech** [comment]
Adding dropwizzard servlet filter is not working.. it is not getting invoked nor i see the loggers getting printed from the filter class.

I have implemented a class that implements filters and added the same to the server application

**Comment by VSJTech** [comment]
Any help is appreciated.

Purpose of my filter: when application starts i want to get my filter invoke and get my application to redirect to a url(for SSO authentication). and get the page returned back to my application after authentication

**Comment by joschi** [comment]
@VSJTech Please use the [Dropwizard user mailing list](https://groups.google.com/forum/#!forum/dropwizard-user) for this discussion.
