### ISSUE TITLE
LinkageError from Jackson Blackbird

### ISSUE THREAD

**Issue by dannychao1** [dropwizard/dropwizard#5281]
Upon upgrading to Dropwizard 2.1.0, we encountered a LinkageError from Jackson Blackbird as described in this [issue](https://github.com/FasterXML/jackson-modules-base/issues/169).  `java.lang.LinkageError: loader 'app' attempted duplicate class definition for com.xxxx.$$JacksonBlackbirdAccess. (com.xxxx.$$JacksonBlackbirdAccess is in unnamed module of loader 'app')`

This causes httpclient to react and shutdown ([as described here](https://blog.adebski.com/posts/apache-http-client-shutting-down/)): `java.lang.IllegalStateException: Connection pool shut down`.  The issue is addressed in 2.13.3, can we expect an upgrade to this version in following dot releases of 2.1.x?

**Comment by zUniQueX** [comment]
We generally integrate dot releases fast (as they normally don't break anything)

**Comment by zUniQueX** [comment]
Resolved in #5293
