### ISSUE TITLE
ManagedPooledDataSource never added to the lifecycle

### ISSUE THREAD

**Issue by volnikh** [dropwizard/dropwizard#5284]
ManagedPooledDataSource is not being added to the lifecycle. SessionFactoryManager is being added and it do call start method on the ManagedPooledDataSource instance.
But without having access to the ManagedPooledDataSource there is no way to enable credentials rotation by changing user/password. Is there any security reason that ManagedPooledDataSource is not being added to the lifecycle.

**Comment by zUniQueX** [comment]
Hi @volnikh. Thanks for reporting this!

I'm not aware of a security issue on this topic. The `dropwizard-jdbi3` module also provides database access and there the `ManagedDataSource` [gets added to the lifecycle](https://github.com/dropwizard/dropwizard/blob/release/2.1.x/dropwizard-jdbi3/src/main/java/io/dropwizard/jdbi3/JdbiFactory.java#L73).

The reason for not adding the `ManagedDataSource` at the moment should be that `SessionFactoryManager` as a wrapper also provides a managed container.

**Comment by erik-sab** [comment]
@zUniQueX so what is the DropWizard suggested way in this case to rotate credentials with zero downtime (w/o rewriting whole implementation to custom one)?
What are implication of adding it there any way?

**Comment by zUniQueX** [comment]
Hi @erik-sab. Adding the `ManagedDataSource` additionally to the `LifecycleEnvironment` would lead to multiple calls of the `start()` and `stop()` methods. We could change the access modifier of the `SessionFactoryManager#getDataSource()` method to `public` to enable access through that managed object.

**Comment by erik-sab** [comment]
@zUniQueX is it doable? It would really unblock our scenario, let me know which version it is released with

**Comment by zUniQueX** [comment]
Fixed with #5681
