### ISSUE TITLE
Missing release notes for v2.1.0

### ISSUE THREAD

**Issue by richeyh** [dropwizard/dropwizard#5285]
I see a tag for [v2.1.0](https://github.com/dropwizard/dropwizard/releases/tag/v2.1.0)
However it looks like there was not any release notes for this. It also appears the artifacts were shipped to [maven central](https://mvnrepository.com/artifact/io.dropwizard/dropwizard-core/2.1.0)

 Was this an accidental release? or is this version ready to be picked up with the beta features?

**Comment by zUniQueX** [comment]
Hi @richeyh. The released build is the final release.

We are working on release notes. The status will then be reported in [this discussion](https://github.com/dropwizard/dropwizard/discussions/5283).
