### ISSUE TITLE
Dropwizard upgraded to 2.1.0 - Getting BlackBird warning

### ISSUE THREAD

**Issue by SHxKM** [dropwizard/dropwizard#5331]
Upon upgrading from dropwizard `2.0.25` to `2.1.0`, This warning is emitted whenever the application boots:

```
WARN  [2022-05-26 10:38:18,889] com.fasterxml.jackson.module.blackbird.BlackbirdModule: Unable to find Java 9+ MethodHandles.privateLookupIn.  Blackbird is not performing optimally!
! java.lang.NoSuchMethodError: java.lang.invoke.MethodHandles.privateLookupIn(Ljava/lang/Class;Ljava/lang/invoke/MethodHandles$Lookup;)Ljava/lang/invoke/MethodHandles$Lookup;
```

What does this error mean? is it looking for Java 9+ functionality that is not available in my Java 8 environment?

Also:

> Blackbird is not performing optimally!

Am I incurring a performance cost here vis-a-vis dropwizard `2.0.25`?

**Comment by zUniQueX** [comment]
Hi @SHxKM. This was already noticed by other users and is currently being discussed in #5319 and #5268. Please refer to those discussions for an answer.
