### ISSUE TITLE
How to reload static assets in dev mode?

### ISSUE THREAD

**Issue by klauern** [dropwizard/dropwizard#54]
Since Dropwizard supports `AssetsBundle`s, I thought that maybe this would be a quick way to test out them fancy JS frontends (Backbone, Ember, etc.) by throwing them up on `src/main/resources/assets` and trying to serve from there.  However, I quickly realized that Dropwizard either doesn't reload any of the resources it gets, or I'm missing something on configuring it to reload static assets.

If I were using the Maven Jetty plugin, I'd throw something in the config to use a custom `webdefault.xml` file as described here for us lowly Windows users: http://docs.codehaus.org/display/JETTY/Files+locked+on+Windows

Is this something I can do in Dropwizard, or is this too far out of scope for the tool?

**Comment by Vadi** [comment]
OK. It is 2015 today. Any solution for this? Every time compiling when changing code in views is really killing time.

**Comment by rjschu** [comment]
I do this by using [grunt](http://gruntjs.com/) and a few grunt tasks ([grunt-watch](https://github.com/gruntjs/grunt-contrib-watch), [grunt-clean](https://github.com/gruntjs/grunt-contrib-clean) and [grunt-copy](https://github.com/gruntjs/grunt-contrib-copy)) to update my assets files in the build directory. 

when you have grunt-watch running  all you have to do is make the changes to you assets files and then grunt will replace the files in your build directory so you can just refresh your webpage and get the changes. 

I know this isnt a solution to the issue but its a decent work around :)

**Comment by BorisNaguet** [comment]
Here's a solution on DW 0.7.1: 
* do not use the AssetBundle as you don't have access to all the details (don't worry it's a very tiny Bundle)
* Add the AssetsServlet directly from the run method of your Application class
* configure the mapping 
* add the desired initParameter (http://www.eclipse.org/jetty/documentation/current/troubleshooting-locked-files-on-windows.html)
* maybe add some way to enable/disbla this, as it's usefull in dev mode, but not in production

```java
Dynamic dynamic = environment.admin().addServlet("assets", new AssetServlet("/website", "/admin-site/", "index.html", Charsets.UTF_8));
dynamic.addMapping("/admin-site/*");
if(devMode){
    dynamic.setInitParameter("useFileMappedBuffer", "false");
}
```

**Comment by mv200580** [comment]
For Eclipse is good to use Filesync plugin, as it explained here http://www.onehippo.org/library/development/use-filesync-eclipse-plugin-for-faster-turn-around.html

**Comment by esiqveland** [comment]
```
Dynamic dynamic = environment.admin().addServlet("assets", new AssetServlet("/website", "/admin-site/", "index.html", Charsets.UTF_8));
dynamic.addMapping("/admin-site/*");
if(devMode){
    dynamic.setInitParameter("useFileMappedBuffer", "false");
}
```

Works for me in DW 0.9.
I use this and set my js build tool to copy the bundles into ./target/classes/assets/

**Comment by jplock** [comment]
Should we always default this parameter to `false` or make `AssetBundle` be configurable?

**Comment by esiqveland** [comment]
I think it's good for production use, but very annoying for developing with.
Not sure if it should be configurable or not, but maybe DW could use an overall devmode? This has probably been discussed before though.

On the other hand it is part of ```dropwizard-assets```, so it could be fine to add it to ```AssetBundle```?

I'm guess it is something everyone using assets in dropwizard has to deal with.
