### ISSUE TITLE
Potential Refactoring

### ISSUE THREAD

**Issue by alvintanjianjia** [dropwizard/dropwizard#5400]
Hi,

I am currently doing some research on Estimating Time Taken for Software Refactoring. Dropwizard is one of my case studies being a highly popular project.

I have identified some packages with refactoring potential and their estimated time to refactor. Would appreciate your kind feedback on the appropriateness of the estimated time to refactor.

1. io.dropwizard.migrations - 60 hours
2. io.dropwizard.logging - 58 hours
3. io.dropwizard.validation - 53 hours
4. io.dropwizard.util - 37 hours
5. io.dropwizard.hibernate - 32 hours

I will be grateful for any help you can provide.

Thank you.

Regards,
Alvin

**Comment by jplock** [comment]
What specifically are you estimating to be refactored?
