### ISSUE TITLE
Integration tests overwrite global log config

### ISSUE THREAD

**Issue by ericdevries** [dropwizard/dropwizard#5479]
I have a bunch of integration tests and unit tests, all setup according to the way the documentation specifies. However, when executing `mvn clean package` it runs the tests, and as soon as it has hit an integration test, it seems to completely overwrite the config that is supposed to be in logback.xml.

The sample output is this

```
[INFO] Running nl.knaw.dans.sword2.core.service.ZipServiceImplTest
[INFO] Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.909 s - in nl.knaw.dans.sword2.core.service.ZipServiceImplTest
[INFO] Running nl.knaw.dans.sword2.core.service.BagExtractorImplTest
[INFO] Tests run: 18, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.197 s - in nl.knaw.dans.sword2.core.service.BagExtractorImplTest
[INFO] Running nl.knaw.dans.sword2.core.service.BagItManagerImplTest
[INFO] Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.017 s - in nl.knaw.dans.sword2.core.service.BagItManagerImplTest
[INFO] Running nl.knaw.dans.sword2.core.service.FilesystemSpaceVerifierImplTest
[INFO] Tests run: 7, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.013 s - in nl.knaw.dans.sword2.core.service.FilesystemSpaceVerifierImplTest
[INFO] Running nl.knaw.dans.sword2.core.service.DepositHandlerImplTest
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.291 s - in nl.knaw.dans.sword2.core.service.DepositHandlerImplTest
[INFO] Running nl.knaw.dans.sword2.auth.SwordAuthenticatorTest
[INFO] Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.34 s - in nl.knaw.dans.sword2.auth.SwordAuthenticatorTest
[INFO] Running nl.knaw.dans.sword2.health.DiskSpaceHealthCheckTest
[INFO] Tests run: 4, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.021 s - in nl.knaw.dans.sword2.health.DiskSpaceHealthCheckTest
[INFO] Running nl.knaw.dans.sword2.health.FileSystemPermissionHealthCheckTest
[INFO] Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.008 s - in nl.knaw.dans.sword2.health.FileSystemPermissionHealthCheckTest
[INFO] Running nl.knaw.dans.sword2.health.QueueHealthCheckTest
[INFO] Tests run: 5, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.064 s - in nl.knaw.dans.sword2.health.QueueHealthCheckTest
[INFO] Running nl.knaw.dans.sword2.health.UploadDepositOnSameFileSystemHealthCheckTest
[INFO] Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.004 s - in nl.knaw.dans.sword2.health.UploadDepositOnSameFileSystemHealthCheckTest
[INFO] Running nl.knaw.dans.sword2.resource.ServiceDocumentResourceImplTest
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 2.369 s - in nl.knaw.dans.sword2.resource.ServiceDocumentResourceImplTest
[INFO] Running nl.knaw.dans.sword2.resource.BaseResourceTest
WARN  [2022-06-29 15:10:00,263] nl.knaw.dans.sword2.resource.BaseResource: Invalid content-length header: letter3
WARN  [2022-06-29 15:10:00,266] nl.knaw.dans.sword2.resource.BaseResource: Invalid content-length header: 123suffix
WARN  [2022-06-29 15:10:00,266] nl.knaw.dans.sword2.resource.BaseResource: Invalid content-length header: prefix123
```

The log statements at the end should not be there. The `ServiceDocumentResourceImplTest` creates a DropwizardAppExtension like so:

```
    private DropwizardAppExtension<DdSword2Configuration> EXT = new DropwizardAppExtension<>(
        DdSword2Application.class,
        ResourceHelpers.resourceFilePath("test-etc/config-servicedocument.yml")
    );
```

If one of the unit tests runs after this test runs, the configured logging that was active prior is no longer active. 

This means that there is some global logging config that runs inside the testing process and is configured multiple times, so the test order messes things up. Is there a way to prevent the DropwizardAppExtension from overwriting the global log config?

**Comment by zUniQueX** [comment]
Hi @ericdevries. Thanks for reporting this!

An integration test creates a new `Application`. In the constructor of this class the `bootstrapLogging()` method gets invoked, which changes the logback configuration according to the YAML file.

When an integration test shuts down, the logging configuration gets [reset](https://github.com/dropwizard/dropwizard/blob/release/2.1.x/dropwizard-testing/src/main/java/io/dropwizard/testing/DropwizardTestSupport.java#L266-L270). This doesn't mean the state prior to that reset gets restored. Instead, if the integration test provides a logging configuration (which probably is the case), the logback `LoggerContext` gets stopped and then [set up again](https://github.com/dropwizard/dropwizard/blob/release/2.1.x/dropwizard-logging/src/main/java/io/dropwizard/logging/DefaultLoggingFactory.java#L206-L216). Thereby a new console appender gets instantiated and registered to the root logger.

If no logging configuration is supplied, then only the appenders are stopped, but the configuration of the loggers remains in the current state.

To disable the logging for other tests after an integration test, you currently have to stop the `LoggerContext` manually to disable logging via logback:
```java
((LoggerContext)org.slf4j.LoggerFactory.getILoggerFactory()).stop();
```
If you don't want to completely disable logging, you could use the `reset()` method of the `LoggerContext`.
