### ISSUE TITLE
PropertyNamingStrategies in AnnotationSensitivePropertyNamingStrategy

### ISSUE THREAD

**Issue by gustavoms11** [dropwizard/dropwizard#5483]
Hello, I am upgrading a project to Java 17 and was resolving the dependency issues when I found this one.

I am also upgrading to DropWizard 2.1.0 to get the compatible jersey versions with some of our other integrations, then I run into this issue:

java.lang.NoClassDefFoundError: com/fasterxml/jackson/databind/PropertyNamingStrategies$SnakeCaseStrategy

Seeing the AnnotationSensitivePropertyNamingStrategy.class, it is using PropertyNamingStrategies from Jackson, however the DW2.1 is using Jackson 2.11 and this class is from Since 2.13.

I can just pick 2.13 in the classpath to override, however it is something to see.

**Comment by zUniQueX** [comment]
Hi @gustavoms11. Dropwizard 2.1.0 was released with Jackson 2.13.2.20220328, so it seems something is overriding your dependency there.

**Comment by gustavoms11** [comment]
It is very weird, since in the dependency tree is showing that is coming from the dropwizard jackson 2.1, I will try refresh de m2 cache then to see, however it is working if I inject directly which I intend to do anyways.

Thanks, will keep in touch if anything happens regarding this.
