### ISSUE TITLE
Multipart upload stopped working when updating from 2.1.0 to 2.1.1

### ISSUE THREAD

**Issue by christopher-cudennec** [dropwizard/dropwizard#5498]
Hi DW-Team! 🙂 

One of our tests stopped working after updating to Dropwizard 2.1.1. At first glance I thought it was caused by updating Jersey to 2.36 and created an issue in their repo: https://github.com/eclipse-ee4j/jersey/issues/5094

Then I found your update notes: https://www.dropwizard.io/en/latest/manual/upgrade-notes/upgrade-notes-2_1_x.html#modification-of-the-client-in-dropwizardappextension

Can you decide if there are more changes needed for migration? It does not seem to be 100% backwards compatible.

Cheers,

Christopher

**Edit:**

I could get my test running when I go back to the old client as documented in your upgrade notes. Do you think we should close this issue again?

**Comment by zUniQueX** [comment]
Hi @christopher-cudennec. I think the upgrade notes should be enough. It wasn't an optimal solution to introduce the connector in 2.1.1, but we had to do so for proper Java 17 support. Since we provided a workaround, users can easily mitigate the problem by using that.

**Comment by christopher-cudennec** [comment]
Thanks for clarification. If it helps with using Java 17 I really appreciate the change 🙂
