### ISSUE TITLE
Could not resolve dependencies for project io.dropwizard:dropwizard-example:jar:0.7.1-SNAPSHOT:

### ISSUE THREAD

**Issue by lagrwilson** [dropwizard/dropwizard#550]
I am trying to compile dropwizard 0.7.1 and I get the following error:

Failed to execute goal on project dropwizard-example: Could not resolve dependencies for project io.dropwizard:dropwizard-example:jar:0.7.1-SNAPSHOT: The following artifacts could not be resolved: io.dropwizard:dropwizard-core:jar:0.7.1-SNAPSHOT, io.dropwizard:dropwizard-auth:jar:0.7.1-SNAPSHOT, io.dropwizard:dropwizard-assets:jar:0.7.1-SNAPSHOT, io.dropwizard:dropwizard-spdy:jar:0.7.1-SNAPSHOT, io.dropwizard:dropwizard-hibernate:jar:0.7.1-SNAPSHOT, io.dropwizard:dropwizard-migrations:jar:0.7.1-SNAPSHOT, io.dropwizard:dropwizard-views-freemarker:jar:0.7.1-SNAPSHOT, io.dropwizard:dropwizard-views-mustache:jar:0.7.1-SNAPSHOT: Could not find artifact io.dropwizard:dropwizard-core:jar:0.7.1-SNAPSHOT in sonatype-nexus-snapshots (http://oss.sonatype.org/content/repositories/snapshots) -> [Help 1]

These files are not on sonatype-nexus-snapshots server.

**Comment by jaybholanath** [comment]
thanks buddy i have also this problem but after see youe suggestion i got an solution thanks
