### ISSUE TITLE
add ability to configure custom alive endpoints

### ISSUE THREAD

**Issue by richeyh** [dropwizard/dropwizard#5518]
Currently after the addition of the health-module into Dropwizard core it allows users to pass a list of [custom endpoints](https://github.com/dropwizard/dropwizard/blob/release/2.1.x/dropwizard-health/src/main/java/io/dropwizard/health/DefaultHealthFactory.java#L61) that it will also listen on. However, these endpoints all default to the readiness of the application unless you pass the `?type=alive` query param. It would be nice if you could configure another list of liveness endpoints that defaulted to the above behavior without the query param present. 

This would bring this project in line with [spring boots probe settings](https://spring.io/blog/2020/03/25/liveness-and-readiness-probes-with-spring-boot) and better in line with [k8s probes](https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/)

I'm happy to contribute the changes for this if the maintainers agree.

**Comment by richeyh** [comment]
Also needed as part of this and would be a follow on ask is support for Regex in the [name field of the HealthCheckConfiguration](https://github.com/dropwizard/dropwizard/blob/release/2.1.x/dropwizard-health/src/main/java/io/dropwizard/health/HealthCheckConfiguration.java#L14). Without that if you have a library that registers multiple checks for things like Kafka for example you could not mark all of the checks critical if you have multiple connections or have to enumerate every single connection for the application twice.

**Comment by pstackle** [comment]
Related to the original issue, I asked a question on the PR. 

For the follow-on ask:
Right now there is a simple 1:1 mapping between a registered `HealthCheck` and the configuration that determines if a given check is critical or not and whether the overall health of the app is healthy or not. Supporting a regex for the name seems like it would add a lot of complexity to the health evaluation. 

If you have a specific case where you want a whole set of HealthChecks to effectively be treated as a single one (i.e. all are marked critical and have the same schedule config), you could create a sort of aggregator `HealthCheck` that you register and configure once. That aggregator `HealthCheck` would have a collection of the relevant `HealthCheck`s and its `check()` method would just iterate over the collection of checks, call `check()` on each one, and then return a `Result` based on whether they were all healthy or if one or more of them were unhealthy. I think that would address your use case and wouldn't need to overcomplicate the existing health evaluation logic.

**Comment by richeyh** [comment]
Yeah, for the regex support you really only need to evaluate the regex once though. After you know the criticality of a check it doesn't have to change. This also makes the config easier for use cases where you have multiple checks registered from a library and want them all critical. This way if you had 5 http clients that all have health checks around them, you could simply use the regex and not have to enumerate each and every one twice. 

Ah yeah an Aggregate regex check could work for the above. The only downside is if you were manually checking your health check results you would not know which one is failing from the endpoint however that could be clarified with logging.

**Comment by pstackle** [comment]
Closing this issue for the same reasons as the associated PR.
