### ISSUE TITLE
overlapping use of jakarta.inject and jakarta.inject-api

### ISSUE THREAD

**Issue by mlilback** [dropwizard/dropwizard#5527]
jakarta.inject and jakarta.inject-api both include javax.inject classes. 

dropwizard-core depends on jersey-bean-validation and jersey-common which both depend on jakarta.inject. core also depends on dropwizard-jersey which depends on jakarta.inject-api. 

dropwizard-testing also uses jakarta-inject, while dropwizard-auth uses jakarta.inject-api.

I can use exclusions in my pom file to work around this, but dropwizard should be consistent on which one it uses across projects.

**Comment by joschi** [comment]
@mlilback Thanks for reporting this!

Would you be able to provide a PR against `release/2.1.x` with the respective exclusions?
`jakarta.inject:jakarta.inject-api` should be used everywhere and `org.glassfish.hk2.external:jakarta.inject` be excluded.
