### ISSUE TITLE
JerseyClientBuilder ignores most configuration settings

### ISSUE THREAD

**Issue by Zoroaster668** [dropwizard/dropwizard#557]
In io.dropwizard.client.JerseyClientBuilder, the "buildHandler" method ignores most settings that can be passed in from a ClientConfig (including but not limited to proxy settings), which makes those settings unusable in DropWizard.

I dug into the ApacheHttpClient4 source and found where they actually create the client handler object.  They do a bunch of logic based on various things in that ClientConfig to get the client set up properly that Dropwizard's JerseyClientBuilder does not - DW's version ignored most of that stuff.

I've got a new version of JerseyClientBuilder that includes that code.  This configures the client properly and allows the use of those features without (apparently) breaking anything else.  Pull request forthcoming; I'd appreciate comments on whether or not my fix looks like it might cause other problems or if I've missed something about how this was intended to work.

**Comment by arteam** [comment]
Closing via #558

Jersey client connector has been rewritten in 0.8.0 and should support all settings of the Apache Client.
