### ISSUE TITLE
Class visibility error in dropwizard-hibernate/src/main/java/io/dropwizard/hibernate/UnitOfWorkAwareProxyFactory.java

### ISSUE THREAD

**Issue by dwwarr** [dropwizard/dropwizard#5873]
Affects version 2.1.2 - caused by Pull Request https://github.com/dropwizard/dropwizard/pull/5748

I get the following error when starting my Dropwizard app:
```
Error in custom provider, java.lang.IllegalStateException: class io.dropwizard.hibernate.UnitOfWorkAwareProxyFactory$MethodInterceptor is not visible to class gov.ic.ngic.jpa.ContentDAO$ByteBuddy$cO9ricgr
...
```

The code causing this error is:
```java
       return new UnitOfWorkAwareProxyFactory(bundle).create(ContentDAO.class, SessionFactory.class,
                bundle.getSessionFactory());
```

I see that the inner class MethodInterceptor in UnitOfWorkAwareProxyFactory only has package visibility.

If I use Dropwizard 2.0.33, or 2.1.1, my application starts fine.

**Comment by zUniQueX** [comment]
Hi @dwwarr. I can confirm this problem. The `invoke` method also needs to be accessible.
