### ISSUE TITLE
Expose the policy object In CachingAuthenticator

### ISSUE THREAD

**Issue by psimonazzi** [dropwizard/dropwizard#5881]
In CachingAuthenticator (dropwizard-auth), it would be useful to expose the cache policy config (using Caffeine `cache.policy()` method), in order to change the configuration at runtime (for example to change the expiration time).
Currently the `cache` object has private access.

**Comment by zUniQueX** [comment]
Hi @psimonazzi. This sounds interesting, but I just cannot imagine where it would be useful to change the expiration time at runtime. Do you have a specific use case for this?

**Comment by psimonazzi** [comment]
Hi, we have a middleware-like application where we would like to provide our users a UI screen to edit the cache settings, since usually they cannot access the config file and restart the server.

**Comment by zUniQueX** [comment]
@psimonazzi Okay, makes sense to me. But I don't know, if this would be helpful for many users.

If we expose the policy object, the values of the cache can be retrieved. At the moment, we restrict access to invalidation of entries. I don't think we'd want to provide full access to the values.

**Comment by zUniQueX** [comment]
In order to keep the current limited access, I don't think we'd want to provide access to the policy.

Since it's easy to provide a custom implementation doing this, I think you can provide this without an implementation of the framework.
