### ISSUE TITLE
Documentation on "Testing Serialization" appears to have an error.

### ISSUE THREAD

**Issue by sfitts** [dropwizard/dropwizard#603]
The code given in the most recent version of the documentation on "Testing Serialization" which can be found at either:

* https://github.com/dropwizard/dropwizard/blob/master/docs/source/manual/testing.rst
* http://dropwizard.readthedocs.org/en/latest/manual/testing.html

does not appear to actually work.  The documentation states that the JSON comparison will be done on a normalized form, but AFAICT it is actually compared as-is, resulting in a failure due to whitespace differences.

The method `JSonHelpers#jsonFixture` used to perform this normalization, but that class has been removed.  You can see its use documented here -- http://dropwizard.github.io/dropwizard/manual/testing.html.  I'm not sure if the method was moved elsewhere or if it is truly gone.  The method was equivalent to:

```
MAPPER.writeValueAsString(MAPPER.readValue(fixture("fixtures/person.json"), JsonNode.class))
```

Comparing against this value instead of simply `#fixture` appears to work as expected.

**Comment by babyman** [comment]
I am following the posted testing guide and can confirm this is still an issue, it would be helpful if the documentation or the code was fixed as right now the mismatch causes confusion to people ( could be just me o_O ) trying to learn how best to use dropwizard.

**Comment by carlo-rtr** [comment]
This code came from the docs
```
package com.example.helloworld.core;

import com.fasterxml.jackson.databind.ObjectMapper;
import io.dropwizard.jackson.Jackson;
import org.junit.Test;
import static io.dropwizard.testing.FixtureHelpers.fixture;
import static org.assertj.core.api.Assertions.assertThat;

public class PersonTest {
    private static final ObjectMapper MAPPER = Jackson.newObjectMapper();

    @Test
    public void deserializesFromJSON() throws Exception {
        final Person person = new Person("Luther Blissett", "lb@example.com");
        assertThat(MAPPER.readValue(fixture("fixtures/person.json"), Person.class))
                .isEqualTo(person);
    }
}
```

the formatting of the json file doesn't matter, as long as it's valid json. @joschi comment early is relevant, you need to do object equality.
