### ISSUE TITLE
JacksonMessageBodyProvider throws exception when post body is null

### ISSUE THREAD

**Issue by gedl** [dropwizard/dropwizard#625]
JacksonMessageBodyProvider in Dropwizard 0.6 allowed null post bodies. As a result, the resource methods would get a "default" instance (calling the default constructor) of the parameter type.

However in 0.7, JacksonMessageBodyProvider throws an exception and the resource method never gets called. Posting {} reverts to the old behaviour.

Because our application is now expecting the old behaviour (i.e. accepted null post bodies reverting to default constructors on resource methods) in multiple places (namely many client applications) changing all the calls is likely to be a nightmare.

Is there any way we can workaround this? Expected behaviour is to get null or an instance of the parameter created with the default constructor.

Thanks.

**Comment by chrislbs** [comment]
In case someone came here like me trying to resolve a similar issue and can't upgrade the dropwizard version to the latest immediately. I tried using @gedl workaround but it made the assumption that .available() would always return non-zero. I made a modification to just go ahead and copy the entity stream to a byte array regardless to ensure we truly know if anything is on the input stream.

https://gist.github.com/chrislbs/b64a9346db07840076b8
