### ISSUE TITLE
UnitOfWorkAwareFactory can lead to java.lang.OutOfMemoryError: Metaspace

### ISSUE THREAD

**Issue by DanyBv** [dropwizard/dropwizard#6263]
A new class is added to the classpath each time the UnitOfWorkAwareFactory create method is called. If multiple proxies of the same class are needed, there will be as many classes added to the classpath as the number of proxies created. Over time, the jvm's metaspace can fill up and in our case can lead to `java.lang.OutOfMemoryError: Metaspace`. This is a regression since https://github.com/dropwizard/dropwizard/pull/5748.

**Comment by zUniQueX** [comment]
Hi @DanyBv, thanks for reporting this!

Javassist indeed uses an internal cache by default while ByteBuddy doesn't.

I'm assuming its a rather rare case where this would cause problems, but a simple cache would do the job and should be easy to integrate.
