### ISSUE TITLE
Problem with setting port on command line

### ISSUE THREAD

**Issue by philion** [dropwizard/dropwizard#636]
According to SimpleServerFactory docs:

> A startup script can override the port via {@code -Ddw.server.connector.port=$PORT}.

However, when I try:

    java -Ddw.server.connector.port=8081 -jar my.jar server config.yml

I get:

> config.yml has an error:
>  Failed to parse configuration at: server.connector; Unexpected token (END_OBJECT), expected FIELD_NAME: missing property 'type' that is to contain type id  (for class io.dropwizard.jetty.ConnectorFactory)
> at [Source: N/A; line: -1, column: -1] (through reference chain: com.acmerocket.stratum.StratumConfiguration["server"]->io.dropwizard.server.SimpleServerFactory["connector"])

Without `-Ddw.server.connector.port=8081`, the app comes up fine.

**Comment by swapanshridhar** [comment]
**I was able to get it working like this :**

`java -Ddw.server.applicationConnectors\[0\].type="http"  -Ddw.server.applicationConnectors\[0\].port="8080" -jar target/<UR_JAR>.jar server conf.yml`

**Dropwizard Version:**

`<dropwizard.version>1.3.8</dropwizard.version>`

**Comment by prakharrke** [comment]
> **I was able to get it working like this :**
> 
> `java -Ddw.server.applicationConnectors\[0\].type="http" -Ddw.server.applicationConnectors\[0\].port="8080" -jar target/<UR_JAR>.jar server conf.yml`
> 
> **Dropwizard Version:**
> 
> `<dropwizard.version>1.3.8</dropwizard.version>`

Did you also declare applicationConnectors in your yaml file too?

**Comment by karussell** [comment]
The PR #866 does not seem to fix this problem here (tried dropwizard version 1.3.12). I.e. you have to specify a config.yml with at least:

```
server:
  applicationConnectors:
   - type: http
```

in order to change the port.
