### ISSUE TITLE
Make it possible to override Jetty ErrorHandler

### ISSUE THREAD

**Issue by ptomli** [dropwizard/dropwizard#647]
In DW 0.6 there was `com.yammer.dropwizard.jetty.UnbrandedErrorHandler`. In DW 0.7, `AbstractServerFactory#buildServer` creates an instance of `org.eclipse.jetty.server.handler.ErrorHandler` directly, and configures it into the locally scoped `Server` instance. This `Server` instance gets passed back to `DefaultServerFactory#build`, and then back to `ServerCommand#run`, where it ends its scope.

Previously, overriding the behaviour of `ErrorHandler` was as simple as just declaring another `UnbrandedErrorHandler` class in the right package and making sure it was earlier in the class path than the DW supplied version. Unconventional, untidy, but simple.

Now, it appears that the only sensible way to override this would be by creating a custom `ServerFactory` and then override/reimplement some code from `AbstractServerFactory`.

Would it not be far simpler to allow `AbstractServerFactory` to either:

  * provide a template method, returning an instance of `ErrorHandler`, to allow simpler overriding of this very important feature (i.e.: design `AbstractServerFactory` for subclassing)
  * be provided with a class name, in configuration, of the `ErrorHandler` to use (IoC/DI)

Overriding the various error mechanisms DW has to deal with (Jetty `ErrorHandler`, Jersey `ExceptionMapper`) has come up a number of times

**Comment by carlo-rtr** [comment]
The code in commit 4c31dba5f33 seems reasonable. Can you submit a PR after rebasing master? My only tweak is to call out in docs that errorhandler needs a zero arg constuctor

**Comment by marcohu** [comment]
I'm new to Dropwizard and still trying to find my way so I might be missing something (or it has been a recent development?), but as of DW 0.8.1 it seems possible to customize error pages with relative ease:

```java
public void run(Configuration config, Environment env)
{
    ...
    env.getAdminContext().setErrorHandler(new CustomErrorHandler());
    env.getApplicationContext().setErrorHandler(new CustomErrorHandler());
}
```

Not too bad, but having the ability to declare the handler in the configuration would be great!

**Comment by ptomli** [comment]
As@marcohu points out, it's now possible to register an ErrorHandler via the application context. For my purposes this is enough in the core, no need to add more knobs and buttons.
