### ISSUE TITLE
Docs: Wrong link to Maven: The Complete Reference

### ISSUE THREAD

**Issue by MaiHameed** [dropwizard/dropwizard#6673]
The [Maven: The Complete Reference](https://www.sonatype.com/ebooks) in your [getting started page](https://www.dropwizard.io/en/latest/getting-started.html#setting-up-using-maven) points to https://www.sonatype.com/ebooks instead of (what I assume to correctly be) https://books.sonatype.com/mvnref-book/reference/index.html

**Comment by zUniQueX** [comment]
Hi @MaiHameed. Thanks for reporting this!

Would you mind creating a PR for the doc update?

**Comment by joschi** [comment]
@MaiHameed Thanks for reporting this!
