### ISSUE TITLE
com.codahale.metrics.WeightedSnapshot$WeightedSample objects not being garbage collected

### ISSUE THREAD

**Issue by escion** [dropwizard/dropwizard#6697]
Hi guys, I'm using micrometer jmx registry to send metrics (specifically a timer) to JMX beans. 
Profiling my application, I see that com.codahale.metrics.WeightedSnapshot$WeightedSample objects increase without being garbage collected; is it normal? same for java.util.concurrent.ConcurrentSkipListMap$Node.
jmx registry uses timer with default ExponentiallyDecayReservoir which it should be the most efficient in terms of memory consumption/GC; my test was stressing my app with 70req/s (the exact rate of my production app).
Any idea?

Thanks a lot

Alessandro

**Comment by zUniQueX** [comment]
Hi @escion. Dropwizard metrics has its own GitHub project. Please start a thread at the issue or discussion board there.
