### ISSUE TITLE
Regex in @Path matches only only 1 of 2 two routes specified, resulting in 404

### ISSUE THREAD

**Issue by govindrai** [dropwizard/dropwizard#6708]
Here is what dropwizard logs to the console in terms configured resources and their paths:

```
INFO  [07:07:13.741] i.d.jersey.DropwizardResourceConfig: The following paths were found for the configured resources:

    DELETE  /apps/affiliate/internal/v1/templates/ (aff.affiliate.http.internal.AffiliateURLTemplatesInternalAPIEndpoint)
    GET     /apps/affiliate/internal/v1/templates/ (aff.affiliate.http.internal.AffiliateURLTemplatesInternalAPIEndpoint)
    POST    /apps/affiliate/internal/v1/templates/ (aff.affiliate.http.internal.AffiliateURLTemplatesInternalAPIEndpoint)
    GET     /apps/affiliate/v1/generate-url (aff.affiliate.http.AffiliateEndpoint)
    GET     /apps/affiliate/v1/redirect-search-url (aff.affiliate.http.AffiliateEndpoint)
    GET     /openapi.{type:json|yaml} (io.swagger.v3.jaxrs2.integration.resources.OpenApiResource)
    GET     /{path: apps/affiliate/v1/redirect|api/affiliate/v1/redirect} (aff.affiliate.http.RedirectEndpoint)
```
The problem is with the last path, specified as a regular expression.

My expectation is that it should trigger for incoming requests to both /apps/affiliate/v1/redirect and /api/affiliate/v1/redirect.

However, visiting `/apps/affiliate/v1/redirect` results in a `404`, but visiting `/api/affiliate/v1/redirect` results in a 200. How can I get resource to respond to either of those paths?

**Comment by zUniQueX** [comment]
Hi @govindrai. Dropwizard doesn't handle the `@Path` annotations. This is done by Jersey. [Their documentation](https://eclipse-ee4j.github.io/jersey.github.io/documentation/latest/jaxrs-resources.html#d0e2082) explains the code 404 will be returned, if the path isn't found.

I've just recognized your first path has a typo in it. If you've just copied it, this could already be the issue.

**Comment by govindrai** [comment]
@zUniQueX Thanks for the response! Correct, if the path isn't found I also expect a 404. But not sure why the path isn't found. 

Sorry about the typo. That's just me manually typing out my expectation. I've updated the original question to correct the typo.

**Comment by zUniQueX** [comment]
@govindrai If that wasn' the error, the Jersey team probably can help you better since this library evaluates the paths.

**Comment by zUniQueX** [comment]
Closing this in favor of https://github.com/eclipse-ee4j/jersey/issues/5263
