### ISSUE TITLE
DropwizardApacheConnector to support setting proxy from JerseyClientRequest

### ISSUE THREAD

**Issue by tomaszzasada** [dropwizard/dropwizard#6758]
Setting `ClientProperties.PROXY_URI` in Jersey client **does not** result in setting the proxy in underlaying RequestConfig of http client.

So something like this **is not supported**:
```
client.target(...)
.request(MediaType.APPLICATION_JSON)
.property(ClientProperties.PROXY_URI, "....")
...
```
It would be great if it was...

**Comment by zUniQueX** [comment]
Hi @tomaszzasada. We don't evaluate the Jersey client property for the proxy uri, but you can set a proxy via the `#using(HttpClientConfiguration)` method.
