### ISSUE TITLE
Junit4 / Grizzly2 on 2.1.5

### ISSUE THREAD

**Issue by johnv-git** [dropwizard/dropwizard#6783]
Just updated from 2.1.4 to 2.1.5, with a legacy junit4 test environment I needed to add `junit-vintage-engine` to get tests to run.  This is because the junit5/jupiter deps come in via the new `org.glassfish.jersey.test-framework.providers:jersey-test-framework-provider-grizzly2:jar:2.39:test`.  They did not in 2.37.  No big deal, just documenting for anyone else in the same situation.

```
        <!-- run junit4 tests in a junit5 world -->
        <dependency>
            <groupId>org.junit.vintage</groupId>
            <artifactId>junit-vintage-engine</artifactId>
        </dependency>
```

Thanks!

**Comment by joschi** [comment]
@johnv-git Thanks for pointing this out!

I've added this to the release notes of Dropwizard 2.1.5:
- https://github.com/dropwizard/dropwizard/discussions/6734
- https://github.com/dropwizard/dropwizard/releases/tag/v2.1.5

> [Jersey 2.38](https://github.com/eclipse-ee4j/jersey/releases/tag/2.38) migrated from JUnit 4.x to JUnit Jupiter (JUnit 5.x): https://github.com/eclipse-ee4j/jersey/pull/5123
> 
> If you're still using JUnit 4.x in your projects, you might need to include `org.junit.vintage:junit-vintage-engine` for running JUnit 4 tests on the JUnit Platform.
> 
> ```xml
> <dependency>
>     <groupId>org.junit.vintage</groupId>
>     <artifactId>junit-vintage-engine</artifactId>
>     <scope>test</scope>
> </dependency>
> ```
> 
> See also [JUnit 5 User Guide - Migrating from JUnit 4](https://junit.org/junit5/docs/5.9.2/user-guide/#migrating-from-junit4).
