### ISSUE TITLE
When initialOverallState=false, the HTTP response code to readiness check is always 503

### ISSUE THREAD

**Issue by raymondchen625** [dropwizard/dropwizard#6794]
When I have `initialOverallState: false` set in my `health` configuration, the HTTP request to the health check endpoint `/health-check` always returns `503` response code, no matter what the actual statuses of my health checks are. For example, it will give a `503` response code with a `healthy:true` in the response body like this:
```
curl -LSi 'localhost:8080/health-check?type=ready&name=mycheck'
HTTP/1.1 503 Service Unavailable
Date: Sat, 11 Mar 2023 00:00:07 GMT
Cache-Control: no-store
Content-Type: application/json
Content-Length: 74

[{"name":"mycheck","healthy":true,"type":"READY","critical":false}]
```

I read the code and the problems seems to be related to the class `io.dropwizard.health.HealthCheckManager`:
- When `initialOverallState` is set to `false`, the state `isAppHealthy` [is initialized as `false`](https://github.com/dropwizard/dropwizard/blob/a6af1e088b53e0a9a7c670949a5dcd448cbd889f/dropwizard-health/src/main/java/io/dropwizard/health/HealthCheckManager.java#L30-L30).
- When the last failed health check becomes healthy, it's supposed to set both `isAppAlive` and `isAppHealthy` to true. But:
  - If it's an `alive` check, the method [handleCriticalHealthChange()](https://github.com/dropwizard/dropwizard/blob/a6af1e088b53e0a9a7c670949a5dcd448cbd889f/dropwizard-health/src/main/java/io/dropwizard/health/HealthCheckManager.java#L166-L166) is called. Because its type is `ALIVE`, only the state [`isAppAlive` is updated](https://github.com/dropwizard/dropwizard/blob/a6af1e088b53e0a9a7c670949a5dcd448cbd889f/dropwizard-health/src/main/java/io/dropwizard/health/HealthCheckManager.java#L166-L166).
  - If it's a `ready` check, the method [handleNonCriticalHealthChange()](https://github.com/dropwizard/dropwizard/blob/a6af1e088b53e0a9a7c670949a5dcd448cbd889f/dropwizard-health/src/main/java/io/dropwizard/health/HealthCheckManager.java#L202-L202) is called. It [only logs a message](https://github.com/dropwizard/dropwizard/blob/a6af1e088b53e0a9a7c670949a5dcd448cbd889f/dropwizard-health/src/main/java/io/dropwizard/health/HealthCheckManager.java#L204) and doesn't change either `isAppAlive` or `isAppHealthy` state.
So in any of these cases, the `isAppHealthy` is never set to `true`
- Because of this, the method [isHealthy()](https://github.com/dropwizard/dropwizard/blob/a6af1e088b53e0a9a7c670949a5dcd448cbd889f/dropwizard-health/src/main/java/io/dropwizard/health/HealthCheckManager.java#L227-L227) never returns `true`. So [the code in JsonHealthResponseProvider](https://github.com/dropwizard/dropwizard/blob/a6af1e088b53e0a9a7c670949a5dcd448cbd889f/dropwizard-health/src/main/java/io/dropwizard/health/response/JsonHealthResponseProvider.java#L63-L72) always gets `healthy=false` and returns `503`.

Dropwizard version `2.1.5`

**Comment by joschi** [comment]
@raymondchen625 Thanks for reporting this!

The bug will be fixed in the next release of Dropwizard 2.1.x and later.
