### ISSUE TITLE
Wrong version for http2-hpack

### ISSUE THREAD

**Issue by danjee** [dropwizard/dropwizard#6929]
After upgrading to dw 4.0.0 I get the following error:

java.lang.NoClassDefFoundError: org/eclipse/jetty/util/Trie

The error is fixed by manually using the dependency:

https://mvnrepository.com/artifact/org.eclipse.jetty.http2/http2-hpack/11.0.14

**Comment by zUniQueX** [comment]
Hi @danjee. Could you please provide more detail for this? We migrated from the `ArrayTernaryTrie` to `Index`. I don't know an other use of `Trie` in our code.

**Comment by joschi** [comment]
@danjee Please post the output of `mvn dependency:tree` or `./gradlew dependencies` (run on your Dropwizard project).

**Comment by joschi** [comment]
@danjee Any news on this?

**Comment by danjee** [comment]
Sorry for this. The issue was on my side due to a transitive dependency.
