### ISSUE TITLE
Map uriPath without ending slash

### ISSUE THREAD

**Issue by fredrikoe** [dropwizard/dropwizard#696]
Let's say I've got my Swagger docs at http://localhost:9000/swagger/index.html. I'd like to map the following to index.html as well:
http://localhost:9000/swagger/
http://localhost:9000/swagger
The former works. I'm doing the following bootstrapping:
bootstrap.addBundle(new AssetsBundle("/swagger", "/swagger", "index.html", "swaggerAssets"));

But http://localhost:9000/swagger gives a HTTP error 500. And looking at the source code (Dropwizard 0.7.1) for AssetBundle it looks like a slash is added at the end if it's not there:
this.uriPath = uriPath.endsWith("/") ? uriPath : (uriPath + '/');

Is there a reason for adding this slash? So this means it's not possible to map http://localhost:9000/swagger or is there another way?

**Comment by carlo-rtr** [comment]
@nbauernfeind approach makes sense
