### ISSUE TITLE
FuzzyEnumModule validation against enum name() instead of toString() breaks compatibility with jsonschema2pojo

### ISSUE THREAD

**Issue by clintfoster** [dropwizard/dropwizard#699]
Since upgrading from DW 0.6.2 to 0.7.1 I'm getting the following error deserializing enum values in POJOs generated by [jsonschema2pojo](https://github.com/joelittlejohn/jsonschema2pojo):

    partlyCloudy was not one of [PARTY_CLOUDY, CLEAR]

This is happening with a field in a class generated by jsonschema2pojo. When jsonschema2pojo sees a field in a JSON schema that is declared as an enum...

    "weather": {
        "enum": [ "partlyCloudy", "clear"]
    },

It generates a Java enum like this:

    public static enum Weather {
        PARTY_CLOUDY("partlyCloudy"),
        CLEAR("clear");
        private final String value;

        private Weather(String value) {
            this.value = value;
        }

        @JsonValue
        @Override
        public String toString() {
            return this.value;
        }
    }

But FuzzyEnumModule.deserialize() is calling name() instead of toString() on the enum to compare its value to the deserialized value, and the literal enum name "PARTLY_CLOUDY" doesn't match the deserialized value "partlyCloudy". Changing FuzzyEnumModule to use toString() might break existing code (although presumably that's what the old deserializer did). If that's not feasible, would it be possible to provide a configuration option to make FuzzyEnumModule be even more fuzzy and call toString()? Either that, or is there a way to specify that the standard deserializer should be used?

**Comment by jontejj** [comment]
This should depend on com.fasterxml.jackson.databind.DeserializationFeature.READ_ENUMS_USING_TO_STRING being enabled or not in the object mapper?

**Comment by brentryan** [comment]
The read enums using to string is a global config which isn't always true.  We have a mix-match use where sometimes we need to string and sometimes JsonCreator.  I already have a PR that fixes this with unit tests.

https://github.com/dropwizard/dropwizard/pull/1220

**Comment by philandstuff** [comment]
In Jackson 2, `@JsonValue` is used to mark a method to serialize to, but also (as a special case) is used to mark how enums should deserialize. From the [javadoc for @JsonValue](http://fasterxml.github.io/jackson-annotations/javadoc/2.5/com/fasterxml/jackson/annotation/JsonValue.html):

> NOTE: when use for Java enums, one additional feature is that value returned by annotated method is also considered to be the value to deserialize from, not just JSON String to serialize as. This is possible since set of Enum values is constant and it is possible to define mapping, but can not be done in general for POJO types; as such, this is not used for POJO deserialization.

Rather than consuming toString, would it make sense to consume this annotation in FuzzyEnumModule as well to maintain compatibility with base Jackson?  Without this, enums that deserialize correctly in raw Jackson will throw JsonMappingException when FuzzyEnumModule is added.

**Comment by jplock** [comment]
Has this been fixed by #1340?

**Comment by nickbabcock** [comment]
Closed by #1220/#1340
