### ISSUE TITLE
ConnectionKeepAliveStrategy didn't use a keepAlive value from HttpClientConfiguration

### ISSUE THREAD

**Issue by nsclass** [dropwizard/dropwizard#7026]
Since default value of connectionKeepAlive value in `RequestConfig` is 3 minutes, the following logic will always have 3 minutes for `TimeValue duration` if server didn't return `keep-alive` in HTTP response.

```java
public TimeValue getKeepAliveDuration(HttpResponse response, HttpContext context) {
                    final TimeValue duration = super.getKeepAliveDuration(response, context);
                    return (duration.getDuration() == -1) ? TimeValue.ofMilliseconds(keepAlive) : duration;
                }
```
RequestConfig in Apache HTTP client.

https://github.com/apache/httpcomponents-client/blob/master/httpclient5/src/main/java/org/apache/hc/client5/http/config/RequestConfig.java#L46

It may miss this logic `.setConnectionKeepAlive(keepAlive > 0 ? TimeValue. ofMilliseconds(keepAlive) : null)` in below code?

https://github.com/dropwizard/dropwizard/blob/release/4.0.x/dropwizard-client/src/main/java/io/dropwizard/client/HttpClientBuilder.java#L370

```java
        final long keepAlive = configuration.getKeepAlive().toMilliseconds();

        final RequestConfig requestConfig
                = RequestConfig.custom().setCookieSpec(cookiePolicy)
                .setResponseTimeout(timeout, TimeUnit.MILLISECONDS)
                .setConnectionKeepAlive(keepAlive > 0 ? TimeValue. ofMilliseconds(keepAlive) : null)
                .setConnectTimeout(connectionTimeout, TimeUnit.MILLISECONDS)
                .setConnectionRequestTimeout(connectionRequestTimeout, TimeUnit.MILLISECONDS)
                .build();
```

This is causing a HTTP call error when Dropwizard HTTP client is trying to communicate with Dropwizard HTTP server since Dropwizard HTTP server's default idle timeout is 30 seconds. After 30 seconds, subsequent HTTP requests will fail from Drowizard HTTP client.

**Comment by zUniQueX** [comment]
Hi @nsclass. When looking where the result of this call [is used](https://github.com/search?q=repo%3Aapache%2Fhttpcomponents-client%20getConnectionKeepAlive()&type=code), setting this value only for the `DefaultConnectionKeepAliveStrategy` feels like a duplication. Maybe we can emulate the behavior of [HttpClient 4.5.x](https://github.com/apache/httpcomponents-client/blob/4.5.x/httpclient/src/main/java/org/apache/http/impl/client/DefaultConnectionKeepAliveStrategy.java#L70) and always set the value to `-1` to use the user-provided value through our [custom `DefaultConnectionKeepAliveStrategy`](https://github.com/dropwizard/dropwizard/blob/release/4.0.x/dropwizard-client/src/main/java/io/dropwizard/client/HttpClientBuilder.java#L393-L399) instead.

**Comment by nsclass** [comment]
applied changes as suggested in PR. Please have a look.
https://github.com/dropwizard/dropwizard/pull/7027/files
