### ISSUE TITLE
Don't take over logging configuration or make it possible to override it

### ISSUE THREAD

**Issue by jnaous** [dropwizard/dropwizard#703]
This makes it difficult to configure loggers in tests that use the DropwizardApplicationRule. Also if there's anything that happens in main that requires logging after shutting down dropwizard, all that logging is swallowed since the logging factory is stopped.

**Comment by carlo-rtr** [comment]
https://github.com/dropwizard/dropwizard/pull/996

**Comment by davideanastasia** [comment]
+1

**Comment by carlo-rtr** [comment]
closed by 847275afd08b217bd98c633c6c7c2d1ab84b8cc0
