### ISSUE TITLE
DropwizardResourceConfig does not support reload

### ISSUE THREAD

**Issue by jnaous** [dropwizard/dropwizard#704]
I am building an extension framework on top of dropwizard that requires the resource config to be reloaded. Unfortunately, Dropwizard extends ScanningResourceConfig unnecessarily, and does not init it properly, which causes a NullPointerException when ResourceConfig.onReload() is called. Instead, DropwizardResourceConfig should probably extend DefaultResourceConfig.

**Comment by joschi** [comment]
@jnaous Any news on this? Could you reproduce it with Dropwizard 0.8.0-rc1 or 0.8.0-rc2?

**Comment by jnaous** [comment]
Hi Jochen, Is there a maven repo I can use for prebuilt binaries to check?
Thanks.

**Comment by joschi** [comment]
@jnaous Both release candidates are available on Maven Central: http://mvnrepository.com/artifact/io.dropwizard

**Comment by carlo-rtr** [comment]
@jnaous if you can confirm this is an issue, feel free to reopen.
