### ISSUE TITLE
Support to know what bundles are already added to bootstrap

### ISSUE THREAD

**Issue by swayamraina** [dropwizard/dropwizard#7154]
Currently the [Bootstrap.class](https://github.com/dropwizard/dropwizard/blob/release/4.0.x/dropwizard-core/src/main/java/io/dropwizard/core/setup/Bootstrap.java) has List of configured bundles but does not expose a getter to know what all bundles are already added.
```
private final List<ConfiguredBundle<? super T>> configuredBundles;
```
Also while adding a bundle it does not check if it is already initialised or added or not
```
public void addBundle(ConfiguredBundle<? super T> bundle) {
        bundle.initialize(this);
        this.configuredBundles.add(bundle);
}
```
Exposing this getter will let users know if they are not re-adding the same bundle
Also DW should throw error or warning if a user tries to add same bundle again.

**Comment by pstackle** [comment]
Hi @swayamraina, 
Can you elaborate on your use case for being able to get a list of configured bundles? 

> Also while adding a bundle it does not check if it is already initialised or added or not
> Also DW should throw error or warning if a user tries to add same bundle again.

There are not currently any limitations imposed by Dropwizard with respect to only allowing one instance of a particular kind of bundle and I don't think it makes sense to create that limitation. 

Can you explain more about how you see that working (on what attribute would you impose the uniqueness constraint) and why you don't think that would impose an unnecessary limitation on bundles that can be registered multiple times now?

**Comment by joschi** [comment]
> Also DW should throw error or warning if a user tries to add same bundle again.

No, it is an explicit feature that you can add a bundle multiple times.

Usually that's done with different configurations and not the exact same bundle instance.

For example, you can add the [`HibernateBundle`](https://javadoc.io/static/io.dropwizard/dropwizard-hibernate/3.0.0/io/dropwizard/hibernate/HibernateBundle.html) multiple times to support different sets of database configurations (e. g. primary & read-replicas).
