### ISSUE TITLE
Health configuration

### ISSUE THREAD

**Issue by danjee** [dropwizard/dropwizard#7253]
I am currently working on upgrading our application to use dropwizard 4. In the last version we used the `HealthCheckBundle` that is now missing from this repo. I've addressed this issue on the dropwizard-health repo but it is now archived: https://github.com/dropwizard/dropwizard-health/issues/167

**Comment by joschi** [comment]
`dropwizard-health` is part of the upstream project (*this* repository) since Dropwizard 2.1.0. 😉 

- https://github.com/dropwizard/dropwizard/discussions/5317
- https://www.dropwizard.io/en/release-4.0.x/manual/core.html#health
