### ISSUE TITLE
Custom error page for AssetsBundle

### ISSUE THREAD

**Issue by Zinurist** [dropwizard/dropwizard#7324]
I'm upgrading  dropwizard from a 2.0.x release to 3.0.1, and noticed that the error page handler doesn't work anymore.

Before, you could set an error page handler like this:
```java
ErrorPageErrorHandler epeh = new ErrorPageErrorHandler();
epeh.addErrorPage(404, "/error404.html");
environment.getApplicationContext().setErrorHandler(epeh);
```
Also explained for example in https://github.com/dropwizard/dropwizard/issues/1461. Something like `http://localhost:8080/rubish.html` would then server `error404.html` from the assets.

This doesn't work anymore. I think [this commit](https://github.com/dropwizard/dropwizard/commit/9c49061deacf38c4acaeac7fd33a6360dbca3355) is the reason (added in dropwizard 2.1.0), since AssetServlet doesn't send an error anymore, but instead just sets the status code. [Documentation for setStatus](https://docs.oracle.com/javaee/6/api/javax/servlet/http/HttpServletResponse.html#setStatus(int)) also mentions this:
```
If this method is used to set an error code, then the container's error page mechanism will not be triggered.
If there is an error and the caller wishes to invoke an error page defined in the web application,
then sendError(int, java.lang.String) must be used instead.
```

Was this an intended change? Is there a better alternative for the error page handler?

**Comment by Zinurist** [comment]
My solution for now is to inherit AssetsBundle and implement the previous behavior (kotlin code):
```kotlin
class SPAAssetsBundle(resourcePath: String, uriPath: String, indexFile: String, assetsName: String) :
	AssetsBundle(resourcePath, uriPath, indexFile, assetsName) {
	override fun createServlet(): AssetServlet {
		return SPAAssetServlet(resourcePath, uriPath, indexFile, defaultMediaType, StandardCharsets.UTF_8)
	}
}

class SPAAssetServlet(resourcePath: String, uriPath: String, indexFile: String?, defaultMediaType: String?, defaultCharset: Charset?) :
	AssetServlet(resourcePath, uriPath, indexFile, defaultMediaType, defaultCharset) {
	override fun doGet(req: HttpServletRequest, resp: HttpServletResponse) {
		super.doGet(req, resp)
		if (resp.status == HttpServletResponse.SC_NOT_FOUND) {
			resp.sendError(HttpServletResponse.SC_NOT_FOUND)
			// or do something else...
		}
	}
}
```
Would also allow for more complex error handling.

**Comment by zUniQueX** [comment]
Hi @Zinurist. The problem of using `sendError` instead of `setStatus` is that not catching exceptions like `IOException` would lead to information exposure through the servlet container's error page mechanism. Therefore we decided to use `setStatus` to keep Dropwizard safe in the default configuration.

If you want to use custom error pages through the container's error page mechanism, you can restore the previous behaviour yourself. `setStatus` doesn't commit the response, so you can modify it afterwards. The following code snippet provides a very simple `Filter` that resets the response and uses `sendError` to trigger the error pages:
```java
environment.servlets().addFilter("sendError", new Filter() {
            @Override
            public void doFilter(ServletRequest servletRequest, ServletResponse servletResponse, FilterChain filterChain) throws IOException, ServletException {
                filterChain.doFilter(servletRequest, servletResponse);
                if (!(servletResponse instanceof HttpServletResponse)) {
                    throw new IllegalStateException("Expecting instance of HttpServletResponse");
                }
                HttpServletResponse httpServletResponse = (HttpServletResponse) servletResponse;
                int status = httpServletResponse.getStatus();
                if (!httpServletResponse.isCommitted() && httpServletResponse.getStatus() >= 400) {
                    httpServletResponse.reset();
                    httpServletResponse.sendError(status);
                }
            }
        }).addMappingForUrlPatterns(EnumSet.of(DispatcherType.REQUEST), true, "/*");
```

**Comment by Zinurist** [comment]
Thank you for the help! Closing the issue since I was able to work around it.
