### ISSUE TITLE
Bundles run for ConfiguredCommand and Command

### ISSUE THREAD

**Issue by oillio** [dropwizard/dropwizard#744]
I would like to be able to specify that some of my bundles be run before a ConfiguredCommand or Command is run, when I don't need the entire environment built up.

I would be happy to provide a pull request, if this would fit in with the project.
The way I would like to implement it:
Add additional Bundle interfaces so that we have 4 versions:
- Bundle has a run that takes no arguments
- ConfiguredBundle's run takes a configuration
- EnvironmentBundle's run takes a configuration and an environment
- ServerBundle's run is a duplicate of EnvironmentBundle

A Command will call run on any Bundles.
A ConfiguredCommand will run all ConfiguredBundles and all Bundles.
etc.

Would this be acceptable?

There is a problem with backwards compatibility, however.  The currently existing ConfiguredBundle would be an EnvironmentBundle in the above naming scheme.

**Comment by jplock** [comment]
I believe this is addressed by https://github.com/dropwizard/dropwizard/pull/1360

**Comment by joschi** [comment]
@oillio If a `Bundle` doesn't require a valid `Environment`, why use a `Bundle` at all and not just load your stuff in the `Application#initialize()` method directly?

**Comment by oillio** [comment]
The primary use case is when I need configuration data, but not environment data.  Config data is not available in Application#initialize.

If I was implementing the ConfiguredBundle/EnvironmentBundle setup described above, I would want to implement the basic Bundle as well to round the implementation out and match the Command implementation.  It would be useful to have a consistent interface across any of my dropwizard libraries.  It would be better to just always provide a bundle, instead of sometimes provide a bundle, sometimes provide some other object that must be run in initialize.

**Comment by amirhmd** [comment]
hi there Im new to open source and would love to contribute to DropWizard. Can anyone help me get started? Or is DropWizard for people who are more experienced in open source?

**Comment by nickbabcock** [comment]
Hey @amirhmd, welcome to open source and Dropwizard :tada:.

- We have the [dropwizard-user](https://groups.google.com/forum/#!forum/dropwizard-user) forum where you can help answer questions and may be the easiest route to helping out.
- If you're interested about getting the word out: write or share blog posts or projects using Dropwizard.
- If you fancy yourself a wordsmith, documentation can always be improved!
- If there's an open issue that's needs work (either via code or in design), input is always welcomed

When in doubt ask on the forums, open an issue, or raise a pull request

If you want to work on this particular issue (and hence why you commented on this issue), it may be best to draw up a tentative pull request showing how this might work (and what/if backwards compatibility is at risk).
