### ISSUE TITLE
Expose a way to get http port in run()

### ISSUE THREAD

**Issue by henrikno** [dropwizard/dropwizard#745]
In dropwizard 0.6 you could get the http port from the configuration in the run() method with `configuration.getHttpConfiguration().getPort()`. In 0.7.x this isn't accessible.

We tried using jetty's connectors, but it hasn't started yet in run(), so we can't use that. Are there any other ways of getting the port?

**Comment by jplock** [comment]
Closing due to lack of feedback

**Comment by yarulan** [comment]
What lack of feedback? Expose a way to get http port in run(). That's crystal clear.

**Comment by jplock** [comment]
If anyone happens to run into this issue, we did add https://github.com/dropwizard/dropwizard/blob/master/dropwizard-lifecycle/src/main/java/io/dropwizard/lifecycle/ServerLifecycleListener.java#L19 in https://github.com/dropwizard/dropwizard/pull/1603 to make this easier.
