### ISSUE TITLE
Bug in hibernate 6.1.7

### ISSUE THREAD

**Issue by rodrigo-rassystem** [dropwizard/dropwizard#7486]
Hello, we are using Dropwizard version 4.0.1 (it uses hibernate-core 6.1.7) and we found an error in our application log:
`Cannot create binding for parameter reference [org.hibernate.query.sqm.tree.expression.ValueBindJpaCriteriaParameter...`

We noticed that this is a hibernate bug and it has been fixed since version 6.2.: https://hibernate.atlassian.net/browse/HHH-15895

Are you planning to release a newer Dropwizard version using at least hibernate 6.2 soon?

**Comment by zUniQueX** [comment]
Hi @rodrigo-rassystem. We can't upgrade to Hibernate 6.2 in Dropwizard 4.x. Dropwizard 4.x is Jakarta EE 9 compatible and therefore uses JPA 3.0. Hibernate 6.1 supports JPA 3.0 and JPA 3.1 while Hibernate 6.2 only supports JPA 3.1. JPA 3.1 is Jakarta EE 10 compatible and we plan to sync Dropwizard versions with EE versions.

However, we currently prepare the EE 10 upgrade. But a release of that will probably take some time.

That being said, JPA 3.1 is a minor release and doesn't contain breaking changes. You may bump the version in your application yourself.
