### ISSUE TITLE
Access log should contain the name of the authenticated user

### ISSUE THREAD

**Issue by maffe** [dropwizard/dropwizard#7506]
The third field in the request/access logs [seems](https://stackoverflow.com/questions/69112100/configuring-jetty-10-11-request-logs) to be for the authenticated user, however I only get dashes. I use Basic authentication as described in the [Dropwizard documentation](https://www.dropwizard.io/en/stable/manual/auth.html). I don’t know what’s the cleanest way to implement this. Ideally this should work out of the box.

**Comment by zUniQueX** [comment]
Hi @maffe. Thanks for reporting this!

The request log (at least the Logback one, which I assume you use here) requests the user information from the `HttpServletRequest`. The information for an implementation of that interface are obtained from the web server and not from the servlet. However, Dropwizard auth filters reside at servlet level.

To overcome this, we would have to set the Jetty `Authentication` and not only the `SecurityContext` inside the Dropwizard auth filter to provide this information to the request logging implementation. I've found a working solution, but it isn't very clean yet. I'll look a bit further into this.
