### ISSUE TITLE
Incorrect bouncy castle artifact is using under DW 4.x and 3.x version

### ISSUE THREAD

**Issue by vkravets** [dropwizard/dropwizard#7508]
<img width="1317" alt="Screenshot 2023-09-12 at 20 20 22" src="https://github.com/dropwizard/dropwizard/assets/985336/74e93675-3572-41ff-80aa-9c8018ea54b8">

Under this table is seems for Java > 1.8 (begin from DW 3.x drops support of Java < 11) need to use bcprov-jdk18on or bcpkix-jdk18on since *-jdk15on is used for Java 1.5-1.8

https://github.com/dropwizard/dropwizard/blob/release/4.0.x/dropwizard-dependencies/pom.xml#L420-L424
https://github.com/dropwizard/dropwizard/blob/release/3.0.x/dropwizard-dependencies/pom.xml#L420-L424

Is it bug or expected?

**Comment by joschi** [comment]
@vkravets Thanks for reporting this! ❤️

This is definitely a bug and will be fixed in the next release of Dropwizard 3.x and 4.x.
