### ISSUE TITLE
LogFormat cannot start with % or [%

### ISSUE THREAD

**Issue by piersy** [dropwizard/dropwizard#765]
The following ConfigurationParsingException is thrown when the log format is started with % or [%

java.lang.RuntimeException: io.dropwizard.configuration.ConfigurationParsingException: ./dropwizard_config.yml has an error:
- Malformed YAML at line: 21, column: 21; while scanning for the next token; found character % '%' that cannot start any token. (Do not use % for indentation);  in 'reader', line 21, column 21:
          logFormat: [%-5level] [%d{yyyy-dd-mm HH:mm:s ... 
                      ^

Given the way that logback formats are constructed Its almost inevitable that the format string will start with %.

The following is the format I would like to use

logFormat: %-5level [%d{yyyy-dd-mm HH:mm:ss.SSS}] [%thread] %logger - %msg%n

As can be seen every element starts with % the only workaround I have found is to prefix the format with a letter of the alphabet.

EG.

logFormat: X %-5level [%d{yyyy-dd-mm HH:mm:ss.SSS}] [%thread] %logger - %msg%n

**Comment by shivangshah** [comment]
I just stumbled upon this issue. Any idea why the logFormat does not print line number? I described the problem in detail here: 
https://github.com/dropwizard/dropwizard/issues/975
