### ISSUE TITLE
Jersey Servlet 3.x API support

### ISSUE THREAD

**Issue by zbiljic** [dropwizard/dropwizard#767]
When I tried to test Jersey async resource

```
@GET
@ManagedAsync
public void helloWorld(@Suspended final AsyncResponse ar) {
    ar.resume("Hello world!");
}
```

I got following exception:

```
java.lang.UnsupportedOperationException: Asynchronous processing not supported on Servlet 2.x container.
...
```

Looking at the `dropwizard-jersey` module `pom.xml` I saw that Jersey container dependency used was `jersey-container-servlet-core`. That module should be used if container implements Servlet API older than 3.0.

For Servlet 3.x support `jersey-container-servlet` module should be used.

```
<dependency>
    <groupId>org.glassfish.jersey.containers</groupId>
    <artifactId>jersey-container-servlet</artifactId>
    <version>${jersey.version}</version>
</dependency>
```

https://jersey.java.net/documentation/latest/modules-and-dependencies.html#servlet-app-general

I hope this will be added into the upcoming 0.8.0 release.

**Comment by prem82** [comment]
I get the same exception while running with 0.8.0-SNAPSHOT version. Jersey version is still not upgraded?. Any idea when will this be upgraded?

**Comment by joschi** [comment]
@prem82 I couldn't reproduce the issue. Please see the referenced commit for a working test of the async functionality.

**Comment by prem82** [comment]
Hi @joschi - thanks for the response. Could you please have a look at the below sample app?  

https://github.com/prem82/async-logger-api  

Please check the POM xml. Without explicitly mentioning the "jersey-container-servlet" dependency, the async API does not work (dropwizard version 0.8.0-SNAPSHOT)  

Input parameters to test:  
http://localhost:9090/logger/async  

Headers:  
User-Agent: Fiddler  
Host: localhost:9090  
Content-Length: 74  
Content-Type: application/json  

Request Body:  
{ "appID" : "smileprem",  "logType" : "WARN", "message" : "Test Message" }  

I get the below exception:  
Causing: javax.servlet.ServletException: java.lang.UnsupportedOperationException: Asynchronous processing not supported on Servlet 2.x container.  

Am I missing something here?

**Comment by joschi** [comment]
Please use Dropwizard 0.8.0-rc2 or 0.8.0-rc3-SNAPSHOT.

**Comment by zbiljic** [comment]
There seems to be a problem when packaging application from console with Maven.
You may want to switch to Dropwizard version 0.8.0-rc2.

**Comment by prem82** [comment]
Thanks guys. It works with 0.8.0-rc2 version. Any idea of 0.9.0 release date?.

**Comment by joschi** [comment]
First we have to get Dropwizard 0.8.0 out of the door, then we can think about Dropwizard 0.9.0. :wink:

**Comment by prem82** [comment]
Oops... that was a typo :)  
Thanks guys for the help...
