### ISSUE TITLE
HealthCheck returns 500 on unhealthy result

### ISSUE THREAD

**Issue by AndrewNorman** [dropwizard/dropwizard#777]
The current version of dropwizard that I am using 0.7.1.

If you write a HealthCheck that is healthy then the servlet returns a 200 code, which is fine.

If there is an unhealthy result then the servlet returns with a 500.

The problem is that a 500 indicates an "Internal Server Error" whereas I have a requirement that it should return a 503 meaning "Service Unavailable".

I think the 503 is a more appropriate response code than a 500, because at the moment I cannot tell the difference between a severe server issue (which is returning a 500) and a unhealthy service which maybe operational with restrictions (which are made clear in the HealthCheck response text).

**Comment by arteam** [comment]
Internally we use [HealthCheckServlet](https://github.com/dropwizard/metrics/blob/master/metrics-servlets/src/main/java/com/codahale/metrics/servlets/HealthCheckServlet.java#L98) from the [Dropwizard Metrics](https://github.com/dropwizard/metrics) project.

I would advice to open a feature request there to add an attribute to the HealthCheckServlet to customize a response code of a failed health check.

If it's done, we will be happy to support it in the server YAML configuration.

**Comment by shruti-palshikar** [comment]
Any updates on this?

**Comment by daluu** [comment]
Perhaps refer to https://github.com/dropwizard/metrics/issues/766, seems stalled there as well.
