### ISSUE TITLE
AWS Serverless Example

### ISSUE THREAD

**Issue by jplock** [dropwizard/dropwizard#7842]
Creating this as a placeholder to add an example to https://github.com/awslabs/aws-serverless-java-container/issues/128

instead of a shaded jar, it would be interesting to use the layered jars to take advantage of SOCI for container pulls and Lambda’s SnapStart

**Comment by josephlbarnett** [comment]
if it's helpful, we used to attempt to deploy our dropwizard app in lambda using https://github.com/trib3/leakycauldron/blob/v1.27.2822/lambda/src/main/kotlin/com/trib3/lambda/TribeServerless.kt -- cold start times were too slow to be useful so we deprecated & then deleted the code, but it may be a useful starting point for anyone interested, as with snapstart the cold start problem may be solved.
