### ISSUE TITLE
DropwizardAppRule cannot be shared in a parent class.

### ISSUE THREAD

**Issue by evanova** [dropwizard/dropwizard#799]
I have 2 JUnit test classes that are sub-classes of a parent containing a DropwizardAppRule.
While tests run correctly on the first class, the tests on the second will fail with a MalformedUrlException indicating a port equal to -2.

The reason is that the DropwizardAppRule.after() method stops the jettyServer within a try/catch which propagate any exception. When an exception occurs, the jettyServer member variable isn't nullified and the next attempt to start it within the same DropwizardAppRule instance will fail since the code believes the server is still up.

The fix is to make sure the jettyServer is nullified within a finally block; this way the jettyServer will be correctly restarted when the 2nd test class is executed.
##### Bugged

``` java
@Override
    protected void after() {
        resetConfigOverrides();
        try {
            jettyServer.stop();
        } catch (Exception e) {
            propagate(e);
        }
        jettyServer = null;
    }
```
##### Fixed

Note the addition of a finally block to ensure jettyServer is null once the test class completes.

``` java
@Override
    protected void after() {
        resetConfigOverrides();
        try {
            jettyServer.stop();
        } catch (Exception e) {
            propagate(e);
        }
        finally {
            jettyServer = null;
        }
    }
```

**Comment by arungupta2008** [comment]
i have dropwizard version 0.7.0-1 can we fix this for this version ? Please

**Comment by joschi** [comment]
@arungupta2008 No, Dropwizard 0.7.x is not maintained anymore. Upgrade to Dropwizard 0.8.x or 0.9.x.
