### ISSUE TITLE
Managed virtual thread pool

### ISSUE THREAD

**Issue by natan-abolafya** [dropwizard/dropwizard#8004]
Would it be possible to have this in dropwizard? Or does it need to wait until dropwizard uses java 19?
Something like
```
environment.lifecycle().virtualExecutorService()
```

I'm using it like this in the meantime:
```
    var factory = new InstrumentedThreadFactory(Thread.ofVirtual().factory(), environment.lifecycle().getMetricRegistry(), "virtual-pool");
    var virtualThreadExecutor = Executors.newThreadPerTaskExecutor(factory);
    environment.lifecycle().manage(new ExecutorServiceManager(virtualThreadExecutor, Duration.seconds(5), "virtual-pool"));
```
have not confirmed it's managed as a regular thread pool yet though.

**Comment by zUniQueX** [comment]
Hi @natan-abolafya. This is planned for one of the next releases. I wanted to release this feature together with the basic loom support for Jetty, but didn't have the time to provide a clean implementation yet. If you have a working solution, feel free to open a PR. To get around the missing loom support before Java 21, you can take a look at the [`getThreadFactory`](https://github.com/dropwizard/dropwizard/blob/release/4.0.x/dropwizard-core/src/main/java/io/dropwizard/core/server/AbstractServerFactory.java#L675-L693) method of the `AbstractServerFactory`.

**Comment by natan-abolafya** [comment]
https://github.com/dropwizard/dropwizard/pull/8066
