### ISSUE TITLE
Exception thrown by a view template doesn't get picked up by ExceptionMapper

### ISSUE THREAD

**Issue by phss** [dropwizard/dropwizard#801]
In my Dropwizard app I am using Freemarker templates through the ViewBundle. I've defined a set of ExceptionMappers to provide a nice-ish page whenever an Exception is thrown.

However, I've noticed that if there's a template error (for instance, a <#broken /> somewhere), an Exception is thrown, but it doesn't get handled by any of the defined ExceptionMappers. The page being display is the default Jetty error (HTTP ERROR 500).

I was wondering if this is by design, or perhaps I am misconfiguring something?

Thanks!

**Comment by carlo-rtr** [comment]
The mapper used is dependent on the mappers registered, there is an algorithm for the most eligible. You can try putting a debug there to see what's happening.

See ExceptionMapperFactory#findMapping(Exception) in jersey-common<2.17>

My guess is this isn't a bug, unless you can point me to an actual issue in the DW framework code.
