### ISSUE TITLE
Deserialization failures due to Afterburner 

### ISSUE THREAD

**Issue by chaitanyachavali** [dropwizard/dropwizard#8067]
I have started to see some failures while deserialization using Jackson after an major upgrade of dropwizard-core (for which dropwizard-jackson is a transitive dependency).  Upon some digging, seems like it caused due to some series of events. Listing them down here. 

1. Afterburner was introduced and added by default since v0.7.0 and was added by commit: https://github.com/dropwizard/dropwizard/commit/7d74d6820150bbea3a1a4c58ea50b3136b1ee156.
2. Afterburner started causing some warnings from Java 9 with introduction of JMS and its adoption by native packages. To curb this, a check has been added to add only for Java 8, PR: https://github.com/dropwizard/dropwizard/pull/2966
3. Later when blackbird module came out along with support for Java 8, then Afterburner was replaced with Blackbird: https://github.com/dropwizard/dropwizard/pull/3803
4. Due to performance issues, Afterburner is added by default when found and if not, Blackbird is added, PR:https://github.com/dropwizard/dropwizard/pull/5477

When doing the revert to Afterburner in _# 4_, the check that was added in _# 2_ was missing and hence the issues are popping back again. 
For now I have identified the illegal and was able to make it work by adding `--add-opens java.base/java.lang=ALL-UNNAMED` to my VM options or by manually adding the Blackbird module by `objectMapper().registerModule(new BlackbirdModule())`

I feel the check added in _# 2_ valid and needs to added back which makes it compatible and executable for Java versions greater that 8 by default. Happy to make that small PR to fix it but would like to know if that's okay and if I am missing something.

**Comment by zUniQueX** [comment]
Hi @chaitanyachavali. I don't think we have something to do here.

Afterburner got removed from the versions 3.x and 4.x and Dropwizard 2.1.x already got its EOL date. For now, I don't see a reason to introduce a behavior change for the last month of support for 2.1.x.
