### ISSUE TITLE
When testing JSON serialization, whitespace is not ignored

### ISSUE THREAD

**Issue by MarkyC** [dropwizard/dropwizard#815]
In the [Testing Docs](https://dropwizard.github.io/dropwizard/manual/testing.html#man-testing-representations-serialization), there is a note: *The comparison is done via a normalized JSON string representation, so whitespace doesn’t affect the results.*

However, when testing serialization, I get a Comparison Failure: `org.junit.ComparisonFailure: 
...
	at com.example.core.user.SubscriberTest.serializesToJSON(SubscriberTest.java:64)`

## Test Code
```
@Test
public void serializesToJSON() throws Exception {

    assertThat(MAPPER.writeValueAsString(user))
            .isEqualTo(fixture("fixtures/Subscriber.json"));
}
```

## Subscriber.json

```
{
  "email": "test@example.com",
  "password": "1234567890",
  "displayName": "Test User",
  "role": "SUBSCRIBER",
  "added": 1400429532000000,
  "modified": 1400429532000000,
  "id": 1,
  "emailConfirmed": true,
  "active": true
}
```

## Differences

I used IDEA to check the differences

### Whitespaced not ignored

When I set IDEA to not ignore whitespace, it shows that there is a difference: 
![Imgur](http://i.imgur.com/F90rIzi.png)

### Whitespace ignored

When I set IDEA to ignore all whitespace, it shows that there is no difference: 
![Imgur](http://i.imgur.com/aJvrjIF.png)

**Comment by carlo-rtr** [comment]
You shouldn't be comparing the strings, you should be comparing the object representations. See the code in the example:

http://www.dropwizard.io/manual/testing.html#testing-serialization
