### ISSUE TITLE
No simple solution for secure content when dropwizard is deployed behind a reverse proxy

### ISSUE THREAD

**Issue by martinborgman** [dropwizard/dropwizard#819]
When a dropwizard application is deployed behind a reverse proxy that also offloads TLS, the http connector is perfectly capable of handling the x-forwarded headers set by the reverse proxy server.
So the connector will properly set the javax.servlet.ServletRequest isSecure flag to true when the request was issued using https.
However there does not appear to be a simple way to make a resource "confidential" in dropwizard.
Now you have to write a servlet filter to redirect request to the secure endpoint yourself which is quite annoying, while adding a simple annotation to your resource could handle this for you regardless whether you are using a reverse proxy setup or handle TLS directly in dropwizard.

Related issue: https://stackoverflow.com/questions/27467365/openshift-diy-dropwizard-with-https

**Comment by jplock** [comment]
What do you mean by "confidential"?  Do any of the new authorization-related changes in Dropwizard 0.9.x solve your issue?

**Comment by martinborgman** [comment]
A servlet engine typically defines a secure endpoint and a non secure endpoint. If you look at tomcat for example it has a non secure port, by default on port 8080, and a secure port, by default on port 8443, defined in it's configuration for this.
You can mark a servlet as "confidential". This means that if you want to access that particular servlet you'll need to access it using the secure endpoint. The port using TLS.
If you access the servlet marked "confidential" using the non secure port, the servlet engine will redirect you to the secure endpoint.
When using a reverse proxy server, you'll need to tell the servlet container whether the connection being used is secure, and if there is secure and non secure content, how to redirect to the proper endpont.

I don't know what you've fixed inn the latest version of Dropwizard, but I will try to take a look.
