### ISSUE TITLE
[0.7.1] dropwizard-example localhost:8443 fails

### ISSUE THREAD

**Issue by chook** [dropwizard/dropwizard#843]
curl https://localhost:8443/hello-world
curl: (35) Server aborted the SSL handshake

Server DEBUG:
DEBUG [2015-01-12 10:25:24,809] org.eclipse.jetty.io.ssl.SslConnection: SslConnection@5476d583{NEED_WRAP,eio=-1/-1,di=-1} -> HttpConnection@6f8c3003{FILLING},g=HttpGenerator{s=START},p=HttpParser{s=START,0 of 0} fill exit
DEBUG [2015-01-12 10:25:24,810] org.eclipse.jetty.server.HttpConnection:
! javax.net.ssl.SSLHandshakeException: no cipher suites in common

I was expecting the example.keystore to work. Perhaps I'm missing something with the mixture of 0.8.0 rc?

**Comment by clamothe** [comment]
I wasn't able to successfully configure my own Dropwizard 0.8.0-rc1 app with https. I tried also using the keystore from the example. Eventually I built dropwizard-example and HTTPS would still not work in this application. I had the same issue chook experienced.

I read that perhaps I needed to install the Java Cryptography Extension, however that did not have any effect.

**Comment by joschi** [comment]
Closed in favor of #919.
