### ISSUE TITLE
@Pattern constraint not working

### ISSUE THREAD

**Issue by ddossot** [dropwizard/dropwizard#844]
I have a POJO method annotated with:

    @Pattern(regexp = "^[A-Z_]{2,32}$")

Despite that, JSON objects with a non-valid field are accepted.

Other constraints on other properties, like `@Size(min = 2, max = 64)` or `@NotNull` work fine.

**Comment by joschi** [comment]
Could you please provide a simple example of the POJO, an invalid, and a valid payload? Which version of Dropwizard are you using?

**Comment by ddossot** [comment]
:tired_face: Sorry I forgot to specify the version :tired_face: I'm using `0.8.0-rc1`.

And yes, I will add the extra information you asked to this issue.

**Comment by ddossot** [comment]
I was using the wrong entity with my JAX-RS resource...
<img src="http://img4.wikia.nocookie.net/__cb20140814175559/r2d/images/9/92/Facepalm_stick_figure.jpg" />
... sorry.

**Comment by joschi** [comment]
Haha, no problem. Thanks for the feedback! :smile:
