### ISSUE TITLE
UnitOfWorkApplicationListener.java commits transaction after exception is thrown in a request.

### ISSUE THREAD

**Issue by lhcjackson-toast** [dropwizard/dropwizard#850]
I am on 0.8.0-rc2

After an exception is thrown in the request, RESOURCE_METHOD_FINISHED event is dispatched first, then ON_EXCEPTION event is dispatched, so we have two problems with the following code:
1. Transaction is committed when exception is thrown. It should be rolled back.
2. If the commit fails, the original exception is lost, replaced by a database exception.

My recommended fix is to check for existing exceptions in RESOURCE_METHOD_FINISHED. 
```java
@Override
public void onEvent(RequestEvent event) {
    if (event.getType() == RequestEvent.Type.RESOURCE_METHOD_START) {
        this.unitOfWork = this.methodMap.get(event.getUriInfo()
                .getMatchedResourceMethod().getInvocable().getDefinitionMethod());
        if (unitOfWork != null) {
            this.session = this.sessionFactory.openSession();
            try {
                configureSession();
                ManagedSessionContext.bind(this.session);
                beginTransaction();
            } catch (Throwable th) {
                this.session.close();
                this.session = null;
                ManagedSessionContext.unbind(this.sessionFactory);
                throw th;
            }
        }
    }
    else if (event.getType() == RequestEvent.Type.RESOURCE_METHOD_FINISHED) {
        if (this.session != null) {
            try {
                commitTransaction();
            } catch (Exception e) {
                rollbackTransaction();
                this.<RuntimeException>rethrow(e);
            }
            finally {
                this.session.close();
                this.session = null;
                ManagedSessionContext.unbind(this.sessionFactory);
            }
        }
    }
    else if (event.getType() == RequestEvent.Type.ON_EXCEPTION) {
        if (this.session != null) {
            try {
                rollbackTransaction();
            }
            finally {
                this.session.close();
                this.session = null;
                ManagedSessionContext.unbind(this.sessionFactory);
            }
        }
    }
}
```

**Comment by phxql** [comment]
The order in which jersey emits the events is:

In case of exception:
* MATCHING_START
* REQUEST_MATCHED
* REQUEST_FILTERED
* RESOURCE_METHOD_START
* RESOURCE_METHOD_FINISHED
* ON_EXCEPTION
* EXCEPTION_MAPPER_FOUND
* EXCEPTION_MAPPING_FINISHED
* RESP_FILTERS_START
* RESP_FILTERS_FINISHED
* FINISHED

In case of no exception:
* MATCHING_START
* REQUEST_MATCHED
* REQUEST_FILTERED
* RESOURCE_METHOD_START
* RESOURCE_METHOD_FINISHED
* RESP_FILTERS_START
* RESP_FILTERS_FINISHED
* FINISHED

My proprosed fix is to replace `RESOURCE_METHOD_FINISHED` with `RESP_FILTERS_START`. With this fix the transaction is rolled back in case of an exception. If no exception happens, the transaction is committed.

**Comment by lhcjackson-toast** [comment]
That sounds good. 

FYI, I patched UnitOfWorkApplicationListener in my project, and I am committing on "FINISHED" event. They passed my integration tests and are working well so far. Here is a snippet of the code,.
```java
            else if (event.getType() == RequestEvent.Type.FINISHED) {
                if (this.session != null && event.getException() == null) {
                    try {
                        commitTransaction();
                    } catch (Exception e) {
                        rollbackTransaction();
                        this.<RuntimeException>rethrow(e);
                    }
                    finally {
                        closeSessions();
                    }
                }
            }
```
