### ISSUE TITLE
Dropwizard & Apache Cassandra?

### ISSUE THREAD

**Issue by gordysc** [dropwizard/dropwizard#852]
First off, let me say I'm blown away by the brilliance of Dropwizard (bravo!!).  I noticed at the moment you only have a module for RDBMS, and was hoping I could peak interest in expanding into the NoSQL space.  

The folks over at Datastax provide an Apache v2 licensed driver for Apache Cassandra:
https://github.com/datastax/java-driver

Recently, they added a really nice abstraction layer to execute queries through annotations, which smells very similar to JDBI's interface.  If Dropwizard provided an optional module to leverage this, you'd have a pretty powerful & scalable stack out of the box for analytics, etc.  Has this been discussed already? Or no?

**Comment by joschi** [comment]
There's [dropwizard-cassandra](https://github.com/stuartgunter/dropwizard-cassandra/) which is well maintained and which is also listed in our [Dropwizard Modules Directory](http://modules.dropwizard.io/thirdparty/).

**Comment by gordysc** [comment]
Wow, I feel dumb.  Thanks!!
