### ISSUE TITLE
Multiple HibernateBundles in the same application registers healthcheck and metrics twice with "hibernate"

### ISSUE THREAD

**Issue by jontejj** [dropwizard/dropwizard#855]
In https://github.com/dropwizard/dropwizard/blob/master/dropwizard-hibernate/src/main/java/io/dropwizard/hibernate/SessionFactoryFactory.java the line:
```final ManagedDataSource dataSource = dbConfig.build(environment.metrics(), "hibernate");```

causes issues for us because we use several different session factories for different databases. This causes invalid metrics in the old 0.7.0 dropwizard and in 0.8.0* dropwizard doesn't start because it discovers that the metric is registered twice.

One solution would be to support a configuration in DataSourceFactory which would default to hibernate to not break legacy code that depends on this metric.

**Comment by arteam** [comment]
@jontejj, please, take a look at #887.
It should resolve the problem with clashed health checks and metrics.
