### ISSUE TITLE
Adding JSONP support to Dropwizard conflicting filter order with GZip

### ISSUE THREAD

**Issue by pmacklin** [dropwizard/dropwizard#858]
We're trying to support JSONP requests in Dropwizard version 0.7.1. We have a custom servlet filter - it's really just a few configuration options built onto the standard [JSONP Filter](https://code.google.com/p/jsonp-java/source/browse/trunk/src/main/java/org/jsonp/JsonpFilter.java). The filter works by registering a HttpServletResponseContentWrapper when the request is detected to be JSONP. This causes the doFilter methods to be applied in a reverse order: the first filter registered is applied last.

The problem arises when we add the filter during our Application `run` method. This is surprisingly before much of the server is bootstrapped due to the `io.dropwizard.cli.EnvironmentCommand` running the Application before its own run method, the latter of which eventually calls the `AbstractServerFactory.createAppServlet`. We have GZIP enabled (because it's awesome, naturally), but that method adds a filter that works in the same way, registering a response wrapper for all requests.

As an aside, the confusing thing about diagnosing this was that responses that were small enough would not get gzipped, presumably because the server decided the response body could fit into a single packet (haven't verified this yet). So on the server side, we could detect that there was response content, and the access log would say it had non-zero bytes, but the requesting agent (cURL, browser, Postman etc.) would claim the response had 0 bytes, and give no indication that it was an invalid GZip content. Just wanted to mention this so anyone else facing a problem with periodic empty response has a clue.

The net effect is that the GZIP filter is applied first by popping the list of registered wrappers and then the response is wrapped in the JSONP callback. This results in a garbled response body like the following:

```
jQuery13906148_139156091( <GZipped JSON data> )
```

So my question is, what's the best way to register a filter so the response wrapping takes place before the GZipping? Is there an Application, Environment or CLI class function we could override that would be called after the lengthy chain of various `run` methods had completed? Is there an application startup hook we could register a callback function with?

The `main` method of the Application class looks like it would work, but it feels kind of hacky (we would need some kludges to expose the environment and config) and would hamper our testing framework bootstrapping - or at least cause us to repeat code there in a non-intuitive location and fashion.

Also, we could just turn of GZipping, but that's not ideal for a production service.

**Comment by pmacklin** [comment]
A more proficient Java colleague of mine solved this with a standard servlet approach that works like this:

```Java
ServletContextListener scl = new ServletContextListener() {
    @Override
    public void contextInitialized(ServletContextEvent sce) {
        // CORS filter:
        Map<String,String> corsInitParams = ImmutableMap.of(
                CrossOriginFilter.ALLOWED_ORIGINS_PARAM, getCORSOrigins(config.getAllowedDomains()),
                CrossOriginFilter.ALLOWED_METHODS_PARAM, "GET,POST",
                CrossOriginFilter.ALLOW_CREDENTIALS_PARAM, "true",
                CrossOriginFilter.ALLOWED_HEADERS_PARAM, "X-Requested-With,Content-Type,Accept,Origin"
        );

        FilterRegistration.Dynamic corsFilter = environment.servlets().addFilter("crossOriginFilter", CrossOriginFilter.class);
        corsFilter.setInitParameters(corsInitParams);
        corsFilter.addMappingForUrlPatterns(EnumSet.allOf(DispatcherType.class), true, "/services/*");

        // JSONP filter:
        Map<String,String> jsonpInitParams = ImmutableMap.of(
                "jsonp", "callback",
                "json-mime-types", MediaType.APPLICATION_JSON,
                "allowed-methods", "GET"
        );

        FilterRegistration.Dynamic jsonpFilter = environment.servlets().addFilter("jsonpFilter", RmnJsonpFilter.class);
        jsonpFilter.setInitParameters(jsonpInitParams);
        jsonpFilter.addMappingForUrlPatterns(EnumSet.allOf(DispatcherType.class), true, "/services/*");
    }

    @Override
    public void contextDestroyed(ServletContextEvent sce) {
    }
};

environment.servlets().addServletListeners(scl);
```

The contextInitialized handler does exactly what we need it to do: add the JSONP filter after the AbstractServletFactory has finished initializing, giving us the needed filter order (JSONP filter at the end of the list).

I would like to leave this open for your consideration. I feel a dropwizard core hook would be a more natural and intuitive way to accomplish this control.

Thanks for your hard work on this project; verily, it is awesome.

**Comment by jplock** [comment]
Is this still an issue with Dropwizard 0.9.x?

**Comment by nickbabcock** [comment]
Should be a non-issue as Dropwizard no longer contains a Gzip Filter (it's a Gzip Handler as of 1.0.0), which shouldn't get in your way. See 29e927a. Let us know if there continues to be problems.
