### ISSUE TITLE
Using jersey's HK2 to inject healthchecks, lifecycle Manageds etc.

### ISSUE THREAD

**Issue by natnan** [dropwizard/dropwizard#862]
(I have asked this on google dropwizard-user groups)[https://groups.google.com/forum/#!topic/dropwizard-user/dmT8BGi9Wcc] and couldn't find a solution. To me it looks like it should be supported given the jersey interface provided by dropwizard.

Let's say I'm using HK2 for dependency injection throughout the application. That's what `´environment.jersey().register(MyResource.class)` does after all.

I bind my service classes via AbstractBinder, while resource classes via directly registering to jersey.

```java
environment.jersey().register(new AbstractBinder() {
          @Override
          protected void configure() {
            ...
            bind(MyService.class):
            ...
          }
        });
environment.jersey().register(MyResource.class); //MyResource uses MyService
```

so my resources etc. can get their dependencies via @Inject.

There are some cases where our healthchecks and Lifecycle classes require those singleton service dependencies (MyService). Even without those specific dependencies, I'd prefer to stick to using dependency injection throughout the application.

However, `environment.healthchecks().register(myHealthCheckObject) //Healtcheck also uses MyService` and  `environment.lifecycle().register(myManagedObject)` only accept instances, not classes; which means they are not injected through the DI framework.

I don't have access to the `ServiceLocator` of jersey, hence cannot create an instance of Healthcheck. I couldn't find a way to access jersey's `ServiceLocator`, probably also because it's not initialized until after `Application.run()` is run. 

Nor I could `environment.lifecycle().register(MyManaged.class)`, which I think should be possible and is the aim of this issue.

I understand dropwizard is in a different context than jersey, and isn't utilizing hk2 directly itself. But this limits our dependency capabilities entirely.

Creating my own `ServiceLocator`, and handling DI through that is an option but will fail when I start implementing my own `AuthFactoryProvider` because it requires dependencies from Jersey. Also I won't be able to ´environment.jersey().register(MyResource.class)` directly.

**Comment by yunspace** [comment]
The ServiceLocator can be obtained through:

    ((ServletContainer) environment.getJerseyServletContainer()).getApplicationHandler().getServiceLocator()

You can verify this is the right one by setting a debug point on classes such as `AuthFactoryProvider` which also use `ServiceLocator`. I've posted this in the forum also.

If you wish to use guice with HK2 I would recommend you to have a look at  https://github.com/HubSpot/dropwizard-guice/pull/45 which uses jersey2-guice library. Auto registration of classes such as Managed are catered for out of the box.

**Comment by natnan** [comment]
`((ServletContainer) environment.getJerseyServletContainer()).getApplicationHandler().getServiceLocator()` is null in `Application.run()` as jersey itself has not been initialized yet,

I guess it'd be best that I create my own DI container using HK2 and link(bridge?) it to the jersey's container. But given the documentation of HK2 and infrequent usage of it, it's not easy to find out whether it's possible or not and how..

**Comment by yunspace** [comment]
In your run() you can replace the default `ServletContainer` with your own container: 

        container = [your container]
        environment.jersey().replace(new Function<ResourceConfig, Servlet>() {
            @Nullable
            @Override
            public ServletContainer apply(ResourceConfig resourceConfig) {
                return container;
            }
        });

In your Container, overwrite the `init()` method to obtain the `ServiceLocator`. I have an example here: https://github.com/yunspace/dropwizard-guice/blob/guice-bridge/src/main/java/com/hubspot/dropwizard/guice/GuiceContainer.java

**Comment by natnan** [comment]
By DI container, I actually meant the ServiceLocator that I could create in `Application.run()`, not `ServletContainer`. I couldn't find a way to bridge one ServiceLocator to another though..

Guice bridge is useful if I decide to go back to Guice, but is not the issue at hand. Thanks.

**Comment by shadowmonkey** [comment]
Sorry for update zombie topic, but this information can be useful. I also tried to get ```ServiceLocator``` from ```jersey container```. Of course I had the same problem and solution from above doesn't work for me.

Instead of jersey container I used utilities.
```ServiceLocator locator = ServiceLocatorUtilities.createAndPopulateServiceLocator()```

https://hk2.java.net/2.4.0-b16/getting-started.html#Automatic_Service_Population

**Comment by natnan** [comment]
Then you had to instantiate the Resource classes, right?
You can't `environment.jersey().register(MyResource.class);` anymore because it will not have dependencies injected from your own container. You have to `environment.jersey().register(locator.getService(MyResource.class));` instead, which means you can only have singleton Resource classes now, not per request.

**Comment by RichardBradley** [comment]
I'd love to have an answer to this one.
I've been poring over this in the debugger and I can't figure it out.

The "jooq bundle" is registering a ConnectionProvider into a DropwizardResourceConfig during run()

How can I get it back out again in other code during `run`? I can't find a `ServiceLocator` or anything like it nearby.

I find the HK2 stuff impossible to follow.

**Comment by natnan** [comment]
Looks like I have forgotten to close this issue. If you check my other issue #1026, I have found a solution to that. But yeah, HK2 is quite difficult to work with given the lack of documentation.

So, either you create your own service locator instead of registering binders to Jersey, and only register your ServiceLocator

```
// create your binders here

// random UUID is added for random locator name generation so DropwizardAppRules wouldn't fail
serviceLocator = ServiceLocatorUtilities.bind(UUID.randomUUID().toString(), binders.toArray(new Binder[binders.size()]));
    environment.getApplicationContext().getAttributes().setAttribute(ServletProperties.SERVICE_LOCATOR, serviceLocator);

// create your healtchecks here.
```

or you "bridge" your service locator: https://github.com/natnan/dropwizard-executor-test/blob/master/src/main/java/com/natnan/dropwizard/executor/ExecutorApplicationBridge.java

**Comment by RichardBradley** [comment]
Thanks for your reply. I still don't understand how to do this though :-(

in my Dropwizard app, I have:

```
public class MyApp extends Application<Config> {
    @Override
    public void initialize(Bootstrap<Configuration> bootstrap) {
        bootstrap.addBundle(new JooqBundle<Configuration>() {
            @Override
            public DataSourceFactory getDataSourceFactory(Configuration configuration) {
                return configuration.getRelationalDatabase();
            }
        });
    }

    @Override
    public void run(Configuration configuration, Environment environment) throws Exception {
      org.jooq.ConnectionProvider connPool = ???;
    }
}
```

The JooqBundle creates a ConnectionProvider and registers it with Jersey:

```
    environment.jersey().register(new JooqBinder(cfg));
    ...
    JooqBinder {
      bind(configuration.connectionProvider())
                .to(ConnectionProvider.class);
    }
```

I'd like to use that pool in my "run", rather than creating a second pool.

Are you able to help me fill in the "???" bit? I can't figure it out from the two links in your previous post.

**Comment by natnan** [comment]
I'm not 100% sure about this but I think you cannot access the objects that are registered to Jersey until after `run()` is finalized because Jersey is not initialized yet. 

I think you might need to customize `JooqBundle` a little so it has a `getConnectionProvider()` method. Since bundles' `run` method is run before the `Application`, the connection provider should be ready to use. That's the only solution I can think of at the moment.

**Comment by RichardBradley** [comment]
> I'm not 100% sure about this but I think you cannot access the objects that are registered to Jersey until after run() is finalized because Jersey is not initialized yet.

Yes, you're right. The binder isn't invoked until after "run()" has finished. 
So there's not going to be a way to use Jersey DI inside run() without a lot of changes.

> I think you might need to customize JooqBundle a little so it has a getConnectionProvider() method

Will do, thanks

**Comment by phavelar** [comment]
This is too much... better luck switching to Spring Boot.

**Comment by RichardBradley** [comment]
(I agree -- the HK2 DI stuff has been "enterprised" to the point where it is impossible to understand and more of a hindrance than a help. The rest of Dropwizard works quite well though; I prefer it to Spring, which has plenty of its own over-engineering issues.)

**Comment by marchign** [comment]
In order to let the ServiceLocator build the healthchecks I am using Jersey INITIALIZATION_FINISHED event as follow:

```
environment.jersey().register(new ApplicationEventListener() {
  @Override
  public void onEvent(ApplicationEvent event) {
    if (event.getType() == ApplicationEvent.Type.INITIALIZATION_FINISHED) {
      ServiceLocator serviceLocator = ((ServletContainer) environment.getJerseyServletContainer()).getApplicationHandler().getServiceLocator();
        for (NamedHealthCheck healthCheck : serviceLocator.getAllServices(NamedHealthCheck.class)) {
          environment.healthChecks().register(healthCheck.getName(), healthCheck);
        }
      }
   }
   
    @Override
    public RequestEventListener onRequest(RequestEvent requestEvent) { return null; }
});
```

Then, I register the healthcheck class in the AbstractBinder, e.g.:
```
environment.jersey().register(new AbstractBinder() {
  @Override
    protected void configure() {
      // ...
      bind(SampleHealthCheck.class).to(NamedHealthCheck.class);
    }
});
```

It is fragile since it relies on the init order of dropwizard components but it works with 1.0.0 and I did not find a better solution.

**Comment by sunds** [comment]
Thank you @natnan !  I was able to get this working with DW 1.0.1 by passing in my own service locator in the run() method as you specified above:

		environment.getApplicationContext().getAttributes().setAttribute(ServletProperties.SERVICE_LOCATOR, locator);


This handy utility will allow you to scan and load dependencies at runtime as an alternative to compile time generation of inhabitant files. This makes running from your IDE easier:

		environment.getApplicationContext().getAttributes().setAttribute(ServletProperties.SERVICE_LOCATOR, locator);

**Comment by baharclerode** [comment]
I put together a bundle here https://github.com/baharclerode/dropwizard-hk2 that makes it easy to register health checks, metrics, and lifecycles/managed the same as resources and have them injected by HK2.
