### ISSUE TITLE
[0.8.0-rc2] Setting the port on the command line fails.

### ISSUE THREAD

**Issue by ojacobson** [dropwizard/dropwizard#865]
From the docs,

```
java -Ddw.server.applicationConnectors[0].port=9090 [...]
```

Trying this with a Dropwizard 0.8.0-rc2 app fails as follows:

```
$ java -Ddw.server.applicationConnectors[0].port=9090 -jar build/libs/dropbear-all.jar server
Exception in thread "main" java.lang.IllegalArgumentException: Unable to override server.applicationConnectors[0].port; node with index not found.
```

I was rather hoping that'd set the port, instead, so I could run Dropwizard on Heroku.

An app reproducing this problem is available at [ojacobson/dropbear](/ojacobson/dropbear). To reproduce:

```
./gradlew build
java -Ddw.server.applicationConnectors[0].port=9090 -jar build/libs/dropbear-all.jar server
```

**Comment by ojacobson** [comment]
As a workaround, creating a config file `example.yml` as follows:

```
server:
    type: default
    applicationConnectors:
        -   type: http
            port: 8080
```

and starting the server with

```
java -Ddw.server.applicationConnectors[0].port=5000  -jar build/libs/dropbear-all.jar server example.yml
```

succeeds, and binds the server to port 5000 (with the admin listener on port 8081 as usual). Having to spell out the default config far enough to give the `-D` properties something to override feels wrong to me, but does work.

**Comment by radius314** [comment]
What happens if you specify the admin port also from the command line?

**Comment by arteam** [comment]
It's a known issue #636 

Currently Dropwizard can't start with an empty configuration.

One possible way to solve this problem in the framework is to handle empty object nodes before configuration overriding. In this case we can:

* Instantiate a default configuration
* Dump it to an object tree
* Pass the tree to the overriding routine
* Create a real configuration from the processed tree

I guess something like that will be sufficient in [ConfigurationFactory#build](https://github.com/dropwizard/dropwizard/blob/master/dropwizard-configuration/src/main/java/io/dropwizard/configuration/ConfigurationFactory.java#L123)

```` java
private T build(JsonNode node, String path) throws IOException, ConfigurationException {
    if (node == null || (node.isObject() && node.size() == 0){
        try {
            node = mapper.valueToTree(klass.newInstance());
        } catch (InstantiationException | IllegalAccessException e) {
            throw new IllegalArgumentException("Unable crate an instance of " +
                    klass, e);
        }
    }
````

I will try to create a PR for this.

**Comment by ojacobson** [comment]
> It's a known issue #636

Aha, thanks. I had a look through the tracker before posting it, but didn't see that one. Feel free to close this as a duplicate; no need for the additional clutter. :)
