### ISSUE TITLE
Add AssetsBundle as an admin Servlet

### ISSUE THREAD

**Issue by BorisNaguet** [dropwizard/dropwizard#870]
Hello,

Since DW 0.7 we can select to add servlet on the admin port, but the AssetsBundle hasn't been updated to reflect that.

I created an AdminAssetsBundle. Since all fields are private, I had to duplicate the whole class, just to change one line:

```java
environment.admin().addServlet(assetsName, createServlet()).addMapping(uriPath + '*');
```

We could also keep a single Bundle and add boolean in one of the constructors.

**Comment by twogood** [comment]
Why mess with the AssetBundle when you can add the AssetServlet?
```java
AssetServlet assetServlet = new AssetServlet("/status", "/status", "index.html",
                Charsets.UTF_8);

environment.admin().addServlet("statusWeb", assetServlet).addMapping("/status/*");
```

**Comment by BorisNaguet** [comment]
As you want, we moved to an "extra servlet in config" solution since then.
In this case, the original AssetBundle is not really useful either.
