### ISSUE TITLE
Timing-Bug when logging once and a possible workaround

### ISSUE THREAD

**Issue by JamesBoon** [dropwizard/dropwizard#8775]
Running _any_ command that contains only one log statement, the output _might_ get lost. 
To illustrate this, I'll be using the `check` command, but it can happen with all commands.
 
I could not track down the bug, but at least found a workaround, which would require a one-line addition to `DefaultLoggingFactory`.  

Here is a test class I wrote, feel free to use or alter it as you wish:
<details>

<summary>CheckCommandTest.java</summary>

```java
package com.example;

import io.dropwizard.core.Application;
import io.dropwizard.core.Configuration;
import io.dropwizard.core.cli.CheckCommand;
import io.dropwizard.core.cli.Cli;
import io.dropwizard.core.setup.Bootstrap;
import io.dropwizard.core.setup.Environment;
import io.dropwizard.util.JarLocation;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.RepeatedTest;
import org.junit.jupiter.api.io.TempDir;

import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.io.PrintStream;
import java.nio.file.Files;
import java.nio.file.Path;

import static org.assertj.core.api.Assertions.assertThat;

class CheckCommandTest {

    @TempDir
    private static Path tempDir;
    private static Path confiYml;

    private static class MyApplication extends Application<Configuration> {
        @Override
        public void run(Configuration configuration, Environment environment) throws Exception {
        }
    }

    private final MyApplication application = new MyApplication();
    private final JarLocation location = new JarLocation(MyApplication.class);
    private final CheckCommand<Configuration> command = new CheckCommand<>(application);

    @BeforeAll
    static void beforeAll() throws IOException {
        String config = """
                logging:
                  appenders:
                    - type: console
                      logFormat: "%msg"
                """;

        confiYml = tempDir.resolve("config.yml");
        Files.writeString(confiYml, config);
    }

    @RepeatedTest(100)
    void shouldWriteToStdOut() {
        PrintStream originalOut = System.out;
        ByteArrayOutputStream stdOut = new ByteArrayOutputStream();
        System.setOut(new PrintStream(stdOut));

        Bootstrap<Configuration> bootstrap = new Bootstrap<>(application);
        bootstrap.addCommand(command);

        Cli cli = new Cli(location, bootstrap, stdOut, System.err);
        cli.run("check", confiYml.toAbsolutePath().toString());

        assertThat(stdOut.toString())
                .isEqualTo("Configuration is OK");

        System.setOut(originalOut);
    }

}
```
</details>  

Running this, I get around ~60 failed and only 40 passed tests.  
I have tested this with the Dropwizard 4, Eclipse Temurin 11 and 17 on Linux (Ubuntu 20).  
This _might_ be a Linux problem. Could anyone confirm this on any other platform?  
  

After digging through the Dropwizard code, I found a workaround:  
If you add a tiny `sleep` to `DefaultLoggingFactory.flushAppender(...)`, all tests pass.
Thus, if adding `Thread.sleep(10);` [here](https://github.com/dropwizard/dropwizard/blob/v4.0.7/dropwizard-logging/src/main/java/io/dropwizard/logging/common/DefaultLoggingFactory.java#L199), before the `while` loop starts.  

Do you think this workaround might be a valid addition?

**Comment by zUniQueX** [comment]
Hi @JamesBoon. Sleeping there wouldn't be a good solution IMHO. The sleep time would be system dependent, so we can't find a valid default there.

Maybe we could think of automatically adjusting the max flush time. Then we wouldn't sleep, if the queues are empty already, but could add the additional sleep time while waiting in the loop.

**Comment by JamesBoon** [comment]
The problem I noticed was that the queue _seemed_ empty, thus the `appender.getNumberOfElementsInQueue()` returned `0`, even if something _should_ have been logged.

**Comment by zUniQueX** [comment]
For async appenders this can be the case. The `Worker` would take some elements from the queue and then log them. So the queue can be empty before all logging events are logged.

The best solution for this problem would be to additionally wait for the appenders to be stopped IMHO. What do you think about that?

**Comment by JamesBoon** [comment]
This sounds like a good solution. But I just tried with with a simple `while (timeWaiting < appender.getMaxFlushTime() && appender.isStarted())` inside the `flushAppender(...)` - but this didn't work as expected. The appender is always `started`.  

Do you have another idea? Maybe my approach to use the `flushAppender(...)` was wrong?

**Comment by zUniQueX** [comment]
@JamesBoon Currently the `DefaultLoggingFactory` doesn't stop the appenders. This additionally allows other threads to further push log events to the queues of the appenders while `stop()` is called, so the queues may be refilled during flushing.

I'd argue `LoggingFactory#stop()` suggests a stop of the logging framework and hence the logback appenders. If we'd do this, we can await the termination of the `Worker`s from the async appenders.

**Comment by JamesBoon** [comment]
:open_mouth: actually, just adding `appender.stop();` [after this line](https://github.com/dropwizard/dropwizard/blob/v4.0.7/dropwizard-logging/src/main/java/io/dropwizard/logging/common/DefaultLoggingFactory.java#L160) solves this issue!  
I don't know if this might have unwanted side effects though...
