### ISSUE TITLE
[Regression] Created Response URI Incorrect in DW 0.8.0-rc3-SNAPSHOT

### ISSUE THREAD

**Issue by MarkHerhold** [dropwizard/dropwizard#878]
The Location header is not being created correctly in DW 0.8.0-rc3-SNAPSHOT when Response.created() is returned with a URI. This appears to be a regression from DW 0.7.1.

### To reproduce:
1. Clone the dropwizard-example folder, setup the DB, and run it.
1. Ensure `<dropwizard-version>0.8.0-rc3-SNAPSHOT</dropwizard-version>` is in the POM
1. Edit the [PeopleResource starting on line 27](https://github.com/dropwizard/dropwizard/blob/master/dropwizard-example/src/main/java/com/example/helloworld/resources/PeopleResource.java#L27)
and change to:

```java
        peopleDAO.create(person);
        return Response.created(new URI(String.valueOf(person.getId()))).build();
```
1. The resulting response will contain a `Location` header with `http://localhost:8080/4` or similar

### Expected result:
`http://localhost:8080/people/4`

### Actual result:
`http://localhost:8080/4`

**Comment by joschi** [comment]
As far as I can tell that's completely correct. You need to build a proper URI with [`UriBuilder`](https://jax-rs-spec.java.net/nonav/2.0/apidocs/javax/ws/rs/core/UriBuilder.html) (yours will literally just contain the ID of the `Person` instance).

```
final URI uri = UriBuilder.fromResource(PeopleResource.class)
                .path("{personId}")
                .build(person.getId());

return Response.created(uri).build();
```

**Comment by MarkHerhold** [comment]
This behavior was as described (the "expected" case) in DW 0.7.1 where the
path for the resource would be added automatically. I have double checked
this behavior and think that it is a great feature. That is why I believe
that this is a regression in 0.8.0-rc3.

Are you saying that this is the new expected behavior? Any clues as to why
there is a difference between 0.7.1 and 0.8.0-rc3?

**Comment by MarkHerhold** [comment]
I've done some further digging. The reason the URIs are resolved to a full path is because Jersey's 1.x (whatever specific version is used in DW 0.7.1) contains some code to the ContainerResponse class when setting headers to look at URIs for the location header and resolve them further if needed.

Here is a code snippet:
```java
    private void setHeaders(MultivaluedMap<String, Object> headers) {
        this.headers = headers;
        Object location = headers.getFirst(HttpHeaders.LOCATION);
        if (location != null) {
            if (location instanceof URI) {
                final URI locationUri = (URI)location;
                if (!locationUri.isAbsolute()) {
                    final URI base = (statusType.getStatusCode() == Status.CREATED.getStatusCode())
                            ? request.getAbsolutePath()
                            : request.getBaseUri();
                    location = UriBuilder.fromUri(base).
                            path(locationUri.getRawPath()).
                            replaceQuery(locationUri.getRawQuery()).
                            fragment(locationUri.getRawFragment()).
                            build();
                }
                headers.putSingle(HttpHeaders.LOCATION, location);
            }
        }
    }
```

I will try to see what Jersey 2.x is doing next or if this functionality was removed.

**Comment by MarkHerhold** [comment]
The [latest Jersey 2.x docs](https://jersey.java.net/apidocs/2.16/jersey/javax/ws/rs/core/Response.html#created(java.net.URI)) state that Jersey should be resolving to an absolute URI.

    location - the URI of the new resource. If a relative URI is supplied it will be converted into an absolute URI by resolving it relative to the request URI (see UriInfo.getRequestUri()).

It seems like others are having a [similar problem](http://jersey.576304.n2.nabble.com/Creating-a-new-WebTarget-from-an-existing-one-td7582191.html).

It looks like this issue is already being tracked in [JERSEY-1910](https://java.net/jira/browse/JERSEY-1910) but it is shown as fixed, resolved, and released in "version 2.3" back in September 2014. This doesn't match up with the versions of Jersey on Maven Central (the latest is currently 2.16). Can anyone explain the version differences?

**Comment by carlo-rtr** [comment]
I believe 2.16 includes changes from 2.3, as 16 > 3.  Is that what you are asking?

Either way, 2.16 appears to be the latest and it's what DW depends on.

**Comment by briehman** [comment]
I opened a Jersey issue for this since I am seeing it in 2.17 also:
https://java.net/jira/browse/JERSEY-2838

**Comment by MarkHerhold** [comment]
@briehman Thanks

**Comment by MarkHerhold** [comment]
I have a bad habit of clicking that comment and close button. :/

**Comment by sebeichholz** [comment]
Hi, is it correct that there is no fix in Jersey for this issue yet?
I updated my DW application from 0.7 to 0.8 and this error forces me to make code changes I don't want :-(

**Comment by joschi** [comment]
@sebeichholz We depend on the fixing of https://java.net/jira/browse/JERSEY-2838 here. Not much we can do in Dropwizard (dropwizard-jersey) without basically rewriting parts of Jersey 2.x.

**Comment by sebeichholz** [comment]
@joschi Ok, thanks.

**Comment by joschi** [comment]
@sebeichholz Could you please check if the issue has been solved in Dropwizard 0.9.0-rc5-SNAPSHOT?

**Comment by sebeichholz** [comment]
I see that the Auto stuff has changed since 0.8.x
Give me some time to adjust my code to these changes.

**Comment by joschi** [comment]
Closed due to lack of feedback.
