### ISSUE TITLE
Ping returns pong and line feed

### ISSUE THREAD

**Issue by vilhelmpersson** [dropwizard/dropwizard#879]
Is there a reason for ping returning the text pong and an line feed.

When building test that uses the response it is easier to just write "pong".equalTo(response) then response.startsWith("pong") and adding null-check and other.

The PingServlet is currently implemented as writer.println(CONTENT); instead of writer.print(CONTENT);

**Comment by MarkReddy** [comment]
The PingServlet is a separate project, please see: https://github.com/dropwizard/metrics You should log an issue there. 

In the meantime when testing you could do the following:

```java
assertThat(response.getContent()).isEqualTo(String.format("pong%n"));
```

As per https://github.com/dropwizard/metrics#L33-L34

**Comment by joschi** [comment]
Additionally changing the response of the PingServlet now would break every existing check in existence, so it's rather unlikely to change just for some increased convenience when writing checks or tests for it.
