### ISSUE TITLE
Jersey media multipart exceptions in 0.8.0-rc3

### ISSUE THREAD

**Issue by jasonsturges** [dropwizard/dropwizard#880]
jersey-media-multipart artifact is throwing exceptions in 0.8.0-rc3-SNAPSHOT, previously functional in 0.8.0-rc2.

pom.xml

    <dependency>
        <groupId>org.glassfish.jersey.media</groupId>
        <artifactId>jersey-media-multipart</artifactId>
        <version>2.15</version>
    </dependency>

Application.java

    import org.glassfish.jersey.media.multipart.MultiPartFeature;

    environment.jersey().register(MultiPartFeature.class);

Throws:

org.glassfish.jersey.internal.Errors: The following warnings have been detected: WARNING: HK2 service reification failed for [org.glassfish.jersey.server.internal.inject.MultivaluedParameterExtractorFactory]

1. org.glassfish.hk2.api.UnsatisfiedDependencyException: There was no object available for injection at SystemInjecteeImpl(requiredType=MultivaluedParameterExtractorProvider,parent=CookieParamValueFactoryProvider,qualifiers={},position=0,optional=false,self=false,unqualified=null,553299831)
2. java.lang.IllegalArgumentException: While attempting to resolve the dependencies of org.glassfish.jersey.server.internal.inject.CookieParamValueFactoryProvider errors were found
3. java.lang.IllegalStateException: Unable to perform operation: resolve on org.glassfish.jersey.server.internal.inject.CookieParamValueFactoryProvider

**Comment by Athou** [comment]
I can reproduce this one. It's probably due to a jersey version mismatch between dropwizard and your explicit dependency on jersey-media-multipart.

Replacing the `jersey-media-multipart` dependency in your pom with the new `dropwizard-forms` module and replacing `environment.jersey().register(MultiPartFeature.class)` with `bootstrap.addBundle(new MultiPartBundle());` as described on https://github.com/dropwizard/dropwizard/blob/master/docs/source/manual/forms.rst should do the trick.

**Comment by joschi** [comment]
@jasonsturges Dropwizard 0.8.0-rc3 is using Jersey 2.16. Please use either the correct version of `jersey-media-multipart` or `dropwizard-forms`, as described by @Athou, which implicitly imports the correct version.

**Comment by jasonsturges** [comment]
Excellent - thank you.  Looking forward to `dropwizard-forms` availability on Maven.

**Comment by joschi** [comment]
dropwizard-forms 0.8.0-rc3 should already be on Maven Central: http://search.maven.org/#artifactdetails%7Cio.dropwizard%7Cdropwizard-forms%7C0.8.0-rc3%7Cjar
