### ISSUE TITLE
Deprecation warning in logback

### ISSUE THREAD

**Issue by eiden** [dropwizard/dropwizard#882]
When I was working on #881, I stumbled upon this warning from logback:
````
11:06:19,038 |-WARN in ch.qos.logback.core.FileAppender[file-appender] - This appender no longer admits a layout as a sub-component, set an encoder instead.
11:06:19,038 |-WARN in ch.qos.logback.core.FileAppender[file-appender] - To ensure compatibility, wrapping your layout in LayoutWrappingEncoder.
11:06:19,038 |-WARN in ch.qos.logback.core.FileAppender[file-appender] - See also http://logback.qos.ch/codes.html#layoutInsteadOfEncoder for details
````

The warning message is generated when calling `OutputStreamAppender#setLayout` which is done in the `ConsoleAppenderFactory`, `FileAppenderFactory` and `LoggingFactory`.

The recommended way (from logback) to fix this, is to wrap the layouts in a `LayoutWrappingEncoder`:

````
LayoutWrappingEncoder<ILoggingEvent> encoder = new LayoutWrappingEncoder<>();
encoder.setLayout(layout == null ? buildLayout(context, timeZone) : layout);
        
appender.setEncoder(encoder);
````

More info can be found here:
http://logback.qos.ch/codes.html#layoutInsteadOfEncoder

**Comment by arteam** [comment]
Thanks, @eiden! I've pushed the fixes.
