### ISSUE TITLE
BaseReporterFactory should support matching includes/excludes with regular expressions

### ISSUE THREAD

**Issue by ToadJam** [dropwizard/dropwizard#883]
My project requires a ReporterFactory that can filter out metrics using logic more complicated than the straightforward Set.contains() that the BaseReporterFactory currently uses. It would be really useful if the include/exclude fields in that class supported regular expressions.

While it IS possible to implement regular expressions on my end by overriding getFilter() to return a custom MetricFilter implementation, this unfortunately has a few drawbacks. Namely, it requires me to reproduce the includes/excludes logic already implemented in getFilter()'s default MetricFilter. This, in turn, makes my code more brittle, as any changes or fixes applied to that MetricFilter implementation (such as, say, https://github.com/dropwizard/dropwizard/commit/8d2fd813f017a91f5f31f663b5fb626720ef8d96) would have to be manually reproduced in my own copy. Ideally that MetricFilter would support regular expressions by default, or at least be extendable in a way that effectively re-uses code.

**Comment by ToadJam** [comment]
I created a PR for this issue here: https://github.com/dropwizard/dropwizard/pull/884

**Comment by arteam** [comment]
+1 for more sophisticated control of metrics reporting.

**Comment by eepstein** [comment]
+1 a simple includesRegex that augments the existing includes: would be enough.

**Comment by arteam** [comment]
Closed via #884
