### ISSUE TITLE
purpose of "realm" attribute when using OAuth

### ISSUE THREAD

**Issue by johnwiesel** [dropwizard/dropwizard#885]
I think I understand the purpose of a "realm" when using basic auth.
How does this apply to oauth and the OAuthFactory? I am a bit confused what to use here.

```
    public OAuthFactory(final Authenticator<String, T> authenticator,
                        final String realm,
                        final Class<T> generatedClass
```

As far as I can tell, this realm is used only in the error response when authentication fails, similar to basic auth. Again, in the context of oauth, wouldn't it make more sense to use scopes instead?
Thanks for your comments.

**Comment by nickbabcock** [comment]
Sorry that we weren't able to answer your question in time, but Dropwizard has moved to an [OAuthCredentialAuthFilter](http://www.dropwizard.io/1.0.6/docs/manual/auth.html#oauth2). The realm is only used in a challenge. [From the spec](https://tools.ietf.org/html/rfc6750#section-3):

> A "realm" attribute MAY be included

The unauthorized handler can be customized as needed.
