### ISSUE TITLE
Handling of generic detection for ConfiguredCommand incomplete

### ISSUE THREAD

**Issue by cowtowncoder** [dropwizard/dropwizard#89]
Looks like ConfiguredCommand assumes that all commands directly extend it; so trying to use an intermediate base class, like:

```
class MyCommmand extends ConfiguredCommand<MyConfig> { }
```

will fail with exception like:

```
Exception in thread "main" java.lang.ClassCastException: java.lang.Class cannot be cast to java.lang.reflect.ParameterizedType
at com.yammer.dropwizard.cli.ConfiguredCommand.getConfigurationClass(ConfiguredCommand.java:36)
at com.yammer.dropwizard.cli.ConfiguredCommand.run(ConfiguredCommand.java:62)
at com.yammer.dropwizard.cli.Command.run(Command.java:113)
at com.yammer.dropwizard.AbstractService.run(AbstractService.java:178)
```

I suspect same is true for other generic types, but this is the one I bumped into.
A work-around is to keep intermediate classes parametric as well.

To fix this it should be possible to just go down inheritance hierarchy to find the place where generic information is passed; and although type aliasing can theoretically be problem (someone using intermediate classes with different number of parameters etc), in practice this should suffice.
(and if not, java-classmate project can solve this cleanly and completely -- but it'd be one more dependency, although can be shaded)

**Comment by rwold-resilient** [comment]
@codahale consider me bitten; I have a class on the form
```
public class ForwarderCommand<T extends Configuration & ForwarderConfiguration> extends ConfiguredCommand<T>
```
which gets a ClassCastException in the first line of
```
protected void run(final Bootstrap<T> bootstrap, final Namespace namespace, final T configuration)
{
    doSomethingThatTakesAForwarderConfiguration(configuration);
    //other stuff
}
```
the actual commands that subclasses ForwarderCommand uses specific (and different) ForwarderConfiguration implementations that extends Configuration.
