### ISSUE TITLE
Metric Reporter filter redux

### ISSUE THREAD

**Issue by eepstein** [dropwizard/dropwizard#890]
Re issues #711 , #713  and #730 

MetricFilter should use different logic for filtering.  Case 4 in #713 results in odd behavior.  

Start with a non-empty includes list and an empty excludes list, then add an excludes list: items in neither list appear in the output.  Adding an excludes list to an in-place includes list starts reporting all metrics not in either list!  That is odd behavior that verges on the behavior of the original bug that was being fixed.

An alternative, semi-standard way of doing this kind of filtering is to always apply both  filters. Given the default behavior of including everything if no filter is specified, this makes senses.  

In the code that might be:

    public MetricFilter getFilter() {
        return new MetricFilter() {
            @Override
            public boolean matches(final String name, final Metric metric) {
                boolean isNotExcluded = getExcludes().isEmpty() || !getExcludes().contains(name);
                boolean isIncluded = getIncludes().isEmpty() || getIncludes().contains(name);
                // Match name that isNotExcluded && isIncluded
                return isNotExcluded && isIncluded;
            }
        };
    }

Note that this logic correctly handles cases 1, 2, and 3 as well - the degenerate cases where either only one filter or no filter at all is specified.

The last of the unit tests changes to:

                new Object[]{INCLUDES, "", EXCLUDES, "any", false, "case4"}

One further reason for this approach (used in multiple project - Spring, Eclipse, to name two) is that it makes sense with regex filters as well.

**Comment by arteam** [comment]
Thank you for pointing this out and for thorough description.
I agree that the current behaviour is not obvious. Especially if you start with the includes list.

But I see one problem with your proposed implementation. The excludes list doesn't make sense if
the includes list is not empty. Shouldn't it exclude items from the include list, rather then always exclude items from all metrics?  By default the include list is empty - it means we report all metrics. The exclude list in then just applied to the include list. 
If we are set to this variant - then description is following:

* _excludes-only_
All metrics are reported, except those with a name listed in excludes.
* _includes-only_
Only metrics with a name listed in includes are reported.
* _mixed (both includes and excludes)_
Only metrics with a name listed in includes are reported, except those listed in excludes.

Implementation is straightforward:
````java
final boolean isIncluded = includes.isEmpty() || includes.contains(name);
final boolean isExcluded = excludes.contains(name);
return isIncluded && !isExcluded;
````

And 4th test case is changed for that:
````java
new Object[]{INCLUDES, EXCLUDES, "inc", true, "case4"},
 new Object[]{INCLUDES, EXCLUDES, "both", false, "case4"},
new Object[]{INCLUDES, EXCLUDES, "exc", false, "case4"},
new Object[]{INCLUDES, EXCLUDES, "any", false, "case4"}
```` 

What do you think?

**Comment by eepstein** [comment]
Yes, that variant produces the same result.

    ! excludes.contains(name)

Is always true when excludes.isEmpty(), so that is the same with a simpler (read: better) implementation.

**Comment by arteam** [comment]
Great, I will make a fix. 
I'm going to wait for resolution of #884 and then will apply the corresponding changes.

**Comment by eepstein** [comment]
I actually had coded it with regexes too - was looking at that.  Shall I do a pull request and you can see if there's something worth incorporating?

**Comment by arteam** [comment]
Sure, send one. 
If everything is right, I'll merge it and you will get credit for your effort on this.

**Comment by eepstein** [comment]
Done.  Thanks!

**Comment by arteam** [comment]
I've rebased the changes and merged them with small improvements.
Thanks, @eepstein, for your steady work on this!

**Comment by eepstein** [comment]
Thanks @arteam for rebasing.  (I only realized after I'd merged and committed that a rebase would have been better.)  And thanks too for your inclusive approach.  Makes it fun!
