### ISSUE TITLE
Potential XSS vulnerability in AbstractParam

### ISSUE THREAD

**Issue by prb** [dropwizard/dropwizard#892]
This came up when a customer ran a scan against a Dropwizard app.  In `AbstractParam` ([here](https://github.com/dropwizard/dropwizard/blob/master/dropwizard-jersey/src/main/java/io/dropwizard/jersey/params/AbstractParam.java#L69)), the input parameter value is sent back unescaped.  While useful, that could enable an attacker to insert scripting into a page that displays those error messages.

**Comment by prb** [comment]
This issue was patched in the application in question by overriding `AbstractParam#errorMessage` in the subclasses in question, but the easy fix in general is simply not to return the input (verbatim) in the response.

**Comment by joschi** [comment]
It's already escaped as a JSON string but which escaping rules would you additionally apply? SQL? JavaScript? HTML? Python?

I don't think that's a problem you can solve in a generic way.

**Comment by prb** [comment]
@joschi I agree that it's a problem without a generic solution, other than perhaps to insist (probably futilely) that UI developers write clean, safe code...  In this case, the security scanning code is attempting to assess the risk of an XSS issue in that it inspects the JSON bodies for the interaction rather than the content actually delivered to the UI layer.

One option would just be to have a global configuration parameter for all `AbstractParam` and descendants that controls whether input is included with error messages.

**Comment by carlo-rtr** [comment]
I don't see a good way of configuring whether abstract params error messages include the original input other than some static side effect state. 

I'm wondering if it makes sense to show the clients the input they send? Would existing users feel we broke backwards compatibility without it? My guess is no. Perhaps we should just send them the general class of error without the input, then we debug log the input & error

**Comment by jplock** [comment]
@carlo-rtr I'm +1 on that approach

**Comment by jplock** [comment]
Fixed in #1022
