### ISSUE TITLE
Upgrade to Jetty 9.2.9

### ISSUE THREAD

**Issue by sixinli** [dropwizard/dropwizard#899]
Hi, I notice that there's a commit upgrading jetty to 9.2.9. I am wondering when is the expected release date for that change?

Thanks!

**Comment by joschi** [comment]
You're referring to commit 071b8104c0cf788264594899386ea5bfbf28d910.

There is currently no fixed date for Dropwizard 0.8.0 or 0.8.0-rc5 but we try to release it in the first weeks of March.
