### ISSUE TITLE
Port binding for tests could fail more transparently

### ISSUE THREAD

**Issue by carlo-rtr** [dropwizard/dropwizard#900]
I forgot I had a ruby unicorn server running locally on port 8080. I then preceded to run DW test suite.
DropwizardAppRuleWithoutConfigTest failed, stating that there wasn't message body provider for Map with mime type of html. I then proceeded to fitz with maven as travis CI said master was OK. I was really confused until I debugged some more, and realized the test was actually receiving a response from the already running server which the client (test) didn't understand.  For some reason, jetty doesn't throw an exception on binding to the port already in use. I suspect it's because one is IPv4 and the other is IPv6, but I'm not sure. I don't think this is a big issue. I just wanted to share my story, and see if anyone knew why the double binding didn't result in an exception.

=> lsof -i :8080
COMMAND   PID         USER   FD   TYPE            DEVICE SIZE/OFF NODE NAME
ruby    50344 carlobarbara    9u  IPv4 0x11cd9d75f1dfc8d      0t0  TCP *:http-alt (LISTEN)
ruby    50364 carlobarbara    9u  IPv4 0x11cd9d75f1dfc8d      0t0  TCP *:http-alt (LISTEN)
java    51420 carlobarbara  119u  IPv6 0x11cd9d769b8483d      0t0  TCP *:http-alt (LISTEN)

**Comment by eternal0** [comment]
Probably a good plan of action, to mitigate this from happening in the future is in addition to the rule being able to return what port it bound to, it should also be able to return what address it bound to

**Comment by nickbabcock** [comment]
I think #1765, while not addressing these concerns exactly, provide good enough workaround by not having tests bind to 8080 or 8081. Let me know if otherwise.
