### ISSUE TITLE
Upgrade Jetty version to 12.x.x 

### ISSUE THREAD

**Issue by nabeelq** [dropwizard/dropwizard#9015]

**Comment by joschi** [comment]
Dropwizard 5.0.0 will be released with support for Jetty 12.

https://github.com/dropwizard/dropwizard/pulls?q=is%3Apr+%22jetty.version+to+v12%22+is%3Amerged+milestone%3A5.0.0

**Comment by nabeelq** [comment]
@joschi when it will be released, can you please confirm the date ?

**Comment by joschi** [comment]
@nabeelq There is no release date for Dropwizard 5.
