### ISSUE TITLE
Is metrics in metric-graphite thread safe?

### ISSUE THREAD

**Issue by sweetest** [dropwizard/dropwizard#905]
Can I use only one meter instance as a static variable and use that throught objects?

seems like there's not any mention about thread-safety explicitly, nor the 'synchronized' code inside Meter.mark()

**Comment by joschi** [comment]
Dropwizard is using the [Metrics](https://github.com/dropwizard/metrics) library underneath. Better ask that question on the [mailing list](https://groups.google.com/forum/#!forum/metrics-user).
