### ISSUE TITLE
BouncyCastle version mismatch

### ISSUE THREAD

**Issue by Athou** [dropwizard/dropwizard#9072]
Hi,

I'd like to add a unit test to the feed fetcher of [CommaFeed](https://github.com/Athou/commafeed/) to make sure invalid SSL certificates are ignored.
For this, I'm using [MockServer](https://github.com/mock-server/mockserver), which dynamically generates a self-signed SSL certificate on the first HTTPS access to any URL, using BouncyCastle.

When I add the following test to [HttpGetterTest](https://github.com/Athou/commafeed/blob/master/commafeed-server/src/test/java/com/commafeed/backend/HttpGetterTest.java) however, I get the following error:

	@Test
	void ignoreInvalidSsl() throws Exception {
		this.mockServerClient.when(HttpRequest.request().withMethod("GET")).respond(HttpResponse.response().withBody("ok"));

		HttpResult result = getter.getBinary("https://localhost:" + this.mockServerClient.getPort(), TIMEOUT);
		Assertions.assertEquals("ok", new String(result.getContent()));
	}
	
	ERROR [MockServer-EventLog0] [MockServerEventLog:113] exception creating SSL context for serversphincsPlus_shake_256 java.lang.NoSuchFieldError: sphincsPlus_shake_256
	at org.bouncycastle.operator.DefaultSignatureAlgorithmIdentifierFinder.<clinit>(Unknown Source)
	at org.bouncycastle.operator.jcajce.JcaContentSignerBuilder.build(Unknown Source)
	at org.mockserver.socket.tls.bouncycastle.BCKeyAndCertificateFactory.signCertificate(BCKeyAndCertificateFactory.java:336)
	at org.mockserver.socket.tls.bouncycastle.BCKeyAndCertificateFactory.generateLeafCert(BCKeyAndCertificateFactory.java:323)
	at org.mockserver.socket.tls.bouncycastle.BCKeyAndCertificateFactory.buildAndSavePrivateKeyAndX509Certificate(BCKeyAndCertificateFactory.java:213)
	at org.mockserver.socket.tls.NettySslContextFactory.createServerSslContext(NettySslContextFactory.java:189)
	
This seems to be [caused by mismatching versions](https://stackoverflow.com/questions/60854300/bouncycastle-signature-creation-java-lang-nosuchfielderror-xmss-sha256ph) of different artifacts of BouncyCastle. Indeed, MockServer pulls BouncyCastle version 1.72 and `dropwizard-dependencies` pulls version 1.77, but only for `bcprov-jdk18on`.

![image](https://github.com/user-attachments/assets/ffd98bff-82fe-4418-9f1b-4dfbe1c2ea32)

If I explicitely specify the same version for both artifacts, the error goes away, but then I'm out of sync with `dropwizard-dependencies`

		<dependency>
			<groupId>org.bouncycastle</groupId>
			<artifactId>bcprov-jdk18on</artifactId>
			<version>1.77</version>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>org.bouncycastle</groupId>
			<artifactId>bcpkix-jdk18on</artifactId>
			<version>1.77</version>
			<scope>test</scope>
		</dependency>
		
Would it make sense for dropwizard to also manage the version of `bcpkix-jdk18on` in `dropwizard-dependencies` since those 2 artifacts seem to need to have the same version? Do you have another idea?

Thanks!

**Comment by joschi** [comment]
We won't add any unused dependencies to the `dropwizard-dependencies` BOM.

For the time being, you could/should declare the other BC dependencies required for your tests with MockServer manually.

This being said, if there was a BOM for BouncyCastle, you could use that.

Please vote for it at https://github.com/bcgit/bc-java/issues/899. 😃
