### ISSUE TITLE
make metrics fail harder?

### ISSUE THREAD

**Issue by brianwawok** [dropwizard/dropwizard#912]
In DW 0.8 RC2 and 5.

My config looked like:

    metrics:
      reporters:
        - type: graphite
          host: {{graphite_host}}
          port: {{graphite_port}}
          prefix: {{graphite_prefix}}.

And nothing happened. Saw no log or warning or metrics.

I changed my config to include

    frequency: 60 seconds

And everything started working.  Not totally sure why.. 

If frequency IS required, it should be added to the Graphite Reporter part of the docs. I see it listed as defaulting to 1 second, but I did not experience this.

 If it is not required, then maybe something is amiss? 

 In either case, would love some info level debugging on what the frequency for metrics is set to, and maybe a warn if I have a metric that will never run for whatever reason,.

**Comment by prb** [comment]
The docs and code are inconsistent, too...

"1 second" https://github.com/dropwizard/dropwizard/blob/2655ac703a0f6ddb4eae933a74dae3d12fde287f/dropwizard-metrics/src/main/java/io/dropwizard/metrics/MetricsFactory.java#L29

"1 minute" https://github.com/dropwizard/dropwizard/blob/2655ac703a0f6ddb4eae933a74dae3d12fde287f/dropwizard-metrics/src/main/java/io/dropwizard/metrics/MetricsFactory.java#L44

**Comment by arteam** [comment]
Thanks, @prb, for catching this. I've clarified the correct frequency value in the docs.

About the actual issue: no, frequency is not required for reportes. If it's not set, then the default one (1 minute) will be used.
I don't have a Graphite instance now to test, but console and CSV file reporters work fine for me without setting a frequency. After 1 minute the metrics show up.
I guess, maybe users expect that metrics will be reported immediately after startup? Should we change that?

**Comment by brianwawok** [comment]
I still vote for a log of "Using frequency of X for metric Y".. maybe info level for your overall frequency, then debug for each metric...

**Comment by nickbabcock** [comment]
Closing this because [the code](https://github.com/dropwizard/dropwizard/blob/master/dropwizard-metrics/src/main/java/io/dropwizard/metrics/MetricsFactory.java#L83-L94) will warn users if something is set up incorrectly and #1514 is for discussing possibilities to informing users of what config values are used at runtime.
