### ISSUE TITLE
DropwizardExtensionsSupport does not work with the Junit5 1.11

### ISSUE THREAD

**Issue by friscoMad** [dropwizard/dropwizard#9191]
This commit in Junit 5.11: https://github.com/junit-team/junit5/commit/abb5ed16be3a9ce552f4a45c11264ded608ae9da breaks the usage in https://github.com/dropwizard/dropwizard/blob/81d6b6ef8b92f8a67ead232a15ad799602a2e9b1/dropwizard-testing/src/main/java/io/dropwizard/testing/junit5/DropwizardExtensionsSupport.java#L149

I am not sure how it would be possible to have some code that works for pre-5.11 and 5.11 but as it is right now it makes impossible to update the applications to use Junit 5.11 and keep the usage of the Junit Dropwizard extension

**Comment by pstackle** [comment]
FYI: https://github.com/dropwizard/dropwizard/pull/9157
