### ISSUE TITLE
BasicAuthProvider does not exist in 0.8 version

### ISSUE THREAD

**Issue by edpichler** [dropwizard/dropwizard#933]
The example on http://dropwizard.io/0.8.0/docs/manual/auth.html#protecting-resources is not working.
The BasicAuthProvider does not exist in 0.8 version.

Same problem with class Responses.

Is there any manual to migrate from 0.7 to 0.8?

**Comment by arteam** [comment]
This is true. `ChainedAuthFactory` example was contributed before update to Jersey 2 and now outdated. We need to rewrite that.

We don't have a migration tutorial, but there is a post in the *dropwizard-dev* [mailing list](https://groups.google.com/forum/#!topic/dropwizard-dev/VInOW_ebiAc) with some hints about obstacles during migration.

**Comment by edpichler** [comment]
I will wait for a more stable version, with the proper documentation. I'm just deploying to production.

**Comment by arteam** [comment]
Fair enough. 
Anyway, thanks for reporting issues. It makes Dropwizard better.
