### ISSUE TITLE
Provide object mapper with Jackson JDK8 Module

### ISSUE THREAD

**Issue by willwhitaker** [dropwizard/dropwizard#935]
To provide support for JDK datatypes included in version 8:

https://github.com/FasterXML/jackson-datatype-jdk8

Is this just as simple as adding the dependency and registering the module inside io.dropwizard.jackson.Jackson?

**Comment by arteam** [comment]
We have a separate [project|https://github.com/dropwizard/dropwizard-java8\ with Java 8 features.
It should support Optional and JSR-310 JDK datatypes for Jackson (not by official FasterXML library, though).

**Comment by joschi** [comment]
[dropwizard-java8 0.8.0-2](https://github.com/dropwizard/dropwizard-java8) switched to the official Jackson JDK8 module.
