### ISSUE TITLE
.io domain retirement

### ISSUE THREAD

**Issue by clarkbreyman** [dropwizard/dropwizard#9411]
It looks like the io (Indian Ocean) [TLD may be going away](https://every.to/p/the-disappearance-of-an-internet-domain). It would be good to have a definitive position on changes to the package prefix as well as public website.

**Comment by joschi** [comment]
> The IANA may fudge its own rules and allow .io to continue to exist. Money talks, and there is a lot of it tied up in .io domains. However, the history of the USSR and Yugoslavia still looms large, and the IANA may feel that playing fast and loose with top-level domains will only come back to haunt it.

I doubt that the `.io` TLD will really vanish but probably some commercial entity will step in and take over stewardship.

In other words, I'd sit that one out. 😬

**Comment by joschi** [comment]
Let's move any further discussion to https://github.com/dropwizard/dropwizard/discussions/9412. 😄
