### ISSUE TITLE
Remove Afterburner Support

### ISSUE THREAD

**Issue by clarkbreyman** [dropwizard/dropwizard#9415]
Given the Java 11 baseline, is it time to remove Afterburner support in Jackson for DW 4.0 +

**Comment by joschi** [comment]
We won't remove it in Dropwizard 4.x, but it already has been removed in the Dropwizard 5.x development branch as part of https://github.com/dropwizard/dropwizard/pull/8038.

Please note that Jackson Afterburner is only used over Jackson Blackbird if explicitly added as a dependency.
https://github.com/dropwizard/dropwizard/blob/v4.0.9/dropwizard-jackson/src/main/java/io/dropwizard/jackson/Jackson.java#L77-L80
