### ISSUE TITLE
Missing dropwizard-testing-junit4 for release 4.0.9

### ISSUE THREAD

**Issue by amelentyev** [dropwizard/dropwizard#9426]
Hi!

Release v4.0.9 was tagged a couple of days ago but it seems that `io.dropwizard.modules:dropwizard-testing-junit4:jar:4.0.9` isn't available, is that expected?

Thanks
Andrey

**Comment by joschi** [comment]
It's 2024, time to migrate to JUnit 5. 😉
https://docs.openrewrite.org/running-recipes/popular-recipe-guides/migrate-from-junit-4-to-junit-5

- https://github.com/dropwizard/dropwizard-testing-junit4/releases/tag/v3.0.9
- https://github.com/dropwizard/dropwizard-testing-junit4/releases/tag/v4.0.9

**Comment by amelentyev** [comment]
Are you pointing me to the release tags because there's some mention of junit4 module not being available anymore? Because I don't believe there is, and even if there were, that'd be a somewhat strange thing to do in a patch release.

As it happens, we use JUnit 4 not because we like it, but because one of the other dependencies we use ships JUnit 4 test tooling but not 5.

**Comment by brentryan** [comment]
Have you read the upgrade guide? 

https://www.dropwizard.io/en/stable/manual/upgrade-notes/upgrade-notes-3_0_x.html
