### ISSUE TITLE
CachingAuthenticator caches Optional.absent()

### ISSUE THREAD

**Issue by brentryan** [dropwizard/dropwizard#947]
Currently the CachingAuthenticator loads Optional.absent() into the cache which means that if you had a failed credential for whatever reason then it gets cached as absent() by the underlying authenticator.

Instead I think this should be updated to something like:

            @Override
            public Optional<P> load(K key) throws Exception {
                cacheMisses.mark();

                //Only cache successful operations, not failures
                Optional<P> g = underlying.authenticate(key);
                if (g.isPresent()) {
                    return g;
                }

                throw new AuthenticationException("Failed to load security context into cache");
            }

Or at the very least, it should be an option to not cache these failures.

Or would be prefer that each individual authenticator throw an exception instead of returning Optional.absent() ?

**Comment by brentryan** [comment]
Just to add a little more context to the problem as well... This could really be considered a bug in OAuthFactory.

https://github.com/dropwizard/dropwizard/blob/5e686e772364264ab0e41357e44d6ba054a4b117/dropwizard-auth/src/main/java/io/dropwizard/auth/oauth/OAuthFactory.java#L19

If you use this code with the CachingAuthenticator it actually presents a pretty big security hole.  You could wind up hitting a resource with your bearer token that you have permissions to access and then that credential gets cached.  You then hit another resource that you don't have permissions to but because your first call was cached it will actually return the cached credential and let you in anyways.

So I'm just trying to figure out what the preferred fix is here for these issues?  Any thoughts?

**Comment by jplock** [comment]
I agree that we shouldn't be caching failures, I'll take a look at this.  Thanks for reporting it!
