### ISSUE TITLE
Custom ExceptionMapper not invoked when Hibernate rollback

### ISSUE THREAD

**Issue by paukiatwee** [dropwizard/dropwizard#949]
Using DW 0.8.0, Java 8

I have one custom exception mapper to handle `hibernate` exception:
```java
import org.hibernate.exception.ConstraintViolationException;


@Provider
public class SQLConstraintViolationExceptionMapper implements ExceptionMapper<ConstraintViolationException> {
    ....
}
```

I registered the mapper https://github.com/paukiatwee/budgetapp/blob/master/src/main/java/io/budgetapp/BudgetApplication.java#L143

When `org.hibernate.exception.ConstraintViolationException` exception is thrown when foreign key violation occurred, `SQLConstraintViolationExceptionMapper` is no called.

You can reproduce the problem by running this integration test https://github.com/paukiatwee/budgetapp/blob/master/src/test/java/io/budgetapp/resource/CategoryResourceIT.java#L65

This might caused by https://github.com/dropwizard/dropwizard/blob/master/dropwizard-hibernate/src/main/java/io/dropwizard/hibernate/UnitOfWorkApplicationListener.java#L87 exception not handled by container.

Working fine for DW 0.7.0

**Comment by arteam** [comment]
I can confirm this issue.

Unfortunately, I can't give a solution now. The problem lies in the update to Jersey 2 in 0.8.0.
Seems to be `UnitOfWorkApplicationListener` doesn't work with exception mappers.

**Comment by arteam** [comment]
I've made another look and can give a workaround for you.

In 0.8.0 in `UnitOfWorkApplicationListener` we commit a Hibernate transaction after a request has been processed and response processing has started. We don't have an event like `BEFORE_RESOURCE_METHOD_FINISHED`, so we are forced to make a commit (with possible errors) during response processing.

In the Jersey architecture at this stage exception mappers are not taken into account, but mappers that implement the interface [ResponseErrorMapper](https://github.com/jersey/jersey/blob/master/core-server/src/main/java/org/glassfish/jersey/server/spi/ResponseErrorMapper.java) are.
They are also not processed by default, so you need to enable this feature in configuration:
````java
environment.jersey().property(ServerProperties.PROCESSING_RESPONSE_ERRORS_ENABLED, true);
````

After that you can refactor your exception mapper something like that:
````java
@Provider
public class SQLConstraintViolationExceptionMapper implements ResponseErrorMapper {

    private static final Logger LOGGER = LoggerFactory.getLogger(SQLConstraintViolationExceptionMapper.class);

    @Override
    public Response toResponse(Throwable e) {
        return Response.status(Response.Status.BAD_REQUEST)
                .entity(Collections.singletonMap("errors",
                        Collections.singletonMap("message", getMessage((ConstraintViolationException) e))))
                .build();
    }

    private List<String> getMessage(ConstraintViolationException e) {

        LOGGER.error(e.getMessage(), e);

        // a hack to convert exception to friendly error message
        if ("fk_budgets_categories".equalsIgnoreCase(e.getConstraintName())) {
            return Collections.singletonList("Failed to delete category due to references to existing budget(s).");
        } else if ("fk_transactions_budgets".equalsIgnoreCase(e.getConstraintName())) {
            return Collections.singletonList("Failed to delete budget due to references to existing transaction(s).");
        }
        return Collections.singletonList(e.getMessage());
    }
}
````

Could you test this approach? If it works for you, I will add information about response error mappers
into the 0.8.0 migration [guide](https://github.com/dropwizard/dropwizard/wiki/Upgrade-guide-0.7.x-to-0.8.x).

**Comment by paukiatwee** [comment]
The issue is fixed after update based on your comment [commit](https://github.com/paukiatwee/budgetapp/commit/bffd10d56e5b21725c185d3ab8f908696be172a8).


However, I think the proper way to fix this is to rethrow exception as `org.glassfish.jersey.server.internal.process.MappableException` as the doc mention:
```
 * A runtime exception that contains a cause, a checked or runtime exception,
 * that may be mapped to a {@link javax.ws.rs.core.Response} instance.
 * <p>
 * The runtime will catch such exceptions and attempt to map the cause
 * exception to a registered {@link javax.ws.rs.ext.ExceptionMapper} that
 * provides an appropriate {@link javax.ws.rs.core.Response} instance.
```

**Comment by arteam** [comment]
That actually seems like a better solution.  Jersey will rethrow the original exception if it's umapped and map to `Response` if it's mapped. Thanks for pointers.

I will try to create a PR for fixing that.
