### ISSUE TITLE
Possible reflective cross site scripting in the io.dropwizard.validation.ConstraintViolations

### ISSUE THREAD

**Issue by WarFox** [dropwizard/dropwizard#953]
We have come across a problem in when doing JSR-303 validation, due to dropwizard `ConstraintViolations` adding the InvalidValue back in the message.

The following request payload,
```json
{
   "url": "/address/<script>alert(2)</script>"
}
```
will result in the following error
```json
{
"errors": [
"url must be a valid URL (was /address/<script>alert(2)</script>)"
]
}
```

We don't want the "was" part.

Based on the investigation we found that it is being appended in the `ConstraintViolations.format()` method.

```java
public static <T> String format(ConstraintViolation<T> v) {
    if (v.getConstraintDescriptor().getAnnotation() instanceof ValidationMethod) {
        final ImmutableList<Path.Node> nodes = ImmutableList.copyOf(v.getPropertyPath());
        final ImmutableList<Path.Node> usefulNodes = nodes.subList(0, nodes.size() - 1);
        final String msg = v.getMessage().startsWith(".") ? "%s%s" : "%s %s";
        return String.format(msg,
                             Joiner.on('.').join(usefulNodes),
                             v.getMessage()).trim();
    } else {
        return String.format("%s %s (was %s)",
                             v.getPropertyPath(),
                             v.getMessage(),
                             v.getInvalidValue());
    }
}
```

Is there any way that we can avoid the `invalidValue` from being attached to the message?

If not can we have a feature switch for that?

**Comment by prb** [comment]
See also #892.

**Comment by WarFox** [comment]
The issue I reported could be rectified if the `invalidValue` is not printed. 

Is it something that could be considered? 

I don't see a point in printing out the value that was sent in the request payload.

**Comment by piefel** [comment]
Funny, I was just about to prepare a patch that used that very function to log invalid messages on the server side. On the client, it probably is not as necessary, since the client might know what it just sent.

**Comment by WarFox** [comment]
Please have a look at the pull request https://github.com/dropwizard/dropwizard/pull/1001/
and advice if it is okay.
