### ISSUE TITLE
Allow to customize MetricsRegistry

### ISSUE THREAD

**Issue by mabn** [dropwizard/dropwizard#956]
I'd like to customize MetricRegistry. It's used to create all the timers and histograms, but I don't like the defaults.
In particular I don't like the fact that MetricBuilder for timers uses default constructor for Timer, which in turn builds a timer backed by ExponentiallyDecayingReservoir.

Why is it bad? Because ExponentiallyDecayingReservoir;
1) "[default setting] heavily biases the reservoir to the past 5 minutes of measurements". I report every 30 seconds, the remaining 4.5 min just skews the results.
2) when nothing is reported the values for percentiles stay on the same level indefinitely instead of dropping to 0 or null.

There are better options, e.g. HdrHistogramResetOnSnapshotReservoir, but right now it's not possible to plug it in.

**Comment by joschi** [comment]
@mabn Thanks for reporting this. Please create an issue for your feature request(s) in the issue tracker for the Metrics project at https://github.com/dropwizard/metrics/issues.

**Comment by mabn** [comment]
I think you misunderstood my problem. Metrics library already allows to create various kinds of metrics via MetricsRegistry.getOrAdd(name, MetricBuilder), or through subclassing via overriding MetricsRegistry.timer(), .meter(), etc.

The issue is that dropwizard creates the instance via "new MetricsRegistry()" which makes it impossible to use different implementation. It also uses .timer(), .meter() methods instead of the ones accepting MetricBuilder.
If MetricRegistry was created through a factory (like e.g. ServerBuilder) or set of MetricBuilders was defined via configuration it would be possible to alter the behavior. Right now it's not.
Changes in Metrics won't help here.

**Comment by arteam** [comment]
I think that the problem not in Metrics, but that Dropwizard `Boostrap` hardcodes creation an instance of `MetricRegistry` and users can't override its behaviour with something like this:

````java
metricRegistry = new MetricRegistry(){
    @Override
    public Histogram histogram(String name) {
        return new Histogram(new HdrHistogramResetOnSnapshotReservoir());
    }

    @Override
    public Timer timer(String name) {
        return new Timer(new HdrHistogramResetOnSnapshotReservoir());
    }
};
````

**Comment by arteam** [comment]
One possible solution:

* Create `MetricRegistryFactory` and make `Boostrap` depends on it.
* Add facility to set a custom factory to `Boostrap` in `Application#initialize`
* Add JVM metrics and to the instance of `MetricRegistry` and `JmxReporter` *after* initialization.

**Comment by glennmcallister** [comment]
I have to agree that this has been closed prematurely. While the way we have managed the `MetricRegistry` previously does work in the majority of cases, there are times when people will need to override them.
