### ISSUE TITLE
Honor Jersey Client Timeout Defaults

### ISSUE THREAD

**Issue by nickbabcock** [dropwizard/dropwizard#960]
According to the [latest Jersey configuration documentation][jt], a client has a read and connect timeout of infinity. Dropwizard assumes a default read and connect timeout for HttpClient and Jersey's client of 500 milliseconds. This was not obvious, especially because I was led down the path of trying to set Jersey Client Properties on the Builder, and didn't realize until later that [the docs say](https://github.com/dropwizard/dropwizard/blob/9c7adb21ac5abd5768f029ca1b2331e4b4e29ed9/dropwizard-client/src/main/java/io/dropwizard/client/JerseyClientBuilder.java#L103-L116)

> WARNING:The default connector ignores Jersey properties

It took me an embarrassingly long time to realize how everything was connected (and that I could change the timeouts with a yaml change), and I'd like to save some time for those in the future.

Solutions:

1. Mention in docs that the timeouts are in effect (which deviates from the default). Provide a sentence stating how to change them.
2. Change the code such that Jersey configuration defaults are actually the default for the Jersey Client. I understand if there is hesitation towards this change as this may break applications that implicitly rely on the 500 millisecond timeout (which is currently the default).

If there are any other deviations, it would probably be fruitful to document them too.

Which solution is preferable?

[jt]: https://jersey.java.net/documentation/latest/appendix-properties.html#appendix-properties-client

**Comment by jplock** [comment]
This should be fixed as part of https://github.com/dropwizard/dropwizard/pull/939

**Comment by nickbabcock** [comment]
Ok thank you for bringing that to my attention, I'm unsure if this issue completely resolved yet. The default timeouts, while being able to be changed (:+1:), are still overridden. I'm fine with it being overridden, as long it is documented. The documentation should definitely state that to change the jersey timeouts to use `using(JerseyClientConfiguration configuration)` and not `withProperty(String propertyName, Object propertyValue)`. I know the API says this, but considering it's a "gotcha", it should probably be stated in the main Client documentation

**Comment by jplock** [comment]
Would you like to submit a PR correcting the documentation?

**Comment by nickbabcock** [comment]
Yup, certainly, I can.
