### ISSUE TITLE
Upgrade to jdk 8

### ISSUE THREAD

**Issue by carlo-rtr** [dropwizard/dropwizard#962]

**Comment by carlo-rtr** [comment]
https://github.com/dropwizard/dropwizard/issues/1060

**Comment by kmejka** [comment]
@carlo-rtr I think you can close this issue now.

**Comment by joschi** [comment]
@kmejka Why?

**Comment by kmejka** [comment]
@joschi I thought the issue #1060 was about that (a duplicate perhaps?), and it's closed. It is even mentioned there as a duplicate. Unless I understood the purpose of the task differently (it's got no description). In that case I''m wrong :).
I just wanted to help out, I know that issue trackers tend to get messy with old tasks which don't need to -open at all.

**Comment by joschi** [comment]
The purpose of this issue is to serve as a reminder to set the JDK baseline for Dropwizard 1.0.0 to Java 8 and to merge the [dropwizard-java8](https://github.com/dropwizard/dropwizard-java8) project into the main repository.

**Comment by kmejka** [comment]
Ok, well then you should disregard my comment :)

**Comment by jplock** [comment]
Can this be closed after https://github.com/dropwizard/dropwizard/commit/e4380dcfa457a75ef2e323411f4f69d8dd556f6e was merged or was there more things we wanted to do?

**Comment by joschi** [comment]
@jplock I'd pull in the classes from  dropwizard-java8 before closing this issue.
