### ISSUE TITLE
Repeatable Benchmarking

### ISSUE THREAD

**Issue by carlo-rtr** [dropwizard/dropwizard#963]
We need a way to identify macro performance degradations. Ideally this would be part of the build process. It may also be worth creating doing micro benchmarking.

**Comment by JonMR** [comment]
Is the goal to have this fully automated and part of CI or to be run manually during the RC phase of development?

Fully automated is obviously more difficult.  I don't think Travis CI gives any guarantees about VM sizing.

**Comment by carlo-rtr** [comment]
I don't think it needs to be a hard requirement that it runs with the build. My only concern is that if it doesn't happen in some automated way, there may be some lag before degradations are caught. This obviously makes it harder to identify the culprit. If you have ideas, I'm all ears.

**Comment by carlo-rtr** [comment]
One think we should do is make sure that empower benchmark is using the latest code.

https://www.techempower.com/benchmarks/

https://github.com/TechEmpower/FrameworkBenchmarks/tree/master/frameworks/Java/dropwizard

**Comment by zloster** [comment]
I've added a [pull request](https://github.com/TechEmpower/FrameworkBenchmarks/pull/2357) for updating the test code to dropwizard 1.0.3 from 0.8.1 at FrameworkBenchmark project. The results from my local test look very promising.
