### ISSUE TITLE
Ease deployment process to AWS and Heroku

### ISSUE THREAD

**Issue by carlo-rtr** [dropwizard/dropwizard#965]

**Comment by axelfontaine** [comment]
Hi everyone,

I just wanted to let you know that we've published a three part article on how to build a Continuous Deployment pipeline from GitHub to AWS for Dropwizard applications, using Travis CI and Boxfuse: https://boxfuse.com/blog/dropwizard-aws.html

It makes it a breeze to get up and running and it comes with out of the box deep integration for the Dropwizard config format with autodetection of ports and healthchecks (https://boxfuse.com/docs/payloads/dropwizard.html).

The entire setup we describe is 100% free, very reliable and very easy to get started with.

Best regards,
Axel

**Comment by carlo-rtr** [comment]
Thanks for the info @axelfontaine. But for this issue, we are looking for something that scales with the open source model. Your solution, from what I read on your site, is more freemium. Free for a few, but paid after that.  Correct me if I'm wrong. We are looking for a completely free and open source solution.

**Comment by axelfontaine** [comment]
Hi @carlo-rtr , first of all let's put things into perspective: neither Heroku nor AWS are completely open source nor do they offer you a completely free solution. You get a small free tier with enough capacity for a single low volume app (limited to 1 year for AWS).

Now as for Boxfuse you are absolutely correct in saying that (just like AWS & Heroku) it is based on a freemium model, albeit for *commercial* applications. But even for those we do have a free plan that matches the AWS free tier, so the overall solution is completely free forever for applications that fit that.

As for open source, we offer Boxfuse for free: https://boxfuse.com/pricing.html#open-source (We strong believers in open source and are in fact running a successful open source project ourselves which will break the 1M download mark in 2015: https://github.com/flyway/flyway)

Boxfuse is by far the easiest way to get Dropwizard apps on AWS. You can literally go from Dropwizard jar to brand new minimal AMI to EC2 instance in under 60 seconds with a single command, and all ports and healtchchecks in ELBs & security groups will be configured automatically based on the info extracted from your Dropwizard yaml file.

In part 3 of our Dropwizard blog post series (https://boxfuse.com/blog/dropwizard-aws-travisci.html) we also showed how you can set up a full continuous deployment pipeline for Dropwizard to AWS using an open-source project on GitHub, Travis CI & Boxfuse. All together for 0 dollars forever (except for AWS after 1 year when the free tier expires).

Give it a try and you'll be pleasantly surprised :-)

Cheers
Axel

**Comment by carlo-rtr** [comment]
@axelfontaine sorry if it seemed I was questioning your commitment to open source, I wasn't. I know AWS and Heroku are not completely open source, but when I see their fee I know it's going towards hardware.  When it comes to paying for scaling deployment, I feel like I would be paying for convenience and tooling.  In some cases that makes sense. I'm sure there will be people who find your service useful, and I bet the product is great.

This issue is about making sure than an alternative also exists. Some set of scripts that can be used to manage deploys, scale without cost, or require auxiliary services.

**Comment by axelfontaine** [comment]
@carlo-rtr No worries. I never took anything personally, I was just trying to clarify what we're offering.

However I feel you should think again about AWS and Heroku are offering. In fact their entire business is made aroung you *paying for convenience and tooling*. In all you want to do is pay for hardware, you should look at https://www.hetzner.de & http://ovh.com . They will provide you with just the hardware and you get fantastic value. In fact the same machine (say Hetzner EX40 and AWS c3.4xlarge) costs you 10x more on AWS. Why? ... You guessed it: you *pay for convenience and tooling*.

I would go even further and say that AWS+Boxfuse is in fact a lot cheaper than Heroku, when it comes to easily manage, deploys & scale Dropwizard applications in the cloud. :-)

**Comment by andyrexford** [comment]
@carlo-rtr Just stumbled over this issue because AWS deployment caught my eye.  We have a fully automated pipeline (git post commit hooks, jenkins, aws opsworks) that we've muscled through with chef recipes but are looking to improve it.  Do you have more details on what you are looking to achieve here?

**Comment by greenreign** [comment]
@carlo-rtr Just stumbled over this issue because AWS deployment caught my eye.  We have a fully automated pipeline (git post commit hooks, jenkins, aws opsworks) that we've muscled through with chef recipes but are looking to improve it.  Do you have more details on what you are looking to achieve here?
