### ISSUE TITLE
dropwizard-jdbi: Binding joda-time DateTime objects to SQL uses JVM timezone, not the timezone in the DateTime object

### ISSUE THREAD

**Issue by mattmcclain** [dropwizard/dropwizard#968]
There is a bug in io.dropwizard.jdbi.args.JodaDateTimeArgument that appears when the JVM timezone differs from the database timezone. This class uses:
  statement.setTimestamp(position, new Timestamp(value.getMillis()));
to bind a DateTime ("value" here) to a PreparedStatement ("statement"), which creates a Timestamp using the JVM's timezone instead of the DateTime object's timezone.

The solution seems to be to use the setTimestamp method that also takes a Calendar argument (http://docs.oracle.com/javase/7/docs/api/java/sql/PreparedStatement.html#setTimestamp%28int,%20java.sql.Timestamp,%20java.util.Calendar%29).

**Comment by arteam** [comment]
Could you, please, provide an example of failing behaviour?

`value.getMillis()` returns a correct epoch, depending on `DateTime` timezone. A JDBC driver then pass this epoch to a database. What perils of such conversion?

**Comment by mattmcclain** [comment]
Of course. I was using dropwizard-jdbi to query for rows in an Amazon Redshift DB with timestamps that fell on a particular date (1/1/2015) in UTC (Redshift timestamps are always in UTC). So, I created the DateTime objects with UTC timezone and binded them to the SQL using the SQL objects API. The returned rows, however, did all fall on the date I wanted. Instead of getting rows between 1/1/2015 00:00:00.000Z and 1/2/2015 00:00:00.000Z, I got rows between 12/31/2014 18:00:00.000Z and 1/1/2015 18:00:00.000Z. So, both of the binded dates got shifted back 6 hours, and my JVM's timezone was US Central (UTC-6). When I passed the JVM argument "-Duser.timezone=UTC", I got back the correct rows.

To answer your 2nd question, there is no peril in the conversion from DateTime to milliseconds. The peril happens after this, either in converting the milliseconds to the Timestamp object (in "new Timestamp(value.getMillis()") or converting the Timestamp into a binary value that's sent to the database - I'm not sure which one, but my guess is the latter. Either way, the root cause is that Timestamp is a thin wrapper around java.util.Date, which is known to use the JVM timezone in some unexpected situations.

**Comment by arteam** [comment]
Sorry, I didn't manage to reproduce the problem.

I used a Postgres database in my local timezone - `Europe/Moscow [+03:00]` and a simple test case:

````sql
CREATE TABLE flights (
  flight_id         VARCHAR(5)               NOT NULL PRIMARY KEY,
  departure_airport VARCHAR(3)               NOT NULL,
  arrival_airport   VARCHAR(3)               NOT NULL,
  departure_time    TIMESTAMP WITH TIME ZONE NOT NULL,
  arrival_time      TIMESTAMP WITH TIME ZONE NOT NULL
)
````

````java
public class TestTZ {

    @Test
    public void test(){
        System.out.printf("Now: %s %n", new DateTime());

        DBI dbi = new DBI("jdbc:postgresql://127.0.0.1:5432/fldb", "user", "pass");
        dbi.registerArgumentFactory(new JodaDateTimeArgumentFactory());
        dbi.registerMapper(new JodaDateTimeMapper());
        dbi.setSQLLog(new PrintStreamLog());

        Handle handle = dbi.open();
        handle.execute("DROP TABLE IF EXISTS flights");
        handle.createScript("schema.sql").execute();

        FlightDao flightDao = handle.attach(FlightDao.class);

        DateTimeFormatter fmt = ISODateTimeFormat.dateTimeNoMillis();
        flightDao.insert("C1671", "ORD", "DUS",
                fmt.parseDateTime("2015-04-01T06:00:00-05:00"),
                fmt.parseDateTime("2015-04-01T21:00:00+02:00"));

        DateTime departureTime = flightDao.getDepartureTime("C1671");
        System.out.printf("Departure time: %s %n", departureTime);

        DateTime arrivalTime = flightDao.getArrivalTime("C1671");
        System.out.printf("Arrival time: %s %n", arrivalTime);

        handle.close();
    }

    public interface FlightDao {

        @SqlUpdate("INSERT INTO flights(flight_id, departure_airport, arrival_airport,departure_time , arrival_time) " +
                   "VALUES (:flight_id, :departure_airport, :arrival_airport, :departure_time, :arrival_time)")
        void insert(@Bind("flight_id") String flightId, @Bind("departure_airport") String departureAirport,
                    @Bind("arrival_airport") String arrivalAirport,
                    @Bind("departure_time") DateTime departureTime , @Bind("arrival_time") DateTime arrivalTime);

        @SqlQuery("SELECT arrival_time FROM flights WHERE flight_id=:flight_id")
        DateTime getArrivalTime(@Bind("flight_id") String flightId);

        @SqlQuery("SELECT departure_time FROM flights WHERE flight_id=:flight_id")
        DateTime getDepartureTime(@Bind("flight_id") String flightId);

    }
}
````

When I ran it with `-Duser.timezone=America/Chicago`, I've got the following output:
````
Now: 2015-04-02T14:59:50.637-05:00 
Handle [org.skife.jdbi.v2.BasicHandle@cc285f4] obtained in 132 millis
batch:[[DROP  TABLE IF EXISTS flights ]] took 21 millis
batch:[[CREATE TABLE flights (   flight_id         VARCHAR(5)               NOT NULL PRIMARY KEY,   departure_airport VARCHAR(3)               NOT NULL,   arrival_airport   VARCHAR(3)               NOT NULL,   departure_time    TIMESTAMP WITH TIME ZONE NOT NULL,   arrival_time      TIMESTAMP WITH TIME ZONE NOT NULL ) ]] took 75 millis
statement:[INSERT INTO flights(flight_id, departure_airport, arrival_airport,departure_time , arrival_time) VALUES (?, ?, ?, ?, ?)] took 15 millis
statement:[SELECT departure_time FROM flights WHERE flight_id=?] took 18 millis
Departure time: 2015-04-01T06:00:00.000-05:00 
statement:[SELECT arrival_time FROM flights WHERE flight_id=?] took 0 millis
Arrival time: 2015-04-01T14:00:00.000-05:00 
Handle [org.skife.jdbi.v2.BasicHandle@cc285f4] released
````

With `-Duser.timezone=UTC`
````
Now: 2015-04-02T20:00:24.544Z 
Handle [org.skife.jdbi.v2.BasicHandle@32d992b2] obtained in 128 millis
batch:[[DROP  TABLE IF EXISTS flights ]] took 17 millis
batch:[[CREATE TABLE flights (   flight_id         VARCHAR(5)               NOT NULL PRIMARY KEY,   departure_airport VARCHAR(3)               NOT NULL,   arrival_airport   VARCHAR(3)               NOT NULL,   departure_time    TIMESTAMP WITH TIME ZONE NOT NULL,   arrival_time      TIMESTAMP WITH TIME ZONE NOT NULL ) ]] took 108 millis
statement:[INSERT INTO flights(flight_id, departure_airport, arrival_airport,departure_time , arrival_time) VALUES (?, ?, ?, ?, ?)] took 13 millis
statement:[SELECT departure_time FROM flights WHERE flight_id=?] took 15 millis
Departure time: 2015-04-01T11:00:00.000Z 
statement:[SELECT arrival_time FROM flights WHERE flight_id=?] took 0 millis
Arrival time: 2015-04-01T19:00:00.000Z 
Handle [org.skife.jdbi.v2.BasicHandle@32d992b2] released
````

And, finally, export from the database returned this:
````csv
flight_id,departure_airport,arrival_airport,departure_time,arrival_time
C1671,ORD,DUS,"2015-04-01 14:00:00.000000","2015-04-01 22:00:00.000000"
````

So for me everything works as expected from different time zones. 

I don't have expeirence with Redshift, so can't say why timestamps were shifted. Also I didn't find the source code of the driver, so that's a black box for me. Maybe you could contact Amazon and ask them for assistance?

However, if you provide a vendor-independent failing test case and a solution, which doesn't break backwards compatibility, I will happily merge it.

**Comment by mattmcclain** [comment]
Artem,
I see that you declare the time columns as "TIMESTAMP WITH TIME ZONE". In Redshift, TIMESTAMPs don't have time zones, so that could be the difference. What happens if you just declare them as TIMESTAMP?

Thanks,
Matt

[Bazaarvoice]

Matthew McClain
Staff Data Scientist
m: 217.721.5606
e: matt.mcclain@bazaarvoice.com<mailto:matt.mcclain@bazaarvoice.com>
Site<http://www.bazaarvoice.com/>  |  Blog<http://www.bazaarvoice.com/blog>  |  Twitter<http://twitter.com/Bazaarvoice>

**Comment by arteam** [comment]
Well, now I see the problem.

When handing SQL `TIMESTAMP` the database doesn't take into account a user time zone during writing, and doesn't convert to the user timezone during reading (by the way, I was wrong that a JDBC driver pass an epoch timestamp, actually it's a string in_ISO 8601_ ).

For example, if you write a date `12-31-2014 18:00:00-06:00` to the database in UTC, it will be
saved as `12-31-2014 18:00:00`. When you read it back in _UTC-06:00_, it will be '12-31-2014 18:00:00-06:00', which is correct, but when you read it UTC, it will be  `12-31-2014 18:00:00Z`,
which probably not the thing you want.

An easy solution, of course, is to advice to users just to switch to `TIMESTAMP WITH TIME ZONE`. 
But I think on an application level we can also give users facility to set a DB time zone during reading and writing dates. For example, it could be useful if a developer is not in a control of the DB schema. 

I will try to create a PR.

**Comment by mattmcclain** [comment]
Artem,
I'm glad that was able to reproduce the issue. Thanks for taking the time to look into this.

Matt

[Bazaarvoice]

Matthew McClain
Staff Data Scientist
m: 217.721.5606
e: matt.mcclain@bazaarvoice.com<mailto:matt.mcclain@bazaarvoice.com>
Site<http://www.bazaarvoice.com/>  |  Blog<http://www.bazaarvoice.com/blog>  |  Twitter<http://twitter.com/Bazaarvoice>

**Comment by pablote** [comment]
I just run into this issue. Is there way a to set the timezone on a per column basis instead of the whole database? I'm currently working against a DB which has datetime columns in different timezones, even within the same table. Thanks.
