### ISSUE TITLE
Vulnerability in jetty-server Dependency (Version 11.0.24) Used in Dropwizard

### ISSUE THREAD

**Issue by irfadkp** [dropwizard/dropwizard#9681]
https://github.com/dropwizard/dropwizard/blob/2dbd8e3704a2753c42c733e0ef180b1631650b07/dropwizard-dependencies/pom.xml#L53

Description
Hello Dropwizard Team,

I wanted to report a concern regarding a known vulnerability in the jetty-server library (org.eclipse.jetty:jetty-server:11.0.24) that is included as a dependency in Dropwizard.

Please make sure support for 12.0.12 jetty in dropwizard 4.x.x and 3.x.x if its possible

The latest release of Dropwizard still relies on this specific version of Jetty, which has reported security vulnerabilities. The secure version of Jetty is 12.0.12, as referenced on the official Jetty artifact page:
[Jetty Server Artifact - mvnrepository.com](https://mvnrepository.com/artifact/org.eclipse.jetty/jetty-server).

As this version of Jetty is embedded in Dropwizard, we are unable to upgrade or override it independently without potentially breaking functionality. This poses a risk for projects using Dropwizard in production, as it leaves them exposed to known security vulnerabilities in the jetty-server dependency.

Steps to Reproduce
Include the latest version of Dropwizard in a project.
Observe the jetty-server version included in the dependency tree (11.0.24).
Refer to known CVEs for this version of Jetty.
Expected Behavior
Dropwizard should use a version of Jetty without known vulnerabilities (e.g., 12.0.12) or provide an alternative configuration to override/upgrade Jetty safely.

Proposed Solution
Please consider upgrading to a secure version of jetty-server (12.0.12) or provide guidance on how users can independently upgrade the Jetty dependency without breaking Dropwizard functionality.

Environment
Dropwizard Version: Latest available
Jetty Version: 11.0.24
Java Version: (Specify your version)
OS: (Specify your OS)
Thank you for addressing this issue! Please let me know if additional details are required.

**Comment by joschi** [comment]
Good news!

https://github.com/jetty/jetty.project/security/advisories/GHSA-qh8g-58pp-2wxh says:

> The impact of this vulnerability is limited to developers that use the Jetty `HttpURI` directly.

Dropwizard is not doing this.

```
❯ git grep 'HttpURI' v4.0.11 
v4.0.11:dropwizard-request-logging/src/test/java/io/dropwizard/request/logging/old/DropwizardSlf4jRequestLogWriterTest.java:import org.eclipse.jetty.http.HttpURI;
v4.0.11:dropwizard-request-logging/src/test/java/io/dropwizard/request/logging/old/DropwizardSlf4jRequestLogWriterTest.java:        when(request.getHttpURI()).thenReturn(HttpURI.from("/test/things?yay"));
```

> Please make sure support for 12.0.12 jetty in dropwizard 4.x.x and 3.x.x if its possible

That's not possible. If you want to use Jetty 12.x, please upgrade to Dropwizard 5.x.
The latest release in that branch is https://github.com/dropwizard/dropwizard/releases/tag/v5.0.0-alpha.5.
