### ISSUE TITLE
Unable to use ResourceTestRule with individual unit tests

### ISSUE THREAD

**Issue by r0goyal** [dropwizard/dropwizard#970]
I am using DW 0.8.0.

I am trying to test my resources by creating an instance of ResourceTestRule in setUp() method of my unit test in the following way - 
```java

@Rule
private ResourceTestRule testRule;

@Before
public void setUp() throws Exception {
    testRule = ResourceTestRule.builder().setMapper(objectMapper).build();
} 
```
However whenever I call testRule.client() after executing above code, I am getting NullPointerException. This is due to the fact that JerseyTest instance variable is not getting initialized.

However JerseyTest is getting initialized when I am using static variable with ClassRule annotation - 

```java
@ClassRule
public static ResourceTestRule testRule;

static {
    testRule = ResourceTestRule.builder().setMapper(objectMapper).build();
}
```

Am I missing something ? Is there any initialization step which is a prerequisite for running tests ?

**Comment by carlo-rtr** [comment]
I think you can use @Rule but do the init inline instead of in @Before. This worked when I modified an existing test with ```@ClassRule```.

https://github.com/junit-team/junit/wiki/Rules
