### ISSUE TITLE
Provide a way to customize the request logging

### ISSUE THREAD

**Issue by carlo-rtr** [dropwizard/dropwizard#972]

**Comment by carlo-rtr** [comment]
I think we would have to make ```RequestLogFactory``` behave similar to the hierarchy of ```ServerFactory```, ```DefaultServerFactory``` and ```SimpleServerFactory```. This would allow you to provide your own impl of RequestLogFactory by specifying the type in the configuration and including the class at runtime. The framework would have to find it via the java provider mechanism ("META-INF.service") like this:

https://github.com/dropwizard/dropwizard/tree/master/dropwizard-core/src/main/resources/META-INF/services

**Comment by ayushvora** [comment]
Hey, so is this gonna solve the problem where, if `timeZone` is specified within an appender, it's rejected and the `timeZone` attribute directly under the `requestLog` attribute is picked up instead?
I see @reines spoke about this in #580:
> if the user specified a timezone and a log format, the timezone would be totally ignored.

Some of us dropwizard users here ran into this issue and we thought of asking about it because the behaviour seemed little surprising.

**Comment by carlo-rtr** [comment]
@ayushvora it wouldn't change the default situation, but it would mean that someone could override and do as they please.

Looking at the code, ```RequestLoggerFactory``` has a timeZone property which is used for ```Slf4jRequestLog```. In mind it makes sense to use that timeZone instead of that one at the appender level. What would happen if you had multiple appenders with different timezones, it wouldn't know which to pick.

**Comment by ayushvora** [comment]
Are we then bound by _Jetty_'s interface? Do we have to add multiple handlers in that case (as many as no. of appenders)? What's being planned?

**Comment by arteam** [comment]
This functionality was contributed in 05d3fcd
