### ISSUE TITLE
Upgrade to Jackson 2.5.2

### ISSUE THREAD

**Issue by cowtowncoder** [dropwizard/dropwizard#973]
The latest patch version from 2.5 is 2.5.2, so it would make sense to upgrade from 2.5.1.
Changes are listed here:

https://github.com/FasterXML/jackson/wiki/Jackson-Release-2.5.2

If necessary, I can create a PR, but since this is a one-liner I thought I'll just file an issue first. If you prefer PR, just let me know.

**Comment by arteam** [comment]
Sorry for unnecessary stir.
It didn't happen to be an one-line change, because the maven-enforcer plugin wasn't happy and I had to manually exclude some dependencies.

Anyway, thanks, Tatu, for reminding us to upgrade. Keep up the good work!

**Comment by cowtowncoder** [comment]
Ah. Right, I actually noticed that after filing issue, local build failing. Thank you for sorting it through!

I'll try to send updates here more often since I do Jackson upgrades, it should be easy enough for me to run tests locally and submit patches too.
