### ISSUE TITLE
AsyncResponse.resume(Throwable) does not trigger ExceptionMapper

### ISSUE THREAD

**Issue by arthurtsang** [dropwizard/dropwizard#974]
i have the following API
```
@Timed
@Path("{id}")
@DELETE
public void delete(@Suspended final AsyncResponse asyncResponse, @PathParam("id") String id ){
...
asyncResponse.resume( new NoSuchElementException("can't find id") );
}
```
and exception mapper
```
@Provider
@Singleton
public class NoSuchElementExceptionMapper implements ExceptionMapper<NoSuchElementException>{
    @Override
    public Response toResponse(NoSuchElementException exception) {
        return ErrorResponse.status(404).throwable(exception).build();
    }
}
```
and registered it at a ConfiguredBundle's run method
```
@Override
    public void run(SearchConfiguration searchConfiguration, Environment environment) throws Exception {
...
        environment.jersey().register(new NoSuchElementExceptionMapper());
    }
```
the exception mapper was never triggered.  however, if i throw the exception directly in the API method, it works.

**Comment by arteam** [comment]
* Could you try to wrap your exception into [MappableException](https://github.com/jersey/jersey/blob/master/core-server/src/main/java/org/glassfish/jersey/server/internal/process/MappableException.java)?
* If this doesn't work, you could try to register an exception mapper as [ResponseErrorMapper](https://github.com/jersey/jersey/blob/master/core-server/src/main/java/org/glassfish/jersey/server/spi/ResponseErrorMapper.java)

Response error mappers are not processed by default, so you need to enable this feature in the configuration:
````java
environment.jersey().property(ServerProperties.PROCESSING_RESPONSE_ERRORS_ENABLED, true);

**Comment by arthurtsang** [comment]
Thanks.  turns out it's my own fault.  resume(Throwable) does work fine with ExceptionMapper.  Sorry for that.

**Comment by leandroandrade** [comment]
You can do that: 

`
@Resource
ManagedExecutorService mes;

@GET
	@Path("{uuid}")
	public void byId(@Suspended AsyncResponse response, @PathParam("uuid") String uuid) {
		supplyAsync(() -> this.service.byId(uuid), mes)
				.whenComplete((result, error) -> Optional.ofNullable(error)
						.ifPresent(erro -> response.resume(erro.getCause())))
				.thenAccept(response::resume);
	}`

The method erro.getCause() will call the exceptionMapper defined.
