### ISSUE TITLE
line number not printing for "logFormat" in v0.8

### ISSUE THREAD

**Issue by shivangshah** [dropwizard/dropwizard#975]
Hi, 
I have the following log format in my yml
```
logFormat: "[%date{dd MMM yyyy;HH:mm:ss.SSS,UTC}] - [%-5level] [%logger{0}:%line] - %msg %ex{full}%n"
```
For some reason it does not print the %line .. the output comes out to something like this: 

```
[07 Apr 2015;21:39:38.377] - [WARN ] [CacheBuilder ?] - ignoring weigher specified without maximumWeight 
[07 Apr 2015;21:39:38.406] - [WARN ] [CacheBuilder ?] - ignoring weigher specified without maximumWeight 
```
I also tried with %L per logback documentation, but still no luck

It gives a "?" instead of the line number. This log format used to work fine with v 0.7.1

All help appreciated !

EDIT: 

I tested the exact same thing with another standalone project using logback.xml and it worked just fine:
```
<appender name="CONSOLE" class="ch.qos.logback.core.ConsoleAppender">
        <encoder class="ch.qos.logback.classic.encoder.PatternLayoutEncoder">
            <pattern>[%date{dd MMM yyyy;HH:mm:ss.SSS,UTC}] - %level [%logger{0}:%line] - %msg%n%ex{1}</pattern>
        </encoder>
    </appender>
```

**Comment by carlo-rtr** [comment]
Not sure, you should follow up with logback folks.

https://groups.google.com/forum/#!searchin/dropwizard-user/log$20pattern$20line/dropwizard-user/DpLMTscoZOY/KD6jB5BzjOIJ

**Comment by shivangshah** [comment]
@carlo-rtr logback seems to be working just fine because we have another stand alone project with logback.xml with the exact same logformat and it prints line numbers just fine. Matter of fact it even works with v0.7.1 of dropwizard. Did the logback version change with v0.8?

**Comment by carlo-rtr** [comment]
Really? I can't reproduce that. https://github.com/carlo-rtr/dropwizard/commits/version7

This is version 0.7.1 with the log formats I tried. If you run the example app, the log line still shows up with a question mark

**Comment by shivangshah** [comment]
@carlo-rtr I am sorry .. I can replicate this problem with 0.7.1 as well on my local env but not in our production .. probably got to do something with mismatch of logback jars?  .. Also, I mentioned in the original question that doing the exact same pattern with logback-test.xml in the same project and running tests prints the line numbers just fine .. So I am literally in the dark as to where I should start my debugging with .. because with standalone logback it looks just fine but with dropwizard it doesn't .. Any other pointers that you can share in regards to this? I am pretty sure logback community would bring me back here to talk to you guys.

**Comment by carlo-rtr** [comment]
You can take a look at LoggingFactory in our source code, that's how the logging is configured. You can try and see what differs with that code and when your logback.xml is consumed.

**Comment by shivangshah** [comment]
got it ... I will try it out ..

**Comment by shivangshah** [comment]
@carlo-rtr : So I dig deep inside the code and although I didn't get a chance to actually fork the project and give it a try to change the code myself, I think I might have found the problem. 
In v0.8 AbstractAppenderFactory : https://github.com/dropwizard/dropwizard/blob/master/dropwizard-logging/src/main/java/io/dropwizard/logging/AbstractAppenderFactory.java#L112
I have a feeling that the "includeCallerData" should be set to "true" before you add the appender. I was able to come to that conclusion of using the "includeCallerData" from here : http://stackoverflow.com/questions/13944641/logback-ayncappender-not-printing-file-and-line-number
And it makes sense too. Because being async, if you don't have calller data, you won't get the line #
Let me know what you think .. If I get time, I will go ahead and fork out the project and try this change myself. If you get a chance to test this change out, greatly appreciated !

**Comment by saadmufti** [comment]
This can be expensive and should not be the default IMHO. If required we
should make it configurable.

---
Saad

**Comment by carlo-rtr** [comment]
That works. Ill submit a PR to make it configurable

**Comment by shivangshah** [comment]
@saadmufti Agreed @carlo-rtr Thank you! Can you let me know the Request # so I can subscribe to it .. possibly even know when it will be getting released ?

**Comment by carlo-rtr** [comment]
https://github.com/dropwizard/dropwizard/pull/995

It will be in the next release, we don't have a timeline yet. If I had to ballpark, I would say 2 months.
