### ISSUE TITLE
The case of the empty string Optional in QueryParam

### ISSUE THREAD

**Issue by nickbabcock** [dropwizard/dropwizard#983]
Taking a look at the [getting started page]

```java
@GET
@Timed
public Saying sayHello(@QueryParam("name") Optional<String> name) {
    final String value = String.format(template, name.or(defaultName));
    return new Saying(counter.incrementAndGet(), value);
}
```

The url `http://localhost:8080/hello-world?name=` will return "Hello, !".

I'm unsure how I feel about this behavior. The person I was walking through
the tutorial expressed concern that it failed the principle of least
astonishment because to him `name` is blank -- thus absent, and should result
in a return of "Hello, Stranger!"

A workaround had to be coded:

```java
@GET
@Timed
public Saying sayHello(@QueryParam("name") Optional<String> name) {
    String output = name.or(defaultName);
    if (Strings.isNullOrEmpty(output)) {
        output = defaultName;
    }

    final String value = String.format(template, output);
    return new Saying(counter.incrementAndGet(), value);
}
```

This seems to defeat the purpose of optional. I think it would be reasonable
to change the behavior of `Optional` so that a blank query parameter is
absent, even though `Optional.of("")` is completely valid.

An argument against changing the code is that it would be a breaking change.
People may have come to rely on blank query params meaning a non-absent
optional. Another argument is that the [spec defines] the query as

> either null or a string holding data

Is `name=` null or is it holding empty data?

If the change is wanted, an open question is what constitues a blank query
param? Is it just a length of 0 (my bias), or can blank query param can
contain all whitespace

EDIT: If the change is not wanted, there probably should be documentation informing that `Optional` can be blank.

[getting started page]: http://www.dropwizard.io/getting-started.html#creating-a-resource-class
[spec defines]: https://url.spec.whatwg.org/#concept-url-query

**Comment by arteam** [comment]
Handling empty query parameteres as optional values sounds reasonably to me.
I don't think backwards compatability is a big issue, because I can't imagine anyone who deri

**Comment by nickbabcock** [comment]
No problem, though I may have just beat you to the patch :smile:

**Comment by arteam** [comment]
No worries. I would merge it now, but I want to hear what others maintaniers have to say.

**Comment by nickbabcock** [comment]
Absolutely, no need to rush this.

**Comment by jplock** [comment]
I think this sounds ok to me.   This wouldn't break anything in any of my applications for instance.
