### ISSUE TITLE
Getting Started Guide does not mention that the example.keystore is required

### ISSUE THREAD

**Issue by chaitrasuresh** [dropwizard/dropwizard#988]
The documentation here - http://dropwizard.github.io/dropwizard/getting-started.html, does not mention that you need the `example.keystore` (Found at - https://github.com/dropwizard/dropwizard/blob/master/dropwizard-example/example.keystore) in order to run the application you built.

Also, the `database` and the `viewRendererConfiguration` sections had to be commented out before I could run the application. When I had these sections, I got the following error - 

 ` * Unrecognized field at: viewRendererConfiguration
    Did you mean?:
      - defaultName
      - server
      - metrics
      - template
      - logging`

**Comment by arteam** [comment]
[example.yml](https://github.com/dropwizard/dropwizard/blob/master/dropwizard-example/example.yml) is the configuration of the [dropwizard-example](https://github.com/dropwizard/dropwizard/tree/master/dropwizard-example) application, which demonstrates different features of Dropwizard. Along with others it's HTTPS, database access and view templates configuration. So this file is not a drop-in replacement for the configuration of a new project.

Actually, for `Getting Started ` you don't need anything apart from the provided YAML file.
````yaml
template: Hello, %s!
defaultName: Stranger
````
