### ISSUE TITLE
Specifying the LogBack maxFileSize parameter to limit logfile

### ISSUE THREAD

**Issue by ckingsbu** [dropwizard/dropwizard#997]
We have a requirement at my firm to limit the logfile sizes for our production deployments.   Logback has a maxFileSize parameter than can be specified when using the ch.qos.logback.core.rolling.SizeAndTimeBasedFNATP trigger policy. I took a look in the code, and couldn't find any obvious way to enable this feature.   Any objections to me adding the maxFileSize parameter and submitting a pull request?

**Comment by carlo-rtr** [comment]
This seems useful. We welcome a PR.

**Comment by ckingsbu** [comment]
Thanks, I've submitted a pull request for this here:  https://github.com/dropwizard/dropwizard/pull/1000

**Comment by akshaymaniyar** [comment]
Hey just wanted to know one thing, how will archivedFileCount work here. Will it ensure that a maximin of 7 files are only maintained? Or will it maintain the files for the last 7 days?
